import assert from 'node:assert/strict';
import {DocumentEngine,DOCUMENT_ENGINE_VERSION} from '../assets/js/document-engine.js';
const engine=new DocumentEngine({documentTitle:'Relatório',bullets:['Revisar prazo até 20/08'],filename:'relatorio.pdf'});
assert.equal(DOCUMENT_ENGINE_VERSION,1);
assert.equal(engine.state.view,'drive');
assert.equal(engine.visibleFiles().length,3);
assert.equal(engine.applyAction('open-drive-file').ok,true);
engine.selectBlock('title');assert.equal(engine.applyAction('title-style').ok,true);
engine.selectBlock('deadline');assert.equal(engine.applyAction('bold-deadline').ok,true);
engine.selectBlock('bullets');assert.equal(engine.applyAction('insert-list').ok,true);
assert.equal(engine.applyAction('add-comment',{text:'Revisar prazo'}).ok,true);
assert.equal(engine.document.comments.length,1);
assert.equal(engine.applyAction('save-version',{label:'Versão revisada'}).ok,true);
assert.equal(engine.document.versions.length,2);
assert.equal(engine.applyAction('permission-commenter',{email:'supervisao@simulacao.edu.br'}).ok,true);
assert.equal(engine.document.share.people[0].permission,'commenter');
assert.equal(engine.applyAction('export-pdf',{settings:{orientation:'landscape'}}).ok,true);
assert.equal(engine.document.pdfReady,true);
assert.equal(engine.document.exportSettings.orientation,'landscape');
const restored=new DocumentEngine({},engine.serialize());
assert.equal(restored.document.comments.length,1);
assert.equal(restored.document.pdfReady,true);
console.log('document-engine: ok');
