'use strict';
(function(){
  window.LABDS_LABS=window.LABDS_LABS||{};const KEY='lab.traffic.state';let root,ctx,state,timer=null;
  const $=s=>root.querySelector(s),$$=s=>[...root.querySelectorAll(s)],clamp=(n,a,b)=>Math.min(b,Math.max(a,Number(n)||0));
  function defaults(){return{tab:'radar',radar:{distance:20,time:.8,limit:40,type:'fixo',records:[]},signal:{phase:'NS-green',elapsed:0,durations:{green:8,yellow:3,allRed:2},running:false,pedestrian:false,emergency:false,cycles:0,collisions:0}};}
  function speed(){return state.radar.distance/state.radar.time*3.6;}
  function render(){root.innerHTML=`<div class="traffic-lab"><header><div><span class="eyebrow">AUTOMAÇÃO E CÁLCULO</span><h2>Radar e trânsito inteligente</h2></div><nav><button data-traffic-tab="radar" class="${state.tab==='radar'?'active':''}">Radar</button><button data-traffic-tab="signal" class="${state.tab==='signal'?'active':''}">Semáforo</button></nav></header><main id="trafficMain"></main></div>`;$$('[data-traffic-tab]').forEach(button=>button.onclick=()=>{state.tab=button.dataset.trafficTab;ctx.storage.set(KEY,state);render();});state.tab==='radar'?renderRadar():renderSignal();}
  function renderRadar(){const v=speed(),over=v-state.radar.limit,main=$('#trafficMain');main.innerHTML=`<section class="radar-layout"><div class="radar-road"><div class="radar-beam"></div><div class="radar-car" style="animation-duration:${clamp(4-v/30,1,4)}s">🚗</div><div class="speed-sign">${state.radar.limit}</div></div><aside class="radar-controls"><label>Distância medida (m)<input id="radarDistance" type="number" min="1" max="500" step=".1" value="${state.radar.distance}"></label><label>Tempo (s)<input id="radarTime" type="number" min=".05" max="30" step=".01" value="${state.radar.time}"></label><label>Limite (km/h)<input id="radarLimit" type="number" min="10" max="130" value="${state.radar.limit}"></label><label>Tipo<select id="radarType"><option value="fixo">Radar fixo</option><option value="movel">Radar móvel</option><option value="trecho">Média por trecho</option></select></label><button id="radarMeasure" class="btn primary">Registrar medição</button><div class="radar-result ${over>0?'over':'ok'}"><b>${v.toFixed(1)} km/h</b><span>${over>0?`${over.toFixed(1)} km/h acima do limite`:'Dentro do limite'}</span></div></aside><div class="radar-table"><h3>Registros fictícios</h3><table><thead><tr><th>Horário</th><th>Velocidade</th><th>Limite</th><th>Situação</th></tr></thead><tbody>${state.radar.records.slice(-12).reverse().map(r=>`<tr><td>${new Date(r.at).toLocaleTimeString('pt-BR')}</td><td>${r.speed.toFixed(1)}</td><td>${r.limit}</td><td>${r.speed>r.limit?'Acima':'Regular'}</td></tr>`).join('')||'<tr><td colspan="4">Nenhum registro.</td></tr>'}</tbody></table></div></section>`;$('#radarType').value=state.radar.type;['Distance','Time','Limit'].forEach(key=>$('#radar'+key).oninput=()=>{state.radar[key.toLowerCase()]=Number($('#radar'+key).value);ctx.storage.set(KEY,state);renderRadar();});$('#radarType').onchange=()=>{state.radar.type=$('#radarType').value;ctx.storage.set(KEY,state);};$('#radarMeasure').onclick=()=>{state.radar.records.push({at:new Date().toISOString(),speed:v,limit:state.radar.limit,type:state.radar.type});state.radar.records=state.radar.records.slice(-100);ctx.storage.set(KEY,state);if(Math.abs(v-state.radar.limit)<2)ctx.core?.complete?.('traffic:radar-precision',{xp:45,credits:15,reason:'Cálculo de velocidade preciso'});renderRadar();};}
  function signalLights(){const p=state.signal.phase;return{ns:p==='NS-green'?'green':p==='NS-yellow'?'yellow':'red',ew:p==='EW-green'?'green':p==='EW-yellow'?'yellow':'red'};}
  function renderSignal(){const lights=signalLights(),s=state.signal,main=$('#trafficMain');main.innerHTML=`<section class="signal-layout"><div class="intersection"><div class="road vertical"></div><div class="road horizontal"></div><div class="traffic-light ns"><i class="${lights.ns==='red'?'on':''}"></i><i class="yellow ${lights.ns==='yellow'?'on':''}"></i><i class="green ${lights.ns==='green'?'on':''}"></i><span>N/S</span></div><div class="traffic-light ew"><i class="${lights.ew==='red'?'on':''}"></i><i class="yellow ${lights.ew==='yellow'?'on':''}"></i><i class="green ${lights.ew==='green'?'on':''}"></i><span>L/O</span></div><div class="vehicle ns-car ${lights.ns==='green'?'moving':''}">🚙</div><div class="vehicle ew-car ${lights.ew==='green'?'moving':''}">🚕</div><div class="pedestrian ${s.pedestrian?'waiting':''}">🚶</div></div><aside><h3>Controlador lógico</h3><label>Verde (s)<input id="signalGreen" type="number" min="3" max="60" value="${s.durations.green}"></label><label>Amarelo (s)<input id="signalYellow" type="number" min="2" max="8" value="${s.durations.yellow}"></label><label>Todos vermelhos (s)<input id="signalAllRed" type="number" min="1" max="8" value="${s.durations.allRed}"></label><div class="signal-actions"><button id="signalToggle" class="btn primary">${s.running?'Pausar':'Iniciar'}</button><button id="pedestrianRequest">Solicitar pedestre</button><button id="emergencyRequest">Prioridade de emergência</button><button id="signalReset">Reiniciar</button></div><dl><dt>Fase</dt><dd id="signalPhase">${s.phase}</dd><dt>Tempo</dt><dd id="signalElapsed">${s.elapsed}s</dd><dt>Ciclos</dt><dd>${s.cycles}</dd><dt>Conflitos</dt><dd>${s.collisions}</dd></dl><button id="validateSignal" class="btn secondary">Validar programação</button></aside></section>`;['Green','Yellow','AllRed'].forEach(key=>$('#signal'+key).onchange=()=>{const map={Green:'green',Yellow:'yellow',AllRed:'allRed'};s.durations[map[key]]=Number($('#signal'+key).value);ctx.storage.set(KEY,state);});$('#signalToggle').onclick=()=>{s.running=!s.running;s.running?startTimer():stopTimer();renderSignal();};$('#pedestrianRequest').onclick=()=>{s.pedestrian=true;ctx.toast('Pedido registrado. O pedestre será atendido na fase segura.','info');ctx.storage.set(KEY,state);};$('#emergencyRequest').onclick=()=>{s.emergency=true;ctx.toast('Prioridade de emergência ativada para o próximo eixo.','warning');ctx.storage.set(KEY,state);};$('#signalReset').onclick=()=>{stopTimer();state.signal=defaults().signal;ctx.storage.set(KEY,state);renderSignal();};$('#validateSignal').onclick=()=>{const ok=s.durations.yellow>=3&&s.durations.allRed>=1&&s.cycles>=1&&s.collisions===0;if(ok){ctx.core?.complete?.('traffic:signal-safe',{xp:70,credits:25,reason:'Semáforo seguro programado'});ctx.toast('Programação validada.','success');}else ctx.toast('Execute um ciclo completo, mantenha amarelo ≥ 3 s e todos vermelhos ≥ 1 s.','warning');};}
  function nextPhase(){const s=state.signal,sequence=['NS-green','NS-yellow','all-red-1','EW-green','EW-yellow','all-red-2'],index=sequence.indexOf(s.phase),next=sequence[(index+1)%sequence.length];s.phase=next;s.elapsed=0;if(next==='NS-green'&&index===sequence.length-1)s.cycles++;if(next.startsWith('all-red')&&s.pedestrian){s.pedestrian=false;ctx.toast('Travessia de pedestre liberada na fase segura.','success');}if(s.emergency&&next.startsWith('all-red')){s.emergency=false;s.phase=next==='all-red-1'?'EW-green':'NS-green';}}
  function phaseDuration(){const s=state.signal;return s.phase.includes('green')?s.durations.green:s.phase.includes('yellow')?s.durations.yellow:s.durations.allRed;}
  function startTimer(){stopTimer();timer=setInterval(()=>{const s=state.signal;if(!s.running)return;s.elapsed++;if(s.elapsed>=phaseDuration())nextPhase();ctx.storage.set(KEY,state);if(root&&state.tab==='signal')renderSignal();},1000);}
  function stopTimer(){clearInterval(timer);timer=null;}
  async function mount(host,context){root=host;ctx=context;state={...defaults(),...(await ctx.storage.get(KEY,{})),radar:{...defaults().radar,...((await ctx.storage.get(KEY,{}))?.radar||{})},signal:{...defaults().signal,...((await ctx.storage.get(KEY,{}))?.signal||{}),durations:{...defaults().signal.durations,...((await ctx.storage.get(KEY,{}))?.signal?.durations||{})}}};render();if(state.signal.running)startTimer();}
  async function unmount(){stopTimer();await ctx?.storage?.set?.(KEY,state);root=null;ctx=null;}
  function exportPayload(){return{text:`TRÂNSITO\nMedições: ${state.radar.records.length}\nCiclos: ${state.signal.cycles}`,native:JSON.stringify(state,null,2),backup:state};}
  function help(){return'<p>No radar, velocidade = distância ÷ tempo. No semáforo, cada eixo deve receber verde, amarelo e uma fase de segurança com todos vermelhos.</p>';}
  window.LABDS_LABS['traffic-lab']={mount,unmount,exportPayload,help};
})();
