'use strict';
(function(){
  window.LABDS_LABS=window.LABDS_LABS||{};
  const KEY='lab.fintech.state';
  const DEFAULT={balance:2450.75,transactions:[],xp:0,tab:'pix'};
  let root,ctx,state,timer=0;
  const money=value=>Number(value||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
  const safe=value=>String(value||'').replace(/[<>]/g,'').slice(0,80);
  async function digest(text){const bytes=new TextEncoder().encode(text);const hash=await crypto.subtle.digest('SHA-256',bytes);return [...new Uint8Array(hash)].map(b=>b.toString(16).padStart(2,'0')).join('');}
  async function save(){await ctx.storage.set(KEY,state);}
  function receipt(tx){return [`PIX EDUCACIONAL`, `ID: ${tx.id}`, `Valor: ${money(tx.amount)}`, `Destino: ${tx.key}`, `Status: ${tx.status}`, `Autenticação: ${tx.auth}`, `Horário: ${new Date(tx.at).toLocaleString('pt-BR')}`].join('\n');}
  function drawQR(canvas,seed){const c=canvas.getContext('2d'),size=21,cell=Math.floor(canvas.width/size);c.fillStyle='#fff';c.fillRect(0,0,canvas.width,canvas.height);let n=0;for(const ch of seed)n=(n*31+ch.charCodeAt(0))>>>0;const rnd=()=>((n=Math.imul(1664525,n)+1013904223>>>0)/4294967296);for(let y=0;y<size;y++)for(let x=0;x<size;x++){const finder=(x<7&&y<7)||(x>13&&y<7)||(x<7&&y>13);const on=finder?((x%6===0||y%6===0)||(x%6>1&&x%6<5&&y%6>1&&y%6<5)):rnd()>.53;if(on){c.fillStyle='#06111d';c.fillRect(x*cell,y*cell,cell,cell);}}}
  function renderHistory(){const box=root.querySelector('#finHistory');box.textContent='';if(!state.transactions.length){box.innerHTML='<p class="muted-copy">Nenhuma transação simulada nesta sessão.</p>';return;}state.transactions.slice().reverse().forEach(tx=>{const item=document.createElement('article');item.className='transaction-row';const left=document.createElement('div');const title=document.createElement('strong');title.textContent=`Pix para ${tx.key}`;const meta=document.createElement('small');meta.textContent=new Date(tx.at).toLocaleString('pt-BR');left.append(title,meta);const value=document.createElement('b');value.textContent=`− ${money(tx.amount)}`;item.append(left,value);box.appendChild(item);});}
  function setTab(tab){state.tab=tab;root.querySelectorAll('[data-fin-tab]').forEach(b=>b.classList.toggle('active',b.dataset.finTab===tab));root.querySelectorAll('[data-fin-panel]').forEach(p=>p.classList.toggle('hidden',p.dataset.finPanel!==tab));save();}
  function animateFlow(nodes,done){clearTimeout(timer);nodes.forEach(n=>n.classList.remove('active'));let i=0;const step=()=>{if(i>0)nodes[i-1].classList.remove('active');if(i>=nodes.length){done?.();return;}nodes[i].classList.add('active');i++;timer=setTimeout(step,620);};step();}
  async function sendPix(){const amount=Number(root.querySelector('#pixAmount').value.replace(',','.')),key=safe(root.querySelector('#pixKey').value),pin=root.querySelector('#pixPin').value.trim();const feedback=root.querySelector('#pixFeedback');feedback.className='practice-feedback';if(!key||!Number.isFinite(amount)||amount<=0){feedback.textContent='Informe uma chave fictícia e um valor válido.';feedback.classList.add('error');return;}if(amount>state.balance){feedback.textContent='Saldo fictício insuficiente. O sistema recusou antes da liquidação.';feedback.classList.add('error');return;}if(!/^\d{4}$/.test(pin)){feedback.textContent='Use o PIN fictício de quatro números para simular a autenticação.';feedback.classList.add('error');return;}const nodes=[...root.querySelectorAll('#pixFlow .flow-node')];feedback.textContent='Autenticando e enviando a ordem...';animateFlow(nodes,async()=>{const at=Date.now(),id=(await digest(`${key}|${amount}|${at}`)).slice(0,16).toUpperCase();const risk=amount>1800?'revisão automática':'baixo';const tx={id,amount,key,status:'LIQUIDADO',auth:'PIN + dispositivo',risk,at};state.balance-=amount;state.transactions.push(tx);state.xp+=25;await save();root.querySelector('#finBalance').textContent=money(state.balance);root.querySelector('#finXp').textContent=state.xp;feedback.className='practice-feedback success';feedback.textContent=`Pix fictício concluído. Risco ${risk}; ID ${id}.`;root.querySelector('#receiptOutput').textContent=receipt(tx);drawQR(root.querySelector('#pixQr'),id);renderHistory();ctx.logEvent({eventType:'fintech',action:'Pix educacional concluído',status:'success',details:{amount,risk}});});}
  function atmAction(action){const output=root.querySelector('#atmOutput');const amount=Number(root.querySelector('#atmAmount').value);if(action==='balance'){output.textContent=`Saldo disponível: ${money(state.balance)}\nNenhum dado real foi consultado.`;return;}if(!Number.isFinite(amount)||amount<=0){output.textContent='Digite um valor fictício válido.';return;}if(action==='withdraw'){if(amount>state.balance){output.textContent='Operação recusada: saldo insuficiente.';return;}state.balance-=amount;output.textContent=`Notas simuladas liberadas: ${money(amount)}\nSaldo restante: ${money(state.balance)}`;}else{state.balance+=amount;output.textContent=`Depósito fictício processado: ${money(amount)}\nNovo saldo: ${money(state.balance)}`;}root.querySelector('#finBalance').textContent=money(state.balance);state.xp+=10;root.querySelector('#finXp').textContent=state.xp;save();}
  function render(){root.innerHTML=`<div class="immersive-lab fintech-lab"><header class="immersive-hero"><div><span class="eyebrow">FINTECH • DADOS FICTÍCIOS</span><h2>Banco, caixa eletrônico e Pix</h2><p>Veja como autenticação, antifraude, mensageria, liquidação e comprovante se conectam em uma transação digital.</p></div><div class="immersive-badges"><span>Saldo fictício <b id="finBalance">${money(state.balance)}</b></span><span>XP <b id="finXp">${state.xp}</b></span><span>Sem dinheiro real</span></div></header><nav class="module-tabs"><button data-fin-tab="pix">Pix</button><button data-fin-tab="atm">Caixa eletrônico</button><button data-fin-tab="security">Segurança</button><button data-fin-tab="history">Histórico</button></nav>
    <section data-fin-panel="pix" class="immersive-grid"><article class="immersive-card"><h3>Nova transferência fictícia</h3><label>Chave Pix<input id="pixKey" maxlength="80" placeholder="aluno@exemplo.local"></label><label>Valor (R$)<input id="pixAmount" type="number" min="0.01" step="0.01" value="25.00"></label><label>PIN fictício<input id="pixPin" inputmode="numeric" maxlength="4" placeholder="1234"></label><button id="sendPix" class="btn primary" type="button">Simular Pix</button><div id="pixFeedback" class="practice-feedback"></div><div class="knowledge-card"><strong>O que acontece na vida real?</strong> O aplicativo autentica, avalia risco, envia a ordem ao participante financeiro e recebe a confirmação de liquidação. Este laboratório não se conecta a bancos.</div></article><article class="immersive-card"><h3>Fluxo da transação</h3><div id="pixFlow" class="flow-track"><div class="flow-node">Aplicativo<br><small>autenticação</small></div><span class="flow-arrow">›</span><div class="flow-node">Antifraude<br><small>regras e risco</small></div><span class="flow-arrow">›</span><div class="flow-node">Participante<br><small>mensagem</small></div><span class="flow-arrow">›</span><div class="flow-node">Liquidação<br><small>confirmação</small></div><span class="flow-arrow">›</span><div class="flow-node">Comprovante<br><small>ID e horário</small></div></div><div class="receipt-grid"><pre id="receiptOutput" class="terminal-mini">O comprovante aparecerá aqui.</pre><canvas id="pixQr" width="210" height="210" aria-label="QR ilustrativo, sem valor bancário"></canvas></div></article></section>
    <section data-fin-panel="atm" class="immersive-grid hidden"><article class="immersive-card atm-machine"><h3>Caixa eletrônico educacional</h3><div class="atm-screen"><b>LAB BANK</b><p>Escolha uma operação. Nenhuma conta real é acessada.</p><input id="atmAmount" type="number" min="1" value="50"></div><div class="button-row"><button data-atm="balance" class="btn secondary">Consultar saldo</button><button data-atm="withdraw" class="btn primary">Sacar</button><button data-atm="deposit" class="btn secondary">Depositar</button></div></article><article class="immersive-card"><h3>Log da máquina</h3><pre id="atmOutput" class="terminal-mini">ATM inicializado. Dispositivos: leitor, teclado, dispensador e impressora simulados.</pre><div class="metric-row"><div class="metric-card"><small>Leitor</small><strong>OK</strong></div><div class="metric-card"><small>Criptografia</small><strong>TLS conceitual</strong></div><div class="metric-card"><small>Notas</small><strong>Simuladas</strong></div></div></article></section>
    <section data-fin-panel="security" class="immersive-grid hidden"><article class="immersive-card"><h3>Camadas de segurança</h3><ol class="security-stack"><li><b>Identidade</b><span>PIN, biometria ou dispositivo cadastrado.</span></li><li><b>Canal protegido</b><span>Dados trafegam em conexão criptografada.</span></li><li><b>Antifraude</b><span>Valor, horário, dispositivo e padrão de uso são avaliados.</span></li><li><b>Integridade</b><span>Identificadores e assinaturas ajudam a detectar alterações.</span></li><li><b>Auditoria</b><span>Eventos são registrados para investigação e suporte.</span></li></ol></article><article class="immersive-card"><h3>Teste de decisão</h3><p>Qual situação exige análise adicional?</p><div class="decision-grid"><button data-risk="low">R$ 12,00 no dispositivo habitual</button><button data-risk="high">R$ 4.900,00 em dispositivo novo, de madrugada</button><button data-risk="medium">R$ 70,00 para contato frequente</button></div><div id="riskFeedback" class="practice-feedback"></div></article></section>
    <section data-fin-panel="history" class="immersive-card hidden"><h3>Transações desta simulação</h3><div id="finHistory" class="transaction-list"></div></section></div>`;
    root.querySelectorAll('[data-fin-tab]').forEach(b=>b.addEventListener('click',()=>setTab(b.dataset.finTab)));root.querySelector('#sendPix').addEventListener('click',sendPix);root.querySelectorAll('[data-atm]').forEach(b=>b.addEventListener('click',()=>atmAction(b.dataset.atm)));root.querySelectorAll('[data-risk]').forEach(b=>b.addEventListener('click',()=>{const map={low:'Baixo risco: comportamento esperado.',medium:'Risco moderado: pode pedir confirmação.',high:'Alto risco: valor elevado, dispositivo novo e horário incomum.'};const f=root.querySelector('#riskFeedback');f.className=`practice-feedback ${b.dataset.risk==='high'?'success':'error'}`;f.textContent=map[b.dataset.risk];}));drawQR(root.querySelector('#pixQr'),'LAB-PIX-EDUCACIONAL');renderHistory();setTab(state.tab);
  }
  async function mount(host,context){root=host;ctx=context;state={...DEFAULT,...await ctx.storage.get(KEY,DEFAULT)};render();}
  async function unmount(){clearTimeout(timer);await save();root=null;ctx=null;state=null;}
  function exportPayload(){return{text:`FINTECH E PIX\nSaldo fictício: ${money(state.balance)}\nTransações: ${state.transactions.length}\nXP: ${state.xp}`,native:JSON.stringify(state,null,2),backup:state,meta:[{label:'Transações',value:String(state.transactions.length)},{label:'XP',value:String(state.xp)}]};}
  function help(){return'<h3>Fintech e Pix</h3><p>Use apenas dados fictícios. O laboratório demonstra etapas comuns de sistemas financeiros, mas não acessa contas, chaves Pix ou redes bancárias reais.</p>';}
  window.LABDS_LABS['fintech-lab']={mount,unmount,exportPayload,help};
})();
