import { CampaignDirector } from '../../core/campaign/CampaignDirector.js';
import { CampaignCinematicRenderer } from '../../rendering/CampaignCinematicRenderer.js';
import { INTEGRATED_CAMPAIGNS,CAMPAIGN_FAULTS,CAMPAIGN_GOALS } from '../../data/campaignSystems.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
class IntegratedCampaignsModule{
 constructor(){this.host=null;this.context=null;this.director=null;this.renderer=null;this.goals=new Set();this.activeFault=null;this.onClick=e=>this.click(e);}
 mount(host,context){this.host=host;this.context=context;this.director=new CampaignDirector(INTEGRATED_CAMPAIGNS,{storage:globalThis.localStorage,profileId:context.profileStore.active().id});for(const g of CAMPAIGN_GOALS)if(context.profileStore.hasCompleted(`campaign-${g.id}`))this.goals.add(g.id);host.addEventListener('click',this.onClick);this.render();this.start();}
 render(){const s=this.director.snapshot();this.host.innerHTML=`<section class="campaign-module"><div class="campaign-stage"><canvas data-campaign-canvas></canvas><header class="campaign-top immersive-hud"><button data-action="back">←</button><div><span>FASE 22</span><b>CAMPANHAS INTEGRADAS</b></div><button data-action="fullscreen">⛶</button></header><div class="objective-chip immersive-hud"><span>MISSÕES CINEMATOGRÁFICAS</span><b data-campaign-goals>${this.goals.size}/${CAMPAIGN_GOALS.length} objetivos</b></div><nav class="campaign-selector immersive-hud">${INTEGRATED_CAMPAIGNS.map(c=>`<button data-action="start" data-id="${c.id}" class="${s.activeId===c.id?'active':''}"><i>${c.icon}</i><span><b>${esc(c.title)}</b><small>${c.stages.length} etapas · ${c.reward} XP</small></span></button>`).join('')}</nav><aside class="campaign-panel immersive-hud" data-campaign-panel>${this.panelMarkup(s)}</aside><aside class="campaign-radio immersive-hud"><span>COMUNICAÇÃO</span><p data-radio>${s.status==='active'?'Controle de missão pronto. Execute a etapa atual.':'Selecione uma campanha para iniciar.'}</p></aside></div></section>`;}
 start(){this.renderer=new CampaignCinematicRenderer(this.host.querySelector('[data-campaign-canvas]'),this.context.settingsStore);this.renderer.start();this.sync();}
 sync(){const s=this.director.snapshot();if(s.activeId)this.renderer.setCampaign(s.activeId);this.renderer.setProgress(s.campaign?.stages?.length?s.stageIndex/s.campaign.stages.length:0);this.renderer.setEvent(this.activeFault);const p=this.host.querySelector('[data-campaign-panel]');if(p)p.innerHTML=this.panelMarkup(s);this.host.querySelectorAll('[data-action="start"]').forEach(x=>x.classList.toggle('active',x.dataset.id===s.activeId));}
 panelMarkup(s){if(!s.campaign)return`<h2>Escolha uma campanha</h2><p>Conecte lançamento, órbita, superfície, robótica, estação e controle de missão em uma experiência contínua.</p>`;const stage=s.stage;return`<span class="eyebrow">${esc(s.campaign.title)}</span><h2>${s.status==='completed'?'Campanha concluída':esc(stage?.label||'Concluída')}</h2><p>${esc(s.campaign.description)}</p><div class="campaign-progress"><i style="width:${Math.round(s.stageIndex/s.campaign.stages.length*100)}%"></i></div><div class="campaign-stages">${s.campaign.stages.map((x,i)=>`<span class="${i<s.stageIndex?'done':i===s.stageIndex?'active':''}"><i>${i<s.stageIndex?'✓':i+1}</i>${esc(x.label)}</span>`).join('')}</div>${s.status==='active'?`<div class="campaign-actions"><button data-action="open-stage" data-module="${stage.module}">Abrir laboratório</button><button data-action="event">Injetar evento</button><button data-action="complete-stage">Validar etapa</button></div>`:`<div class="campaign-actions"><button data-action="export">Exportar evidência</button><button data-action="restart">Refazer campanha</button></div>`}<small>Pontuação ${s.score} · ${s.completed.length}/${s.campaign.stages.length} checkpoints</small>`;}
 click(e){const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action;if(a==='back')return this.context.onBack();if(a==='fullscreen')return this.renderer.requestFullscreen();if(a==='start'){this.director.start(b.dataset.id);this.complete('start-campaign');this.sync();}if(a==='open-stage'){this.context.openModule?.(b.dataset.module);}if(a==='event'){const fault=CAMPAIGN_FAULTS[Math.floor(Math.random()*CAMPAIGN_FAULTS.length)];this.activeFault=this.director.injectEvent(fault.id,fault.severity);this.renderer.setEvent(this.activeFault);const radio=this.host.querySelector('[data-radio]');if(radio)radio.textContent=`Alerta: ${fault.label}. Procedimento recomendado: ${fault.procedure}.`;setTimeout(()=>{if(this.director.resolveEvent(fault.id,fault.procedure)){this.activeFault={...this.activeFault,resolved:true};this.renderer.setEvent(this.activeFault);this.complete('resolve-event');this.context.toast('Evento resolvido com procedimento correto.');}},800);}if(a==='complete-stage'){const result=this.director.completeStage({quality:1});if(result.ok){if(this.director.snapshot().completed.length>=3)this.complete('complete-three');if(result.status==='completed'){this.complete('complete-campaign');const campaign=this.director.campaign();if(this.context.profileStore.addXp(campaign.reward,`campaign-complete-${campaign.id}`))this.context.toast(`${campaign.title}: +${campaign.reward} XP`);}this.sync();}}if(a==='export')this.export();if(a==='restart'){this.director.start(this.director.activeId);this.sync();}}
 export(){const blob=new Blob([JSON.stringify(this.director.evidence(),null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='cosmos-ds-campanha.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 complete(id){if(this.goals.has(id))return;this.goals.add(id);const g=CAMPAIGN_GOALS.find(x=>x.id===id);if(g&&this.context.profileStore.addXp(g.xp,`campaign-${id}`))this.context.toast(`${g.label}: +${g.xp} XP`);const el=this.host.querySelector('[data-campaign-goals]');if(el)el.textContent=`${this.goals.size}/${CAMPAIGN_GOALS.length} objetivos`;}
 unmount(){this.renderer?.destroy();this.host?.removeEventListener('click',this.onClick);if(this.host)this.host.innerHTML='';}
}
export const createModule=()=>new IntegratedCampaignsModule();
