import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { requireLiveAuthSession } from "./session-guard.ts";
import {createClient} from "jsr:@supabase/supabase-js@2.111.0";
import {consumeRate,ensureAccess,logRisk,requestIp} from "./security.ts";
const H={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"},J=(x:unknown,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{...H,"Content-Type":"application/json"}}),now=()=>new Date().toISOString();
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:H});if(Number(req.headers.get('content-length')||0)>65536)return J({error:'payload_too_large'},413);try{
 const url=Deno.env.get('SUPABASE_URL')!,auth=req.headers.get('Authorization')||'',c=createClient(url,Deno.env.get('SUPABASE_ANON_KEY')!,{global:{headers:{Authorization:auth}}}),db=createClient(url,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,{auth:{persistSession:false,autoRefreshToken:false}}),{data:{user}}=await c.auth.getUser();if(!user)return J({error:'unauthorized'},401);const live=await requireLiveAuthSession(db,auth,user.id);if(!live.ok)return J({error:live.error,detail:live.detail||null},live.status);
 const {data:p}=await db.from('profiles').select('active,must_change_password,role').eq('id',user.id).maybeSingle();if(!p?.active||p.must_change_password||p.role!=='student')return J({error:'student_not_ready'},403);await ensureAccess(db,user,req,'activity-progress');
 const b=await req.json().catch(()=>({})),action=String(b?.action||''),eid=String(b?.exercise_id||'');const rl=await consumeRate(db,`activity-progress:${user.id}:${requestIp(req)||'noip'}`,90,60,120);if(rl.allowed===false){await logRisk(db,user,req,'rate_limit','high',{source:'activity-progress',action,count:rl.count});return new Response(JSON.stringify({error:'rate_limited',retry_after:rl.retry_after||120}),{status:429,headers:{...H,'Content-Type':'application/json','Retry-After':String(rl.retry_after||120)}})};if(!eid)return J({error:'missing_exercise'},400);
 const {data:m}=await db.from('class_memberships').select('class_id').eq('user_id',user.id).eq('active',true).order('is_primary',{ascending:false}).limit(1).maybeSingle();if(!m)return J({error:'no_class'},403);
 const {data:e}=await db.from('exercises').select('id,class_id,subject_id,default_locked,active,visible').eq('id',eid).eq('active',true).eq('visible',true).maybeSingle();if(!e)return J({error:'exercise_forbidden'},403);
 let belongs=false;if(e.class_id)belongs=e.class_id===m.class_id;else{const {data:cs}=await db.from('class_subjects').select('class_id').eq('class_id',m.class_id).eq('subject_id',e.subject_id).eq('active',true).maybeSingle();belongs=!!cs}if(!belongs)return J({error:'exercise_forbidden'},403);
 const {data:progress}=await db.from('student_exercises').select('status,security_locked,security_lock_reason').eq('student_id',user.id).eq('exercise_id',eid).maybeSingle();if(progress?.security_locked||progress?.status==='blocked')return J({error:'activity_locked',reason:progress?.security_lock_reason||'Atividade bloqueada.'},423);
 let released=!e.default_locked;const {data:sr}=await db.from('exercise_releases').select('enabled,release_at,lock_at').eq('student_id',user.id).eq('exercise_id',eid).order('updated_at',{ascending:false}).limit(1).maybeSingle();if(sr)released=sr.enabled&&(!sr.release_at||Date.parse(sr.release_at)<=Date.now())&&(!sr.lock_at||Date.parse(sr.lock_at)>Date.now());else{const {data:cr}=await db.from('exercise_releases').select('enabled,release_at,lock_at').is('student_id',null).eq('class_id',m.class_id).eq('exercise_id',eid).order('updated_at',{ascending:false}).limit(1).maybeSingle();if(cr)released=cr.enabled&&(!cr.release_at||Date.parse(cr.release_at)<=Date.now())&&(!cr.lock_at||Date.parse(cr.lock_at)>Date.now())}if(!released)return J({error:'exercise_locked_by_teacher'},423);
 if(action==='start'){if(!progress){const {error}=await db.from('student_exercises').insert({student_id:user.id,exercise_id:eid,status:'in_progress',progress_percent:0,attempts:0,started_at:now(),last_activity_at:now()});if(error)throw error}else if(progress.status==='not_started')await db.from('student_exercises').update({status:'in_progress',started_at:now(),last_activity_at:now()}).eq('student_id',user.id).eq('exercise_id',eid);return J({ok:true})}
 if(action==='touch'){await db.from('student_exercises').update({last_activity_at:now()}).eq('student_id',user.id).eq('exercise_id',eid);return J({ok:true})}
 if(action==='complete'){const sid=String(b?.session_id||''),{data:s}=await db.from('activity_sessions').select('id,started_at,locked,ended_at').eq('id',sid).eq('student_id',user.id).eq('exercise_id',eid).maybeSingle();if(!s||s.locked||s.ended_at){await logRisk(db,user,req,'completion_without_valid_session','warning',{source:'activity-progress',exercise_id:eid});return J({error:'active_supervised_session_required'},423)}if(Date.now()-Date.parse(s.started_at)<5000){await logRisk(db,user,req,'activity_too_fast','high',{source:'activity-progress',exercise_id:eid});return J({error:'activity_too_fast'},400)};const {data:f}=await db.from('student_files').select('content').eq('student_id',user.id).eq('exercise_id',eid);if(!(f||[]).some(x=>String(x.content||'').trim()))return J({error:'empty_activity'},400);await db.from('student_exercises').update({status:'completed',progress_percent:100,completed_at:now(),last_activity_at:now()}).eq('student_id',user.id).eq('exercise_id',eid);return J({ok:true})}
 return J({error:'unknown_action'},400);
}catch(e){console.error(e);return J({error:'internal_error',detail:String((e as Error)?.message||e)},500)}});
