import { readFile, readdir, stat } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { resolve, dirname, relative } from 'node:path';
const root=resolve(import.meta.dirname,'..');
const required=[
 'index.html','service-worker.js','public/manifest.webmanifest','src/main.js','src/app/CosmosApp.js','src/styles.css',
 'src/rendering/WebGLCosmosRenderer.js','src/rendering/PremiumAssetOverlayRenderer.js','src/rendering/HolographicRadarRenderer.js','src/rendering/EarthGlobeRenderer.js','src/rendering/RocketSceneRenderer.js','src/rendering/LunarSceneRenderer.js','src/rendering/MarsSceneRenderer.js','src/rendering/StationSceneRenderer.js','src/rendering/UniverseSceneRenderer.js','src/rendering/MissionDirectorRenderer.js','src/rendering/SolarSystemSceneRenderer.js','src/rendering/LaunchRemasterSceneRenderer.js','src/rendering/StationRemasterSceneRenderer.js','src/rendering/PlanetaryExplorationRenderer.js','src/rendering/DeepSpaceSceneRenderer.js','src/rendering/SpaceMuseumSceneRenderer.js','src/rendering/PremiumAssetSceneRenderer.js','src/rendering/KnowledgeOrbRenderer.js',
 'src/modules/curiosity-center/CuriosityCenterModule.js','src/core/knowledge/KnowledgeEngine.js','src/core/knowledge/KnowledgeProfileStore.js','src/data/knowledge/spaceKnowledge.js','public/data/knowledge/catalog.json',
 'src/modules/premium-assets/PremiumAssetsModule.js','src/core/assets/PremiumIntegrationOrchestrator.js','src/core/assets/GlbGeometryParser.js','src/core/assets/GlbSceneParser.js','src/core/assets/GltfAnimationPlayer.js','src/core/assets/PremiumColliderSystem.js','src/core/assets/HdrEnvironmentParser.js','src/core/assets/PremiumAssetManager.js','src/core/assets/AssetPackCache.js','src/data/premiumAssetSystems.js','src/data/premiumIntegrationSystems.js','public/assets/premium/manifest.json','src/modules/deep-space-remaster/DeepSpaceRemasterModule.js','src/modules/visual-museum/VisualMuseumModule.js','src/core/deep-space/DeepSpaceNavigationModel.js','src/core/museum-remaster/MuseumExperienceModel.js','src/data/deepSpaceSystems.js','src/data/visualMuseumSystems.js','src/modules/lunar-mars-remaster/LunarMarsRemasterModule.js','src/core/lunar-mars-remaster/PlanetaryExplorationModel.js','src/data/lunarMarsRemasterSystems.js','src/workers/planetary-exploration.worker.js','src/modules/solar-remaster/SolarSystemRemasterModule.js','src/modules/launch-remaster/LaunchRemasterModule.js','src/modules/station-remaster/StationRemasterModule.js','src/core/launch-remaster/LaunchExperienceModel.js','src/data/launchRemasterSystems.js','src/core/station-remaster/OrbitalFlightModel.js','src/core/station-remaster/StationRemasterExperience.js','src/data/stationRemasterSystems.js','src/core/solar/SolarNavigationModel.js','src/core/input/ImmersiveInputController.js','src/data/solarSystemBodies.js','src/modules/academy/AcademyModule.js','src/modules/mission-control/MissionControlModule.js','src/modules/history/HistoryModule.js','src/modules/people/PeopleModule.js','src/modules/languages/LanguagesModule.js','src/modules/mission-control-advanced/MissionControlAdvancedModule.js','src/modules/earth-orbit/EarthOrbitModule.js','src/modules/launch/LaunchModule.js','src/modules/moon-apollo/MoonApolloModule.js','src/modules/mars-robotics/MarsRoboticsModule.js','src/modules/space-station/SpaceStationModule.js','src/modules/observatory/ObservatoryModule.js','src/modules/mission-director/MissionDirectorModule.js',
 'src/core/teacher/MissionPlan.js','src/core/teacher/GuidedSession.js','src/core/teacher/MissionRepository.js','src/core/evidence/EvidenceBuilder.js','src/core/xr/XRSupportService.js','src/core/accessibility/AccessibilityController.js','src/core/backup/ProfileBackupService.js','src/core/persistence/StorageDiagnostics.js','src/data/missionDirectorSystems.js',
 'src/modules/cinematic-studio/CinematicStudioModule.js','src/rendering/CinematicStudioRenderer.js','src/core/rendering/CinematicPostProcessController.js','src/data/cinematicSystems.js',
 'src/modules/physics-controls/PhysicsControlsModule.js','src/rendering/PhysicsArenaRenderer.js','src/core/physics/UnifiedPhysicsController.js','src/data/physicsControlSystems.js',
 'src/modules/integrated-campaigns/IntegratedCampaignsModule.js','src/rendering/CampaignCinematicRenderer.js','src/core/campaign/CampaignDirector.js','src/data/campaignSystems.js',
 'src/modules/performance-qa/PerformanceQAModule.js','src/rendering/QADiagnosticsRenderer.js','src/core/performance/PerformanceBudgetManager.js','src/core/performance/AssetStreamingManager.js','src/data/performanceSystems.js',
 'src/workers/telemetry.worker.js','src/workers/orbital.worker.js','src/workers/launch.worker.js','src/workers/lunar.worker.js','src/workers/mars.worker.js','src/workers/station.worker.js','src/workers/observatory.worker.js','src/workers/orbital-flight.worker.js','scripts/audit-graphics.mjs','.github/workflows/deploy-pages.yml'
];
for(const file of required)if(!existsSync(resolve(root,file)))throw new Error(`Arquivo obrigatório ausente: ${file}`);
async function walk(folder){const files=[];for(const entry of await readdir(folder)){const path=resolve(folder,entry),info=await stat(path);if(info.isDirectory())files.push(...await walk(path));else files.push(path);}return files;}
const jsFiles=(await walk(resolve(root,'src'))).filter(file=>file.endsWith('.js'));
const importPattern=/(?:from\s+|import\()(['"])(\.\.?\/[^'"]+)\1/g;
for(const file of jsFiles){const text=await readFile(file,'utf8');for(const match of text.matchAll(importPattern)){const target=resolve(dirname(file),match[2]);if(!existsSync(target))throw new Error(`Import não encontrado em ${relative(root,file)}: ${match[2]}`);}}
const manifest=JSON.parse(await readFile(resolve(root,'public/manifest.webmanifest'),'utf8'));if(!manifest.name||!manifest.start_url||!manifest.icons?.length)throw new Error('Manifesto PWA incompleto.');
const serviceWorker=await readFile(resolve(root,'service-worker.js'),'utf8');for(const match of serviceWorker.matchAll(/'\.\/([^']+)'/g)){const path=resolve(root,match[1]);if(!existsSync(path)&&!match[1].endsWith('/'))throw new Error(`Service Worker referencia arquivo inexistente: ${match[1]}`);}
const packageJson=JSON.parse(await readFile(resolve(root,'package.json'),'utf8'));if(packageJson.version!=='24.0.0')throw new Error('Versão esperada da C1.1: 24.0.0.');
const registry=await readFile(resolve(root,'src/core/modules/ModuleRegistry.js'),'utf8');const available=(registry.match(/status:'available'/g)||[]).length;if(available!==25)throw new Error(`Esperados 25 módulos disponíveis; encontrados ${available}.`);
const premiumManifest=JSON.parse(await readFile(resolve(root,'public/assets/premium/manifest.json'),'utf8'));
if(premiumManifest.schema!=='cosmos-ds-premium-assets-v2'||premiumManifest.assets?.length!==8)throw new Error('Manifesto premium incompleto.');
for(const asset of premiumManifest.assets){if(asset.lods?.length!==3)throw new Error(`Asset sem três LODs: ${asset.id}`);if(!asset.animations?.length||!asset.parts||!asset.colliders?.length)throw new Error(`Asset sem rig, animações ou colliders: ${asset.id}`);for(const lod of asset.lods)if(!existsSync(resolve(root,lod.url.replace(/^\.\//,''))))throw new Error(`GLB ausente: ${lod.url}`);}
const glbCount=(await walk(resolve(root,'public/assets/premium/models'))).filter(file=>file.endsWith('.glb')).length;if(glbCount!==24)throw new Error(`Esperados 24 arquivos GLB; encontrados ${glbCount}.`);
const integration=await readFile(resolve(root,'src/data/premiumIntegrationSystems.js'),'utf8');for(const id of ['launch-remaster','station-remaster','planetary-remaster','visual-museum'])if(!integration.includes(`'${id}'`))throw new Error(`Integração premium ausente: ${id}`);
const knowledge=await import('../src/data/knowledge/spaceKnowledge.js');if(knowledge.SPACE_KNOWLEDGE.length<20)throw new Error('Catálogo C1.1 deve possuir ao menos 20 itens.');if(Object.keys(knowledge.KNOWLEDGE_SOURCES).length<8)throw new Error('Catálogo C1.1 deve possuir fontes oficiais.');
console.log(`COSMOS DS C1.1 validado: ${jsFiles.length} arquivos JavaScript, ${required.length} arquivos obrigatórios, ${available} módulos e ${knowledge.SPACE_KNOWLEDGE.length} itens de conhecimento offline.`);
