import { PremiumAssetManager } from '../core/assets/PremiumAssetManager.js';
import { GltfAnimationPlayer } from '../core/assets/GltfAnimationPlayer.js';
import { InteriorInteractionSystem } from '../core/assets/InteriorInteractionSystem.js';
const VS_MESH=`#version 300 es
precision highp float;layout(location=0) in vec3 a_position;layout(location=1) in vec3 a_normal;layout(location=2) in vec4 a_color;uniform mat4 u_model,u_view,u_projection;out vec3 v_world;out vec3 v_normal;out vec4 v_color;out vec3 v_object;void main(){vec4 world=u_model*vec4(a_position,1.);v_world=world.xyz;v_normal=mat3(u_model)*a_normal;v_color=a_color;v_object=a_position;gl_Position=u_projection*u_view*world;}`;
const FS_MESH=`#version 300 es
precision highp float;in vec3 v_world;in vec3 v_normal;in vec4 v_color;in vec3 v_object;out vec4 outColor;uniform sampler2D u_albedo,u_roughness,u_environment;uniform vec3 u_camera,u_light;uniform float u_metalness,u_roughnessValue,u_mode,u_section,u_clip,u_exposure,u_time,u_selected;
#define PI 3.14159265359
vec2 envUv(vec3 d){d=normalize(d);return vec2(atan(d.z,d.x)/(2.*PI)+.5,asin(clamp(d.y,-1.,1.))/PI+.5);}vec3 env(vec3 d){return texture(u_environment,envUv(d)).rgb;}vec4 triSample(sampler2D tex,vec3 p,vec3 n){vec3 w=pow(abs(normalize(n)),vec3(5.));w/=max(.001,w.x+w.y+w.z);return texture(tex,p.yz*.42)*w.x+texture(tex,p.zx*.42)*w.y+texture(tex,p.xy*.42)*w.z;}
void main(){if(u_section>.5&&v_world.x>u_clip)discard;vec3 N=normalize(v_normal),V=normalize(u_camera-v_world),L=normalize(u_light);vec3 base=pow(max(v_color.rgb,vec3(.01)),vec3(2.2))*pow(max(triSample(u_albedo,v_object,N).rgb,vec3(.05)),vec3(2.2));float rough=clamp(u_roughnessValue*mix(.58,1.35,triSample(u_roughness,v_object,N).r),.08,.98);float metal=clamp(u_metalness,0.,1.);float ndl=max(dot(N,L),0.),ndv=max(dot(N,V),0.);vec3 H=normalize(L+V);float ndh=max(dot(N,H),0.);float power=mix(180.,5.,rough);float spec=pow(ndh,power)*(1.-rough*.55);vec3 F0=mix(vec3(.04),base,metal);vec3 fres=F0+(1.-F0)*pow(1.-max(dot(H,V),0.),5.);vec3 reflected=env(reflect(-V,N));vec3 diffuse=base*(1.-metal)*(ndl*.88+.08);vec3 color=diffuse+fres*spec*2.2+reflected*mix(.16,.7,metal)*(1.-rough*.45)+env(N)*base*.11;if(u_mode>1.5&&u_mode<2.5)color=N*.5+.5;else if(u_mode>2.5)color=mix(vec3(.08,.2,.75),vec3(1.,.12,.02),smoothstep(-1.6,1.8,v_world.y));float alpha=1.;if(u_mode>.5&&u_mode<1.5){float edge=pow(1.-ndv,2.5);color=vec3(.08,.62,1.2)*(edge+.16)+reflected*.25;alpha=.32+.48*edge;}color+=vec3(.12,.72,1.2)*u_selected*(.25+pow(1.-ndv,2.));color=vec3(1.)-exp(-color*u_exposure);color=pow(max(color,0.),vec3(1./2.2));outColor=vec4(color,alpha);}`;
const VS_BG=`#version 300 es
precision highp float;out vec2 v_uv;void main(){vec2 p=vec2((gl_VertexID<<1)&2,gl_VertexID&2);v_uv=p*.5;gl_Position=vec4(p*2.-1.,0,1);}`;
const FS_BG=`#version 300 es
precision highp float;in vec2 v_uv;out vec4 outColor;uniform sampler2D u_environment;uniform vec2 u_resolution;uniform float u_yaw,u_pitch,u_time,u_quality,u_exposure;#define PI 3.14159265359
float hash(vec3 p){p=fract(p*.1031);p+=dot(p,p.yzx+33.33);return fract((p.x+p.y)*p.z);}vec2 envUv(vec3 d){d=normalize(d);return vec2(atan(d.z,d.x)/(2.*PI)+.5,asin(clamp(d.y,-1.,1.))/PI+.5);}mat2 rot(float a){float c=cos(a),s=sin(a);return mat2(c,-s,s,c);}void main(){vec2 p=v_uv*2.-1.;p.x*=u_resolution.x/max(1.,u_resolution.y);vec3 rd=normalize(vec3(p,1.35));rd.xz*=rot(u_yaw);rd.yz*=rot(u_pitch);vec3 col=texture(u_environment,envUv(rd)).rgb;float stars=step(mix(.9992,.9977,u_quality),hash(floor(rd*mix(90.,210.,u_quality)+u_time*.002)));col+=stars*vec3(.7,.85,1.5);float horizon=smoothstep(.02,-.2,rd.y);vec2 gp=rd.xz/max(.05,abs(rd.y));float grid=(step(.96,fract(abs(gp.x)*.7))+step(.96,fract(abs(gp.y)*.7)))*horizon;col+=vec3(.02,.22,.34)*grid*.32;float glow=exp(-length(p-vec2(.48,-.35))*2.2);col+=vec3(.08,.2,.42)*glow*.2;col=vec3(1.)-exp(-col*u_exposure*.82);col=pow(max(col,0.),vec3(1./2.2));outColor=vec4(col,1.);}`;
function shader(gl,type,source){const item=gl.createShader(type);gl.shaderSource(item,source);gl.compileShader(item);if(!gl.getShaderParameter(item,gl.COMPILE_STATUS)){const message=gl.getShaderInfoLog(item)||'Falha ao compilar shader';gl.deleteShader(item);throw new Error(message);}return item;}
function program(gl,vs,fs){const p=gl.createProgram(),a=shader(gl,gl.VERTEX_SHADER,vs),b=shader(gl,gl.FRAGMENT_SHADER,fs);gl.attachShader(p,a);gl.attachShader(p,b);gl.linkProgram(p);gl.deleteShader(a);gl.deleteShader(b);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw new Error(gl.getProgramInfoLog(p)||'Falha de link');return p;}
function matMul(a,b){const o=new Float32Array(16);for(let c=0;c<4;c++)for(let r=0;r<4;r++)o[c*4+r]=a[r]*b[c*4]+a[4+r]*b[c*4+1]+a[8+r]*b[c*4+2]+a[12+r]*b[c*4+3];return o;}
const identity=()=>new Float32Array([1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]);
function trs(t=[0,0,0],q=[0,0,0,1],s=[1,1,1]){const[x,y,z,w]=q,x2=x+x,y2=y+y,z2=z+z,xx=x*x2,xy=x*y2,xz=x*z2,yy=y*y2,yz=y*z2,zz=z*z2,wx=w*x2,wy=w*y2,wz=w*z2;return new Float32Array([(1-(yy+zz))*s[0],(xy+wz)*s[0],(xz-wy)*s[0],0,(xy-wz)*s[1],(1-(xx+zz))*s[1],(yz+wx)*s[1],0,(xz+wy)*s[2],(yz-wx)*s[2],(1-(xx+yy))*s[2],0,t[0],t[1],t[2],1]);}
function perspective(fov,aspect,near,far){const f=1/Math.tan(fov/2),nf=1/(near-far);return new Float32Array([f/aspect,0,0,0,0,f,0,0,0,0,(far+near)*nf,-1,0,0,2*far*near*nf,0]);}
function lookAt(eye,target=[0,0,0],up=[0,1,0]){let zx=eye[0]-target[0],zy=eye[1]-target[1],zz=eye[2]-target[2],zl=Math.hypot(zx,zy,zz)||1;zx/=zl;zy/=zl;zz/=zl;let xx=up[1]*zz-up[2]*zy,xy=up[2]*zx-up[0]*zz,xz=up[0]*zy-up[1]*zx,xl=Math.hypot(xx,xy,xz)||1;xx/=xl;xy/=xl;xz/=xl;const yx=zy*xz-zz*xy,yy=zz*xx-zx*xz,yz=zx*xy-zy*xx;return new Float32Array([xx,yx,zx,0,xy,yy,zy,0,xz,yz,zz,0,-xx*eye[0]-xy*eye[1]-xz*eye[2],-yx*eye[0]-yy*eye[1]-yz*eye[2],-zx*eye[0]-zy*eye[1]-zz*eye[2],1]);}
async function imageFromBlob(blob){if(typeof createImageBitmap==='function')return createImageBitmap(blob);return new Promise((resolve,reject)=>{const img=new Image(),url=URL.createObjectURL(blob);img.onload=()=>{URL.revokeObjectURL(url);resolve(img);};img.onerror=()=>{URL.revokeObjectURL(url);reject(new Error('Falha ao decodificar textura.'));};img.src=url;});}
function textureFromImage(gl,image,{roughness=false}={}){const tex=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,tex);gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL,true);gl.texImage2D(gl.TEXTURE_2D,0,roughness?gl.RGBA8:gl.SRGB8_ALPHA8,gl.RGBA,gl.UNSIGNED_BYTE,image);gl.generateMipmap(gl.TEXTURE_2D);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR_MIPMAP_LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.REPEAT);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.REPEAT);return tex;}
function textureFromHdr(gl,hdr){const tex=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,tex);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA32F,hdr.width,hdr.height,0,gl.RGBA,gl.FLOAT,hdr.pixels);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.NEAREST);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.NEAREST);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.REPEAT);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);return tex;}
export class PremiumAssetSceneRenderer{
 constructor(canvas,settingsStore,{input,onDiagnostics=()=>{},onAssetLoaded=()=>{}}={}){this.canvas=canvas;this.settingsStore=settingsStore;this.input=input;this.onDiagnostics=onDiagnostics;this.onAssetLoaded=onAssetLoaded;this.manager=new PremiumAssetManager({settingsStore});this.gl=null;this.meshProgram=null;this.bgProgram=null;this.bgVao=null;this.drawables=[];this.textures=[];this.raf=0;this.running=false;this.loading=false;this.fallback=false;this.contextLost=false;this.assetId='shuttle';this.lod='auto';this.mode=0;this.section=false;this.autoRotate=true;this.yaw=.65;this.pitch=-.15;this.distance=5.2;this.turn=0;this.current=null;this.player=null;this.interactions=null;this.selectedNode=-1;this.currentAnimation=null;this.interactions=null;this.selectedNode=-1;this.lastTime=0;this.lastDiag=0;this.loadToken=0;this.resizeObserver=typeof ResizeObserver!=='undefined'?new ResizeObserver(()=>this.resize()):null;this.onResize=()=>this.resize();this.onContextLost=e=>{e.preventDefault();this.contextLost=true;this.onDiagnostics(this.diagnostics('context-lost'));};this.onContextRestored=async()=>{this.contextLost=false;await this.init();await this.loadAsset(this.assetId,this.lod,true);};}
 async init(){await this.manager.init();const gl=this.canvas.getContext('webgl2',{antialias:true,alpha:false,powerPreference:'high-performance'});if(!gl){this.startFallback();return false;}this.gl=gl;this.meshProgram=program(gl,VS_MESH,FS_MESH);this.bgProgram=program(gl,VS_BG,FS_BG);this.bgVao=gl.createVertexArray();this.meshUniforms={model:gl.getUniformLocation(this.meshProgram,'u_model'),view:gl.getUniformLocation(this.meshProgram,'u_view'),projection:gl.getUniformLocation(this.meshProgram,'u_projection'),camera:gl.getUniformLocation(this.meshProgram,'u_camera'),light:gl.getUniformLocation(this.meshProgram,'u_light'),metalness:gl.getUniformLocation(this.meshProgram,'u_metalness'),roughness:gl.getUniformLocation(this.meshProgram,'u_roughnessValue'),mode:gl.getUniformLocation(this.meshProgram,'u_mode'),section:gl.getUniformLocation(this.meshProgram,'u_section'),clip:gl.getUniformLocation(this.meshProgram,'u_clip'),exposure:gl.getUniformLocation(this.meshProgram,'u_exposure'),time:gl.getUniformLocation(this.meshProgram,'u_time'),selected:gl.getUniformLocation(this.meshProgram,'u_selected'),albedo:gl.getUniformLocation(this.meshProgram,'u_albedo'),roughnessMap:gl.getUniformLocation(this.meshProgram,'u_roughness'),environment:gl.getUniformLocation(this.meshProgram,'u_environment')};this.bgUniforms={environment:gl.getUniformLocation(this.bgProgram,'u_environment'),resolution:gl.getUniformLocation(this.bgProgram,'u_resolution'),yaw:gl.getUniformLocation(this.bgProgram,'u_yaw'),pitch:gl.getUniformLocation(this.bgProgram,'u_pitch'),time:gl.getUniformLocation(this.bgProgram,'u_time'),quality:gl.getUniformLocation(this.bgProgram,'u_quality'),exposure:gl.getUniformLocation(this.bgProgram,'u_exposure')};this.resize();return true;}
 async start(){if(!this.gl&&!await this.init())return;this.running=true;this.resizeObserver?this.resizeObserver.observe(this.canvas):addEventListener('resize',this.onResize);this.canvas.addEventListener('webglcontextlost',this.onContextLost);this.canvas.addEventListener('webglcontextrestored',this.onContextRestored);await this.loadAsset(this.assetId,this.lod);this.lastTime=performance.now();this.raf=requestAnimationFrame(t=>this.frame(t));}
 async loadAsset(id,lod='auto',force=false){this.assetId=id;this.lod=lod;if(this.fallback){this.onAssetLoaded({asset:this.manager.asset(id),selected:{level:0},geometry:{triangles:0,vertices:0},scene:{parts:0,animations:[]},loadMs:0});return;}const token=++this.loadToken;this.loading=true;try{const loaded=await this.manager.loadAsset(id,{lod,force});if(!this.gl||token!==this.loadToken)return;const[albedo,roughness]=await Promise.all([imageFromBlob(loaded.albedoBlob),imageFromBlob(loaded.roughnessBlob)]);if(!this.gl||token!==this.loadToken){albedo.close?.();roughness.close?.();return;}this.disposeGeometry();const gl=this.gl;for(const primitive of loaded.scene.primitives){const vao=gl.createVertexArray(),buffers=[];gl.bindVertexArray(vao);const bind=(location,data,size)=>{const buffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,data,gl.STATIC_DRAW);gl.enableVertexAttribArray(location);gl.vertexAttribPointer(location,size,gl.FLOAT,false,0,0);buffers.push(buffer);};bind(0,primitive.positions,3);bind(1,primitive.normals,3);bind(2,primitive.colors,4);const idx=gl.createBuffer();gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,idx);gl.bufferData(gl.ELEMENT_ARRAY_BUFFER,primitive.indices,gl.STATIC_DRAW);buffers.push(idx);this.drawables.push({vao,buffers,primitive});}this.textures=[textureFromImage(gl,albedo),textureFromImage(gl,roughness,{roughness:true}),textureFromHdr(gl,loaded.environment)];albedo.close?.();roughness.close?.();this.current=loaded;this.player=new GltfAnimationPlayer(loaded.scene);this.interactions=new InteriorInteractionSystem(loaded.scene);this.selectedNode=-1;this.distance=4.8;const defaultAnimation=loaded.asset.animations?.[0];if(defaultAnimation)this.playAnimation(defaultAnimation,{restart:true});this.onAssetLoaded(loaded);this.onDiagnostics(this.diagnostics('loaded'));}finally{if(token===this.loadToken)this.loading=false;}}
 setLod(value){return this.loadAsset(this.assetId,value);}setMode(value){this.mode=Number(value)||0;}setSection(value){this.section=Boolean(value);}setAutoRotate(value){this.autoRotate=Boolean(value);}animationList(){return this.player?.list?.()||[];}playAnimation(name,{loop,speed,restart=true}={}){if(!this.player)return false;const ok=this.player.play(name,{loop,speed,restart});if(ok)this.currentAnimation=name;return ok;}pauseAnimation(){this.player?.pause();}
 interactionList(){return this.interactions?.list?.()||[];}
 colliderList(){return(this.current?.scene?.colliders||[]).map(item=>structuredClone(item));}
 activateInteraction(index){const item=this.interactions?.activate?.(Number(index));if(!item)return null;this.selectedNode=item.node;const clip=this.interactions.resolveClip(item.action,this.animationList());if(clip)this.playAnimation(clip,{restart:true});this.focusNode(item.node);this.onDiagnostics({state:'interaction',interaction:item.action,node:item.node,clip});return{...item,clip};}
 focusNode(nodeIndex){const node=this.current?.scene?.nodes?.[nodeIndex];if(!node)return false;const [x=0,y=0,z=0]=node.translation||[0,0,0];this.yaw=Math.atan2(x,z||.001);this.pitch=Math.max(-.65,Math.min(.65,Math.atan2(y,Math.hypot(x,z)||1)));this.distance=Math.max(2.2,Math.min(5.5,this.current.scene.bounds.radius*2.1));this.autoRotate=false;return true;}
 setInteriorMode(value){this.section=Boolean(value);if(value){this.distance=Math.max(2.1,this.distance*.72);this.pitch=0;this.autoRotate=false;}return this.section;}
 resize(){if(!this.gl)return;const rect=this.canvas.getBoundingClientRect(),profile=this.settingsStore.getProfile(),dpr=Math.min(devicePixelRatio||1,2)*profile.renderScale,w=Math.max(2,Math.floor(rect.width*dpr)),h=Math.max(2,Math.floor(rect.height*dpr));if(w!==this.canvas.width||h!==this.canvas.height){this.canvas.width=w;this.canvas.height=h;this.gl.viewport(0,0,w,h);}}
 frame(time){if(!this.running)return;const dt=Math.min(.05,(time-this.lastTime)/1000||.016);this.lastTime=time;const sample=this.input?.sample?.()||{};this.yaw-=sample.lookX*.018+sample.strafe*dt*.9;this.pitch=Math.max(-1.15,Math.min(1.15,this.pitch-sample.lookY*.018));this.distance=Math.max(2.2,Math.min(10,this.distance+sample.zoom*.15-sample.forward*dt*2.2));if(this.autoRotate&&!this.settingsStore.get().reducedMotion)this.turn+=dt*.28;const overrides=this.player?.update(dt)||new Map();if(!this.contextLost&&this.gl&&this.current)this.draw(time,overrides);if(time-this.lastDiag>1200){this.lastDiag=time;this.onDiagnostics(this.diagnostics(this.loading?'loading':'running'));}this.raf=requestAnimationFrame(t=>this.frame(t));}
 worldMatrices(overrides){const scene=this.current.scene,worlds=new Array(scene.nodes.length),visit=(index,parent)=>{const n=scene.nodes[index],o=overrides.get(index)||{},local=n.matrix?new Float32Array(n.matrix):trs(o.translation||n.translation,o.rotation||n.rotation,o.scale||n.scale),world=matMul(parent,local);worlds[index]=world;for(const child of n.children)visit(child,world);};for(const root of scene.roots)visit(root,identity());return worlds;}
 draw(time,overrides){this.resize();const gl=this.gl,profile=this.settingsStore.getProfile(),quality=profile.id==='performance'?.2:profile.id==='experience'?1:.62,exposure=profile.id==='experience'?1.35:1.05;gl.disable(gl.CULL_FACE);gl.enable(gl.DEPTH_TEST);gl.depthMask(true);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.useProgram(this.bgProgram);gl.bindVertexArray(this.bgVao);gl.activeTexture(gl.TEXTURE2);gl.bindTexture(gl.TEXTURE_2D,this.textures[2]);gl.uniform1i(this.bgUniforms.environment,2);gl.uniform2f(this.bgUniforms.resolution,this.canvas.width,this.canvas.height);gl.uniform1f(this.bgUniforms.yaw,this.yaw);gl.uniform1f(this.bgUniforms.pitch,this.pitch);gl.uniform1f(this.bgUniforms.time,time*.001);gl.uniform1f(this.bgUniforms.quality,quality);gl.uniform1f(this.bgUniforms.exposure,exposure);gl.disable(gl.DEPTH_TEST);gl.drawArrays(gl.TRIANGLES,0,3);gl.enable(gl.DEPTH_TEST);
 const scene=this.current.scene,baseScale=1.75/Math.max(.01,scene.bounds.radius),eye=[Math.sin(this.yaw)*Math.cos(this.pitch)*this.distance,Math.sin(this.pitch)*this.distance,Math.cos(this.yaw)*Math.cos(this.pitch)*this.distance],view=lookAt(eye),projection=perspective(Math.PI/4,this.canvas.width/this.canvas.height,.05,100),base=matMul(trs([0,0,0],[0,Math.sin(this.turn/2),0,Math.cos(this.turn/2)],[baseScale,baseScale,baseScale]),trs(scene.bounds.center.map(v=>-v))),worlds=this.worldMatrices(overrides);gl.useProgram(this.meshProgram);gl.uniformMatrix4fv(this.meshUniforms.view,false,view);gl.uniformMatrix4fv(this.meshUniforms.projection,false,projection);gl.uniform3fv(this.meshUniforms.camera,eye);gl.uniform3f(this.meshUniforms.light,-.6,.85,.45);gl.uniform1f(this.meshUniforms.metalness,this.current.asset.metalness);gl.uniform1f(this.meshUniforms.roughness,this.current.asset.roughness);gl.uniform1f(this.meshUniforms.mode,this.mode);gl.uniform1f(this.meshUniforms.section,this.section?1:0);gl.uniform1f(this.meshUniforms.clip,0);gl.uniform1f(this.meshUniforms.exposure,exposure);gl.uniform1f(this.meshUniforms.time,time*.001);this.textures.forEach((texture,index)=>{gl.activeTexture(gl.TEXTURE0+index);gl.bindTexture(gl.TEXTURE_2D,texture);});gl.uniform1i(this.meshUniforms.albedo,0);gl.uniform1i(this.meshUniforms.roughnessMap,1);gl.uniform1i(this.meshUniforms.environment,2);if(this.mode===1){gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);gl.depthMask(false);}for(const item of this.drawables){gl.bindVertexArray(item.vao);gl.uniform1f(this.meshUniforms.selected,item.primitive.nodeIndex===this.selectedNode?1:0);gl.uniformMatrix4fv(this.meshUniforms.model,false,matMul(base,worlds[item.primitive.nodeIndex]||identity()));gl.drawElements(gl.TRIANGLES,item.primitive.indices.length,item.primitive.indexType===5125?gl.UNSIGNED_INT:gl.UNSIGNED_SHORT,0);}if(this.mode===1){gl.depthMask(true);gl.disable(gl.BLEND);}}
 startFallback(){this.fallback=true;this.running=true;const ctx=this.canvas.getContext('2d');if(!ctx)return;const draw=()=>{if(!this.running)return;const rect=this.canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,1.5),w=Math.max(2,Math.floor(rect.width*dpr)),h=Math.max(2,Math.floor(rect.height*dpr));this.canvas.width=w;this.canvas.height=h;const g=ctx.createRadialGradient(w*.5,h*.45,10,w*.5,h*.5,w*.7);g.addColorStop(0,'#12324a');g.addColorStop(.45,'#071421');g.addColorStop(1,'#010307');ctx.fillStyle=g;ctx.fillRect(0,0,w,h);ctx.strokeStyle='rgba(91,225,255,.18)';for(let i=0;i<18;i++){ctx.beginPath();ctx.ellipse(w*.5,h*.72,i*28*dpr,i*9*dpr,0,0,Math.PI*2);ctx.stroke();}ctx.fillStyle='#dff8ff';ctx.font=`700 ${18*dpr}px system-ui`;ctx.fillText('Asset Premium · fallback 2D',18*dpr,30*dpr);ctx.fillStyle='#69ddff';ctx.font=`${14*dpr}px system-ui`;ctx.fillText(this.manager.asset(this.assetId)?.title||this.assetId,18*dpr,54*dpr);this.raf=requestAnimationFrame(draw);};draw();this.onDiagnostics(this.diagnostics('fallback'));}
 diagnostics(state='idle'){return{state,renderer:this.fallback?'Canvas 2D':'WebGL2 + GLB animado',resolution:`${this.canvas.width}×${this.canvas.height}`,profile:this.settingsStore.getProfile().id,asset:this.assetId,lod:this.current?.selected?.level??this.lod,triangles:this.current?.scene?.triangles||0,vertices:this.current?.scene?.vertices||0,parts:this.current?.scene?.parts||0,animations:this.current?.scene?.animations?.length||0,animation:this.player?.state?.clip||null,loadMs:this.current?.loadMs||0,loadedPacks:this.manager.diagnostics().loaded,mode:this.mode,section:this.section,contextLost:this.contextLost};}
 async requestFullscreen(){if(!document.fullscreenElement)await this.canvas.closest('.premium-assets-stage')?.requestFullscreen?.();else await document.exitFullscreen?.();}
 disposeGeometry(){if(!this.gl)return;for(const item of this.drawables){for(const buffer of item.buffers)this.gl.deleteBuffer(buffer);this.gl.deleteVertexArray(item.vao);}for(const texture of this.textures)this.gl.deleteTexture(texture);this.drawables=[];this.textures=[];this.player=null;this.interactions=null;this.selectedNode=-1;this.currentAnimation=null;}
 destroy(){this.running=false;cancelAnimationFrame(this.raf);this.resizeObserver?.disconnect();removeEventListener('resize',this.onResize);this.canvas.removeEventListener('webglcontextlost',this.onContextLost);this.canvas.removeEventListener('webglcontextrestored',this.onContextRestored);this.disposeGeometry();if(this.gl&&this.bgVao)this.gl.deleteVertexArray(this.bgVao);if(this.gl&&this.meshProgram)this.gl.deleteProgram(this.meshProgram);if(this.gl&&this.bgProgram)this.gl.deleteProgram(this.bgProgram);this.manager.releaseAll();this.gl=null;this.meshProgram=null;this.bgProgram=null;this.bgVao=null;}
}
