'use strict';
(function(){
  window.LABDS_LABS=window.LABDS_LABS||{};
  const KEY='lab.energy.state';let root,ctx,state;
  const $=s=>root.querySelector(s),clamp=(n,a,b)=>Math.min(b,Math.max(a,Number(n)||0));
  function defaults(){return{tab:'voltage',voltage:{source:12,current:4,length:18,area:1.5,resistivity:.0175},solar:{panels:6,power:450,irradiance:5.2,tilt:25,shade:10,efficiency:88,battery:8,consumption:9},wind:{speed:8,radius:2.5,cp:.38,hours:8,battery:6,consumption:5}};}
  function voltageResult(){const v=state.voltage,drop=2*v.length*v.current*v.resistivity/v.area,percent=drop/v.source*100;return{drop,percent,end:v.source-drop,power:v.current*drop};}
  function solarResult(){const s=state.solar,tiltFactor=Math.max(.55,1-Math.abs(s.tilt-25)*.008),shadeFactor=1-s.shade/100,energy=s.panels*s.power/1000*s.irradiance*tiltFactor*shadeFactor*s.efficiency/100;return{energy,balance:energy-s.consumption,batteryDays:s.battery/Math.max(.1,s.consumption-energy)};}
  function windResult(){const w=state.wind,area=Math.PI*w.radius*w.radius,power=.5*1.225*area*w.speed**3*w.cp/1000,energy=power*w.hours;return{area,power,energy,balance:energy-w.consumption};}
  function drawGraph(values,label){const canvas=$('#energyChart');if(!canvas)return;const c=canvas.getContext('2d'),w=canvas.width,h=canvas.height;c.clearRect(0,0,w,h);c.fillStyle='#07111f';c.fillRect(0,0,w,h);const max=Math.max(1,...values.map(v=>v.value));values.forEach((item,index)=>{const bw=(w-80)/values.length-16,bh=item.value/max*(h-80),x=50+index*((w-80)/values.length),y=h-45-bh;c.fillStyle=item.color;c.fillRect(x,y,bw,bh);c.fillStyle='#dceaff';c.font='12px system-ui';c.fillText(item.label,x,h-22);c.fillText(item.value.toFixed(2),x,y-7);});c.fillStyle='#9fb5d0';c.fillText(label,14,18);}
  function renderPanel(){const host=$('#energyPanel');if(state.tab==='voltage'){const r=voltageResult();host.innerHTML=`<div class="energy-controls">${input('source','Tensão da fonte (V)',state.voltage.source,1,400,.1)}${input('current','Corrente (A)',state.voltage.current,.1,100,.1)}${input('length','Comprimento do cabo (m)',state.voltage.length,.5,500,.5)}${input('area','Seção do cabo (mm²)',state.voltage.area,.5,50,.5)}${input('resistivity','Resistividade',state.voltage.resistivity,.01,.05,.0001)}</div><div class="energy-meter"><span>Fonte ${state.voltage.source.toFixed(1)} V</span><i style="width:${clamp(r.end/state.voltage.source*100,0,100)}%"></i><span>Carga ${r.end.toFixed(2)} V</span></div><div class="energy-results"><article><b>${r.drop.toFixed(2)} V</b><span>queda</span></article><article><b>${r.percent.toFixed(1)}%</b><span>perda percentual</span></article><article><b>${r.end.toFixed(2)} V</b><span>tensão na carga</span></article><article class="${r.percent>5?'warning':'ok'}"><b>${r.percent>5?'Revisar':'Adequado'}</b><span>limite educacional de 5%</span></article></div>`;bindInputs('voltage');drawGraph([{label:'Fonte',value:state.voltage.source,color:'#55d6ff'},{label:'Carga',value:Math.max(0,r.end),color:'#43e6a8'},{label:'Queda',value:r.drop,color:'#ff6f8d'}],'Comparação de tensão');}
    if(state.tab==='solar'){const r=solarResult();host.innerHTML=`<div class="energy-controls">${input('panels','Painéis',state.solar.panels,1,40,1)}${input('power','Potência por painel (W)',state.solar.power,100,800,10)}${input('irradiance','Horas de sol pico',state.solar.irradiance,1,8,.1)}${input('tilt','Inclinação (°)',state.solar.tilt,0,70,1)}${input('shade','Sombra (%)',state.solar.shade,0,100,1)}${input('efficiency','Eficiência do sistema (%)',state.solar.efficiency,40,100,1)}${input('battery','Bateria (kWh)',state.solar.battery,0,100,.5)}${input('consumption','Consumo diário (kWh)',state.solar.consumption,.5,100,.5)}</div><div class="solar-scene"><div class="sun" style="--shade:${state.solar.shade/100}"></div><div class="solar-panels" style="transform:perspective(500px) rotateX(${65-state.solar.tilt*.55}deg)">${Array.from({length:Math.min(12,state.solar.panels)},()=>'<i></i>').join('')}</div></div><div class="energy-results"><article><b>${r.energy.toFixed(2)} kWh</b><span>produção diária</span></article><article><b>${r.balance.toFixed(2)} kWh</b><span>saldo</span></article><article class="${r.balance>=0?'ok':'warning'}"><b>${r.balance>=0?'Autossuficiente':'Déficit'}</b><span>comparação diária</span></article></div>`;bindInputs('solar');drawGraph([{label:'Produção',value:r.energy,color:'#ffcf5d'},{label:'Consumo',value:state.solar.consumption,color:'#55d6ff'},{label:'Bateria',value:state.solar.battery,color:'#7f6cff'}],'Energia diária');}
    if(state.tab==='wind'){const r=windResult();host.innerHTML=`<div class="energy-controls">${input('speed','Velocidade do vento (m/s)',state.wind.speed,1,30,.5)}${input('radius','Raio das pás (m)',state.wind.radius,.5,30,.5)}${input('cp','Coeficiente de potência',state.wind.cp,.1,.59,.01)}${input('hours','Horas de operação',state.wind.hours,1,24,1)}${input('battery','Bateria (kWh)',state.wind.battery,0,100,.5)}${input('consumption','Consumo (kWh)',state.wind.consumption,.5,100,.5)}</div><div class="wind-scene"><div class="wind-tower"><span style="animation-duration:${Math.max(.3,3-state.wind.speed*.08)}s"><i></i><i></i><i></i></span></div><div class="wind-lines"></div></div><div class="energy-results"><article><b>${r.power.toFixed(2)} kW</b><span>potência instantânea</span></article><article><b>${r.energy.toFixed(2)} kWh</b><span>energia produzida</span></article><article><b>${r.balance.toFixed(2)} kWh</b><span>saldo</span></article></div>`;bindInputs('wind');drawGraph([{label:'Produção',value:r.energy,color:'#43e6a8'},{label:'Consumo',value:state.wind.consumption,color:'#ff6f8d'},{label:'Bateria',value:state.wind.battery,color:'#7f6cff'}],'Energia eólica');}}
  function input(key,label,value,min,max,step){return`<label>${label}<input data-energy-key="${key}" type="number" min="${min}" max="${max}" step="${step}" value="${value}"></label>`;}
  function bindInputs(section){$$('[data-energy-key]').forEach(input=>input.oninput=()=>{state[section][input.dataset.energyKey]=Number(input.value);ctx.storage.set(KEY,state);renderPanel();});}
  function template(){return`<div class="energy-lab"><header><div><span class="eyebrow">ELETRÔNICA E SUSTENTABILIDADE</span><h2>Energia e medições</h2><p>Altere parâmetros, observe cálculos e compare produção, perda, consumo e armazenamento.</p></div><nav>${[['voltage','Queda de tensão'],['solar','Energia solar'],['wind','Energia eólica']].map(([id,label])=>`<button data-energy-tab="${id}" class="${state.tab===id?'active':''}">${label}</button>`).join('')}</nav></header><section class="energy-layout"><div id="energyPanel"></div><aside><canvas id="energyChart" width="520" height="300"></canvas><div class="state-card info"><h3>Atividade</h3><p>Encontre uma configuração que mantenha a queda abaixo de 5% ou produza energia suficiente para o consumo configurado.</p><button id="validateEnergy" class="btn primary">Validar configuração</button></div></aside></section></div>`;}
  async function mount(host,context){root=host;ctx=context;state={...defaults(),...(await ctx.storage.get(KEY,{}))};root.innerHTML=template();$$('[data-energy-tab]').forEach(button=>button.onclick=()=>{state.tab=button.dataset.energyTab;ctx.storage.set(KEY,state);root.innerHTML=template();mountBindings();});mountBindings();}
  function mountBindings(){$$('[data-energy-tab]').forEach(button=>button.onclick=()=>{state.tab=button.dataset.energyTab;ctx.storage.set(KEY,state);root.innerHTML=template();mountBindings();});$('#validateEnergy').onclick=()=>{const ok=state.tab==='voltage'?voltageResult().percent<=5:state.tab==='solar'?solarResult().balance>=0:windResult().balance>=0;if(ok){ctx.core?.complete?.(`energy:${state.tab}`,{xp:60,credits:25,reason:`Configuração de ${state.tab} validada`});ctx.toast('Configuração validada.','success');}else ctx.toast('A configuração ainda apresenta perda ou déficit. Ajuste os parâmetros.','warning');};renderPanel();}
  async function unmount(){await ctx?.storage?.set?.(KEY,state);root=null;ctx=null;}
  function exportPayload(){return{text:`ENERGIA\nAba: ${state.tab}\nDados: ${JSON.stringify(state[state.tab])}`,native:JSON.stringify(state,null,2),backup:state};}
  function help(){return'<p>Queda de tensão usa resistividade, comprimento, corrente e seção do cabo. Solar e eólica comparam produção simulada, consumo e bateria.</p>';}
  window.LABDS_LABS['energy-lab']={mount,unmount,exportPayload,help};
})();
