'use strict';
(function(){
  window.LABDS_LABS=window.LABDS_LABS||{};
  const KEY='lab.automation.state';
  const DEFAULT={tab:'gate',xp:0,authorized:['ABC1D23','LAB2026'],rules:{plate:true,weight:true,notify:true},robot:{x:45,y:35,grip:false}};
  let root,ctx,state,timer=0,raf=0;
  async function save(){await ctx.storage.set(KEY,state);}
  function setTab(tab){state.tab=tab;root.querySelectorAll('[data-auto-tab]').forEach(b=>b.classList.toggle('active',b.dataset.autoTab===tab));root.querySelectorAll('[data-auto-panel]').forEach(p=>p.classList.toggle('hidden',p.dataset.autoPanel!==tab));save();if(tab==='robot')drawRobot();else cancelAnimationFrame(raf);}
  function appendLog(text,tone=''){const log=root.querySelector('#autoLog');const line=document.createElement('div');line.className=tone;line.textContent=`${new Date().toLocaleTimeString('pt-BR')}  ${text}`;log.prepend(line);}
  function runGate(){const plate=root.querySelector('#plateInput').value.toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,7),weight=Number(root.querySelector('#weightInput').value),nodes=[...root.querySelectorAll('#gateFlow .flow-node')],status=root.querySelector('#gateStatus');if(plate.length<6||!Number.isFinite(weight)){status.textContent='Informe placa e peso fictícios.';return;}clearTimeout(timer);nodes.forEach(n=>n.classList.remove('active'));let i=0;const steps=['Sensor detectou aproximação.','Câmera capturou a placa.','OCR converteu imagem em texto.','Sistema consultou a lista de autorização.','Balança registrou o peso.','Regra decidiu a abertura da cancela.'];const next=()=>{if(i>0)nodes[i-1].classList.remove('active');if(i>=nodes.length){const authorized=!state.rules.plate||state.authorized.includes(plate),weightOk=!state.rules.weight||weight<=28000,open=authorized&&weightOk;status.className=`gate-status ${open?'open':'blocked'}`;status.innerHTML=`<span>${open?'✓':'!'}</span><b>${open?'ACESSO LIBERADO':'ACESSO BLOQUEADO'}</b><small>${!authorized?'placa não autorizada':!weightOk?'peso acima do limite':'regras atendidas'}</small>`;appendLog(`${plate}: ${open?'cancela aberta':'bloqueado'} (${weight} kg)`,open?'success':'error');if(state.rules.notify)appendLog('Notificação local enviada ao operador.','info');state.xp+=open?25:12;root.querySelector('#autoXp').textContent=state.xp;save();return;}nodes[i].classList.add('active');appendLog(steps[i]);i++;timer=setTimeout(next,520);};next();}
  function buildRule(){const sensor=root.querySelector('#ruleSensor').value,condition=root.querySelector('#ruleCondition').value,action=root.querySelector('#ruleAction').value,preview=root.querySelector('#rulePreview');preview.textContent=`QUANDO ${sensor}\nSE ${condition}\nENTÃO ${action}`;state.xp+=8;root.querySelector('#autoXp').textContent=state.xp;save();}
  function drawRobot(){cancelAnimationFrame(raf);const canvas=root.querySelector('#robotCanvas');if(!canvas)return;const c=canvas.getContext('2d');const loop=t=>{const rect=canvas.getBoundingClientRect(),ratio=(window.LABDS?.PerformanceManager?.canvasScale?.(2)??Math.min(2,devicePixelRatio||1));if(canvas.width!==Math.round(rect.width*ratio)||canvas.height!==Math.round(rect.height*ratio)){canvas.width=Math.round(rect.width*ratio);canvas.height=Math.round(rect.height*ratio);c.setTransform(ratio,0,0,ratio,0,0);}const w=rect.width,h=rect.height;c.clearRect(0,0,w,h);const g=c.createLinearGradient(0,0,w,h);g.addColorStop(0,'#050c15');g.addColorStop(1,'#0b2934');c.fillStyle=g;c.fillRect(0,0,w,h);c.strokeStyle='rgba(100,230,255,.1)';for(let x=0;x<w;x+=32){c.beginPath();c.moveTo(x,0);c.lineTo(x,h);c.stroke();}const base={x:w*.28,y:h*.78},a1=(state.robot.x/100-.5)*1.8,a2=(state.robot.y/100-.5)*2;const p1={x:base.x+Math.cos(-1.1+a1)*110,y:base.y+Math.sin(-1.1+a1)*110},p2={x:p1.x+Math.cos(-.35+a2)*95,y:p1.y+Math.sin(-.35+a2)*95};c.lineCap='round';c.lineWidth=24;c.strokeStyle='#1c5a78';c.beginPath();c.moveTo(base.x,base.y);c.lineTo(p1.x,p1.y);c.lineTo(p2.x,p2.y);c.stroke();c.lineWidth=5;c.strokeStyle='#75efff';c.stroke();for(const p of [base,p1,p2]){c.beginPath();c.arc(p.x,p.y,16,0,Math.PI*2);c.fillStyle='#0b1928';c.fill();c.strokeStyle='#6de9ff';c.stroke();}c.strokeStyle=state.robot.grip?'#56f1b9':'#ffcc67';c.lineWidth=6;c.beginPath();c.moveTo(p2.x,p2.y);c.lineTo(p2.x+18,p2.y-15);c.moveTo(p2.x,p2.y);c.lineTo(p2.x+18,p2.y+15);c.stroke();c.fillStyle='#e8f8ff';c.font='700 15px system-ui';c.fillText(`Garra: ${state.robot.grip?'fechada':'aberta'}`,16,28);raf=requestAnimationFrame(loop);};raf=requestAnimationFrame(loop);}
  function render(){root.innerHTML=`<div class="immersive-lab automation-lab"><header class="immersive-hero"><div><span class="eyebrow">AUTOMAÇÃO • IOT • ROBÓTICA</span><h2>Transforme eventos em ações</h2><p>Combine sensores, OCR, regras, atuadores, alertas e controle de robô em cenários industriais e logísticos simulados.</p></div><div class="immersive-badges"><span>XP <b id="autoXp">${state.xp}</b></span><span>Dados fictícios</span><span>Execução local</span></div></header><nav class="module-tabs"><button data-auto-tab="gate">Portaria inteligente</button><button data-auto-tab="rules">Regras IoT</button><button data-auto-tab="robot">Braço robótico</button><button data-auto-tab="telemetry">Telemetria</button></nav>
    <section data-auto-panel="gate" class="immersive-grid"><article class="immersive-card"><h3>Entrada de caminhão</h3><label>Placa fictícia<input id="plateInput" maxlength="7" value="ABC1D23"></label><label>Peso registrado (kg)<input id="weightInput" type="number" min="0" value="18450"></label><div class="rule-switches"><label><input id="rulePlate" type="checkbox" checked> validar placa</label><label><input id="ruleWeight" type="checkbox" checked> limitar a 28.000 kg</label><label><input id="ruleNotify" type="checkbox" checked> avisar operador</label></div><button id="runGate" class="btn primary">Executar automação</button><div id="gateStatus" class="gate-status"><span>○</span><b>AGUARDANDO</b><small>sensor sem evento</small></div></article><article class="immersive-card"><h3>Fluxo físico e digital</h3><div id="gateFlow" class="flow-track"><div class="flow-node">Sensor<br><small>presença</small></div><span class="flow-arrow">›</span><div class="flow-node">Câmera<br><small>imagem</small></div><span class="flow-arrow">›</span><div class="flow-node">OCR<br><small>placa</small></div><span class="flow-arrow">›</span><div class="flow-node">Sistema<br><small>regra</small></div><span class="flow-arrow">›</span><div class="flow-node">Balança<br><small>peso</small></div><span class="flow-arrow">›</span><div class="flow-node">Cancela<br><small>atuador</small></div></div><div id="autoLog" class="automation-log"><div>Laboratório inicializado.</div></div></article></section>
    <section data-auto-panel="rules" class="immersive-grid hidden"><article class="immersive-card"><h3>Construtor de regra</h3><label>QUANDO<select id="ruleSensor"><option>sensor de presença detectar movimento</option><option>temperatura passar de 32 °C</option><option>câmera reconhecer uma placa</option><option>estoque chegar ao mínimo</option></select></label><label>SE<select id="ruleCondition"><option>o dispositivo estiver autorizado</option><option>o valor superar o limite</option><option>for horário de funcionamento</option><option>não houver falha ativa</option></select></label><label>ENTÃO<select id="ruleAction"><option>abrir a cancela e registrar o evento</option><option>ligar ventilação e enviar alerta</option><option>bloquear acesso e chamar o operador</option><option>acionar motor por cinco segundos</option></select></label><button id="buildRule" class="btn primary">Montar regra</button></article><article class="immersive-card"><h3>Lógica gerada</h3><pre id="rulePreview" class="terminal-mini">Escolha os componentes e monte a regra.</pre><div class="knowledge-card"><strong>Automação orientada a eventos:</strong> sensores produzem sinais; o software interpreta condições; atuadores executam ações; logs permitem auditoria.</div></article></section>
    <section data-auto-panel="robot" class="immersive-grid hidden"><article class="immersive-card"><h3>Controle do braço</h3><label>Articulação A<input id="robotX" type="range" min="0" max="100" value="${state.robot.x}"></label><label>Articulação B<input id="robotY" type="range" min="0" max="100" value="${state.robot.y}"></label><button id="robotGrip" class="btn primary">Alternar garra</button><div class="button-row"><button data-preset="pick" class="btn secondary">Posição coleta</button><button data-preset="drop" class="btn secondary">Posição entrega</button></div></article><article class="immersive-card"><div class="visual-stage"><canvas id="robotCanvas" aria-label="Braço robótico simulado"></canvas></div></article></section>
    <section data-auto-panel="telemetry" class="immersive-grid hidden"><article class="immersive-card"><h3>Telemetria em tempo real</h3><div class="metric-row"><div class="metric-card"><small>Temperatura</small><strong id="teleTemp">27.4 °C</strong></div><div class="metric-card"><small>Umidade</small><strong id="teleHumidity">58%</strong></div><div class="metric-card"><small>Vibração</small><strong id="teleVibration">0.18 g</strong></div><div class="metric-card"><small>Energia</small><strong id="telePower">1.4 kW</strong></div></div><button id="simulateFault" class="btn danger">Simular superaquecimento</button></article><article class="immersive-card"><h3>Resposta automática</h3><div class="server-rack"><div>Sensor</div><i></i><div>Gateway IoT</div><i></i><div>Regra</div><i></i><div>Ventilação</div></div><div id="faultFeedback" class="practice-feedback">Sistema operando normalmente.</div></article></section></div>`;
    root.querySelectorAll('[data-auto-tab]').forEach(b=>b.addEventListener('click',()=>setTab(b.dataset.autoTab)));root.querySelector('#runGate').addEventListener('click',runGate);for(const [id,key] of [['rulePlate','plate'],['ruleWeight','weight'],['ruleNotify','notify']])root.querySelector(`#${id}`).addEventListener('change',e=>{state.rules[key]=e.target.checked;save();});root.querySelector('#buildRule').addEventListener('click',buildRule);root.querySelector('#robotX').addEventListener('input',e=>{state.robot.x=Number(e.target.value);save();});root.querySelector('#robotY').addEventListener('input',e=>{state.robot.y=Number(e.target.value);save();});root.querySelector('#robotGrip').addEventListener('click',()=>{state.robot.grip=!state.robot.grip;save();});root.querySelectorAll('[data-preset]').forEach(b=>b.addEventListener('click',()=>{const p=b.dataset.preset==='pick'?{x:18,y:80,grip:true}:{x:82,y:25,grip:false};Object.assign(state.robot,p);root.querySelector('#robotX').value=p.x;root.querySelector('#robotY').value=p.y;save();}));root.querySelector('#simulateFault').addEventListener('click',()=>{root.querySelector('#teleTemp').textContent='43.8 °C';root.querySelector('#telePower').textContent='2.8 kW';const f=root.querySelector('#faultFeedback');f.className='practice-feedback error';f.textContent='Regra acionada: desligar carga, ligar ventilação e notificar manutenção.';state.xp+=20;root.querySelector('#autoXp').textContent=state.xp;save();});setTab(state.tab);
  }
  async function mount(host,context){root=host;ctx=context;state={...DEFAULT,...await ctx.storage.get(KEY,DEFAULT),robot:{...DEFAULT.robot,...(await ctx.storage.get(KEY,DEFAULT)).robot},rules:{...DEFAULT.rules,...(await ctx.storage.get(KEY,DEFAULT)).rules}};render();}
  async function unmount(){clearTimeout(timer);cancelAnimationFrame(raf);await save();root=null;ctx=null;state=null;}
  function exportPayload(){return{text:`AUTOMAÇÃO E IOT\nXP: ${state.xp}\nPlacas autorizadas: ${state.authorized.join(', ')}`,native:JSON.stringify(state,null,2),backup:state,meta:[{label:'XP',value:String(state.xp)},{label:'Regras',value:String(Object.values(state.rules).filter(Boolean).length)}]};}
  function help(){return'<h3>Automação e IoT</h3><p>Use dados fictícios para simular sensores, OCR, regras, atuadores e robótica. Nenhum equipamento real é controlado.</p>';}
  window.LABDS_LABS['automation-lab']={mount,unmount,exportPayload,help};
})();
