import { OperationalPanelModel } from '../../core/technical/OperationalPanelModel.js';
import { TechnicalCutawayRenderer } from '../../rendering/TechnicalCutawayRenderer.js';
import { TECHNICAL_SYSTEMS,TECHNICAL_SYSTEM_BY_ID,TECHNICAL_VIEW_MODES,TECHNICAL_PANEL_GOALS } from '../../data/technicalMuseumSystems.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=(value,precision=0)=>Number(value??0).toLocaleString('pt-BR',{minimumFractionDigits:precision,maximumFractionDigits:precision});
const download=(name,text,type='application/json')=>{const blob=new Blob([text],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
class TechnicalOperationsModule{
  constructor(){this.container=null;this.context=null;this.model=null;this.renderer=null;this.raf=0;this.last=0;this.panelTab='quick';this.logOpen=false;this.helpOpen=false;this.onClick=e=>this.handleClick(e);this.onKey=e=>this.handleKey(e);}
  mount(container,context){this.container=container;this.context=context;const requested=sessionStorage.getItem('cosmos-ds-technical-target');sessionStorage.removeItem('cosmos-ds-technical-target');this.model=new OperationalPanelModel(TECHNICAL_SYSTEM_BY_ID[requested]?requested:'satellite');container.addEventListener('click',this.onClick);addEventListener('keydown',this.onKey);this.render();this.startRenderer();}
  unmount(){cancelAnimationFrame(this.raf);this.renderer?.destroy();this.container?.removeEventListener('click',this.onClick);removeEventListener('keydown',this.onKey);}
  render(){const system=this.model.system(),snap=this.model.snapshot(),sub=system.subsystems.find(item=>item.id===snap.selectedSubsystemId)||system.subsystems[0],step=snap.currentStep;this.container.innerHTML=`<section class="technical-operations" style="--tech:${system.color}"><div class="technical-stage"><canvas id="technical-cutaway-canvas" aria-label="Modelo técnico interativo de ${esc(system.name)}"></canvas><div class="technical-scanlines"></div>
    <header class="technical-top immersive-hud"><button class="hud-icon" data-action="back">←</button><div class="target-chip"><span>${system.symbol}</span><div><b>${esc(system.name)}</b><small>Museu técnico · dados didáticos</small></div></div><div class="technical-top-actions"><span class="hud-status" id="technical-renderer">Canvas 2D</span><button class="hud-icon" data-action="toggle-help">?</button><button class="hud-icon" data-action="fullscreen">⛶</button></div></header>
    <div class="objective-chip technical-objective"><span>PROCEDIMENTO OPERACIONAL</span><b id="technical-objective">${step?esc(step.objective):'Procedimento concluído. Gere a evidência técnica.'}</b></div>
    <nav class="technical-system-rail immersive-hud">${TECHNICAL_SYSTEMS.map(item=>`<button class="${item.id===system.id?'active':''}" data-action="select-system" data-system="${item.id}" style="--system:${item.color}"><i>${item.symbol}</i><span><b>${esc(item.name)}</b><small>${item.subsystems.length} subsistemas</small></span></button>`).join('')}</nav>
    <nav class="technical-mode-rail immersive-hud">${TECHNICAL_VIEW_MODES.map(item=>`<button class="${item.id===snap.viewMode?'active':''}" data-action="set-view-mode" data-mode="${item.id}" title="${esc(item.description)}"><i>${item.short}</i><span>${esc(item.label)}</span></button>`).join('')}</nav>
    <aside class="technical-telemetry immersive-hud" id="technical-telemetry">${this.telemetryMarkup(snap)}</aside>
    <aside class="technical-subsystems immersive-hud"><span class="eyebrow">HOTSPOTS E SUBSISTEMAS</span><div>${system.subsystems.map(item=>`<button class="${item.id===sub.id?'active':''} ${snap.fault?.target===item.id?'fault':''}" data-action="select-subsystem" data-subsystem="${item.id}"><i>${item.icon}</i><span><b>${esc(item.name)}</b><small>${esc(item.sensors.join(' · '))}</small></span></button>`).join('')}</div></aside>
    <aside class="technical-detail immersive-hud"><header><div><span class="eyebrow">${sub.icon} ${esc(sub.name)}</span><h2>${esc(system.name)}</h2></div><nav><button class="${this.panelTab==='quick'?'active':''}" data-action="detail-tab" data-tab="quick">Rápido</button><button class="${this.panelTab==='expanded'?'active':''}" data-action="detail-tab" data-tab="expanded">Expandido</button><button class="${this.panelTab==='ds'?'active':''}" data-action="detail-tab" data-tab="ds">DS</button></nav></header>${this.detailMarkup(sub)}
      <section class="technical-command-section"><span class="eyebrow">COMANDOS</span><div>${system.commands.map(item=>`<button data-action="execute-command" data-command="${item.id}" class="${item.target===sub.id?'related':''}"><b>${esc(item.label)}</b><small>${esc(item.target)}</small></button>`).join('')}</div></section>
      <section class="technical-fault-section"><span class="eyebrow">ANOMALIAS DIDÁTICAS</span><div>${system.faults.map(item=>`<button data-action="inject-fault" data-fault="${item.id}" class="${snap.fault?.id===item.id?'active':''}"><b>${esc(item.label)}</b><small>${esc(item.severity)}</small></button>`).join('')}</div>${snap.fault?`<article class="technical-active-fault"><b>${esc(snap.fault.label)}</b><p>${esc(snap.fault.cause)}</p><small>Procedimento: ${esc(snap.fault.solution)}</small></article>`:''}</section>
    </aside>
    <aside class="technical-procedure immersive-hud"><header><span>ETAPAS ${snap.progress.steps}/${snap.progress.totalSteps}</span><b>${step?esc(step.title):'Procedimento concluído'}</b></header><div class="technical-procedure-progress"><i style="width:${Math.round(snap.progress.steps/snap.progress.totalSteps*100)}%"></i></div>${step?`<p>${esc(step.objective)}</p><small>Ação esperada: ${esc(step.requiredAction)}</small><em>${esc(step.evidence)}</em>`:'<p>Todos os checkpoints foram cumpridos.</p>'}<footer><button data-action="register-evidence">Registrar na trilha</button><button data-action="export-evidence">Exportar JSON</button><button class="secondary" data-action="open-workshop">Abrir oficina 3D</button><button class="secondary" data-action="open-related">Abrir laboratório 3D</button><button class="secondary" data-action="open-museum">Voltar ao museu</button></footer></aside>
    <button class="technical-log-toggle immersive-hud" data-action="toggle-log">LOG ${snap.actions.length}</button><aside class="technical-log immersive-hud ${this.logOpen?'open':''}"><button class="drawer-close" data-action="toggle-log">×</button><span class="eyebrow">LOG OPERACIONAL</span>${snap.actions.slice(-14).reverse().map(item=>`<p><b>${esc(item.type)}</b><small>${new Date(item.at).toLocaleTimeString('pt-BR')}</small></p>`).join('')||'<p>Nenhuma ação registrada.</p>'}</aside>
    <aside class="technical-help immersive-hud ${this.helpOpen?'open':''}"><button class="drawer-close" data-action="toggle-help">×</button><span class="eyebrow">COMO UTILIZAR</span><h3>Painel técnico em camadas</h3><p>Escolha um veículo, toque nos hotspots, alterne Exterior/Corte/Raio X/Desmontado e execute comandos para interpretar a telemetria.</p><div class="control-grid"><span><kbd>Mouse/toque</kbd> girar e selecionar</span><span><kbd>1–4</kbd> modos técnicos</span><span><kbd>S</kbd> próximo sistema</span><span><kbd>F</kbd> anomalia</span><span><kbd>E</kbd> evidência</span></div><p>Valores e falhas são modelos didáticos, não procedimentos operacionais reais.</p></aside>
    <div class="technical-loading" id="technical-loading"><i></i><span>Preparando painel e modelo técnico…</span></div>
  </div></section>`;}
  startRenderer(){const canvas=this.container.querySelector('#technical-cutaway-canvas');this.renderer=new TechnicalCutawayRenderer(canvas,this.context.settingsStore,{onSelect:id=>this.selectSubsystem(id),onDiagnostics:d=>{const el=this.container?.querySelector('#technical-renderer');if(el)el.textContent=`${d.renderer} · ${d.resolution}`;}});this.renderer.setSystem(this.model.system());this.renderer.setState(this.model.snapshot());this.renderer.start();this.last=performance.now();const tick=now=>{const dt=Math.min(.05,(now-this.last)/1000||.016);this.last=now;this.model.update(dt);this.renderer?.setState(this.model.snapshot());if(Math.floor(now/500)!==Math.floor((now-dt*1000)/500))this.updateTelemetry();this.raf=requestAnimationFrame(tick);};this.raf=requestAnimationFrame(tick);setTimeout(()=>this.container.querySelector('#technical-loading')?.classList.add('hidden'),450);}
  restart(){cancelAnimationFrame(this.raf);this.renderer?.destroy();this.render();this.startRenderer();}
  selectSystem(id){if(!this.model.selectSystem(id))return;sessionStorage.setItem('cosmos-ds-technical-target',id);this.panelTab='quick';this.restart();this.context.toast(`${this.model.system().name}: painel operacional carregado.`);}
  selectSubsystem(id){if(!this.model.selectSubsystem(id))return;this.panelTab='quick';const sub=this.model.system().subsystems.find(item=>item.id===id);this.context.recordGuidedEvent?.('technical-hotspot',{systemId:this.model.systemId,subsystemId:id});this.rerenderPreservingRenderer();this.checkGoals();if(sub)this.context.toast(`${sub.name}: sensores e software identificados.`);}
  rerenderPreservingRenderer(){cancelAnimationFrame(this.raf);this.renderer?.destroy();this.render();this.startRenderer();}
  setMode(id){if(!this.model.setViewMode(id))return;this.context.recordGuidedEvent?.('technical-view-mode',{systemId:this.model.systemId,mode:id});this.rerenderPreservingRenderer();this.checkGoals();}
  executeCommand(id){const result=this.model.executeCommand(id);if(!result.ok)return this.context.toast(result.reason);this.context.recordGuidedEvent?.('technical-command',{systemId:this.model.systemId,commandId:id});this.context.toast(result.command.message);this.rerenderPreservingRenderer();this.checkGoals();}
  injectFault(id){const fault=this.model.injectFault(id);if(!fault)return;this.context.recordGuidedEvent?.('technical-fault',{systemId:this.model.systemId,faultId:id});this.context.toast(`${fault.label}: analise a telemetria e aplique o procedimento.`);this.rerenderPreservingRenderer();}
  detailMarkup(sub){if(this.panelTab==='expanded')return `<p>${esc(sub.description)}</p><dl><div><dt>Sensores</dt><dd>${sub.sensors.map(esc).join(', ')}</dd></div><div><dt>Linguagens</dt><dd>${sub.languages.map(esc).join(', ')}</dd></div></dl>`;if(this.panelTab==='ds')return `<p>${esc(sub.ds)}</p><pre><code>sensor → validação → estado → comando → telemetria</code></pre><small>Observe responsabilidades separadas, limites e recuperação de falhas.</small>`;return `<p>${esc(sub.description)}</p><div class="technical-tags">${sub.sensors.map(item=>`<span>${esc(item)}</span>`).join('')}${sub.languages.map(item=>`<span class="language">${esc(item)}</span>`).join('')}</div>`;}
  telemetryMarkup(snap){return snap.telemetry.map(item=>`<div class="${item.state}"><span>${esc(item.label)}</span><b>${fmt(item.value,item.precision)} ${esc(item.unit)}</b><i><em style="width:${Math.max(0,Math.min(100,(item.value-item.min)/(item.max-item.min)*100))}%"></em></i></div>`).join('');}
  updateTelemetry(){const host=this.container?.querySelector('#technical-telemetry');if(host)host.innerHTML=this.telemetryMarkup(this.model.snapshot());}
  registerEvidence(){const evidence=this.model.evidence(this.context.profileStore.active()),summary=`${evidence.system.name}: ${evidence.session.procedure.steps}/${evidence.session.procedure.totalSteps} etapas; subsistemas ${evidence.session.inspectedSubsystems.join(', ')||'nenhum'}; modos ${evidence.session.viewModes.join(', ')}; falhas resolvidas ${evidence.session.resolvedFaults.length}.`;this.context.setGuidedEvidence?.(summary);this.context.recordGuidedEvent?.('manual-evidence',{systemId:this.model.systemId,summary});this.context.profileStore.addXp(140,`technical-evidence-${this.model.systemId}`);this.model.record('evidence:registered',{summary});this.context.toast('Evidência técnica registrada na jornada ativa.');this.checkGoals();}
  exportEvidence(){const evidence=this.model.evidence(this.context.profileStore.active());download(`cosmos-ds-${this.model.systemId}-evidencia.json`,JSON.stringify(evidence,null,2));this.model.record('evidence:exported',{});this.context.recordGuidedEvent?.('technical-evidence-exported',{systemId:this.model.systemId});this.context.profileStore.addXp(140,`technical-export-${this.model.systemId}`);this.context.toast('Evidência JSON exportada.');this.checkGoals();}
  checkGoals(){const p=this.model.progress(),checks=[['inspect-three',p.inspected>=3],['use-three-modes',p.modes>=3],['resolve-two',p.resolved>=2],['complete-procedure',p.completed],['export-evidence',this.model.actions.some(item=>item.type==='evidence:exported'||item.type==='evidence:registered')]];for(const [id,done] of checks){if(!done)continue;const goal=TECHNICAL_PANEL_GOALS.find(item=>item.id===id);if(this.context.profileStore.addXp(goal.xp,`technical-goal-${this.model.systemId}-${id}`))this.context.toast(`${goal.label}: +${goal.xp} XP.`);}}
  openRelated(){this.context.openModule(this.model.system().relatedModule);}
  openMuseum(){sessionStorage.setItem('cosmos-ds-museum-target',this.model.system().museumExhibit);this.context.openModule('visual-museum');}
  handleClick(event){const target=event.target.closest('[data-action]');if(!target)return;const action=target.dataset.action;if(action==='back')return this.context.onBack();if(action==='select-system')return this.selectSystem(target.dataset.system);if(action==='select-subsystem')return this.selectSubsystem(target.dataset.subsystem);if(action==='set-view-mode')return this.setMode(target.dataset.mode);if(action==='detail-tab'){this.panelTab=target.dataset.tab;return this.rerenderPreservingRenderer();}if(action==='execute-command')return this.executeCommand(target.dataset.command);if(action==='inject-fault')return this.injectFault(target.dataset.fault);if(action==='register-evidence')return this.registerEvidence();if(action==='export-evidence')return this.exportEvidence();if(action==='open-workshop'){sessionStorage.setItem('cosmos-ds-workshop-target',this.model.systemId);return this.context.openModule('space-workshop');}if(action==='open-related')return this.openRelated();if(action==='open-museum')return this.openMuseum();if(action==='toggle-log'){this.logOpen=!this.logOpen;this.container.querySelector('.technical-log')?.classList.toggle('open',this.logOpen);return;}if(action==='toggle-help'){this.helpOpen=!this.helpOpen;this.container.querySelector('.technical-help')?.classList.toggle('open',this.helpOpen);return;}if(action==='fullscreen')return this.container.querySelector('.technical-stage')?.requestFullscreen?.();}
  handleKey(event){if(['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName))return;const key=event.key.toLowerCase();if(['1','2','3','4'].includes(key))this.setMode(TECHNICAL_VIEW_MODES[Number(key)-1].id);if(key==='s'){const i=TECHNICAL_SYSTEMS.findIndex(item=>item.id===this.model.systemId);this.selectSystem(TECHNICAL_SYSTEMS[(i+1)%TECHNICAL_SYSTEMS.length].id);}if(key==='f')this.injectFault(this.model.system().faults[0].id);if(key==='e')this.registerEvidence();}
}
export const createModule=()=>new TechnicalOperationsModule();
