import { ImmersiveInputController } from '../../core/input/ImmersiveInputController.js';
import { CinematicStudioRenderer } from '../../rendering/CinematicStudioRenderer.js';
import { CINEMATIC_SCENES,CINEMATIC_FEATURES,CINEMATIC_GOALS } from '../../data/cinematicSystems.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
class CinematicStudioModule{
 constructor(){this.host=null;this.context=null;this.renderer=null;this.input=null;this.raf=0;this.last=0;this.yaw=.2;this.pitch=-.08;this.zoom=1;this.scene=0;this.scenesSeen=new Set();this.goals=new Set();this.cinema=false;this.settingsOff=null;this.onClick=e=>this.click(e);this.onInput=e=>this.inputChange(e);}
 mount(host,context){this.host=host;this.context=context;host.addEventListener('click',this.onClick);host.addEventListener('input',this.onInput);this.restore();this.render();this.start();this.settingsOff=context.bus.on('settings:changed',()=>this.restart());}
 restore(){for(const g of CINEMATIC_GOALS)if(this.context.profileStore.hasCompleted(`cinematic-${g.id}`))this.goals.add(g.id);}
 render(){const profile=this.context.settingsStore.getProfile();this.host.innerHTML=`<section class="cinematic-studio quality-${profile.id}"><div class="cinematic-stage"><canvas data-cinematic-canvas aria-label="Estúdio cinematográfico 3D e 360 graus"></canvas><header class="cinematic-top immersive-hud"><button data-action="back">←</button><div><span>FASE 20</span><b>ESTÚDIO CINEMATOGRÁFICO</b></div><div><span data-cine-profile>${profile.label}</span><button data-action="fullscreen">⛶</button></div></header><div class="objective-chip immersive-hud"><span>ILUMINAÇÃO E FOTOREALISMO</span><b data-cine-goals>${this.goals.size}/${CINEMATIC_GOALS.length} objetivos</b></div><nav class="cinematic-scenes immersive-hud">${CINEMATIC_SCENES.map((s,i)=>`<button data-action="scene" data-index="${i}" class="${i===0?'active':''}"><i>${s.icon}</i><span>${esc(s.label)}</span></button>`).join('')}</nav><aside class="cinematic-controls immersive-hud"><h3>Direção visual</h3><label>Exposição <input data-control="exposure" type="range" min="0.4" max="2.2" step="0.05" value="1.08"></label><button data-action="cinema">Modo cinema</button><button data-action="auto-exposure" class="active">Exposição automática</button><div class="cinematic-features">${CINEMATIC_FEATURES.map(f=>`<span>✓ ${f.label}</span>`).join('')}</div><button data-action="diagnostics">Analisar orçamento</button></aside><aside class="cinematic-diag immersive-hud" data-cine-diag><span>GPU estimada</span><b>-- ms</b><small>Ray steps -- · partículas --</small></aside><div class="virtual-joysticks cinematic-joysticks"><div class="virtual-joystick left" data-stick="left"><div class="joystick-ring"></div><div class="joystick-knob"></div><span>ZOOM</span></div><div class="virtual-joystick right" data-stick="right"><div class="joystick-ring"></div><div class="joystick-knob"></div><span>CÂMERA</span></div></div></div></section>`;}
 start(){const canvas=this.host.querySelector('[data-cinematic-canvas]');this.input=new ImmersiveInputController({canvas,root:this.host,leftStick:this.host.querySelector('[data-stick="left"]'),rightStick:this.host.querySelector('[data-stick="right"]')});this.input.attach();this.renderer=new CinematicStudioRenderer(canvas,this.context.settingsStore,{onDiagnostics:d=>this.updateDiag(d)});this.renderer.start();this.last=performance.now();const tick=now=>{const dt=Math.min(.05,(now-this.last)/1000||.016);this.last=now;const s=this.input.sample();this.yaw+=Number(s.lookX||0)*dt*1.7;this.pitch=Math.max(-1.25,Math.min(1.25,this.pitch+Number(s.lookY||0)*dt*1.4));this.zoom=Math.max(.55,Math.min(1.7,this.zoom-Number(s.forward||0)*dt*.5));this.renderer.setCamera(this.yaw,this.pitch,this.zoom);this.renderer.updateTelemetry({speed:Math.abs(s.forward||0)*10,luminance:.45+.2*Math.sin(now*.0003),danger:this.scene===0?.35:0});this.raf=requestAnimationFrame(tick);};this.raf=requestAnimationFrame(tick);}
 restart(){cancelAnimationFrame(this.raf);this.renderer?.destroy();this.input?.detach();this.start();}
 click(e){const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action;if(a==='back')return this.context.onBack();if(a==='fullscreen')return this.renderer.requestFullscreen();if(a==='scene'){this.scene=Number(b.dataset.index);this.renderer.setScene(this.scene);this.scenesSeen.add(this.scene);this.host.querySelectorAll('[data-action="scene"]').forEach(x=>x.classList.toggle('active',x===b));if(this.scenesSeen.size>=3)this.complete('compare-scenes');}if(a==='cinema'){this.cinema=!this.cinema;b.classList.toggle('active',this.cinema);this.renderer.setCinema(this.cinema);if(this.cinema)this.complete('enable-cinema');}if(a==='auto-exposure'){b.classList.toggle('active');this.renderer.controller.setAutoExposure(b.classList.contains('active'));}if(a==='diagnostics'){this.complete('inspect-budget');const d=this.renderer.controller.budget();this.context.toast(`Orçamento estimado: ${d.estimatedGpuMs} ms GPU, ${d.raySteps} passos.`);}}
 inputChange(e){if(e.target.matches('[data-control="exposure"]')){this.renderer.setExposure(e.target.value);this.complete('tune-exposure');}}
 updateDiag(d){const el=this.host?.querySelector('[data-cine-diag]');if(!el)return;const b=el.querySelector('b'),s=el.querySelector('small');if(b)b.textContent=`${d.estimatedGpuMs??this.renderer?.controller?.budget().estimatedGpuMs??'--'} ms`;if(s){const p=this.renderer?.profile();s.textContent=`Ray steps ${p?.steps??'--'} · partículas ${Math.round((p?.particles??0)*100)}%`;}}
 complete(id){if(this.goals.has(id))return;this.goals.add(id);const g=CINEMATIC_GOALS.find(x=>x.id===id);if(g&&this.context.profileStore.addXp(g.xp,`cinematic-${id}`))this.context.toast(`${g.label}: +${g.xp} XP`);const l=this.host.querySelector('[data-cine-goals]');if(l)l.textContent=`${this.goals.size}/${CINEMATIC_GOALS.length} objetivos`;if(this.goals.size===CINEMATIC_GOALS.length&&this.context.profileStore.addXp(500,'cinematic-certification'))this.context.toast('Certificação Direção Cinematográfica: +500 XP');}
 unmount(){cancelAnimationFrame(this.raf);this.renderer?.destroy();this.input?.detach();this.settingsOff?.();this.host?.removeEventListener('click',this.onClick);this.host?.removeEventListener('input',this.onInput);if(this.host)this.host.innerHTML='';}
}
export const createModule=()=>new CinematicStudioModule();
