import {
  SPACE_KNOWLEDGE, KNOWLEDGE_SOURCES, KNOWLEDGE_TYPES, KNOWLEDGE_TIMELINE,
  KNOWLEDGE_RECORDS, KNOWLEDGE_MYTH_CHALLENGES, KNOWLEDGE_COMPARE_DIMENSIONS
} from '../../data/knowledge/spaceKnowledge.js';
import { KnowledgeEngine } from '../../core/knowledge/KnowledgeEngine.js';
import { KnowledgeProfileStore } from '../../core/knowledge/KnowledgeProfileStore.js';
import { KnowledgeTimelineEngine } from '../../core/knowledge/KnowledgeTimelineEngine.js';
import { KnowledgeNarrator } from '../../core/knowledge/KnowledgeNarrator.js';
import { KnowledgeOrbRenderer } from '../../rendering/KnowledgeOrbRenderer.js';

const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const typeLabel=type=>({celestial:'Mundo',mission:'Missão',technology:'Tecnologia',person:'Pessoa',organization:'Agência/empresa',phenomenon:'Fenômeno',curiosity:'Curiosidade'}[type]||type);
const modeLabel=mode=>({explore:'Explorar',timeline:'Linha do tempo',myths:'Verdade ou mito',records:'Recordes'}[mode]||mode);

class CuriosityCenterModule {
  constructor(){
    this.container=null;this.context=null;this.engine=new KnowledgeEngine(SPACE_KNOWLEDGE,KNOWLEDGE_SOURCES);
    this.timelineEngine=new KnowledgeTimelineEngine(KNOWLEDGE_TIMELINE,KNOWLEDGE_SOURCES,SPACE_KNOWLEDGE.map(item=>item.id));
    this.narrator=new KnowledgeNarrator();this.profileState=null;this.renderer=null;
    this.selectedId='earth';this.query='';this.type='all';this.category='all';this.onlyFavorites=false;this.onlyUndiscovered=false;
    this.detailOpen=false;this.detailTab='quick';this.compareOpen=false;this.photoMode=false;this.results=[];
    this.mode='explore';this.timelineEra='all';this.timelineQuery='';this.mythIndex=0;this.mythFeedback=null;this.recordCategory='all';
    this.onClick=e=>this.handleClick(e);this.onInput=e=>this.handleInput(e);this.onKeyDown=e=>this.handleKeyDown(e);
  }
  mount(container,context){
    this.container=container;this.context=context;this.profileState=new KnowledgeProfileStore(context.settingsStore.storage,context.profileStore.active().id);
    const requested=sessionStorage.getItem('cosmos-ds-knowledge-target');sessionStorage.removeItem('cosmos-ds-knowledge-target');
    this.selectedId=this.engine.get(requested)?requested:this.engine.get(this.profileState.snapshot().lastViewed)?this.profileState.snapshot().lastViewed:'earth';
    this.results=this.engine.search();container.addEventListener('click',this.onClick);container.addEventListener('input',this.onInput);addEventListener('keydown',this.onKeyDown);this.render();this.startRenderer();
  }
  unmount(){this.renderer?.destroy();this.narrator.destroy();this.container?.removeEventListener('click',this.onClick);this.container?.removeEventListener('input',this.onInput);removeEventListener('keydown',this.onKeyDown);}
  selected(){return this.engine.get(this.selectedId)||this.engine.get('earth');}
  render(){
    const item=this.selected(),state=this.profileState.snapshot(),profile=this.context.settingsStore.getProfile(),stats=this.engine.stats();
    this.container.innerHTML=`<section class="knowledge-module quality-${profile.id}">
      <div class="knowledge-stage ${this.photoMode?'photo-mode':''} mode-${this.mode}" id="knowledge-stage">
        <canvas id="knowledge-canvas" aria-label="Visualização 3D e 360 graus do item selecionado"></canvas>
        <div class="knowledge-vignette" aria-hidden="true"></div><div class="knowledge-grid-horizon" aria-hidden="true"></div>
        <header class="knowledge-topbar immersive-hud">
          <button class="hud-icon" data-action="back" aria-label="Voltar">←</button>
          <div class="knowledge-target-chip"><i id="knowledge-target-symbol" style="--knowledge-a:${item.visual.colors[0]}">${escapeHtml(item.symbol)}</i><div><b id="knowledge-target-name">${escapeHtml(item.name)}</b><small id="knowledge-target-meta">${escapeHtml(typeLabel(item.type))} · ${escapeHtml(item.category)}</small></div></div>
          <div class="knowledge-top-actions"><span class="hud-status" id="knowledge-renderer">-- FPS</span><button class="hud-icon" data-action="narrate-summary" title="Ouvir resumo">🔊</button><button class="hud-icon" data-action="reset-view" title="Recentrar">◎</button><button class="hud-icon" data-action="fullscreen" title="Tela cheia">⛶</button><button class="hud-icon" data-action="toggle-photo" title="Modo foto">◫</button></div>
        </header>
        <div class="knowledge-objective objective-chip"><span>COSMOS CURIOSO · C1.2</span><b>Explore ${stats.total} fichas, marcos históricos, recordes, mitos e conexões com DS.</b></div>
        <nav class="knowledge-mode-bar immersive-hud" aria-label="Áreas da enciclopédia">${['explore','timeline','myths','records'].map(mode=>`<button class="${this.mode===mode?'active':''}" data-action="set-mode" data-mode="${mode}">${modeLabel(mode)}</button>`).join('')}</nav>
        <aside class="knowledge-search immersive-hud">
          <label><span>⌕</span><input id="knowledge-query" value="${escapeHtml(this.query)}" placeholder="Buscar mundo, missão, pessoa, linguagem, sensor…" autocomplete="off"></label>
          <div class="knowledge-type-row">${KNOWLEDGE_TYPES.map(entry=>`<button class="${this.type===entry.id?'active':''}" data-action="set-type" data-type="${entry.id}">${entry.label}</button>`).join('')}</div>
          <select id="knowledge-category" aria-label="Filtrar por categoria"><option value="all">Todas as categorias</option>${this.engine.categories().map(category=>`<option value="${escapeHtml(category)}" ${this.category===category?'selected':''}>${escapeHtml(category)}</option>`).join('')}</select>
          <div class="knowledge-filter-actions"><button class="${this.onlyFavorites?'active':''}" data-action="toggle-favorites">★ Favoritos</button><button class="${this.onlyUndiscovered?'active':''}" data-action="toggle-undiscovered">? Não vistos</button><button data-action="random-item">Aleatório</button></div>
        </aside>
        <aside class="knowledge-progress immersive-hud"><div><span>DESCOBERTAS</span><b>${state.discovered.length}/${SPACE_KNOWLEDGE.length}</b></div><div><span>LINHA DO TEMPO</span><b>${state.timelineViewed.length}/${KNOWLEDGE_TIMELINE.length}</b></div><div><span>MITOS</span><b>${Object.values(state.mythAnswers).filter(answer=>answer.correct).length}/${KNOWLEDGE_MYTH_CHALLENGES.length}</b></div></aside>
        <div class="knowledge-crosshair" aria-hidden="true"><i></i><i></i></div>
        <div class="knowledge-action-stack immersive-hud">
          <button data-action="discover-item">SCAN</button><button class="${state.favorites.includes(item.id)?'active':''}" data-action="favorite-item">★</button><button class="${state.comparison.includes(item.id)?'active':''}" data-action="compare-item">⇄</button><button data-action="open-detail">INFO</button><button data-action="open-related-module">3D</button>
        </div>
        <nav class="knowledge-card-rail immersive-hud" id="knowledge-card-rail">${this.cardsMarkup()}</nav>
        <aside class="knowledge-detail-drawer immersive-hud ${this.detailOpen?'open':''}" id="knowledge-detail-drawer" aria-hidden="${!this.detailOpen}">${this.detailMarkup()}</aside>
        <section class="knowledge-compare-overlay immersive-hud ${this.compareOpen?'open':''}" aria-hidden="${!this.compareOpen}">${this.comparisonMarkup()}</section>
        <section class="knowledge-insight-overlay immersive-hud ${this.mode!=='explore'?'open':''}" aria-hidden="${this.mode==='explore'}">${this.insightMarkup()}</section>
        <div class="knowledge-scan-flash" id="knowledge-scan-flash" aria-hidden="true"></div>
      </div>
    </section>`;
  }
  startRenderer(){const canvas=this.container.querySelector('#knowledge-canvas');this.renderer=new KnowledgeOrbRenderer(canvas,this.context.settingsStore,{onTelemetry:data=>this.updateTelemetry(data),onContextState:state=>{if(String(state).startsWith('fallback:'))this.context.toast('Visual simplificado ativado; todo o conteúdo continua disponível.');}});this.renderer.setTarget(this.selected());this.renderer.start();}
  filterResults(){this.results=this.engine.search(this.query,{type:this.type,category:this.category,favorites:this.profileState.snapshot().favorites,discovered:this.profileState.snapshot().discovered,onlyFavorites:this.onlyFavorites,onlyUndiscovered:this.onlyUndiscovered});}
  cardsMarkup(){this.filterResults();if(!this.results.length)return '<div class="knowledge-empty"><b>Nenhum item encontrado</b><span>Tente outro termo ou remova os filtros.</span></div>';return this.results.map(item=>`<button class="knowledge-card ${item.id===this.selectedId?'active':''}" data-action="select-item" data-id="${item.id}" style="--knowledge-a:${item.visual.colors[0]};--knowledge-b:${item.visual.colors[1]}"><i>${escapeHtml(item.symbol)}</i><span><b>${escapeHtml(item.name)}</b><small>${escapeHtml(item.category)}</small></span>${this.profileState.isFavorite(item.id)?'<em>★</em>':''}</button>`).join('');}
  detailMarkup(){const item=this.selected(),sources=this.engine.sourcesFor(item.id),related=this.engine.related(item.id),state=this.profileState.snapshot();return `<button class="drawer-close" data-action="close-detail">×</button>
    <div class="knowledge-detail-head"><i style="--knowledge-a:${item.visual.colors[0]}">${escapeHtml(item.symbol)}</i><div><span class="eyebrow">${escapeHtml(typeLabel(item.type))}</span><h2>${escapeHtml(item.name)}</h2><p>${escapeHtml(item.summary)}</p><div class="knowledge-narration-row"><button data-action="narrate-summary">🔊 Resumo</button><button data-action="narrate-description">AD Audiodescrição</button><button data-action="stop-narration">■ Parar</button></div></div></div>
    <div class="knowledge-detail-tabs"><button class="${this.detailTab==='quick'?'active':''}" data-action="detail-tab" data-tab="quick">Rápido</button><button class="${this.detailTab==='expanded'?'active':''}" data-action="detail-tab" data-tab="expanded">Descobrir</button><button class="${this.detailTab==='technical'?'active':''}" data-action="detail-tab" data-tab="technical">DS/Técnico</button></div>
    <div class="knowledge-detail-body">${this.detailTab==='quick'?this.quickMarkup(item):this.detailTab==='expanded'?this.expandedMarkup(item,sources,related):this.technicalMarkup(item)}</div>
    <div class="knowledge-detail-footer"><button class="button small ${state.favorites.includes(item.id)?'primary':'secondary'}" data-action="favorite-item">${state.favorites.includes(item.id)?'★ Favorito':'☆ Favoritar'}</button><button class="button small secondary" data-action="compare-item">Comparar</button><button class="button small primary" data-action="open-related-module">Abrir laboratório 3D</button></div>`;}
  quickMarkup(item){return `<article class="knowledge-highlight"><span>VOCÊ SABIA?</span><b>${escapeHtml(item.quickFact)}</b></article><div class="knowledge-metrics">${Object.entries(item.metrics||{}).slice(0,8).map(([key,value])=>`<div><span>${escapeHtml(key.toUpperCase())}</span><b>${escapeHtml(value)}</b></div>`).join('')}</div><p class="knowledge-approx">Valores físicos são aproximados quando indicado. Revisão do conteúdo: ${escapeHtml(item.lastReviewed)}.</p>`;}
  expandedMarkup(item,sources,related){return `<h3>Fatos essenciais</h3><div class="knowledge-fact-list">${(item.facts||[]).map(fact=>`<article><i>✓</i><span>${escapeHtml(fact)}</span></article>`).join('')}</div><h3>Curiosidades</h3><div class="knowledge-fact-list curiosity">${(item.curiosities||[]).map(fact=>`<article><i>✦</i><span>${escapeHtml(fact)}</span></article>`).join('')}</div><h3>Conexões</h3><div class="knowledge-related">${related.map(entry=>`<button data-action="select-related" data-id="${entry.id}"><i>${escapeHtml(entry.symbol)}</i><span>${escapeHtml(entry.name)}</span></button>`).join('')}</div><h3>Fontes oficiais</h3><div class="knowledge-sources">${sources.map(source=>`<button data-action="open-source" data-source="${source.id}"><b>${escapeHtml(source.organization)}</b><span>${escapeHtml(source.label)}</span></button>`).join('')}</div>`;}
  technicalMarkup(item){const t=item.technical||{systems:[],languages:[]};return `<article class="knowledge-architecture"><span>ARQUITETURA DIGITAL</span><h3>${escapeHtml(t.headline||'Sistemas relacionados')}</h3>${(t.systems||[]).map((system,index)=>`<div style="--depth:${index}"><i>${String(index+1).padStart(2,'0')}</i><b>${escapeHtml(system)}</b></div>`).join('')}</article><h3>Linguagens relacionadas</h3><div class="knowledge-language-tags">${(t.languages||[]).map(language=>`<span>${escapeHtml(language)}</span>`).join('')}</div><article class="knowledge-challenge"><span>DESAFIO DS</span><b>${escapeHtml(t.challenge||'Relacione dados, sensores e decisões do sistema.')}</b></article>`;}
  comparisonMarkup(){const state=this.profileState.snapshot(),basic=this.engine.compare(state.comparison),advanced=this.engine.compareAdvanced(state.comparison,KNOWLEDGE_COMPARE_DIMENSIONS);return `<header><div><span class="eyebrow">COMPARADOR ESPACIAL AVANÇADO</span><h2>Escala, gravidade, temperatura e distância</h2></div><button class="hud-icon" data-action="close-comparison">×</button></header>${basic.items.length?`<div class="knowledge-compare-items">${basic.items.map(item=>`<article style="--knowledge-a:${item.visual.colors[0]}"><i>${escapeHtml(item.symbol)}</i><b>${escapeHtml(item.name)}</b><button data-action="compare-item" data-id="${item.id}">remover</button></article>`).join('')}</div>${advanced.rows.length?`<div class="knowledge-compare-bars">${advanced.rows.map(row=>`<article><header><b>${escapeHtml(row.label)}</b><small>${row.scale==='log'?'escala logarítmica':'escala relativa'}</small></header>${row.values.map((value,index)=>`<div><span>${escapeHtml(advanced.items[index]?.name||'')}</span><i style="--value:${value.width}%"></i><em>${escapeHtml(value.label)}</em></div>`).join('')}</article>`).join('')}</div>`:''}<details class="knowledge-raw-compare"><summary>Ver métricas descritivas</summary><div class="knowledge-compare-table">${basic.metrics.slice(0,12).map(metric=>`<div><b>${escapeHtml(metric.key)}</b>${metric.values.map(value=>`<span>${escapeHtml(value)}</span>`).join('')}</div>`).join('')}</div></details><footer><button class="button secondary" data-action="clear-comparison">Limpar</button><button class="button primary" data-action="award-comparison" ${basic.items.length<2?'disabled':''}>Registrar comparação</button></footer>`:'<div class="knowledge-empty"><b>Selecione itens com o botão ⇄</b><span>Mundos possuem comparação quantitativa; missões e tecnologias permanecem na tabela descritiva.</span></div>'}`;}
  insightMarkup(){if(this.mode==='timeline')return this.timelineMarkup();if(this.mode==='myths')return this.mythMarkup();if(this.mode==='records')return this.recordsMarkup();return '';}
  insightHeader(title,subtitle){return `<header class="knowledge-insight-head"><div><span class="eyebrow">C1.2 · ${escapeHtml(modeLabel(this.mode))}</span><h2>${escapeHtml(title)}</h2><p>${escapeHtml(subtitle)}</p></div><button class="hud-icon" data-action="set-mode" data-mode="explore">×</button></header>`;}
  timelineMarkup(){const events=this.timelineEngine.list({era:this.timelineEra,query:this.timelineQuery}),state=this.profileState.snapshot(),range=this.timelineEngine.range();return `${this.insightHeader('Linha do tempo visual',`${range.start}–${range.end} · ${range.count} marcos conectados a pessoas, missões e tecnologias.`)}<div class="knowledge-timeline-tools"><label>⌕ <input id="knowledge-timeline-query" value="${escapeHtml(this.timelineQuery)}" placeholder="Buscar marco ou tecnologia"></label><div>${['all',...this.timelineEngine.categories()].map(era=>`<button class="${this.timelineEra===era?'active':''}" data-action="set-timeline-era" data-era="${escapeHtml(era)}">${era==='all'?'Todas':escapeHtml(era)}</button>`).join('')}</div></div><div class="knowledge-timeline-track">${events.map((event,index)=>`<button class="knowledge-timeline-event ${state.timelineViewed.includes(event.id)?'viewed':''}" data-action="open-timeline-item" data-id="${event.id}" style="--timeline-index:${index}"><span>${event.year}</span><i></i><article><b>${escapeHtml(event.title)}</b><p>${escapeHtml(event.summary)}</p><small>${escapeHtml(event.technology)}</small></article></button>`).join('')||'<div class="knowledge-empty"><b>Nenhum marco encontrado</b><span>Altere o filtro ou a busca.</span></div>'}</div>`;}
  mythMarkup(){const myth=KNOWLEDGE_MYTH_CHALLENGES[this.mythIndex%KNOWLEDGE_MYTH_CHALLENGES.length],saved=this.profileState.snapshot().mythAnswers[myth.id],feedback=this.mythFeedback?.id===myth.id?this.mythFeedback:saved;return `${this.insightHeader('Verdade ou mito',`Analise a afirmação, escolha uma resposta e abra a evidência relacionada.`)}<div class="knowledge-myth-card"><span>QUESTÃO ${this.mythIndex+1}/${KNOWLEDGE_MYTH_CHALLENGES.length}</span><h3>${escapeHtml(myth.statement)}</h3><div class="knowledge-myth-actions"><button data-action="answer-myth" data-answer="true">VERDADE</button><button data-action="answer-myth" data-answer="false">MITO</button></div>${feedback?`<article class="${feedback.correct?'correct':'wrong'}"><b>${feedback.correct?'Resposta correta':'Revise a evidência'}</b><p>${escapeHtml(myth.explanation)}</p><button data-action="open-related-insight" data-id="${myth.relatedId}">Abrir ficha relacionada</button></article>`:''}<footer><button data-action="previous-myth">← Anterior</button><button data-action="next-myth">Próxima →</button></footer></div>`;}
  recordsMarkup(){const categories=['all',...new Set(KNOWLEDGE_RECORDS.map(item=>item.category))],records=KNOWLEDGE_RECORDS.filter(item=>this.recordCategory==='all'||item.category===this.recordCategory),state=this.profileState.snapshot();return `${this.insightHeader('Recordes espaciais','Marcos de tamanho, temperatura, história e exploração com acesso à evidência relacionada.')}<div class="knowledge-record-filters">${categories.map(category=>`<button class="${this.recordCategory===category?'active':''}" data-action="set-record-category" data-category="${escapeHtml(category)}">${category==='all'?'Todos':escapeHtml(category)}</button>`).join('')}</div><div class="knowledge-record-grid">${records.map((record,index)=>`<button class="knowledge-record-card ${state.recordsViewed.includes(record.id)?'viewed':''}" data-action="open-record" data-id="${record.id}"><span>#${String(index+1).padStart(2,'0')} · ${escapeHtml(record.category)}</span><b>${escapeHtml(record.title)}</b><strong>${escapeHtml(record.value)}</strong><p>${escapeHtml(record.detail)}</p></button>`).join('')}</div>`;}
  selectItem(id,{openDetail=false}={}){const item=this.engine.get(id);if(!item)return;this.selectedId=id;this.profileState.setLastViewed(id);this.detailOpen=openDetail;this.detailTab='quick';this.mode='explore';this.renderer?.setTarget(item);this.renderAndRestart();}
  discover(){const item=this.selected(),fresh=this.profileState.discover(item.id);const flash=this.container.querySelector('#knowledge-scan-flash');flash?.classList.remove('active');requestAnimationFrame(()=>flash?.classList.add('active'));if(fresh){const awarded=this.context.profileStore.addXp(35,`knowledge-discovery-${item.id}`);if(awarded)this.context.toast(`Descoberta registrada: ${item.name} · +35 XP.`);}else this.context.toast(`${item.name} já faz parte da sua coleção.`);this.checkCertification();this.renderAndRestart();}
  checkCertification(){const state=this.profileState.snapshot(),types=new Set(state.discovered.map(id=>this.engine.get(id)?.type).filter(Boolean));if(state.discovered.length>=12&&types.size>=6){const awarded=this.context.profileStore.addXp(500,'knowledge-c12-certification');if(awarded)this.context.toast('Certificação Curador do COSMOS: +500 XP.');}if(Object.values(state.mythAnswers).filter(answer=>answer.correct).length===KNOWLEDGE_MYTH_CHALLENGES.length){const awarded=this.context.profileStore.addXp(220,'knowledge-c12-myths');if(awarded)this.context.toast('Todos os mitos investigados: +220 XP.');}}
  renderAndRestart(){this.renderer?.destroy();this.render();this.startRenderer();}
  narrate(mode){const ok=this.narrator.speak(this.selected(),mode);if(!ok)this.context.toast('Narração não está disponível neste navegador.');}
  openTimeline(id){const event=this.timelineEngine.get(id);if(!event)return;const fresh=this.profileState.viewTimeline(id);if(fresh)this.context.profileStore.addXp(20,`timeline-${id}`);this.selectItem(event.relatedId,{openDetail:true});}
  answerMyth(answer){const myth=KNOWLEDGE_MYTH_CHALLENGES[this.mythIndex%KNOWLEDGE_MYTH_CHALLENGES.length],value=answer==='true',correct=value===myth.answer,first=this.profileState.answerMyth(myth.id,value,correct);this.mythFeedback={id:myth.id,correct};if(first&&correct)this.context.profileStore.addXp(30,`myth-${myth.id}`);this.context.toast(correct?'Correto: evidência desbloqueada.':'Essa afirmação precisa ser revista.');this.checkCertification();this.renderAndRestart();}
  openRecord(id){const record=KNOWLEDGE_RECORDS.find(item=>item.id===id);if(!record)return;const fresh=this.profileState.viewRecord(id);if(fresh)this.context.profileStore.addXp(15,`record-${id}`);this.selectItem(record.relatedId,{openDetail:true});}
  handleClick(event){const target=event.target.closest('[data-action]');if(!target)return;const action=target.dataset.action;
    if(action==='back')return this.context.onBack();
    if(action==='select-item'||action==='select-related')return this.selectItem(target.dataset.id,{openDetail:action==='select-related'});
    if(action==='set-type'){this.type=target.dataset.type;this.renderAndRestart();return;}
    if(action==='set-mode'){this.mode=target.dataset.mode;this.compareOpen=false;this.detailOpen=false;this.renderAndRestart();return;}
    if(action==='toggle-favorites'){this.onlyFavorites=!this.onlyFavorites;this.renderAndRestart();return;}
    if(action==='toggle-undiscovered'){this.onlyUndiscovered=!this.onlyUndiscovered;this.renderAndRestart();return;}
    if(action==='random-item'){const item=this.engine.random(this.profileState.snapshot().discovered);this.selectItem(item.id);return;}
    if(action==='discover-item')return this.discover();
    if(action==='favorite-item'){this.profileState.toggleFavorite(target.dataset.id||this.selectedId);this.context.toast(this.profileState.isFavorite(target.dataset.id||this.selectedId)?'Adicionado aos favoritos.':'Removido dos favoritos.');this.renderAndRestart();return;}
    if(action==='compare-item'){this.profileState.toggleComparison(target.dataset.id||this.selectedId);this.compareOpen=true;this.renderAndRestart();return;}
    if(action==='open-detail'){this.detailOpen=true;this.renderAndRestart();return;}
    if(action==='close-detail'){this.detailOpen=false;this.renderAndRestart();return;}
    if(action==='detail-tab'){this.detailTab=target.dataset.tab;this.renderAndRestart();return;}
    if(action==='close-comparison'){this.compareOpen=false;this.renderAndRestart();return;}
    if(action==='clear-comparison'){this.profileState.clearComparison();this.renderAndRestart();return;}
    if(action==='award-comparison'){const ids=this.profileState.snapshot().comparison;if(ids.length>=2){const key=`knowledge-comparison-${[...ids].sort().join('-')}`;const awarded=this.context.profileStore.addXp(120,key);this.context.toast(awarded?'Comparação registrada: +120 XP.':'Esta comparação já foi registrada.');}return;}
    if(action==='open-related-module'){const module=this.selected().technical?.module;if(module)this.context.openModule(module);return;}
    if(action==='open-source'){const source=KNOWLEDGE_SOURCES[target.dataset.source];if(source)window.open(source.url,'_blank','noopener,noreferrer');return;}
    if(action==='reset-view')return this.renderer?.reset();
    if(action==='fullscreen')return this.renderer?.requestFullscreen();
    if(action==='toggle-photo'){this.photoMode=!this.photoMode;this.container.querySelector('#knowledge-stage')?.classList.toggle('photo-mode',this.photoMode);return;}
    if(action==='narrate-summary')return this.narrate('summary');
    if(action==='narrate-description')return this.narrate('description');
    if(action==='stop-narration')return this.narrator.stop();
    if(action==='set-timeline-era'){this.timelineEra=target.dataset.era;this.renderAndRestart();return;}
    if(action==='open-timeline-item')return this.openTimeline(target.dataset.id);
    if(action==='answer-myth')return this.answerMyth(target.dataset.answer);
    if(action==='previous-myth'){this.mythIndex=(this.mythIndex-1+KNOWLEDGE_MYTH_CHALLENGES.length)%KNOWLEDGE_MYTH_CHALLENGES.length;this.mythFeedback=null;this.renderAndRestart();return;}
    if(action==='next-myth'){this.mythIndex=(this.mythIndex+1)%KNOWLEDGE_MYTH_CHALLENGES.length;this.mythFeedback=null;this.renderAndRestart();return;}
    if(action==='open-related-insight')return this.selectItem(target.dataset.id,{openDetail:true});
    if(action==='set-record-category'){this.recordCategory=target.dataset.category;this.renderAndRestart();return;}
    if(action==='open-record')return this.openRecord(target.dataset.id);
  }
  handleInput(event){if(event.target.id==='knowledge-query')this.query=event.target.value;else if(event.target.id==='knowledge-category')this.category=event.target.value;else if(event.target.id==='knowledge-timeline-query'){this.timelineQuery=event.target.value;this.renderAndRestart();return;}else return;this.filterResults();const rail=this.container.querySelector('#knowledge-card-rail');if(rail)rail.innerHTML=this.cardsMarkup();}
  handleKeyDown(event){if(['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName))return;const key=event.key.toLowerCase();if(key==='i'){this.detailOpen=!this.detailOpen;this.renderAndRestart();}if(key==='s')this.discover();if(key==='r')this.renderer?.reset();if(key==='p'){this.photoMode=!this.photoMode;this.container.querySelector('#knowledge-stage')?.classList.toggle('photo-mode',this.photoMode);}if(key==='c'){this.compareOpen=!this.compareOpen;this.renderAndRestart();}if(key==='t'){this.mode='timeline';this.renderAndRestart();}if(key==='m'){this.mode='myths';this.renderAndRestart();}if(key==='v'){this.mode='records';this.renderAndRestart();}}
  updateTelemetry(data){const el=this.container.querySelector('#knowledge-renderer');if(el)el.textContent=`${data.fps||'--'} FPS · ${data.renderer}`;}
}

export function createModule(){return new CuriosityCenterModule();}
