import { readFile, readdir, stat } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { resolve, dirname, relative } from 'node:path';
const root=resolve(import.meta.dirname,'..');
const required=[
 'index.html','service-worker.js','public/manifest.webmanifest','src/main.js','src/app/CosmosApp.js','src/styles.css','src/styles-core.css','src/styles-labs.css',
 'src/modules/project-curation-studio/ProjectCurationStudioModule.js','src/core/projects/ProjectCurationEngine.js','src/core/projects/SourceReliabilityEngine.js','src/core/projects/StudentPortfolioStore.js','src/rendering/DigitalExhibitionRenderer.js','src/data/interdisciplinaryProjectSystems.js','public/data/project-curation/catalog.json',
 'src/modules/culture-discovery/CultureDiscoveryModule.js','src/core/culture/CultureDiscoveryEngine.js','src/core/culture/CultureDiscoveryStore.js','src/rendering/CulturalConstellationRenderer.js','src/data/cultureDiscoverySystems.js','public/data/culture-discovery/catalog.json',
 'src/modules/astrophotography-lab/AstrophotographyLabModule.js','src/core/astrophotography/AstrophotographySessionModel.js','src/rendering/AstrophotographyPipelineRenderer.js','src/data/astrophotographySystems.js','public/data/astrophotography/catalog.json',
 'src/modules/telescope-lab/TelescopeLabModule.js','src/core/telescope/ImmersiveTelescopeModel.js','src/rendering/TelescopeObservationRenderer.js','src/data/telescopeLabSystems.js','public/data/telescope-lab/catalog.json',
 'src/rendering/WebGLCosmosRenderer.js','src/rendering/PremiumAssetOverlayRenderer.js','src/rendering/HolographicRadarRenderer.js','src/rendering/EarthGlobeRenderer.js','src/rendering/RocketSceneRenderer.js','src/rendering/LunarSceneRenderer.js','src/rendering/MarsSceneRenderer.js','src/rendering/StationSceneRenderer.js','src/rendering/UniverseSceneRenderer.js','src/rendering/MissionDirectorRenderer.js','src/rendering/SolarSystemSceneRenderer.js','src/rendering/LaunchRemasterSceneRenderer.js','src/rendering/StationRemasterSceneRenderer.js','src/rendering/PlanetaryExplorationRenderer.js','src/rendering/DeepSpaceSceneRenderer.js','src/rendering/SpaceMuseumSceneRenderer.js','src/rendering/PremiumAssetSceneRenderer.js','src/rendering/KnowledgeOrbRenderer.js',
 'src/modules/space-workshop/SpaceWorkshopModule.js','src/core/workshop/SpaceAssemblyModel.js','src/rendering/SpaceAssemblyRenderer.js','src/data/spaceWorkshopSystems.js','public/data/workshop/catalog.json',
 'src/modules/technical-operations/TechnicalOperationsModule.js','src/core/technical/OperationalPanelModel.js','src/rendering/TechnicalCutawayRenderer.js','src/data/technicalMuseumSystems.js','public/data/technical/catalog.json',
 'src/modules/journey-center/JourneyCenterModule.js','src/modules/teacher-trail-studio/TeacherTrailStudioModule.js','src/core/guided/CustomTrailPlan.js','src/core/guided/CustomTrailRepository.js','src/core/guided/TeacherTrailDashboard.js','src/core/evidence/TrailEvidenceBuilder.js','src/data/teacherTrailSystems.js','public/data/teacher/catalog.json','src/core/loading/ModuleLoadCoordinator.js','src/core/guided/PlatformToolTour.js','src/core/guided/GuidedLessonPlanStore.js','src/data/guidedTrailDefinitions.js','src/data/guidedJourneySystems.js',
 'src/modules/technology-hub/TechnologyHubModule.js','src/core/technology/SpaceTechnologyEngine.js','src/core/guided/GuidedTrailStore.js','src/core/guided/GuidedTrailEngine.js','src/data/technologyGuidedSystems.js','src/rendering/TechnologyNetworkRenderer.js','public/data/technology/catalog.json',
 'src/modules/curiosity-center/CuriosityCenterModule.js','src/core/knowledge/KnowledgeEngine.js','src/core/knowledge/KnowledgeProfileStore.js','src/core/knowledge/KnowledgeTimelineEngine.js','src/core/knowledge/KnowledgeNarrator.js','src/data/knowledge/spaceKnowledge.js','src/data/knowledge/spaceKnowledgeExpansion.js','public/data/knowledge/catalog.json',
 'src/modules/premium-assets/PremiumAssetsModule.js','src/core/assets/PremiumIntegrationOrchestrator.js','src/core/assets/GlbGeometryParser.js','src/core/assets/GlbSceneParser.js','src/core/assets/GltfAnimationPlayer.js','src/core/assets/PremiumColliderSystem.js','src/core/assets/HdrEnvironmentParser.js','src/core/assets/PremiumAssetManager.js','src/core/assets/AssetPackCache.js','src/data/premiumAssetSystems.js','src/data/premiumIntegrationSystems.js','public/assets/premium/manifest.json','src/modules/deep-space-remaster/DeepSpaceRemasterModule.js','src/modules/visual-museum/VisualMuseumModule.js','src/core/deep-space/DeepSpaceNavigationModel.js','src/core/museum-remaster/MuseumExperienceModel.js','src/data/deepSpaceSystems.js','src/data/visualMuseumSystems.js','src/modules/lunar-mars-remaster/LunarMarsRemasterModule.js','src/core/lunar-mars-remaster/PlanetaryExplorationModel.js','src/data/lunarMarsRemasterSystems.js','src/workers/planetary-exploration.worker.js','src/modules/solar-remaster/SolarSystemRemasterModule.js','src/modules/launch-remaster/LaunchRemasterModule.js','src/modules/station-remaster/StationRemasterModule.js','src/core/launch-remaster/LaunchExperienceModel.js','src/data/launchRemasterSystems.js','src/core/station-remaster/OrbitalFlightModel.js','src/core/station-remaster/StationRemasterExperience.js','src/data/stationRemasterSystems.js','src/core/solar/SolarNavigationModel.js','src/core/input/ImmersiveInputController.js','src/data/solarSystemBodies.js','src/modules/academy/AcademyModule.js','src/modules/mission-control/MissionControlModule.js','src/modules/history/HistoryModule.js','src/modules/people/PeopleModule.js','src/modules/languages/LanguagesModule.js','src/modules/mission-control-advanced/MissionControlAdvancedModule.js','src/modules/earth-orbit/EarthOrbitModule.js','src/modules/launch/LaunchModule.js','src/modules/moon-apollo/MoonApolloModule.js','src/modules/mars-robotics/MarsRoboticsModule.js','src/modules/space-station/SpaceStationModule.js','src/modules/observatory/ObservatoryModule.js','src/modules/mission-director/MissionDirectorModule.js',
 'src/core/teacher/MissionPlan.js','src/core/teacher/GuidedSession.js','src/core/teacher/MissionRepository.js','src/core/evidence/EvidenceBuilder.js','src/core/xr/XRSupportService.js','src/core/accessibility/AccessibilityController.js','src/core/backup/ProfileBackupService.js','src/core/persistence/StorageDiagnostics.js','src/data/missionDirectorSystems.js',
 'src/modules/cinematic-studio/CinematicStudioModule.js','src/rendering/CinematicStudioRenderer.js','src/core/rendering/CinematicPostProcessController.js','src/data/cinematicSystems.js',
 'src/modules/physics-controls/PhysicsControlsModule.js','src/rendering/PhysicsArenaRenderer.js','src/core/physics/UnifiedPhysicsController.js','src/data/physicsControlSystems.js',
 'src/modules/integrated-campaigns/IntegratedCampaignsModule.js','src/rendering/CampaignCinematicRenderer.js','src/core/campaign/CampaignDirector.js','src/data/campaignSystems.js',
 'src/modules/performance-qa/PerformanceQAModule.js','src/rendering/QADiagnosticsRenderer.js','src/core/performance/PerformanceBudgetManager.js','src/core/performance/AssetStreamingManager.js','src/data/performanceSystems.js',
 'src/workers/telemetry.worker.js','src/workers/orbital.worker.js','src/workers/launch.worker.js','src/workers/lunar.worker.js','src/workers/mars.worker.js','src/workers/station.worker.js','src/workers/observatory.worker.js','src/workers/orbital-flight.worker.js','scripts/audit-graphics.mjs','.github/workflows/deploy-pages.yml'
];
for(const file of required)if(!existsSync(resolve(root,file)))throw new Error(`Arquivo obrigatório ausente: ${file}`);
async function walk(folder){const files=[];for(const entry of await readdir(folder)){const path=resolve(folder,entry),info=await stat(path);if(info.isDirectory())files.push(...await walk(path));else files.push(path);}return files;}
const jsFiles=(await walk(resolve(root,'src'))).filter(file=>file.endsWith('.js'));
const importPattern=/(?:from\s+|import\()(['"])(\.\.?\/[^'"]+)\1/g;
for(const file of jsFiles){const text=await readFile(file,'utf8');for(const match of text.matchAll(importPattern)){const target=resolve(dirname(file),match[2]);if(!existsSync(target))throw new Error(`Import não encontrado em ${relative(root,file)}: ${match[2]}`);}}
const manifest=JSON.parse(await readFile(resolve(root,'public/manifest.webmanifest'),'utf8'));if(!manifest.name||!manifest.start_url||!manifest.icons?.length)throw new Error('Manifesto PWA incompleto.');
const serviceWorker=await readFile(resolve(root,'service-worker.js'),'utf8');for(const match of serviceWorker.matchAll(/'\.\/([^']+)'/g)){const path=resolve(root,match[1]);if(!existsSync(path)&&!match[1].endsWith('/'))throw new Error(`Service Worker referencia arquivo inexistente: ${match[1]}`);}
const packageJson=JSON.parse(await readFile(resolve(root,'package.json'),'utf8'));if(packageJson.version!=='34.0.0')throw new Error('Versão esperada da C5.2: 34.0.0.');
const registry=await readFile(resolve(root,'src/core/modules/ModuleRegistry.js'),'utf8');const available=(registry.match(/status:'available'/g)||[]).length;if(available!==34)throw new Error(`Esperados 34 módulos disponíveis; encontrados ${available}.`);
const premiumManifest=JSON.parse(await readFile(resolve(root,'public/assets/premium/manifest.json'),'utf8'));
if(premiumManifest.schema!=='cosmos-ds-premium-assets-v2'||premiumManifest.assets?.length!==8)throw new Error('Manifesto premium incompleto.');
for(const asset of premiumManifest.assets){if(asset.lods?.length!==3)throw new Error(`Asset sem três LODs: ${asset.id}`);if(!asset.animations?.length||!asset.parts||!asset.colliders?.length)throw new Error(`Asset sem rig, animações ou colliders: ${asset.id}`);for(const lod of asset.lods)if(!existsSync(resolve(root,lod.url.replace(/^\.\//,''))))throw new Error(`GLB ausente: ${lod.url}`);}
const glbCount=(await walk(resolve(root,'public/assets/premium/models'))).filter(file=>file.endsWith('.glb')).length;if(glbCount!==24)throw new Error(`Esperados 24 arquivos GLB; encontrados ${glbCount}.`);
const integration=await readFile(resolve(root,'src/data/premiumIntegrationSystems.js'),'utf8');for(const id of ['launch-remaster','station-remaster','planetary-remaster','visual-museum'])if(!integration.includes(`'${id}'`))throw new Error(`Integração premium ausente: ${id}`);
const knowledge=await import('../src/data/knowledge/spaceKnowledge.js');
if(knowledge.SPACE_KNOWLEDGE.length!==57)throw new Error(`Catálogo C1.2 deve possuir 57 itens; encontrados ${knowledge.SPACE_KNOWLEDGE.length}.`);
if(Object.keys(knowledge.KNOWLEDGE_SOURCES).length<40)throw new Error('Catálogo C1.2 deve possuir ao menos 40 fontes oficiais.');
if(knowledge.KNOWLEDGE_TIMELINE.length!==18||knowledge.KNOWLEDGE_RECORDS.length!==10||knowledge.KNOWLEDGE_MYTH_CHALLENGES.length!==8)throw new Error('Linha do tempo, recordes ou mitos da C1.2 estão incompletos.');

const technology=await import('../src/data/technologyGuidedSystems.js');
if(technology.SPACE_TECHNOLOGIES.length!==10||technology.SPACE_LANGUAGES_C2.length!==10||technology.SPACE_SENSORS.length!==12)throw new Error('Catálogo técnico da C2.1 incompleto.');
if(technology.DIGITAL_ARCHITECTURE_LAYERS.length!==8||technology.TELEMETRY_SCENARIOS.length!==5||technology.TECHNOLOGY_CHALLENGES.length!==6)throw new Error('Laboratórios técnicos da C2.1 incompletos.');
const guided=await import('../src/data/guidedTrailDefinitions.js');
const journey=await import('../src/data/guidedJourneySystems.js');
if(guided.GUIDED_TRAILS.length!==7||guided.GUIDED_TRAILS.some(trail=>trail.steps.length<5))throw new Error('Trilhas guiadas da C5.2 incompletas.');
if(Object.keys(journey.GUIDED_STORIES).length!==7||journey.TOOL_TOUR_STEPS.length!==5||journey.LOADING_STAGES.length!==5)throw new Error('Narrativas, tour ou carregamento da C5.2 incompletos.');
if(/modules\/(technology-hub|curiosity-center)|assets\/premium|styles-labs/.test(serviceWorker))throw new Error('Service Worker não deve pré-carregar laboratórios ou assets premium na abertura.');
const mainSource=await readFile(resolve(root,'src/main.js'),'utf8');const appSource=await readFile(resolve(root,'src/app/CosmosApp.js'),'utf8');
if(!/styles-core\.css/.test(await readFile(resolve(root,'index.html'),'utf8')))throw new Error('A abertura deve usar apenas styles-core.css.');
if(!/requestIdleCallback/.test(mainSource)||!/import\('\.\/rendering\/WebGLCosmosRenderer\.js'\)/.test(mainSource))throw new Error('Fundo WebGL deve iniciar de forma ociosa e sob demanda.');
if(!/import\('\.\.\/core\/assets\/PremiumIntegrationOrchestrator\.js'\)/.test(appSource))throw new Error('Integração premium deve permanecer lazy-loaded.');
const techCatalog=JSON.parse(await readFile(resolve(root,'public/data/technology/catalog.json'),'utf8'));
if(techCatalog.schema!=='cosmos-ds-technology-catalog-v1'||techCatalog.trails!==7||!techCatalog.trailIds.includes('projects'))throw new Error('Catálogo público de tecnologia inválido.');
const teacher=await import('../src/data/teacherTrailSystems.js');
if(teacher.TEACHER_TRAIL_TEMPLATES.length!==3||teacher.TEACHER_TRAIL_EVENT_TYPES.length!==4||teacher.TEACHER_TRAIL_ADAPTATIONS.length!==3)throw new Error('Fundação de autoria da C2.3 incompleta.');
const teacherCatalog=JSON.parse(await readFile(resolve(root,'public/data/teacher/catalog.json'),'utf8'));
if(teacherCatalog.schema!=='cosmos-ds-teacher-trails-v1'||!teacherCatalog.capabilities?.activeTimePerStep||!teacherCatalog.capabilities?.printToPdf)throw new Error('Catálogo público do professor inválido.');
if(!/CustomTrailRepository/.test(appSource)||!/teacher-trail-studio/.test(registry))throw new Error('Integração de trilhas personalizadas ausente.');
const technical=await import('../src/data/technicalMuseumSystems.js');
if(technical.TECHNICAL_SYSTEMS.length!==5||technical.TECHNICAL_VIEW_MODES.length!==4||technical.TECHNICAL_PANEL_GOALS.length!==5)throw new Error('Museu técnico C3.1 incompleto.');
if(technical.TECHNICAL_SYSTEMS.some(system=>system.subsystems.length<5||system.telemetry.length<6||system.procedure.length<4))throw new Error('Painéis operacionais C3.1 sem profundidade mínima.');
const workshop=await import('../src/data/spaceWorkshopSystems.js');
if(workshop.SPACE_WORKSHOP_SYSTEMS.length!==5||workshop.WORKSHOP_DIFFICULTIES.length!==3||workshop.WORKSHOP_FLOW_TYPES.length!==3||workshop.WORKSHOP_GOALS.length!==5)throw new Error('Oficina Espacial C3.2 incompleta.');
if(workshop.SPACE_WORKSHOP_SYSTEMS.some(system=>system.components.length<6||system.links.length<10||system.faults.length<3))throw new Error('Oficinas C3.2 sem profundidade mínima.');
const technicalCatalog=JSON.parse(await readFile(resolve(root,'public/data/technical/catalog.json'),'utf8'));
if(technicalCatalog.schema!=='cosmos-ds-technical-panels-v1'||technicalCatalog.systems!==5)throw new Error('Catálogo público dos painéis técnicos inválido.');
const telescope=await import('../src/data/telescopeLabSystems.js');
if(telescope.TELESCOPE_CATALOG.length!==7||telescope.TELESCOPE_TARGETS.length!==10||telescope.TELESCOPE_EYEPIECES.length!==4||telescope.TELESCOPE_FILTERS.length!==6||telescope.SKY_CONDITIONS.length!==5)throw new Error('Laboratório de telescópios C4.1 incompleto.');
if(telescope.TELESCOPE_CATALOG.some(item=>!item.parts?.length||!item.strengths?.length||!item.limits?.length))throw new Error('Catálogo de telescópios sem profundidade mínima.');
const telescopeCatalog=JSON.parse(await readFile(resolve(root,'public/data/telescope-lab/catalog.json'),'utf8'));
if(telescopeCatalog.schema!=='cosmos-ds-telescope-lab-v1'||telescopeCatalog.instruments!==7||!telescopeCatalog.capabilities?.guidedEvidence)throw new Error('Catálogo público de telescópios inválido.');

const astrophotography=await import('../src/data/astrophotographySystems.js');
if(astrophotography.ASTRO_CAMERAS.length!==4||astrophotography.ASTRO_TARGETS.length!==6||astrophotography.ASTRO_CAPTURE_PRESETS.length!==4||astrophotography.ASTRO_CALIBRATION_FRAMES.length!==3)throw new Error('Laboratório de astrofotografia C4.2 incompleto.');
if(astrophotography.ASTRO_STACK_METHODS.length!==3||astrophotography.ASTRO_PALETTES.length!==4||astrophotography.ASTRO_SESSION_CONDITIONS.length!==4||astrophotography.ASTRO_OPTICAL_SETUPS.length!==4)throw new Error('Pipeline de processamento C4.2 incompleto.');
const astroCatalog=JSON.parse(await readFile(resolve(root,'public/data/astrophotography/catalog.json'),'utf8'));
if(astroCatalog.schema!=='cosmos-ds-astrophotography-lab-v1'||astroCatalog.cameras!==4||!astroCatalog.capabilities?.alignmentAndStacking||!astroCatalog.capabilities?.offlineProcedural)throw new Error('Catálogo público de astrofotografia inválido.');
if(/astrophotography-lab|astrophotographySystems|AstrophotographyPipelineRenderer/.test(serviceWorker))throw new Error('Service Worker não deve pré-carregar o laboratório de astrofotografia.');

const culture=await import('../src/data/cultureDiscoverySystems.js');
if(culture.SPACE_ORGANIZATIONS.length!==12||culture.SPACE_CAREERS.length!==12||culture.SPACE_CULTURE_WORKS.length!==14)throw new Error('Catálogo cultural C5.1 incompleto.');
if(culture.CULTURE_DISCOVERY_TRAILS.length!==6||culture.CULTURE_DISCUSSION_PROMPTS.length!==8||culture.CULTURE_DISCOVERY_GOALS.length!==6)throw new Error('Trilhas, discussões ou objetivos da C5.1 incompletos.');
if(culture.SPACE_ORGANIZATIONS.some(item=>!culture.CULTURE_SOURCES[item.sourceId]||!item.modules?.length))throw new Error('Organização cultural sem fonte oficial ou laboratório relacionado.');
if(culture.SPACE_CULTURE_WORKS.some(item=>!item.science?.length||!item.fiction?.length||!item.modules?.length))throw new Error('Obra cultural sem separação entre ciência, ficção e laboratório.');
const cultureCatalog=JSON.parse(await readFile(resolve(root,'public/data/culture-discovery/catalog.json'),'utf8'));
if(cultureCatalog.schema!=='cosmos-ds-culture-discovery-v1'||cultureCatalog.organizations!==12||cultureCatalog.careers!==12||cultureCatalog.works!==14||!cultureCatalog.capabilities?.noCopyrightedMedia)throw new Error('Catálogo público cultural inválido.');
if(/culture-discovery|cultureDiscoverySystems|CulturalConstellationRenderer/.test(serviceWorker))throw new Error('Service Worker não deve pré-carregar a Central de Cultura Espacial.');

const projects=await import('../src/data/interdisciplinaryProjectSystems.js');
if(projects.INTERDISCIPLINARY_PROJECTS.length!==6||projects.CAREER_SIMULATIONS.length!==8||projects.SOURCE_RELIABILITY_CASES.length!==8)throw new Error('Catálogo de projetos e carreiras C5.2 incompleto.');
if(projects.SOURCE_RELIABILITY_CRITERIA.length!==5||projects.PROJECT_COMPETENCIES.length!==10||projects.EXHIBITION_THEMES.length!==4)throw new Error('Rubrica, competências ou temas C5.2 incompletos.');
if(projects.INTERDISCIPLINARY_PROJECTS.some(item=>item.modules.length<3||item.roles.length<3||item.deliverables.length<4))throw new Error('Projetos C5.2 sem profundidade mínima.');
if(projects.CAREER_SIMULATIONS.some(item=>item.choices.length!==3||!item.modules.length))throw new Error('Simulações de carreira C5.2 incompletas.');
const projectCatalog=JSON.parse(await readFile(resolve(root,'public/data/project-curation/catalog.json'),'utf8'));
if(projectCatalog.schema!=='cosmos-ds-project-curation-v1'||projectCatalog.projects!==6||projectCatalog.careerSimulations!==8||!projectCatalog.capabilities?.digitalExhibition)throw new Error('Catálogo público de projetos C5.2 inválido.');
if(/project-curation-studio|interdisciplinaryProjectSystems|DigitalExhibitionRenderer/.test(serviceWorker))throw new Error('Service Worker não deve pré-carregar o Estúdio de Projetos.');
const cultureModuleC52=await readFile(resolve(root,'src/modules/culture-discovery/CultureDiscoveryModule.js'),'utf8');
if(!cultureModuleC52.includes("openModule('project-curation-studio')"))throw new Error('Central de Cultura deve navegar para Projetos e Portfólio.');
const peopleModule=await readFile(resolve(root,'src/modules/people/PeopleModule.js'),'utf8');const historyModule=await readFile(resolve(root,'src/modules/history/HistoryModule.js'),'utf8');if(!peopleModule.includes("openModule('culture-discovery')")||!historyModule.includes("openModule('culture-discovery')"))throw new Error('Pessoas e História devem oferecer navegação bidirecional para Cultura Espacial.');
console.log(`COSMOS DS C5.2 validado: ${jsFiles.length} arquivos JavaScript, ${required.length} arquivos obrigatórios, ${available} módulos, ${knowledge.SPACE_KNOWLEDGE.length} fichas, ${knowledge.KNOWLEDGE_TIMELINE.length} marcos, ${knowledge.KNOWLEDGE_RECORDS.length} recordes e ${knowledge.KNOWLEDGE_MYTH_CHALLENGES.length} mitos, ${technology.SPACE_SENSORS.length} sensores, ${guided.GUIDED_TRAILS.length} trilhas guiadas, ${culture.SPACE_ORGANIZATIONS.length} organizações, ${culture.SPACE_CAREERS.length} carreiras, ${projects.INTERDISCIPLINARY_PROJECTS.length} projetos e ${projects.CAREER_SIMULATIONS.length} simulações profissionais com abertura leve sob demanda.`);
