import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { requireLiveAuthSession } from "./session-guard.ts";
import {createClient} from "jsr:@supabase/supabase-js@2.111.0";
import {consumeRate,ensureAccess,logRisk,requestIp} from "./security.ts";
const H={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"},J=(x:unknown,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{...H,"Content-Type":"application/json"}});
const risky=[['eval()',/\beval\s*\(/i],['new Function',/\bnew\s+Function\s*\(/i],['document.cookie',/\bdocument\s*\.\s*cookie\b/i],['top/parent navigation',/\b(?:window\s*\.\s*top|top\s*\.\s*location|parent\s*\.\s*location)\b/i],['sendBeacon',/\bnavigator\s*\.\s*sendBeacon\s*\(/i],['WebSocket/EventSource',/\b(?:WebSocket|EventSource)\s*\(/i],['iframe/object/embed',/<\s*(?:iframe|object|embed)\b/i],['javascript: URL',/javascript\s*:/i],['Python process/socket',/\b(?:subprocess|os\s*\.\s*system|import\s+socket|from\s+socket)\b/i],['Python JS bridge',/\b(?:import\s+js|from\s+js\s+import|pyfetch|micropip)\b/i]] as const;
const network=[['fetch',/\bfetch\s*\(/i],['XMLHttpRequest',/\bXMLHttpRequest\b/i],['external script',/<script[^>]+src\s*=\s*["']https?:\/\//i],['importScripts',/\bimportScripts\s*\(/i]] as const;
const fileAliases=(value:string)=>{const n=String(value||'').trim().toLowerCase(),out=new Set([n]);if(n==='style.css')out.add('estilo.css');if(n==='estilo.css')out.add('style.css');if(n==='app.js')out.add('script.js');if(n==='script.js')out.add('app.js');if(n==='atividade.md')out.add('referencia.md');if(n==='referencia.md')out.add('atividade.md');if(n==='mainactivity.kt')out.add('main.kt');if(n==='main.kt')out.add('mainactivity.kt');return [...out]};
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:H});if(Number(req.headers.get('content-length')||0)>1200000)return J({error:'payload_too_large'},413);try{
 const url=Deno.env.get('SUPABASE_URL')!,auth=req.headers.get('Authorization')||'',uc=createClient(url,Deno.env.get('SUPABASE_ANON_KEY')!,{global:{headers:{Authorization:auth}}}),db=createClient(url,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,{auth:{persistSession:false,autoRefreshToken:false}}),{data:{user}}=await uc.auth.getUser();if(!user)return J({error:'unauthorized'},401);const live=await requireLiveAuthSession(db,auth,user.id);if(!live.ok)return J({error:live.error,detail:live.detail||null},live.status);
 const {data:p}=await db.from('profiles').select('active,must_change_password,role').eq('id',user.id).maybeSingle();if(!p?.active||p.must_change_password||p.role!=='student')return J({error:'student_not_ready'},403);await ensureAccess(db,user,req,'student-files');const b=await req.json().catch(()=>({})),action=String(b?.action||''),eid=String(b?.exercise_id||'');const rl=await consumeRate(db,`student-files:${user.id}:${requestIp(req)||'noip'}`,180,60,120);if(rl.allowed===false){await logRisk(db,user,req,'rate_limit','high',{source:'student-files',action,count:rl.count});return new Response(JSON.stringify({error:'rate_limited',retry_after:rl.retry_after||120}),{status:429,headers:{...H,'Content-Type':'application/json','Retry-After':String(rl.retry_after||120)}})};if(!eid)return J({error:'missing_exercise'},400);
 const {data:m}=await db.from('class_memberships').select('class_id').eq('user_id',user.id).eq('active',true).order('is_primary',{ascending:false}).limit(1).maybeSingle();if(!m)return J({error:'no_class'},403);const {data:e}=await db.from('exercises').select('id,class_id,subject_id,default_locked').eq('id',eid).eq('active',true).eq('visible',true).maybeSingle();if(!e)return J({error:'exercise_forbidden'},403);
 let belongs=false;if(e.class_id)belongs=e.class_id===m.class_id;else{const {data:cs}=await db.from('class_subjects').select('class_id').eq('class_id',m.class_id).eq('subject_id',e.subject_id).eq('active',true).maybeSingle();belongs=!!cs}if(!belongs)return J({error:'exercise_forbidden'},403);
 const {data:pr}=await db.from('student_exercises').select('status,security_locked,security_lock_reason').eq('student_id',user.id).eq('exercise_id',eid).maybeSingle();if(pr?.security_locked||pr?.status==='blocked')return J({error:'activity_locked',reason:pr?.security_lock_reason||'Atividade bloqueada.'},423);
 let released=!e.default_locked;const {data:sr}=await db.from('exercise_releases').select('enabled,release_at,lock_at').eq('student_id',user.id).eq('exercise_id',eid).order('updated_at',{ascending:false}).limit(1).maybeSingle();if(sr)released=sr.enabled&&(!sr.release_at||Date.parse(sr.release_at)<=Date.now())&&(!sr.lock_at||Date.parse(sr.lock_at)>Date.now());else{const {data:cr}=await db.from('exercise_releases').select('enabled,release_at,lock_at').is('student_id',null).eq('class_id',m.class_id).eq('exercise_id',eid).order('updated_at',{ascending:false}).limit(1).maybeSingle();if(cr)released=cr.enabled&&(!cr.release_at||Date.parse(cr.release_at)<=Date.now())&&(!cr.lock_at||Date.parse(cr.lock_at)>Date.now())}if(!released)return J({error:'exercise_locked_by_teacher'},423);
 const {data:policy}=await db.from('exercise_security_policies').select('block_external_network').eq('exercise_id',eid).maybeSingle();const findings=(content:string)=>{const out:string[]=[];for(const [n,r] of risky)if(r.test(content))out.push(n);if(policy?.block_external_network)for(const [n,r] of network)if(r.test(content))out.push(n);return out};
 const reject=async(content:string,filename:string)=>{const f=findings(content);if(!f.length)return null;const eventType=f.some(x=>['fetch','XMLHttpRequest','external script','importScripts'].includes(x))?'external_network_attempt':'malicious_code_pattern';await db.from('security_events').insert({student_id:user.id,exercise_id:eid,event_type:eventType,severity:'critical',confidence:'objective',details:{filename,patterns:f,server_rejected:true},ip_address:requestIp(req)});await logRisk(db,user,req,eventType,'critical',{source:'student-files',exercise_id:eid,filename,patterns:f});return J({error:'malicious_code_rejected',patterns:f},422)};
 if(action==='ensure'){const {data:old}=await db.from('student_files').select('id,filename,language,content,revision,saved_at').eq('student_id',user.id).eq('exercise_id',eid).order('filename');const clean:any[]=[];for(const f of (Array.isArray(b?.files)?b.files.slice(0,10):[])){const filename=String(f?.filename||'').replace(/[^a-zA-Z0-9._-]/g,'').slice(0,120),content=String(f?.content||'').slice(0,1000000);if(!filename)continue;const r=await reject(content,filename);if(r)return r;clean.push({student_id:user.id,exercise_id:eid,filename,language:String(f?.language||'text').slice(0,40),content});}if(!clean.length)return old?.length?J({files:old}):J({error:'no_files'},400);const existingAliases=new Set((old||[]).flatMap((f:any)=>fileAliases(f.filename))),missing=clean.filter((f:any)=>!fileAliases(f.filename).some(n=>existingAliases.has(n)));if(missing.length){const {error}=await db.from('student_files').insert(missing);if(error)throw error;}const {data:all,error:allError}=await db.from('student_files').select('id,filename,language,content,revision,saved_at').eq('student_id',user.id).eq('exercise_id',eid).order('filename');if(allError)throw allError;return J({files:all||[],reconciled:missing.length,existing:(old||[]).length})}
 if(action==='save'){const id=String(b?.file_id||''),content=String(b?.content??'');if(!id||content.length>1000000)return J({error:'invalid_file'},400);const {data:t}=await db.from('student_files').select('filename').eq('id',id).eq('student_id',user.id).eq('exercise_id',eid).maybeSingle();if(!t)return J({error:'file_not_found'},404);const r=await reject(content,t.filename);if(r)return r;const {data,error}=await db.from('student_files').update({content}).eq('id',id).eq('student_id',user.id).eq('exercise_id',eid).select('id,filename,language,content,revision,saved_at').maybeSingle();if(error)throw error;return J({file:data})}
 if(action==='save_all'||action==='checkpoint'){const items=Array.isArray(b?.files)?b.files.slice(0,10):[];if(!items.length)return J({error:'no_files'},400);const saved:any[]=[];for(const f of items){const id=String(f?.file_id||''),content=String(f?.content??'');if(!id||content.length>1000000)return J({error:'invalid_file',file_id:id||null},400);const {data:t}=await db.from('student_files').select('filename').eq('id',id).eq('student_id',user.id).eq('exercise_id',eid).maybeSingle();if(!t)return J({error:'file_not_found',file_id:id},404);const r=await reject(content,t.filename);if(r)return r;const {data,error}=await db.from('student_files').update({content}).eq('id',id).eq('student_id',user.id).eq('exercise_id',eid).select('id,filename,language,content,revision,saved_at').maybeSingle();if(error)throw error;if(data)saved.push(data)}return J({ok:true,manual:true,files:saved,saved_at:new Date().toISOString()})}
 return J({error:'unknown_action'},400);
}catch(e){console.error(e);return J({error:'internal_error',detail:String((e as Error)?.message||e)},500)}});
