export const txt=(v:unknown,n=500)=>String(v??'').trim().slice(0,n);
export const requestIp=(req:Request)=>{const cf=txt(req.headers.get('cf-connecting-ip'),128);if(cf)return cf;const real=txt(req.headers.get('x-real-ip'),128);if(real)return real;const xs=txt(req.headers.get('x-forwarded-for'),512).split(',').map(x=>x.trim()).filter(Boolean);return xs.length?txt(xs[xs.length-1],128):null};
const now=()=>new Date().toISOString();
const rank=(v:string)=>({info:0,warning:1,high:2,critical:3} as Record<string,number>)[v]??0;
const maxSeverity=(a:string,b:string)=>rank(a)>=rank(b)?a:b;
export async function consumeRate(db:any,key:string,limit:number,window:number,block:number){const{data,error}=await db.rpc('security_consume_rate_limit',{p_key:key,p_limit:limit,p_window_seconds:window,p_block_seconds:block});return error?{allowed:true,count:0,retry_after:0}:(data||{allowed:true,count:0,retry_after:0})}
async function geoFor(db:any,ip:string|null){if(!ip)return{lookup_ok:false,country_code:null,region:null,region_code:null,city:null,asn:null,organization:null};const{data:c}=await db.from('security_ip_cache').select('*').eq('ip_address',ip).gt('expires_at',now()).maybeSingle();if(c)return c;let g:any={lookup_ok:false,country_code:null,region:null,region_code:null,city:null,asn:null,organization:null,raw:{}};try{const ctl=new AbortController(),timer=setTimeout(()=>ctl.abort(),2200),r=await fetch(`https://ipapi.co/${encodeURIComponent(ip)}/json/`,{signal:ctl.signal,headers:{'user-agent':'AGV-Security/1.0'}});clearTimeout(timer);const x=await r.json().catch(()=>({}));if(r.ok&&!x?.error)g={lookup_ok:true,country_code:txt(x.country_code||x.country,8)||null,region:txt(x.region,120)||null,region_code:txt(x.region_code,16)||null,city:txt(x.city,120)||null,asn:txt(x.asn,80)||null,organization:txt(x.org,240)||null,raw:x}}catch(_){ }const ttl=g.lookup_ok?7*86400_000:1800_000,row={ip_address:ip,...g,looked_up_at:now(),expires_at:new Date(Date.now()+ttl).toISOString()};try{await db.from('security_ip_cache').upsert(row,{onConflict:'ip_address'})}catch(_){ }return row}
function risk(g:any){if(!g?.lookup_ok)return{severity:'info',risk_code:null,outside_parana:false,geo_status:'unknown'};const cc=String(g.country_code||'').toUpperCase(),rc=String(g.region_code||'').toUpperCase();if(cc==='BR'&&rc==='PR')return{severity:'info',risk_code:null,outside_parana:false,geo_status:'parana'};if(cc&&((cc!=='BR')||(rc&&rc!=='PR')))return{severity:'critical',risk_code:'outside_parana',outside_parana:true,geo_status:'outside_parana'};return{severity:'warning',risk_code:'geo_inconclusive',outside_parana:false,geo_status:'inconclusive'}}
function reqId(req:Request){return txt(req.headers.get('cf-ray')||req.headers.get('x-request-id')||crypto.randomUUID(),160)}
export async function ensureAccess(db:any,user:any,req:Request,source:string){const ip=requestIp(req);if(!ip)return;const since=new Date(Date.now()-3600_000).toISOString(),{data:old}=await db.from('agv_core_security_events').select('id').eq('user_id',user.id).eq('ip_address',ip).eq('category','access_security').gte('created_at',since).limit(1);if((old||[]).length)return;const g=await geoFor(db,ip),r=risk(g);await db.from('agv_core_security_events').insert({user_id:user.id,category:'access_security',severity:r.severity,payload:{event_code:'server.endpoint_access',source,geo_status:r.geo_status,outside_parana:r.outside_parana},ip_address:ip,country_code:g.country_code||null,region:g.region||null,region_code:g.region_code||null,city:g.city||null,asn:g.asn||null,organization:g.organization||null,request_id:reqId(req),user_agent:txt(req.headers.get('user-agent'),500)||null,risk_code:r.risk_code})}
export async function logRisk(db:any,user:any,req:Request,eventCode:string,severity:string,payload:any={}){const ip=requestIp(req),g=await geoFor(db,ip),r=risk(g),final=maxSeverity(severity,r.severity);await db.from('agv_core_security_events').insert({user_id:user?.id||null,category:'application_security',severity:final,payload:{event_code:eventCode,source:payload?.source||null,details:payload||{},geo_status:r.geo_status,outside_parana:r.outside_parana},ip_address:ip,country_code:g.country_code||null,region:g.region||null,region_code:g.region_code||null,city:g.city||null,asn:g.asn||null,organization:g.organization||null,request_id:reqId(req),user_agent:txt(req.headers.get('user-agent'),500)||null,risk_code:r.risk_code||eventCode})}
