'use strict';

(function(){
  window.LABDS_LABS=window.LABDS_LABS||{};
  let root=null,ctx=null,state=null,worker=null,ready=false,requestCounter=0,pending=new Map(),schemaCache=[];
  const STORAGE_KEY='lab.sql.state';
  const defaults={schemaVersion:1,sql:`CREATE TABLE IF NOT EXISTS alunos (
  id INTEGER PRIMARY KEY,
  nome TEXT NOT NULL,
  turma TEXT NOT NULL,
  nota REAL CHECK(nota BETWEEN 0 AND 10)
);

INSERT OR IGNORE INTO alunos (id, nome, turma, nota) VALUES
  (1, 'Ana', '3DS', 8.5),
  (2, 'Carlos', '2DS', 7.2),
  (3, 'Júlia', '3DS', 9.1);

SELECT turma, COUNT(*) AS estudantes, ROUND(AVG(nota), 2) AS media
FROM alunos
GROUP BY turma
ORDER BY media DESC;`,database:null,lastResults:[],history:[]};
  const $=selector=>root?.querySelector(selector);
  function setStatus(text,tone=''){const element=$('#sqlStatus');if(element){element.textContent=text;element.dataset.tone=tone;}}
  function makeRequest(type,payload={},timeout=window.LABDS.SECURITY_LIMITS?.sqlTimeoutMs||9000){
    return new Promise((resolve,reject)=>{if(!worker)return reject(new Error('Worker SQL indisponível.'));const requestId=++requestCounter;const timer=setTimeout(()=>{pending.delete(requestId);reject(Object.assign(new Error(`Operação SQL excedeu ${Math.round(timeout/1000)} segundos.`),{name:'TimeoutError'}));},timeout);pending.set(requestId,{resolve,reject,timer});const transfer=payload.buffer instanceof ArrayBuffer?[payload.buffer]:[];worker.postMessage({type,requestId,payload},transfer);});
  }
  function terminateWorker(){for(const item of pending.values()){clearTimeout(item.timer);item.reject(new Error('Worker SQL reiniciado.'));}pending.clear();worker?.terminate();worker=null;ready=false;}
  async function createWorker(){
    terminateWorker();worker=new Worker('js/workers/sql-runner.js');worker.onmessage=event=>{const {type,requestId,payload}=event.data||{};const item=pending.get(requestId);if(!item)return;clearTimeout(item.timer);pending.delete(requestId);if(type==='error')item.reject(Object.assign(new Error(payload?.message||'Erro SQL'),{name:payload?.name||'Error'}));else item.resolve({type,payload});};worker.onerror=event=>{const error=new Error(`Falha no Worker SQL: ${event.message}`);for(const item of pending.values()){clearTimeout(item.timer);item.reject(error);}pending.clear();worker=null;ready=false;setStatus('worker interrompido','error');};
    const response=await makeRequest('init',{jsUrl:window.LABDS.SQLJS_URL,wasmUrl:window.LABDS.SQLJS_WASM,database:state.database},30000);ready=true;schemaCache=response.payload.schema||[];renderExplorer();setStatus('SQLite pronto no Worker','success');
  }
  async function ensureWorker(){if(ready&&worker)return;setStatus('carregando SQLite','busy');await createWorker();}

  function renderResults(results=[],elapsed=0){
    state.lastResults=results;const host=$('#sqlResults');host.textContent='';
    if(!results.length){const card=document.createElement('div');card.className='state-card success';const h=document.createElement('h3');h.textContent='Comando executado';const p=document.createElement('p');p.textContent='Nenhum conjunto de resultados foi retornado.';card.append(h,p);host.appendChild(card);$('#sqlExecutionMeta').textContent=`${elapsed.toFixed(2)} ms`;return;}
    let displayed=0,total=0;
    results.forEach((result,index)=>{total+=Number(result.totalRows??result.values.length);displayed+=result.values.length;const section=document.createElement('section');section.className='sql-result-set';const header=document.createElement('div');header.className='panel-toolbar';const strong=document.createElement('strong');strong.textContent=`Resultado ${index+1}`;const span=document.createElement('span');span.textContent=`${result.totalRows??result.values.length} linha(s)${result.truncated?' • resultado limitado':''}`;header.append(strong,span);const wrap=document.createElement('div');wrap.className='table-wrap';const table=document.createElement('table');table.className='data-table';const thead=document.createElement('thead'),headerRow=document.createElement('tr');result.columns.forEach(column=>{const th=document.createElement('th');th.textContent=column;headerRow.appendChild(th);});thead.appendChild(headerRow);const tbody=document.createElement('tbody');result.values.forEach(row=>{const tr=document.createElement('tr');row.forEach(value=>{const td=document.createElement('td');if(value===null){td.textContent='NULL';td.className='null';}else td.textContent=String(value);tr.appendChild(td);});tbody.appendChild(tr);});table.append(thead,tbody);wrap.appendChild(table);section.append(header,wrap);host.appendChild(section);});$('#sqlExecutionMeta').textContent=`${displayed}/${total} linha(s) exibidas • ${elapsed.toFixed(2)} ms`;
  }

  function renderExplorer(){const box=$('#sqlExplorer');if(!box)return;box.textContent='';if(!schemaCache.length){const p=document.createElement('p');p.className='muted-copy';p.textContent='Nenhuma tabela criada.';box.appendChild(p);return;}schemaCache.forEach(table=>{const button=document.createElement('button');button.className='schema-table';button.type='button';const strong=document.createElement('strong');strong.textContent=table.name;button.appendChild(strong);table.columns.forEach(column=>{const row=document.createElement('span');const name=document.createTextNode(column.name);const small=document.createElement('small');small.textContent=`${column.type||'ANY'}${column.pk?' • PK':''}${column.notnull?' • NOT NULL':''}`;row.append(name,small);button.appendChild(row);});button.addEventListener('click',()=>{$('#sqlCode').value=`SELECT * FROM "${String(table.name).replace(/"/g,'""')}" LIMIT 100;`;run();});box.appendChild(button);});}

  async function run(){
    const sql=$('#sqlCode').value.trim();if(!sql)return;if(sql.length>(window.LABDS.SECURITY_LIMITS?.codeBytes||200000)){ctx.toast('A consulta excede 200 KB.','warning');return;}const started=performance.now();$('#sqlRun').disabled=true;$('#sqlStop').disabled=false;setStatus('executando no Worker','busy');
    try{await ensureWorker();const before=schemaCache.map(item=>item.name);const response=await makeRequest('exec',{sql});const payload=response.payload;state.database=payload.database;schemaCache=payload.schema||[];state.sql=sql;state.history.push({time:new Date().toISOString(),sql,ok:true,elapsed:payload.elapsed});state.history=state.history.slice(-100);renderResults(payload.results,payload.elapsed);renderExplorer();await ctx.storage.set(STORAGE_KEY,state);setStatus('concluído','success');ctx.toast('SQL executado no Worker.','success');ctx.logEvent({eventType:'sql_execution',action:'Consulta SQL executada',input:sql,output:payload.results.length?JSON.stringify(payload.results.map(result=>({columns:result.columns,rows:result.values.slice(0,25),totalRows:result.totalRows})),null,2):'Comando executado sem conjunto de resultados.',status:'success',context:{database:'SQLite/SQL.js em Web Worker',durationMs:Math.round(payload.elapsed),resultSets:payload.results.length,returnedRows:payload.results.reduce((sum,result)=>sum+(result.totalRows||result.values.length),0),tablesBefore:before,tablesAfter:schemaCache.map(item=>item.name),databaseBytes:payload.databaseBytes}});
    }catch(error){const elapsed=performance.now()-started;state.history.push({time:new Date().toISOString(),sql,ok:false,error:error.message});state.history=state.history.slice(-100);renderError(error.message);setStatus(error.name==='TimeoutError'?'interrompido por tempo':'erro','error');ctx.toast(error.message,'error',6000);ctx.logEvent({eventType:'sql_execution',action:'Erro ao executar SQL',input:sql,status:error.name==='TimeoutError'?'interrupted':'error',error:error.message,context:{database:'SQLite/SQL.js em Web Worker',durationMs:Math.round(elapsed)}});if(error.name==='TimeoutError'){terminateWorker();ctx.toast('O Worker foi encerrado e o último banco salvo será restaurado na próxima execução.','warning',6000);}}
    finally{if(root){$('#sqlRun').disabled=false;$('#sqlStop').disabled=true;}}
  }
  function renderError(message){const host=$('#sqlResults');host.textContent='';const card=document.createElement('div');card.className='state-card error';const h=document.createElement('h3');h.textContent='Erro SQL';const p=document.createElement('p');p.textContent=String(message);card.append(h,p);host.appendChild(card);}
  function stop(){if(!worker)return;terminateWorker();setStatus('interrompido','warning');$('#sqlRun').disabled=false;$('#sqlStop').disabled=true;ctx.toast('Execução SQL interrompida. O banco será restaurado do último estado salvo.','warning');}
  async function reset(){if(!confirm('Limpar o banco e restaurar o exemplo?'))return;await ensureWorker();const response=await makeRequest('reset');state={...defaults,history:[]};schemaCache=response.payload.schema||[];$('#sqlCode').value=defaults.sql;renderResults([]);renderExplorer();await ctx.storage.set(STORAGE_KEY,state);setStatus('restaurado','success');}
  async function downloadDatabase(){try{await ensureWorker();const response=await makeRequest('export',{},10000);const buffer=response.payload.buffer;window.LABDS.Exporter.download(new Uint8Array(buffer),`laboratorio-ds-${Date.now()}.sqlite`,'application/vnd.sqlite3');ctx.logEvent({eventType:'export',action:'Banco SQLite exportado',status:'success',context:{fileSize:buffer.byteLength,tables:schemaCache.map(item=>item.name)}});}catch(error){ctx.toast(error.message,'error');}}
  async function importDatabase(file){if(!file)return;if(file.size>20*1024*1024){ctx.toast('O banco excede 20 MB.','warning');return;}try{await ensureWorker();const buffer=await file.arrayBuffer();const response=await makeRequest('import',{buffer},15000);state.database=response.payload.database;schemaCache=response.payload.schema||[];renderExplorer();renderResults([]);await ctx.storage.set(STORAGE_KEY,state);ctx.toast('Banco SQLite importado e validado.','success');ctx.logEvent({eventType:'import',action:'Banco SQLite importado',status:'success',context:{fileName:file.name,fileSize:file.size,tables:schemaCache.map(item=>item.name)}});}catch(error){ctx.toast(error.message,'error');}}

  async function mount(host,context){
    root=host;ctx=context;state={...defaults,...(await ctx.storage.get(STORAGE_KEY,defaults))};state.history=Array.isArray(state.history)?state.history:[];root.innerHTML='<div class="workspace sql-workspace"><aside class="workspace-panel sql-sidebar"><div class="panel-title"><div><h2>Explorador do banco</h2><p>Tabelas, colunas, tipos e restrições.</p></div></div><div id="sqlExplorer" class="schema-explorer"><p class="muted-copy">Carregando SQLite no Worker…</p></div><div class="button-row vertical"><button id="sqlImportBtn" class="btn secondary" type="button">Importar .sqlite</button><input id="sqlImportFile" type="file" accept=".sqlite,.db,application/octet-stream" hidden><button id="sqlDownloadDb" class="btn secondary" type="button">Exportar banco</button><button id="sqlReset" class="btn subtle" type="button">Limpar banco</button></div><div class="state-card info"><p>Execução real em WebAssembly dentro de Web Worker. Consultas acima de 9 segundos são interrompidas.</p></div></aside><main class="workspace-main sql-main"><section class="resizable-panel sql-editor"><div class="panel-toolbar"><div class="tabs"><button class="tab-btn active" type="button">consulta.sql</button></div><div class="button-row"><button id="sqlRun" class="btn primary" type="button">Executar SQL</button><button id="sqlStop" class="btn secondary" type="button" disabled>Interromper</button><button id="sqlClear" class="btn secondary" type="button">Limpar editor</button><span id="sqlStatus">aguardando</span></div></div><textarea id="sqlCode" class="code-editor" spellcheck="false" aria-label="Consulta SQL"></textarea></section><section class="sql-results-panel"><div class="panel-toolbar"><strong>Resultados</strong><span id="sqlExecutionMeta"></span></div><div id="sqlResults" class="sql-results"><div class="muted-copy">Execute comandos para visualizar tabelas e registros.</div></div></section></main></div>';
    $('#sqlCode').value=state.sql||defaults.sql;$('#sqlRun').addEventListener('click',run);$('#sqlStop').addEventListener('click',stop);$('#sqlClear').addEventListener('click',()=>$('#sqlCode').value='');$('#sqlReset').addEventListener('click',reset);$('#sqlDownloadDb').addEventListener('click',downloadDatabase);$('#sqlImportBtn').addEventListener('click',()=>$('#sqlImportFile').click());$('#sqlImportFile').addEventListener('change',event=>{importDatabase(event.target.files?.[0]);event.target.value='';});$('#sqlCode').addEventListener('keydown',event=>{if(event.key==='Tab'){event.preventDefault();event.target.setRangeText('  ',event.target.selectionStart,event.target.selectionEnd,'end');}if((event.ctrlKey||event.metaKey)&&event.key==='Enter'){event.preventDefault();run();}});setStatus('carregamento sob demanda','');ensureWorker().catch(error=>{setStatus('requer conexão','warning');renderError(`${error.message} O editor continua disponível.`);});
  }
  function exportPayload(){const sql=$('#sqlCode')?.value||state.sql;return{text:['LABORATÓRIO SQL — SQLITE EM WORKER',`Exportado em: ${new Date().toLocaleString('pt-BR')}`,'','===== SQL =====',sql,'','===== HISTÓRICO =====',...state.history.map(item=>`${item.time} • ${item.ok?'OK':'ERRO'} • ${item.elapsed?`${Number(item.elapsed).toFixed(2)} ms`:item.error}`)].join('\n'),native:sql,backup:{...state,database:state.database},meta:[{label:'Motor',value:'SQLite/WebAssembly em Worker'},{label:'Tabelas',value:String(schemaCache.length)},{label:'Timeout',value:'9 segundos'}]};}
  function help(){return '<p>SQLite executa de verdade em WebAssembly dentro de um Web Worker. O botão Interromper encerra a execução e o banco é recuperado do último estado salvo. Resultados são limitados para preservar memória e responsividade.</p>';}
  async function unmount(){if(root){state.sql=$('#sqlCode').value;await ctx.storage.set(STORAGE_KEY,state);}try{await makeRequest('close',{},1000);}catch{}terminateWorker();root=null;ctx=null;state=null;schemaCache=[];}
  window.LABDS_LABS['sql-lab']={mount,unmount,exportPayload,help};
})();
