'use strict';
(function(){
  window.LABDS_LABS=window.LABDS_LABS||{};
  const KEY='lab.blockchain.state';
  const DEFAULT={difficulty:2,chain:[],xp:0,transactions:[]};
  let root,ctx,state,abort=false;
  const enc=new TextEncoder();
  async function sha256(text){const hash=await crypto.subtle.digest('SHA-256',enc.encode(text));return [...new Uint8Array(hash)].map(b=>b.toString(16).padStart(2,'0')).join('');}
  async function save(){await ctx.storage.set(KEY,state);}
  function short(value){return `${value.slice(0,8)}…${value.slice(-6)}`;}
  async function ensureGenesis(){if(state.chain.length)return;const block={index:0,at:Date.now(),data:'Bloco gênese do Lab DS',previous:'0'.repeat(64),nonce:0};block.hash=await sha256(JSON.stringify(block));state.chain=[block];await save();}
  function renderChain(){const box=root.querySelector('#chainBlocks');box.textContent='';state.chain.forEach((block,index)=>{const item=document.createElement('article');item.className='block-card';item.innerHTML=`<span>BLOCO ${block.index}</span><strong>${short(block.hash)}</strong><small>nonce ${block.nonce}</small><p></p><i></i>`;item.querySelector('p').textContent=block.data;item.querySelector('i').style.setProperty('--progress',`${Math.min(100,(index+1)/Math.max(1,state.chain.length)*100)}%`);box.appendChild(item);});root.querySelector('#chainHeight').textContent=state.chain.length;root.querySelector('#chainXp').textContent=state.xp;root.querySelector('#chainDifficulty').textContent=state.difficulty;}
  async function mine(){const data=root.querySelector('#blockData').value.trim();if(!data)return ctx.toast('Digite uma informação fictícia para o bloco.','warning');const button=root.querySelector('#mineBlock'),log=root.querySelector('#mineLog'),progress=root.querySelector('#mineProgress');button.disabled=true;abort=false;const previous=state.chain.at(-1).hash,index=state.chain.length,at=Date.now(),prefix='0'.repeat(state.difficulty);let nonce=0,hash='',batch=0;log.textContent=`Procurando hash iniciado por ${prefix}…`;const start=performance.now();while(!abort){for(let i=0;i<300;i++){nonce++;hash=await sha256(`${index}|${at}|${data}|${previous}|${nonce}`);if(hash.startsWith(prefix))break;}batch++;progress.style.width=`${Math.min(96,(batch%60)/60*100)}%`;if(hash.startsWith(prefix))break;await new Promise(r=>setTimeout(r,0));if(performance.now()-start>16000){log.textContent='Limite educacional atingido. Reduza a dificuldade e tente novamente.';button.disabled=false;return;}}
    if(abort){log.textContent='Mineração interrompida.';button.disabled=false;return;}const block={index,at,data,previous,nonce,hash};state.chain.push(block);state.xp+=30+state.difficulty*15;progress.style.width='100%';log.textContent=`Bloco validado em ${((performance.now()-start)/1000).toFixed(2)} s, após ${nonce.toLocaleString('pt-BR')} tentativas.\nHash: ${hash}`;root.querySelector('#blockData').value='';await save();renderChain();ctx.logEvent({eventType:'blockchain',action:'Bloco minerado',status:'success',details:{difficulty:state.difficulty,nonce}});button.disabled=false;}
  async function expectedHash(block){if(block.index===0){const clean={index:block.index,at:block.at,data:block.data,previous:block.previous,nonce:block.nonce};return sha256(JSON.stringify(clean));}return sha256(`${block.index}|${block.at}|${block.data}|${block.previous}|${block.nonce}`);}
  async function validateChain(){const out=root.querySelector('#validationOutput');out.className='practice-feedback';out.textContent='Recalculando hashes…';let valid=true,reason='';for(let i=0;i<state.chain.length;i++){const block=state.chain[i],calculated=await expectedHash(block);if(calculated!==block.hash){valid=false;reason=`O hash armazenado do bloco ${block.index} não corresponde ao conteúdo atual.`;break;}if(i>0&&block.previous!==state.chain[i-1].hash){valid=false;reason=`O bloco ${block.index} não aponta para o hash do bloco anterior.`;break;}}out.className=`practice-feedback ${valid?'success':'error'}`;out.textContent=valid?'Cadeia consistente: conteúdo, hash e encadeamento foram conferidos.':`Integridade quebrada. ${reason}`;}
  async function tamper(){if(state.chain.length<2)return ctx.toast('Minere pelo menos um bloco antes de alterar a cadeia.','warning');state.chain[1].data+=' [ALTERADO SEM RECALCULAR]';renderChain();const out=root.querySelector('#validationOutput');out.className='practice-feedback error';out.textContent='Conteúdo alterado. Clique em Validar cadeia para recalcular e detectar a divergência.';await save();}
  function addTx(){const from=root.querySelector('#txFrom').value.trim(),to=root.querySelector('#txTo').value.trim(),amount=Number(root.querySelector('#txAmount').value);if(!from||!to||!Number.isFinite(amount)||amount<=0)return ctx.toast('Preencha remetente, destino e quantidade fictícios.','warning');state.transactions.push({from,to,amount,at:Date.now()});root.querySelector('#blockData').value=JSON.stringify(state.transactions.slice(-4));root.querySelector('#txPool').textContent=state.transactions.map((t,i)=>`${i+1}. ${t.from} → ${t.to}: ${t.amount.toFixed(4)} LAB`).join('\n');save();}
  function render(){root.innerHTML=`<div class="immersive-lab blockchain-lab"><header class="immersive-hero"><div><span class="eyebrow">BLOCKCHAIN • HASH REAL</span><h2>Construa uma cadeia de blocos</h2><p>Use SHA-256 real do navegador e uma prova de trabalho reduzida para compreender blocos, nonce, hash, integridade e consenso.</p></div><div class="immersive-badges"><span>Altura <b id="chainHeight">0</b></span><span>Dificuldade <b id="chainDifficulty">${state.difficulty}</b></span><span>XP <b id="chainXp">${state.xp}</b></span></div></header><section class="immersive-grid"><article class="immersive-card"><h3>Pool de transações fictícias</h3><div class="form-grid"><label>Origem<input id="txFrom" value="alice"></label><label>Destino<input id="txTo" value="bob"></label><label>Quantidade LAB<input id="txAmount" type="number" min="0.0001" step="0.0001" value="0.1250"></label></div><button id="addTx" class="btn secondary">Adicionar ao pool</button><pre id="txPool" class="terminal-mini">Pool vazio.</pre><h3>Novo bloco</h3><label>Dados<textarea id="blockData" rows="4" placeholder="Transações, evento ou mensagem"></textarea></label><label>Dificuldade<input id="difficultyRange" type="range" min="1" max="3" value="${state.difficulty}"></label><div class="button-row"><button id="mineBlock" class="btn primary">Minerar bloco</button><button id="stopMining" class="btn secondary">Interromper</button></div><div class="large-progress"><i id="mineProgress"></i></div><pre id="mineLog" class="terminal-mini">Pronto para minerar.</pre></article><article class="immersive-card"><h3>Rede e integridade</h3><div class="block-network" id="chainBlocks"></div><div class="button-row"><button id="validateChain" class="btn primary">Validar cadeia</button><button id="tamperChain" class="btn danger">Alterar um bloco</button></div><div id="validationOutput" class="practice-feedback"></div><div class="knowledge-card"><strong>Importante:</strong> esta prova de trabalho é reduzida para ensino. Redes reais usam regras, consenso, nós e consumo computacional muito mais complexos.</div></article></section></div>`;
    root.querySelector('#difficultyRange').addEventListener('input',e=>{state.difficulty=Number(e.target.value);root.querySelector('#chainDifficulty').textContent=state.difficulty;save();});root.querySelector('#mineBlock').addEventListener('click',mine);root.querySelector('#stopMining').addEventListener('click',()=>{abort=true;});root.querySelector('#validateChain').addEventListener('click',validateChain);root.querySelector('#tamperChain').addEventListener('click',tamper);root.querySelector('#addTx').addEventListener('click',addTx);root.querySelector('#txPool').textContent=state.transactions.map((t,i)=>`${i+1}. ${t.from} → ${t.to}: ${t.amount.toFixed(4)} LAB`).join('\n')||'Pool vazio.';renderChain();}
  async function mount(host,context){root=host;ctx=context;state={...DEFAULT,...await ctx.storage.get(KEY,DEFAULT)};await ensureGenesis();render();}
  async function unmount(){abort=true;await save();root=null;ctx=null;state=null;}
  function exportPayload(){return{text:`BLOCKCHAIN LAB\nBlocos: ${state.chain.length}\nXP: ${state.xp}`,native:JSON.stringify(state,null,2),backup:state,meta:[{label:'Blocos',value:String(state.chain.length)},{label:'XP',value:String(state.xp)}]};}
  function help(){return'<h3>Blockchain</h3><p>Minere blocos com hash SHA-256 real e observe como cada bloco referencia o anterior. Não há criptomoeda, carteira ou transação financeira real.</p>';}
  window.LABDS_LABS['blockchain-lab']={mount,unmount,exportPayload,help};
})();
