import { GUIDED_STORIES } from '../../data/guidedJourneySystems.js';
const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[char]));
const stateLabel=value=>value==='COMPLETED'?'Concluída':value==='ACTIVE'?'Em andamento':value==='PAUSED'?'Pausada':'Nova';
class JourneyCenterModule {
  constructor(){this.container=null;this.context=null;this.tab='stories';this.onClick=event=>this.handleClick(event);}
  mount(container,context){this.container=container;this.context=context;this.render();container.addEventListener('click',this.onClick);}
  unmount(){this.container?.removeEventListener('click',this.onClick);}
  engine(){return this.context.guidedTrails;}
  render(){const active=this.engine().active();this.container.innerHTML=`<section class="journey-center">
    <header class="journey-center-hero"><div><span class="eyebrow">Fase C2.3 · Jornadas oficiais e do professor</span><h2>Escolha uma história e entenda <span>o que usar, como usar e por que usar.</span></h2><p>As trilhas organizam os laboratórios em uma sequência pedagógica. Roteiros personalizados usam códigos curtos e preservam tempo, checkpoints e evidências por perfil.</p></div><div class="journey-center-actions"><button class="button secondary" data-action="back">← Portal leve</button>${active?`<button class="button primary" data-action="continue-active">Continuar ${active.completed+1}/${active.total}</button>`:''}</div></header>
    <nav class="journey-center-tabs"><button class="${this.tab==='stories'?'active':''}" data-action="tab" data-tab="stories">Histórias guiadas</button><button class="${this.tab==='tools'?'active':''}" data-action="tab" data-tab="tools">Como usar</button><button class="${this.tab==='teacher'?'active':''}" data-action="tab" data-tab="teacher">Professor e código</button></nav>
    <main>${this.tab==='stories'?this.storyMarkup():this.tab==='tools'?this.toolsMarkup():this.teacherMarkup()}</main>
  </section>`;}
  storyMarkup(){const definitions=this.engine().definitions();return `<section class="journey-story-grid">${definitions.map(trail=>this.storyCard(trail)).join('')}</section>`;}
  storyCard(trail){const story=trail.story||GUIDED_STORIES[trail.id]||{role:'Explorador',opening:trail.summary,mission:trail.summary,color:trail.accent||'#5ee3ff'},status=this.engine().status(trail.id),action=status.state==='READY'?'start':status.state==='COMPLETED'?'restart':'resume',label=status.state==='READY'?'Iniciar história':status.state==='COMPLETED'?'Refazer história':'Continuar história';return `<article class="journey-story-card ${trail.custom?'custom':''}" style="--journey:${story.color||trail.accent}"><header><span>${trail.icon}</span><div><small>${escapeHtml(story.role)} · ${escapeHtml(trail.duration)}</small><h3>${escapeHtml(trail.title)}</h3></div></header>${trail.custom?`<div class="journey-custom-badge"><b>PROFESSOR</b><span>${escapeHtml(trail.className)} · código ${escapeHtml(trail.accessCode)}</span></div>`:''}<p class="journey-story-opening">${escapeHtml(story.opening||trail.summary)}</p><div class="journey-mission"><b>MISSÃO</b><span>${escapeHtml(story.mission||trail.summary)}</span></div><div class="journey-step-preview">${trail.steps.slice(0,4).map((step,index)=>`<span><i>${index+1}</i>${escapeHtml(step.title)}</span>`).join('')}${trail.steps.length>4?`<span><i>+</i>${trail.steps.length-4} etapas</span>`:''}</div><div class="journey-progress"><i style="width:${status.percent}%"></i></div><footer><small>${status.completed}/${status.total} · ${stateLabel(status.state)}</small><button data-action="${action}" data-trail="${trail.id}">${label}</button></footer></article>`;}
  toolsMarkup(){return `<section class="journey-tools-layout"><article><span class="eyebrow">Tour contextual</span><h3>Aprenda as ferramentas sem sair da experiência</h3><p>O tour destaca um recurso por vez, explica sua finalidade e indica a ação seguinte. Ele não carrega laboratórios pesados e pode ser repetido a qualquer momento.</p><button class="button primary" data-action="start-platform-tour">Iniciar tour das ferramentas</button></article><ol>${['Escolha um modo na abertura leve.','Abra somente o laboratório indicado.','Leia objetivo, tempo e checkpoint no HUD.','Use “Por que usar?” para entender a função da ferramenta.','Registre a evidência e deixe o sistema preparar apenas o próximo passo.'].map((item,index)=>`<li><span>${index+1}</span>${item}</li>`).join('')}</ol></section>`;}
  teacherMarkup(){return `<section class="journey-teacher-plan"><div><span class="eyebrow">TRILHAS PERSONALIZADAS</span><h3>Entre por código ou abra o estúdio do professor</h3><p>O código funciona localmente e identifica uma trilha salva neste dispositivo. O Estúdio permite criar, ordenar, importar e exportar roteiros, acompanhar perfis e gerar evidências.</p></div><div class="journey-code-entry"><label>Código da trilha<input id="journey-access-code" maxlength="12" autocomplete="off" placeholder="Ex.: A1B2C3"></label><button class="button primary" data-action="join-by-code">Abrir por código</button></div><div class="hero-actions"><button class="button primary" data-action="open-teacher-studio">Abrir Estúdio de Trilhas</button><button class="button secondary" data-action="open-director">Abrir Direção de Missões</button></div><small class="journey-local-warning">O acompanhamento é local ao dispositivo. Para outras máquinas, exporte o roteiro e importe no equipamento utilizado pela turma.</small></section>`;}
  startTrail(id,restart=false){if(restart)this.engine().reset(id);const status=restart||this.engine().status(id).state==='READY'?this.engine().start(id):this.engine().resume(id);this.context.toast(`História iniciada: ${this.engine().definition(id).title}.`);this.context.openModule(status.currentStep.moduleId);}
  handleClick(event){const target=event.target.closest('[data-action]');if(!target)return;const action=target.dataset.action;if(action==='back'){this.context.onBack();return;}if(action==='tab'){this.tab=target.dataset.tab;this.render();return;}if(action==='start'||action==='resume'){this.startTrail(target.dataset.trail);return;}if(action==='restart'){if(confirm('Reiniciar esta história e apagar o progresso desta trilha?'))this.startTrail(target.dataset.trail,true);return;}if(action==='continue-active'){const active=this.engine().active();if(active?.currentStep)this.context.openModule(active.currentStep.moduleId);return;}if(action==='start-platform-tour'){this.context.onBack();setTimeout(()=>this.context.startToolTour?.(),0);return;}if(action==='open-director'){this.context.openModule('mission-director');return;}if(action==='open-teacher-studio'){this.context.openModule('teacher-trail-studio');return;}if(action==='join-by-code'){const code=this.container.querySelector('#journey-access-code')?.value?.trim().toUpperCase(),trail=this.engine().definitions().find(item=>item.custom&&item.accessCode===code);if(!trail){this.context.toast('Código não encontrado neste dispositivo.');return;}this.startTrail(trail.id);return;}}
}
export function createModule(){return new JourneyCenterModule();}
