'use strict';
(function(){
  window.LABDS_LABS=window.LABDS_LABS||{};
  const KEY='lab.biomonitor.v32';
  let root,ctx,state,raf=0,lastTime=0,lastSample=0,elapsed=0;
  const $=s=>root.querySelector(s),$$=s=>[...root.querySelectorAll(s)];
  const clamp=(n,a,b)=>Math.min(b,Math.max(a,Number(n)||0));
  function defaults(){return{running:true,scenario:'rest',bpm:72,targetBpm:72,oxygen:98,respiration:16,alertLow:50,alertHigh:130,history:[],comparisons:{rest:null,exercise:null},startedAt:new Date().toISOString(),simulatedSeconds:0};}
  function save(){ctx.storage.set(KEY,state);}
  function scenarioTarget(id){return id==='rest'?72:id==='walk'?96:id==='exercise'?148:id==='recovery'?82:state.bpm;}
  function applyScenario(id){state.scenario=id;state.targetBpm=scenarioTarget(id);if(id==='exercise')state.respiration=28;else if(id==='walk')state.respiration=21;else if(id==='recovery')state.respiration=18;else state.respiration=16;save();renderControls();}
  function ecgValue(phase){const p=((phase%1)+1)%1;let y=Math.sin(p*Math.PI*2)*.04;if(p>.10&&p<.18)y+=Math.sin((p-.10)/.08*Math.PI)*.12;if(p>.30&&p<.34)y-=Math.sin((p-.30)/.04*Math.PI)*.18;if(p>.34&&p<.37)y+=Math.sin((p-.34)/.03*Math.PI)*1.0;if(p>.37&&p<.42)y-=Math.sin((p-.37)/.05*Math.PI)*.32;if(p>.58&&p<.72)y+=Math.sin((p-.58)/.14*Math.PI)*.22;return y;}
  function drawGrid(c,w,h){c.fillStyle='#03100d';c.fillRect(0,0,w,h);c.strokeStyle='rgba(68,255,174,.08)';c.lineWidth=1;for(let x=0;x<w;x+=10){c.beginPath();c.moveTo(x,0);c.lineTo(x,h);c.stroke();}for(let y=0;y<h;y+=10){c.beginPath();c.moveTo(0,y);c.lineTo(w,y);c.stroke();}c.strokeStyle='rgba(68,255,174,.17)';for(let x=0;x<w;x+=50){c.beginPath();c.moveTo(x,0);c.lineTo(x,h);c.stroke();}for(let y=0;y<h;y+=50){c.beginPath();c.moveTo(0,y);c.lineTo(w,y);c.stroke();}}
  function drawECG(now){const canvas=$('#bioCanvas');if(!canvas)return;const rect=canvas.getBoundingClientRect(),dpr=(window.LABDS?.PerformanceManager?.canvasScale?.(2)??Math.min(devicePixelRatio||1,2)),w=Math.max(320,Math.floor(rect.width*dpr)),h=Math.max(210,Math.floor(rect.height*dpr));if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;}const c=canvas.getContext('2d');drawGrid(c,w,h);const seconds=7,beatsPerSecond=state.bpm/60,cx=w/seconds;c.strokeStyle='#55ffae';c.shadowColor='#35ff9c';c.shadowBlur=10*dpr;c.lineWidth=2*dpr;c.beginPath();for(let x=0;x<w;x++){const t=elapsed-seconds+x/cx,phase=t*beatsPerSecond,noise=Math.sin(t*13.7)*.006+Math.sin(t*5.2)*.004,y=h*.52-ecgValue(phase)*h*.34-noise*h;c.lineTo(x,y);}c.stroke();c.shadowBlur=0;const cursor=((elapsed%seconds)/seconds)*w;c.fillStyle='rgba(255,255,255,.7)';c.fillRect(cursor,0,1*dpr,h);}
  function drawHistory(){const canvas=$('#bioHistory');if(!canvas)return;const c=canvas.getContext('2d'),w=canvas.width,h=canvas.height;c.clearRect(0,0,w,h);c.fillStyle='#07111f';c.fillRect(0,0,w,h);c.strokeStyle='rgba(130,170,210,.18)';for(let y=30;y<h;y+=40){c.beginPath();c.moveTo(35,y);c.lineTo(w-12,y);c.stroke();}const values=state.history.slice(-60);if(values.length<2){c.fillStyle='#9fb5d0';c.fillText('O histórico aparece após alguns segundos de simulação.',18,28);return;}const min=35,max=190;c.strokeStyle='#58e6a7';c.lineWidth=2;c.beginPath();values.forEach((item,i)=>{const x=35+i/(values.length-1)*(w-55),y=h-25-(clamp(item.bpm,min,max)-min)/(max-min)*(h-50);if(i===0)c.moveTo(x,y);else c.lineTo(x,y);});c.stroke();c.fillStyle='#9fb5d0';c.font='12px system-ui';c.fillText('190 bpm',4,20);c.fillText('35 bpm',8,h-22);c.fillText('últimos 60 s',w-90,h-8);}
  function updateNumbers(){const rounded=Math.round(state.bpm),status=rounded<state.alertLow?'ABAIXO DO LIMITE':rounded>state.alertHigh?'ACIMA DO LIMITE':'FAIXA CONFIGURADA';$('#bioBpm').textContent=rounded;$('#bioOxygen').textContent=`${Math.round(state.oxygen)}%`;$('#bioRespiration').textContent=`${Math.round(state.respiration)}/min`;$('#bioStatus').textContent=status;$('#bioStatus').className=`bio-status ${status==='FAIXA CONFIGURADA'?'ok':'alert'}`;$('#bioTimer').textContent=new Date(state.simulatedSeconds*1000).toISOString().slice(11,19);}
  function loop(now){if(!root)return;const dt=Math.min(.05,(now-lastTime)/1000||0);lastTime=now;if(state.running){elapsed+=dt;state.simulatedSeconds+=dt;const delta=state.targetBpm-state.bpm;state.bpm+=delta*Math.min(1,dt*(state.scenario==='recovery'?.45:.7));state.bpm+=Math.sin(elapsed*1.8)*.06;state.oxygen=clamp(98-(state.bpm>125?(state.bpm-125)*.018:0)+Math.sin(elapsed*.4)*.15,94,100);if(now-lastSample>=1000){lastSample=now;state.history.push({at:new Date().toISOString(),bpm:Math.round(state.bpm),scenario:state.scenario});state.history=state.history.slice(-300);save();drawHistory();}updateNumbers();}drawECG(now);raf=requestAnimationFrame(loop);}
  function renderControls(){$$('[data-bio-scenario]').forEach(button=>button.classList.toggle('active',button.dataset.bioScenario===state.scenario));const manual=$('#bioManual');if(manual)manual.value=Math.round(state.targetBpm);const toggle=$('#bioToggle');if(toggle)toggle.textContent=state.running?'Pausar monitor':'Iniciar monitor';}
  function validateComparison(){if(!state.comparisons.rest||!state.comparisons.exercise)return ctx.toast('Registre uma leitura em repouso e outra em exercício.','warning');const difference=state.comparisons.exercise-state.comparisons.rest;if(difference<20)return ctx.toast('A diferença ainda é pequena. Simule exercício por alguns segundos antes de registrar.','warning');ctx.core?.complete?.('biomonitor:comparison',{xp:65,credits:25,reason:'Comparação entre repouso e exercício concluída'});ctx.toast(`Comparação concluída: aumento de ${Math.round(difference)} bpm.`,'success');}
  function template(){return`<div class="biomonitor-lab"><header class="bio-header"><div><span class="eyebrow">SINAIS SIMULADOS</span><h2>BioMonitor — painel de batimentos</h2><p>Observe a resposta simulada ao repouso, caminhada, exercício e recuperação.</p></div><div class="medical-disclaimer"><strong>Simulação educacional</strong><span>Não mede sinais reais, não faz diagnóstico e não substitui equipamento médico.</span></div></header><section class="bio-dashboard"><main class="bio-monitor"><div class="bio-screen-head"><span>ECG SIMULADO • DERIVAÇÃO EDUCACIONAL</span><strong id="bioStatus" class="bio-status ok">FAIXA CONFIGURADA</strong></div><canvas id="bioCanvas" aria-label="Traçado cardíaco simulado"></canvas><div class="bio-metrics"><article><span>Frequência</span><strong><b id="bioBpm">72</b> bpm</strong></article><article><span>Oxigenação simulada</span><strong id="bioOxygen">98%</strong></article><article><span>Respiração</span><strong id="bioRespiration">16/min</strong></article><article><span>Tempo</span><strong id="bioTimer">00:00:00</strong></article></div></main><aside class="bio-controls"><h3>Cenário</h3><div class="bio-scenarios">${[['rest','Repouso'],['walk','Caminhada'],['exercise','Exercício'],['recovery','Recuperação'],['manual','Manual']].map(([id,label])=>`<button type="button" data-bio-scenario="${id}" class="${state.scenario===id?'active':''}">${label}</button>`).join('')}</div><label>Batimentos-alvo<input id="bioManual" type="range" min="35" max="190" value="${Math.round(state.targetBpm)}"><output id="bioManualOut">${Math.round(state.targetBpm)} bpm</output></label><div class="bio-limit-grid"><label>Alerta mínimo<input id="bioLow" type="number" min="30" max="120" value="${state.alertLow}"></label><label>Alerta máximo<input id="bioHigh" type="number" min="80" max="220" value="${state.alertHigh}"></label></div><button id="bioToggle" class="btn primary" type="button">${state.running?'Pausar monitor':'Iniciar monitor'}</button><button id="bioReset" class="btn secondary" type="button">Reiniciar simulação</button></aside></section><section class="bio-lower"><article><div class="section-heading compact"><div><span class="eyebrow">HISTÓRICO</span><h3>Evolução dos últimos segundos</h3></div></div><canvas id="bioHistory" width="760" height="230"></canvas></article><article class="bio-activity"><h3>Atividade comparativa</h3><p>Registre uma leitura em repouso, depois simule exercício e compare.</p><div class="bio-readings"><button id="recordRest" class="btn secondary" type="button">Registrar repouso</button><span id="restReading">${state.comparisons.rest?Math.round(state.comparisons.rest)+' bpm':'—'}</span><button id="recordExercise" class="btn secondary" type="button">Registrar exercício</button><span id="exerciseReading">${state.comparisons.exercise?Math.round(state.comparisons.exercise)+' bpm':'—'}</span></div><button id="validateBio" class="btn primary" type="button">Validar comparação</button></article></section></div>`;}
  async function mount(host,context){root=host;ctx=context;state={...defaults(),...(await ctx.storage.get(KEY,{}))};state.comparisons={...defaults().comparisons,...(state.comparisons||{})};root.innerHTML=template();$$('[data-bio-scenario]').forEach(button=>button.onclick=()=>applyScenario(button.dataset.bioScenario));$('#bioManual').oninput=event=>{state.scenario='manual';state.targetBpm=clamp(event.target.value,35,190);$('#bioManualOut').textContent=`${Math.round(state.targetBpm)} bpm`;renderControls();save();};$('#bioLow').onchange=event=>{state.alertLow=clamp(event.target.value,30,120);save();};$('#bioHigh').onchange=event=>{state.alertHigh=clamp(event.target.value,80,220);save();};$('#bioToggle').onclick=()=>{state.running=!state.running;renderControls();save();};$('#bioReset').onclick=async()=>{cancelAnimationFrame(raf);raf=0;elapsed=0;lastTime=0;lastSample=0;state=defaults();await ctx.storage.set(KEY,state);await mount(host,context);};$('#recordRest').onclick=()=>{state.comparisons.rest=state.bpm;$('#restReading').textContent=`${Math.round(state.bpm)} bpm`;save();ctx.toast('Leitura de repouso registrada.','success');};$('#recordExercise').onclick=()=>{state.comparisons.exercise=state.bpm;$('#exerciseReading').textContent=`${Math.round(state.bpm)} bpm`;save();ctx.toast('Leitura de exercício registrada.','success');};$('#validateBio').onclick=validateComparison;lastTime=performance.now();lastSample=lastTime;drawHistory();raf=requestAnimationFrame(loop);}
  async function unmount(){cancelAnimationFrame(raf);raf=0;await ctx?.storage?.set?.(KEY,state);root=null;ctx=null;}
  function exportPayload(){const session=ctx?.session?.get?.();return{text:['BIOMONITOR — SIMULAÇÃO EDUCACIONAL',`Estudante: ${session?.studentName||'Não informado'}`,`Turma: ${session?.studentClass||'Não informada'}`,`Cenário: ${state.scenario}`,`Frequência atual: ${Math.round(state.bpm)} bpm`,`Repouso registrado: ${state.comparisons.rest?Math.round(state.comparisons.rest)+' bpm':'não registrado'}`,`Exercício registrado: ${state.comparisons.exercise?Math.round(state.comparisons.exercise)+' bpm':'não registrado'}`,'','Este relatório não possui finalidade médica.'].join('\n'),native:JSON.stringify({version:window.LABDS.VERSION,simulated:true,state},null,2),backup:state,meta:[{label:'BPM',value:String(Math.round(state.bpm))},{label:'Amostras',value:String(state.history.length)}]};}
  function help(){return'<p>Escolha um cenário e observe a transição. O traçado e os valores são gerados matematicamente para aprendizagem e não representam medição de uma pessoa.</p>';}
  window.LABDS_LABS['biomonitor-lab']={mount,unmount,exportPayload,help};
})();
