import * as THREE from '../voxelcraft-ds/vendor/three/three.module.min.js';
const {Engine,COLOR_NAMES}=globalThis.CrystalCascadeEngine;
const params=new URLSearchParams(location.search);const quality=params.get('quality')||'medio';const reduced=params.get('reduced')==='1'||matchMedia('(prefers-reduced-motion: reduce)').matches;const muted=params.get('muted')==='1';
const levelsData=await fetch('./levels.json').then(r=>r.json());const levels=levelsData.levels;const colors=['#59f2ff','#ffca55','#55f0a3','#b987ff','#ff6eaa','#62a9ff'];
let portalPaused=false;let levelIndex=Math.max(0,Math.min(levels.length-1,Number(localStorage.getItem('fliperama-crystal-level')||0)));let engine;let selected=-1;let busy=false;let campaignStars=JSON.parse(localStorage.getItem('fliperama-crystal-stars')||'{}');
const el=id=>document.getElementById(id);const board=el('board');
function post(type,detail={}){parent?.postMessage({source:'fliperama-ds-crystal-cascade',type,detail},location.origin==='null'?'*':location.origin)}
function goalText(){const l=levels[levelIndex],parts=[`Meta: ${l.targetScore.toLocaleString('pt-BR')} pts`];if(engine.blockers.size)parts.push(`gelo ${engine.blockers.size}`);for(const [k,v] of Object.entries(l.collect||{})){const now=engine.collected[k]||0;parts.push(`${k} ${Math.min(now,v)}/${v}`);}return parts.join(' · ')}
function render(){el('levelLabel').textContent=`Fase ${levelIndex+1}/12`;el('missionTitle').textContent=levels[levelIndex].name;el('missionText').textContent=`Objetivo em até ${levels[levelIndex].moves} movimentos`;el('moves').textContent=engine.moves;el('score').textContent=engine.score.toLocaleString('pt-BR');el('combo').textContent=`×${Math.max(1,engine.combo)}`;el('goal').textContent=goalText();el('stars').textContent='★'.repeat(campaignStars[levelIndex+1]||0)+'☆'.repeat(3-(campaignStars[levelIndex+1]||0));board.replaceChildren();engine.board.forEach((piece,i)=>{const b=document.createElement('button');b.className='tile'+(i===selected?' selected':'')+(engine.blockers.has(i)?' ice':'');b.dataset.index=i;b.setAttribute('role','gridcell');b.setAttribute('aria-label',`Cristal ${COLOR_NAMES[piece.color]}${piece.special?', especial '+piece.special:''}${engine.blockers.has(i)?', com gelo':''}`);const c=document.createElement('span');c.className='crystal';c.style.setProperty('--c',colors[piece.color]);b.append(c);if(piece.special){const s=document.createElement('span');s.className=`special ${piece.special}`;b.append(s);}board.append(b);});}
function save(){localStorage.setItem('fliperama-crystal-level',String(levelIndex));localStorage.setItem('fliperama-crystal-stars',JSON.stringify(campaignStars));localStorage.setItem('fliperama-crystal-state',JSON.stringify({schemaVersion:1,levelIndex,state:engine.snapshot()}));}
function loadLevel(index,restore=true){levelIndex=index;engine=new Engine(levels[index],0xCC3700+index*997);selected=-1;const raw=restore?localStorage.getItem('fliperama-crystal-state'):null;if(raw){try{const s=JSON.parse(raw);if(s.schemaVersion===1&&s.levelIndex===index)engine.restore(s.state);}catch{}}render();save();post('progress',{level:levelIndex+1,totalLevels:12,score:engine.score});}
function showResult(victory){const stars=victory?engine.stars():0;if(victory){campaignStars[levelIndex+1]=Math.max(campaignStars[levelIndex+1]||0,stars);save();}el('resultTitle').textContent=victory?`Fase concluída · ${'★'.repeat(stars)}`:'Movimentos esgotados';el('resultText').textContent=victory?`${engine.score.toLocaleString('pt-BR')} pontos · melhor combo ×${Math.max(1,engine.combo)}.`:'Reorganize suas combinações, use peças especiais e tente novamente.';el('resultAction').textContent=victory?(levelIndex===11?'Rever campanha':'Próxima fase'):'Tentar novamente';el('result').hidden=false;post(victory?(levelIndex===11?'victory':'level-complete'):'defeat',{level:levelIndex+1,stars,score:engine.score});}
board.addEventListener('click',async e=>{const tile=e.target.closest('.tile');if(!tile||busy||portalPaused||engine.status!=='playing')return;const i=Number(tile.dataset.index);if(selected<0){selected=i;render();return;}if(selected===i){selected=-1;render();return;}busy=true;const result=engine.swap(selected,i);selected=-1;render();if(result.ok&&!reduced){board.animate([{transform:'rotateX(7deg) scale(1)'},{transform:'rotateX(7deg) scale(1.012)'},{transform:'rotateX(7deg) scale(1)'}],{duration:220});}save();if(engine.status==='victory')showResult(true);else if(engine.status==='defeat')showResult(false);busy=false;});
el('reset').onclick=()=>{localStorage.removeItem('fliperama-crystal-state');loadLevel(levelIndex,false)};el('resultAction').onclick=()=>{el('result').hidden=true;if(engine.status==='victory'&&levelIndex<11){localStorage.removeItem('fliperama-crystal-state');loadLevel(levelIndex+1,false);}else if(engine.status==='victory'){localStorage.removeItem('fliperama-crystal-state');loadLevel(0,false);}else{localStorage.removeItem('fliperama-crystal-state');loadLevel(levelIndex,false);}};

addEventListener('keydown',e=>{if(e.code==='KeyR'){localStorage.removeItem('fliperama-crystal-state');loadLevel(levelIndex,false);}});
addEventListener('message',e=>{if((location.origin!=='null'&&e.origin!==location.origin)||e.data?.source!=='fliperama-ds')return;const t=e.data.type;if(t==='pause')portalPaused=true;else if(t==='resume'||t==='start')portalPaused=false;else if(t==='restart'){portalPaused=false;localStorage.removeItem('fliperama-crystal-state');loadLevel(0,false);}else if(t==='shutdown')portalPaused=true;});

// Lightweight real WebGL backdrop: crystalline field, camera and animated lights.
const canvas=el('scene');const renderer=new THREE.WebGLRenderer({canvas,alpha:false,antialias:quality!=='baixo'});renderer.setPixelRatio(Math.min(devicePixelRatio,quality==='ultra'?1.75:quality==='alto'?1.4:1.05));const scene=new THREE.Scene();scene.background=new THREE.Color(0x050816);scene.fog=new THREE.FogExp2(0x071025,.055);const camera=new THREE.PerspectiveCamera(55,1,.1,100);camera.position.set(0,2.5,13);scene.add(new THREE.HemisphereLight(0x8edfff,0x170a35,1.1));const light=new THREE.PointLight(0xc28cff,22,30);light.position.set(2,5,5);scene.add(light);const group=new THREE.Group();scene.add(group);const count=quality==='baixo'?18:quality==='medio'?28:quality==='alto'?40:54;for(let i=0;i<count;i++){const geo=new THREE.OctahedronGeometry(.18+Math.random()*.45,0);const mat=new THREE.MeshStandardMaterial({color:new THREE.Color(colors[i%colors.length]),metalness:.25,roughness:.23,emissive:new THREE.Color(colors[i%colors.length]),emissiveIntensity:.16,transparent:true,opacity:.45+Math.random()*.35});const m=new THREE.Mesh(geo,mat);m.position.set((Math.random()-.5)*18,(Math.random()-.5)*11,-2-Math.random()*18);m.rotation.set(Math.random()*3,Math.random()*3,Math.random()*3);m.userData.speed=.08+Math.random()*.2;group.add(m)}function resize(){const w=innerWidth,h=innerHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}addEventListener('resize',resize);resize();let last=performance.now();function frame(t){const dt=Math.min(.04,(t-last)/1000);last=t;if(!reduced){group.rotation.y+=dt*.035;group.children.forEach(m=>{m.rotation.x+=dt*m.userData.speed;m.rotation.y+=dt*m.userData.speed*.8});light.position.x=Math.sin(t*.00035)*5;}renderer.render(scene,camera);requestAnimationFrame(frame)}requestAnimationFrame(frame);
loadLevel(levelIndex,true);post('ready',{renderer:'three+dom',runtime:'crystal-cascade-3d',levels:12});
