import { ImmersiveInputController } from '../../core/input/ImmersiveInputController.js';
import { OrbitalFlightModel } from '../../core/station-remaster/OrbitalFlightModel.js';
import { StationRemasterExperience } from '../../core/station-remaster/StationRemasterExperience.js';
import { StationRemasterSceneRenderer } from '../../rendering/StationRemasterSceneRenderer.js';
import { STATION_VARIANTS, ORBITAL_VEHICLES, ORBITAL_SATELLITES, STATION_CAMERA_PRESETS, STATION_INSPECTIONS, SIX_DOF_AXES, STATION_BY_ID, ORBITAL_VEHICLE_BY_ID, SATELLITE_BY_ID } from '../../data/stationRemasterSystems.js';

const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const fmt=(value,digits=1)=>Number(value??0).toLocaleString('pt-BR',{minimumFractionDigits:digits,maximumFractionDigits:digits});

class StationRemasterModule {
  constructor(){
    this.container=null;this.context=null;this.experience=new StationRemasterExperience();this.input=null;this.renderer=null;this.worker=null;this.fallback=null;this.fallbackTimer=0;this.inputClock=0;this.telemetry=new OrbitalFlightModel().telemetry();this.rendererInfo={fps:0,webgl:false,resolution:'--'};this.logs=[];
    this.inspectionOpen=false;this.fleetOpen=false;this.helpOpen=false;this.replayOpen=false;this.dockingMode=false;this.settingsUnsub=null;this.replayTimer=0;
    this.onClick=e=>this.handleClick(e);this.onInput=e=>this.handleRange(e);this.onKeyDown=e=>this.handleKeyDown(e);
  }
  mount(container,context){
    this.container=container;this.context=context;container.addEventListener('click',this.onClick);container.addEventListener('input',this.onInput);addEventListener('keydown',this.onKeyDown);
    this.restoreProgress();this.render();this.startRenderer();this.startWorker();this.settingsUnsub=context.bus.on('settings:changed',()=>this.restartRenderer());
  }
  unmount(){
    clearInterval(this.fallbackTimer);clearInterval(this.replayTimer);this.worker?.postMessage({type:'stop'});this.worker?.terminate();this.worker=null;this.renderer?.destroy();this.input?.detach();this.settingsUnsub?.();
    this.container?.removeEventListener('click',this.onClick);this.container?.removeEventListener('input',this.onInput);removeEventListener('keydown',this.onKeyDown);
  }
  restoreProgress(){const done=this.context?.profileStore?.active?.().completedExperiences??[];for(const item of STATION_INSPECTIONS)if(done.includes(`station-remaster-inspection-${item.id}`))this.experience.inspections.add(item.id);}
  render(){
    const station=STATION_BY_ID[this.experience.stationId],vehicle=ORBITAL_VEHICLE_BY_ID[this.experience.vehicleId],satellite=SATELLITE_BY_ID[this.experience.satelliteId],profile=this.context.settingsStore.getProfile(),snap=this.experience.snapshot();
    this.container.innerHTML=`<section class="station-remaster-module quality-${profile.id}"><div class="station-remaster-stage" id="station-remaster-stage">
      <canvas id="station-remaster-canvas" aria-label="Estação espacial, veículos e satélites em ambiente 3D e 360 graus"></canvas><div class="station-remaster-vignette"></div><div class="station-remaster-grain"></div><div class="station-remaster-cockpit"></div>
      <header class="immersive-hud station-remaster-top"><button class="hud-icon" data-action="back" aria-label="Voltar">←</button><div class="target-chip"><span id="sr-target-icon" style="color:${station.color}">${station.symbol}</span><div><b id="sr-target-name">${escapeHtml(station.name)}</b><small id="sr-target-class">${escapeHtml(station.className)}</small></div></div><div class="station-remaster-top-actions"><span class="hud-status" id="sr-state">${escapeHtml(this.telemetry.state)}</span><span class="hud-status"><b id="sr-fps">--</b> FPS</span><button class="hud-icon" data-action="toggle-help">?</button><button class="hud-icon" data-action="fullscreen">⛶</button></div></header>
      <div class="objective-chip station-remaster-objective"><span>OPERAÇÃO ORBITAL</span><b id="sr-objective">Explore exterior, interior, EVA, veículos e satélites. Depois realize um acoplamento seguro.</b></div>
      <aside class="station-remaster-telemetry immersive-hud"><div><span>DIST</span><b id="sr-distance">${fmt(this.telemetry.distanceM)} m</b></div><div><span>VEL REL</span><b id="sr-speed">${fmt(this.telemetry.relativeSpeed,2)} m/s</b></div><div><span>ALINH.</span><b id="sr-align">${fmt(this.telemetry.alignmentErrorDeg)}°</b></div><div><span>RCS</span><b id="sr-fuel">${fmt(this.telemetry.fuelPercent,0)}%</b></div><div><span>CÂMERA</span><b id="sr-camera">360</b></div></aside>
      <div class="station-remaster-crosshair"><i></i><i></i></div>
      <nav class="station-variant-dock immersive-hud" aria-label="Configurações de estação">${STATION_VARIANTS.map(item=>`<button class="station-variant-orb ${item.id===station.id?'active':''}" data-action="select-station" data-station="${item.id}" style="--station-color:${item.color}"><i>${item.symbol}</i><span><b>${escapeHtml(item.name)}</b><small>${escapeHtml(item.className)}</small></span></button>`).join('')}</nav>
      <nav class="station-camera-rail immersive-hud" aria-label="Câmeras 3D">${STATION_CAMERA_PRESETS.map(item=>`<button class="${item.id===snap.cameraId?'active':''}" data-action="select-camera" data-camera="${item.id}" title="${escapeHtml(item.description)}"><i>${item.short}</i><span>${escapeHtml(item.label)}</span></button>`).join('')}</nav>
      <div class="station-action-stack immersive-hud"><button data-action="toggle-inspection">INSPEÇÃO <b>${snap.inspections.length}/5</b></button><button data-action="toggle-fleet">FROTA</button><button class="${this.dockingMode?'active':''}" data-action="toggle-docking">ACOPLAR</button><button data-action="toggle-autopilot">AUTO ${this.telemetry.autopilot?'ON':'OFF'}</button><button data-action="toggle-replay" ${snap.replayLength?'':'disabled'}>REPLAY</button><button data-action="open-technical">SISTEMAS</button><button data-action="toggle-photo">FOTO</button></div>
      <aside class="station-inspection-drawer immersive-hud ${this.inspectionOpen?'open':''}"><button class="drawer-close" data-action="toggle-inspection">×</button><span class="eyebrow">Inspeção 3D/360°</span><h3>Validação visual da operação</h3><p>${escapeHtml(station.description)}</p><div class="station-remaster-inspection-list">${STATION_INSPECTIONS.map(item=>`<article class="${snap.inspections.includes(item.id)?'done':''}"><button data-action="go-inspection" data-inspection="${item.id}"><i>${snap.inspections.includes(item.id)?'✓':'○'}</i><span><b>${escapeHtml(item.label)}</b><small>${escapeHtml(item.detail)}</small></span></button><button class="button small ${snap.inspections.includes(item.id)?'secondary':'primary'}" data-action="validate-inspection" data-inspection="${item.id}">${snap.inspections.includes(item.id)?'Revisar':'Validar'}</button></article>`).join('')}</div><div class="station-remaster-specs">${station.modules.map(item=>`<span>${escapeHtml(item)}</span>`).join('')}<span>${fmt(station.orbitKm,0)} km</span>${station.fictional?'<span>Conceito didático</span>':''}</div></aside>
      <aside class="station-fleet-drawer immersive-hud ${this.fleetOpen?'open':''}"><button class="drawer-close" data-action="toggle-fleet">×</button><span class="eyebrow">Frota orbital</span><h3>Veículos e satélites</h3><div class="fleet-tabs"><b>VEÍCULOS</b>${ORBITAL_VEHICLES.map(item=>`<button class="fleet-card ${item.id===vehicle.id?'active':''}" data-action="select-vehicle" data-vehicle="${item.id}" style="--fleet-color:${item.color}"><i>${item.symbol}</i><span><strong>${escapeHtml(item.name)}</strong><small>${escapeHtml(item.className)} · ${escapeHtml(item.dimensions)}</small></span></button>`).join('')}<b>SATÉLITES</b>${ORBITAL_SATELLITES.map(item=>`<button class="fleet-card ${item.id===satellite.id?'active':''}" data-action="select-satellite" data-satellite="${item.id}" style="--fleet-color:${item.color}"><i>${item.symbol}</i><span><strong>${escapeHtml(item.name)}</strong><small>${escapeHtml(item.className)} · ${fmt(item.altitudeKm,0)} km</small></span></button>`).join('')}</div></aside>
      <aside class="station-replay-drawer immersive-hud ${this.replayOpen?'open':''}"><button class="drawer-close" data-action="toggle-replay">×</button><span class="eyebrow">Replay orbital</span><h3>Revise a aproximação em seis graus de liberdade</h3><input id="sr-replay-range" type="range" min="0" max="${Math.max(0,snap.replayLength-1)}" value="${snap.replayIndex}" data-action="replay-range"><div class="launch-replay-controls"><button data-action="replay-step" data-step="-15">−15</button><button data-action="replay-play">${snap.replayPlaying?'PAUSAR':'PLAY'}</button><button data-action="replay-step" data-step="15">+15</button></div><div class="station-replay-readout" id="sr-replay-readout">${this.replayReadout()}</div></aside>
      <aside class="station-help-overlay immersive-hud ${this.helpOpen?'open':''}"><button class="drawer-close" data-action="toggle-help">×</button><span class="eyebrow">Controles 6DOF</span><h3>Movimento completo no espaço</h3><div class="control-grid">${SIX_DOF_AXES.map(axis=>`<span><kbd>${axis.keys}</kbd>${axis.label}</span>`).join('')}<span><kbd>C</kbd>próxima câmera</span><span><kbd>B</kbd>próxima estação</span><span><kbd>V</kbd>próximo veículo</span><span><kbd>N</kbd>próximo satélite</span><span><kbd>K</kbd>piloto automático</span><span><kbd>P</kbd>modo foto</span></div><p>No celular, use os joysticks virtuais e os botões de rolagem. Controles físicos são detectados pela Gamepad API.</p></aside>
      <div class="virtual-joysticks station-remaster-joysticks"><div class="virtual-joystick left" data-stick="left"><div class="joystick-ring"></div><div class="joystick-knob"></div><span>MOVER</span></div><div class="virtual-joystick right" data-stick="right"><div class="joystick-ring"></div><div class="joystick-knob"></div><span>OLHAR</span></div></div>
      <div class="station-roll-controls immersive-hud"><button data-action="roll" data-roll="-1">↶</button><button data-action="lift" data-lift="1">↑</button><button data-action="lift" data-lift="-1">↓</button><button data-action="roll" data-roll="1">↷</button></div>
      <div class="station-docking-panel immersive-hud ${this.dockingMode?'open':''}"><span>AUTODOCK</span><b id="sr-dock-envelope">${this.dockingEnvelope()}</b><button data-action="abort-docking">ABORTAR</button><button data-action="reset-flight">RESET</button></div>
      <div class="station-remaster-loading" id="station-remaster-loading"><i></i><b>Inicializando ambiente orbital 3D</b><span>Estação, veículos, satélites e câmeras</span></div>
    </div></section>`;
    this.updatePhotoMode();
  }
  startRenderer(){
    const canvas=this.container.querySelector('#station-remaster-canvas');this.input=new ImmersiveInputController({canvas,root:this.container,leftStick:this.container.querySelector('[data-stick="left"]'),rightStick:this.container.querySelector('[data-stick="right"]')});this.input.attach();
    this.renderer=new StationRemasterSceneRenderer(canvas,this.context.settingsStore,this.input,this.experience,{onTelemetry:data=>this.updateRendererTelemetry(data),onInput:(input,dt)=>this.forwardInput(input,dt),onContextState:state=>this.context.toast(state==='lost'?'Contexto gráfico perdido. A física orbital foi preservada.':'Contexto gráfico restaurado.')});this.applyVariants();this.renderer.setFlight(this.telemetry);this.renderer.start();setTimeout(()=>this.container.querySelector('#station-remaster-loading')?.classList.add('hidden'),500);
  }
  restartRenderer(){this.renderer?.destroy();this.input?.detach();this.startRenderer();}
  startWorker(){
    const vehicle=ORBITAL_VEHICLE_BY_ID[this.experience.vehicleId];try{this.worker=new Worker(new URL('../../workers/orbital-flight.worker.js',import.meta.url),{type:'module'});this.worker.onmessage=e=>this.handleWorkerMessage(e.data);this.worker.onerror=()=>this.activateFallback();this.worker.postMessage({type:'quality',payload:{quality:this.context.settingsStore.getProfile().id}});this.worker.postMessage({type:'configure',payload:{vehicleId:vehicle.id,fuelKg:vehicle.fuelKg}});this.worker.postMessage({type:'start'});}catch(error){this.activateFallback();}
  }
  activateFallback(){if(this.worker){this.worker.terminate();this.worker=null;}const vehicle=ORBITAL_VEHICLE_BY_ID[this.experience.vehicleId];this.fallback=new OrbitalFlightModel({vehicleId:vehicle.id,fuelKg:vehicle.fuelKg});clearInterval(this.fallbackTimer);this.fallbackTimer=setInterval(()=>{this.receiveTelemetry(this.fallback.step(.05,this.lastInput||{}));this.receiveEvents(this.fallback.drainEvents());},50);this.context.toast('Worker orbital indisponível: simulação executada no modo compatível.');}
  forwardInput(input,dt){this.inputClock+=dt;if(this.inputClock<.033)return;this.inputClock=0;const flightCamera=['free-flight','cockpit','docking-port'].includes(this.experience.cameraId);const active=flightCamera?input:{};const payload={forward:active.forward||0,strafe:active.strafe||0,lift:active.lift||0,yaw:(active.lookX||0)*.025,pitch:(active.lookY||0)*.025,roll:active.roll||0,boost:Boolean(active.boost)};this.lastInput=payload;if(this.worker)this.worker.postMessage({type:'input',payload});}
  handleWorkerMessage(message){if(message.type==='telemetry')this.receiveTelemetry(message.payload);if(message.type==='events')this.receiveEvents(message.payload);}
  receiveTelemetry(payload){this.telemetry=payload;this.experience.record(payload);this.renderer?.setFlight(payload);this.updateLiveDom();if(payload.docked)this.completeDocking();}
  receiveEvents(events=[]){this.logs.push(...events);for(const event of events)this.context.toast(event.message);}
  completeDocking(){if(this.context.profileStore.addXp(520,'station-remaster-safe-docking'))this.context.toast('Acoplamento seguro concluído · 520 XP');this.updateObjective('Acoplamento concluído. Explore as demais estações, veículos e satélites.');this.checkCertification();}
  updateLiveDom(){const set=(id,value)=>{const el=this.container?.querySelector(id);if(el)el.textContent=value;};set('#sr-distance',`${fmt(this.telemetry.distanceM)} m`);set('#sr-speed',`${fmt(this.telemetry.relativeSpeed,2)} m/s`);set('#sr-align',`${fmt(this.telemetry.alignmentErrorDeg)}°`);set('#sr-fuel',`${fmt(this.telemetry.fuelPercent,0)}%`);set('#sr-state',this.telemetry.state);set('#sr-dock-envelope',this.dockingEnvelope());const range=this.container?.querySelector('#sr-replay-range');if(range){range.max=Math.max(0,this.experience.replay.length-1);if(!this.experience.replayPlaying)range.value=this.experience.replayIndex;}}
  updateRendererTelemetry(data){this.rendererInfo=data;const fps=this.container?.querySelector('#sr-fps');if(fps)fps.textContent=data.fps;const camera=this.container?.querySelector('#sr-camera');if(camera)camera.textContent=STATION_CAMERA_PRESETS.find(item=>item.id===data.camera)?.short??data.camera;}
  updateObjective(text){const el=this.container?.querySelector('#sr-objective');if(el)el.textContent=text;}
  dockingEnvelope(){if(this.telemetry.docked)return 'ACOPLADO';if(this.telemetry.collision)return 'CONTATO FORA DO ENVELOPE';if(this.telemetry.relativeSpeed<.18&&this.telemetry.alignmentErrorDeg<4.5)return 'ENVELOPE SEGURO';return 'AJUSTE VELOCIDADE E ALINHAMENTO';}
  applyVariants(){const station=STATION_BY_ID[this.experience.stationId],vehicle=ORBITAL_VEHICLE_BY_ID[this.experience.vehicleId],satellite=SATELLITE_BY_ID[this.experience.satelliteId];this.renderer?.setVariants({station:station.variant,vehicle:vehicle.variant,satellite:satellite.variant});}
  updateSelectionDom(){const station=STATION_BY_ID[this.experience.stationId];const name=this.container.querySelector('#sr-target-name'),klass=this.container.querySelector('#sr-target-class'),icon=this.container.querySelector('#sr-target-icon');if(name)name.textContent=station.name;if(klass)klass.textContent=station.className;if(icon){icon.textContent=station.symbol;icon.style.color=station.color;}this.container.querySelectorAll('[data-action="select-station"]').forEach(button=>button.classList.toggle('active',button.dataset.station===station.id));this.container.querySelectorAll('[data-action="select-vehicle"]').forEach(button=>button.classList.toggle('active',button.dataset.vehicle===this.experience.vehicleId));this.container.querySelectorAll('[data-action="select-satellite"]').forEach(button=>button.classList.toggle('active',button.dataset.satellite===this.experience.satelliteId));this.applyVariants();}
  updateCameraDom(){this.container.querySelectorAll('[data-action="select-camera"]').forEach(button=>button.classList.toggle('active',button.dataset.camera===this.experience.cameraId));}
  updateDrawers(){this.container.querySelector('.station-inspection-drawer')?.classList.toggle('open',this.inspectionOpen);this.container.querySelector('.station-fleet-drawer')?.classList.toggle('open',this.fleetOpen);this.container.querySelector('.station-help-overlay')?.classList.toggle('open',this.helpOpen);this.container.querySelector('.station-replay-drawer')?.classList.toggle('open',this.replayOpen);}
  updatePhotoMode(){this.container?.querySelector('.station-remaster-stage')?.classList.toggle('photo-mode',this.experience.photoMode);}
  replayReadout(){const item=this.experience.replay[this.experience.replayIndex]??this.telemetry;return `<span>ESTADO <b>${escapeHtml(item.state||'FREE')}</b></span><span>TEMPO <b>${fmt(item.elapsed,1)} s</b></span><span>DISTÂNCIA <b>${fmt(item.distanceM)} m</b></span><span>VEL. RELATIVA <b>${fmt(item.relativeSpeed,2)} m/s</b></span><span>ALINHAMENTO <b>${fmt(item.alignmentErrorDeg)}°</b></span><span>RCS <b>${fmt(item.fuelPercent,0)}%</b></span>`;}
  handleRange(event){if(event.target?.dataset.action==='replay-range'){const item=this.experience.setReplayIndex(event.target.value);if(item){this.renderer?.setFlight(item);this.container.querySelector('#sr-replay-readout').innerHTML=this.replayReadout();}}}
  handleClick(event){const target=event.target.closest('[data-action]');if(!target)return;const action=target.dataset.action;
    if(action==='back')return this.context.onBack();if(action==='fullscreen')return this.renderer?.requestFullscreen();if(action==='toggle-help'){this.helpOpen=!this.helpOpen;this.updateDrawers();return;}if(action==='toggle-inspection'){this.inspectionOpen=!this.inspectionOpen;this.updateDrawers();return;}if(action==='toggle-fleet'){this.fleetOpen=!this.fleetOpen;this.updateDrawers();return;}if(action==='toggle-replay'){this.replayOpen=!this.replayOpen;this.updateDrawers();return;}
    if(action==='select-camera'){this.experience.setCamera(target.dataset.camera);this.updateCameraDom();return;}if(action==='select-station'){this.experience.selectStation(target.dataset.station);this.updateSelectionDom();if(this.experience.visited.size>=3&&this.context.profileStore.addXp(240,'station-remaster-station-tour'))this.context.toast('Três arquiteturas orbitais exploradas · 240 XP');this.checkCertification();return;}
    if(action==='select-vehicle'){this.experience.selectVehicle(target.dataset.vehicle);this.updateSelectionDom();this.resetFlightForVehicle();return;}if(action==='select-satellite'){this.experience.selectSatellite(target.dataset.satellite);this.experience.setCamera('satellite-chase');this.updateSelectionDom();this.updateCameraDom();const seen=this.context.profileStore.active().completedExperiences.filter(id=>id.startsWith('station-remaster-satellite-')).length;if(this.context.profileStore.addXp(90,`station-remaster-satellite-${target.dataset.satellite}`))this.context.toast('Satélite inspecionado · 90 XP');if(seen+1>=4)this.context.profileStore.addXp(160,'station-remaster-satellite-fleet');this.checkCertification();return;}
    if(action==='go-inspection'){const item=STATION_INSPECTIONS.find(entry=>entry.id===target.dataset.inspection);if(item){this.experience.setCamera(item.camera);this.inspectionOpen=false;this.updateCameraDom();this.updateDrawers();}return;}if(action==='validate-inspection'){const result=this.experience.completeInspection(target.dataset.inspection);if(!result.ok)return this.context.toast(result.reason);if(this.context.profileStore.addXp(100,`station-remaster-inspection-${target.dataset.inspection}`))this.context.toast(`${result.item.label} validada · 100 XP`);const article=target.closest('article');article?.classList.add('done');const icon=article?.querySelector('i');if(icon)icon.textContent='✓';target.textContent='Revisar';target.classList.remove('primary');target.classList.add('secondary');const count=this.container.querySelector('[data-action="toggle-inspection"] b');if(count)count.textContent=`${this.experience.inspections.size}/5`;this.checkCertification();return;}
    if(action==='toggle-docking'){this.dockingMode=!this.dockingMode;this.container.querySelector('.station-docking-panel')?.classList.toggle('open',this.dockingMode);if(this.dockingMode){this.experience.setCamera('docking-port');this.updateCameraDom();}return;}if(action==='toggle-autopilot'){const enabled=!this.telemetry.autopilot;if(this.worker)this.worker.postMessage({type:'autopilot',payload:{enabled}});else this.fallback?.setAutopilot(enabled);this.context.toast(enabled?'Piloto automático de acoplamento ativado.':'Piloto automático desativado.');return;}
    if(action==='abort-docking'){if(this.worker)this.worker.postMessage({type:'abort'});else this.fallback?.abort();return;}if(action==='reset-flight'){if(this.worker)this.worker.postMessage({type:'reset'});else this.receiveTelemetry(this.fallback?.reset());return;}if(action==='open-technical'){sessionStorage.setItem('cosmos-ds-technical-target','station');return this.context.openModule('technical-operations');}if(action==='toggle-photo'){this.experience.togglePhotoMode();this.updatePhotoMode();return;}if(action==='roll'||action==='lift'){const input={roll:Number(target.dataset.roll)||0,lift:Number(target.dataset.lift)||0};if(this.worker)this.worker.postMessage({type:'step',payload:{dt:.16,input}});else this.receiveTelemetry(this.fallback.step(.16,input));return;}
    if(action==='replay-step'){const item=this.experience.setReplayIndex(this.experience.replayIndex+Number(target.dataset.step||0));if(item){this.renderer.setFlight(item);this.container.querySelector('#sr-replay-readout').innerHTML=this.replayReadout();const range=this.container.querySelector('#sr-replay-range');if(range)range.value=this.experience.replayIndex;}return;}if(action==='replay-play'){this.toggleReplayPlay();return;}
  }

  checkCertification(){
    const completed=this.context.profileStore.active().completedExperiences;
    const satellites=completed.filter(id=>id.startsWith('station-remaster-satellite-')).length>=4;
    const stations=completed.includes('station-remaster-station-tour');
    const docking=completed.includes('station-remaster-safe-docking');
    if(this.experience.inspections.size===STATION_INSPECTIONS.length&&satellites&&stations&&docking){
      if(this.context.profileStore.addXp(450,'station-remaster-certification'))this.context.toast('Certificação Operações Orbitais Imersivas · 450 XP');
    }
  }

  resetFlightForVehicle(){const vehicle=ORBITAL_VEHICLE_BY_ID[this.experience.vehicleId];if(this.worker){this.worker.postMessage({type:'configure',payload:{vehicleId:vehicle.id,fuelKg:vehicle.fuelKg}});this.worker.postMessage({type:'start'});}else{this.fallback=new OrbitalFlightModel({vehicleId:vehicle.id,fuelKg:vehicle.fuelKg});this.receiveTelemetry(this.fallback.telemetry());}}
  restartWorkerKeepState(){const old=this.telemetry;this.renderer?.setFlight(old);}
  toggleReplayPlay(){this.experience.replayPlaying=!this.experience.replayPlaying;clearInterval(this.replayTimer);if(this.experience.replayPlaying)this.replayTimer=setInterval(()=>{const next=this.experience.replayIndex+1;if(next>=this.experience.replay.length){this.experience.replayPlaying=false;clearInterval(this.replayTimer);return;}const item=this.experience.setReplayIndex(next);this.renderer?.setFlight(item);const range=this.container.querySelector('#sr-replay-range');if(range)range.value=next;const readout=this.container.querySelector('#sr-replay-readout');if(readout)readout.innerHTML=this.replayReadout();},80);this.replayOpen=true;this.updateDrawers();}
  handleKeyDown(event){if(['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName))return;if(event.code==='KeyC'){this.experience.cycleCamera();this.updateCameraDom();}if(event.code==='KeyB'){const ids=STATION_VARIANTS.map(item=>item.id),next=ids[(ids.indexOf(this.experience.stationId)+1)%ids.length];this.experience.selectStation(next);this.updateSelectionDom();}if(event.code==='KeyV'){const ids=ORBITAL_VEHICLES.map(item=>item.id),next=ids[(ids.indexOf(this.experience.vehicleId)+1)%ids.length];this.experience.selectVehicle(next);this.updateSelectionDom();this.resetFlightForVehicle();}if(event.code==='KeyN'){const ids=ORBITAL_SATELLITES.map(item=>item.id),next=ids[(ids.indexOf(this.experience.satelliteId)+1)%ids.length];this.experience.selectSatellite(next);this.experience.setCamera('satellite-chase');this.updateSelectionDom();this.updateCameraDom();}if(event.code==='KeyK'){const enabled=!this.telemetry.autopilot;if(this.worker)this.worker.postMessage({type:'autopilot',payload:{enabled}});else this.fallback?.setAutopilot(enabled);}if(event.code==='KeyP'){this.experience.togglePhotoMode();this.updatePhotoMode();}if(event.code==='KeyR')this.renderer?.resetCamera();if(event.code==='KeyO'){this.experience.setCamera('station-orbit');this.renderer?.resetCamera();this.updateCameraDom();}}
}

export function createModule(){return new StationRemasterModule();}
