-- APPLIED/LIVE SAFE CATALOG — LAB Virtual tools only.
-- Idempotent: contains no economic rewards.
do $$ declare p uuid; begin
select id into p from public.platforms where code='lab-virtual';
if p is null then raise exception 'platform lab-virtual missing'; end if;
insert into public.activity_catalog(platform_id,activity_id,name,reward_policy,max_xp,max_points,max_coins,repeatable,active,metadata) values
(p,'tool:cmd','Prompt de Comando — CMD','no_economic_reward',0,0,0,false,true,'{"kind":"tool","toolId":"cmd","level":"basic","module":"","type":"terminal"}'::jsonb),
(p,'tool:powershell','Windows PowerShell','no_economic_reward',0,0,0,false,true,'{"kind":"tool","toolId":"powershell","level":"intermediate","module":"","type":"terminal"}'::jsonb),
(p,'tool:bash','Terminal Linux — Bash','no_economic_reward',0,0,0,false,true,'{"kind":"tool","toolId":"bash","level":"basic","module":"","type":"terminal"}'::jsonb),
(p,'tool:ubuntu','Terminal Ubuntu','no_economic_reward',0,0,0,false,true,'{"kind":"tool","toolId":"ubuntu","level":"basic","module":"","type":"terminal"}'::jsonb),
(p,'tool:debian','Terminal Debian','no_economic_reward',0,0,0,false,true,'{"kind":"tool","toolId":"debian","level":"basic","module":"","type":"terminal"}'::jsonb),
(p,'tool:kali','Terminal Kali Linux','no_economic_reward',0,0,0,false,true,'{"kind":"tool","toolId":"kali","level":"advanced","module":"","type":"terminal"}'::jsonb),
(p,'tool:fedora','Terminal Fedora','no_economic_reward',0,0,0,false,true,'{"kind":"tool","toolId":"fedora","level":"intermediate","module":"","type":"terminal"}'::jsonb),
(p,'tool:chromeos','Terminal ChromeOS — Crosh','no_economic_reward',0,0,0,false,true,'{"kind":"tool","toolId":"chromeos","level":"basic","module":"","type":"terminal"}'::jsonb),
(p,'tool:macos','Terminal macOS — Zsh','no_economic_reward',0,0,0,false,true,'{"kind":"tool","toolId":"macos","level":"intermediate","module":"","type":"terminal"}'::jsonb),
(p,'tool:python','Ambiente Python','no_economic_reward',0,0,0,false,true,'{"kind":"tool","toolId":"python","level":"basic","module":"python-lab","type":"lab"}'::jsonb),
(p,'tool:javascript','Ambiente JavaScript','no_economic_reward',0,0,0,false,true,'{"kind":"tool","toolId":"javascript","level":"basic","module":"javascript-lab","type":"lab"}'::jsonb),
(p,'tool:web','HTML, CSS e JavaScript Web','no_economic_reward',0,0,0,false,true,'{"kind":"tool","toolId":"web","level":"intermediate","module":"web-lab","type":"lab"}'::jsonb),
(p,'tool:sql','Laboratório SQL','no_economic_reward',0,0,0,false,true,'{"kind":"tool","toolId":"sql","level":"intermediate","module":"sql-lab","type":"lab"}'::jsonb),
(p,'tool:network','Laboratório de Redes','no_economic_reward',0,0,0,false,true,'{"kind":"tool","toolId":"network","level":"intermediate","module":"network-lab","type":"lab"}'::jsonb),
(p,'tool:virtual-machine','Sistemas Operacionais e Máquinas Virtuais','no_economic_reward',0,0,0,false,true,'{"kind":"tool","toolId":"virtual-machine","level":"advanced","module":"vm-lab","type":"lab"}'::jsonb),
(p,'tool:hardware','Hardware Studio 3D','no_economic_reward',0,0,0,false,true,'{"kind":"tool","toolId":"hardware","level":"intermediate","module":"hardware-lab","type":"lab"}'::jsonb),
(p,'tool:graphics','Cores, Pixels e Resolução','no_economic_reward',0,0,0,false,true,'{"kind":"tool","toolId":"graphics","level":"basic","module":"graphics-lab","type":"lab"}'::jsonb),
(p,'tool:block-programming','Programação em Blocos','no_economic_reward',0,0,0,false,true,'{"kind":"tool","toolId":"block-programming","level":"basic","module":"blocks-lab","type":"lab"}'::jsonb),
(p,'tool:data-tools','Bits, Bases e Codificações','no_economic_reward',0,0,0,false,true,'{"kind":"tool","toolId":"data-tools","level":"basic","module":"data-tools-lab","type":"lab"}'::jsonb),
(p,'tool:git-github','Git e GitHub','no_economic_reward',0,0,0,false,true,'{"kind":"tool","toolId":"git-github","level":"intermediate","module":"git-lab","type":"lab"}'::jsonb),
(p,'tool:cybersecurity','Cibersegurança Defensiva','no_economic_reward',0,0,0,false,true,'{"kind":"tool","toolId":"cybersecurity","level":"advanced","module":"security-lab","type":"lab"}'::jsonb),
(p,'tool:cyber-ops','Cyber Ops — Shadow Grid','no_economic_reward',0,0,0,false,true,'{"kind":"tool","toolId":"cyber-ops","level":"advanced","module":"cyber-ops-lab","type":"lab"}'::jsonb),
(p,'tool:sysadmin','Administração de Sistemas e Redes','no_economic_reward',0,0,0,false,true,'{"kind":"tool","toolId":"sysadmin","level":"advanced","module":"sysadmin-lab","type":"lab"}'::jsonb),
(p,'tool:code-games','Simuladores Interativos DS','no_economic_reward',0,0,0,false,true,'{"kind":"tool","toolId":"code-games","level":"intermediate","module":"code-games-lab","type":"lab"}'::jsonb),
(p,'tool:voxelcraft-3d','VoxelCraft DS 3D','no_economic_reward',0,0,0,false,true,'{"kind":"tool","toolId":"voxelcraft-3d","level":"advanced","module":"voxelcraft-lab","type":"lab"}'::jsonb),
(p,'tool:fintech-pix','Fintech, Caixa Eletrônico e Pix','no_economic_reward',0,0,0,false,true,'{"kind":"tool","toolId":"fintech-pix","level":"intermediate","module":"fintech-lab","type":"lab"}'::jsonb),
(p,'tool:blockchain-crypto','Blockchain e Criptomoedas','no_economic_reward',0,0,0,false,true,'{"kind":"tool","toolId":"blockchain-crypto","level":"advanced","module":"blockchain-lab","type":"lab"}'::jsonb),
(p,'tool:digital-communication','E-mail, Mensagens e Criptografia','no_economic_reward',0,0,0,false,true,'{"kind":"tool","toolId":"digital-communication","level":"intermediate","module":"communication-lab","type":"lab"}'::jsonb),
(p,'tool:display-media','Telas, Pixels, FPS, Hertz e Áudio','no_economic_reward',0,0,0,false,true,'{"kind":"tool","toolId":"display-media","level":"intermediate","module":"display-media-lab","type":"lab"}'::jsonb),
(p,'tool:automation-iot','Automação, IoT, OCR e Robótica','no_economic_reward',0,0,0,false,true,'{"kind":"tool","toolId":"automation-iot","level":"advanced","module":"automation-lab","type":"lab"}'::jsonb),
(p,'tool:help-center','Central de Ajuda e Conhecimento','no_economic_reward',0,0,0,false,true,'{"kind":"tool","toolId":"help-center","level":"basic","module":"help-center-lab","type":"lab"}'::jsonb),
(p,'tool:tutorial-center','Central de Tutoriais e Passo a Passo','no_economic_reward',0,0,0,false,true,'{"kind":"tool","toolId":"tutorial-center","level":"basic","module":"tutorial-center-lab","type":"lab"}'::jsonb),
(p,'tool:tech-explorer','Explorar Tecnologia, Linguagens e Carreiras','no_economic_reward',0,0,0,false,true,'{"kind":"tool","toolId":"tech-explorer","level":"basic","module":"tech-explorer-lab","type":"lab"}'::jsonb),
(p,'tool:productivity-suite','Produtividade e Escritório','no_economic_reward',0,0,0,false,true,'{"kind":"tool","toolId":"productivity-suite","level":"intermediate","module":"productivity-lab","type":"lab"}'::jsonb),
(p,'tool:market-simulator','Mercado Tech e Análise de Gráficos','no_economic_reward',0,0,0,false,true,'{"kind":"tool","toolId":"market-simulator","level":"intermediate","module":"market-lab","type":"lab"}'::jsonb),
(p,'tool:printing-3d','Impressão 3D e Modelagem','no_economic_reward',0,0,0,false,true,'{"kind":"tool","toolId":"printing-3d","level":"intermediate","module":"printing3d-lab","type":"lab"}'::jsonb),
(p,'tool:energy-systems','Energia, Queda de Tensão, Solar e Eólica','no_economic_reward',0,0,0,false,true,'{"kind":"tool","toolId":"energy-systems","level":"intermediate","module":"energy-lab","type":"lab"}'::jsonb),
(p,'tool:traffic-radar','Radar, Semáforo e Trânsito Inteligente','no_economic_reward',0,0,0,false,true,'{"kind":"tool","toolId":"traffic-radar","level":"intermediate","module":"traffic-lab","type":"lab"}'::jsonb),
(p,'tool:world-tools','Relógios Mundiais, Alarmes e Conversores','no_economic_reward',0,0,0,false,true,'{"kind":"tool","toolId":"world-tools","level":"basic","module":"world-tools-lab","type":"lab"}'::jsonb),
(p,'tool:solar-system','Sistema Solar Interativo 2D e Perspectiva','no_economic_reward',0,0,0,false,true,'{"kind":"tool","toolId":"solar-system","level":"intermediate","module":"solar-system-lab","type":"lab"}'::jsonb),
(p,'tool:school-randomizer','Sorteios, Turmas e Organização Escolar','no_economic_reward',0,0,0,false,true,'{"kind":"tool","toolId":"school-randomizer","level":"basic","module":"school-randomizer-lab","type":"lab"}'::jsonb),
(p,'tool:biomonitor','BioMonitor — Batimentos e Sinais','no_economic_reward',0,0,0,false,true,'{"kind":"tool","toolId":"biomonitor","level":"intermediate","module":"biomonitor-lab","type":"lab"}'::jsonb),
(p,'tool:thermal-panel','Clima Extremo — Temperatura e Sensores','no_economic_reward',0,0,0,false,true,'{"kind":"tool","toolId":"thermal-panel","level":"intermediate","module":"thermal-panel-lab","type":"lab"}'::jsonb),
(p,'tool:audio-lab','AudioLab — Frequências e Equalização','no_economic_reward',0,0,0,false,true,'{"kind":"tool","toolId":"audio-lab","level":"intermediate","module":"audio-lab","type":"lab"}'::jsonb),
(p,'tool:iptv-streaming','IPTV, Streaming e Qualidade de Rede','no_economic_reward',0,0,0,false,true,'{"kind":"tool","toolId":"iptv-streaming","level":"intermediate","module":"iptv-lab","type":"lab"}'::jsonb),
(p,'tool:device-sensors','Câmera, Microfone e Sensores do Dispositivo','no_economic_reward',0,0,0,false,true,'{"kind":"tool","toolId":"device-sensors","level":"intermediate","module":"device-lab","type":"lab"}'::jsonb),
(p,'tool:artificial-intelligence','Inteligência Artificial e Redes Neurais','no_economic_reward',0,0,0,false,true,'{"kind":"tool","toolId":"artificial-intelligence","level":"advanced","module":"ai-lab","type":"lab"}'::jsonb),
(p,'tool:network-operations','Rack, MikroTik, CFTV e Cabeamento','no_economic_reward',0,0,0,false,true,'{"kind":"tool","toolId":"network-operations","level":"advanced","module":"network-ops-lab","type":"lab"}'::jsonb),
(p,'tool:game-engine','Laboratório de Engine e Renderização','no_economic_reward',0,0,0,false,true,'{"kind":"tool","toolId":"game-engine","level":"advanced","module":"game-engine-lab","type":"lab"}'::jsonb),
(p,'tool:electronics','Eletrônica, Energia e Calculadoras','no_economic_reward',0,0,0,false,true,'{"kind":"tool","toolId":"electronics","level":"intermediate","module":"electronics-lab","type":"lab"}'::jsonb)
on conflict(platform_id,activity_id) do update set name=excluded.name,reward_policy=excluded.reward_policy,max_xp=0,max_points=0,max_coins=0,repeatable=false,active=true,metadata=excluded.metadata;
end $$;
