-- Etapa 4 / v14.8.9 — regras públicas de validação replicadas no servidor.
-- Não contém gabarito; somente critérios que já existem no bundle do aluno.
with rules(subject_slug, exercise_number, validation) as (
  values
    ('introducao-programacao', 1, $agv${"minChars":120,"regras":[{"arquivo":"main.py","rotulo":"Entrada de dados","padroes":["\\binput\\s*\\("]},{"arquivo":"main.py","rotulo":"Conversão para inteiro","padroes":["\\bint\\s*\\("]},{"arquivo":"main.py","rotulo":"Conversão para decimal","padroes":["\\bfloat\\s*\\("]},{"arquivo":"main.py","rotulo":"Saída formatada","padroes":["f[\\\"\\']|\\.format\\s*\\("]}]}$agv$::jsonb),
    ('introducao-programacao', 2, $agv${"minChars":300,"regras":[{"arquivo":"main.py","rotulo":"Cinco entradas de dados","padroes":["(?:input\\s*\\([^)]*\\).*?){5}"]},{"arquivo":"main.py","rotulo":"Conversões float e int","padroes":["float\\s*\\(","int\\s*\\("],"modo":"todos"},{"arquivo":"main.py","rotulo":"Soma e divisão","padroes":["\\+","(?<!/)\\/(?!/)"],"modo":"todos"},{"arquivo":"main.py","rotulo":"Subtração ou diferença absoluta","padroes":["abs\\s*\\(","\\-"]},{"arquivo":"main.py","rotulo":"Divisão inteira","padroes":["//"]},{"arquivo":"main.py","rotulo":"Resto da divisão","padroes":["%"]},{"arquivo":"main.py","rotulo":"Potência","padroes":["\\*\\*"]},{"arquivo":"main.py","rotulo":"Arredondamento","padroes":["round\\s*\\(","\\.\\d+f"]},{"arquivo":"main.py","rotulo":"Saída formatada","padroes":["f[\\\"\\']","\\.format\\s*\\("]}]}$agv$::jsonb),
    ('introducao-programacao', 3, $agv${"minChars":180,"regras":[{"arquivo":"main.py","rotulo":"Entrada do nome e da idade","padroes":["(?:input\\s*\\([^)]*\\).*?){2}"]},{"arquivo":"main.py","rotulo":"Conversão da idade para inteiro","padroes":["\\bint\\s*\\("]},{"arquivo":"main.py","rotulo":"Condição if com comparação","padroes":["\\bif\\s+[^\\n:]+(?:>=|>|==|<=|<)[^\\n:]*:"]},{"arquivo":"main.py","rotulo":"Caminho alternativo com else","padroes":["\\belse\\s*:"]},{"arquivo":"main.py","rotulo":"Saída nos dois caminhos","padroes":["(?:\\bprint\\s*\\([^\\n]*\\).*?){2}"]},{"arquivo":"main.py","rotulo":"Mensagem formatada ou personalizada","padroes":["f[\\\"\\']","\\.format\\s*\\("]}]}$agv$::jsonb),
    ('introducao-programacao', 4, $agv${"minChars":210,"regras":[{"arquivo":"main.py","rotulo":"Nome e duas notas","padroes":["(?:input\\s*\\([^)]*\\).*?){3}"]},{"arquivo":"main.py","rotulo":"Conversão das notas para decimal","padroes":["(?:\\bfloat\\s*\\([^\\n]*\\).*?){2}"]},{"arquivo":"main.py","rotulo":"Cálculo da média","padroes":["=\\s*\\(?[^\\n=]+\\+[^\\n=]+\\)?\\s*\\/\\s*2","sum\\s*\\([^)]*\\)\\s*\\/\\s*2"]},{"arquivo":"main.py","rotulo":"Primeiro caminho com if","padroes":["\\bif\\s+[^\\n:]+(?:>=|>|==|<=|<)[^\\n:]*:"]},{"arquivo":"main.py","rotulo":"Caminho intermediário com elif","padroes":["\\belif\\s+[^\\n:]+(?:>=|>|==|<=|<)[^\\n:]*:"]},{"arquivo":"main.py","rotulo":"Caminho final com else","padroes":["\\belse\\s*:"]},{"arquivo":"main.py","rotulo":"Três situações possíveis","padroes":["aprovad","recupera","reprovad"],"modo":"todos"},{"arquivo":"main.py","rotulo":"Saída formatada","padroes":["f[\\\"\\']","\\.format\\s*\\("]}]}$agv$::jsonb),
    ('introducao-programacao', 5, $agv${"minChars":430,"regras":[{"arquivo":"main.py","rotulo":"Entrada numérica de idade","padroes":["\\bint\\s*\\([^\\n]*input\\s*\\(","\\binput\\s*\\([^)]*\\)[\\s\\S]*?\\bint\\s*\\("]},{"arquivo":"main.py","rotulo":"Quatro entradas de dados","padroes":["(?:(?:\\binput\\s*\\()[\\s\\S]*?){4}"]},{"arquivo":"main.py","rotulo":"Operadores lógicos","padroes":["\\band\\b","\\bor\\b","\\bnot\\b"],"modo":"todos"},{"arquivo":"main.py","rotulo":"Decisão com if, elif e else","padroes":["\\bif\\s+[^\\n:]+:","\\belif\\s+[^\\n:]+:","\\belse\\s*:"],"modo":"todos"},{"arquivo":"main.py","rotulo":"Validação de respostas","padroes":["\\bin\\s*\\([^\\n]+\\)","Dados inválidos"],"modo":"todos"},{"arquivo":"main.py","rotulo":"Resultados de acesso","padroes":["Entrada liberada","Entrada liberada com autorização","Entrada não permitida"],"modo":"todos"},{"arquivo":"main.py","rotulo":"Saída no terminal","padroes":["\\bprint\\s*\\(","f[\"\\']"]}]}$agv$::jsonb),
    ('introducao-programacao', 6, $agv${"minChars":210,"regras":[{"arquivo":"main.py","rotulo":"Três entradas numéricas","padroes":["(?:[\\s\\S]*?input\\s*\\(){3}"]},{"arquivo":"main.py","rotulo":"Conversão para inteiro","padroes":["\\bint\\s*\\("]},{"arquivo":"main.py","rotulo":"Estrutura for","padroes":["\\bfor\\s+[A-Za-z_][A-Za-z0-9_]*\\s+in\\s+"]},{"arquivo":"main.py","rotulo":"Uso da função range","padroes":["\\brange\\s*\\("]},{"arquivo":"main.py","rotulo":"Inclusão do limite final","padroes":["range\\s*\\([^\\n)]*(?:[A-Za-z_][A-Za-z0-9_]*\\s*\\+\\s*1|1\\s*\\+\\s*[A-Za-z_][A-Za-z0-9_]*)","(?:\\+=\\s*1|=\\s*[A-Za-z_][A-Za-z0-9_]*\\s*\\+\\s*1)[\\s\\S]*?range\\s*\\("]},{"arquivo":"main.py","rotulo":"Multiplicação dentro do exercício","padroes":["\\*"]},{"arquivo":"main.py","rotulo":"Validação com if e else","padroes":["\\bif\\s+[^\\n:]+:","\\belse\\s*:"],"modo":"todos"},{"arquivo":"main.py","rotulo":"Saída formatada","padroes":["f[\\\"\\']","\\.format\\s*\\("]}]}$agv$::jsonb),
    ('introducao-programacao', 7, $agv${"minChars":360,"regras":[{"arquivo":"main.py","rotulo":"Entrada da quantidade","padroes":["\\bint\\s*\\([^\\n]*input\\s*\\("]},{"arquivo":"main.py","rotulo":"Entrada repetida de valor","padroes":["\\bfloat\\s*\\([^\\n]*input\\s*\\(","\\binput\\s*\\([^)]*\\)[\\s\\S]*?\\bfloat\\s*\\("]},{"arquivo":"main.py","rotulo":"Estrutura for com range","padroes":["\\bfor\\s+[A-Za-z_][A-Za-z0-9_]*\\s+in\\s+range\\s*\\("]},{"arquivo":"main.py","rotulo":"Uso de acumulador","padroes":["(?:([A-Za-z_][A-Za-z0-9_]*)\\s*\\+=\\s*[A-Za-z_][A-Za-z0-9_]*|([A-Za-z_][A-Za-z0-9_]*)\\s*=\\s*\\2\\s*\\+\\s*[A-Za-z_][A-Za-z0-9_]*)"]},{"arquivo":"main.py","rotulo":"Pelo menos três contagens","padroes":["(?:(?:[A-Za-z_][A-Za-z0-9_]*\\s*\\+=\\s*1|([A-Za-z_][A-Za-z0-9_]*)\\s*=\\s*\\1\\s*\\+\\s*1)[\\s\\S]*?){3}"]},{"arquivo":"main.py","rotulo":"Decisão em três faixas","padroes":["\\bif\\s+[^\\n:]+:","\\belif\\s+[^\\n:]+:","\\belse\\s*:"],"modo":"todos"},{"arquivo":"main.py","rotulo":"Cálculo de média por pedido","padroes":["[A-Za-z_][A-Za-z0-9_]*\\s*=\\s*[A-Za-z_][A-Za-z0-9_]*\\s*/\\s*[A-Za-z_][A-Za-z0-9_]*"]},{"arquivo":"main.py","rotulo":"Resumo financeiro","padroes":["Total vendido","Ticket médio","Pedidos pequenos","Pedidos médios","Pedidos grandes"],"modo":"todos"}]}$agv$::jsonb),
    ('introducao-programacao', 8, $agv${"minChars":280,"regras":[{"arquivo":"main.py","rotulo":"Entrada de senha","padroes":["\\binput\\s*\\("]},{"arquivo":"main.py","rotulo":"Estrutura while","padroes":["\\bwhile\\s+[^\\n:]+:"]},{"arquivo":"main.py","rotulo":"Controle de tentativas","padroes":["(?:[A-Za-z_][A-Za-z0-9_]*\\s*\\+=\\s*1|([A-Za-z_][A-Za-z0-9_]*)\\s*=\\s*\\1\\s*\\+\\s*1)"]},{"arquivo":"main.py","rotulo":"Comparação de senha","padroes":["=="]},{"arquivo":"main.py","rotulo":"Decisão com if e else","padroes":["\\bif\\s+[^\\n:]+:","\\belse\\s*:"],"modo":"todos"},{"arquivo":"main.py","rotulo":"Controle de encerramento","padroes":["\\bnot\\b","\\bbreak\\b"]},{"arquivo":"main.py","rotulo":"Mensagens no terminal","padroes":["\\bprint\\s*\\(","f[\"\\']"]}]}$agv$::jsonb)
)
update public.exercises e
set config = jsonb_set(coalesce(e.config,'{}'::jsonb), '{server_validation}', r.validation, true),
    updated_at = now()
from public.subjects s, rules r
where e.subject_id=s.id
  and s.slug=r.subject_slug
  and e.exercise_number=r.exercise_number;
