-- v14.10.8.29 — central de apoio, mensagens e check-ins pedagógicos
--
-- A central nasce em modo aluno-professor. Conversas entre estudantes não são
-- habilitadas por esta migration. Dados clínicos, diagnósticos e laudos não
-- pertencem a estas tabelas; registre apenas a necessidade pedagógica objetiva.

create table if not exists public.student_support_threads (
  id uuid primary key default gen_random_uuid(),
  student_id uuid not null references public.profiles(id) on delete cascade,
  category text not null check (category in ('question','help','feedback','bug')),
  subject_slug text,
  exercise_id uuid references public.exercises(id) on delete set null,
  status text not null default 'open'
    check (status in ('open','answered','waiting_student','closed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_message_at timestamptz not null default now()
);

create index if not exists student_support_threads_student_idx
  on public.student_support_threads(student_id,last_message_at desc);
create index if not exists student_support_threads_open_idx
  on public.student_support_threads(status,last_message_at desc)
  where status <> 'closed';
create index if not exists student_support_threads_exercise_idx
  on public.student_support_threads(exercise_id)
  where exercise_id is not null;

alter table public.student_support_threads enable row level security;
revoke all on table public.student_support_threads from anon, authenticated;
grant select, insert on table public.student_support_threads to authenticated;

drop policy if exists student_support_threads_select_own on public.student_support_threads;
create policy student_support_threads_select_own
  on public.student_support_threads for select to authenticated
  using (student_id=(select auth.uid()));

drop policy if exists student_support_threads_insert_own on public.student_support_threads;
create policy student_support_threads_insert_own
  on public.student_support_threads for insert to authenticated
  with check (
    student_id=(select auth.uid())
    and status='open'
    and length(coalesce(subject_slug,'')) <= 120
  );

create table if not exists public.student_support_messages (
  id bigint generated by default as identity primary key,
  thread_id uuid not null references public.student_support_threads(id) on delete cascade,
  author_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check (length(btrim(body)) between 1 and 4000),
  created_at timestamptz not null default now()
);

create index if not exists student_support_messages_thread_idx
  on public.student_support_messages(thread_id,created_at,id);
create index if not exists student_support_messages_author_idx
  on public.student_support_messages(author_id,created_at desc);

alter table public.student_support_messages enable row level security;
revoke all on table public.student_support_messages from anon, authenticated;
grant select, insert on table public.student_support_messages to authenticated;
revoke all on sequence public.student_support_messages_id_seq from anon;
grant usage on sequence public.student_support_messages_id_seq to authenticated;

drop policy if exists student_support_messages_select_own_thread on public.student_support_messages;
create policy student_support_messages_select_own_thread
  on public.student_support_messages for select to authenticated
  using (
    exists (
      select 1 from public.student_support_threads t
      where t.id=thread_id and t.student_id=(select auth.uid())
    )
  );

drop policy if exists student_support_messages_insert_own_thread on public.student_support_messages;
create policy student_support_messages_insert_own_thread
  on public.student_support_messages for insert to authenticated
  with check (
    author_id=(select auth.uid())
    and exists (
      select 1 from public.student_support_threads t
      where t.id=thread_id
        and t.student_id=(select auth.uid())
        and t.status <> 'closed'
    )
  );

-- Atualiza somente o relógio da conversa. A função é mantida fora dos schemas
-- expostos pela Data API e não aceita parâmetros controlados pelo cliente além
-- da linha já autorizada.
create schema if not exists private;

create or replace function private.trg_touch_student_support_thread()
returns trigger
language plpgsql
security definer
set search_path=''
as $$
begin
  update public.student_support_threads
  set last_message_at=new.created_at,
      updated_at=new.created_at,
      status=case when new.author_id=student_id then 'open' else status end
  where id=new.thread_id;
  return new;
end;
$$;

revoke all on function private.trg_touch_student_support_thread() from public, anon, authenticated, service_role;

drop trigger if exists on_student_support_message_touch_thread on public.student_support_messages;
create trigger on_student_support_message_touch_thread
after insert on public.student_support_messages
for each row execute function private.trg_touch_student_support_thread();

create table if not exists public.student_focus_checkins (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.profiles(id) on delete cascade,
  -- O vínculo é informativo porque a tabela de experiências é opcional e ainda
  -- não existe em todas as instalações que recebem esta migration.
  assignment_id uuid,
  exercise_id uuid references public.exercises(id) on delete set null,
  response text not null check (response in ('present','need_help','pause')),
  context jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now(),
  constraint student_focus_checkins_context_object check (jsonb_typeof(context)='object')
);

create index if not exists student_focus_checkins_student_idx
  on public.student_focus_checkins(student_id,occurred_at desc);
create index if not exists student_focus_checkins_assignment_idx
  on public.student_focus_checkins(assignment_id)
  where assignment_id is not null;
create index if not exists student_focus_checkins_exercise_idx
  on public.student_focus_checkins(exercise_id)
  where exercise_id is not null;

alter table public.student_focus_checkins enable row level security;
revoke all on table public.student_focus_checkins from anon, authenticated;
grant select, insert on table public.student_focus_checkins to authenticated;
revoke all on sequence public.student_focus_checkins_id_seq from anon;
grant usage on sequence public.student_focus_checkins_id_seq to authenticated;

drop policy if exists student_focus_checkins_select_own on public.student_focus_checkins;
create policy student_focus_checkins_select_own
  on public.student_focus_checkins for select to authenticated
  using (student_id=(select auth.uid()));

drop policy if exists student_focus_checkins_insert_own on public.student_focus_checkins;
create policy student_focus_checkins_insert_own
  on public.student_focus_checkins for insert to authenticated
  with check (student_id=(select auth.uid()));

create table if not exists public.student_support_notifications (
  id uuid primary key default gen_random_uuid(),
  student_id uuid not null references public.profiles(id) on delete cascade,
  title text not null check (length(btrim(title)) between 1 and 120),
  body text not null check (length(btrim(body)) between 1 and 1000),
  tone text not null default 'encouragement'
    check (tone in ('encouragement','celebration','guidance','reminder')),
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  read_at timestamptz
);

create index if not exists student_support_notifications_unread_idx
  on public.student_support_notifications(student_id,created_at desc)
  where read_at is null;
create index if not exists student_support_notifications_student_idx
  on public.student_support_notifications(student_id,created_at desc);
create index if not exists student_support_notifications_created_by_idx
  on public.student_support_notifications(created_by)
  where created_by is not null;

alter table public.student_support_notifications enable row level security;
revoke all on table public.student_support_notifications from anon, authenticated;
grant select, update(read_at) on table public.student_support_notifications to authenticated;

drop policy if exists student_support_notifications_select_own on public.student_support_notifications;
create policy student_support_notifications_select_own
  on public.student_support_notifications for select to authenticated
  using (student_id=(select auth.uid()));

drop policy if exists student_support_notifications_mark_own_read on public.student_support_notifications;
create policy student_support_notifications_mark_own_read
  on public.student_support_notifications for update to authenticated
  using (student_id=(select auth.uid()))
  with check (student_id=(select auth.uid()));

comment on table public.student_support_threads is
  'Conversas pedagógicas aluno-professor. Chat entre estudantes permanece desabilitado.';
comment on table public.student_focus_checkins is
  'Check-ins voluntários de presença/ajuda, sem efeito disciplinar, acadêmico ou econômico.';
comment on table public.student_support_notifications is
  'Mensagens e celebrações enviadas por professor; não concedem XP ou nota por si próprias.';
