'use strict';
(function(){
  window.LABDS_LABS=window.LABDS_LABS||{};
  const KEY='lab.networkops.state';
  const DEFAULT={tab:'rack',xp:0,wires:[],vlans:{1:[1,2,3,4],10:[5,6],20:[7,8]},cameras:[{name:'Portão',bitrate:4,online:true},{name:'Pátio',bitrate:3,online:true},{name:'Laboratório',bitrate:5,online:true},{name:'Corredor',bitrate:2,online:false}]};
  const T568B=['branco-laranja','laranja','branco-verde','azul','branco-azul','verde','branco-marrom','marrom'];
  let root,ctx,state;
  async function save(){await ctx.storage.set(KEY,state);}
  function setTab(tab){state.tab=tab;root.querySelectorAll('[data-noc-tab]').forEach(b=>b.classList.toggle('active',b.dataset.nocTab===tab));root.querySelectorAll('[data-noc-panel]').forEach(p=>p.classList.toggle('hidden',p.dataset.nocPanel!==tab));save();}
  function renderWires(){const box=root.querySelector('#wireOrder');box.textContent='';state.wires.forEach((wire,index)=>{const item=document.createElement('button');item.type='button';item.className='wire-chip';item.dataset.color=wire;item.textContent=`${index+1}. ${wire}`;item.addEventListener('click',()=>{state.wires.splice(index,1);renderWires();save();});box.appendChild(item);});root.querySelector('#wireCount').textContent=`${state.wires.length}/8`;}
  function addWire(color){if(state.wires.length>=8)return;state.wires.push(color);renderWires();save();}
  function validateCable(){const ok=state.wires.length===8&&state.wires.every((w,i)=>w===T568B[i]),out=root.querySelector('#wireFeedback');out.className=`practice-feedback ${ok?'success':'error'}`;out.textContent=ok?'Padrão T568B correto. Os pares foram mantidos na sequência adequada.':`A ordem ainda não corresponde ao T568B. Compare posições ${state.wires.findIndex((w,i)=>w!==T568B[i])+1 || 1} em diante.`;if(ok){state.xp+=25;root.querySelector('#nocXp').textContent=state.xp;save();}}
  function resetCable(){state.wires=[];renderWires();save();}
  function renderSwitch(){const box=root.querySelector('#switchPorts');box.textContent='';for(let p=1;p<=8;p++){const vlan=Object.entries(state.vlans).find(([,ports])=>ports.includes(p))?.[0]||'1';const button=document.createElement('button');button.type='button';button.className='switch-port';button.innerHTML=`<span>${p}</span><i></i><small>VLAN ${vlan}</small>`;button.addEventListener('click',()=>{const next=vlan==='1'?'10':vlan==='10'?'20':'1';for(const ports of Object.values(state.vlans)){const idx=ports.indexOf(p);if(idx>=0)ports.splice(idx,1);}state.vlans[next].push(p);renderSwitch();save();});box.appendChild(button);}}
  function applyFirewall(){const source=root.querySelector('#fwSource').value.trim(),port=Number(root.querySelector('#fwPort').value),action=root.querySelector('#fwAction').value,out=root.querySelector('#fwOutput');if(!/^\d{1,3}(\.\d{1,3}){3}(\/\d{1,2})?$/.test(source)||!Number.isInteger(port)||port<1||port>65535){out.textContent='Regra inválida. Revise rede de origem e porta.';return;}out.textContent=`/ip firewall filter add chain=forward src-address=${source} protocol=tcp dst-port=${port} action=${action}\n\nRegra simulada aplicada. Em equipamento real, revise ordem, interfaces, estado da conexão e impacto.`;state.xp+=15;root.querySelector('#nocXp').textContent=state.xp;save();}
  function renderCameras(){const box=root.querySelector('#cameraGrid');box.textContent='';state.cameras.forEach((cam,index)=>{const card=document.createElement('article');card.className=`camera-card ${cam.online?'online':'offline'}`;card.innerHTML=`<div class="camera-noise"><span>${cam.online?'REC':'SEM SINAL'}</span><i></i></div><strong></strong><small></small><button type="button">${cam.online?'Desconectar':'Reconectar'}</button>`;card.querySelector('strong').textContent=cam.name;card.querySelector('small').textContent=`${cam.bitrate} Mb/s • H.265 simulado`;card.querySelector('button').addEventListener('click',()=>{cam.online=!cam.online;renderCameras();calculateStorage();save();});box.appendChild(card);});}
  function calculateStorage(){const days=Number(root.querySelector('#storageDays')?.value||7),active=state.cameras.filter(c=>c.online),mbps=active.reduce((n,c)=>n+c.bitrate,0),gb=mbps*3600*24*days/8/1024;root.querySelector('#storageResult').textContent=`${gb.toFixed(1)} GB para ${active.length} câmera(s) em ${days} dia(s), sem considerar overhead ou gravação por movimento.`;}
  function render(){root.innerHTML=`<div class="immersive-lab network-ops-lab"><header class="immersive-hero"><div><span class="eyebrow">NOC • CABEAMENTO • CFTV</span><h2>Operações de rede e segurança eletrônica</h2><p>Organize rack, crimpe RJ45, configure VLANs, escreva regra de firewall e dimensione câmeras IP e armazenamento.</p></div><div class="immersive-badges"><span>XP <b id="nocXp">${state.xp}</b></span><span>8 portas</span><span>4 câmeras</span></div></header><nav class="module-tabs"><button data-noc-tab="rack">Rack e cabeamento</button><button data-noc-tab="switch">Switch e VLAN</button><button data-noc-tab="router">MikroTik conceitual</button><button data-noc-tab="cctv">CFTV e NVR</button></nav>
    <section data-noc-panel="rack" class="immersive-grid"><article class="immersive-card"><h3>Crimpagem T568B</h3><p>Selecione os condutores na ordem do pino 1 ao 8.</p><div class="wire-palette">${T568B.map(c=>`<button data-wire="${c}" class="wire-color" data-color="${c}">${c}</button>`).join('')}</div><div class="wire-order-head"><b>Conector RJ45</b><span id="wireCount">0/8</span></div><div id="wireOrder" class="wire-order"></div><div class="button-row"><button id="validateCable" class="btn primary">Testar cabo</button><button id="resetCable" class="btn secondary">Refazer</button></div><div id="wireFeedback" class="practice-feedback"></div></article><article class="immersive-card"><h3>Rack de comunicação</h3><div class="rack-visual"><div><span>01U</span><b>Patch panel 24 portas</b><i class="rack-lights"></i></div><div><span>02U</span><b>Switch gerenciável</b><i class="rack-lights active"></i></div><div><span>03U</span><b>Roteador / firewall</b><i class="rack-lights active"></i></div><div><span>04U</span><b>NVR e armazenamento</b><i class="rack-lights"></i></div><div><span>05U</span><b>UPS / energia</b><i class="rack-lights active"></i></div></div><div class="knowledge-card"><strong>Organização:</strong> identifique cabos, use patch panels, documente portas, respeite curvatura e separe dados de energia quando necessário.</div></article></section>
    <section data-noc-panel="switch" class="immersive-grid hidden"><article class="immersive-card"><h3>Switch gerenciável</h3><p>Clique em uma porta para alternar entre VLAN 1, 10 e 20.</p><div id="switchPorts" class="switch-ports"></div><div class="vlan-legend"><span>VLAN 1: gestão</span><span>VLAN 10: alunos</span><span>VLAN 20: câmeras</span></div></article><article class="immersive-card"><h3>Switch gerenciável × não gerenciável</h3><table class="data-table"><thead><tr><th>Recurso</th><th>Gerenciável</th><th>Não gerenciável</th></tr></thead><tbody><tr><td>VLAN</td><td>Sim</td><td>Não</td></tr><tr><td>Monitoramento</td><td>Sim</td><td>Limitado</td></tr><tr><td>Configuração</td><td>Web/CLI</td><td>Plug and play</td></tr><tr><td>Uso</td><td>Redes controladas</td><td>Expansão simples</td></tr></tbody></table></article></section>
    <section data-noc-panel="router" class="immersive-grid hidden"><article class="immersive-card router-panel"><h3>Regra de firewall — estilo RouterOS</h3><label>Rede de origem<input id="fwSource" value="192.168.10.0/24"></label><label>Porta TCP<input id="fwPort" type="number" min="1" max="65535" value="443"></label><label>Ação<select id="fwAction"><option value="accept">accept</option><option value="drop">drop</option><option value="reject">reject</option></select></label><button id="applyFirewall" class="btn primary">Gerar regra</button></article><article class="immersive-card"><h3>Terminal de configuração</h3><pre id="fwOutput" class="terminal-mini">/interface print\n/ip address print\n/ip firewall filter print</pre><div class="knowledge-card"><strong>MikroTik real:</strong> ordem de regras, conexão estabelecida, interfaces, NAT e acesso administrativo exigem planejamento. Aqui nada é enviado a um roteador.</div></article></section>
    <section data-noc-panel="cctv" class="immersive-grid hidden"><article class="immersive-card"><h3>Monitor de câmeras IP</h3><div id="cameraGrid" class="camera-grid"></div></article><article class="immersive-card"><h3>Dimensionamento do NVR</h3><label>Dias de retenção<input id="storageDays" type="range" min="1" max="30" value="7"></label><p id="storageResult"></p><div class="metric-row"><div class="metric-card"><small>PoE</small><strong>energia + dados</strong></div><div class="metric-card"><small>Bitrate</small><strong>qualidade × espaço</strong></div><div class="metric-card"><small>H.265</small><strong>compressão</strong></div></div></article></section></div>`;
    root.querySelectorAll('[data-noc-tab]').forEach(b=>b.addEventListener('click',()=>setTab(b.dataset.nocTab)));root.querySelectorAll('[data-wire]').forEach(b=>b.addEventListener('click',()=>addWire(b.dataset.wire)));root.querySelector('#validateCable').addEventListener('click',validateCable);root.querySelector('#resetCable').addEventListener('click',resetCable);root.querySelector('#applyFirewall').addEventListener('click',applyFirewall);root.querySelector('#storageDays').addEventListener('input',calculateStorage);renderWires();renderSwitch();renderCameras();calculateStorage();setTab(state.tab);
  }
  async function mount(host,context){root=host;ctx=context;state={...DEFAULT,...await ctx.storage.get(KEY,DEFAULT),vlans:{...DEFAULT.vlans,...(await ctx.storage.get(KEY,DEFAULT)).vlans}};render();}
  async function unmount(){await save();root=null;ctx=null;state=null;}
  function exportPayload(){return{text:`NOC E CFTV\nXP: ${state.xp}\nCabos selecionados: ${state.wires.length}\nCâmeras online: ${state.cameras.filter(c=>c.online).length}`,native:JSON.stringify(state,null,2),backup:state,meta:[{label:'XP',value:String(state.xp)},{label:'Câmeras',value:String(state.cameras.length)}]};}
  function help(){return'<h3>Rede, MikroTik e CFTV</h3><p>As configurações são fictícias e locais. Use o laboratório para compreender cabeamento, VLAN, firewall, câmeras e armazenamento.</p>';}
  window.LABDS_LABS['network-ops-lab']={mount,unmount,exportPayload,help};
})();
