'use strict';

(function(){
  window.LABDS=window.LABDS||{};
  const common={
    tutorial:[
      {title:'Conheça o ambiente',text:'Observe os painéis, a barra de ferramentas, o estado atual e os avisos de execução real ou simulada.'},
      {title:'Teste uma ação segura',text:'Use um exemplo, faça uma alteração pequena e confira imediatamente o resultado.'},
      {title:'Analise o resultado',text:'Compare o que você esperava com o que o laboratório exibiu. Erros fazem parte da prática.'},
      {title:'Registre e exporte',text:'Use o histórico e a exportação para documentar o que foi realizado.'}
    ],
    guided:['Abra o exemplo inicial.','Faça uma alteração observável.','Execute ou teste.','Corrija um erro proposital.','Exporte o resultado.'],
    practice:[
      {q:'Qual atitude representa uma prática segura no laboratório?',options:['Testar uma mudança por vez e observar o resultado','Usar dados e senhas reais','Importar arquivos desconhecidos sem prévia','Ignorar mensagens de erro'],answer:0,explanation:'Alterações pequenas e verificáveis tornam a prática mais segura e facilitam a depuração.'},
      {q:'Antes de apagar ou restaurar um ambiente, qual ação é recomendada?',options:['Exportar o que precisa ser preservado','Fechar o navegador imediatamente','Compartilhar uma senha real','Desativar todas as validações'],answer:0,explanation:'A exportação preserva evidências e permite continuar o trabalho depois.'}
    ]
  };

  const content={
    cmd:{summary:'Pratique comandos do Prompt de Comando em um sistema de arquivos virtual.',realWorld:'Técnicos usam o CMD para navegar em pastas, automatizar tarefas, diagnosticar rede e coletar informações do Windows.',tutorial:[{title:'Leia o prompt',text:'O caminho exibido antes do cursor indica a pasta atual.'},{title:'Liste arquivos',text:'Use dir para visualizar pastas e arquivos.'},{title:'Crie e acesse',text:'Use mkdir projeto e depois cd projeto.'},{title:'Crie um arquivo',text:'Use type nul > README.txt e confira com dir.'}],guided:['Execute dir.','Crie a pasta projeto-ds.','Entre na pasta criada.','Crie README.txt.','Mostre a árvore com tree /f.'],practice:[{q:'Qual comando cria uma pasta no CMD?',options:['mkdir projeto','touch projeto','new-folder projeto','ls projeto'],answer:0,explanation:'mkdir e md criam diretórios no Prompt de Comando.'},{q:'Qual comando mostra a árvore incluindo arquivos?',options:['tree /f','tree /a','dir /w','path /f'],answer:0,explanation:'O parâmetro /f inclui os arquivos na árvore.'}]},
    powershell:{summary:'Use cmdlets, objetos e pipelines em uma simulação educacional.',realWorld:'Administradores usam PowerShell para automatizar configurações, consultar processos, serviços, usuários e arquivos.',tutorial:[{title:'Cmdlets',text:'Os comandos seguem normalmente o padrão Verbo-Substantivo, como Get-ChildItem.'},{title:'Pipeline',text:'O caractere | envia objetos de um cmdlet para o próximo.'},{title:'Filtros',text:'Where-Object filtra objetos por propriedades.'},{title:'Seleção',text:'Select-Object escolhe propriedades para o resultado.'}],guided:['Execute Get-ChildItem.','Consulte Get-Process.','Use um pipeline com Select-Object.','Crie uma pasta com New-Item.','Consulte o histórico.']},
    bash:{summary:'Explore arquivos, permissões, pipes e scripts em um shell GNU/Linux simulado.',realWorld:'Desenvolvedores e profissionais de cloud usam Bash em servidores, contêineres, CI/CD e automação.',tutorial:[{title:'Localização',text:'pwd mostra o diretório atual e ls lista o conteúdo.'},{title:'Criação',text:'mkdir cria diretórios e touch cria arquivos.'},{title:'Pipes',text:'O caractere | conecta a saída de um comando à entrada de outro.'},{title:'Permissões',text:'chmod altera permissões no sistema simulado.'}],guided:['Execute pwd e ls.','Crie ~/projeto-ds.','Crie app.sh.','Torne o arquivo executável.','Use cat para visualizar o conteúdo.']},
    python:{summary:'Escreva e execute Python real no navegador com Pyodide/WebAssembly.',realWorld:'Python é usado em automação, back-end, dados, inteligência artificial, testes e scripts administrativos.',tutorial:[{title:'Entrada e saída',text:'Use input() para receber texto e print() para exibir resultados.'},{title:'Variáveis',text:'Atribua valores com = e observe os tipos.'},{title:'Condição',text:'Use if e else com indentação consistente.'},{title:'Coleções',text:'Listas permitem armazenar e percorrer vários valores.'}],guided:['Altere o nome da variável de entrada.','Adicione uma nova nota à lista.','Mostre a maior nota.','Crie uma condição para média maior ou igual a 8.','Execute e revise o console.'],practice:[{q:'Qual expressão calcula a quantidade de itens de uma lista chamada notas?',options:['len(notas)','count(notas)','notas.size','length(notas)'],answer:0,explanation:'len() retorna a quantidade de itens de coleções Python.'},{q:'Qual detalhe é estrutural em blocos if no Python?',options:['Indentação','Chaves obrigatórias','Ponto e vírgula obrigatório','Palavra then'],answer:0,explanation:'A indentação delimita os blocos no Python.'}]},
    javascript:{summary:'Execute JavaScript em Web Worker com console e interrupção de loops.',realWorld:'JavaScript controla interfaces web, servidores Node.js, automações e aplicações multiplataforma.',tutorial:[{title:'Variáveis',text:'Use const para referências que não serão reatribuídas e let para valores mutáveis.'},{title:'Coleções',text:'Arrays organizam conjuntos de valores.'},{title:'Laços',text:'for...of percorre os itens de um array.'},{title:'Funções',text:'Funções organizam comportamento reutilizável.'}],guided:['Crie um array com três tecnologias.','Percorra o array.','Crie uma função de saudação.','Leia uma entrada simulada.','Trate um valor vazio.']},
    web:{summary:'Edite HTML, CSS e JavaScript e veja o resultado em iframe sandboxado.',realWorld:'Front-end combina estrutura, apresentação e comportamento para construir páginas e aplicações acessíveis.',tutorial:[{title:'HTML',text:'Estruture conteúdo com elementos semânticos.'},{title:'CSS',text:'Aplique layout, tipografia, cores e responsividade.'},{title:'JavaScript',text:'Associe eventos e atualize a interface.'},{title:'DevTools mental',text:'Leia o console e corrija o primeiro erro antes de avançar.'}],guided:['Mude o título no HTML.','Crie uma classe nova no CSS.','Associe um evento de clique.','Teste no modo celular.','Provoque e depois corrija um erro no console.']},
    sql:{summary:'Execute SQLite real em Web Worker, crie tabelas e consulte dados.',realWorld:'SQL é usado para armazenar, consultar, integrar e analisar dados em sistemas administrativos e aplicações.',tutorial:[{title:'Estrutura',text:'CREATE TABLE define colunas, tipos e restrições.'},{title:'Dados',text:'INSERT adiciona registros.'},{title:'Consulta',text:'SELECT escolhe colunas e linhas.'},{title:'Filtro e ordenação',text:'WHERE filtra e ORDER BY ordena os resultados.'}],guided:['Crie uma tabela produtos.','Insira pelo menos três registros.','Consulte todos os produtos.','Filtre por preço.','Calcule média e total com funções de agregação.'],practice:[{q:'Qual cláusula filtra linhas antes da agregação?',options:['WHERE','HAVING','ORDER BY','GROUP BY'],answer:0,explanation:'WHERE filtra linhas; HAVING normalmente filtra grupos após GROUP BY.'},{q:'Qual restrição identifica unicamente um registro?',options:['PRIMARY KEY','DEFAULT','CHECK','INDEX sem unicidade'],answer:0,explanation:'PRIMARY KEY garante a identificação única do registro.'}]},
    network:{summary:'Configure uma topologia e observe IP, gateway, DNS, latência e falhas.',realWorld:'Profissionais de redes usam essas informações para conectar equipamentos e localizar falhas de comunicação.',tutorial:[{title:'Endereço',text:'IP identifica uma interface dentro de uma rede.'},{title:'Máscara',text:'A máscara define a parte de rede e a parte de host.'},{title:'Gateway',text:'O gateway encaminha tráfego para outras redes.'},{title:'DNS',text:'DNS traduz nomes em endereços.'}],guided:['Configure dois hosts na mesma sub-rede.','Teste conectividade local.','Defina um gateway.','Simule falha de DNS.','Compare latência e perda.']},
    'virtual-machine':{summary:'Configure hardware, firmware, disco e instalação de um sistema operacional simulado.',realWorld:'Máquinas virtuais são usadas para testes, servidores, laboratórios, compatibilidade e isolamento de ambientes.',tutorial:[{title:'Hardware virtual',text:'RAM, CPU, disco e firmware precisam atender aos requisitos do sistema.'},{title:'Boot',text:'O firmware procura um dispositivo inicializável.'},{title:'Partições',text:'O instalador organiza o disco antes de copiar arquivos.'},{title:'Configuração inicial',text:'Idioma, região, usuário e rede concluem o ambiente.'}],guided:['Selecione um perfil de sistema.','Valide o hardware.','Abra o firmware.','Inicie pela mídia de instalação.','Conclua idioma, disco e usuário sem usar dados reais.']},
    hardware:{summary:'Monte um computador, conecte cabos e valide compatibilidade, energia e refrigeração.',realWorld:'Técnicos verificam socket, memória, fonte, refrigeração e conexões antes do primeiro boot.',tutorial:[{title:'Compatibilidade',text:'Processador e placa-mãe precisam usar o mesmo socket.'},{title:'Memória',text:'A geração da RAM deve ser compatível com a placa.'},{title:'Energia',text:'A fonte deve alimentar a placa, CPU e GPU com margem.'},{title:'POST',text:'O POST identifica falhas de montagem antes do sistema iniciar.'}],guided:['Escolha placa e processador compatíveis.','Selecione memória correta.','Conecte ATX e EPS.','Dimensione a fonte.','Execute o POST e corrija qualquer falha.']},
    graphics:{summary:'Manipule RGBA, contraste, transparência e pixels.',realWorld:'Designers e desenvolvedores usam cores, alfa e pixels em interfaces, imagens, jogos e acessibilidade.',tutorial:[{title:'RGBA',text:'RGB representa cor; alfa controla a opacidade de 0 a 1.'},{title:'Transparência',text:'O fundo quadriculado ajuda a visualizar áreas transparentes.'},{title:'Contraste',text:'A relação de contraste influencia a leitura.'},{title:'Pixel art',text:'Cada célula representa um pixel com coordenadas X e Y.'}],guided:['Escolha uma cor.','Reduza o alfa e compare os fundos.','Copie o código CSS rgba().','Pinte uma forma.','Use a borracha, desfaça e exporte PNG.']},
    'block-programming':{summary:'Organize blocos seguros e gere pseudocódigo e JavaScript.',realWorld:'Programação visual ajuda a compreender fluxo, condições, repetição e decomposição antes de escrever sintaxe completa.',tutorial:[{title:'Sequência',text:'A ordem dos blocos altera o comportamento.'},{title:'Entrada e saída',text:'Entrada recebe dados; saída apresenta resultados.'},{title:'Decisão',text:'Condições selecionam caminhos.'},{title:'Repetição',text:'Laços executam um bloco várias vezes.'}],guided:['Comece com Início.','Adicione entrada e saída.','Inclua uma repetição.','Reorganize por teclado ou arraste.','Execute e compare o pseudocódigo.']},
    'data-tools':{summary:'Converta bases, Unicode, Base64 e hashes localmente.',realWorld:'Codificações aparecem em redes, arquivos, URLs, APIs, segurança e armazenamento.',tutorial:[{title:'Bases numéricas',text:'Binário usa base 2; hexadecimal usa base 16.'},{title:'Unicode',text:'Unicode associa códigos a caracteres.'},{title:'Base64',text:'Base64 codifica bytes como texto, mas não é criptografia.'},{title:'Hash',text:'Hash resume dados e ajuda a verificar integridade.'}],guided:['Converta decimal para binário.','Converta hexadecimal para decimal.','Codifique uma frase em Base64.','Calcule um hash.','Altere um caractere e compare o resultado.']},
    'git-github':{summary:'Pratique Git e GitHub em um repositório e remoto simulados.',realWorld:'Equipes usam Git para versionar código, trabalhar em branches, revisar mudanças e publicar projetos.',tutorial:[{title:'Repositório',text:'git init cria o repositório local.'},{title:'Stage',text:'git add prepara alterações para o próximo commit.'},{title:'Commit',text:'git commit registra um ponto do histórico.'},{title:'Remoto',text:'push e pull sincronizam com um repositório remoto simulado.'}],guided:['Inicialize um repositório.','Crie README.md.','Adicione e faça commit.','Crie uma branch.','Faça merge e publique no remoto simulado.']},
    cybersecurity:{summary:'Aprenda defesa, sanitização, autenticação, logs e criptografia em cenários fictícios.',realWorld:'Segurança defensiva reduz risco em aplicações, contas, redes e dados.',tutorial:[{title:'Entrada não confiável',text:'Toda entrada deve ser validada e codificada conforme o contexto.'},{title:'Autenticação',text:'Senhas fortes e 2FA reduzem acesso indevido.'},{title:'Logs',text:'Registros ajudam a investigar eventos sem armazenar segredos.'},{title:'Integridade',text:'Hashes e assinaturas ajudam a detectar alterações.'}],guided:['Identifique uma mensagem de phishing.','Sanitize uma entrada fictícia.','Ative 2FA simulado.','Analise logs de um incidente.','Verifique a integridade de um arquivo fictício.']},
    sysadmin:{summary:'Administre usuários, grupos, serviços, rede, VPN e dispositivos fictícios.',realWorld:'Administração de sistemas organiza identidades, permissões, infraestrutura e auditoria.',tutorial:[{title:'Princípio do menor privilégio',text:'Conceda somente as permissões necessárias.'},{title:'Grupos',text:'Permissões por grupo facilitam administração.'},{title:'Serviços',text:'Serviços precisam de estado, dependências e logs.'},{title:'Auditoria',text:'Alterações administrativas devem gerar registro.'}],guided:['Crie um usuário fictício.','Associe-o a um grupo.','Defina permissões mínimas.','Configure uma VPN simulada.','Revise o log de auditoria.']},
    'code-games':{summary:'Jogue primeiro e observe como estado, eventos, loops, colisões e pontuação aparecem no código.',realWorld:'Engines de jogos atualizam o mundo, processam entrada, verificam colisões e renderizam quadros continuamente.',tutorial:[{title:'Jogue sem bloqueio',text:'Escolha um jogo e compreenda os controles antes de abrir o código.'},{title:'Observe o feedback',text:'Tokens e desafios apresentam conceitos de tecnologia.'},{title:'Abra o código',text:'O painel opcional mostra uma simplificação da mecânica ativa.'},{title:'Compare jogos',text:'Perceba como o mesmo loop serve a gêneros diferentes.'}],guided:['Jogue a Cobrinha Tech.','Descubra uma palavra na Forca.','Analise uma tendência.','Colete tokens no Pac-Tech.','Abra o código de duas mecânicas.']},
    'fintech-pix':{summary:'Simule autenticação, antifraude, mensageria, liquidação e comprovante de uma operação Pix fictícia.',realWorld:'Sistemas financeiros conectam aplicativos, participantes, serviços de risco, mensageria e auditoria.',tutorial:[{title:'Autenticação',text:'Confirme identidade com dado fictício.'},{title:'Risco',text:'O sistema avalia valor, dispositivo e padrão.'},{title:'Liquidação',text:'A ordem recebe confirmação e identificador.'},{title:'Comprovante',text:'O registro reúne valor, destino, status e horário.'}],guided:['Simule um Pix de baixo valor.','Tente um valor acima do saldo.','Consulte o caixa eletrônico.','Identifique uma situação de alto risco.','Leia o comprovante.']},
    'blockchain-crypto':{summary:'Construa blocos com SHA-256 real e prova de trabalho reduzida.',realWorld:'Blockchains conectam blocos, hashes, nós e consenso para manter um registro distribuído.',tutorial:[{title:'Transação',text:'Crie dados fictícios para o pool.'},{title:'Hash',text:'Observe como qualquer alteração muda o resumo.'},{title:'Nonce',text:'A mineração busca um valor que atenda à dificuldade.'},{title:'Integridade',text:'Cada bloco referencia o hash anterior.'}],guided:['Adicione uma transação.','Minere um bloco.','Aumente a dificuldade.','Altere um bloco.','Valide a cadeia.']},
    'digital-communication':{summary:'Acompanhe e-mail, DNS, SMTP, TLS, cabeçalhos e criptografia local.',realWorld:'Mensagens passam por clientes, servidores, protocolos e controles de segurança.',tutorial:[{title:'Composição',text:'Use destinatário, assunto e corpo claros.'},{title:'DNS e SMTP',text:'O domínio aponta para o servidor que recebe a mensagem.'},{title:'TLS',text:'O canal protege dados durante o transporte.'},{title:'Criptografia',text:'A cifra transforma texto em dados ilegíveis sem a chave.'}],guided:['Envie um e-mail fictício.','Analise os passos do servidor.','Criptografe uma mensagem local.','Inspecione cabeçalhos.','Compare SMTP, IMAP e POP3.']},
    'display-media':{summary:'Explore FPS, Hertz, subpixels, conectores e áudio.',realWorld:'Jogos, monitores, placas de vídeo, cabos e sistemas de áudio dependem de sinais, taxas e processamento.',tutorial:[{title:'FPS',text:'Quadros produzidos pelo sistema.'},{title:'Hertz',text:'Atualizações possíveis no monitor.'},{title:'RGB',text:'Subpixels combinam luz vermelha, verde e azul.'},{title:'Áudio',text:'Ondas são amostradas, processadas e reproduzidas.'}],guided:['Compare 30 FPS e 60 Hz.','Aumente FPS acima do Hz.','Amplie subpixels.','Compare HDMI e VGA.','Gere uma onda de áudio.']},
    'automation-iot':{summary:'Combine sensores, OCR, regras, atuadores e robótica.',realWorld:'Automação industrial reage a eventos e registra decisões em sistemas de controle.',tutorial:[{title:'Evento',text:'Um sensor detecta uma mudança.'},{title:'Regra',text:'O software verifica condições.'},{title:'Ação',text:'Um atuador executa a resposta.'},{title:'Telemetria',text:'Métricas e logs apoiam manutenção.'}],guided:['Simule a entrada de caminhão.','Bloqueie uma placa não autorizada.','Monte uma regra IoT.','Mova o braço robótico.','Simule superaquecimento.']},
    'artificial-intelligence':{summary:'Visualize redes neurais, treinamento, classificação, tokens e chatbot por regras.',realWorld:'Sistemas de IA transformam dados em representações e estimativas, exigindo avaliação e supervisão.',tutorial:[{title:'Entradas',text:'Dados são transformados em características.'},{title:'Pesos',text:'Conexões ajustam a influência de cada sinal.'},{title:'Treinamento',text:'O modelo reduz erro ao longo das épocas.'},{title:'Tokens',text:'Modelos de linguagem processam unidades de texto.'}],guided:['Treine vinte épocas.','Altere características do classificador.','Tokenize uma frase.','Converse com o chatbot local.','Compare regras com modelo generativo.']},
    'network-operations':{summary:'Pratique rack, RJ45, VLAN, firewall, MikroTik conceitual, CFTV e NVR.',realWorld:'Operações de rede dependem de documentação, segmentação, configuração e monitoramento.',tutorial:[{title:'Camada física',text:'Cabos e conectores precisam de padrão e teste.'},{title:'Switch',text:'VLANs segmentam portas em redes lógicas.'},{title:'Roteador',text:'Regras controlam tráfego entre redes.'},{title:'CFTV',text:'Bitrate e retenção definem o armazenamento.'}],guided:['Monte T568B.','Altere uma porta de VLAN.','Gere uma regra de firewall.','Reconecte uma câmera.','Calcule sete dias de retenção.']},
    'game-engine':{summary:'Jogue uma plataforma, observe um mundo em blocos e monitore desempenho.',realWorld:'Engines unem entrada, física, colisão, câmera, áudio e renderização.',tutorial:[{title:'Loop',text:'Atualiza o estado e desenha quadros.'},{title:'Física',text:'Velocidade e gravidade alteram a posição.'},{title:'Colisão',text:'Limites impedem atravessar plataformas.'},{title:'Profiler',text:'Tempo de quadro mostra custo de processamento.'}],guided:['Jogue a plataforma.','Altere gravidade.','Colete tokens.','Observe a projeção isométrica.','Aumente a carga do profiler.']},

    'tutorial-center':{summary:'Aprenda ferramentas digitais com tutoriais locais, níveis de detalhe e checklists salvos no aparelho.',realWorld:'Estudantes usam esses procedimentos para entregar atividades, organizar arquivos, colaborar e publicar projetos com menos erros.',tutorial:[{title:'Escolha o objetivo',text:'Pesquise Classroom, e-mail, arquivos, código, produtividade, hospedagem ou segurança.'},{title:'Ajuste o nível',text:'Use Objetivo para ações essenciais, Guiado para explicações e Detalhado para exemplos e erros comuns.'},{title:'Confirme cada etapa',text:'Marque o checklist somente depois de realizar ou compreender a ação.'},{title:'Exporte a evidência',text:'Baixe o checklist concluído e use o fluxo do Classroom para anexar a atividade.'}],guided:['Pesquise “Classroom”.','Abra o tutorial de entrega.','Alterne entre Objetivo e Detalhado.','Marque uma etapa concluída.','Exporte o checklist e prepare a entrega.']},
    'tech-explorer':{summary:'Explore linguagens de programação, carreiras, IA, história e aplicações reais com fontes e exemplos.',realWorld:'A pesquisa orientada ajuda estudantes a relacionar linguagens, ferramentas, formação e oportunidades profissionais.',tutorial:[{title:'Explore por interesse',text:'Use busca e filtros para localizar linguagem, área ou tecnologia.'},{title:'Compare linguagens',text:'Observe origem, paradigma, aplicações, sintaxe e documentação.'},{title:'Analise carreiras',text:'Relacione atribuições, habilidades e fontes salariais com a data da pesquisa.'},{title:'Verifique a fonte',text:'Tecnologias e mercados mudam; abra a documentação ou pesquisa indicada.'}],guided:['Pesquise uma linguagem conhecida.','Abra o exemplo e copie o código.','Compare duas linguagens.','Explore uma carreira e uma fonte de vagas.','Registre um desafio de pesquisa.']},
    'solar-system':{summary:'Simule órbitas, ciclos e escalas de tempo do Sistema Solar em Canvas 2D ou perspectiva.',realWorld:'Modelos visuais são usados no ensino e na ciência para investigar movimentos que seriam lentos, grandes ou difíceis de observar diretamente.',tutorial:[{title:'Escolha a visualização',text:'Alterne entre vista plana e perspectiva para comparar representação e profundidade.'},{title:'Controle o tempo',text:'Use dias, meses e anos por segundo para observar ciclos em velocidades diferentes.'},{title:'Navegue',text:'Aplique zoom e arraste a cena sem alterar os dados orbitais.'},{title:'Analise um planeta',text:'Selecione um planeta e leia período orbital, distância e fatos educacionais.'}],guided:['Pause a simulação.','Selecione a Terra.','Avance 30 dias.','Compare Terra e Marte.','Ative órbitas, nomes e perspectiva.']},
    'world-tools':{summary:'Compare fusos horários, use despertador, contagem regressiva, cronômetro e conversores locais.',realWorld:'Fusos, alarmes e conversões apoiam viagens, trabalho remoto, logística, programação, ciência e organização de estudos.',tutorial:[{title:'Relógios mundiais',text:'Adicione cidades e compare data e hora com Intl.DateTimeFormat.'},{title:'Fusos do Brasil',text:'Observe Fernando de Noronha, Brasília, Manaus e Rio Branco.'},{title:'Gerencie o tempo',text:'Use despertador, contagem regressiva e cronômetro com voltas.'},{title:'Converta valores',text:'Teste temperatura, unidades e bases numéricas.'}],guided:['Adicione Tóquio e Londres.','Compare Brasília e Manaus.','Programe uma contagem de cinco minutos.','Registre uma volta no cronômetro.','Converta 25 °C para Fahrenheit.']},
    'school-randomizer':{summary:'Organize sorteios de nomes, números, equipes, turmas e salas com resultados reproduzíveis.',realWorld:'Professores e equipes usam sorteios transparentes para distribuir tarefas, formar grupos e organizar espaços.',tutorial:[{title:'Prepare a lista',text:'Use um item por linha e retire ausentes antes do sorteio.'},{title:'Defina uma semente',text:'A mesma semente permite reproduzir o resultado para conferência.'},{title:'Aplique restrições',text:'Na formação de equipes, registre pessoas que devem ficar juntas ou separadas.'},{title:'Exporte o resultado',text:'Salve o histórico antes de abrir o Classroom.'}],guided:['Cadastre pelo menos seis nomes.','Faça um sorteio sem repetição.','Forme três equipes.','Sorteie uma turma e uma sala compatível.','Exporte o histórico.']},
    biomonitor:{summary:'Observe sinais fisiológicos matematicamente simulados em cenários de repouso, esforço e recuperação.',realWorld:'Painéis de monitoramento exibem séries temporais e alarmes, mas exigem sensores e equipamentos certificados em situações reais.',tutorial:[{title:'Escolha um cenário',text:'Repouso, caminhada e exercício alteram gradualmente os valores simulados.'},{title:'Configure limites',text:'Defina faixas de alerta e observe a mudança de estado.'},{title:'Compare leituras',text:'Registre repouso e exercício para analisar a diferença.'},{title:'Interprete com cuidado',text:'Os dados são fictícios e não possuem finalidade médica.'}],guided:['Observe o repouso por alguns segundos.','Registre a leitura.','Ative exercício.','Registre a nova leitura.','Valide a comparação e exporte.']},
    'thermal-panel':{summary:'Controle temperatura, alarmes, unidades e efeitos gráficos extremos em um painel de sensores.',realWorld:'Automação industrial e climatização usam sensores, limites e histerese para controlar equipamentos com estabilidade.',tutorial:[{title:'Altere a temperatura',text:'Use potenciômetro, entrada numérica ou valores predefinidos.'},{title:'Observe o estado',text:'Cores e efeitos representam frio, estabilidade e superaquecimento.'},{title:'Configure alarmes',text:'Defina limites mínimo e máximo e uma histerese.'},{title:'Teste os extremos',text:'Acione os dois alarmes e exporte a telemetria.'}],guided:['Selecione qualidade automática.','Leve a temperatura abaixo do limite frio.','Retorne à faixa estável.','Ultrapasse o limite quente.','Valide e exporte a atividade.']},
    'audio-lab':{summary:'Visualize ondas, espectro e equalização com áudio opcional ativado somente após clique.',realWorld:'Áudio digital combina frequência, amplitude, filtros e análise espectral em comunicação, música e multimídia.',tutorial:[{title:'Comece no modo visual',text:'Observe forma de onda e espectro sem emitir som.'},{title:'Ajuste a frequência',text:'Compare graves, médias e agudas.'},{title:'Explore formas',text:'Alterne entre onda senoidal, quadrada, triangular e dente de serra.'},{title:'Equalize com segurança',text:'Ajuste bandas e mantenha volume baixo.'}],guided:['Mantenha Somente visual marcado.','Compare 80 Hz e 4.000 Hz.','Altere a forma da onda.','Ajuste duas bandas do equalizador.','Classifique uma frequência e exporte.']},
    electronics:{summary:'Use calculadora, circuito de LED, Lei de Ohm e motor por PWM.',realWorld:'Eletrônica conecta software, sensores, energia, atuadores e robótica.',tutorial:[{title:'Tensão',text:'Diferença de potencial que impulsiona corrente.'},{title:'Resistência',text:'Limita a passagem de corrente.'},{title:'Polaridade',text:'Alguns componentes possuem sentido correto.'},{title:'PWM',text:'Controla energia média por pulsos.'}],guided:['Ajuste tensão e resistência.','Inverta a polaridade.','Calcule uma expressão.','Controle o motor.','Compare corrente e potência.']}
  };

  window.LABDS.LEARNING_CONTENT={common,content};
})();
