const clamp=(value,min,max)=>Math.max(min,Math.min(max,Number(value)||0));
const seeded=(seed,index)=>{const x=Math.sin((seed+1)*(index+13)*12.9898)*43758.5453;return x-Math.floor(x);};
const FLOW={planner:'#66e6ff',capture:'#ffca70',calibration:'#7af0bd',stack:'#a98cff',process:'#ff83b0',notebook:'#72ddff'};

export class AstrophotographyPipelineRenderer{
  constructor(canvas,settingsStore,{onSelect=()=>{},onDiagnostics=()=>{}}={}){
    this.canvas=canvas;this.ctx=canvas.getContext('2d');this.settingsStore=settingsStore;this.onSelect=onSelect;this.onDiagnostics=onDiagnostics;
    this.state=null;this.mode='planner';this.running=false;this.raf=0;this.width=0;this.height=0;this.dpr=1;this.yaw=-.18;this.pitch=.08;this.zoom=1;this.drag=null;this.frames=0;this.lastFps=performance.now();this.fps=0;
    this.onResize=()=>this.resize();this.onPointerDown=e=>this.pointerDown(e);this.onPointerMove=e=>this.pointerMove(e);this.onPointerUp=()=>this.drag=null;this.onWheel=e=>{e.preventDefault();this.zoom=clamp(this.zoom-e.deltaY*.001,0.72,1.75);};this.onClick=e=>this.click(e);
  }
  setState(state){this.state=state;this.mode=state.mode||this.mode;}
  setMode(mode){this.mode=mode;}
  start(){if(this.running)return;this.running=true;addEventListener('resize',this.onResize);this.canvas.addEventListener('pointerdown',this.onPointerDown);this.canvas.addEventListener('pointermove',this.onPointerMove);this.canvas.addEventListener('pointerup',this.onPointerUp);this.canvas.addEventListener('pointercancel',this.onPointerUp);this.canvas.addEventListener('wheel',this.onWheel,{passive:false});this.canvas.addEventListener('click',this.onClick);this.resize();this.loop(performance.now());}
  resize(){const rect=this.canvas.getBoundingClientRect();this.dpr=Math.min(devicePixelRatio||1,this.settingsStore.getProfile().id==='performance'?1:1.6);this.width=Math.max(1,Math.floor(rect.width));this.height=Math.max(1,Math.floor(rect.height));this.canvas.width=Math.floor(this.width*this.dpr);this.canvas.height=Math.floor(this.height*this.dpr);this.ctx.setTransform(this.dpr,0,0,this.dpr,0,0);this.onDiagnostics({renderer:'Canvas 2D procedural',fps:this.fps,resolution:`${this.canvas.width}×${this.canvas.height}`});}
  loop(now){if(!this.running)return;this.frames++;if(now-this.lastFps>=1000){this.fps=Math.round(this.frames*1000/(now-this.lastFps));this.frames=0;this.lastFps=now;this.onDiagnostics({renderer:'Canvas 2D procedural',fps:this.fps,resolution:`${this.canvas.width}×${this.canvas.height}`});}this.draw(now/1000);this.raf=requestAnimationFrame(t=>this.loop(t));}
  pointerDown(e){this.drag={x:e.clientX,y:e.clientY,yaw:this.yaw,pitch:this.pitch};this.canvas.setPointerCapture?.(e.pointerId);}
  pointerMove(e){if(!this.drag)return;this.yaw=this.drag.yaw+(e.clientX-this.drag.x)*.004;this.pitch=clamp(this.drag.pitch+(e.clientY-this.drag.y)*.003,-.42,.42);}
  click(e){const rect=this.canvas.getBoundingClientRect(),x=e.clientX-rect.left,y=e.clientY-rect.top;if(x>this.width*.5&&y>this.height*.2&&y<this.height*.78)this.onSelect({kind:'preview'});else if(y>this.height*.78)this.onSelect({kind:'frames'});else this.onSelect({kind:'rig'});}
  draw(time){const c=this.ctx;if(!c||!this.state)return;c.clearRect(0,0,this.width,this.height);this.drawSky(c,time);this.drawRig(c,time);this.drawSensor(c,time);this.drawBeforeAfter(c,time);this.drawHistogram(c);this.drawFrameStrip(c,time);this.drawTelemetry(c);}
  drawSky(c,time){const g=c.createRadialGradient(this.width*.72,this.height*.18,0,this.width*.55,this.height*.42,Math.max(this.width,this.height));g.addColorStop(0,'#15304f');g.addColorStop(.38,'#071425');g.addColorStop(1,'#02060d');c.fillStyle=g;c.fillRect(0,0,this.width,this.height);const reduced=this.settingsStore.get().reducedMotion,count=this.settingsStore.getProfile().id==='performance'?70:150;for(let i=0;i<count;i++){const x=seeded(11,i)*this.width,y=seeded(23,i)*this.height,r=.3+seeded(37,i)*1.35,a=reduced?.72:.48+.35*Math.sin(time*(.45+seeded(41,i))+i);c.globalAlpha=clamp(a,0,1);c.fillStyle=i%19===0?'#85caff':'#eff9ff';c.beginPath();c.arc(x,y,r,0,Math.PI*2);c.fill();}c.globalAlpha=1;c.fillStyle='rgba(75,179,211,.055)';for(let i=0;i<7;i++){const y=this.height*(.13+i*.105);c.fillRect(0,y,this.width,1);}}
  project(x,y,z,ox,oy,scale){const cy=Math.cos(this.yaw),sy=Math.sin(this.yaw),cp=Math.cos(this.pitch),sp=Math.sin(this.pitch),rx=x*cy-z*sy,rz=x*sy+z*cy,ry=y*cp-rz*sp,rz2=y*sp+rz*cp,d=1/(1+rz2*.12);return{x:ox+rx*scale*d,y:oy-ry*scale*d,s:d};}
  drawRig(c,time){const s=this.state,cam=s.camera,opt=s.optical,ox=this.width*.19,oy=this.height*.69,scale=Math.min(this.width,this.height)*.13*this.zoom,p=(x,y,z)=>this.project(x,y,z,ox,oy,scale);c.save();c.lineCap='round';c.lineJoin='round';const base=p(0,0,0);c.strokeStyle='rgba(112,217,238,.62)';c.lineWidth=4;for(const leg of [[-1,-1,.8],[1,-1,.8],[0,-1,-1]]){const q=p(...leg);c.beginPath();c.moveTo(base.x,base.y);c.lineTo(q.x,q.y);c.stroke();}const mount=p(0,.42,0);c.fillStyle='#102a3b';c.beginPath();c.arc(mount.x,mount.y,12,0,Math.PI*2);c.fill();c.strokeStyle=cam.color;c.lineWidth=2;c.stroke();const a=p(-.72,.78,0),b=p(.72,1.05,0);c.strokeStyle='#233d4b';c.lineWidth=25;c.beginPath();c.moveTo(a.x,a.y);c.lineTo(b.x,b.y);c.stroke();c.strokeStyle=cam.color;c.lineWidth=3;c.stroke();const camera=p(-.88,.73,.02);c.fillStyle='#0a1825';c.fillRect(camera.x-18,camera.y-13,36,26);c.strokeStyle=cam.color;c.strokeRect(camera.x-18,camera.y-13,36,26);c.fillStyle=cam.color;c.fillRect(camera.x-22,camera.y-5,5,10);if(cam.cooled){c.strokeStyle='#6fe8ff';c.beginPath();for(let i=0;i<3;i++){c.moveTo(camera.x-12+i*9,camera.y+16);c.lineTo(camera.x-8+i*9,camera.y+23+Math.sin(time*2+i)*2);}c.stroke();}c.fillStyle='#dff8ff';c.font='800 10px ui-monospace';c.fillText(opt.name,Math.max(12,ox-scale*1.5),oy+scale*1.08);c.fillStyle=cam.color;c.fillText(cam.name,Math.max(12,ox-scale*1.5),oy+scale*1.25);c.restore();}
  drawSensor(c,time){const s=this.state,cam=s.camera,x=this.width*.39,y=this.height*.18,w=Math.min(210,this.width*.22),h=Math.min(145,this.height*.22);c.save();c.fillStyle='rgba(3,12,24,.84)';c.strokeStyle='rgba(111,222,244,.18)';c.lineWidth=1;c.beginPath();c.roundRect(x,y,w,h,15);c.fill();c.stroke();c.fillStyle='#071c2c';c.fillRect(x+18,y+32,w-36,h-54);const cols=16,rows=10,active=s.capture?Math.round((Math.sin(time*2)+1)*.5*cols*rows):0;for(let row=0;row<rows;row++)for(let col=0;col<cols;col++){const index=row*cols+col,px=x+20+col*(w-40)/cols,py=y+34+row*(h-58)/rows;c.fillStyle=index<active?cam.color:`rgba(85,147,169,${.12+seeded(9,index)*.16})`;c.fillRect(px,py,(w-40)/cols-1,(h-58)/rows-1);}c.fillStyle='#8eb1c0';c.font='700 9px ui-monospace';c.fillText(`${cam.sensor} · ${cam.megapixels} MP · ${cam.bitDepth} bit`,x+16,y+18);c.fillText(`PIXEL ${cam.pixelSizeUm} µm · ${cam.maxFps} FPS`,x+16,y+h-10);c.restore();}
  previewRect(side){const mobile=this.width<760,w=mobile?this.width*.72:this.width*.27,h=mobile?this.height*.23:this.height*.39,x=mobile?this.width*.14:(side==='before'?this.width*.46:this.width*.73),y=mobile?(side==='before'?this.height*.31:this.height*.56):this.height*.25;return{x,y,w:mobile?w:w-.02*this.width,h:mobile?h:h};}
  drawBeforeAfter(c,time){const before=this.previewRect('before'),after=this.previewRect('after');this.drawImagePanel(c,before,time,false);this.drawImagePanel(c,after,time,true);}
  drawImagePanel(c,r,time,processed){const s=this.state,target=s.target,available=processed?s.processing:s.capture;c.save();c.fillStyle='rgba(1,5,11,.9)';c.strokeStyle=processed?'rgba(119,240,189,.4)':'rgba(255,202,112,.32)';c.lineWidth=2;c.beginPath();c.roundRect(r.x,r.y,r.w,r.h,16);c.fill();c.stroke();c.beginPath();c.roundRect(r.x+8,r.y+30,r.w-16,r.h-40,11);c.clip();c.fillStyle='#01050b';c.fillRect(r.x,r.y,r.w,r.h);const seed=target.id.length*33+(processed?73:17),stars=target.kind==='deep-sky'?100:38;for(let i=0;i<stars;i++){const x=r.x+8+seeded(seed,i)*(r.w-16),y=r.y+30+seeded(seed+2,i)*(r.h-40),radius=.3+seeded(seed+4,i)*(processed?1.5:1.1),alpha=processed?.45+seeded(seed+6,i)*.55:.2+seeded(seed+6,i)*.45;c.globalAlpha=available?alpha:.15;c.fillStyle='#edf9ff';c.beginPath();c.arc(x,y,radius,0,Math.PI*2);c.fill();}c.globalAlpha=1;this.drawTarget(c,target,r,processed,time);if(!processed){const noise=available?clamp((s.capture?.meanQuality?100-s.capture.meanQuality:70)/100,.08,.75):.65;c.globalAlpha=noise*.42;for(let i=0;i<900;i++){const x=r.x+seeded(seed+9,i)*r.w,y=r.y+30+seeded(seed+11,i)*(r.h-35),v=Math.round(90+seeded(seed+13,i)*120);c.fillStyle=`rgb(${v},${v},${v})`;c.fillRect(x,y,1,1);}c.globalAlpha=1;}c.restore();c.fillStyle=processed?'#78efbd':'#ffca70';c.font='900 9px ui-monospace';c.fillText(processed?'DEPOIS · EMPILHADO/PROCESSADO':'ANTES · QUADRO BRUTO',r.x+13,r.y+19);if(!available){c.fillStyle='#7896a5';c.font='700 10px ui-monospace';c.fillText(processed?'Processe para revelar o resultado':'Capture uma sequência',r.x+18,r.y+r.h-16);}}
  drawTarget(c,t,r,processed,time){const cx=r.x+r.w*.5,cy=r.y+r.h*.56,scale=Math.min(r.w,r.h)*(processed?.33:.27);if(t.id==='moon'){const g=c.createRadialGradient(cx-scale*.2,cy-scale*.25,2,cx,cy,scale);g.addColorStop(0,'#fffbea');g.addColorStop(1,processed?'#88929a':'#666d73');c.fillStyle=g;c.beginPath();c.arc(cx,cy,scale,0,Math.PI*2);c.fill();c.fillStyle='rgba(30,35,40,.25)';for(let i=0;i<18;i++){const a=seeded(44,i)*Math.PI*2,rr=Math.sqrt(seeded(45,i))*scale*.8;c.beginPath();c.arc(cx+Math.cos(a)*rr,cy+Math.sin(a)*rr,2+seeded(46,i)*scale*.1,0,Math.PI*2);c.fill();}}else if(['jupiter','saturn','mars'].includes(t.id)){const radius=scale*(t.id==='mars'?.4:.55);if(t.id==='saturn'){c.strokeStyle=processed?'#e5cf95':'#987f55';c.lineWidth=Math.max(2,radius*.24);c.beginPath();c.ellipse(cx,cy,radius*1.9,radius*.55,-.12,0,Math.PI*2);c.stroke();}c.fillStyle=t.color;c.beginPath();c.arc(cx,cy,radius,0,Math.PI*2);c.fill();if(t.id==='jupiter'){c.save();c.beginPath();c.arc(cx,cy,radius,0,Math.PI*2);c.clip();for(let i=-3;i<=3;i++){c.fillStyle=i%2?'rgba(105,58,35,.42)':'rgba(255,240,203,.35)';c.fillRect(cx-radius,cy+i*radius*.22,radius*2,radius*.11);}c.restore();}}else if(t.kind==='deep-sky'){const palette=this.state.palette,colors=palette?.colors||['#82ddcf','#b298ff','#e8f9ff'],g=c.createRadialGradient(cx,cy,2,cx,cy,scale*1.55);g.addColorStop(0,processed?colors[0]:'#d8f5eb');g.addColorStop(.24,processed?`${colors[1]}aa`:'rgba(90,166,164,.46)');g.addColorStop(1,'rgba(43,65,120,0)');c.fillStyle=g;c.beginPath();if(t.id==='andromeda')c.ellipse(cx,cy,scale*1.65,scale*.38,-.32,0,Math.PI*2);else c.ellipse(cx,cy,scale*1.25,scale*.65,.24,0,Math.PI*2);c.fill();}if(!this.settingsStore.get().reducedMotion&&(this.state.capture||this.state.processing)){c.globalAlpha=.18+.1*Math.sin(time*2);c.strokeStyle=FLOW[this.mode]||'#66e6ff';c.lineWidth=2;c.beginPath();c.arc(cx,cy,scale*1.2+Math.sin(time)*5,0,Math.PI*2);c.stroke();c.globalAlpha=1;}}
  drawHistogram(c){const bins=this.state.processing?.histogram||this.state.stack?.histogram||Array.from({length:32},(_,i)=>Math.exp(-Math.pow((i/31-.24)/.17,2))*78),mobile=this.width<760,x=mobile?this.width*.09:this.width*.47,y=mobile?this.height*.81:this.height*.7,w=mobile?this.width*.82:this.width*.5,h=mobile?this.height*.12:this.height*.16;c.save();c.fillStyle='rgba(3,12,24,.82)';c.strokeStyle='rgba(105,218,242,.16)';c.beginPath();c.roundRect(x,y,w,h,13);c.fill();c.stroke();const barW=(w-24)/bins.length;bins.forEach((value,i)=>{const bh=(h-30)*value/100,c1=this.state.palette?.colors?.[i%this.state.palette.colors.length]||'#69e5ff';c.fillStyle=c1;c.globalAlpha=.65;c.fillRect(x+12+i*barW,y+h-12-bh,Math.max(1,barW-1),bh);});c.globalAlpha=1;c.fillStyle='#8eb0be';c.font='800 8px ui-monospace';c.fillText('HISTOGRAMA · SOMBRAS → MEIOS-TONS → ALTAS LUZES',x+12,y+15);c.restore();}
  drawFrameStrip(c,time){if(this.width<760)return;const capture=this.state.capture,x=this.width*.4,y=this.height*.08,w=this.width*.58,h=70;c.fillStyle='rgba(3,12,24,.68)';c.beginPath();c.roundRect(x,y,w,h,12);c.fill();c.fillStyle='#809eab';c.font='800 8px ui-monospace';c.fillText('QUADROS DA SESSÃO',x+10,y+14);const frames=capture?.sampledFrames||[];for(let i=0;i<18;i++){const frame=frames[Math.floor(i/18*frames.length)],q=frame?.quality||15,fx=x+10+i*(w-20)/18,fw=(w-20)/18-3;c.fillStyle=`rgba(${Math.round(40+q*1.3)},${Math.round(80+q*1.4)},${Math.round(100+q*1.2)},.78)`;c.fillRect(fx,y+23,fw,34);c.fillStyle=q>=70?'#72efbd':q>=45?'#ffca70':'#ff758f';c.fillRect(fx,y+60,fw,3);}if(!capture){c.fillStyle='#617e8e';c.fillText('Aguardando captura',x+10,y+48);}}
  drawTelemetry(c){const s=this.state,m=s.metrics,p=s.progress,x=14,y=14,w=Math.min(390,this.width*.38),h=88;c.fillStyle='rgba(3,12,24,.78)';c.beginPath();c.roundRect(x,y,w,h,13);c.fill();c.strokeStyle='rgba(105,219,244,.15)';c.stroke();c.fillStyle=FLOW[this.mode]||'#66e6ff';c.font='900 9px ui-monospace';c.fillText(`ASTRO C4.2 · ${String(this.mode).toUpperCase()} · ${p.percent}%`,x+12,y+17);c.fillStyle='#dff8ff';c.font='800 10px ui-monospace';c.fillText(`${s.target.name} · ${s.camera.name}`,x+12,y+37);c.fillStyle='#83a4b3';c.font='700 8px ui-monospace';c.fillText(`FOV ${m.fovWidth}° × ${m.fovHeight}° · ${m.pixelScale}"/px`,x+12,y+56);c.fillText(`${s.requestedFrames} quadros · ${m.durationMinutes} min · ${m.dataGb} GB`,x+12,y+74);}
  destroy(){this.running=false;cancelAnimationFrame(this.raf);removeEventListener('resize',this.onResize);this.canvas.removeEventListener('pointerdown',this.onPointerDown);this.canvas.removeEventListener('pointermove',this.onPointerMove);this.canvas.removeEventListener('pointerup',this.onPointerUp);this.canvas.removeEventListener('pointercancel',this.onPointerUp);this.canvas.removeEventListener('wheel',this.onWheel);this.canvas.removeEventListener('click',this.onClick);this.ctx?.clearRect(0,0,this.width,this.height);}
}
