export class CampaignCinematicRenderer{
 constructor(canvas,settingsStore,{onDiagnostics=()=>{}}={}){this.canvas=canvas;this.settingsStore=settingsStore;this.onDiagnostics=onDiagnostics;this.ctx=null;this.raf=0;this.progress=0;this.theme='lunar-expedition';this.event=null;this.reducedMotion=settingsStore.get().reducedMotion;this.resize=()=>this.handleResize();}
 start(){this.destroy(false);this.ctx=this.canvas.getContext('2d');addEventListener('resize',this.resize);this.handleResize();const tick=now=>{if(!this.reducedMotion)this.progress=(this.progress+.0005)%1;this.draw(now);this.raf=requestAnimationFrame(tick)};this.raf=requestAnimationFrame(tick);this.onDiagnostics({state:'campaign-canvas'});}
 setCampaign(id){this.theme=id;} setProgress(v){this.progress=Math.max(0,Math.min(1,Number(v)||0));} setEvent(event){this.event=event;}
 draw(now){const c=this.ctx;if(!c)return;const w=this.canvas.width,h=this.canvas.height;const palette=this.theme==='mars-expedition'?['#2b0b06','#8f3517','#ff9b54']:this.theme==='orbital-operations'?['#020817','#0a315d','#77ddff']:['#02040b','#19223f','#d9e6ff'];const g=c.createRadialGradient(w*.58,h*.42,0,w*.58,h*.42,w*.75);g.addColorStop(0,palette[1]);g.addColorStop(.45,palette[0]);g.addColorStop(1,'#010207');c.fillStyle=g;c.fillRect(0,0,w,h);for(let i=0;i<120;i++){const x=(i*89+(now*.002))%w,y=(i*53)%h;c.fillStyle=`rgba(255,255,255,${.2+(i%5)*.12})`;c.fillRect(x,y,i%9===0?2:1,i%9===0?2:1);}const cx=w*(.2+.6*this.progress),cy=h*.55-Math.sin(this.progress*Math.PI)*h*.28;c.strokeStyle='rgba(106,219,255,.25)';c.lineWidth=3;c.beginPath();c.moveTo(w*.12,h*.62);c.quadraticCurveTo(w*.5,h*.08,w*.88,h*.58);c.stroke();c.fillStyle=palette[2];c.shadowColor=palette[2];c.shadowBlur=24;c.beginPath();c.arc(cx,cy,Math.max(6,w/130),0,Math.PI*2);c.fill();c.shadowBlur=0;if(this.event&&!this.event.resolved){c.fillStyle='rgba(180,24,16,.82)';c.fillRect(w*.5-180,28,360,44);c.fillStyle='#fff';c.textAlign='center';c.font='700 15px sans-serif';c.fillText(`ALERTA · ${String(this.event.id).replaceAll('-',' ').toUpperCase()}`,w*.5,56);c.textAlign='left';}c.fillStyle='rgba(3,9,20,.74)';c.fillRect(22,h-76,330,48);c.fillStyle='#d9f7ff';c.font='600 14px sans-serif';c.fillText(`${this.theme.replaceAll('-',' ').toUpperCase()} · ${Math.round(this.progress*100)}%`,38,h-46);}
 handleResize(){const p=this.settingsStore.getProfile(),scale=Math.min(2,devicePixelRatio||1)*p.renderScale;this.canvas.width=Math.max(2,Math.round(this.canvas.clientWidth*scale));this.canvas.height=Math.max(2,Math.round(this.canvas.clientHeight*scale));}
 resize(){this.handleResize();}
 requestFullscreen(){return this.canvas.parentElement?.requestFullscreen?.();}destroy(notify=true){cancelAnimationFrame(this.raf);removeEventListener('resize',this.resize);this.ctx=null;if(notify)this.onDiagnostics({state:'destroyed'});}
}
