const VS=`#version 300 es
precision highp float;out vec2 vUv;void main(){vec2 p=vec2((gl_VertexID<<1)&2,gl_VertexID&2);vUv=p;gl_Position=vec4(p*2.-1.,0.,1.);}`;
const FS=`#version 300 es
precision highp float;in vec2 vUv;out vec4 outColor;
uniform vec2 u_resolution;uniform float u_time,u_yaw,u_pitch,u_zoom,u_motion,u_quality,u_warp,u_energy;uniform int u_mode,u_camera_mode;uniform vec3 u_position;
#define PI 3.14159265359
float hash11(float p){p=fract(p*.1031);p*=p+33.33;p*=p+p;return fract(p);}float hash31(vec3 p){p=fract(p*.1031);p+=dot(p,p.yzx+33.33);return fract((p.x+p.y)*p.z);}float noise(vec3 p){vec3 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(mix(hash31(i),hash31(i+vec3(1,0,0)),f.x),mix(hash31(i+vec3(0,1,0)),hash31(i+vec3(1,1,0)),f.x),f.y),mix(mix(hash31(i+vec3(0,0,1)),hash31(i+vec3(1,0,1)),f.x),mix(hash31(i+vec3(0,1,1)),hash31(i+vec3(1,1,1)),f.x),f.y),f.z);}float fbm(vec3 p){float s=0.,a=.52;for(int i=0;i<6;i++){s+=a*noise(p);p=p*2.02+vec3(1.7,-.8,.6);a*=.5;}return s;}
mat2 rot(float a){float c=cos(a),s=sin(a);return mat2(c,-s,s,c);}float ring(vec2 p,float r,float w){return exp(-abs(length(p)-r)*w);}vec3 palette(float t,vec3 a,vec3 b,vec3 c,vec3 d){return a+b*cos(6.28318*(c*t+d));}
vec3 starfield(vec3 rd,float t){vec3 col=vec3(0);for(int layer=0;layer<5;layer++){float z=80.+float(layer)*57.;vec3 q=rd*z+u_position*.04;vec3 id=floor(q);float h=hash31(id);float s=pow(max(0.,1.-length(fract(q)-.5)*2.),14.);float tw=.55+.45*sin(t*(.4+h*2.)+h*45.);col+=mix(vec3(.45,.68,1.),vec3(1.,.86,.66),h)*s*step(.991-float(layer)*.001,h)*tw;}return col;}
void main(){vec2 p=vUv*2.-1.;p.x*=u_resolution.x/max(1.,u_resolution.y);float t=u_time*u_motion;vec3 rd=normalize(vec3(p/max(.52,u_zoom),1.55));rd.xz*=rot(u_yaw);rd.yz*=rot(u_pitch);if(u_camera_mode==1)rd.xy*=rot(sin(t*.1)*.025);vec3 ro=vec3(0,0,-3.8)+u_position*.015;vec3 col=vec3(.0015,.0025,.009);col+=starfield(rd,t)*(u_quality*.65+.42);
float radial=length(p);float angle=atan(p.y,p.x);
if(u_mode==0){float nearby=0.;for(int i=0;i<18;i++){float fi=float(i);vec2 q=vec2(sin(fi*12.23),cos(fi*7.13))*.75;nearby+=exp(-length(p-q)*45.)*(.5+.5*sin(t*.9+fi));}col+=vec3(.5,.75,1.)*nearby;col+=vec3(.08,.18,.34)*exp(-radial*2.);}
else if(u_mode==1){float trans=1.;for(int i=0;i<72;i++){if(float(i)>mix(24.,68.,u_quality))break;float d=float(i)*.085;vec3 sp=ro+rd*d;float den=smoothstep(.47,.76,fbm(sp*.95+vec3(t*.015,0,-t*.01)))*exp(-abs(sp.y)*.09);vec3 c=palette(fbm(sp*.45),vec3(.28),vec3(.34),vec3(1.),vec3(.1,.28,.62));col+=c*den*trans*.055;trans*=1.-den*.043;}col+=vec3(.85,.45,.95)*exp(-radial*4.)*.25;}
else if(u_mode==2){float r1=ring(p,.38,28.),r2=ring(p,.58,18.),fil=fbm(vec3(p*5.,t*.04));col+=mix(vec3(.08,.9,.72),vec3(.52,.25,1.),fil)*(r1+r2*.55)*(1.+fil);col+=vec3(.8,1.,.94)*exp(-radial*radial*34.)*1.7;}
else if(u_mode==3){float shell=ring(p,.52,22.);float fil=fbm(vec3(normalize(vec3(p,1.))*5.+t*.035));col+=mix(vec3(.1,.48,1.),vec3(1.,.22,.04),fil)*shell*(.75+1.5*fil);col+=vec3(1.,.82,.5)*exp(-radial*radial*28.);}
else if(u_mode==4){float core=exp(-radial*radial*80.);float beam=exp(-abs(p.x)*65.)*smoothstep(.9,.05,abs(p.y));float pulse=.4+.6*pow(.5+.5*sin(t*7.),9.);col+=vec3(.45,.7,1.)*(core*3.+beam*pulse*1.6);col+=vec3(.18,.25,.8)*ring(p,.22,42.);}
else if(u_mode==5){float bh=smoothstep(.22,.16,radial);float disk=exp(-abs(p.y+sin(p.x*5.)*.025)*50.)*smoothstep(.12,.28,radial)*smoothstep(.9,.28,radial);float hot=.5+.5*cos(angle*3.-t*1.4);col+=mix(vec3(1.,.18,.02),vec3(1.,.92,.38),hot)*disk*2.;col*=1.-bh;col+=vec3(.16,.28,.75)*ring(p,.255,55.)*.8;}
else if(u_mode==6){float rr=radial;float arms=.5+.5*cos(angle*3.-rr*13.+t*.08);float disk=exp(-rr*2.4)*(0.15+arms*.85);float core=exp(-rr*rr*48.);col+=mix(vec3(.18,.3,.9),vec3(1.,.62,.28),smoothstep(.7,0.,rr))*disk*.95+vec3(1.,.9,.7)*core*2.2;}
else{float clusters=0.;for(int i=0;i<12;i++){float fi=float(i);vec2 q=vec2(sin(fi*14.2),cos(fi*9.7))*(.15+mod(fi,4.)*.18);float g=exp(-length(p-q)*18.);float arms=.5+.5*cos(atan(p.y-q.y,p.x-q.x)*2.-length(p-q)*25.);clusters+=g*(.35+.65*arms);}col+=mix(vec3(.24,.38,1.),vec3(.95,.5,1.),fbm(vec3(p*3.,t*.02)))*clusters;}
if(u_warp>0.){float lines=pow(max(0.,.5+.5*cos(angle*70.+radial*120.-t*28.)),14.)*smoothstep(.2,1.2,radial);col+=vec3(.42,.82,1.)*lines*u_warp*1.7;col*=1.+u_warp*.4;}
float vig=smoothstep(1.45,.18,length(p*.72));col*=.38+.62*vig;col*=mix(.75,1.,u_energy/100.);col=pow(max(col,0.),vec3(.78));outColor=vec4(col,1.);}`;
function compile(gl,type,source){const s=gl.createShader(type);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS)){const message=gl.getShaderInfoLog(s)||'Falha no shader';gl.deleteShader(s);throw new Error(message);}return s;}
export class DeepSpaceSceneRenderer{
  constructor(canvas,settingsStore,{onDiagnostics=()=>{}}={}){this.canvas=canvas;this.settingsStore=settingsStore;this.onDiagnostics=onDiagnostics;this.gl=null;this.program=null;this.vao=null;this.raf=0;this.running=false;this.fallback=false;this.contextLost=false;this.state={destination:{shaderMode:1},snapshot:{yaw:0,pitch:0,distance:4.8,position:{x:0,y:0,z:0},cameraMode:'orbit',warp:{active:false,progress:0},energy:100}};this.lastDiag=0;this.resizeObserver=typeof ResizeObserver!=='undefined'?new ResizeObserver(()=>this.resize()):null;this.onResize=()=>this.resize();this.onContextLost=e=>{e.preventDefault();this.contextLost=true;this.onDiagnostics(this.diagnostics('context-lost'));};this.onContextRestored=()=>{this.contextLost=false;this.init();};}
  init(){const gl=this.canvas.getContext('webgl2',{antialias:false,alpha:false,powerPreference:'high-performance'});if(!gl){this.startFallback();return false;}this.gl=gl;const vs=compile(gl,gl.VERTEX_SHADER,VS),fs=compile(gl,gl.FRAGMENT_SHADER,FS),p=gl.createProgram();gl.attachShader(p,vs);gl.attachShader(p,fs);gl.linkProgram(p);gl.deleteShader(vs);gl.deleteShader(fs);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw new Error(gl.getProgramInfoLog(p)||'Falha de link');if(this.program)gl.deleteProgram(this.program);if(this.vao)gl.deleteVertexArray(this.vao);this.program=p;this.vao=gl.createVertexArray();gl.bindVertexArray(this.vao);this.u={resolution:gl.getUniformLocation(p,'u_resolution'),time:gl.getUniformLocation(p,'u_time'),yaw:gl.getUniformLocation(p,'u_yaw'),pitch:gl.getUniformLocation(p,'u_pitch'),zoom:gl.getUniformLocation(p,'u_zoom'),motion:gl.getUniformLocation(p,'u_motion'),quality:gl.getUniformLocation(p,'u_quality'),warp:gl.getUniformLocation(p,'u_warp'),energy:gl.getUniformLocation(p,'u_energy'),mode:gl.getUniformLocation(p,'u_mode'),cameraMode:gl.getUniformLocation(p,'u_camera_mode'),position:gl.getUniformLocation(p,'u_position')};this.resize();return true;}
  setState(destination,snapshot){this.state={destination:destination||this.state.destination,snapshot:snapshot||this.state.snapshot};}
  start(){if(!this.gl&&!this.init())return;this.running=true;this.resizeObserver?this.resizeObserver.observe(this.canvas):addEventListener('resize',this.onResize);this.canvas.addEventListener('webglcontextlost',this.onContextLost);this.canvas.addEventListener('webglcontextrestored',this.onContextRestored);this.raf=requestAnimationFrame(t=>this.frame(t));}
  resize(){if(!this.gl)return;const rect=this.canvas.getBoundingClientRect(),profile=this.settingsStore.getProfile(),dpr=Math.min(devicePixelRatio||1,2)*profile.renderScale;const w=Math.max(2,Math.floor(rect.width*dpr)),h=Math.max(2,Math.floor(rect.height*dpr));if(w!==this.canvas.width||h!==this.canvas.height){this.canvas.width=w;this.canvas.height=h;this.gl.viewport(0,0,w,h);}}
  frame(time){if(!this.running)return;if(!this.contextLost&&this.gl&&this.program){this.resize();const gl=this.gl,profile=this.settingsStore.getProfile(),settings=this.settingsStore.get(),s=this.state.snapshot,d=this.state.destination;const quality=profile.id==='performance'?.35:profile.id==='experience'?1:.68;gl.useProgram(this.program);gl.bindVertexArray(this.vao);gl.uniform2f(this.u.resolution,this.canvas.width,this.canvas.height);gl.uniform1f(this.u.time,time*.001);gl.uniform1f(this.u.yaw,s.cameraMode==='free'?s.freeYaw??s.yaw:s.yaw);gl.uniform1f(this.u.pitch,s.cameraMode==='free'?s.freePitch??s.pitch:s.pitch);gl.uniform1f(this.u.zoom,s.cameraMode==='telescope'?1.65:Math.max(.6,6/Math.max(1,s.distance||4.8)));gl.uniform1f(this.u.motion,settings.reducedMotion?.08:profile.motionFactor);gl.uniform1f(this.u.quality,quality);gl.uniform1f(this.u.warp,s.warp?.active?Math.sin((s.warp.progress||0)*Math.PI):0);gl.uniform1f(this.u.energy,s.energy??100);gl.uniform1i(this.u.mode,d.shaderMode??0);gl.uniform1i(this.u.cameraMode,{orbit:0,free:1,cinematic:2,telescope:3}[s.cameraMode]??0);gl.uniform3f(this.u.position,s.position?.x||0,s.position?.y||0,s.position?.z||0);gl.drawArrays(gl.TRIANGLES,0,3);if(time-this.lastDiag>1200){this.lastDiag=time;this.onDiagnostics(this.diagnostics('running'));}}this.raf=requestAnimationFrame(t=>this.frame(t));}
  startFallback(){this.fallback=true;this.running=true;const ctx=this.canvas.getContext('2d');if(!ctx)return;const draw=()=>{if(!this.running)return;const rect=this.canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,1.5),w=Math.max(2,Math.floor(rect.width*dpr)),h=Math.max(2,Math.floor(rect.height*dpr));if(this.canvas.width!==w||this.canvas.height!==h){this.canvas.width=w;this.canvas.height=h;}const g=ctx.createRadialGradient(w*.55,h*.45,4,w*.5,h*.5,w*.7);g.addColorStop(0,'#512d86');g.addColorStop(.32,'#10245f');g.addColorStop(1,'#01030b');ctx.fillStyle=g;ctx.fillRect(0,0,w,h);for(let i=0;i<260;i++){const x=(i*193)%w,y=(i*83)%h,r=(i%11===0?2.2:.8)*dpr;ctx.fillStyle=`rgba(${150+i%100},${185+i%60},255,${.25+(i%7)*.08})`;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill();}ctx.fillStyle='rgba(222,238,255,.92)';ctx.font=`${16*dpr}px system-ui`;ctx.fillText('Universo Profundo · fallback 2D',18*dpr,28*dpr);this.raf=requestAnimationFrame(draw);};draw();this.onDiagnostics(this.diagnostics('fallback'));}
  diagnostics(state='idle'){return{state,renderer:this.fallback?'Canvas 2D':'WebGL2',resolution:`${this.canvas.width}×${this.canvas.height}`,profile:this.settingsStore.getProfile().id,destination:this.state.destination?.id,camera:this.state.snapshot?.cameraMode,contextLost:this.contextLost};}
  destroy(){this.running=false;cancelAnimationFrame(this.raf);this.resizeObserver?.disconnect();removeEventListener('resize',this.onResize);this.canvas.removeEventListener('webglcontextlost',this.onContextLost);this.canvas.removeEventListener('webglcontextrestored',this.onContextRestored);if(this.gl&&this.vao)this.gl.deleteVertexArray(this.vao);if(this.gl&&this.program)this.gl.deleteProgram(this.program);this.vao=null;this.program=null;this.gl=null;}
}
