const DPR=()=>Math.min(2,globalThis.devicePixelRatio||1);
export class DigitalExhibitionRenderer {
  constructor({canvas,reducedMotion=false}={}){this.canvas=canvas;this.ctx=canvas?.getContext('2d');this.reducedMotion=reducedMotion;this.state={artifacts:[],theme:{accent:'#a98cff',background:'#050817'},title:'Exposição'};this.raf=0;this.time=0;this.resizeObserver=null;this.onResize=()=>this.resize();}
  getProfile(){return {id:'procedural-2d',label:'Canvas 2D leve'};}
  start(state){this.state={...this.state,...state};this.resizeObserver=new ResizeObserver(this.onResize);this.resizeObserver.observe(this.canvas);this.resize();this.frame();}
  update(state){this.state={...this.state,...state};}
  resize(){if(!this.canvas||!this.ctx)return;const rect=this.canvas.getBoundingClientRect(),dpr=DPR();this.canvas.width=Math.max(1,Math.floor(rect.width*dpr));this.canvas.height=Math.max(1,Math.floor(rect.height*dpr));this.ctx.setTransform(dpr,0,0,dpr,0,0);}
  frame(){this.draw();if(!this.reducedMotion){this.time+=0.016;this.raf=requestAnimationFrame(()=>this.frame());}}
  draw(){const ctx=this.ctx;if(!ctx)return;const w=this.canvas.clientWidth||800,h=this.canvas.clientHeight||480,{theme,artifacts,title}=this.state;ctx.clearRect(0,0,w,h);const gradient=ctx.createRadialGradient(w*.5,h*.25,20,w*.5,h*.4,Math.max(w,h));gradient.addColorStop(0,theme.accent+'35');gradient.addColorStop(1,theme.background);ctx.fillStyle=gradient;ctx.fillRect(0,0,w,h);
    ctx.save();ctx.globalAlpha=.45;for(let i=0;i<55;i++){const x=(i*97.7)%w,y=(i*53.2+h*.08)%h,r=(i%3)+.5;ctx.fillStyle=i%7===0?theme.accent:'#ffffff';ctx.beginPath();ctx.arc(x,y+Math.sin(this.time+i)*2,r,0,Math.PI*2);ctx.fill();}ctx.restore();
    ctx.fillStyle='#f3f8ff';ctx.font='700 18px system-ui';ctx.textAlign='center';ctx.fillText(title||'Exposição digital',w/2,34);ctx.strokeStyle=theme.accent+'88';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(w*.08,h*.82);ctx.lineTo(w*.92,h*.82);ctx.stroke();
    const list=(artifacts||[]).slice(0,6),columns=w<620?2:3,cardW=Math.min(210,(w-36-(columns-1)*12)/columns),cardH=w<620?120:145,startX=(w-(columns*cardW+(columns-1)*12))/2,startY=65;
    list.forEach((item,index)=>{const row=Math.floor(index/columns),col=index%columns,x=startX+col*(cardW+12),y=startY+row*(cardH+14);ctx.fillStyle='rgba(8,18,35,.86)';ctx.strokeStyle=theme.accent+'77';ctx.lineWidth=1;ctx.beginPath();ctx.roundRect(x,y,cardW,cardH,14);ctx.fill();ctx.stroke();ctx.fillStyle=theme.accent;ctx.font='800 11px system-ui';ctx.textAlign='left';ctx.fillText(String(item.type||'PEÇA').toUpperCase(),x+13,y+21);ctx.fillStyle='#f4f9ff';ctx.font='700 14px system-ui';this.wrap(ctx,item.title||'Sem título',x+13,y+43,cardW-26,18,2);ctx.fillStyle='#94a9bf';ctx.font='12px system-ui';this.wrap(ctx,item.reflection||item.summary||'',x+13,y+82,cardW-26,16,3);});
    if(!list.length){ctx.fillStyle='#9eb1c7';ctx.font='14px system-ui';ctx.textAlign='center';ctx.fillText('Selecione itens do portfólio para montar a exposição.',w/2,h/2);}}
  wrap(ctx,text,x,y,maxWidth,lineHeight,maxLines=3){const words=String(text||'').split(/\s+/);let line='',count=0;for(const word of words){const test=line?`${line} ${word}`:word;if(ctx.measureText(test).width>maxWidth&&line){ctx.fillText(line,x,y+count*lineHeight);line=word;count++;if(count>=maxLines)return;}else line=test;}if(line&&count<maxLines)ctx.fillText(line,x,y+count*lineHeight);}
  destroy(){cancelAnimationFrame(this.raf);this.resizeObserver?.disconnect();this.resizeObserver=null;this.ctx?.clearRect(0,0,this.canvas?.width||0,this.canvas?.height||0);}
}
