const VERT=`#version 300 es
precision highp float;
out vec2 vUv;
void main(){vec2 p=vec2((gl_VertexID<<1)&2,gl_VertexID&2);vUv=p;gl_Position=vec4(p*2.0-1.0,0,1);}`;
const FRAG=`#version 300 es
precision highp float;
in vec2 vUv;out vec4 outColor;
uniform vec2 u_resolution;uniform float u_time;uniform float u_yaw;uniform float u_pitch;uniform float u_zoom;uniform float u_motion;uniform int u_steps;uniform float u_mode;
float hash21(vec2 p){p=fract(p*vec2(123.34,456.21));p+=dot(p,p+45.32);return fract(p.x*p.y);}
float noise(vec3 p){vec3 i=floor(p),f=fract(p);f=f*f*(3.0-2.0*f);float n=dot(i,vec3(1,57,113));return mix(mix(mix(hash21(vec2(n,n+1.)),hash21(vec2(n+57.,n+58.)),f.y),mix(hash21(vec2(n+113.,n+114.)),hash21(vec2(n+170.,n+171.)),f.y),f.z),mix(mix(hash21(vec2(n+1.,n+2.)),hash21(vec2(n+58.,n+59.)),f.y),mix(hash21(vec2(n+114.,n+115.)),hash21(vec2(n+171.,n+172.)),f.y),f.z),f.x);}
float fbm(vec3 p){float v=0.,a=.5;for(int i=0;i<5;i++){v+=a*noise(p);p=p*2.03+vec3(7.1,3.7,5.9);a*=.5;}return v;}
mat2 rot(float a){float c=cos(a),s=sin(a);return mat2(c,-s,s,c);}
float sdSphere(vec3 p,float r){return length(p)-r;}
float sdBox(vec3 p,vec3 b){vec3 q=abs(p)-b;return length(max(q,0.))+min(max(q.x,max(q.y,q.z)),0.);}
float mapScene(vec3 p){float planet=sdSphere(p-vec3(0.,.15,4.4),1.15);float dais=sdBox(p-vec3(0.,-1.15,3.7),vec3(2.2,.08,1.8));float console=sdBox(p-vec3(0.,-.78,2.5),vec3(1.8,.18,.25));return min(planet,min(dais,console));}
vec3 normalAt(vec3 p){vec2 e=vec2(.002,0);float d=mapScene(p);return normalize(vec3(mapScene(p+e.xyy)-d,mapScene(p+e.yxy)-d,mapScene(p+e.yyx)-d));}
float gridLine(vec2 p,float scale){vec2 g=abs(fract(p*scale-.5)-.5)/fwidth(p*scale);return 1.-min(min(g.x,g.y),1.);}
void main(){
 vec2 uv=vUv;vec2 p=(uv*2.-1.);p.x*=u_resolution.x/max(1.,u_resolution.y);p/=u_zoom;
 vec3 ro=vec3(0.,0.,-1.8),rd=normalize(vec3(p,1.8));rd.xz=rot(u_yaw)*rd.xz;rd.yz=rot(u_pitch)*rd.yz;
 float t=u_time*u_motion;vec3 col=mix(vec3(.003,.008,.025),vec3(.018,.035,.095),uv.y);
 float stars=0.;for(int l=0;l<3;l++){float sc=90.+float(l)*55.;vec2 cell=floor((uv+vec2(u_yaw,u_pitch)*.03)*sc);vec2 local=fract(uv*sc)-.5;float h=hash21(cell+float(l)*9.3);stars+=smoothstep(.04,0.,length(local-(vec2(hash21(cell+2.1),hash21(cell+7.9))-.5)*.7))*step(.982+float(l)*.005,h);}
 col+=vec3(.65,.86,1.)*stars*(.8+.2*sin(t*2.));
 float fog=fbm(vec3(p*1.1,t*.025));col+=mix(vec3(.02,.05,.12),vec3(.14,.035,.24),u_mode)*fog*.15*exp(-length(p)*.5);
 float depth=0.,hit=0.;vec3 pos=ro;for(int i=0;i<96;i++){if(i>=u_steps)break;pos=ro+rd*depth;float d=mapScene(pos);if(d<.002){hit=1.;break;}depth+=d*.72;if(depth>11.)break;}
 if(hit>.5){vec3 n=normalAt(pos),light=normalize(vec3(-.6,.8,-.3));float diff=max(dot(n,light),0.);float rim=pow(1.-max(dot(n,-rd),0.),2.5);float planetMask=1.-step(.2,abs(length(pos-vec3(0.,.15,4.4))-1.15));vec3 metal=mix(vec3(.025,.11,.19),vec3(.09,.38,.55),diff);vec3 planet=mix(vec3(.015,.12,.28),vec3(.08,.58,.55),fbm((pos-vec3(0.,.15,4.4))*3.));vec3 surface=mix(metal,planet,planetMask);surface*=.24+diff;surface+=vec3(.1,.7,1.)*rim*(.35+.45*planetMask);col=surface;}
 float grid=gridLine(p+vec2(0.,.42),7.);col+=vec3(.08,.55,.9)*grid*.09*smoothstep(1.5,.1,abs(p.y+.45));
 for(int i=0;i<8;i++){float fi=float(i);float a=fi*.785+t*.08;vec2 node=vec2(cos(a),sin(a)*.42)*(.58+.08*sin(fi*2.1));float d=length(p-node);float ring=smoothstep(.025,.008,abs(d-.035));float glow=exp(-d*38.);vec3 nc=mix(vec3(.15,.75,1.),vec3(.75,.35,1.),fract(fi*.37+u_mode*.2));col+=nc*(ring*1.4+glow*.35);}
 float scan=sin((uv.y+t*.12)*u_resolution.y*.22)*.5+.5;col+=vec3(.03,.15,.2)*scan*.035;
 col*=.7+.3*smoothstep(1.35,.15,length(p));outColor=vec4(pow(col,vec3(.86)),1.);
}`;

function compile(gl,type,source){const shader=gl.createShader(type);gl.shaderSource(shader,source);gl.compileShader(shader);if(!gl.getShaderParameter(shader,gl.COMPILE_STATUS)){const message=gl.getShaderInfoLog(shader);gl.deleteShader(shader);throw new Error(message);}return shader;}

export class MissionDirectorRenderer{
 constructor(canvas,settingsStore,{onDiagnostics=()=>{}}={}){this.canvas=canvas;this.settingsStore=settingsStore;this.onDiagnostics=onDiagnostics;this.gl=null;this.program=null;this.uniforms={};this.running=false;this.rafId=0;this.yaw=0;this.pitch=-.08;this.zoom=1;this.mode=.35;this.contextLost=false;this.xrSession=null;this.xrReferenceSpace=null;this.xrEndHandler=null;this.drag=null;this.fallbackCtx=null;this.resizeObserver=typeof ResizeObserver!=='undefined'?new ResizeObserver(()=>this.resize()):null;this.onResize=()=>this.resize();this.onDown=e=>{this.drag={x:e.clientX,y:e.clientY,yaw:this.yaw,pitch:this.pitch};this.canvas.setPointerCapture?.(e.pointerId);};this.onMove=e=>{if(!this.drag)return;this.yaw=this.drag.yaw+(e.clientX-this.drag.x)*.006;this.pitch=Math.max(-.7,Math.min(.55,this.drag.pitch+(e.clientY-this.drag.y)*.004));};this.onUp=()=>{this.drag=null;};this.onWheel=e=>{e.preventDefault();this.zoom=Math.max(.7,Math.min(1.55,this.zoom-e.deltaY*.0007));};this.onLost=e=>{e.preventDefault();this.contextLost=true;this.onDiagnostics(this.getDiagnostics());};this.onRestored=()=>{this.contextLost=false;this.initialize();};}
 initialize(){
  const gl=this.canvas.getContext('webgl2',{alpha:false,antialias:false,powerPreference:'high-performance',preserveDrawingBuffer:false,failIfMajorPerformanceCaveat:false});
  if(!gl){this.startFallback('WebGL2 indisponível');return false;}
  this.gl=gl;const v=compile(gl,gl.VERTEX_SHADER,VERT),f=compile(gl,gl.FRAGMENT_SHADER,FRAG),p=gl.createProgram();gl.attachShader(p,v);gl.attachShader(p,f);gl.linkProgram(p);gl.deleteShader(v);gl.deleteShader(f);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw new Error(gl.getProgramInfoLog(p));if(this.program)gl.deleteProgram(this.program);this.program=p;
  for(const name of ['resolution','time','yaw','pitch','zoom','motion','steps','mode'])this.uniforms[name]=gl.getUniformLocation(p,`u_${name}`);
  this.resize();this.onDiagnostics(this.getDiagnostics());return true;
 }
 start(){if(!this.gl&&!this.initialize()&&!this.fallbackCtx)return;if(this.running)return;this.running=true;this.resizeObserver?.observe(this.canvas.parentElement||this.canvas);if(!this.resizeObserver)addEventListener('resize',this.onResize);this.canvas.addEventListener('pointerdown',this.onDown);this.canvas.addEventListener('pointermove',this.onMove);this.canvas.addEventListener('pointerup',this.onUp);this.canvas.addEventListener('pointercancel',this.onUp);this.canvas.addEventListener('wheel',this.onWheel,{passive:false});this.canvas.addEventListener('webglcontextlost',this.onLost);this.canvas.addEventListener('webglcontextrestored',this.onRestored);this.rafId=requestAnimationFrame(t=>this.frame(t));}
 setMode(value){this.mode=Math.max(0,Math.min(1,Number(value)||0));}
 resetCamera(){this.yaw=0;this.pitch=-.08;this.zoom=1;}
 resize(){const rect=this.canvas.parentElement?.getBoundingClientRect?.()||{width:innerWidth,height:650};const profile=this.settingsStore.getProfile();const dpr=Math.min(devicePixelRatio||1,2)*profile.renderScale;const width=Math.max(1,Math.floor(rect.width*dpr)),height=Math.max(1,Math.floor((rect.height||650)*dpr));if(this.canvas.width!==width||this.canvas.height!==height){this.canvas.width=width;this.canvas.height=height;this.canvas.style.width=`${rect.width}px`;this.canvas.style.height=`${rect.height||650}px`;this.gl?.viewport(0,0,width,height);}this.onDiagnostics(this.getDiagnostics());}
 renderGL(time,{yaw=this.yaw,pitch=this.pitch,zoom=this.zoom,resolution=[this.canvas.width,this.canvas.height]}={}){if(this.contextLost||!this.gl||!this.program)return;const gl=this.gl,profile=this.settingsStore.getProfile(),state=this.settingsStore.get();gl.useProgram(this.program);gl.uniform2f(this.uniforms.resolution,resolution[0],resolution[1]);gl.uniform1f(this.uniforms.time,time*.001);gl.uniform1f(this.uniforms.yaw,yaw);gl.uniform1f(this.uniforms.pitch,pitch);gl.uniform1f(this.uniforms.zoom,zoom);gl.uniform1f(this.uniforms.motion,state.reducedMotion?.08:profile.motionFactor);gl.uniform1i(this.uniforms.steps,profile.id==='performance'?42:profile.id==='experience'?88:64);gl.uniform1f(this.uniforms.mode,this.mode);gl.drawArrays(gl.TRIANGLES,0,3);}
 frame(time){if(!this.running||this.xrSession)return;if(this.fallbackCtx)this.drawFallback(time);else{this.resize();this.renderGL(time);}this.rafId=requestAnimationFrame(t=>this.frame(t));}
 async enterXR(session){if(!session)throw new Error('Sessão WebXR ausente.');if(!this.gl||this.fallbackCtx)throw new Error('WebXR exige o renderizador WebGL2 ativo.');if(typeof XRWebGLLayer==='undefined')throw new Error('XRWebGLLayer indisponível neste navegador.');await this.gl.makeXRCompatible?.();const layer=new XRWebGLLayer(session,this.gl);session.updateRenderState({baseLayer:layer,depthNear:.05,depthFar:100});this.xrReferenceSpace=await session.requestReferenceSpace('local');this.xrSession=session;cancelAnimationFrame(this.rafId);this.rafId=0;this.xrEndHandler=()=>{this.xrSession=null;this.xrReferenceSpace=null;this.xrEndHandler=null;if(this.running)this.rafId=requestAnimationFrame(t=>this.frame(t));};session.addEventListener('end',this.xrEndHandler,{once:true});session.requestAnimationFrame((time,frame)=>this.xrFrame(time,frame));return true;}
 xrFrame(time,frame){const session=frame.session;if(!this.xrSession||session!==this.xrSession)return;const pose=frame.getViewerPose(this.xrReferenceSpace);const layer=session.renderState.baseLayer;this.gl.bindFramebuffer(this.gl.FRAMEBUFFER,layer.framebuffer);if(pose){for(const view of pose.views){const viewport=layer.getViewport(view);this.gl.viewport(viewport.x,viewport.y,viewport.width,viewport.height);const q=view.transform.orientation;const siny=2*(q.w*q.y+q.x*q.z),cosy=1-2*(q.y*q.y+q.z*q.z);const yaw=Math.atan2(siny,cosy);const sinp=Math.max(-1,Math.min(1,2*(q.w*q.x-q.z*q.y)));const pitch=Math.asin(sinp);this.renderGL(time,{yaw,pitch,zoom:1,resolution:[viewport.width,viewport.height]});}}session.requestAnimationFrame((next, nextFrame)=>this.xrFrame(next,nextFrame));}

 startFallback(reason='Modo 2D'){this.fallbackCtx=this.canvas.getContext('2d');this.onDiagnostics({...this.getDiagnostics(),fallback:true,reason});}
 drawFallback(time){const ctx=this.fallbackCtx,w=this.canvas.width,h=this.canvas.height;if(!ctx)return;const t=time*.0002;ctx.fillStyle='#020713';ctx.fillRect(0,0,w,h);for(let i=0;i<140;i++){const x=(Math.sin(i*83.1)*.5+.5)*w,y=(Math.sin(i*29.7)*.5+.5)*h,a=.2+.8*((i%9)/9);ctx.fillStyle=`rgba(180,225,255,${a})`;ctx.fillRect(x,y,i%17===0?2:1,i%17===0?2:1);}const cx=w*.52,cy=h*.45,r=Math.min(w,h)*.18;const g=ctx.createRadialGradient(cx-r*.3,cy-r*.3,r*.1,cx,cy,r);g.addColorStop(0,'#46b8d9');g.addColorStop(.55,'#0b466f');g.addColorStop(1,'#021225');ctx.fillStyle=g;ctx.beginPath();ctx.arc(cx,cy,r,0,Math.PI*2);ctx.fill();ctx.strokeStyle='rgba(85,220,255,.45)';for(let i=0;i<8;i++){const a=i*Math.PI/4+t;ctx.beginPath();ctx.arc(cx+Math.cos(a)*r*2.2,cy+Math.sin(a)*r*.8,8,0,Math.PI*2);ctx.stroke();}ctx.fillStyle='rgba(85,220,255,.65)';ctx.font=`${Math.max(12,w/70)}px monospace`;ctx.fillText('CENTRO DE DIREÇÃO · FALLBACK 2D',24,h-28);}
 getDiagnostics(){return {renderer:this.fallbackCtx?'Canvas 2D':'WebGL2',width:this.canvas.width,height:this.canvas.height,quality:this.settingsStore.getProfile().id,yaw:Number(this.yaw.toFixed(2)),pitch:Number(this.pitch.toFixed(2)),zoom:Number(this.zoom.toFixed(2)),contextLost:this.contextLost,fallback:Boolean(this.fallbackCtx)};}
 async fullscreen(){const target=this.canvas.parentElement||this.canvas;if(document.fullscreenElement)await document.exitFullscreen?.();else await target.requestFullscreen?.();setTimeout(()=>this.resize(),100);}
 destroy(){this.running=false;if(this.xrSession){try{this.xrSession.end();}catch{}}this.xrSession=null;this.xrReferenceSpace=null;cancelAnimationFrame(this.rafId);this.rafId=0;this.resizeObserver?.disconnect();if(!this.resizeObserver)removeEventListener('resize',this.onResize);this.canvas.removeEventListener('pointerdown',this.onDown);this.canvas.removeEventListener('pointermove',this.onMove);this.canvas.removeEventListener('pointerup',this.onUp);this.canvas.removeEventListener('pointercancel',this.onUp);this.canvas.removeEventListener('wheel',this.onWheel);this.canvas.removeEventListener('webglcontextlost',this.onLost);this.canvas.removeEventListener('webglcontextrestored',this.onRestored);if(this.gl&&this.program)this.gl.deleteProgram(this.program);this.program=null;this.gl=null;this.fallbackCtx=null;}
}
