export class PhysicsArenaRenderer{
 constructor(canvas,settingsStore,{onDiagnostics=()=>{}}={}){this.canvas=canvas;this.settingsStore=settingsStore;this.onDiagnostics=onDiagnostics;this.ctx=null;this.raf=0;this.state={position:{x:0,y:1.8,z:0},mode:'earth',speed:0,suspension:[]};this.reducedMotion=settingsStore.get().reducedMotion;this.resize=()=>this.handleResize();}
 start(){this.destroy(false);this.ctx=this.canvas.getContext('2d');addEventListener('resize',this.resize);this.handleResize();const draw=now=>{this.draw(now);this.raf=requestAnimationFrame(draw)};this.raf=requestAnimationFrame(draw);this.onDiagnostics({state:'canvas2d-physics'});}
 setState(state){this.state=state;}
 draw(now){const c=this.ctx;if(!c)return;const w=this.canvas.width,h=this.canvas.height;c.clearRect(0,0,w,h);const sky=c.createLinearGradient(0,0,0,h);const colors=this.state.mode==='moon'?['#02040b','#171a20']:this.state.mode==='mars'?['#3e160c','#a44b26']:this.state.mode==='microgravity'||this.state.mode==='flight'?['#01030b','#07122b']:['#061b36','#2b6d88'];sky.addColorStop(0,colors[0]);sky.addColorStop(1,colors[1]);c.fillStyle=sky;c.fillRect(0,0,w,h);c.save();c.translate(w/2,h*.68);const scale=Math.min(w,h)/18;c.strokeStyle='rgba(112,218,255,.22)';c.lineWidth=1;for(let i=-12;i<=12;i++){c.beginPath();c.moveTo(i*scale,-h);c.lineTo(i*scale,h);c.stroke();c.beginPath();c.moveTo(-w,i*scale*.55);c.lineTo(w,i*scale*.55);c.stroke();}const x=this.state.position.x*scale*.18,z=this.state.position.z*scale*.12,y=(this.state.position.y-1.8)*scale;c.translate(x+z,-y-z*.32);c.fillStyle='#d8e7ef';c.strokeStyle='#53d9ff';c.lineWidth=3;if(this.state.mode==='rover'){c.fillRect(-scale*.75,-scale*.35,scale*1.5,scale*.55);c.fillStyle='#1b2730';for(let i=0;i<6;i++){const px=(i%3-1)*scale*.62,py=(i<3?-.02:.48)*scale;c.beginPath();c.arc(px,py,scale*.2,0,Math.PI*2);c.fill();c.stroke();}}else{c.beginPath();c.arc(0,0,scale*.42,0,Math.PI*2);c.fill();c.stroke();c.beginPath();c.moveTo(0,-scale*.4);c.lineTo(0,-scale*1.1);c.stroke();c.beginPath();c.moveTo(-scale*.55,-scale*.1);c.lineTo(scale*.55,-scale*.1);c.stroke();}c.restore();c.fillStyle='rgba(8,15,28,.78)';c.fillRect(18,18,270,64);c.fillStyle='#c8f4ff';c.font=`600 ${Math.max(12,w/80)}px sans-serif`;c.fillText(`${String(this.state.mode).toUpperCase()} · ${this.state.speed.toFixed(2)} m/s`,34,48);c.fillStyle='#7bdfff';c.fillText(`x ${this.state.position.x.toFixed(1)} · y ${this.state.position.y.toFixed(1)} · z ${this.state.position.z.toFixed(1)}`,34,72);}
 handleResize(){const p=this.settingsStore.getProfile(),scale=Math.min(2,devicePixelRatio||1)*p.renderScale;this.canvas.width=Math.max(2,Math.round(this.canvas.clientWidth*scale));this.canvas.height=Math.max(2,Math.round(this.canvas.clientHeight*scale));}
 resize(){this.handleResize();}
 requestFullscreen(){return this.canvas.parentElement?.requestFullscreen?.();}
 destroy(notify=true){cancelAnimationFrame(this.raf);removeEventListener('resize',this.resize);this.ctx=null;if(notify)this.onDiagnostics({state:'destroyed'});}
}
