import { PremiumAssetManager } from '../core/assets/PremiumAssetManager.js';
import { GltfAnimationPlayer } from '../core/assets/GltfAnimationPlayer.js';

const VS=`#version 300 es
precision highp float;
layout(location=0) in vec3 a_position;layout(location=1) in vec3 a_normal;layout(location=2) in vec4 a_color;
uniform mat4 u_model,u_view,u_projection;out vec3 v_world;out vec3 v_normal;out vec4 v_color;out vec3 v_object;
void main(){vec4 world=u_model*vec4(a_position,1.);v_world=world.xyz;v_normal=mat3(u_model)*a_normal;v_color=a_color;v_object=a_position;gl_Position=u_projection*u_view*world;}`;
const FS=`#version 300 es
precision highp float;
in vec3 v_world;in vec3 v_normal;in vec4 v_color;in vec3 v_object;out vec4 outColor;
uniform sampler2D u_albedo,u_roughness,u_environment;uniform vec3 u_camera,u_light;uniform float u_metalness,u_roughnessValue,u_exposure,u_opacity,u_time;
#define PI 3.14159265359
vec2 envUv(vec3 d){d=normalize(d);return vec2(atan(d.z,d.x)/(2.*PI)+.5,asin(clamp(d.y,-1.,1.))/PI+.5);}vec3 env(vec3 d){return texture(u_environment,envUv(d)).rgb;}
vec4 triSample(sampler2D tex,vec3 p,vec3 n){vec3 w=pow(abs(normalize(n)),vec3(5.));w/=max(.001,w.x+w.y+w.z);return texture(tex,p.yz*.42)*w.x+texture(tex,p.zx*.42)*w.y+texture(tex,p.xy*.42)*w.z;}
void main(){vec3 N=normalize(v_normal),V=normalize(u_camera-v_world),L=normalize(u_light);vec3 base=pow(max(v_color.rgb,vec3(.01)),vec3(2.2))*pow(max(triSample(u_albedo,v_object,N).rgb,vec3(.05)),vec3(2.2));float rough=clamp(u_roughnessValue*mix(.58,1.35,triSample(u_roughness,v_object,N).r),.08,.98);float metal=clamp(u_metalness,0.,1.);float ndl=max(dot(N,L),0.),ndv=max(dot(N,V),0.);vec3 H=normalize(L+V);float ndh=max(dot(N,H),0.);float power=mix(180.,5.,rough);float spec=pow(ndh,power)*(1.-rough*.55);vec3 F0=mix(vec3(.04),base,metal);vec3 fres=F0+(1.-F0)*pow(1.-max(dot(H,V),0.),5.);vec3 reflected=env(reflect(-V,N));vec3 diffuse=base*(1.-metal)*(ndl*.88+.09);vec3 color=diffuse+fres*spec*2.2+reflected*mix(.18,.74,metal)*(1.-rough*.45)+env(N)*base*.12;float rim=pow(1.-ndv,2.4);color+=vec3(.08,.58,1.1)*rim*.18;color=vec3(1.)-exp(-color*u_exposure);color=pow(max(color,0.),vec3(1./2.2));float alpha=clamp(u_opacity*(.9+.1*rim),0.,1.);outColor=vec4(color*alpha,alpha);}`;
function compile(gl,type,source){const shader=gl.createShader(type);gl.shaderSource(shader,source);gl.compileShader(shader);if(!gl.getShaderParameter(shader,gl.COMPILE_STATUS)){const error=gl.getShaderInfoLog(shader)||'Falha ao compilar shader premium integrado.';gl.deleteShader(shader);throw new Error(error);}return shader;}
function createProgram(gl){const p=gl.createProgram(),vs=compile(gl,gl.VERTEX_SHADER,VS),fs=compile(gl,gl.FRAGMENT_SHADER,FS);gl.attachShader(p,vs);gl.attachShader(p,fs);gl.linkProgram(p);gl.deleteShader(vs);gl.deleteShader(fs);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw new Error(gl.getProgramInfoLog(p)||'Falha de link premium integrado.');return p;}
function matMul(a,b){const o=new Float32Array(16);for(let c=0;c<4;c++)for(let r=0;r<4;r++)o[c*4+r]=a[r]*b[c*4]+a[4+r]*b[c*4+1]+a[8+r]*b[c*4+2]+a[12+r]*b[c*4+3];return o;}
function identity(){return new Float32Array([1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]);}
function trs(t=[0,0,0],q=[0,0,0,1],s=[1,1,1]){const[x,y,z,w]=q,x2=x+x,y2=y+y,z2=z+z,xx=x*x2,xy=x*y2,xz=x*z2,yy=y*y2,yz=y*z2,zz=z*z2,wx=w*x2,wy=w*y2,wz=w*z2;return new Float32Array([(1-(yy+zz))*s[0],(xy+wz)*s[0],(xz-wy)*s[0],0,(xy-wz)*s[1],(1-(xx+zz))*s[1],(yz+wx)*s[1],0,(xz+wy)*s[2],(yz-wx)*s[2],(1-(xx+yy))*s[2],0,t[0],t[1],t[2],1]);}
function perspective(fov,aspect,near,far){const f=1/Math.tan(fov/2),nf=1/(near-far);return new Float32Array([f/aspect,0,0,0,0,f,0,0,0,0,(far+near)*nf,-1,0,0,2*far*near*nf,0]);}
function lookAt(eye,target=[0,0,0],up=[0,1,0]){let zx=eye[0]-target[0],zy=eye[1]-target[1],zz=eye[2]-target[2],zl=Math.hypot(zx,zy,zz)||1;zx/=zl;zy/=zl;zz/=zl;let xx=up[1]*zz-up[2]*zy,xy=up[2]*zx-up[0]*zz,xz=up[0]*zy-up[1]*zx,xl=Math.hypot(xx,xy,xz)||1;xx/=xl;xy/=xl;xz/=xl;const yx=zy*xz-zz*xy,yy=zz*xx-zx*xz,yz=zx*xy-zy*xx;return new Float32Array([xx,yx,zx,0,xy,yy,zy,0,xz,yz,zz,0,-xx*eye[0]-xy*eye[1]-xz*eye[2],-yx*eye[0]-yy*eye[1]-yz*eye[2],-zx*eye[0]-zy*eye[1]-zz*eye[2],1]);}
async function imageFromBlob(blob){if(typeof createImageBitmap==='function')return createImageBitmap(blob);return new Promise((resolve,reject)=>{const img=new Image(),url=URL.createObjectURL(blob);img.onload=()=>{URL.revokeObjectURL(url);resolve(img);};img.onerror=()=>{URL.revokeObjectURL(url);reject(new Error('Falha ao decodificar textura integrada.'));};img.src=url;});}
function textureFromImage(gl,image,{roughness=false}={}){const tex=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,tex);gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL,true);gl.texImage2D(gl.TEXTURE_2D,0,roughness?gl.RGBA8:gl.SRGB8_ALPHA8,gl.RGBA,gl.UNSIGNED_BYTE,image);gl.generateMipmap(gl.TEXTURE_2D);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR_MIPMAP_LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.REPEAT);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.REPEAT);return tex;}
function textureFromHdr(gl,hdr){const tex=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,tex);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA32F,hdr.width,hdr.height,0,gl.RGBA,gl.FLOAT,hdr.pixels);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.NEAREST);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.NEAREST);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.REPEAT);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);return tex;}
export class PremiumAssetOverlayRenderer{
 constructor(canvas,settingsStore,{onDiagnostics=()=>{},onAssetLoaded=()=>{}}={}){this.canvas=canvas;this.settingsStore=settingsStore;this.onDiagnostics=onDiagnostics;this.onAssetLoaded=onAssetLoaded;this.manager=new PremiumAssetManager({settingsStore});this.gl=null;this.program=null;this.drawables=[];this.textures=[];this.current=null;this.player=null;this.assetId='shuttle';this.lod='auto';this.visible=true;this.opacity=.94;this.yaw=.6;this.pitch=-.12;this.distance=5.2;this.scale=1;this.offset=[0,0,0];this.turn=0;this.raf=0;this.running=false;this.last=0;this.contextLost=false;this.loadToken=0;this.currentAnimation=null;this.resizeObserver=typeof ResizeObserver!=='undefined'?new ResizeObserver(()=>this.resize()):null;this.onResize=()=>this.resize();this.onContextLost=e=>{e.preventDefault();this.contextLost=true;this.onDiagnostics({state:'context-lost'});};this.onContextRestored=async()=>{this.contextLost=false;await this.init(true);await this.loadAsset(this.assetId,'auto',true);};}
 async init(force=false){if(this.gl&&!force)return true;try{await this.manager.init();}catch(error){this.onDiagnostics({state:'error',message:error.message,code:error.code||'RESOURCE'});this.startFallback('assets');return false;}const gl=this.canvas.getContext('webgl2',{alpha:true,antialias:true,premultipliedAlpha:true,powerPreference:'high-performance'});if(!gl){this.startFallback();return false;}this.gl=gl;this.program=createProgram(gl);this.uniforms={model:gl.getUniformLocation(this.program,'u_model'),view:gl.getUniformLocation(this.program,'u_view'),projection:gl.getUniformLocation(this.program,'u_projection'),camera:gl.getUniformLocation(this.program,'u_camera'),light:gl.getUniformLocation(this.program,'u_light'),metalness:gl.getUniformLocation(this.program,'u_metalness'),roughness:gl.getUniformLocation(this.program,'u_roughnessValue'),exposure:gl.getUniformLocation(this.program,'u_exposure'),opacity:gl.getUniformLocation(this.program,'u_opacity'),time:gl.getUniformLocation(this.program,'u_time'),albedo:gl.getUniformLocation(this.program,'u_albedo'),roughnessMap:gl.getUniformLocation(this.program,'u_roughness'),environment:gl.getUniformLocation(this.program,'u_environment')};this.resize();return true;}
 startFallback(reason='webgl'){this.canvas.hidden=true;this.canvas.classList.add('premium-layer-hidden');this.onDiagnostics({state:'fallback',renderer:'procedural',reason});}
 async start(assetId='shuttle'){if(!await this.init())return false;this.running=true;this.canvas.hidden=false;this.resizeObserver?this.resizeObserver.observe(this.canvas):addEventListener('resize',this.onResize);this.canvas.addEventListener('webglcontextlost',this.onContextLost);this.canvas.addEventListener('webglcontextrestored',this.onContextRestored);await this.loadAsset(assetId,'auto');this.last=performance.now();this.raf=requestAnimationFrame(t=>this.frame(t));return true;}
 setPresentation({yaw,pitch,distance,scale,offset,opacity}={}){if(Number.isFinite(yaw))this.yaw=yaw;if(Number.isFinite(pitch))this.pitch=pitch;if(Number.isFinite(distance))this.distance=distance;if(Number.isFinite(scale))this.scale=scale;if(Array.isArray(offset))this.offset=offset;if(Number.isFinite(opacity))this.opacity=opacity;}
 setVisible(value){this.visible=Boolean(value);this.canvas.classList.toggle('premium-layer-hidden',!this.visible);}
 playAnimation(name,{loop,speed,restart=false}={}){if(!name||!this.player)return false;if(name===this.currentAnimation&&!restart)return true;const ok=this.player.play(name,{loop,speed,restart:true});if(ok){this.currentAnimation=name;this.onDiagnostics({state:'animation',animation:name});}return ok;}
 animationList(){return this.player?.list?.()||[];}
 async loadAsset(id,lod='auto',force=false){this.assetId=id;this.lod=lod;if(!this.gl)return;const token=++this.loadToken;this.onDiagnostics({state:'loading',asset:id});try{const loaded=await this.manager.loadAsset(id,{lod,force});if(!this.gl||token!==this.loadToken)return;const[albedo,roughness]=await Promise.all([imageFromBlob(loaded.albedoBlob),imageFromBlob(loaded.roughnessBlob)]);if(!this.gl||token!==this.loadToken){albedo.close?.();roughness.close?.();return;}this.disposeGeometry();const gl=this.gl;for(const primitive of loaded.scene.primitives){const vao=gl.createVertexArray(),buffers=[];gl.bindVertexArray(vao);const bind=(location,data,size)=>{const buffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,data,gl.STATIC_DRAW);gl.enableVertexAttribArray(location);gl.vertexAttribPointer(location,size,gl.FLOAT,false,0,0);buffers.push(buffer);};bind(0,primitive.positions,3);bind(1,primitive.normals,3);bind(2,primitive.colors,4);const index=gl.createBuffer();gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,index);gl.bufferData(gl.ELEMENT_ARRAY_BUFFER,primitive.indices,gl.STATIC_DRAW);buffers.push(index);this.drawables.push({vao,buffers,primitive});}this.textures=[textureFromImage(gl,albedo),textureFromImage(gl,roughness,{roughness:true}),textureFromHdr(gl,loaded.environment)];albedo.close?.();roughness.close?.();this.current=loaded;this.player=new GltfAnimationPlayer(loaded.scene);const defaultAnimation=loaded.asset.animations?.[0];if(defaultAnimation)this.playAnimation(defaultAnimation,{restart:true});this.onAssetLoaded(loaded);this.onDiagnostics({state:'loaded',asset:id,lod:loaded.selected.level,triangles:loaded.scene.triangles,vertices:loaded.scene.vertices,parts:loaded.scene.parts,animations:loaded.scene.animations.length,loadMs:loaded.loadMs});}catch(error){this.current=null;this.disposeGeometry();this.canvas.classList.add('premium-layer-hidden');this.onDiagnostics({state:'error',asset:id,message:error.message,code:error.code||'RESOURCE'});}}
 resize(){if(!this.gl)return;const rect=this.canvas.getBoundingClientRect(),profile=this.settingsStore.getProfile(),dpr=Math.min(devicePixelRatio||1,1.7)*Math.min(1,profile.renderScale+.05),w=Math.max(2,Math.floor(rect.width*dpr)),h=Math.max(2,Math.floor(rect.height*dpr));if(w!==this.canvas.width||h!==this.canvas.height){this.canvas.width=w;this.canvas.height=h;this.gl.viewport(0,0,w,h);}}
 frame(time){if(!this.running)return;const dt=Math.min(.05,(time-this.last)/1000||.016);this.last=time;if(!this.settingsStore.get().reducedMotion)this.turn+=dt*.18;const overrides=this.player?.update(dt)||new Map();if(this.visible&&!this.contextLost&&this.gl&&this.current)this.draw(time,overrides);else if(this.gl){this.gl.clearColor(0,0,0,0);this.gl.clear(this.gl.COLOR_BUFFER_BIT|this.gl.DEPTH_BUFFER_BIT);}this.raf=requestAnimationFrame(t=>this.frame(t));}
 worldMatrices(overrides){const scene=this.current.scene,worlds=new Array(scene.nodes.length),visit=(index,parent)=>{const n=scene.nodes[index],o=overrides.get(index)||{},local=n.matrix?new Float32Array(n.matrix):trs(o.translation||n.translation,o.rotation||n.rotation,o.scale||n.scale),world=matMul(parent,local);worlds[index]=world;for(const child of n.children)visit(child,world);};for(const root of scene.roots)visit(root,identity());return worlds;}
 draw(time,overrides){this.resize();const gl=this.gl,scene=this.current.scene,profile=this.settingsStore.getProfile(),exposure=profile.id==='experience'?1.4:profile.id==='performance'?1.02:1.18,eye=[Math.sin(this.yaw)*Math.cos(this.pitch)*this.distance,Math.sin(this.pitch)*this.distance,Math.cos(this.yaw)*Math.cos(this.pitch)*this.distance],view=lookAt(eye),projection=perspective(Math.PI/4,this.canvas.width/this.canvas.height,.05,100),baseScale=(1.75/Math.max(.01,scene.bounds.radius))*this.scale,base=matMul(trs(this.offset,[0,Math.sin(this.turn/2),0,Math.cos(this.turn/2)],[baseScale,baseScale,baseScale]),trs(scene.bounds.center.map(v=>-v))),worlds=this.worldMatrices(overrides);gl.clearColor(0,0,0,0);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.enable(gl.DEPTH_TEST);gl.enable(gl.BLEND);gl.blendFunc(gl.ONE,gl.ONE_MINUS_SRC_ALPHA);gl.useProgram(this.program);gl.uniformMatrix4fv(this.uniforms.view,false,view);gl.uniformMatrix4fv(this.uniforms.projection,false,projection);gl.uniform3fv(this.uniforms.camera,eye);gl.uniform3f(this.uniforms.light,-.65,.9,.5);gl.uniform1f(this.uniforms.metalness,this.current.asset.metalness);gl.uniform1f(this.uniforms.roughness,this.current.asset.roughness);gl.uniform1f(this.uniforms.exposure,exposure);gl.uniform1f(this.uniforms.opacity,this.opacity);gl.uniform1f(this.uniforms.time,time*.001);this.textures.forEach((texture,index)=>{gl.activeTexture(gl.TEXTURE0+index);gl.bindTexture(gl.TEXTURE_2D,texture);});gl.uniform1i(this.uniforms.albedo,0);gl.uniform1i(this.uniforms.roughnessMap,1);gl.uniform1i(this.uniforms.environment,2);for(const item of this.drawables){gl.bindVertexArray(item.vao);gl.uniformMatrix4fv(this.uniforms.model,false,matMul(base,worlds[item.primitive.nodeIndex]||identity()));gl.drawElements(gl.TRIANGLES,item.primitive.indices.length,item.primitive.indexType===5125?gl.UNSIGNED_INT:gl.UNSIGNED_SHORT,0);}gl.disable(gl.BLEND);}
 disposeGeometry(){if(!this.gl)return;for(const item of this.drawables){for(const buffer of item.buffers)this.gl.deleteBuffer(buffer);this.gl.deleteVertexArray(item.vao);}for(const texture of this.textures)this.gl.deleteTexture(texture);this.drawables=[];this.textures=[];this.player=null;this.currentAnimation=null;}
 destroy(){this.running=false;cancelAnimationFrame(this.raf);this.resizeObserver?.disconnect();removeEventListener('resize',this.onResize);this.canvas.removeEventListener('webglcontextlost',this.onContextLost);this.canvas.removeEventListener('webglcontextrestored',this.onContextRestored);this.disposeGeometry();if(this.gl&&this.program)this.gl.deleteProgram(this.program);this.manager.releaseAll();this.gl=null;this.program=null;}
}
