const clamp=(v,min,max)=>Math.min(max,Math.max(min,v));
const FLOW_COLORS={energy:'#ffd166',data:'#5edbff',command:'#bc8cff'};
export class SpaceAssemblyRenderer{
  constructor(canvas,settingsStore,{onSelect=()=>{},onDiagnostics=()=>{}}={}){this.canvas=canvas;this.settingsStore=settingsStore;this.onSelect=onSelect;this.onDiagnostics=onDiagnostics;this.ctx=null;this.system=null;this.snapshot=null;this.raf=0;this.last=0;this.yaw=-.25;this.pitch=.18;this.zoom=1;this.drag=null;this.width=1;this.height=1;this.dpr=1;this.hits=[];this.onResize=()=>this.resize();this.onPointerDown=e=>this.pointerDown(e);this.onPointerMove=e=>this.pointerMove(e);this.onPointerUp=()=>this.drag=null;this.onWheel=e=>{e.preventDefault();this.zoom=clamp(this.zoom-e.deltaY*.0009,.65,1.7);};}
  start(){this.ctx=this.canvas.getContext('2d');if(!this.ctx)throw new Error('Canvas 2D indisponível.');this.canvas.addEventListener('pointerdown',this.onPointerDown);this.canvas.addEventListener('pointermove',this.onPointerMove);this.canvas.addEventListener('pointerup',this.onPointerUp);this.canvas.addEventListener('pointercancel',this.onPointerUp);this.canvas.addEventListener('wheel',this.onWheel,{passive:false});addEventListener('resize',this.onResize,{passive:true});this.resize();this.last=performance.now();this.raf=requestAnimationFrame(t=>this.loop(t));}
  setSystem(system){this.system=system;this.hits=[];}
  setState(snapshot){this.snapshot=snapshot;}
  resize(){const rect=this.canvas.getBoundingClientRect();this.dpr=Math.min(2,devicePixelRatio||1);this.width=Math.max(1,Math.floor(rect.width*this.dpr));this.height=Math.max(1,Math.floor(rect.height*this.dpr));if(this.canvas.width!==this.width||this.canvas.height!==this.height){this.canvas.width=this.width;this.canvas.height=this.height;}this.onDiagnostics({renderer:'canvas2d-workbench',resolution:`${this.width}×${this.height}`});}
  loop(now){const dt=Math.min(.05,(now-this.last)/1000||.016);this.last=now;if(!this.drag&&!this.settingsStore?.get?.().reducedMotion)this.yaw+=dt*.018;this.draw(now*.001);this.raf=requestAnimationFrame(t=>this.loop(t));}
  pointerDown(event){const rect=this.canvas.getBoundingClientRect(),x=(event.clientX-rect.left)*this.dpr,y=(event.clientY-rect.top)*this.dpr;const hit=[...this.hits].reverse().find(item=>Math.hypot(item.x-x,item.y-y)<=item.r);if(hit){this.onSelect(hit);return;}this.drag={x:event.clientX,y:event.clientY,yaw:this.yaw,pitch:this.pitch};this.canvas.setPointerCapture?.(event.pointerId);}
  pointerMove(event){if(!this.drag)return;this.yaw=this.drag.yaw+(event.clientX-this.drag.x)*.007;this.pitch=clamp(this.drag.pitch+(event.clientY-this.drag.y)*.005,-.65,.65);}
  project([x,y,z=0]){const cy=Math.cos(this.yaw),sy=Math.sin(this.yaw),cp=Math.cos(this.pitch),sp=Math.sin(this.pitch);const rx=x*cy-z*sy,rz=x*sy+z*cy,ry=y*cp-rz*sp,depth=y*sp+rz*cp,scale=Math.min(this.width,this.height)*.21*this.zoom/(1+depth*.08);return{x:this.width*.5+rx*scale,y:this.height*.5-ry*scale,depth,scale};}
  componentPosition(component){const slotId=Object.entries(this.snapshot?.installed||{}).find(([,id])=>id===component.id)?.[0];const slot=this.system?.slots.find(item=>item.id===slotId);return slot?.position||component.position;}
  draw(time){const c=this.ctx;if(!c)return;const profile=this.settingsStore.getProfile();c.fillStyle=profile.id==='performance'?'#02060c':'#020710';c.fillRect(0,0,this.width,this.height);this.drawGrid(time);if(!this.system||!this.snapshot){c.fillStyle='#9bdcf0';c.font=`${18*this.dpr}px system-ui`;c.fillText('Preparando oficina espacial…',30*this.dpr,50*this.dpr);return;}this.hits=[];this.drawWorkbench();this.drawConnections(time);const entries=this.system.slots.map(slot=>({slot,p:this.project(slot.position)})).sort((a,b)=>a.p.depth-b.p.depth);for(const {slot,p} of entries)this.drawSlot(slot,p);this.drawLegend();}
  drawGrid(time){const c=this.ctx,w=this.width,h=this.height,step=54*this.dpr,offset=this.settingsStore?.get?.().reducedMotion?0:(time*8*this.dpr)%step;c.save();c.strokeStyle='rgba(85,194,229,.07)';c.lineWidth=1;for(let x=-step+offset;x<w+step;x+=step){c.beginPath();c.moveTo(x,0);c.lineTo(x,h);c.stroke();}for(let y=-step+offset;y<h+step;y+=step){c.beginPath();c.moveTo(0,y);c.lineTo(w,y);c.stroke();}const g=c.createRadialGradient(w*.5,h*.5,0,w*.5,h*.5,Math.min(w,h)*.55);g.addColorStop(0,'rgba(26,119,155,.16)');g.addColorStop(1,'rgba(0,0,0,0)');c.fillStyle=g;c.fillRect(0,0,w,h);c.restore();}
  drawWorkbench(){const c=this.ctx,p=this.project([0,0,0]),size=Math.min(this.width,this.height)*.25*this.zoom;c.save();c.translate(p.x,p.y);c.rotate(this.yaw*.08);c.fillStyle='rgba(7,25,42,.82)';c.strokeStyle=this.system.color;c.lineWidth=2*this.dpr;c.shadowColor=this.system.color;c.shadowBlur=18*this.dpr;c.beginPath();if(this.system.shape==='capsule'){c.moveTo(0,-size*.72);c.lineTo(size*.52,size*.45);c.quadraticCurveTo(0,size*.72,-size*.52,size*.45);c.closePath();}else if(this.system.shape==='rover'){c.roundRect(-size*.72,-size*.3,size*1.44,size*.6,15*this.dpr);}else if(this.system.shape==='shuttle'){c.moveTo(size*.82,0);c.lineTo(-size*.55,-size*.28);c.lineTo(-size*.18,0);c.lineTo(-size*.55,size*.28);c.closePath();}else if(this.system.shape==='station'){c.rect(-size*.68,-size*.12,size*1.36,size*.24);c.moveTo(-size*.22,-size*.6);c.lineTo(-size*.22,size*.6);c.moveTo(size*.22,-size*.6);c.lineTo(size*.22,size*.6);}else{c.roundRect(-size*.5,-size*.34,size,size*.68,15*this.dpr);c.moveTo(-size*.5,0);c.lineTo(-size,0);c.moveTo(size*.5,0);c.lineTo(size,0);}c.fill();c.stroke();c.restore();}
  drawConnections(time){const c=this.ctx,connected=new Set(this.snapshot.connected||[]),selected=this.snapshot.selectedFlow;for(const link of this.system.links){const from=this.system.components.find(item=>item.id===link.from),to=this.system.components.find(item=>item.id===link.to);if(!from||!to)continue;const a=this.project(this.componentPosition(from)),b=this.project(this.componentPosition(to)),active=connected.has(link.id),visible=link.type===selected;c.save();c.strokeStyle=active?(FLOW_COLORS[link.type]||this.system.color):'rgba(111,151,168,.13)';c.lineWidth=(visible?3:1)*this.dpr;c.setLineDash(active?[]:[5*this.dpr,6*this.dpr]);c.globalAlpha=visible?1:.34;c.beginPath();c.moveTo(a.x,a.y);c.lineTo(b.x,b.y);c.stroke();if(active&&visible&&!this.settingsStore?.get?.().reducedMotion){const phase=(time*.42+this.system.links.indexOf(link)*.11)%1,x=a.x+(b.x-a.x)*phase,y=a.y+(b.y-a.y)*phase;c.fillStyle=FLOW_COLORS[link.type];c.beginPath();c.arc(x,y,4*this.dpr,0,Math.PI*2);c.fill();}c.restore();}}
  drawSlot(slot,p){const c=this.ctx,installedId=this.snapshot.installed?.[slot.id],component=this.system.components.find(item=>item.id===installedId),expected=this.system.components.find(item=>item.slot===slot.id),selectedId=this.snapshot.selectedComponentId,fault=this.snapshot.activeFault,wrong=component&&component.slot!==slot.id,selected=component?.id===selectedId,highlight=!component&&this.snapshot.difficulty==='guided'&&expected?.id===selectedId;const r=(component?18:15)*this.dpr*this.zoom;c.save();c.shadowColor=wrong?'#ff627d':highlight?'#ffe66d':selected?this.system.color:'rgba(0,0,0,0)';c.shadowBlur=(wrong||highlight||selected?22:6)*this.dpr;c.fillStyle=component?(wrong?'rgba(101,12,34,.9)':'rgba(8,35,54,.92)'):'rgba(4,18,31,.55)';c.strokeStyle=wrong?'#ff627d':highlight?'#ffe66d':component?this.system.color:'rgba(123,188,210,.32)';c.lineWidth=(selected||highlight?3:1.5)*this.dpr;c.setLineDash(component?[]:[5*this.dpr,5*this.dpr]);c.beginPath();c.arc(p.x,p.y,r,0,Math.PI*2);c.fill();c.stroke();c.setLineDash([]);c.fillStyle='#effcff';c.textAlign='center';c.textBaseline='middle';c.font=`900 ${11*this.dpr*this.zoom}px system-ui`;c.fillText(component?.icon||'＋',p.x,p.y);c.font=`700 ${9*this.dpr}px system-ui`;c.fillStyle=component?'#dff8ff':'#779baa';c.fillText(component?.name||slot.label,p.x,p.y+r+13*this.dpr);if(fault?.target===component?.id){c.fillStyle='#ff4d6d';c.beginPath();c.arc(p.x+r*.72,p.y-r*.72,6*this.dpr,0,Math.PI*2);c.fill();}c.restore();this.hits.push({kind:component?'component':'slot',id:component?.id||slot.id,slotId:slot.id,x:p.x,y:p.y,r:r+14*this.dpr});}
  drawLegend(){const c=this.ctx,h=this.height;c.save();c.font=`700 ${9*this.dpr}px ui-monospace`;c.fillStyle='rgba(202,232,242,.66)';c.fillText('Arraste: girar bancada · roda/pinça: zoom · toque: instalar/inspecionar',20*this.dpr,h-18*this.dpr);c.restore();}
  destroy(){cancelAnimationFrame(this.raf);removeEventListener('resize',this.onResize);this.canvas?.removeEventListener('pointerdown',this.onPointerDown);this.canvas?.removeEventListener('pointermove',this.onPointerMove);this.canvas?.removeEventListener('pointerup',this.onPointerUp);this.canvas?.removeEventListener('pointercancel',this.onPointerUp);this.canvas?.removeEventListener('wheel',this.onWheel);this.ctx=null;this.system=null;this.snapshot=null;this.hits=[];}
}
