const VS=`#version 300 es
precision highp float;out vec2 vUv;void main(){vec2 p=vec2((gl_VertexID<<1)&2,gl_VertexID&2);vUv=p;gl_Position=vec4(p*2.-1.,0.,1.);}`;
const FS=`#version 300 es
precision highp float;in vec2 vUv;out vec4 outColor;
uniform vec2 u_resolution;uniform float u_time,u_yaw,u_pitch,u_distance,u_motion,u_quality,u_animation;uniform int u_exhibit,u_zone,u_camera;uniform vec3 u_walk_pos;
#define FAR 60.
float hash31(vec3 p){p=fract(p*.1031);p+=dot(p,p.yzx+33.33);return fract((p.x+p.y)*p.z);}mat2 rot(float a){float c=cos(a),s=sin(a);return mat2(c,-s,s,c);}float sdSphere(vec3 p,float r){return length(p)-r;}float sdBox(vec3 p,vec3 b){vec3 q=abs(p)-b;return length(max(q,0.))+min(max(q.x,max(q.y,q.z)),0.);}float sdRoundBox(vec3 p,vec3 b,float r){return sdBox(p,b)-r;}float sdCyl(vec3 p,float r,float h){vec2 d=abs(vec2(length(p.xz),p.y))-vec2(r,h);return min(max(d.x,d.y),0.)+length(max(d,0.));}float sdCapsule(vec3 p,vec3 a,vec3 b,float r){vec3 pa=p-a,ba=b-a;float h=clamp(dot(pa,ba)/dot(ba,ba),0.,1.);return length(pa-ba*h)-r;}float sdTorus(vec3 p,vec2 t){vec2 q=vec2(length(p.xz)-t.x,p.y);return length(q)-t.y;}float opU(float a,float b){return min(a,b);}float opS(float a,float b){return max(-b,a);}vec2 hit(float d,float m){return vec2(d,m);}vec2 uni(vec2 a,vec2 b){return a.x<b.x?a:b;}
float rocket(vec3 p){float d=sdCyl(p, .28,1.35);d=opU(d,sdCyl(p-vec3(0,1.48,0),.2,.22));vec3 q=p-vec3(0,1.86,0);float cone=max(length(q.xz)-(.28-(q.y+.38)*.45),abs(q.y)-.4);d=opU(d,cone);d=opU(d,sdCyl(p+vec3(0,1.48,0),.34,.15));for(int i=0;i<4;i++){float a=float(i)*1.5708;vec3 e=p+vec3(sin(a)*.16,1.72,cos(a)*.16);d=opU(d,sdCyl(e,.055,.2));}return d;}
float booster(vec3 p){float d=rocket(p);for(int i=0;i<4;i++){float a=float(i)*1.5708;vec3 q=p+vec3(sin(a)*.42,1.15-u_animation*.25,cos(a)*.42);q.xz*=rot(-a);d=opU(d,sdBox(q,vec3(.28,.035,.045)));}return d;}
float capsule(vec3 p){float d=sdCyl(p,.55,.38);d=opU(d,sdSphere((p-vec3(0,.32,0))*vec3(1.,1.4,1.),.55));d=opS(d,sdBox(p-vec3(0,.22,-.48),vec3(.2,.12,.12)));return d;}
float lander(vec3 p){float d=sdBox(p-vec3(0,.25,0),vec3(.48,.38,.45));d=opU(d,sdCyl(p-vec3(0,.78,0),.34,.18));for(int i=0;i<4;i++){float a=float(i)*1.5708;vec3 foot=vec3(sin(a)*.78,-.45-u_animation*.16,cos(a)*.78);d=opU(d,sdCapsule(p,vec3(sin(a)*.3,0.,cos(a)*.3),foot,.035));d=opU(d,sdCyl(p-foot,.12,.025));}return d;}
float shuttle(vec3 p){float d=sdRoundBox(p*vec3(1.,1.2,1.)-vec3(0,.1,0),vec3(.38,.3,1.2),.18);vec3 wing=p;wing.z+=.15;d=opU(d,sdBox(wing,vec3(1.15,.045,.48)));d=opU(d,sdBox(p-vec3(0,.45,.5),vec3(.06,.48,.38)));if(u_animation>.5)d=opS(d,sdBox(p-vec3(0,.33,.15),vec3(.25,.2,.55)));return d;}
float suit(vec3 p){float d=sdSphere(p-vec3(0,.82,0),.22);d=opU(d,sdRoundBox(p-vec3(0,.25,0),vec3(.32,.48,.2),.12));d=opU(d,sdCapsule(p,vec3(-.24,.5,0),vec3(-.55,.05,0),.09));d=opU(d,sdCapsule(p,vec3(.24,.5,0),vec3(.55,.05,0),.09));d=opU(d,sdCapsule(p,vec3(-.15,-.15,0),vec3(-.22,-.75,0),.11));d=opU(d,sdCapsule(p,vec3(.15,-.15,0),vec3(.22,-.75,0),.11));return d;}
float rover(vec3 p){float d=sdRoundBox(p-vec3(0,.25,0),vec3(.65,.22,.45),.08);d=opU(d,sdCyl((p-vec3(0,.72,0)).xzy,.05,.5));d=opU(d,sdBox(p-vec3(0,.78,0),vec3(.25,.1,.16)));for(int i=0;i<6;i++){float side=i<3?-1.:1.;float z=(float(i%3)-1.)*.38;vec3 q=p-vec3(side*.72,0.,z);q.zx*=rot(1.5708);d=opU(d,sdTorus(q,vec2(.17,.055)));}vec3 arm=p-vec3(.48,.42,-.2-u_animation*.2);d=opU(d,sdCapsule(arm,vec3(0),vec3(.45,.22,-.2),.045));return d;}
float telescope(vec3 p){float d=sdBox(p-vec3(0,.1,0),vec3(.42,.28,.8));d=opU(d,sdCyl((p-vec3(0,.2,-.9)).xzy,.5,.08));for(int i=0;i<6;i++){float a=float(i)*1.0472;vec3 q=p-vec3(sin(a)*.3,.2,-.98+cos(a)*.3);d=opU(d,sdSphere(q,.17));}d=opU(d,sdBox(p-vec3(0,-.55,0),vec3(1.3,.03,.65)));return d;}
float satellite(vec3 p){float d=sdBox(p,vec3(.38,.3,.45));d=opU(d,sdCyl((p-vec3(0,0,-.6-u_animation*.2)).xzy,.48,.06));d=opU(d,sdBox(p-vec3(1.15,0,0),vec3(.72,.03,.42)));d=opU(d,sdBox(p+vec3(1.15,0,0),vec3(.72,.03,.42)));return d;}
float probe(vec3 p){float d=sdBox(p,vec3(.32,.28,.4));vec3 q=p-vec3(0,.15,-.48-u_animation*.22);q.xy*=rot(.7);d=opU(d,sdTorus(q,vec2(.55,.045)));d=opU(d,sdCyl((p-vec3(0,-.55,0)).xzy,.18,.42));return d;}
float station(vec3 p){float d=sdCyl(p.xzy,.22,1.65);for(int i=-2;i<=2;i++){float x=float(i)*.62;d=opU(d,sdCyl((p-vec3(x,0,0)).xzy,.35,.25));}d=opU(d,sdBox(p-vec3(0,.05,0),vec3(2.45,.035,.52+u_animation*.15)));return d;}
float gateway(vec3 p){float d=sdCyl(p.xzy,.26,.75);d=opU(d,sdCyl((p-vec3(.72,0,0)).xzy,.22,.55));d=opU(d,sdBox(p-vec3(-.95,0,0),vec3(.7,.03,.4)));d=opU(d,sdBox(p-vec3(.95,0,0),vec3(.7,.03,.4)));return d;}
float exhibitSdf(vec3 p){if(u_exhibit==0)return rocket(p);if(u_exhibit==1)return booster(p);if(u_exhibit==2)return capsule(p);if(u_exhibit==3)return lander(p);if(u_exhibit==4)return shuttle(p);if(u_exhibit==5)return suit(p);if(u_exhibit==6)return rover(p);if(u_exhibit==7)return telescope(p);if(u_exhibit==8)return satellite(p);if(u_exhibit==9)return probe(p);if(u_exhibit==10)return station(p);return gateway(p);}
vec2 mapScene(vec3 p){if(u_camera==2){float cabin=sdRoundBox(p,vec3(1.8,1.1,2.4),.2);float voidBox=sdRoundBox(p-vec3(0,0,.4),vec3(1.55,.85,2.2),.16);float wall=opS(cabin,voidBox);vec2 r=hit(wall,4.);r=uni(r,hit(sdBox(p-vec3(0,-.62,1.1),vec3(1.25,.08,.55)),5.));r=uni(r,hit(sdBox(p-vec3(0,.1,1.8),vec3(1.15,.62,.08)),6.));return r;}float floorD=p.y+1.05;float hall=min(25.-abs(p.x),min(4.5-abs(p.y),21.-abs(p.z)));vec2 r=hit(floorD,2.);r=uni(r,hit(hall,3.));vec3 q=p;if(u_camera!=0)q.y+=.15;float scaleValue=(u_exhibit==0||u_exhibit==1)?.75:(u_exhibit==10?.65:1.);q/=scaleValue;float obj=exhibitSdf(q)*scaleValue;r=uni(r,hit(obj,1.));r=uni(r,hit(sdCyl(p+vec3(0,1.0,0),1.6,.08),7.));return r;}
vec3 normalAt(vec3 p){vec2 e=vec2(.002,0);float d=mapScene(p).x;return normalize(vec3(mapScene(p+e.xyy).x-d,mapScene(p+e.yxy).x-d,mapScene(p+e.yyx).x-d));}
vec3 material(float m,vec3 p){if(m<1.5){vec3 zone=u_zone==0?vec3(1.,.45,.18):u_zone==1?vec3(.3,.72,1.):u_zone==2?vec3(.25,.9,.62):vec3(.65,.42,1.);float metal=.62+.38*hash31(floor(p*14.));return mix(zone,vec3(.85,.9,.94),metal*.42);}if(m<2.5)return vec3(.035,.045,.058);if(m<3.5)return vec3(.025,.035,.055);if(m<4.5)return vec3(.15,.2,.25);if(m<5.5)return vec3(.055,.075,.09);if(m<6.5)return vec3(.08,.32,.45);return vec3(.12,.35,.48);}
void main(){vec2 p=vUv*2.-1.;p.x*=u_resolution.x/max(1.,u_resolution.y);float t=u_time*u_motion;vec3 ro,rd;if(u_camera==0){ro=u_walk_pos;rd=normalize(vec3(p,1.45));rd.xz*=rot(u_yaw);rd.yz*=rot(u_pitch);}else if(u_camera==2){ro=vec3(0,0,-1.25);rd=normalize(vec3(p,1.35));rd.xz*=rot(u_yaw*.25);rd.yz*=rot(u_pitch*.25);}else{ro=vec3(sin(u_yaw)*cos(u_pitch),sin(u_pitch),cos(u_yaw)*cos(u_pitch))*u_distance;rd=normalize(-ro+vec3(p.x*.7,p.y*.7,0));if(u_camera==3){ro.xz*=rot(t*.1);rd=normalize(-ro+vec3(p.x*.6,p.y*.6,0));}}vec3 col=vec3(.006,.009,.018);float total=0.;float mat=0.;bool found=false;for(int i=0;i<128;i++){if(float(i)>mix(58.,118.,u_quality))break;vec3 pos=ro+rd*total;vec2 h=mapScene(pos);if(h.x<.002){mat=h.y;found=true;break;}total+=h.x*.72;if(total>FAR)break;}if(found){vec3 pos=ro+rd*total,n=normalAt(pos);vec3 light=normalize(vec3(-.5,.8,-.35));float diff=max(.08,dot(n,light));float spec=pow(max(0.,dot(reflect(-light,n),-rd)),40.);col=material(mat,pos)*(diff+.16)+vec3(.7,.9,1.)*spec*.5;float grid=step(.975,fract(abs(pos.x)*.25))+step(.975,fract(abs(pos.z)*.25));if(mat>1.5&&mat<3.5)col+=vec3(.08,.4,.62)*grid*.25;}else{float stars=0.;vec3 q=rd*90.;stars=step(.997,hash31(floor(q)))*pow(max(0.,1.-length(fract(q)-.5)*2.),10.);col+=vec3(.65,.82,1.)*stars;}float fog=1.-exp(-total*.015);col=mix(col,vec3(.01,.025,.05),fog);float vig=smoothstep(1.45,.2,length(p*.72));col*=.42+.58*vig;col=pow(max(col,0.),vec3(.82));outColor=vec4(col,1.);}`;
function compile(gl,type,source){const s=gl.createShader(type);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS)){const message=gl.getShaderInfoLog(s)||'Falha no shader';gl.deleteShader(s);throw new Error(message);}return s;}
export class SpaceMuseumSceneRenderer{
  constructor(canvas,settingsStore,{onDiagnostics=()=>{}}={}){this.canvas=canvas;this.settingsStore=settingsStore;this.onDiagnostics=onDiagnostics;this.gl=null;this.program=null;this.vao=null;this.raf=0;this.running=false;this.fallback=false;this.contextLost=false;this.state={exhibitIndex:0,zoneIndex:0,snapshot:{cameraMode:'walk',position:{x:0,y:1.7,z:10},yaw:3.14,pitch:0,orbitYaw:.45,orbitPitch:-.08,orbitDistance:5},animation:false};this.resizeObserver=typeof ResizeObserver!=='undefined'?new ResizeObserver(()=>this.resize()):null;this.onResize=()=>this.resize();this.onContextLost=e=>{e.preventDefault();this.contextLost=true;this.onDiagnostics(this.diagnostics('context-lost'));};this.onContextRestored=()=>{this.contextLost=false;this.init();};this.lastDiag=0;}
  init(){const gl=this.canvas.getContext('webgl2',{antialias:false,alpha:false,powerPreference:'high-performance'});if(!gl){this.startFallback();return false;}this.gl=gl;const vs=compile(gl,gl.VERTEX_SHADER,VS),fs=compile(gl,gl.FRAGMENT_SHADER,FS),program=gl.createProgram();gl.attachShader(program,vs);gl.attachShader(program,fs);gl.linkProgram(program);gl.deleteShader(vs);gl.deleteShader(fs);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw new Error(gl.getProgramInfoLog(program)||'Falha de link');if(this.program)gl.deleteProgram(this.program);if(this.vao)gl.deleteVertexArray(this.vao);this.program=program;this.vao=gl.createVertexArray();gl.bindVertexArray(this.vao);this.u={resolution:gl.getUniformLocation(program,'u_resolution'),time:gl.getUniformLocation(program,'u_time'),yaw:gl.getUniformLocation(program,'u_yaw'),pitch:gl.getUniformLocation(program,'u_pitch'),distance:gl.getUniformLocation(program,'u_distance'),motion:gl.getUniformLocation(program,'u_motion'),quality:gl.getUniformLocation(program,'u_quality'),animation:gl.getUniformLocation(program,'u_animation'),exhibit:gl.getUniformLocation(program,'u_exhibit'),zone:gl.getUniformLocation(program,'u_zone'),camera:gl.getUniformLocation(program,'u_camera'),walkPos:gl.getUniformLocation(program,'u_walk_pos')};this.resize();return true;}
  setState({exhibitIndex=0,zoneIndex=0,snapshot,animation=false}={}){this.state={exhibitIndex,zoneIndex,snapshot:snapshot||this.state.snapshot,animation};}
  start(){if(!this.gl&&!this.init())return;this.running=true;this.resizeObserver?this.resizeObserver.observe(this.canvas):addEventListener('resize',this.onResize);this.canvas.addEventListener('webglcontextlost',this.onContextLost);this.canvas.addEventListener('webglcontextrestored',this.onContextRestored);this.raf=requestAnimationFrame(t=>this.frame(t));}
  resize(){if(!this.gl)return;const rect=this.canvas.getBoundingClientRect(),profile=this.settingsStore.getProfile(),dpr=Math.min(devicePixelRatio||1,2)*profile.renderScale;const w=Math.max(2,Math.floor(rect.width*dpr)),h=Math.max(2,Math.floor(rect.height*dpr));if(w!==this.canvas.width||h!==this.canvas.height){this.canvas.width=w;this.canvas.height=h;this.gl.viewport(0,0,w,h);}}
  frame(time){if(!this.running)return;if(!this.contextLost&&this.gl&&this.program){this.resize();const gl=this.gl,profile=this.settingsStore.getProfile(),settings=this.settingsStore.get(),s=this.state.snapshot;gl.useProgram(this.program);gl.bindVertexArray(this.vao);gl.uniform2f(this.u.resolution,this.canvas.width,this.canvas.height);gl.uniform1f(this.u.time,time*.001);gl.uniform1f(this.u.yaw,s.cameraMode==='walk'||s.cameraMode==='interior'?s.yaw:s.orbitYaw);gl.uniform1f(this.u.pitch,s.cameraMode==='walk'||s.cameraMode==='interior'?s.pitch:s.orbitPitch);gl.uniform1f(this.u.distance,s.orbitDistance||5);gl.uniform1f(this.u.motion,settings.reducedMotion?.08:profile.motionFactor);gl.uniform1f(this.u.quality,profile.id==='performance'?.25:profile.id==='experience'?1:.62);gl.uniform1f(this.u.animation,this.state.animation?.5+.5*Math.sin(time*.002):0);gl.uniform1i(this.u.exhibit,this.state.exhibitIndex);gl.uniform1i(this.u.zone,this.state.zoneIndex);gl.uniform1i(this.u.camera,{walk:0,orbit:1,interior:2,cinematic:3}[s.cameraMode]??0);gl.uniform3f(this.u.walkPos,s.position?.x||0,s.position?.y||1.7,s.position?.z||10);gl.drawArrays(gl.TRIANGLES,0,3);if(time-this.lastDiag>1200){this.lastDiag=time;this.onDiagnostics(this.diagnostics('running'));}}this.raf=requestAnimationFrame(t=>this.frame(t));}
  startFallback(){this.fallback=true;this.running=true;const ctx=this.canvas.getContext('2d');if(!ctx)return;const draw=()=>{if(!this.running)return;const rect=this.canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,1.5),w=Math.max(2,Math.floor(rect.width*dpr)),h=Math.max(2,Math.floor(rect.height*dpr));this.canvas.width=w;this.canvas.height=h;const g=ctx.createLinearGradient(0,0,0,h);g.addColorStop(0,'#0b1730');g.addColorStop(.55,'#08111d');g.addColorStop(1,'#02050a');ctx.fillStyle=g;ctx.fillRect(0,0,w,h);ctx.strokeStyle='rgba(78,205,255,.16)';for(let x=0;x<w;x+=50*dpr){ctx.beginPath();ctx.moveTo(x,h*.55);ctx.lineTo(w*.5,h);ctx.stroke();}ctx.fillStyle='#d9f6ff';ctx.font=`${17*dpr}px system-ui`;ctx.fillText('Museu Visual 3D · fallback 2D',18*dpr,30*dpr);this.raf=requestAnimationFrame(draw);};draw();this.onDiagnostics(this.diagnostics('fallback'));}
  diagnostics(state='idle'){return{state,renderer:this.fallback?'Canvas 2D':'WebGL2',resolution:`${this.canvas.width}×${this.canvas.height}`,profile:this.settingsStore.getProfile().id,exhibit:this.state.exhibitIndex,camera:this.state.snapshot?.cameraMode,contextLost:this.contextLost};}
  destroy(){this.running=false;cancelAnimationFrame(this.raf);this.resizeObserver?.disconnect();removeEventListener('resize',this.onResize);this.canvas.removeEventListener('webglcontextlost',this.onContextLost);this.canvas.removeEventListener('webglcontextrestored',this.onContextRestored);if(this.gl&&this.vao)this.gl.deleteVertexArray(this.vao);if(this.gl&&this.program)this.gl.deleteProgram(this.program);this.vao=null;this.program=null;this.gl=null;}
}
