const vertexSource=`#version 300 es
in vec2 a_position;out vec2 v_uv;void main(){v_uv=a_position*.5+.5;gl_Position=vec4(a_position,0.,1.);}`;
const fragmentSource=`#version 300 es
precision highp float;out vec4 outColor;in vec2 v_uv;
uniform vec2 u_resolution;uniform float u_time,u_yaw,u_pitch,u_roll,u_zoom,u_quality,u_motion,u_station,u_vehicle,u_satellite,u_camera,u_dock,u_fuel,u_fault,u_orbit;
uniform vec3 u_vehicle_pos,u_vehicle_rot;
#define PI 3.14159265359
float hash21(vec2 p){p=fract(p*vec2(123.34,456.21));p+=dot(p,p+45.32);return fract(p.x*p.y);}float hash31(vec3 p){p=fract(p*.1031);p+=dot(p,p.yzx+33.33);return fract((p.x+p.y)*p.z);}float noise(vec3 p){vec3 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);float n000=hash31(i),n100=hash31(i+vec3(1,0,0)),n010=hash31(i+vec3(0,1,0)),n110=hash31(i+vec3(1,1,0)),n001=hash31(i+vec3(0,0,1)),n101=hash31(i+vec3(1,0,1)),n011=hash31(i+vec3(0,1,1)),n111=hash31(i+vec3(1,1,1));return mix(mix(mix(n000,n100,f.x),mix(n010,n110,f.x),f.y),mix(mix(n001,n101,f.x),mix(n011,n111,f.x),f.y),f.z);}float fbm(vec3 p){float v=0.,a=.5;for(int i=0;i<5;i++){v+=a*noise(p);p=p*2.03+17.1;a*=.5;}return v;}
mat2 rot(float a){float c=cos(a),s=sin(a);return mat2(c,-s,s,c);}float sdSphere(vec3 p,float r){return length(p)-r;}float sdBox(vec3 p,vec3 b){vec3 q=abs(p)-b;return length(max(q,0.))+min(max(q.x,max(q.y,q.z)),0.);}float sdCapsule(vec3 p,vec3 a,vec3 b,float r){vec3 pa=p-a,ba=b-a;float h=clamp(dot(pa,ba)/dot(ba,ba),0.,1.);return length(pa-ba*h)-r;}float sdCylinder(vec3 p,float r,float h){vec2 d=abs(vec2(length(p.xz),p.y))-vec2(r,h);return min(max(d.x,d.y),0.)+length(max(d,0.));}float opU(float a,float b){return min(a,b);}float opS(float a,float b){return max(-b,a);}vec2 opU2(vec2 a,vec2 b){return a.x<b.x?a:b;}
vec3 rotateEuler(vec3 p,vec3 r){p.yz=rot(r.x)*p.yz;p.xz=rot(r.y)*p.xz;p.xy=rot(r.z)*p.xy;return p;}
vec2 solarPanel(vec3 p,vec3 pos,vec3 scale){vec3 q=p-pos;float frame=sdBox(q,scale);float cell=sdBox(q,scale-vec3(.035,.018,.035));return vec2(min(frame,cell),cell<frame?3.:2.);}
vec2 station0(vec3 p){vec2 h=vec2(99.,0.);h=opU2(h,vec2(sdCylinder(p.xzy,0.34,2.4),1.));h=opU2(h,vec2(sdCylinder((p-vec3(0,0,2.45)).xzy,.4,.45),1.));h=opU2(h,vec2(sdCylinder((p+vec3(0,0,2.45)).xzy,.4,.45),1.));h=opU2(h,vec2(sdBox(p,vec3(3.8,.09,.09)),4.));for(int i=-2;i<=2;i++){float fi=float(i);h=opU2(h,vec2(sdCylinder((p-vec3(fi*.78,0,0)).zxy,.28,.42),1.));}h=opU2(h,solarPanel(p,vec3(2.45,0,1.15),vec3(1.35,.035,.62)));h=opU2(h,solarPanel(p,vec3(-2.45,0,1.15),vec3(1.35,.035,.62)));h=opU2(h,solarPanel(p,vec3(2.45,0,-1.15),vec3(1.35,.035,.62)));h=opU2(h,solarPanel(p,vec3(-2.45,0,-1.15),vec3(1.35,.035,.62)));h=opU2(h,vec2(sdSphere(p-vec3(.75,-.46,.25),.34),6.));return h;}
vec2 station1(vec3 p){vec2 h=vec2(sdCylinder(p.xzy,.72,2.0),1.);h=opU2(h,vec2(sdBox(p-vec3(1.7,0,.3),vec3(1.45,.045,.75)),2.));h=opU2(h,vec2(sdCylinder((p-vec3(0,0,-2.05)).xzy,.38,.42),4.));h=opU2(h,vec2(sdSphere(p-vec3(0,.45,.5),.32),6.));return h;}
vec2 station2(vec3 p){vec2 h=vec2(sdCylinder(p.xzy,.4,1.25),1.);h=opU2(h,vec2(sdCylinder((p-vec3(0,0,-1.4)).xzy,.31,.45),4.));h=opU2(h,solarPanel(p,vec3(1.8,0,.2),vec3(1.35,.035,.52)));h=opU2(h,solarPanel(p,vec3(-1.8,0,.2),vec3(1.35,.035,.52)));h=opU2(h,vec2(sdBox(p-vec3(0,.55,.8),vec3(.75,.38,.48)),1.));return h;}
vec2 station3(vec3 p){vec2 h=vec2(sdCylinder(p.xzy,.3,1.4),1.);float ring=abs(length(p.xy)-1.85)-.14;ring=max(ring,abs(p.z)-.2);h=opU2(h,vec2(ring,7.));for(int i=0;i<4;i++){float a=float(i)*PI*.5;vec3 q=p;q.xy=rot(-a)*q.xy;h=opU2(h,vec2(sdBox(q-vec3(1.05,0,0),vec3(.9,.055,.055)),4.));}h=opU2(h,solarPanel(p,vec3(0,0,2.2),vec3(1.45,.035,.55)));return h;}
vec2 stationMap(vec3 p){if(u_station<.5)return station0(p);if(u_station<1.5)return station1(p);if(u_station<2.5)return station2(p);return station3(p);}
vec2 vehicleMap(vec3 p){vec3 q=p-u_vehicle_pos;q=rotateEuler(q,u_vehicle_rot);vec2 h=vec2(99.,0.);if(u_vehicle<.5){h=vec2(sdCapsule(q,vec3(0,0,-.8),vec3(0,0,.45),.42),5.);h=opU2(h,vec2(sdCylinder((q-vec3(0,0,.65)).xzy,.35,.22),4.));}else if(u_vehicle<1.5){h=vec2(sdCylinder(q.xzy,.43,.85),5.);h=opU2(h,vec2(sdCapsule(q,vec3(0,0,-1.15),vec3(0,0,-.7),.34),5.));}else if(u_vehicle<2.5){h=vec2(sdBox(q,vec3(.48,.16,1.2)),5.);h=opU2(h,vec2(sdCapsule(q-vec3(0,.05,-1.25),vec3(0,0,-.5),vec3(0,0,.55),.5),5.));h=opU2(h,vec2(sdBox(q-vec3(.9,0,.05),vec3(.85,.045,.55)),5.));h=opU2(h,vec2(sdBox(q+vec3(.9,0,-.05),vec3(.85,.045,.55)),5.));}else{h=vec2(sdBox(q,vec3(.42,.28,.72)),5.);h=opU2(h,vec2(sdCylinder((q-vec3(0,0,-.9)).xzy,.26,.38),4.));}return h;}
vec2 satelliteMap(vec3 p){vec3 q=p-vec3(-5.5,1.8,-1.5);q.xz=rot(u_time*.06*u_motion)*q.xz;vec2 h=vec2(sdBox(q,vec3(.35,.3,.48)),8.);if(u_satellite<.5){h=opU2(h,solarPanel(q,vec3(1.15,0,0),vec3(.75,.025,.34)));h=opU2(h,solarPanel(q,vec3(-1.15,0,0),vec3(.75,.025,.34)));}else if(u_satellite<1.5){h=opU2(h,vec2(sdSphere(q-vec3(0,.15,.68),.5),9.));h=opU2(h,solarPanel(q,vec3(1.2,0,0),vec3(.7,.025,.3)));}else if(u_satellite<2.5){h=opU2(h,vec2(sdCylinder((q-vec3(0,0,.85)).xzy,.42,.58),9.));h=opU2(h,solarPanel(q,vec3(1.15,0,-.2),vec3(.7,.025,.3)));h=opU2(h,solarPanel(q,vec3(-1.15,0,-.2),vec3(.7,.025,.3)));}else{for(int i=0;i<4;i++){float fi=float(i);vec3 c=vec3((fi-1.5)*.65,sin(fi*2.)*.45,cos(fi*1.7)*.35);h=opU2(h,vec2(sdBox(q-c,vec3(.18)),8.));}}return h;}
vec2 sceneMap(vec3 p){vec2 h=stationMap(p);h=opU2(h,vehicleMap(p));h=opU2(h,satelliteMap(p));return h;}
vec3 normalMap(vec3 p){float e=.0015;return normalize(vec3(sceneMap(p+vec3(e,0,0)).x-sceneMap(p-vec3(e,0,0)).x,sceneMap(p+vec3(0,e,0)).x-sceneMap(p-vec3(0,e,0)).x,sceneMap(p+vec3(0,0,e)).x-sceneMap(p-vec3(0,0,e)).x));}
bool earthHit(vec3 ro,vec3 rd,out float t,out vec3 n){vec3 ce=vec3(0.,-17.,-29.);float r=14.;vec3 oc=ro-ce;float b=dot(oc,rd),c=dot(oc,oc)-r*r,h=b*b-c;if(h<0.)return false;t=-b-sqrt(h);if(t<0.)return false;n=normalize(ro+rd*t-ce);return true;}
vec3 stars(vec3 rd){vec2 p=rd.xy/(abs(rd.z)+1.35);float h=hash21(floor(p*(620.+u_quality*580.)));float star=step(mix(.9974,.9958,u_quality),h)*pow(h,24.);float neb=fbm(vec3(p*3.2,u_time*.004*u_motion))*.055*u_quality;return vec3(.003,.007,.018)+vec3(.45,.62,1.)*star+vec3(.055,.018,.12)*neb;}
vec3 background(vec3 ro,vec3 rd){vec3 col=stars(rd);float t;vec3 n;if(earthHit(ro,rd,t,n)){vec3 sun=normalize(vec3(-.45,.72,.35));float diff=max(0.,dot(n,sun));float land=smoothstep(.51,.7,fbm(n*5.3));float cloud=smoothstep(.61,.78,fbm(n*12.+vec3(u_time*.008*u_motion,0,0)));vec3 base=mix(vec3(.018,.12,.34),vec3(.045,.27,.13),land);base=mix(base,vec3(.85,.9,.96),cloud*.48);float night=1.-smoothstep(-.05,.2,dot(n,sun));float cities=step(.82,fbm(n*48.))*land*night;col=base*(.08+1.02*diff)+vec3(1.,.55,.17)*cities*.7;float rim=pow(1.-max(0.,dot(-rd,n)),3.);col+=vec3(.09,.45,1.)*rim*(.65+.45*u_quality);}return col;}
vec3 material(float id,vec3 p,vec3 n,vec3 rd){vec3 sun=normalize(vec3(-.5,.75,.38));float diff=max(.04,dot(n,sun));float spec=pow(max(0.,dot(reflect(-sun,n),-rd)),mix(24.,70.,u_quality));float fres=pow(1.-max(0.,dot(n,-rd)),3.);vec3 c;if(id<1.5)c=vec3(.64,.69,.72);else if(id<2.5)c=vec3(.035,.13,.3);else if(id<3.5)c=vec3(.025,.22,.46);else if(id<4.5)c=vec3(.28,.31,.34);else if(id<5.5)c=vec3(.78,.82,.84);else if(id<6.5)c=vec3(.14,.38,.55);else if(id<7.5)c=vec3(.18,.48,.4);else if(id<8.5)c=vec3(.7,.55,.24);else c=vec3(.55,.62,.7);c*=.2+diff*.95;c+=spec*vec3(.8,.9,1.)*.5+fres*vec3(.08,.3,.55)*.35;return c;}
vec3 renderInterior(vec3 ro,vec3 rd){float t=0.;vec3 col=vec3(.004,.009,.015);for(int i=0;i<96;i++){vec3 p=ro+rd*t;float wall=abs(length(p.xy)-1.18);float ribs=abs(fract((p.z+20.)*.36)-.5)-.035;float panels=min(abs(abs(p.x)-.88)-.09,abs(abs(p.y)-.88)-.09);float d=max(-wall,min(ribs,panels));if(d<.002){vec3 n=normalize(vec3(p.x,p.y,0.));float light=.25+.75*max(0.,dot(n,normalize(vec3(.2,.75,.4))));float stripe=step(.82,fract((p.z+12.)*.22));col=mix(vec3(.35,.42,.46),vec3(.08,.34,.47),stripe)*light;break;}t+=max(.012,d*.7);if(t>30.)break;}float dust=0.;vec2 uv=v_uv-.5;for(int i=0;i<20;i++){float fi=float(i);vec2 q=fract(vec2(hash21(vec2(fi,1.)),hash21(vec2(fi,9.)))+vec2(.016,-.012)*u_time*u_motion*(.4+fi*.04))-.5;dust+=.004/(length(uv-q)+.008);}col+=vec3(.45,.72,.92)*dust*.08;return col;}
void camera(out vec3 ro,out vec3 ta){float dist=7.2/u_zoom;if(u_camera<.5){ro=vec3(0,.7,dist);ro.xz=rot(u_yaw)*ro.xz;ro.yz=rot(u_pitch)*ro.yz;ta=vec3(0,0,0);}else if(u_camera<1.5){ro=u_vehicle_pos+vec3(0,.1,1.3);ta=ro+normalize(vec3(sin(u_yaw)*cos(u_pitch),sin(u_pitch),-cos(u_yaw)*cos(u_pitch)));}else if(u_camera<2.5){ro=u_vehicle_pos+vec3(0,.05,-.2);ta=ro+normalize(vec3(sin(u_yaw)*.25,sin(u_pitch)*.25,-1.));}else if(u_camera<3.5){ro=vec3(.75,-.42,.18);ta=vec3(0,-14.,-25.);}else if(u_camera<4.5){ro=vec3(0,0,5.2);ta=ro+normalize(vec3(sin(u_yaw),sin(u_pitch),-cos(u_yaw)));}else if(u_camera<5.5){ro=vec3(2.6,1.1,3.5);ta=vec3(.5,.2,0.);}else if(u_camera<6.5){ro=u_vehicle_pos+vec3(0,0,1.5);ta=vec3(0,0,0);}else if(u_camera<7.5){ro=vec3(3.1,1.7,2.4);ta=vec3(.8,0,0);}else if(u_camera<8.5){ro=vec3(-5.5,2.1,2.8);ta=vec3(-5.5,1.8,-1.5);}else if(u_camera<9.5){ro=u_vehicle_pos+vec3(0,.4,.2);ta=u_vehicle_pos+vec3(0,.2,-1.8);}else{float a=u_time*.09*u_motion;ro=vec3(cos(a)*8.,2.1+sin(a*.7),sin(a)*8.);ta=vec3(0,0,0);}}
void main(){vec2 uv=(gl_FragCoord.xy*2.-u_resolution.xy)/min(u_resolution.x,u_resolution.y);vec3 ro,ta;camera(ro,ta);if(u_camera>3.5&&u_camera<4.5){vec3 ww=normalize(ta-ro),uu=normalize(cross(ww,vec3(0,1,0))),vv=cross(uu,ww);vec3 rd=normalize(uu*uv.x*.72+vv*uv.y*.72+ww);vec3 col=renderInterior(ro,rd);col=pow(max(col,0.),vec3(.82));outColor=vec4(col,1);return;}vec3 ww=normalize(ta-ro),uu=normalize(cross(ww,vec3(0,1,0))),vv=cross(uu,ww);uu.xy=rot(u_roll)*uu.xy;vec3 rd=normalize(uu*uv.x*.82+vv*uv.y*.82+ww);vec3 col=background(ro,rd);float t=0.,mat=0.;bool hit=false;float maxSteps=mix(50.,116.,u_quality);for(int i=0;i<120;i++){if(float(i)>maxSteps)break;vec3 p=ro+rd*t;vec2 h=sceneMap(p);if(h.x<.0018){hit=true;mat=h.y;break;}t+=h.x*.8;if(t>42.)break;}if(hit){vec3 p=ro+rd*t,n=normalMap(p);col=material(mat,p,n,rd);float shadow=0.,st=.03;for(int i=0;i<18;i++){float h=sceneMap(p+n*.01+normalize(vec3(-.5,.75,.38))*st).x;shadow=max(shadow,.07-h/st);st+=clamp(h,.025,.35);}col*=1.-clamp(shadow,0.,.55);}float thruster=(1.-smoothstep(.0,.3,u_fuel))*0.;float plume=0.;if(u_camera<3.5||u_camera>4.5){vec3 axis=normalize(vec3(0,0,1));vec3 v=u_vehicle_pos+vec3(0,0,1.);float d=length(cross(v-ro,rd));plume=exp(-d*95.)*smoothstep(.02,.35,length(u_vehicle_pos))*u_quality;}col+=plume*vec3(.2,.65,1.)*.18;float debris=0.;if(u_fault>.5){for(int i=0;i<14;i++){float fi=float(i);vec3 pp=vec3(sin(fi*6.3),cos(fi*4.7),fract(fi*.37+u_time*.05))*vec3(2.5,1.8,2.8);float d=length(cross(pp-ro,rd));debris+=exp(-d*150.)*.04;}col+=debris*vec3(1.,.48,.16);}float vign=1.-dot(v_uv-.5,v_uv-.5)*.62;col*=vign;col=pow(max(col,0.),vec3(.82));outColor=vec4(col,1.);}`;

const clamp=(value,min,max)=>Math.min(max,Math.max(min,value));
const CAMERA_INDEX={
  'station-orbit':0,'free-flight':1,cockpit:2,cupola:3,interior:4,eva:5,'docking-port':6,'robotic-arm':7,'satellite-chase':8,'payload-bay':9,cinematic:10
};
export class StationRemasterSceneRenderer {
  constructor(canvas,settingsStore,input,experience,{onTelemetry,onInput,onContextState}={}){this.canvas=canvas;this.settingsStore=settingsStore;this.input=input;this.experience=experience;this.onTelemetry=onTelemetry;this.onInput=onInput;this.onContextState=onContextState;this.gl=null;this.ctx=null;this.program=null;this.vao=null;this.buffer=null;this.raf=0;this.resizeObserver=null;this.last=performance.now();this.startedAt=this.last;this.fpsClock=this.last;this.frames=0;this.fps=0;this.flight={position:{x:0,y:0,z:18},rotation:{yaw:0,pitch:0,roll:0},fuelPercent:100,state:'FREE'};this.stationVariant=0;this.vehicleVariant=0;this.satelliteVariant=0;this.destroyed=false;this.resize=this.resize.bind(this);this.onLost=e=>this.contextLost(e);this.onRestored=()=>this.contextRestored();}
  start(){this.destroyed=false;if(!this.startWebGL())this.ctx=this.canvas.getContext('2d');this.canvas.addEventListener('webglcontextlost',this.onLost);this.canvas.addEventListener('webglcontextrestored',this.onRestored);if('ResizeObserver'in globalThis){this.resizeObserver=new ResizeObserver(()=>this.resize());this.resizeObserver.observe(this.canvas);}else addEventListener('resize',this.resize);this.resize();this.last=performance.now();this.raf=requestAnimationFrame(now=>this.loop(now));return Boolean(this.gl);}
  startWebGL(){const profile=this.settingsStore.getProfile();const gl=this.canvas.getContext('webgl2',{antialias:false,alpha:false,powerPreference:profile.id==='experience'?'high-performance':'low-power'});if(!gl)return false;const compile=(type,source)=>{const shader=gl.createShader(type);gl.shaderSource(shader,source);gl.compileShader(shader);if(!gl.getShaderParameter(shader,gl.COMPILE_STATUS)){const m=gl.getShaderInfoLog(shader);gl.deleteShader(shader);throw new Error(m);}return shader;};try{const vs=compile(gl.VERTEX_SHADER,vertexSource),fs=compile(gl.FRAGMENT_SHADER,fragmentSource),program=gl.createProgram();gl.attachShader(program,vs);gl.attachShader(program,fs);gl.linkProgram(program);gl.deleteShader(vs);gl.deleteShader(fs);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw new Error(gl.getProgramInfoLog(program));const vao=gl.createVertexArray(),buffer=gl.createBuffer();gl.bindVertexArray(vao);gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,3,-1,-1,3]),gl.STATIC_DRAW);const loc=gl.getAttribLocation(program,'a_position');gl.enableVertexAttribArray(loc);gl.vertexAttribPointer(loc,2,gl.FLOAT,false,0,0);this.gl=gl;this.program=program;this.vao=vao;this.buffer=buffer;return true;}catch(error){console.warn('Estação remaster WebGL2 indisponível.',error);return false;}}
  contextLost(event){event.preventDefault();cancelAnimationFrame(this.raf);this.onContextState?.('lost');}
  contextRestored(){this.gl=null;this.program=null;this.vao=null;this.buffer=null;if(this.startWebGL()){this.resize();this.last=performance.now();this.raf=requestAnimationFrame(now=>this.loop(now));this.onContextState?.('restored');}}
  setVariants({station=0,vehicle=0,satellite=0}={}){this.stationVariant=station;this.vehicleVariant=vehicle;this.satelliteVariant=satellite;}
  setFlight(telemetry){this.flight={...this.flight,...telemetry};}
  resetCamera(){this.experience.yaw=.25;this.experience.pitch=-.08;this.experience.roll=0;this.experience.zoom=1;}
  requestFullscreen(){const root=this.canvas.closest('.station-remaster-stage')||this.canvas;if(document.fullscreenElement)return document.exitFullscreen?.();return root.requestFullscreen?.();}
  resize(){const rect=this.canvas.getBoundingClientRect(),profile=this.settingsStore.getProfile(),dpr=Math.min(profile.id==='experience'?1.65:profile.id==='balanced'?1.12:.7,devicePixelRatio||1);this.canvas.width=Math.max(1,Math.round(rect.width*dpr));this.canvas.height=Math.max(1,Math.round(rect.height*dpr));this.gl?.viewport(0,0,this.canvas.width,this.canvas.height);}
  loop(now){if(this.destroyed)return;const dt=Math.min(.05,(now-this.last)/1000||.016);this.last=now;const input=this.input?.sample?.()??{};this.experience.update(dt,input);this.onInput?.(input,dt);this.draw(now);this.frames++;if(now-this.fpsClock>=500){this.fps=Math.round(this.frames*1000/(now-this.fpsClock));this.frames=0;this.fpsClock=now;this.onTelemetry?.({fps:this.fps,camera:this.experience.cameraId,profile:this.settingsStore.getProfile().id,webgl:Boolean(this.gl),resolution:`${this.canvas.width}×${this.canvas.height}`});}this.raf=requestAnimationFrame(t=>this.loop(t));}
  uniform1(name,value){const loc=this.gl.getUniformLocation(this.program,name);if(loc!==null)this.gl.uniform1f(loc,value);}uniform3(name,v){const loc=this.gl.getUniformLocation(this.program,name);if(loc!==null)this.gl.uniform3f(loc,v.x||0,v.y||0,v.z||0);}
  draw(now){if(this.gl)this.drawWebGL(now);else this.drawFallback(now);}
  drawWebGL(now){const gl=this.gl,settings=this.settingsStore.get(),profile=this.settingsStore.getProfile(),s=this.experience.snapshot(),f=this.flight,elapsed=(now-this.startedAt)/1000;gl.disable(gl.DEPTH_TEST);gl.clearColor(0,0,0,1);gl.clear(gl.COLOR_BUFFER_BIT);gl.useProgram(this.program);gl.bindVertexArray(this.vao);gl.uniform2f(gl.getUniformLocation(this.program,'u_resolution'),this.canvas.width,this.canvas.height);this.uniform1('u_time',settings.reducedMotion?0:elapsed);this.uniform1('u_yaw',s.yaw);this.uniform1('u_pitch',s.pitch);this.uniform1('u_roll',s.roll);this.uniform1('u_zoom',s.zoom);this.uniform1('u_quality',profile.id==='performance'?.12:profile.id==='experience'?1:.58);this.uniform1('u_motion',settings.reducedMotion?0:profile.motionFactor);this.uniform1('u_station',this.stationVariant);this.uniform1('u_vehicle',this.vehicleVariant);this.uniform1('u_satellite',this.satelliteVariant);this.uniform1('u_camera',CAMERA_INDEX[s.cameraId]??0);this.uniform1('u_dock',clamp(1-(f.distanceM||18)/18,0,1));this.uniform1('u_fuel',(f.fuelPercent||0)/100);this.uniform1('u_fault',f.collision?1:0);this.uniform1('u_orbit',elapsed*.01);this.uniform3('u_vehicle_pos',{x:(f.position?.x||0)*.18,y:(f.position?.y||0)*.18,z:clamp((f.position?.z||18)*.18,-2,4)});this.uniform3('u_vehicle_rot',f.rotation||{});gl.drawArrays(gl.TRIANGLES,0,3);}
  drawFallback(now){const ctx=this.ctx;if(!ctx)return;const w=this.canvas.width,h=this.canvas.height,s=this.experience.snapshot(),f=this.flight,t=(now-this.startedAt)/1000;ctx.clearRect(0,0,w,h);ctx.fillStyle='#020611';ctx.fillRect(0,0,w,h);for(let i=0;i<120;i++){const x=(Math.sin(i*91.3)*.5+.5)*w,y=(Math.sin(i*37.2+1.4)*.5+.5)*h;ctx.fillStyle=`rgba(210,235,255,${.18+(i%6)*.08})`;ctx.fillRect(x,y,1+(i%4===0),1+(i%4===0));}const er=Math.min(w,h)*.33,ex=w*.73,ey=h*.78;const eg=ctx.createRadialGradient(ex-er*.3,ey-er*.35,er*.05,ex,ey,er);eg.addColorStop(0,'#7bd4ff');eg.addColorStop(.48,'#145da4');eg.addColorStop(1,'#031326');ctx.fillStyle=eg;ctx.beginPath();ctx.arc(ex,ey,er,0,Math.PI*2);ctx.fill();ctx.save();ctx.translate(w*.47,h*.43);ctx.rotate(s.yaw*.16);const scale=Math.min(w,h)*.12/s.zoom;ctx.fillStyle='#c7ced1';ctx.fillRect(-scale*2.2,-scale*.16,scale*4.4,scale*.32);ctx.fillRect(-scale*.28,-scale*2.1,scale*.56,scale*4.2);ctx.fillStyle='#123d78';for(const side of [-1,1])for(const z of [-1,1])ctx.fillRect(side*scale*1.55-scale*.8,z*scale*.95-scale*.36,scale*1.6,scale*.72);if(this.stationVariant===3){ctx.strokeStyle='#74ffc3';ctx.lineWidth=scale*.16;ctx.beginPath();ctx.arc(0,0,scale*1.65,0,Math.PI*2);ctx.stroke();}ctx.restore();const vx=w*.47+(f.position?.x||0)*4,vy=h*.43+(f.position?.y||0)*4;ctx.fillStyle='#f0f3f4';ctx.beginPath();ctx.ellipse(vx,vy,18,12,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='rgba(110,225,255,.75)';ctx.font=`${Math.max(11,w/78)}px ui-monospace`;ctx.fillText(`FALLBACK 2D · ${s.cameraId.toUpperCase()} · ${f.state||'FREE'} · ${Math.round(t)}s`,18,h-18);}
  destroy(){this.destroyed=true;cancelAnimationFrame(this.raf);this.resizeObserver?.disconnect();if(!this.resizeObserver)removeEventListener('resize',this.resize);this.canvas?.removeEventListener('webglcontextlost',this.onLost);this.canvas?.removeEventListener('webglcontextrestored',this.onRestored);if(this.gl){if(this.buffer)this.gl.deleteBuffer(this.buffer);if(this.vao)this.gl.deleteVertexArray(this.vao);if(this.program)this.gl.deleteProgram(this.program);}this.gl=null;this.ctx=null;this.program=null;this.vao=null;this.buffer=null;}
}
