const clamp=(v,min,max)=>Math.min(max,Math.max(min,v));
const hexAlpha=(hex,alpha)=>{const clean=String(hex||'#69ddff').replace('#','');const value=parseInt(clean.length===3?clean.split('').map(x=>x+x).join(''):clean,16);return `rgba(${value>>16},${value>>8&255},${value&255},${alpha})`;};
export class TechnicalCutawayRenderer{
  constructor(canvas,settingsStore,{onSelect=()=>{},onDiagnostics=()=>{}}={}){this.canvas=canvas;this.settingsStore=settingsStore;this.onSelect=onSelect;this.onDiagnostics=onDiagnostics;this.ctx=null;this.system=null;this.snapshot=null;this.raf=0;this.last=0;this.yaw=-.3;this.pitch=.18;this.zoom=1;this.drag=null;this.width=0;this.height=0;this.dpr=1;this.points=[];this.onResize=()=>this.resize();this.onPointerDown=e=>this.pointerDown(e);this.onPointerMove=e=>this.pointerMove(e);this.onPointerUp=()=>this.drag=null;this.onWheel=e=>{e.preventDefault();this.zoom=clamp(this.zoom-e.deltaY*.0008,.65,1.75);};}
  start(){this.ctx=this.canvas.getContext('2d');if(!this.ctx)throw new Error('Canvas 2D indisponível.');this.canvas.addEventListener('pointerdown',this.onPointerDown);this.canvas.addEventListener('pointermove',this.onPointerMove);this.canvas.addEventListener('pointerup',this.onPointerUp);this.canvas.addEventListener('pointercancel',this.onPointerUp);this.canvas.addEventListener('wheel',this.onWheel,{passive:false});addEventListener('resize',this.onResize,{passive:true});this.resize();this.last=performance.now();this.raf=requestAnimationFrame(t=>this.loop(t));}
  setSystem(system){this.system=system;this.points=[];}
  setState(snapshot){this.snapshot=snapshot;}
  resize(){const rect=this.canvas.getBoundingClientRect();this.dpr=Math.min(2,devicePixelRatio||1);this.width=Math.max(1,Math.floor(rect.width*this.dpr));this.height=Math.max(1,Math.floor(rect.height*this.dpr));if(this.canvas.width!==this.width||this.canvas.height!==this.height){this.canvas.width=this.width;this.canvas.height=this.height;}this.onDiagnostics({resolution:`${this.width}×${this.height}`,renderer:'canvas2d'});}
  loop(now){const dt=Math.min(.05,(now-this.last)/1000||.016);this.last=now;if(!this.drag&&!this.settingsStore?.get?.().reducedMotion)this.yaw+=dt*.035;this.draw(now*.001);this.raf=requestAnimationFrame(t=>this.loop(t));}
  pointerDown(event){this.drag={x:event.clientX,y:event.clientY,yaw:this.yaw,pitch:this.pitch};this.canvas.setPointerCapture?.(event.pointerId);const rect=this.canvas.getBoundingClientRect(),x=(event.clientX-rect.left)*this.dpr,y=(event.clientY-rect.top)*this.dpr;const hit=[...this.points].reverse().find(point=>Math.hypot(point.x-x,point.y-y)<point.r);if(hit)this.onSelect(hit.id);}
  pointerMove(event){if(!this.drag)return;this.yaw=this.drag.yaw+(event.clientX-this.drag.x)*.008;this.pitch=clamp(this.drag.pitch+(event.clientY-this.drag.y)*.006,-.75,.75);}
  project([x,y,z],explode=1){const cy=Math.cos(this.yaw),sy=Math.sin(this.yaw),cp=Math.cos(this.pitch),sp=Math.sin(this.pitch);let px=x*explode,pz=z*explode,py=y*explode;const rx=px*cy-pz*sy,rz=px*sy+pz*cy,ry=py*cp-rz*sp,depth=py*sp+rz*cp;const scale=Math.min(this.width,this.height)*.19*this.zoom/(1+depth*.08);return {x:this.width*.5+rx*scale,y:this.height*.51-ry*scale,depth,scale};}
  draw(time){const c=this.ctx;if(!c)return;const profile=this.settingsStore?.getProfile?this.settingsStore.getProfile():{id:'balanced'},w=this.width,h=this.height,system=this.system,snap=this.snapshot;c.fillStyle='#020711';c.fillRect(0,0,w,h);this.drawBackdrop(profile.id==='performance'?0:time);if(!system||!snap){c.fillStyle='#9edff0';c.font=`${18*this.dpr}px system-ui`;c.fillText('Preparando modelo técnico…',30*this.dpr,50*this.dpr);return;}const mode=snap.viewMode,explode=mode==='exploded'?1.75:1,alpha=mode==='xray'?.18:mode==='cutaway'?.52:.78;this.points=[];this.drawConnections(system,explode,mode);this.drawCore(system,mode,alpha);const sorted=system.subsystems.map(item=>({item,p:this.project(item.position,explode)})).sort((a,b)=>a.p.depth-b.p.depth);for(const entry of sorted)this.drawSubsystem(entry.item,entry.p,mode,snap.selectedSubsystemId===entry.item.id,snap.fault?.target===entry.item.id);this.drawLabels(system,snap);}
  drawBackdrop(time){const c=this.ctx,w=this.width,h=this.height;c.save();c.strokeStyle='rgba(74,174,215,.08)';c.lineWidth=1*this.dpr;const step=48*this.dpr,offset=(time*10*this.dpr)%step;for(let x=-step+offset;x<w+step;x+=step){c.beginPath();c.moveTo(x,0);c.lineTo(x,h);c.stroke();}for(let y=-step+offset;y<h+step;y+=step){c.beginPath();c.moveTo(0,y);c.lineTo(w,y);c.stroke();}const grd=c.createRadialGradient(w*.5,h*.48,0,w*.5,h*.48,Math.min(w,h)*.58);grd.addColorStop(0,'rgba(37,124,162,.18)');grd.addColorStop(1,'rgba(0,0,0,0)');c.fillStyle=grd;c.fillRect(0,0,w,h);c.restore();}
  drawCore(system,mode,alpha){const c=this.ctx,w=this.width,h=this.height,p=this.project([0,0,0]),size=Math.min(w,h)*.21*this.zoom;c.save();c.translate(p.x,p.y);c.rotate(this.yaw*.18);c.shadowColor=hexAlpha(system.color,.35);c.shadowBlur=24*this.dpr;c.fillStyle=hexAlpha(system.color,alpha*.16);c.strokeStyle=hexAlpha(system.color,.7);c.lineWidth=2*this.dpr;const shape=system.shape;
    c.beginPath();
    if(shape==='capsule'){c.moveTo(0,-size*.65);c.lineTo(size*.48,size*.42);c.quadraticCurveTo(0,size*.7,-size*.48,size*.42);c.closePath();}
    else if(shape==='rover'){c.roundRect(-size*.6,-size*.27,size*1.2,size*.55,12*this.dpr);}
    else if(shape==='shuttle'){c.moveTo(size*.72,0);c.lineTo(-size*.45,-size*.24);c.lineTo(-size*.12,0);c.lineTo(-size*.45,size*.24);c.closePath();}
    else if(shape==='station'){c.rect(-size*.55,-size*.12,size*1.1,size*.24);c.moveTo(-size*.15,-size*.5);c.lineTo(-size*.15,size*.5);c.moveTo(size*.15,-size*.5);c.lineTo(size*.15,size*.5);}
    else{c.roundRect(-size*.42,-size*.32,size*.84,size*.64,14*this.dpr);c.moveTo(-size*.42,0);c.lineTo(-size*.95,0);c.moveTo(size*.42,0);c.lineTo(size*.95,0);}
    if(mode==='cutaway'){c.save();c.clip();c.fillRect(-size,0,size*2,size);c.restore();}else c.fill();c.stroke();
    if(mode==='xray'){c.setLineDash([7*this.dpr,5*this.dpr]);c.strokeStyle=hexAlpha(system.color,.45);c.stroke();}
    c.restore();}
  drawConnections(system,explode,mode){const c=this.ctx,center=this.project([0,0,0]);c.save();c.lineWidth=(mode==='xray'?2:1)*this.dpr;c.setLineDash(mode==='xray'?[5*this.dpr,5*this.dpr]:[]);for(const item of system.subsystems){const p=this.project(item.position,explode);c.strokeStyle=hexAlpha(system.color,mode==='xray'?.65:.22);c.beginPath();c.moveTo(center.x,center.y);c.lineTo(p.x,p.y);c.stroke();}c.restore();}
  drawSubsystem(item,p,mode,selected,fault){const c=this.ctx,r=(selected?19:14)*this.dpr*this.zoom;c.save();c.shadowColor=fault?'rgba(255,76,100,.85)':hexAlpha(this.system.color,selected?.85:.3);c.shadowBlur=(selected?24:10)*this.dpr;c.fillStyle=fault?'rgba(136,18,41,.78)':selected?hexAlpha(this.system.color,.42):mode==='xray'?hexAlpha(this.system.color,.18):'rgba(7,27,43,.88)';c.strokeStyle=fault?'#ff6880':selected?this.system.color:hexAlpha(this.system.color,.55);c.lineWidth=(selected?3:1.5)*this.dpr;c.beginPath();c.arc(p.x,p.y,r,0,Math.PI*2);c.fill();c.stroke();c.fillStyle='#edfbff';c.font=`900 ${11*this.dpr*this.zoom}px system-ui`;c.textAlign='center';c.textBaseline='middle';c.fillText(item.icon,p.x,p.y);c.font=`700 ${9*this.dpr}px system-ui`;c.fillStyle=selected?'#fff':'#9fc4d0';c.fillText(item.name,p.x,p.y+r+13*this.dpr);c.restore();this.points.push({id:item.id,x:p.x,y:p.y,r:r+12*this.dpr});}
  drawLabels(system,snap){const c=this.ctx,w=this.width,h=this.height;c.save();c.textAlign='left';c.fillStyle=hexAlpha(system.color,.75);c.font=`800 ${10*this.dpr}px ui-monospace`;c.fillText(`${system.name.toUpperCase()} · ${snap.viewMode.toUpperCase()}`,22*this.dpr,h-30*this.dpr);c.fillStyle='rgba(194,226,236,.62)';c.font=`${9*this.dpr}px ui-monospace`;c.fillText('Arraste para girar · toque em um ponto para inspecionar · roda/pinça para zoom',22*this.dpr,h-14*this.dpr);c.restore();}
  destroy(){cancelAnimationFrame(this.raf);removeEventListener('resize',this.onResize);this.canvas?.removeEventListener('pointerdown',this.onPointerDown);this.canvas?.removeEventListener('pointermove',this.onPointerMove);this.canvas?.removeEventListener('pointerup',this.onPointerUp);this.canvas?.removeEventListener('pointercancel',this.onPointerUp);this.canvas?.removeEventListener('wheel',this.onWheel);this.ctx=null;this.system=null;this.snapshot=null;this.points=[];}
}
