export class TechnologyNetworkRenderer {
  constructor({canvas,reducedMotion=false}){this.canvas=canvas;this.ctx=canvas?canvas.getContext('2d'):null;this.reducedMotion=reducedMotion;this.nodes=[];this.activeId='sensor';this.raf=0;this.resizeObserver=null;this.startAt=performance.now();}
  start(layers=[]){if(!this.ctx)return false;this.nodes=layers.map((item,index)=>({...item,index}));this.resize();if(typeof ResizeObserver!=='undefined'){this.resizeObserver=new ResizeObserver(()=>this.resize());this.resizeObserver.observe(this.canvas);}this.loop();return true;}
  setActive(id){this.activeId=id;}
  resize(){const rect=this.canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2);this.canvas.width=Math.max(1,Math.floor(rect.width*dpr));this.canvas.height=Math.max(1,Math.floor(rect.height*dpr));this.ctx.setTransform(dpr,0,0,dpr,0,0);}
  loop(){const draw=now=>{this.draw(now);if(!this.reducedMotion)this.raf=requestAnimationFrame(draw);};this.raf=requestAnimationFrame(draw);}
  draw(now){const ctx=this.ctx,w=this.canvas.clientWidth,h=this.canvas.clientHeight;ctx.clearRect(0,0,w,h);const gradient=ctx.createRadialGradient(w*.5,h*.45,10,w*.5,h*.45,Math.max(w,h)*.65);gradient.addColorStop(0,'rgba(30,105,170,.25)');gradient.addColorStop(1,'rgba(2,7,20,0)');ctx.fillStyle=gradient;ctx.fillRect(0,0,w,h);const margin=Math.min(70,w*.08),usable=Math.max(1,w-margin*2),y=h*.55;ctx.lineWidth=2;ctx.strokeStyle='rgba(92,220,255,.22)';ctx.beginPath();ctx.moveTo(margin,y);ctx.lineTo(w-margin,y);ctx.stroke();const t=(now-this.startAt)/1500;
    this.nodes.forEach((node,index)=>{const x=margin+usable*(index/Math.max(1,this.nodes.length-1)),active=node.id===this.activeId,pulse=(Math.sin(t-index*.55)+1)/2;ctx.beginPath();ctx.arc(x,y,active?15:10,0,Math.PI*2);ctx.fillStyle=active?'rgba(103,236,255,.92)':`rgba(81,151,215,${.36+pulse*.18})`;ctx.fill();ctx.strokeStyle=active?'#e9fdff':'rgba(113,221,255,.44)';ctx.stroke();ctx.fillStyle=active?'#ffffff':'#9fc3d6';ctx.font=`700 ${active?12:10}px system-ui`;ctx.textAlign='center';ctx.fillText(String(index+1).padStart(2,'0'),x,y+4);if(index<this.nodes.length-1){const px=x+(usable/Math.max(1,this.nodes.length-1))*((t+index*.19)%1);ctx.beginPath();ctx.arc(px,y,3,0,Math.PI*2);ctx.fillStyle='#74e9ff';ctx.fill();}}
    );}
  destroy(){cancelAnimationFrame(this.raf);this.resizeObserver?.disconnect();this.nodes=[];this.ctx?.clearRect(0,0,this.canvas.width,this.canvas.height);}
}
