const VS=`#version 300 es
precision highp float;out vec2 vUv;void main(){vec2 p=vec2((gl_VertexID<<1)&2,gl_VertexID&2);vUv=p;gl_Position=vec4(p*2.-1.,0.,1.);}`;
const FS=`#version 300 es
precision highp float;in vec2 vUv;out vec4 outColor;uniform vec2 u_resolution;uniform float u_time;uniform float u_yaw;uniform float u_pitch;uniform float u_zoom;uniform float u_motion;uniform int u_mode;uniform int u_steps;uniform float u_particles;
float h(vec3 p){p=fract(p*.1031);p+=dot(p,p.yzx+33.33);return fract((p.x+p.y)*p.z);}float n(vec3 p){vec3 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(mix(h(i),h(i+vec3(1,0,0)),f.x),mix(h(i+vec3(0,1,0)),h(i+vec3(1,1,0)),f.x),f.y),mix(mix(h(i+vec3(0,0,1)),h(i+vec3(1,0,1)),f.x),mix(h(i+vec3(0,1,1)),h(i+vec3(1,1,1)),f.x),f.y),f.z);}float fbm(vec3 p){float s=0.,a=.5;for(int i=0;i<5;i++){s+=a*n(p);p=p*2.03+1.7;a*=.5;}return s;}
mat2 rot(float a){float c=cos(a),s=sin(a);return mat2(c,-s,s,c);}float sdSphere(vec3 p,float r){return length(p)-r;}float sdTorus(vec3 p,vec2 t){vec2 q=vec2(length(p.xz)-t.x,p.y);return length(q)-t.y;}
void main(){vec2 p=(vUv*2.-1.);p.x*=u_resolution.x/max(1.,u_resolution.y);vec3 rd=normalize(vec3(p/u_zoom,1.45));rd.xz*=rot(u_yaw);rd.yz*=rot(u_pitch);vec3 ro=vec3(0,0,-3.2);float t=u_time*u_motion;vec3 col=vec3(.002,.004,.014);
float star=0.;for(int i=0;i<4;i++){vec3 q=rd*(90.+float(i)*43.);vec3 cell=floor(q);float s=h(cell);star+=step(.994-float(i)*.0015,s)*pow(max(0.,1.-length(fract(q)-.5)*2.),8.)*(.5+.5*sin(t*(.6+s*2.)+s*30.));}col+=vec3(.62,.79,1.)*star*u_particles;
if(u_mode==0){vec3 q=rd*2.2+vec3(sin(t*.03)*.2,0,0);float cloud=0.;float trans=1.;for(int i=0;i<64;i++){if(i>=u_steps)break;float z=float(i)*.075;vec3 sp=ro+rd*z;float d=fbm(sp*1.15+vec3(0,0,t*.018));float den=smoothstep(.54,.78,d)*exp(-length(sp.xy)*.3);vec3 c=mix(vec3(.08,.2,.7),vec3(.95,.16,.55),fbm(sp*.7+2.));cloud+=den*trans*.08;col+=c*den*trans*.055;trans*=1.-den*.045;}col+=vec3(.2,.42,1.)*cloud*.25;}
else if(u_mode==1){vec2 q=p;float r=length(q);float a=atan(q.y,q.x)+r*8.+t*.025;float disk=exp(-r*2.4)*(.45+.55*pow(.5+.5*cos(a*2.),3.));float core=exp(-r*r*44.);col+=mix(vec3(.2,.32,.9),vec3(1.,.55,.25),r)*disk*.9+vec3(1.,.88,.68)*core*2.;}
else if(u_mode==2){float ring=exp(-abs(length(p)-.42)*30.);float blast=fbm(vec3(normalize(vec3(p,1.))*4.+t*.04));col+=mix(vec3(.12,.55,1.),vec3(1.,.2,.08),blast)*ring*(.7+blast);col+=vec3(.8,.9,1.)*exp(-dot(p,p)*18.);}
else if(u_mode==3){float ring=exp(-abs(length(p)-.28)*52.);float lens=1./(1.+dot(p,p)*25.);col+=vec3(1.,.45,.08)*ring*(1.4+.6*sin(atan(p.y,p.x)*4.+t));col*=smoothstep(.09,.15,length(p));col+=vec3(.18,.34,.8)*lens*.18;}
else {vec3 q=vec3(p,0);q.xy*=rot(t*.12);float body=smoothstep(.035,0.,abs(sdTorus(q,vec2(.42,.025))));float dish=smoothstep(.025,0.,abs(sdSphere(q-vec3(0,.08,0),.16)));col+=vec3(.2,.65,1.)*body+vec3(.82,.9,1.)*dish*.7;}
float vig=smoothstep(1.35,.18,length(p*.72));col*=.48+.52*vig;col=pow(max(col,0.),vec3(.82));outColor=vec4(col,1);}`;
function shader(gl,type,src){const s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS)){const m=gl.getShaderInfoLog(s);gl.deleteShader(s);throw new Error(m);}return s;}
export class UniverseSceneRenderer{
  constructor(canvas,settingsStore,{onDiagnostics=()=>{}}={}){this.canvas=canvas;this.settingsStore=settingsStore;this.onDiagnostics=onDiagnostics;this.gl=null;this.program=null;this.raf=0;this.running=false;this.yaw=0;this.pitch=0;this.zoom=1;this.mode='nebula';this.drag=null;this.fallback=false;this.contextLost=false;this.lastDiag=0;this.resizeObserver=typeof ResizeObserver!=='undefined'?new ResizeObserver(()=>this.resize()):null;this.onResize=()=>this.resize();this.onDown=e=>{this.drag={x:e.clientX,y:e.clientY,yaw:this.yaw,pitch:this.pitch};this.canvas.setPointerCapture?.(e.pointerId);};this.onMove=e=>{if(!this.drag)return;this.yaw=this.drag.yaw+(e.clientX-this.drag.x)*.006;this.pitch=Math.max(-1.15,Math.min(1.15,this.drag.pitch+(e.clientY-this.drag.y)*.005));};this.onUp=()=>{this.drag=null;};this.onWheel=e=>{e.preventDefault();this.zoom=Math.max(.62,Math.min(1.8,this.zoom-e.deltaY*.0007));};this.onContextLost=e=>{e.preventDefault();this.contextLost=true;this.onDiagnostics(this.diagnostics('context-lost'));};this.onContextRestored=()=>{this.contextLost=false;this.init();this.onDiagnostics(this.diagnostics('context-restored'));};}
  init(){const gl=this.canvas.getContext('webgl2',{antialias:false,alpha:false,powerPreference:'high-performance'});if(!gl){this.startFallback();return false;}this.gl=gl;const vs=shader(gl,gl.VERTEX_SHADER,VS),fs=shader(gl,gl.FRAGMENT_SHADER,FS),p=gl.createProgram();gl.attachShader(p,vs);gl.attachShader(p,fs);gl.linkProgram(p);gl.deleteShader(vs);gl.deleteShader(fs);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw new Error(gl.getProgramInfoLog(p));if(this.program)gl.deleteProgram(this.program);this.program=p;this.u={resolution:gl.getUniformLocation(p,'u_resolution'),time:gl.getUniformLocation(p,'u_time'),yaw:gl.getUniformLocation(p,'u_yaw'),pitch:gl.getUniformLocation(p,'u_pitch'),zoom:gl.getUniformLocation(p,'u_zoom'),motion:gl.getUniformLocation(p,'u_motion'),mode:gl.getUniformLocation(p,'u_mode'),steps:gl.getUniformLocation(p,'u_steps'),particles:gl.getUniformLocation(p,'u_particles')};this.resize();return true;}
  start(){if(!this.gl&&!this.init())return;this.running=true;this.resizeObserver?this.resizeObserver.observe(this.canvas):addEventListener('resize',this.onResize);this.canvas.addEventListener('pointerdown',this.onDown);this.canvas.addEventListener('pointermove',this.onMove);this.canvas.addEventListener('pointerup',this.onUp);this.canvas.addEventListener('pointercancel',this.onUp);this.canvas.addEventListener('wheel',this.onWheel,{passive:false});this.canvas.addEventListener('webglcontextlost',this.onContextLost);this.canvas.addEventListener('webglcontextrestored',this.onContextRestored);this.raf=requestAnimationFrame(t=>this.frame(t));}
  setMode(mode){this.mode=mode;}
  resetCamera(){this.yaw=0;this.pitch=0;this.zoom=1;}
  resize(){if(!this.gl)return;const rect=this.canvas.getBoundingClientRect(),profile=this.settingsStore.getProfile(),dpr=Math.min(devicePixelRatio||1,2)*profile.renderScale;const w=Math.max(2,Math.floor(rect.width*dpr)),h=Math.max(2,Math.floor(rect.height*dpr));if(w!==this.canvas.width||h!==this.canvas.height){this.canvas.width=w;this.canvas.height=h;this.gl.viewport(0,0,w,h);}}
  frame(time){if(!this.running)return;if(!this.contextLost&&this.gl&&this.program){this.resize();const gl=this.gl,profile=this.settingsStore.getProfile(),settings=this.settingsStore.get();const modes={nebula:0,galaxy:1,supernova:2,blackhole:3,telescope:4};gl.useProgram(this.program);gl.uniform2f(this.u.resolution,this.canvas.width,this.canvas.height);gl.uniform1f(this.u.time,time*.001);gl.uniform1f(this.u.yaw,this.yaw);gl.uniform1f(this.u.pitch,this.pitch);gl.uniform1f(this.u.zoom,this.zoom);gl.uniform1f(this.u.motion,settings.reducedMotion?.08:profile.motionFactor);gl.uniform1i(this.u.mode,modes[this.mode]??0);gl.uniform1i(this.u.steps,profile.id==='performance'?24:profile.id==='experience'?58:40);gl.uniform1f(this.u.particles,profile.id==='performance'?.55:profile.id==='experience'?1.2:.85);gl.drawArrays(gl.TRIANGLES,0,3);if(time-this.lastDiag>1100){this.lastDiag=time;this.onDiagnostics(this.diagnostics('running'));}}this.raf=requestAnimationFrame(t=>this.frame(t));}
  startFallback(){this.fallback=true;const ctx=this.canvas.getContext('2d');if(!ctx)return;const draw=()=>{if(!this.running)return;const r=this.canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,1.5);this.canvas.width=Math.max(2,r.width*dpr);this.canvas.height=Math.max(2,r.height*dpr);const w=this.canvas.width,h=this.canvas.height,g=ctx.createRadialGradient(w*.55,h*.48,4,w*.5,h*.5,w*.55);g.addColorStop(0,'#6d3dbd');g.addColorStop(.32,'#152b6a');g.addColorStop(1,'#02040f');ctx.fillStyle=g;ctx.fillRect(0,0,w,h);for(let i=0;i<180;i++){const x=(i*197)%w,y=(i*83)%h,s=(i%5===0?2:1)*dpr;ctx.fillStyle=`rgba(190,220,255,${.25+(i%7)/10})`;ctx.fillRect(x,y,s,s);}ctx.fillStyle='rgba(130,180,255,.85)';ctx.font=`${18*dpr}px sans-serif`;ctx.fillText('Universo profundo · fallback 2D',18*dpr,30*dpr);this.raf=requestAnimationFrame(draw);};this.running=true;draw();this.onDiagnostics(this.diagnostics('fallback'));}
  diagnostics(state='idle'){return {state,renderer:this.fallback?'Canvas 2D':'WebGL2',resolution:`${this.canvas.width}×${this.canvas.height}`,profile:this.settingsStore.getProfile().id,mode:this.mode,yaw:Number(this.yaw.toFixed(2)),pitch:Number(this.pitch.toFixed(2)),zoom:Number(this.zoom.toFixed(2)),contextLost:this.contextLost};}
  destroy(){this.running=false;cancelAnimationFrame(this.raf);this.resizeObserver?.disconnect();removeEventListener('resize',this.onResize);this.canvas.removeEventListener('pointerdown',this.onDown);this.canvas.removeEventListener('pointermove',this.onMove);this.canvas.removeEventListener('pointerup',this.onUp);this.canvas.removeEventListener('pointercancel',this.onUp);this.canvas.removeEventListener('wheel',this.onWheel);this.canvas.removeEventListener('webglcontextlost',this.onContextLost);this.canvas.removeEventListener('webglcontextrestored',this.onContextRestored);if(this.gl&&this.program)this.gl.deleteProgram(this.program);this.program=null;this.gl=null;this.drag=null;}
}
