import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const app=fs.readFileSync(path.join(root,'assets/js/app.js'),'utf8');
const css=fs.readFileSync(path.join(root,'assets/css/app.css'),'utf8');
assert.match(app,/function renderFinalizationGate\(/,'Tela explícita de conclusão ausente.');
assert.match(app,/Concluir atividade/,'Botão Concluir atividade ausente.');
assert.match(app,/PROCESSANDO ATIVIDADE/,'Animação de processamento não identificada.');
assert.match(app,/function deliveryGuideHTML\(/,'Passo a passo do Classroom ausente.');
assert.match(app,/Adicionar ou criar/,'Instrução de anexação no Classroom ausente.');
assert.match(app,/Fazer upload/,'Instrução de upload ausente.');
assert.match(app,/Marcar como concluída/,'Confirmação final do Classroom ausente.');
assert.match(app,/deliveryCurrentStep/,'Fluxo sequencial de entrega ausente.');
assert.match(app,/attachedConfirmedAt/,'Horário de confirmação do anexo ausente.');
assert.match(app,/deliveredConfirmedAt/,'Horário de confirmação final ausente.');
assert.match(css,/\.delivery-step\.current/,'Destaque do passo atual ausente.');
assert.match(css,/\.attention-pulse/,'Animação de chamada de atenção ausente.');
assert.match(css,/\.classroom-guide-steps/,'Layout do guia do Classroom ausente.');
console.log('Fluxo guiado de conclusão, PDF, Classroom, anexo e entrega validado.');
