import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {GUIDED_MINIMUM_MINUTES,LESSON_TIME_MINUTES} from '../assets/js/data.js';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const app=fs.readFileSync(path.join(root,'assets/js/app.js'),'utf8');
const css=fs.readFileSync(path.join(root,'assets/css/app.css'),'utf8');
const auth=fs.readFileSync(path.join(root,'assets/js/teacher-auth.js'),'utf8');
const sw=fs.readFileSync(path.join(root,'sw.js'),'utf8');
assert.equal(GUIDED_MINIMUM_MINUTES,5);
assert.equal(LESSON_TIME_MINUTES,25);
assert.match(app,/advanceActiveClock\(\)/);
assert.match(app,/awaitingCompletion/);
assert.match(app,/pdfReleaseAt/);
assert.match(app,/pdfReleaseReason/);
assert.match(app,/automatic-session-time/);
assert.match(app,/teacher-class-code/);
assert.match(app,/releaseCompletionPdf/);
assert.match(app,/completed:runtime\.completed/);
assert.match(app,/writeEmergencyCheckpoint/);
assert.match(app,/stageCheckpoints/);
assert.match(app,/lessonProgressFor/);
assert.match(app,/curriculumRevision/);
assert.match(app,/\['1ADM-01','1ADM-02','1ADM-03'\]/);
assert.doesNotMatch(app,/function renderGuidedPaceGate/,'A antiga tela de espera por tempo não deve continuar no fluxo.');
assert.match(app,/Preciso de ajuda/);
assert.match(app,/tutorialOpens/);
assert.match(css,/safe-area-inset-bottom/);
assert.match(css,/@media\(max-width:420px\)/);
assert.match(auth,/PBKDF2-HMAC-SHA-256/);
assert.match(auth,/iterations:360000/);
assert.match(auth,/senha admin SEED TI nova\./);
assert.doesNotMatch(auth,/password\s*:\s*['"]/i);
assert.match(sw,/2\.5\.7-r38/);
assert.match(app,/updateViaCache:'none'/);
console.log('Guided resume, five-minute proof timing, tutorial, open access and responsive cache tests passed.');

assert.match(app,/renderOfficeLabStage/);
assert.match(app,/renderEmailLabStage/);
assert.match(app,/renderTwoFactorLabStage/);
assert.match(app,/renderCompletionSequence/);
