import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {LESSONS} from '../assets/js/data.js';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const app=fs.readFileSync(path.join(root,'assets/js/app.js'),'utf8');
const css=fs.readFileSync(path.join(root,'assets/css/app.css'),'utf8');
for(const id of ['1ADM-04','1ADM-05','1ADM-06','1ADM-07','1ADM-08','2ADM-01','2ADM-02','2ADM-03','2ADM-04','2ADM-05'])assert.ok(LESSONS.some(lesson=>lesson.id===id),`Aula prática ausente: ${id}`);
for(const type of ['office-lab','formula','email-lab','document-lab','presentation-lab'])assert.ok(LESSONS.some(lesson=>lesson.stages.some(stage=>stage.type===type)),`Ferramenta administrativa ausente: ${type}`);
for(const lesson of LESSONS.filter(item=>item.classId==='2ADM')){
  assert.equal(lesson.stages.some(stage=>['hardware-lab','minigame'].includes(stage.type)),false,`${lesson.id} não deve exigir hardware, jogo ou experiência 3D.`);
}
assert.match(app,/email_simulated_sent/);
assert.match(app,/office_action_completed/);
assert.match(app,/document_pdf_exported/);
assert.match(app,/formula_completed/);
assert.match(app,/presentation_action_completed/);
assert.match(app,/renderCompletionSequence/);
assert.match(app,/closeStageTool/);
assert.match(app,/Preciso de ajuda/);
assert.match(css,/webmail-shell/);
assert.match(css,/office-workspace/);
assert.match(css,/document-studio/);
assert.match(css,/drive-suite/);
assert.match(css,/slides-workspace/);
assert.match(css,/pdf-wait-card/);
assert.match(app,/DocumentEngine/);
assert.match(app,/SpreadsheetEngine/);
assert.match(css,/@media\(max-width:390px\)/);
console.log('Practical office tools, closeable interfaces, detailed help and responsive administrative experience tests passed.');
