(function(global){'use strict';
const VALUES={p:100,n:320,b:330,r:500,q:900,k:20000};
function evalPos(engine,side){let score=0;for(let i=0;i<64;i++){const p=engine.board[i];if(!p)continue;const own=(p===p.toUpperCase()?'w':'b')===side,m=VALUES[p.toLowerCase()]||0;score+=(own?1:-1)*m;const r=Math.floor(i/8),c=i%8,center=3.5-(Math.abs(3.5-r)+Math.abs(3.5-c))/2;score+=(own?1:-1)*center*(p.toLowerCase()==='p'?3:6)}const out=engine.outcome();if(out.status==='checkmate')return out.winner===side?999999:-999999;if(out.status!=='playing')return 0;const mobility=engine.legalMoves().length;score+=(engine.turn===side?1:-1)*mobility*1.5;return score}
function ordered(moves){return [...moves].sort((a,b)=>((b.captured?VALUES[b.captured.toLowerCase()]:0)+(b.promotion?800:0))-((a.captured?VALUES[a.captured.toLowerCase()]:0)+(a.promotion?800:0)))}
function minimax(engine,depth,alpha,beta,rootSide,deadline){if(Date.now()>deadline)return evalPos(engine,rootSide);const out=engine.outcome();if(depth<=0||out.status!=='playing')return evalPos(engine,rootSide);const maximizing=engine.turn===rootSide;let best=maximizing?-Infinity:Infinity;for(const m of ordered(engine.legalMoves())){const e=engine.clone();e.play(m);const s=minimax(e,depth-1,alpha,beta,rootSide,deadline);if(maximizing){best=Math.max(best,s);alpha=Math.max(alpha,best)}else{best=Math.min(best,s);beta=Math.min(beta,best)}if(beta<=alpha||Date.now()>deadline)break}return best}
function chooseMove(engine,level='normal',seed=Math.random()){const legal=engine.legalMoves();if(!legal.length)return null;const side=engine.turn;if(level==='mestre'||level==='estrategica'){for(const m of ordered(legal)){const e=engine.clone();e.play(m);const o=e.outcome();if(o.status==='checkmate'&&o.winner===side)return m}}if(level==='iniciante'){const captures=legal.filter(m=>m.captured);const pool=captures.length&&seed>.35?captures:legal;return pool[Math.floor(seed*997)%pool.length]}
 const depth=level==='mestre'?3:level==='estrategica'?2:1,deadline=Date.now()+(level==='mestre'?900:level==='estrategica'?450:180);const scored=ordered(legal).map(m=>{const e=engine.clone();e.play(m);return{m,s:minimax(e,depth-1,-Infinity,Infinity,side,deadline)}}).sort((a,b)=>b.s-a.s);if(level==='normal'&&scored.length>1&&seed<.18)return scored[1].m;if(level==='estrategica'&&scored.length>2&&seed<.08)return scored[1].m;return scored[0].m}
const api={chooseMove,evaluate:evalPos};if(typeof module!=='undefined'&&module.exports)module.exports=api;global.ChessArenaAI=api;
})(typeof globalThis!=='undefined'?globalThis:this);
