import * as THREE from '../voxelcraft-ds/vendor/three/three.module.min.js';
const {ChessEngine,squareName}=globalThis.ChessArenaEngine,{chooseMove}=globalThis.ChessArenaAI;
const qs=new URLSearchParams(location.search),reduced=qs.get('reduced')==='1'||(typeof matchMedia==='function'&&matchMedia('(prefers-reduced-motion: reduce)').matches),quality=qs.get('quality')||'medio';
const modeEl=document.getElementById('mode'),statusEl=document.getElementById('status'),turnEl=document.getElementById('turn'),stateEl=document.getElementById('state'),movesEl=document.getElementById('moves'),historyEl=document.getElementById('history');
const storedMode=localStorage.getItem('fliperama-chess-mode')||qs.get('mode')||'cpu-normal';modeEl.value=[...modeEl.options].some(o=>o.value===storedMode)?storedMode:'cpu-normal';
let engine=new ChessEngine(),selected=-1,pendingPromotion=null,paused=false,cpuThinking=false,topView=false,ended=false;
function post(type,detail={}){parent?.postMessage({source:'fliperama-ds-chess-arena-360',type,detail},location.origin==='null'?'*':location.origin)}
function save(){localStorage.setItem('fliperama-chess-mode',modeEl.value);localStorage.setItem('fliperama-chess-save',JSON.stringify({schemaVersion:1,engine:engine.snapshot(),mode:modeEl.value,ended}))}
function restore(){try{const s=JSON.parse(localStorage.getItem('fliperama-chess-save')||'null');if(s?.schemaVersion===1&&s.engine){engine.restore(s.engine);if([...modeEl.options].some(o=>o.value===s.mode))modeEl.value=s.mode;ended=!!s.ended;return true}}catch{}return false}
const scene=new THREE.Scene();scene.background=new THREE.Color(0x05080f);scene.fog=new THREE.Fog(0x05080f,15,32);const camera=new THREE.PerspectiveCamera(42,innerWidth/innerHeight,.1,60);const renderer=new THREE.WebGLRenderer({canvas:document.getElementById('scene'),antialias:quality!=='baixo',powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,quality==='ultra'?2:quality==='alto'?1.6:1.25));renderer.setSize(innerWidth,innerHeight,false);renderer.shadowMap.enabled=['alto','ultra'].includes(quality);scene.add(new THREE.HemisphereLight(0xccecff,0x12151a,1.8));const sun=new THREE.DirectionalLight(0xffffff,2.2);sun.position.set(6,12,9);sun.castShadow=renderer.shadowMap.enabled;scene.add(sun);
const arena=new THREE.Group();scene.add(arena);const pedestal=new THREE.Mesh(new THREE.CylinderGeometry(6.4,6.9,.8,8),new THREE.MeshStandardMaterial({color:0x101b27,metalness:.65,roughness:.35}));pedestal.position.y=-.55;pedestal.receiveShadow=true;arena.add(pedestal);
const squareMeshes=[],highlightMeshes=[];for(let r=0;r<8;r++)for(let c=0;c<8;c++){const i=r*8+c,light=(r+c)%2===0;const m=new THREE.Mesh(new THREE.BoxGeometry(1,.18,1),new THREE.MeshStandardMaterial({color:light?0xd7d2c4:0x28455a,roughness:.6,metalness:.15,emissive:0x000000}));m.position.set(c-3.5,0,r-3.5);m.userData.square=i;m.receiveShadow=true;arena.add(m);squareMeshes.push(m);const h=new THREE.Mesh(new THREE.CylinderGeometry(.23,.23,.035,28),new THREE.MeshBasicMaterial({color:0x72efff,transparent:true,opacity:0}));h.rotation.x=Math.PI/2;h.position.set(c-3.5,.13,r-3.5);h.userData.square=i;arena.add(h);highlightMeshes.push(h)}
const pieceGroup=new THREE.Group();arena.add(pieceGroup);function mat(side){return new THREE.MeshStandardMaterial({color:side==='w'?0xf5efe1:0x182636,roughness:.28,metalness:.5,emissive:0x000000})}
function pieceMesh(piece,square){const side=piece===piece.toUpperCase()?'w':'b',t=piece.toLowerCase(),g=new THREE.Group(),material=mat(side),add=(geom,y,s=1)=>{const m=new THREE.Mesh(geom,material);m.position.y=y;m.scale.setScalar(s);m.castShadow=renderer.shadowMap.enabled;m.receiveShadow=true;m.userData.square=square;g.add(m);return m};add(new THREE.CylinderGeometry(.34,.4,.16,24),.18);if(t==='p'){add(new THREE.CylinderGeometry(.18,.26,.42,18),.47);add(new THREE.SphereGeometry(.2,18,12),.75)}if(t==='r'){add(new THREE.CylinderGeometry(.24,.31,.55,16),.5);add(new THREE.BoxGeometry(.5,.18,.5),.84)}if(t==='n'){add(new THREE.CylinderGeometry(.23,.31,.42,16),.43);const head=add(new THREE.ConeGeometry(.27,.55,5),.77);head.rotation.z=side==='w'?.35:-.35}if(t==='b'){add(new THREE.CylinderGeometry(.2,.3,.55,18),.5);add(new THREE.SphereGeometry(.22,18,12),.82);const tip=add(new THREE.ConeGeometry(.12,.28,12),1.05)}if(t==='q'){add(new THREE.CylinderGeometry(.23,.32,.68,20),.57);add(new THREE.SphereGeometry(.25,18,12),.94);for(let k=0;k<5;k++){const a=k*Math.PI*2/5,x=.26*Math.cos(a),z=.26*Math.sin(a),c=add(new THREE.ConeGeometry(.08,.25,8),1.15,.8);c.position.x=x;c.position.z=z}}if(t==='k'){add(new THREE.CylinderGeometry(.24,.34,.72,20),.58);add(new THREE.SphereGeometry(.24,18,12),.98);const v=add(new THREE.BoxGeometry(.08,.34,.08),1.25),h=add(new THREE.BoxGeometry(.27,.08,.08),1.28)}g.position.set(square%8-3.5,.1,Math.floor(square/8)-3.5);g.userData.square=square;return g}
function rebuildPieces(){pieceGroup.clear();engine.board.forEach((p,i)=>{if(p)pieceGroup.add(pieceMesh(p,i))})}
function legalFromSelected(){return selected>=0?engine.legalMovesFrom(selected):[]}
function updateHighlights(){for(let i=0;i<64;i++){squareMeshes[i].material.emissive.setHex(i===selected?0x174f62:0);highlightMeshes[i].material.opacity=0}for(const m of legalFromSelected())highlightMeshes[m.to].material.opacity=m.captured?.8:.55}
function outcomeLabel(o){if(o.status==='checkmate')return'XEQUE-MATE';if(o.status==='stalemate')return'AFOGAMENTO';if(o.status.startsWith('draw'))return'EMPATE';if(o.check)return'XEQUE';return'NORMAL'}
function updateHud(){const o=engine.outcome();turnEl.textContent=engine.turn==='w'?'BRANCAS':'PRETAS';stateEl.textContent=outcomeLabel(o);movesEl.textContent=Math.ceil(engine.moveLog.length/2);statusEl.textContent=o.status==='playing'?`${engine.turn==='w'?'Brancas':'Pretas'} jogam${o.check?' · rei em xeque':''}`:describeResult(o);historyEl.innerHTML=engine.moveLog.map((m,i)=>`<span>${i+1}. ${m.fromName}→${m.toName}${m.promotion?'='+m.promotion.toUpperCase():''}${m.castle?' · roque':''}</span>`).join('');historyEl.scrollTop=historyEl.scrollHeight;post('progress',{turn:engine.turn,moves:engine.moveLog.length,status:o.status,check:o.check,mode:modeEl.value})}
function describeResult(o){if(o.status==='checkmate')return`${o.winner==='w'?'Brancas':'Pretas'} vencem por xeque-mate.`;if(o.status==='stalemate')return'Empate por afogamento.';if(o.status==='draw-50')return'Empate pela regra dos 50 lances.';if(o.status==='draw-threefold')return'Empate por repetição tripla.';if(o.status==='draw-insufficient')return'Empate por material insuficiente.';return''}
function finishIfNeeded(){const o=engine.outcome();if(o.status==='playing')return false;ended=true;const modal=document.getElementById('result');document.getElementById('resultBadge').textContent=o.status==='checkmate'?'PARTIDA ENCERRADA':'EMPATE';document.getElementById('resultTitle').textContent=o.status==='checkmate'?`${o.winner==='w'?'Brancas':'Pretas'} vencem`:'Partida empatada';document.getElementById('resultText').textContent=describeResult(o);modal.hidden=false;post('victory',{winner:o.winner,status:o.status,moves:engine.moveLog.length,mode:modeEl.value});save();return true}
function renderState(){rebuildPieces();updateHighlights();updateHud();save()}
function cpuLevel(){return modeEl.value.startsWith('cpu-')?modeEl.value.slice(4):null}function cpuTurn(){return !!cpuLevel()&&engine.turn==='b'}
function maybeCpu(){if(paused||ended||cpuThinking||!cpuTurn())return;cpuThinking=true;statusEl.textContent=`CPU ${cpuLevel()} analisando…`;setTimeout(()=>{const m=chooseMove(engine,cpuLevel());if(m)engine.play(m);cpuThinking=false;selected=-1;renderState();if(!finishIfNeeded())updateHud()},reduced?30:220)}
function doMove(move,promotion){if(move.promotion&&!promotion){pendingPromotion=move;document.getElementById('promotion').hidden=false;return}engine.play({...move,promotion:promotion||move.promotion});selected=-1;pendingPromotion=null;document.getElementById('promotion').hidden=true;renderState();if(!finishIfNeeded())maybeCpu()}
function selectSquare(sq){if(paused||ended||cpuThinking||cpuTurn())return;const piece=engine.board[sq];if(selected>=0){const moves=legalFromSelected().filter(m=>m.to===sq);if(moves.length){const q=moves.find(m=>m.promotion==='q')||moves[0];doMove(q);return}if(piece&&(piece===piece.toUpperCase()?'w':'b')===engine.turn){selected=sq;updateHighlights();return}selected=-1;updateHighlights();return}if(piece&&(piece===piece.toUpperCase()?'w':'b')===engine.turn){selected=sq;updateHighlights()}}
const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2();let down=null,yaw=0,pitch=.72,distance=12.5;function cameraPos(){if(topView)return new THREE.Vector3(0,13.5,.01);return new THREE.Vector3(Math.sin(yaw)*Math.cos(pitch)*distance,Math.sin(pitch)*distance,Math.cos(yaw)*Math.cos(pitch)*distance)}function updateCamera(){camera.position.copy(cameraPos());camera.lookAt(0,0,0)}updateCamera();
const canvas=renderer.domElement;canvas.addEventListener('pointerdown',e=>{down={x:e.clientX,y:e.clientY,yaw,pitch};canvas.setPointerCapture?.(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(!down||topView)return;const dx=e.clientX-down.x,dy=e.clientY-down.y;if(Math.abs(dx)+Math.abs(dy)>4){yaw=down.yaw-dx*.008;pitch=Math.max(.35,Math.min(1.18,down.pitch+dy*.006));updateCamera()}});canvas.addEventListener('pointerup',e=>{if(!down)return;const moved=Math.hypot(e.clientX-down.x,e.clientY-down.y);down=null;if(moved>8)return;const rect=canvas.getBoundingClientRect();pointer.x=((e.clientX-rect.left)/rect.width)*2-1;pointer.y=-((e.clientY-rect.top)/rect.height)*2+1;raycaster.setFromCamera(pointer,camera);const hits=raycaster.intersectObjects([...pieceGroup.children,...squareMeshes],true);for(const hit of hits){let obj=hit.object;while(obj&&obj.userData.square===undefined)obj=obj.parent;if(obj?.userData.square!==undefined){selectSquare(obj.userData.square);break}}});canvas.addEventListener('wheel',e=>{distance=Math.max(8,Math.min(18,distance+Math.sign(e.deltaY)));updateCamera()},{passive:true});
function toggleCamera(){topView=!topView;document.getElementById('camera').textContent=topView?'Visão orbital':'Visão superior';updateCamera()}function newGame(){engine=new ChessEngine();selected=-1;ended=false;cpuThinking=false;document.getElementById('result').hidden=true;document.getElementById('promotion').hidden=true;localStorage.removeItem('fliperama-chess-save');renderState();maybeCpu()}
document.getElementById('camera').onclick=toggleCamera;document.getElementById('new').onclick=newGame;document.getElementById('again').onclick=newGame;modeEl.onchange=()=>{localStorage.setItem('fliperama-chess-mode',modeEl.value);newGame()};document.querySelectorAll('[data-p]').forEach(b=>b.onclick=()=>{if(pendingPromotion)doMove({...pendingPromotion,promotion:b.dataset.p},b.dataset.p)});addEventListener('keydown',e=>{if(e.code==='KeyC')toggleCamera();if(e.code==='KeyN')newGame();if(e.code==='Escape')selected=-1,updateHighlights()});addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight,false)});
addEventListener('message',e=>{if((location.origin!=='null'&&e.origin!==location.origin)||e.data?.source!=='fliperama-ds')return;const t=e.data.type;if(t==='pause')paused=true;if(t==='resume'||t==='start')paused=false;if(t==='restart')newGame();if(t==='shutdown')paused=true});
restore();renderState();finishIfNeeded();post('ready',{renderer:'three',game:'chess-arena-360',rules:'complete',modes:5});maybeCpu();
let last=performance.now();function frame(now){const dt=Math.min(.05,(now-last)/1000);last=now;if(!paused&&!reduced){arena.rotation.y+=Math.sin(now*.00012)*dt*.003}renderer.render(scene,camera);requestAnimationFrame(frame)}requestAnimationFrame(frame);
