import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import { fileURLToPath } from 'node:url';
const here=path.dirname(fileURLToPath(import.meta.url));
const root=path.resolve(here,'../..');
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const migration=read('core/database/019_activity_teacher_content.sql');
const edge=read('core/edge-functions/agv-teacher-activity/index.ts');
const ui=read('professor/assets/professor.js');
const config=read('professor/assets/config.js');
const html=read('professor/index.html');
const schema=JSON.parse(read('core/contracts/teacher-content.schema.json'));
assert.match(migration,/enable row level security/i);
assert.match(migration,/revoke all on table public\.activity_teacher_content from anon, authenticated/i);
assert.match(edge,/teacher_classes/);
assert.match(edge,/class_memberships/);
assert.match(edge,/student_out_of_scope/);
assert.match(edge,/activity_teacher_content/);
assert.match(edge,/staff_only/);
assert.match(config,/staff-dashboard/);
assert.match(config,/agv-teacher-activity/);
assert.doesNotMatch(ui,/service_role|sb_secret_/i);
assert.match(html,/Gabarito explicado/);
assert.equal(schema.title,'AGV Teacher Activity Content');
console.log(JSON.stringify({status:'ok',teacherContentDirectStudentAccess:false,teacherScope:'server-side',frontendContainsAnswers:false},null,2));
