import { ImmersiveInputController } from '../../core/input/ImmersiveInputController.js';
import { UnifiedPhysicsController } from '../../core/physics/UnifiedPhysicsController.js';
import { PhysicsArenaRenderer } from '../../rendering/PhysicsArenaRenderer.js';
import { PHYSICS_ENVIRONMENTS,CONTROL_PRESETS,PHYSICS_GOALS } from '../../data/physicsControlSystems.js';
class PhysicsControlsModule{
 constructor(){this.host=null;this.context=null;this.model=new UnifiedPhysicsController('earth');this.renderer=null;this.input=null;this.raf=0;this.last=0;this.visited=new Set();this.goals=new Set();this.preset=CONTROL_PRESETS[0];this.onClick=e=>this.click(e);}
 mount(host,context){this.host=host;this.context=context;host.addEventListener('click',this.onClick);this.restore();this.render();this.start();}
 restore(){for(const g of PHYSICS_GOALS)if(this.context.profileStore.hasCompleted(`physics-${g.id}`))this.goals.add(g.id);}
 render(){this.host.innerHTML=`<section class="physics-lab"><div class="physics-stage"><canvas data-physics-canvas aria-label="Arena de física e controles"></canvas><header class="physics-top immersive-hud"><button data-action="back">←</button><div><span>FASE 21</span><b>FÍSICA E CONTROLES</b></div><button data-action="fullscreen">⛶</button></header><div class="objective-chip immersive-hud"><span>SIMULAÇÃO MULTIGRAVIDADE</span><b data-physics-goals>${this.goals.size}/${PHYSICS_GOALS.length} objetivos</b></div><nav class="physics-envs immersive-hud">${PHYSICS_ENVIRONMENTS.map((x,i)=>`<button data-action="environment" data-id="${x.id}" class="${i===0?'active':''}"><i>${x.icon}</i><span>${x.label}</span></button>`).join('')}</nav><aside class="physics-hud immersive-hud"><div><span>GRAVIDADE</span><b data-gravity>9,81 m/s²</b></div><div><span>VELOCIDADE</span><b data-speed>0,0 m/s</b></div><div><span>DISTÂNCIA</span><b data-distance>0 m</b></div><div><span>ENERGIA</span><b data-energy>100%</b></div><div><span>RCS</span><b data-fuel>100%</b></div></aside><aside class="physics-presets immersive-hud"><span>CONTROLE</span>${CONTROL_PRESETS.map((p,i)=>`<button data-action="preset" data-id="${p.id}" class="${i===0?'active':''}">${p.label}</button>`).join('')}<button data-action="reset">Reiniciar</button><button data-action="validate-control">Validar controle</button></aside><div class="virtual-joysticks physics-joysticks"><div class="virtual-joystick left" data-stick="left"><div class="joystick-ring"></div><div class="joystick-knob"></div><span>MOVER</span></div><div class="virtual-joystick right" data-stick="right"><div class="joystick-ring"></div><div class="joystick-knob"></div><span>OLHAR</span></div></div><div class="physics-mobile-actions immersive-hud"><button data-action="jump">JUMP</button><button data-action="up">▲</button><button data-action="roll-left">↶</button><button data-action="roll-right">↷</button><button data-action="down">▼</button></div></div></section>`;}
 start(){const canvas=this.host.querySelector('[data-physics-canvas]');this.input=new ImmersiveInputController({canvas,root:this.host,leftStick:this.host.querySelector('[data-stick="left"]'),rightStick:this.host.querySelector('[data-stick="right"]')});this.input.attach();this.renderer=new PhysicsArenaRenderer(canvas,this.context.settingsStore);this.renderer.start();this.last=performance.now();const tick=now=>{const dt=Math.min(.05,(now-this.last)/1000||.016);this.last=now;const raw=this.input.sample(),sensitivity=this.preset.sensitivity;const input={forward:Number(raw.forward||0)*sensitivity,right:Number(raw.right||0)*sensitivity,lookX:Number(raw.lookX||0)*sensitivity,lookY:Number(raw.lookY||0)*sensitivity,up:Number(raw.up||0),roll:Number(raw.roll||0),boost:raw.boost,jump:raw.jump};const state=this.model.update(dt,input);this.renderer.setState(state);this.update(state);if(this.model.mode==='rover'&&state.distance>=250)this.complete('drive-rover');if((this.model.mode==='flight'||this.model.mode==='microgravity')&&state.distance>=30&&Math.abs(state.rotation.roll)>.2)this.complete('six-dof');this.raf=requestAnimationFrame(tick);};this.raf=requestAnimationFrame(tick);}
 click(e){const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action;if(a==='back')return this.context.onBack();if(a==='fullscreen')return this.renderer.requestFullscreen();if(a==='environment'){this.model.setMode(b.dataset.id);this.model.reset();this.visited.add(b.dataset.id);this.host.querySelectorAll('[data-action="environment"]').forEach(x=>x.classList.toggle('active',x===b));if([...this.visited].filter(x=>['earth','moon','mars'].includes(x)).length>=3)this.complete('visit-gravities');}if(a==='preset'){this.preset=CONTROL_PRESETS.find(x=>x.id===b.dataset.id)||CONTROL_PRESETS[0];this.host.querySelectorAll('[data-action="preset"]').forEach(x=>x.classList.toggle('active',x===b));}if(a==='reset')this.model.reset();if(a==='validate-control')this.complete('gamepad');if(a==='jump')this.model.update(.016,{jump:true});if(a==='up')this.model.update(.1,{up:1});if(a==='down')this.model.update(.1,{up:-1});if(a==='roll-left')this.model.update(.1,{roll:-1});if(a==='roll-right')this.model.update(.1,{roll:1});}
 update(s){const set=(q,v)=>{const el=this.host.querySelector(q);if(el)el.textContent=v};set('[data-gravity]',`${s.gravity.toFixed(2).replace('.',',')} m/s²`);set('[data-speed]',`${s.speed.toFixed(1).replace('.',',')} m/s`);set('[data-distance]',`${Math.round(s.distance)} m`);set('[data-energy]',`${Math.round(s.energy)}%`);set('[data-fuel]',`${Math.round(s.fuel)}%`);}
 complete(id){if(this.goals.has(id))return;this.goals.add(id);const g=PHYSICS_GOALS.find(x=>x.id===id);if(g&&this.context.profileStore.addXp(g.xp,`physics-${id}`))this.context.toast(`${g.label}: +${g.xp} XP`);const el=this.host.querySelector('[data-physics-goals]');if(el)el.textContent=`${this.goals.size}/${PHYSICS_GOALS.length} objetivos`;if(this.goals.size===PHYSICS_GOALS.length&&this.context.profileStore.addXp(520,'physics-certification'))this.context.toast('Certificação Pilotagem e Física: +520 XP');}
 unmount(){cancelAnimationFrame(this.raf);this.renderer?.destroy();this.input?.detach();this.host?.removeEventListener('click',this.onClick);if(this.host)this.host.innerHTML='';}
}
export const createModule=()=>new PhysicsControlsModule();
