import {Mundo360Simulation} from './simulation.mjs';
import {Mundo360Renderer} from './render.mjs';
const params=new URLSearchParams(location.search),quality=params.get('quality')||'medio',reduced=params.get('reduced')==='1'||matchMedia('(prefers-reduced-motion: reduce)').matches,muted=params.get('muted')==='1';
const [valeData,villageData,forestData,industrialData,towerData]=await Promise.all(['./region.json','./village.json','./forest.json','./industrial.json','./tower.json'].map(url=>fetch(url).then(r=>{if(!r.ok)throw new Error(`Falha ao carregar ${url}`);return r.json()}))),world={schemaVersion:5,regions:[valeData.region,villageData.region,forestData.region,industrialData.region,towerData.region]},SAVE_KEY='fliperama-mundo-plataforma-360',SOURCE='fliperama-ds-mundo-plataforma-360';
const el=id=>document.getElementById(id),sim=new Mundo360Simulation(world);let portalPaused=false,lastSave=0,drag=null,panorama=false,lastPanoramaButton=false,interactQueued=false;
function post(type,detail={}){parent?.postMessage({source:SOURCE,type,detail},location.origin==='null'?'*':location.origin)}
function save(){localStorage.setItem(SAVE_KEY,JSON.stringify(sim.snapshot()));post('progress',sim.progress());}
function restore(){try{return sim.restore(JSON.parse(localStorage.getItem(SAVE_KEY)||'null'))}catch{return false}}
restore();let finished=sim.completed;const view=new Mundo360Renderer(el('scene'),sim.region,{quality,reduced});
const keys=Object.create(null),touch={left:false,right:false,forward:false,back:false,jump:false};addEventListener('keydown',e=>{keys[e.code]=true;if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();if(e.code==='KeyC'&&!e.repeat)toggle360();if(e.code==='KeyE'&&!e.repeat)interactQueued=true;if(e.code==='KeyR'&&!e.repeat)restart();});addEventListener('keyup',e=>keys[e.code]=false);
document.querySelectorAll('[data-action]').forEach(btn=>{const a=btn.dataset.action;const on=e=>{e.preventDefault();if(a==='panorama'){if(!lastPanoramaButton){toggle360();lastPanoramaButton=true}return}if(a==='interact'){interactQueued=true;return}touch[a]=true};const off=e=>{e.preventDefault();if(a==='panorama'){lastPanoramaButton=false;return}if(a==='interact')return;touch[a]=false};btn.addEventListener('pointerdown',on);btn.addEventListener('pointerup',off);btn.addEventListener('pointercancel',off);btn.addEventListener('pointerleave',off)});
const canvas=el('scene');canvas.addEventListener('pointerdown',e=>{drag={x:e.clientX,y:e.clientY};canvas.setPointerCapture?.(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(!drag)return;view.setCameraDelta(e.clientX-drag.x,e.clientY-drag.y);drag={x:e.clientX,y:e.clientY}});canvas.addEventListener('pointerup',()=>drag=null);canvas.addEventListener('pointercancel',()=>drag=null);canvas.addEventListener('wheel',e=>e.preventDefault(),{passive:false});addEventListener('resize',()=>view.resize());
function toggle360(){panorama=view.togglePanorama();el('mode360').textContent=panorama?'PANORAMA 360 ATIVO':'EXPLORAÇÃO 360';el('mode360').classList.toggle('active',panorama);}
function gamepad(){const p=(navigator.getGamepads?.()||[])[0];if(!p)return{x:0,z:0,lx:0,ly:0,jump:false,panorama:false,interact:false};return{x:Math.abs(p.axes[0]||0)>.15?p.axes[0]:0,z:Math.abs(p.axes[1]||0)>.15?p.axes[1]:0,lx:Math.abs(p.axes[2]||0)>.16?p.axes[2]:0,ly:Math.abs(p.axes[3]||0)>.16?p.axes[3]:0,jump:!!p.buttons[0]?.pressed,interact:!!p.buttons[2]?.pressed,panorama:!!p.buttons[3]?.pressed}}
let gpPanoramaLatch=false,gpInteractLatch=false;
function sectorName(pos){let best=sim.region.sectors?.[0],bestD=Infinity;for(const s of sim.region.sectors||[]){const d=(pos.x-s.center[0])**2+(pos.z-s.center[1])**2;if(d<bestD){bestD=d;best=s}}return best?.name||sim.region.name;}
function updateHud(){const p=sim.progress(),h=view.heading();el('regionLine').textContent=`Região ${p.region}/${p.totalRegions} · ${sectorName(sim.player.pos)}`;if(sim.region.kind==='village'){el('orbsLabel').textContent='Dados';el('orbs').textContent=`${p.data}/${p.totalData}`;el('beaconsLabel').textContent='Missão';el('beacons').textContent=`${p.mission}/3`;}else if(sim.region.kind==='forest'){el('orbsLabel').textContent='Nós';el('orbs').textContent=`${p.nodes}/${p.totalNodes}`;el('beaconsLabel').textContent='Região';el('beacons').textContent='3/4';}else if(sim.region.kind==='industrial'){el('orbsLabel').textContent=p.industrialStage<1?'Energia':p.industrialStage<2?'Cargas':'Controle';el('orbs').textContent=p.industrialStage<1?`${p.power}/${p.totalPower}`:p.industrialStage<2?`${p.cargo}/${p.totalCargo}`:(p.controlSynced?'OK':'PEND.');el('beaconsLabel').textContent='Região';el('beacons').textContent='4/5';}else if(sim.region.kind==='tower'){el('orbsLabel').textContent=p.towerStage<1?'Sincronia':'Núcleo';el('orbs').textContent=p.towerStage<1?`${p.sync}/${p.totalSync}`:(p.towerCore?'ATIVO':'PEND.');el('beaconsLabel').textContent='Região';el('beacons').textContent='5/5';}else{el('orbsLabel').textContent='Orbes';el('orbs').textContent=`${p.orbs}/${p.totalOrbs}`;el('beaconsLabel').textContent='Balizas';el('beacons').textContent=`${p.beacons}/${p.totalBeacons}`;}el('lives').textContent=p.lives;el('score').textContent=p.score.toLocaleString('pt-BR');el('heading').textContent=`${h.label} ${h.deg}°`;el('objective').textContent=sim.objective();const hint=sim.interactionHint();el('interactPrompt').hidden=!hint;el('interactPrompt').textContent=hint?`E · ${hint.kind==='npc'?'Falar com':'Interagir:'} ${hint.name}`:'';}
function restart(){sim.resetAll();finished=false;el('result').hidden=true;save();updateHud();}
el('replay').onclick=()=>{localStorage.removeItem(SAVE_KEY);restart()};
function tone(freq=440,d=.05){if(muted)return;try{const AC=window.AudioContext||window.webkitAudioContext,a=new AC(),o=a.createOscillator(),g=a.createGain();o.frequency.value=freq;g.gain.value=.025;o.connect(g).connect(a.destination);o.start();g.gain.exponentialRampToValueAtTime(.0001,a.currentTime+d);o.stop(a.currentTime+d+.01)}catch{}}
let toastTimer=0;function toast(text,ms=1300){el('toast').textContent=text;el('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el('toast').classList.remove('show'),ms);}
function handleEvents(){for(const ev of sim.consumeEvents()){if(ev.type==='collect'){tone(760,.07);toast(`${ev.name} recuperado`)}else if(ev.type==='beacon'){tone(980,.11);toast(`${ev.name} ativada`)}else if(ev.type==='checkpoint'){tone(620,.07);toast('Checkpoint atualizado',700)}else if(ev.type==='damage'){tone(180,.09)}else if(ev.type==='region-change'){tone(900,.18);const labels={2:'Vila Tecnológica desbloqueada!',3:'Floresta de Circuitos desbloqueada!',4:'Região Industrial desbloqueada!',5:'Torre Central desbloqueada!'};toast(labels[ev.region]||'Nova região desbloqueada!',1900);post('region-change',{region:ev.region,totalRegions:5,name:ev.name})}else if(ev.type==='migration'){toast(ev.fromSchema===4?'Save v0.38.4 migrado · Torre Central liberada':ev.fromSchema===3?'Save v0.38.3 migrado · Região Industrial liberada':ev.fromSchema===2?'Save v0.38.2 migrado · campanha ampliada':'Save anterior migrado para a campanha atual',2300)}else if(ev.type==='dialog'){tone(520,.04);toast(`${ev.npc}: ${ev.text}`,3000)}else if(ev.type==='activate'){tone(840,.08);toast(`${ev.name} sincronizado`)}else if(ev.type==='upload'){tone(960,.12);toast('Upload concluído · Estação de Dados estável',1700)}else if(ev.type==='core'){tone(1060,.15);toast('Núcleo da Vila sincronizado',1700)}else if(ev.type==='forest-node'){tone(1120,.14);toast(`${ev.name} restaurado · ${ev.count}/3`,1800)}else if(ev.type==='industrial-power'){tone(760,.09);toast(`${ev.name} estabilizado · ${ev.count}/3`,1700)}else if(ev.type==='cargo-route'){tone(880,.1);toast(`${ev.name} processado · ${ev.count}/3`,1700)}else if(ev.type==='industrial-control'){tone(1180,.16);toast('Sala de Controle sincronizada',1800)}else if(ev.type==='tower-sync'){tone(980,.12);toast(`${ev.name} sincronizado · ${ev.count}/3`,1700)}else if(ev.type==='tower-core'){tone(1320,.22);toast('Núcleo Central ativado · Portal de Conclusão liberado',2200)}else if(ev.type==='mission'){tone(720,.06);toast(ev.label,ev.mission?1600:1100);post('mission',{region:sim.regionIndex+1,mission:ev.mission||sim.progress().mission,label:ev.label})}else if(ev.type==='notice'){toast(ev.text,1700)}else if(ev.type==='victory'){finished=true;tone(1040,.22);el('resultText').textContent=`Cinco regiões sincronizadas · Torre Central e Núcleo no topo concluídos · ${ev.score.toLocaleString('pt-BR')} pontos.`;el('result').hidden=false;post('victory',{region:5,regions:5,missions:6,lives:sim.lives,score:ev.score,completed:true});}save();}}
addEventListener('message',e=>{if((location.origin!=='null'&&e.origin!==location.origin)||e.data?.source!=='fliperama-ds')return;const t=e.data.type;if(t==='pause'||t==='shutdown')portalPaused=true;else if(t==='resume'||t==='start')portalPaused=false;else if(t==='restart')restart()});
post('ready',{renderer:'three',runtime:'mundo-plataforma-ds-360',regions:5,mode360:true,village:true,forest:true,industrial:true,tower:true});handleEvents();save();updateHud();if(finished){el('resultText').textContent='Campanha atual já concluída neste dispositivo.';el('result').hidden=false;}let prev=performance.now();function frame(now){const dt=Math.min(.035,(now-prev)/1000||0);prev=now;const gp=gamepad();if(gp.panorama&&!gpPanoramaLatch){toggle360();gpPanoramaLatch=true}else if(!gp.panorama)gpPanoramaLatch=false;if(gp.interact&&!gpInteractLatch){interactQueued=true;gpInteractLatch=true}else if(!gp.interact)gpInteractLatch=false;view.setGamepadLook(gp.lx,gp.ly,dt);if(!portalPaused&&!finished){const basis=view.movementBasis();let localX=(keys.KeyD||keys.ArrowRight||touch.right?1:0)-(keys.KeyA||keys.ArrowLeft||touch.left?1:0)+gp.x;let localZ=(keys.KeyW||keys.ArrowUp||touch.forward?1:0)-(keys.KeyS||keys.ArrowDown||touch.back?1:0)-gp.z;if(panorama){localX=0;localZ=0}const len=Math.hypot(localX,localZ)||1;localX/=len;localZ/=len;const worldX=localX*basis.cos+localZ*basis.sin,worldZ=localX*basis.sin-localZ*basis.cos;sim.tick(dt,{x:worldX,z:worldZ,jump:!panorama&&(keys.Space||touch.jump||gp.jump),interact:interactQueued});interactQueued=false;handleEvents();if(now-lastSave>2200){save();lastSave=now}}view.update(sim,dt);updateHud();requestAnimationFrame(frame)}requestAnimationFrame(frame);
