'use strict';
(function(){
  window.LABDS_LABS=window.LABDS_LABS||{};
  const KEY='lab.market.state';
  const ASSETS={
    TechCode:{price:100,vol:.012,trend:.0012,risk:'Médio',fee:.002,description:'Índice fictício de projetos de software.'},
    RoboCoin:{price:65,vol:.028,trend:.0005,risk:'Alto',fee:.004,description:'Ativo educacional ligado à robótica.'},
    EduData:{price:140,vol:.009,trend:.001,risk:'Baixo',fee:.0015,description:'Índice fictício de dados e educação.'},
    GreenEnergy:{price:82,vol:.017,trend:.0015,risk:'Médio',fee:.0025,description:'Ativo simulado de energia sustentável.'},
    VirtualNet:{price:118,vol:.02,trend:-.0002,risk:'Médio',fee:.003,description:'Infraestrutura e redes em ambiente fictício.'},
    Print3D:{price:48,vol:.023,trend:.0008,risk:'Alto',fee:.0035,description:'Fabricação digital e impressão 3D.'}
  };
  let root,ctx,state,timer=null,seed=1;
  const $=s=>root.querySelector(s),clamp=(n,a,b)=>Math.min(b,Math.max(a,Number(n)||0));
  function defaults(){const asset='TechCode';return{asset,seed:202603,history:Array.from({length:45},(_,i)=>({t:i,price:ASSETS[asset].price})),position:null,simulationCredits:1000,mode:'tutorial',seconds:0,closed:[]};}
  function rnd(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;}
  function normal(){return (rnd()+rnd()+rnd()+rnd()+rnd()+rnd()-3)/1.2;}
  function current(){return state.history.at(-1)?.price||ASSETS[state.asset].price;}
  function resetAsset(){const base=ASSETS[state.asset].price;state.history=Array.from({length:45},(_,i)=>({t:i,price:base}));state.position=null;state.seconds=0;seed=Number(state.seed)||1;}
  function tick(){const asset=ASSETS[state.asset],last=current(),eventRoll=rnd();let shock=0;if(eventRoll<.006)shock=(rnd()>.5?1:-1)*(asset.vol*8);else if(eventRoll<.03)shock=(rnd()>.5?1:-1)*(asset.vol*3);const change=asset.trend+normal()*asset.vol+shock;const next=Math.max(.5,last*(1+change));state.seconds++;state.history.push({t:state.seconds,price:Number(next.toFixed(4))});state.history=state.history.slice(-120);renderLive();ctx.storage.set(KEY,state);}
  function pnl(){if(!state.position)return 0;const direction=state.position.side==='buy'?1:-1,variation=(current()-state.position.entry)/state.position.entry*direction;return state.position.amount*variation-state.position.amount*ASSETS[state.asset].fee;}
  function openPosition(side){if(state.position)return ctx.toast('Encerre a posição atual antes de abrir outra.','warning');const amount=clamp($('#marketAmount').value,10,state.simulationCredits);if(amount>state.simulationCredits)return ctx.toast('Pontos temporários insuficientes.','warning');state.simulationCredits-=amount;state.position={side,amount,entry:current(),openedAt:Date.now()};renderLive();ctx.toast(side==='buy'?'Posição de compra aberta.':'Posição de venda aberta.','success');}
  function closePosition(){if(!state.position)return;const result=pnl(),returned=Math.max(0,state.position.amount+result);state.simulationCredits+=returned;state.closed.push({...state.position,exit:current(),result,closedAt:Date.now()});const positive=result>0;ctx.core?.addTempPoints?.(Math.round(result),`Mercado Tech: ${state.asset}`);if(state.closed.length>=3)ctx.core?.complete?.('market:three-positions',{xp:45,credits:positive?10:0,reason:'Análise de três posições no Mercado Tech'});ctx.toast(`${positive?'Lucro':'Prejuízo'} simulado: ${result.toFixed(2)} pontos.` ,positive?'success':'warning',5000);state.position=null;renderLive();}
  function draw(){const canvas=$('#marketChart');if(!canvas)return;const c=canvas.getContext('2d'),w=canvas.width,h=canvas.height,values=state.history.map(x=>x.price),min=Math.min(...values),max=Math.max(...values),span=Math.max(.01,max-min);c.clearRect(0,0,w,h);c.fillStyle='#07111f';c.fillRect(0,0,w,h);c.strokeStyle='rgba(160,190,230,.16)';c.lineWidth=1;for(let i=0;i<5;i++){const y=25+i*(h-50)/4;c.beginPath();c.moveTo(45,y);c.lineTo(w-12,y);c.stroke();c.fillStyle='#8fa5c0';c.font='11px system-ui';c.fillText((max-span*i/4).toFixed(2),3,y+4);}c.strokeStyle=current()>=state.history[0].price?'#43e6a8':'#ff6f8d';c.lineWidth=3;c.beginPath();state.history.forEach((point,index)=>{const x=45+index*(w-60)/Math.max(1,state.history.length-1),y=25+(max-point.price)/span*(h-50);index?c.lineTo(x,y):c.moveTo(x,y);});c.stroke();if(state.position){const y=25+(max-state.position.entry)/span*(h-50);c.strokeStyle='#ffcf5d';c.setLineDash([6,5]);c.beginPath();c.moveTo(45,y);c.lineTo(w-12,y);c.stroke();c.setLineDash([]);}}
  function renderLive(){if(!root)return;$('#marketPrice').textContent=current().toFixed(2);$('#marketCredits').textContent=state.simulationCredits.toFixed(2);$('#marketSeconds').textContent=`${state.seconds}s`;$('#marketPosition').textContent=state.position?`${state.position.side==='buy'?'Compra':'Venda'} • entrada ${state.position.entry.toFixed(2)} • ${pnl().toFixed(2)} pts`:'Sem posição aberta';$('#marketClose').disabled=!state.position;draw();renderHistory();}
  function renderHistory(){const host=$('#marketHistory');host.innerHTML=state.closed.slice(-8).reverse().map(item=>`<tr><td>${item.side==='buy'?'Compra':'Venda'}</td><td>${item.entry.toFixed(2)}</td><td>${item.exit.toFixed(2)}</td><td class="${item.result>=0?'positive':'negative'}">${item.result.toFixed(2)}</td></tr>`).join('')||'<tr><td colspan="4">Nenhuma posição encerrada.</td></tr>';}
  function template(){return`<div class="market-lab"><header class="market-header"><div><span class="eyebrow">SIMULAÇÃO EDUCACIONAL • SEM DINHEIRO REAL</span><h2>Mercado Tech</h2><p>O gráfico evolui por tendência, volatilidade e eventos aleatórios. Sua escolha não altera o próximo movimento.</p></div><div class="market-mode"><label>Ativo<select id="marketAsset">${Object.keys(ASSETS).map(name=>`<option>${name}</option>`).join('')}</select></label><label>Semente<input id="marketSeed" type="number" value="${state.seed}"></label><button id="marketReset" type="button">Reiniciar série</button></div></header><section class="market-grid"><div class="market-chart-card"><div class="market-quote"><div><b id="marketPrice"></b><span>${state.asset}</span></div><div><b id="marketCredits"></b><span>pontos temporários</span></div><div><b id="marketSeconds"></b><span>tempo</span></div></div><canvas id="marketChart" width="920" height="380"></canvas><div class="market-position"><label>Valor da posição<input id="marketAmount" type="number" min="10" step="10" value="100"></label><button id="marketBuy" class="buy">Comprar ↑</button><button id="marketSell" class="sell">Vender ↓</button><button id="marketClose">Encerrar posição</button><span id="marketPosition"></span></div></div><aside><article><h3>Como decidir</h3><p><b>Comprar:</b> você acredita em alta. <b>Vender:</b> você acredita em queda. O resultado depende apenas da série simulada.</p></article><article><h3>${state.asset}</h3><p id="assetDescription"></p><dl><dt>Risco</dt><dd id="assetRisk"></dd><dt>Volatilidade</dt><dd id="assetVol"></dd><dt>Taxa fictícia</dt><dd id="assetFee"></dd></dl></article><article><h3>Eventos</h3><p>Movimentos pequenos são comuns. Eventos raros podem produzir alta ou queda forte. Resultados passados não determinam o próximo ponto.</p></article></aside></section><section class="market-history"><h2>Histórico de posições</h2><table><thead><tr><th>Decisão</th><th>Entrada</th><th>Saída</th><th>Resultado</th></tr></thead><tbody id="marketHistory"></tbody></table></section></div>`;}
  function updateAssetInfo(){const a=ASSETS[state.asset];$('#assetDescription').textContent=a.description;$('#assetRisk').textContent=a.risk;$('#assetVol').textContent=`${(a.vol*100).toFixed(1)}% por passo`;$('#assetFee').textContent=`${(a.fee*100).toFixed(2)}%`;}
  async function mount(host,context){root=host;ctx=context;state={...defaults(),...(await ctx.storage.get(KEY,{}))};seed=Number(state.seed)||1;root.innerHTML=template();$('#marketAsset').value=state.asset;$('#marketAsset').onchange=()=>{state.asset=$('#marketAsset').value;resetAsset();updateAssetInfo();renderLive();};$('#marketSeed').onchange=()=>{state.seed=Number($('#marketSeed').value)||1;};$('#marketReset').onclick=()=>{state.seed=Number($('#marketSeed').value)||1;resetAsset();renderLive();};$('#marketBuy').onclick=()=>openPosition('buy');$('#marketSell').onclick=()=>openPosition('sell');$('#marketClose').onclick=closePosition;updateAssetInfo();renderLive();timer=setInterval(tick,1000);}
  async function unmount(){clearInterval(timer);timer=null;await ctx?.storage?.set?.(KEY,state);root=null;ctx=null;}
  function exportPayload(){return{text:`MERCADO TECH\nAtivo: ${state.asset}\nPreço: ${current().toFixed(2)}\nPontos: ${state.simulationCredits.toFixed(2)}\nPosições: ${state.closed.length}`,native:JSON.stringify(state,null,2),backup:state};}
  function help(){return'<p>Escolha Comprar ou Vender e acompanhe uma série independente. A simulação usa ativos e pontos fictícios, não recomenda investimentos e não utiliza dinheiro real.</p>';}
  window.LABDS_LABS['market-lab']={mount,unmount,exportPayload,help};
})();
