'use strict';

(function(){
  window.LABDS_LABS=window.LABDS_LABS||{};
  let root=null,ctx=null,state=null,worker=null,running=false,runtimeReady=false,runStarted=0,runTimer=null,runToken=0;
  const STORAGE_KEY='lab.python.state';
  const defaults={schemaVersion:1,code:`nome = input("Digite seu nome: ")
notas = [8.5, 7.0, 9.2]
media = sum(notas) / len(notas)

print(f"Olá, {nome}!")
print(f"Média: {media:.2f}")

if media >= 7:
    print("Situação: aprovado")
else:
    print("Situação: recuperação")`,stdin:'Gabriel',logs:[],packages:[]};
  const packageCatalog=[
    {name:'numpy',desc:'Cálculo numérico e arrays.',status:'disponível',size:'≈ 8 MB'},
    {name:'pandas',desc:'Análise e manipulação de dados.',status:'disponível',size:'≈ 15 MB'},
    {name:'matplotlib',desc:'Gráficos científicos; a saída gráfica depende do backend do Pyodide.',status:'parcial',size:'≈ 12 MB'},
    {name:'pillow',desc:'Manipulação de imagens com Pillow.',status:'disponível',size:'≈ 5 MB'},
    {name:'micropip',desc:'Instala pacotes Python puros compatíveis; rede do código do aluno continua bloqueada.',status:'parcial',size:'≈ 1 MB'},
    {name:'pygame',desc:'Pygame tradicional não é disponibilizado neste navegador. Use o laboratório de jogos web.',status:'indisponível',size:'—'}
  ];
  const $=selector=>root?.querySelector(selector);
  function log(text,level='log'){String(text??'').split('\n').forEach(line=>state.logs.push({time:new Date().toLocaleTimeString('pt-BR'),text:(line||' ').slice(0,20000),level}));state.logs=state.logs.slice(-350);renderConsole();}
  function renderConsole(){const box=$('#pyConsole');if(!box)return;box.textContent='';if(!state.logs.length){const empty=document.createElement('div');empty.className='muted-copy';empty.textContent='O Python será carregado quando você executar o código.';box.appendChild(empty);return;}state.logs.forEach(item=>{const row=document.createElement('div');row.className=`code-log ${item.level}`;const time=document.createElement('span');time.textContent=item.time;row.append(time,document.createTextNode(item.text));box.appendChild(row);});box.scrollTop=box.scrollHeight;}
  function setStatus(text,tone=''){const element=$('#pyStatus');if(element){element.textContent=text;element.dataset.tone=tone;}}
  function cleanupWorker(){clearTimeout(runTimer);runTimer=null;worker?.terminate();worker=null;runtimeReady=false;}
  function createWorker(){
    if(worker)return;worker=new Worker('js/workers/python-runner.js');const token=runToken;
    worker.onmessage=event=>{if(token!==runToken)return;const {type,payload}=event.data||{};if(type==='status')setStatus(payload,'busy');else if(type==='ready'){runtimeReady=true;setStatus(`Python ${payload} pronto`,'success');}else if(type==='stdout')log(payload,'log');else if(type==='stderr')log(payload,'error');else if(type==='result')log(payload,'result');else if(type==='error'){log(payload.message,'error');if(payload.stack)log(payload.stack.split('\n').slice(0,6).join('\n'),'dim');setStatus('erro','error');}else if(type==='done'){clearTimeout(runTimer);runTimer=null;running=false;$('#pyRun').disabled=false;$('#pyStop').disabled=true;if(payload.ok)setStatus('concluído','success');ctx.storage.set(STORAGE_KEY,state);const stdin=/senha|password/i.test(state.code)?'[entrada omitida por possível campo de senha]':state.stdin;ctx.logEvent({eventType:'code_execution',action:'Código Python executado',input:state.code,output:state.logs.map(item=>item.text).join('\n'),status:payload.ok?'success':'error',context:{language:'Python',file:'main.py',stdin,durationMs:Math.round(performance.now()-runStarted),engine:'Pyodide/WebAssembly em Worker',packages:[...state.packages],limits:payload.metrics||{},networkBlocked:true}});}else if(type==='package'){if(!state.packages.includes(payload.name))state.packages.push(payload.name);renderPackages();setStatus(`${payload.name} disponível`,'success');}};
    worker.onerror=event=>{log(`Falha no ambiente Python: ${event.message}`,'error');stop('worker-error');};
  }
  function run(){
    if(running)return;state.code=$('#pyCode').value;state.stdin=$('#pyStdin').value;if(state.code.length>(window.LABDS.SECURITY_LIMITS?.codeBytes||200000)){ctx.toast('O código excede 200 KB.','warning');return;}if(state.stdin.length>20000){ctx.toast('A entrada padrão excede 20 KB.','warning');return;}runStarted=performance.now();state.logs=[];renderConsole();runToken++;cleanupWorker();createWorker();running=true;$('#pyRun').disabled=true;$('#pyStop').disabled=false;setStatus('carregando Pyodide','busy');runTimer=setTimeout(()=>{if(running){log(`Execução interrompida após ${(window.LABDS.SECURITY_LIMITS?.pythonTimeoutMs||25000)/1000} segundos.`,'warning');stop('timeout');}},window.LABDS.SECURITY_LIMITS?.pythonTimeoutMs||25000);worker.postMessage({type:'run',code:state.code,stdin:state.stdin.split(/\r?\n/),url:window.LABDS.PYODIDE_URL,indexURL:window.LABDS.PYODIDE_INDEX});
  }
  function stop(reason='user',record=true){const wasRunning=running;runToken++;cleanupWorker();running=false;if(root){$('#pyRun').disabled=false;$('#pyStop').disabled=true;setStatus('interrompido','warning');}if(wasRunning){log(reason==='timeout'?'Worker encerrado pelo watchdog.':'Ambiente interrompido. Será recarregado na próxima execução.','warning');if(record)ctx?.logEvent({eventType:'code_execution',action:'Execução Python interrompida',input:state.code,output:state.logs.map(item=>item.text).join('\n'),status:'interrupted',context:{language:'Python',file:'main.py',reason,durationMs:Math.round(performance.now()-runStarted)}});}}
  function install(name){if(name==='pygame'){ctx.toast('Pygame tradicional não está disponível no Pyodide desta versão. Abra Jogos com Código para uma alternativa web.','warning',7000);return;}if(running){ctx.toast('Aguarde a execução terminar.','warning');return;}runToken++;cleanupWorker();createWorker();setStatus(`preparando ${name}`,'busy');worker.postMessage({type:'install',packageName:name,url:window.LABDS.PYODIDE_URL,indexURL:window.LABDS.PYODIDE_INDEX});ctx.logEvent({eventType:'package_operation',action:`Biblioteca Python solicitada: ${name}`,status:'success',context:{package:name,operation:'load',allowlisted:true}});}
  function renderPackages(){const box=$('#pyPackages');box.textContent='';packageCatalog.forEach(item=>{const article=document.createElement('article');article.className='package-card';const info=document.createElement('div');const strong=document.createElement('strong');strong.textContent=item.name;const p=document.createElement('p');p.textContent=item.desc;const small=document.createElement('small');small.textContent=`${item.size} • ${state.packages.includes(item.name)?'carregado nesta sessão':item.status}`;info.append(strong,p,small);const button=document.createElement('button');button.className=`btn ${state.packages.includes(item.name)?'subtle':'secondary'}`;button.type='button';button.dataset.package=item.name;button.disabled=state.packages.includes(item.name);button.textContent=state.packages.includes(item.name)?'Disponível':item.status==='indisponível'?'Ver alternativa':'Carregar';article.append(info,button);box.appendChild(article);});box.querySelectorAll('[data-package]').forEach(button=>button.addEventListener('click',()=>install(button.dataset.package)));}
  async function mount(host,context){root=host;ctx=context;state={...defaults,...(await ctx.storage.get(STORAGE_KEY,defaults)),logs:[],packages:[]};root.innerHTML='<div class="split-view code-lab python-layout"><section class="resizable-panel"><div class="panel-toolbar"><div class="tabs"><button class="tab-btn active" type="button">main.py</button></div><div class="button-row"><button id="pyRun" class="btn primary" type="button">Executar</button><button id="pyStop" class="btn secondary" type="button" disabled>Parar</button><button id="pyRestore" class="btn subtle" type="button">Restaurar</button></div></div><textarea id="pyCode" class="code-editor" spellcheck="false" aria-label="Código Python"></textarea></section><section class="resizable-panel python-side"><div class="panel-toolbar"><strong>Console Python</strong><span id="pyStatus" data-tone="success">aguardando</span></div><div class="stdin-box"><label>Entrada padrão — uma linha para cada <code>input()</code><textarea id="pyStdin" rows="4" aria-label="Entrada padrão Python"></textarea></label></div><div class="state-card info"><p>Execução real em Pyodide/WebAssembly. Rede do código, novos Workers e bibliotecas fora da lista são bloqueados. Watchdog de 25 segundos.</p></div><div id="pyConsole" class="console-card code-console"></div><div class="package-section"><div class="panel-title"><div><h3>Compatibilidade de bibliotecas</h3><p>Disponível, parcial ou indisponível no navegador.</p></div></div><div id="pyPackages" class="package-list"></div></div></section></div>';$('#pyCode').value=state.code;$('#pyStdin').value=state.stdin;$('#pyRun').addEventListener('click',run);$('#pyStop').addEventListener('click',()=>stop('user'));$('#pyRestore').addEventListener('click',()=>{if(confirm('Restaurar o exemplo?')){$('#pyCode').value=defaults.code;$('#pyStdin').value=defaults.stdin;}});$('#pyCode').addEventListener('keydown',event=>{if(event.key==='Tab'){event.preventDefault();event.target.setRangeText('    ',event.target.selectionStart,event.target.selectionEnd,'end');}if((event.ctrlKey||event.metaKey)&&event.key==='Enter'){event.preventDefault();run();}});renderConsole();renderPackages();}
  function exportPayload(){const code=$('#pyCode')?.value||state.code;return{text:['AMBIENTE PYTHON — PYODIDE',`Exportado em: ${new Date().toLocaleString('pt-BR')}`,'','===== CÓDIGO =====',code,'','===== CONSOLE =====',...state.logs.map(item=>`[${item.time}] ${item.text}`)].join('\n'),native:code,backup:{schemaVersion:1,code,stdin:$('#pyStdin')?.value||state.stdin},meta:[{label:'Execução',value:'Pyodide/WebAssembly em Worker'},{label:'Rede do aluno',value:'bloqueada'},{label:'Conexão',value:'necessária no primeiro carregamento'}]};}
  function help(){return '<p>Python executa de verdade com Pyodide. NumPy e Pandas são suportados; Matplotlib e Micropip têm limitações; Pygame tradicional não é oferecido. O botão Parar encerra o Worker e interrompe loops.</p>';}
  async function unmount(){stop('unmount',false);if(ctx&&root){state.code=$('#pyCode').value;state.stdin=$('#pyStdin').value;await ctx.storage.set(STORAGE_KEY,state);}root=null;ctx=null;state=null;}
  window.LABDS_LABS['python-lab']={mount,unmount,exportPayload,help};
})();
