import { SpaceTechnologyEngine } from '../../core/technology/SpaceTechnologyEngine.js';
import { SPACE_TECHNOLOGIES, SPACE_LANGUAGES_C2, SPACE_SENSORS, DIGITAL_ARCHITECTURE_LAYERS, TELEMETRY_SCENARIOS, TECHNOLOGY_CHALLENGES } from '../../data/technologyGuidedSystems.js';
import { GUIDED_TRAILS } from '../../data/guidedTrailDefinitions.js';
import { TechnologyNetworkRenderer } from '../../rendering/TechnologyNetworkRenderer.js';

const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const statusLabel=status=>status==='COMPLETED'?'Concluída':status==='ACTIVE'?'Em andamento':status==='PAUSED'?'Pausada':'Não iniciada';

class TechnologyHubModule {
  constructor(){this.container=null;this.context=null;this.engine=new SpaceTechnologyEngine();this.tab='trails';this.selectedTechnology='embedded';this.selectedLanguage='c';this.selectedSensor='gyroscope';this.selectedLayer='sensor';this.sensorFault=false;this.sensorReading=null;this.sensorTimer=0;this.telemetryIndex=0;this.telemetryResult=null;this.challengeIndex=0;this.challengeScore=0;this.challengeFeedback='';this.renderer=null;this.onClick=event=>this.handleClick(event);this.onInput=event=>this.handleInput(event);}
  mount(container,context){this.container=container;this.context=context;this.render();container.addEventListener('click',this.onClick);container.addEventListener('input',this.onInput);this.startVisuals();}
  unmount(){this.container?.removeEventListener('click',this.onClick);this.container?.removeEventListener('input',this.onInput);this.stopVisuals();}
  trailEngine(){return this.context.guidedTrails;}
  render(){const quality=this.context.settingsStore.getProfile();this.container.innerHTML=`<section class="technology-hub quality-${quality.id}">
    <header class="technology-hero">
      <div><span class="eyebrow">Fase C2.1 · Tecnologia, Programação e Modo Guiado</span><h2>Central de Tecnologia Espacial</h2><p>Explore linguagens, sensores, telemetria e arquitetura digital ou siga uma trilha sequencial por toda a plataforma.</p></div>
      <div class="technology-hero-actions"><span class="technology-status">26 módulos conectados</span><button class="button secondary" data-action="back">← Portal</button></div>
    </header>
    <nav class="technology-tabs" aria-label="Áreas da Central de Tecnologia">
      ${this.tabButton('trails','Trilhas guiadas')}${this.tabButton('technologies','Tecnologias')}${this.tabButton('languages','Linguagens')}${this.tabButton('sensors','Sensores')}${this.tabButton('telemetry','Telemetria')}${this.tabButton('architecture','Arquitetura')}${this.tabButton('challenge','Desafio DS')}
    </nav>
    <div class="technology-workspace">${this.tabMarkup()}</div>
  </section>`;}
  tabButton(id,label){return `<button class="${this.tab===id?'active':''}" data-action="set-tab" data-tab="${id}">${label}</button>`;}
  tabMarkup(){if(this.tab==='trails')return this.trailsMarkup();if(this.tab==='technologies')return this.technologiesMarkup();if(this.tab==='languages')return this.languagesMarkup();if(this.tab==='sensors')return this.sensorsMarkup();if(this.tab==='telemetry')return this.telemetryMarkup();if(this.tab==='architecture')return this.architectureMarkup();return this.challengeMarkup();}
  trailsMarkup(){const active=this.trailEngine()?.active?.();return `<section class="guided-trails-panel">
    <div class="technology-section-head"><div><span class="eyebrow">Modo guiado</span><h3>Escolha um percurso com começo, meio e conclusão</h3><p>Cada trilha abre os laboratórios na ordem correta, apresenta o objetivo atual e registra o progresso separadamente por aluno.</p></div>${active?`<article class="active-trail-summary"><span>TRILHA ATIVA</span><b>${escapeHtml(this.trailEngine().definition(active.trailId)?.title)}</b><small>${active.completed}/${active.total} etapas · ${active.percent}%</small><button data-action="open-current-step">Continuar etapa</button></article>`:''}</div>
    <div class="guided-trail-grid">${GUIDED_TRAILS.map(trail=>this.trailCard(trail)).join('')}</div>
    <article class="guided-rules"><strong>Como funciona</strong><span>1. Inicie uma trilha.</span><span>2. Abra o laboratório indicado.</span><span>3. Realize o objetivo apresentado no HUD.</span><span>4. Registre a etapa e avance sem pular a sequência.</span></article>
  </section>`;}
  trailCard(trail){const state=this.trailEngine()?.status?.(trail.id)||{state:'READY',percent:0,completed:0,total:trail.steps.length,currentStep:trail.steps[0]};const action=state.state==='COMPLETED'?'review-trail':state.state==='READY'?'start-trail':'resume-trail';const label=state.state==='COMPLETED'?'Revisar trilha':state.state==='READY'?'Iniciar trilha':'Continuar trilha';return `<article class="guided-trail-card" style="--trail:${trail.accent}"><header><span>${trail.icon}</span><div><small>${escapeHtml(trail.level)} · ${escapeHtml(trail.duration)}</small><h4>${escapeHtml(trail.title)}</h4></div></header><p>${escapeHtml(trail.summary)}</p><div class="trail-progress"><i style="width:${state.percent}%"></i></div><div class="trail-meta"><span>${state.completed}/${state.total} etapas</span><b>${statusLabel(state.state)}</b></div><ol>${trail.steps.slice(0,3).map(step=>`<li>${escapeHtml(step.title)}</li>`).join('')}<li>+ ${Math.max(0,trail.steps.length-3)} etapas</li></ol><footer><button data-action="${action}" data-trail="${trail.id}">${label}</button>${state.state!=='READY'?`<button class="secondary" data-action="reset-trail" data-trail="${trail.id}">Reiniciar</button>`:''}</footer></article>`;}
  technologiesMarkup(){const selected=this.engine.getTechnology(this.selectedTechnology);return `<section class="technology-catalog-layout"><aside><label class="technology-search">⌕ <input id="technology-search" placeholder="Buscar tecnologia, ferramenta ou módulo"></label><div id="technology-results">${this.technologyList(SPACE_TECHNOLOGIES)}</div></aside><article class="technology-detail-panel"><span class="technology-big-icon">${selected.icon}</span><small>${escapeHtml(selected.category)}</small><h3>${escapeHtml(selected.name)}</h3><p>${escapeHtml(selected.summary)}</p><h4>Ferramentas e conceitos</h4><div class="technology-chip-row">${selected.tools.map(item=>`<span>${escapeHtml(item)}</span>`).join('')}</div><h4>Riscos estudados</h4><div class="technology-chip-row warning">${selected.risks.map(item=>`<span>${escapeHtml(item)}</span>`).join('')}</div><h4>Laboratórios relacionados</h4><div class="technology-module-links">${selected.modules.map(id=>`<button data-action="open-related-module" data-module="${id}">${escapeHtml(id)}</button>`).join('')}</div></article></section>`;}
  technologyList(items){return items.map(item=>`<button class="technology-list-item ${item.id===this.selectedTechnology?'active':''}" data-action="select-technology" data-id="${item.id}"><span>${item.icon}</span><div><b>${escapeHtml(item.name)}</b><small>${escapeHtml(item.category)}</small></div></button>`).join('')||'<p class="empty-state">Nenhuma tecnologia encontrada.</p>';}
  languagesMarkup(){const language=this.engine.getLanguage(this.selectedLanguage);return `<section class="technology-language-layout"><aside>${SPACE_LANGUAGES_C2.map(item=>`<button class="${item.id===language.id?'active':''}" data-action="select-language-c2" data-id="${item.id}"><b>${escapeHtml(item.name)}</b><small>${escapeHtml(item.layer)}</small></button>`).join('')}</aside><article><span class="eyebrow">${escapeHtml(language.layer)}</span><h3>${escapeHtml(language.name)}</h3><div class="language-role-card"><span>APLICAÇÃO DIDÁTICA</span><p>${escapeHtml(language.role)}</p></div><div class="language-role-card success"><span>PONTO FORTE</span><p>${escapeHtml(language.strength)}</p></div><div class="language-role-card warning"><span>CUIDADO</span><p>${escapeHtml(language.caution)}</p></div><button class="button secondary" data-action="open-related-module" data-module="languages">Abrir laboratório completo de linguagens</button></article></section>`;}
  sensorsMarkup(){const sensor=this.engine.getSensor(this.selectedSensor),reading=this.sensorReading||this.engine.sensorReading(sensor.id,Date.now(),this.sensorFault);return `<section class="sensor-lab-layout"><aside class="sensor-list">${SPACE_SENSORS.map(item=>`<button class="${item.id===sensor.id?'active':''}" data-action="select-sensor" data-id="${item.id}"><b>${escapeHtml(item.name)}</b><small>${escapeHtml(item.unit)}</small></button>`).join('')}</aside><article class="sensor-console"><header><div><span class="eyebrow">Leitura simulada</span><h3>${escapeHtml(sensor.name)}</h3></div><button class="sensor-fault-toggle ${this.sensorFault?'on':''}" data-action="toggle-sensor-fault">${this.sensorFault?'Falha ativa':'Injetar falha'}</button></header><div class="sensor-gauge ${reading.status}"><strong id="sensor-live-value">${reading.value}</strong><span>${escapeHtml(reading.unit)}</span><i style="--sensor-level:${Math.max(0,Math.min(100,(reading.value-sensor.min)/(sensor.max-sensor.min)*100))}%"></i></div><p>${escapeHtml(sensor.use)}</p><div class="sensor-range"><span>mín. ${sensor.min} ${escapeHtml(sensor.unit)}</span><span>normal ${sensor.normal[0]}–${sensor.normal[1]}</span><span>máx. ${sensor.max} ${escapeHtml(sensor.unit)}</span></div><h4>Aplicações</h4><div class="technology-chip-row">${sensor.vehicles.map(item=>`<span>${escapeHtml(item)}</span>`).join('')}</div></article></section>`;}
  telemetryMarkup(){const scenario=TELEMETRY_SCENARIOS[this.telemetryIndex%TELEMETRY_SCENARIOS.length],result=this.telemetryResult;return `<section class="telemetry-lab"><article class="telemetry-packet"><header><span>PACOTE ${this.telemetryIndex+1}/${TELEMETRY_SCENARIOS.length}</span><b>${escapeHtml(scenario.title)}</b></header><pre>${escapeHtml(JSON.stringify(scenario.packet,null,2))}</pre><div class="telemetry-actions"><button data-action="validate-telemetry">Validar pacote</button><button class="secondary" data-action="next-telemetry">Próximo cenário</button></div></article><article class="telemetry-diagnostic ${result?.status||''}"><span class="eyebrow">Diagnóstico</span><h3>${result?result.status.toUpperCase():'AGUARDANDO'}</h3><p>${result?escapeHtml(result.explanation):'Analise sensor, unidade, valor, sequência e estado antes de aceitar o pacote.'}</p>${result?.reasons?.length?`<ul>${result.reasons.map(item=>`<li>${escapeHtml(item)}</li>`).join('')}</ul>`:''}<div class="telemetry-pipeline"><span>Sensor</span><i>→</i><span>Validação</span><i>→</i><span>Fila</span><i>→</i><span>Painel</span><i>→</i><span>Banco</span></div></article></section>`;}
  architectureMarkup(){const layer=DIGITAL_ARCHITECTURE_LAYERS.find(item=>item.id===this.selectedLayer)||DIGITAL_ARCHITECTURE_LAYERS[0];return `<section class="architecture-visual"><canvas id="technology-network-canvas" aria-label="Fluxo visual da arquitetura digital"></canvas><div class="architecture-node-row">${DIGITAL_ARCHITECTURE_LAYERS.map(item=>`<button class="${item.id===layer.id?'active':''}" data-action="select-layer" data-id="${item.id}"><span>${String(item.order).padStart(2,'0')}</span><b>${escapeHtml(item.title)}</b></button>`).join('')}</div><article class="architecture-layer-detail"><span>CAMADA ${String(layer.order).padStart(2,'0')}</span><h3>${escapeHtml(layer.title)}</h3><p>${escapeHtml(layer.detail)}</p><button class="button secondary" data-action="open-current-step">Usar em uma trilha guiada</button></article></section>`;}
  challengeMarkup(){if(this.challengeIndex>=TECHNOLOGY_CHALLENGES.length)return `<article class="technology-completion"><span class="eyebrow">Desafio concluído</span><h3>Arquitetura espacial analisada</h3><p>Você relacionou linguagens, sensores, dados e camadas pelo contexto do problema.</p><strong>${this.challengeScore}/${TECHNOLOGY_CHALLENGES.length}</strong><button data-action="restart-challenge">Revisar desafio</button></article>`;const challenge=TECHNOLOGY_CHALLENGES[this.challengeIndex];return `<section class="technology-challenge"><article><span class="eyebrow">Questão ${this.challengeIndex+1}/${TECHNOLOGY_CHALLENGES.length}</span><h3>${escapeHtml(challenge.prompt)}</h3><div class="technology-answer-grid">${challenge.options.map(option=>`<button data-action="answer-technology" data-answer="${option}">${escapeHtml(this.answerLabel(option))}</button>`).join('')}</div>${this.challengeFeedback?`<p class="challenge-feedback">${escapeHtml(this.challengeFeedback)}</p>`:''}</article><aside><strong>${this.challengeScore}</strong><span>acertos</span><small>Recompensa final: 260 XP</small></aside></section>`;}
  answerLabel(id){return SPACE_TECHNOLOGIES.find(item=>item.id===id)?.name||SPACE_LANGUAGES_C2.find(item=>item.id===id)?.name||SPACE_SENSORS.find(item=>item.id===id)?.name||DIGITAL_ARCHITECTURE_LAYERS.find(item=>item.id===id)?.title||id;}
  handleClick(event){const target=event.target.closest('[data-action]');if(!target)return;const action=target.dataset.action;
    if(action==='back')return this.context.onBack();
    if(action==='set-tab'){this.tab=target.dataset.tab;this.rerender();return;}
    if(action==='select-technology'){this.selectedTechnology=target.dataset.id;this.rerender();return;}
    if(action==='select-language-c2'){this.selectedLanguage=target.dataset.id;this.rerender();return;}
    if(action==='select-sensor'){this.selectedSensor=target.dataset.id;this.sensorFault=false;this.rerender();return;}
    if(action==='toggle-sensor-fault'){this.sensorFault=!this.sensorFault;this.rerender();return;}
    if(action==='open-related-module')return this.context.openModule(target.dataset.module);
    if(action==='select-layer'){this.selectedLayer=target.dataset.id;this.renderer?.setActive(this.selectedLayer);this.rerender();return;}
    if(action==='start-trail'||action==='resume-trail'||action==='review-trail'){const id=target.dataset.trail;const state=action==='start-trail'?this.trailEngine().start(id):action==='review-trail'?(this.trailEngine().reset(id),this.trailEngine().start(id)):this.trailEngine().resume(id);this.context.toast(`Trilha iniciada: ${this.trailEngine().definition(id).title}.`);this.context.openModule(state.currentStep.moduleId);return;}
    if(action==='reset-trail'){if(confirm('Reiniciar esta trilha e apagar o progresso dela?')){this.trailEngine().reset(target.dataset.trail);this.context.toast('Trilha reiniciada.');this.rerender();}return;}
    if(action==='open-current-step'){const active=this.trailEngine().active();if(active?.currentStep)this.context.openModule(active.currentStep.moduleId);else this.context.toast('Inicie uma trilha guiada primeiro.');return;}
    if(action==='validate-telemetry'){const scenario=TELEMETRY_SCENARIOS[this.telemetryIndex%TELEMETRY_SCENARIOS.length],validation=this.engine.validatePacket(scenario.packet,{previousSequence:scenario.previousSequence??null});this.telemetryResult={...validation,explanation:scenario.explanation};if(validation.status===scenario.expected){this.context.profileStore.addXp(25,`c21-telemetry-${scenario.id}`);this.context.toast('Diagnóstico coerente com o cenário.');}this.render();return;}
    if(action==='next-telemetry'){this.telemetryIndex=(this.telemetryIndex+1)%TELEMETRY_SCENARIOS.length;this.telemetryResult=null;this.render();return;}
    if(action==='answer-technology'){const challenge=TECHNOLOGY_CHALLENGES[this.challengeIndex],correct=target.dataset.answer===challenge.answer;if(correct){this.challengeScore++;this.challengeIndex++;this.challengeFeedback=challenge.explanation;if(this.challengeIndex===TECHNOLOGY_CHALLENGES.length){this.context.profileStore.addXp(260,'c21-technology-challenge');this.context.toast('Desafio de tecnologia concluído: +260 XP.');}}else{this.challengeFeedback='Revise a função principal de cada opção antes de responder.';this.context.toast('A escolha não atende ao objetivo principal.');}this.render();return;}
    if(action==='restart-challenge'){this.challengeIndex=0;this.challengeScore=0;this.challengeFeedback='';this.render();return;}
  }
  handleInput(event){if(event.target.id!=='technology-search')return;const results=this.engine.search(event.target.value);const host=this.container.querySelector('#technology-results');if(host)host.innerHTML=this.technologyList(results);}
  rerender(){this.stopVisuals();this.render();this.startVisuals();}
  startVisuals(){if(this.tab==='architecture'){const canvas=this.container.querySelector('#technology-network-canvas');this.renderer=new TechnologyNetworkRenderer({canvas,reducedMotion:this.context.settingsStore.get().reducedMotion});this.renderer.start(DIGITAL_ARCHITECTURE_LAYERS);this.renderer.setActive(this.selectedLayer);}if(this.tab==='sensors'){const update=()=>{const sensor=this.engine.getSensor(this.selectedSensor);this.sensorReading=this.engine.sensorReading(sensor.id,Date.now(),this.sensorFault);const value=this.container.querySelector('#sensor-live-value');if(value)value.textContent=this.sensorReading.value;};update();this.sensorTimer=setInterval(update,700);}}
  stopVisuals(){clearInterval(this.sensorTimer);this.sensorTimer=0;this.renderer?.destroy();this.renderer=null;}
}

export function createModule(){return new TechnologyHubModule();}
