(() => {
'use strict';
const canvas=document.getElementById('avatarCanvas'); if(!canvas) return;
const status=document.getElementById('avatar3dStatus'); const loading=document.getElementById('avatar3dLoading');
const contextOptions={antialias:true,alpha:true,premultipliedAlpha:false,powerPreference:'high-performance',failIfMajorPerformanceCaveat:false,desynchronized:true};
const gl=canvas.getContext('webgl2',contextOptions)||canvas.getContext('webgl',contextOptions);
if(!gl){status.textContent='WebGL indisponível — fallback visual HQ';loading.hidden=true;document.getElementById('avatarFallback').hidden=true;canvas.hidden=true;window.DSVisualRecovery?.showFallback?.('WebGL indisponível');document.dispatchEvent(new CustomEvent('ds-avatar-ready',{detail:{mode:'fallback2d',equipped:[],qualityFallback:'hq'}}));return;}
const shaderPack=window.DSRendererProfile?.shaderSources?.()||{};
const V=shaderPack.vertex||`attribute vec3 a_position;attribute vec3 a_normal;uniform mat4 u_model,u_view,u_proj;varying vec3 v_n;varying vec3 v_w;void main(){vec4 w=u_model*vec4(a_position,1.0);v_w=w.xyz;v_n=normalize(mat3(u_model)*a_normal);gl_Position=u_proj*u_view*w;}`;
const F=shaderPack.fragment||`precision mediump float;varying vec3 v_n;uniform vec4 u_color;uniform vec3 u_emissive;uniform float u_metallic,u_roughness;void main(){vec3 n=normalize(v_n),l=normalize(vec3(.65,.9,.75));float d=max(dot(n,l),0.0);gl_FragColor=vec4(u_color.rgb*(.2+d*.8)+u_emissive,u_color.a);}`;
function shader(type,src){const s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s}
const program=gl.createProgram();gl.attachShader(program,shader(gl.VERTEX_SHADER,V));gl.attachShader(program,shader(gl.FRAGMENT_SHADER,F));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(program));gl.useProgram(program);
const loc={p:gl.getAttribLocation(program,'a_position'),n:gl.getAttribLocation(program,'a_normal'),m:gl.getUniformLocation(program,'u_model'),v:gl.getUniformLocation(program,'u_view'),pr:gl.getUniformLocation(program,'u_proj'),c:gl.getUniformLocation(program,'u_color'),e:gl.getUniformLocation(program,'u_emissive'),met:gl.getUniformLocation(program,'u_metallic'),rough:gl.getUniformLocation(program,'u_roughness'),...((window.DSRendererProfile?.bind?.(gl,program))||{})};
const M={id:()=>new Float32Array([1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]),mul:(a,b)=>{let o=new Float32Array(16);for(let c=0;c<4;c++)for(let r=0;r<4;r++)o[c*4+r]=a[r]*b[c*4]+a[4+r]*b[c*4+1]+a[8+r]*b[c*4+2]+a[12+r]*b[c*4+3];return o},trs:(t,q,s)=>{let[x,y,z,w]=q,x2=x+x,y2=y+y,z2=z+z,xx=x*x2,xy=x*y2,xz=x*z2,yy=y*y2,yz=y*z2,zz=z*z2,wx=w*x2,wy=w*y2,wz=w*z2;return new Float32Array([(1-(yy+zz))*s[0],(xy+wz)*s[0],(xz-wy)*s[0],0,(xy-wz)*s[1],(1-(xx+zz))*s[1],(yz+wx)*s[1],0,(xz+wy)*s[2],(yz-wx)*s[2],(1-(xx+yy))*s[2],0,t[0],t[1],t[2],1])},persp:(fov,a,n,f)=>{let z=1/Math.tan(fov/2),nf=1/(n-f);return new Float32Array([z/a,0,0,0,0,z,0,0,0,0,(f+n)*nf,-1,0,0,2*f*n*nf,0])},look:(eye,target,up)=>{let zx=eye[0]-target[0],zy=eye[1]-target[1],zz=eye[2]-target[2],zl=Math.hypot(zx,zy,zz);zx/=zl;zy/=zl;zz/=zl;let xx=up[1]*zz-up[2]*zy,xy=up[2]*zx-up[0]*zz,xz=up[0]*zy-up[1]*zx,xl=Math.hypot(xx,xy,xz);xx/=xl;xy/=xl;xz/=xl;let yx=zy*xz-zz*xy,yy=zz*xx-zx*xz,yz=zx*xy-zy*xx;return new Float32Array([xx,yx,zx,0,xy,yy,zy,0,xz,yz,zz,0,-(xx*eye[0]+xy*eye[1]+xz*eye[2]),-(yx*eye[0]+yy*eye[1]+yz*eye[2]),-(zx*eye[0]+zy*eye[1]+zz*eye[2]),1])}};
function slerp(a,b,t){let cos=a[0]*b[0]+a[1]*b[1]+a[2]*b[2]+a[3]*b[3],bb=b;if(cos<0){cos=-cos;bb=b.map(v=>-v)}if(cos>.9995){let r=a.map((v,i)=>v+(bb[i]-v)*t),l=Math.hypot(...r);return r.map(v=>v/l)}let th=Math.acos(cos),sin=Math.sin(th);return a.map((v,i)=>(Math.sin((1-t)*th)*v+Math.sin(t*th)*bb[i])/sin)}
function qmul(a,b){return[a[3]*b[0]+a[0]*b[3]+a[1]*b[2]-a[2]*b[1],a[3]*b[1]-a[0]*b[2]+a[1]*b[3]+a[2]*b[0],a[3]*b[2]+a[0]*b[1]-a[1]*b[0]+a[2]*b[3],a[3]*b[3]-a[0]*b[0]-a[1]*b[1]-a[2]*b[2]]}
function qaxis(axis,angle){let h=angle/2,s=Math.sin(h);return[axis[0]*s,axis[1]*s,axis[2]*s,Math.cos(h)]}
const normalizeQuality=q=>({economy:'basic',balanced:'intermediate',high:'advanced',ultraAdvanced:'realism'}[q]||q);
let avatar=null,clips={},active='Idle',start=performance.now(),yaw=.45,pitch=.08,dist=9.2,auto=true,drag=false,last=[0,0],quality=normalizeQuality(document.body.dataset.quality||'intermediate'),transitionPose=null,transitionStart=0,transitionDuration=260,activePresetId=null,rigFocus='full',motionScale=1;
let currentLod=quality==='basic'?'avatar-tech-v1-lod2.glb':(['advanced','ultra','realism'].includes(quality)?'avatar-tech-v1-lod0.glb':'avatar-tech-v1-lod1.glb');
const equipmentCatalog=(window.DS_EQUIPMENT?.items||[]); const presets=(window.DS_EQUIPMENT?.presets||[]);
const assetCache=new Map(),equipped=new Map(),slotOwners=new Map();
const LOADOUT_KEY='ds-avatar-loadout-v1';
function savedLoadout(){const profileItems=window.DSAvatarProfile?.getState?.().equippedItems;if(Array.isArray(profileItems))return profileItems.filter(id=>equipmentCatalog.some(x=>x.id===id));try{const value=JSON.parse(localStorage.getItem(LOADOUT_KEY)||'null');return Array.isArray(value?.items)?value.items.filter(id=>equipmentCatalog.some(x=>x.id===id)):[]}catch(_){return[]}}
function persistLoadout(){const items=[...equipped.keys()];try{localStorage.setItem(LOADOUT_KEY,JSON.stringify({version:1,items,activePresetId,updatedAt:new Date().toISOString()}))}catch(_){}window.DSAvatarProfile?.setEquipped?.(items,{source:'viewer'});document.dispatchEvent(new CustomEvent('ds-avatar-loadout-change',{detail:{items,activePresetId}}))}
function capturePose(){return avatar?.nodes.map(n=>({t:[...n.t],r:[...n.r],s:[...n.s]}))||null}
function rotateBone(name,axis,angle){const n=avatar?.nodes.find(x=>x.name===name);if(n)n.r=qmul(n.r,qaxis(axis,angle))}
function smoothstep(v){v=Math.max(0,Math.min(1,v));return v*v*(3-2*v)}
function rigAllows(group){return rigFocus==='full'||rigFocus===group||(rigFocus==='arms'&&group.includes('arm'))||(rigFocus==='legs'&&group.includes('leg'))}
function secondaryMotion(now){if(!avatar)return;const t=(now-start)/1000,motion=(quality==='basic'?.55:quality==='intermediate'?.78:quality==='advanced'?1:quality==='ultra'?1.12:1.22)*motionScale;const breath=Math.sin(t*1.55);if(active==='Idle'){if(rigAllows('core')){rotateBone('B_SpineLower',[1,0,0],breath*.009*motion);rotateBone('B_Chest',[1,0,0],-breath*.007*motion);rotateBone('B_Head',[0,1,0],Math.sin(t*.72)*.025*motion)}if(rigAllows('left-arm'))rotateBone('B_WristL',[0,0,1],breath*.018*motion);if(rigAllows('right-arm'))rotateBone('B_WristR',[0,0,1],-breath*.018*motion)}if(active==='Walk'||active==='Run'||active==='WalkShowcase'){const speed=active==='Run'?9:active==='WalkShowcase'?5.5:5.2,amp=active==='Run'?.72:.42,phase=Math.sin(t*speed);if(rigAllows('left-leg')){rotateBone('B_KneeL',[1,0,0],Math.max(0,phase)*amp);rotateBone('B_AnkleL',[1,0,0],-phase*.16)}if(rigAllows('right-leg')){rotateBone('B_KneeR',[1,0,0],Math.max(0,-phase)*amp);rotateBone('B_AnkleR',[1,0,0],phase*.16)}if(rigAllows('core')){rotateBone('B_SpineLower',[0,1,0],phase*.04);rotateBone('B_Chest',[0,1,0],-phase*.035)}}if((active==='Wave'||active==='Goodbye')&&rigAllows('right-arm')){rotateBone('B_WristR',[0,0,1],Math.sin(t*10)*.18*motion);rotateBone('B_PalmR',[0,0,1],Math.sin(t*10+1)*.07*motion)}if(active==='DanceLoop'){if(rigAllows('core')){rotateBone('B_Head',[0,1,0],Math.sin(t*3.4)*.16);rotateBone('B_Chest',[0,1,0],Math.sin(t*4)*.09)}if(rigAllows('left-leg'))rotateBone('B_AnkleL',[1,0,0],Math.sin(t*6)*.12);if(rigAllows('right-leg'))rotateBone('B_AnkleR',[1,0,0],Math.sin(t*6+Math.PI)*.12)}}
const SLOT_NODE={'hair':'SLOT_HAIR','head':'SLOT_HEAD','face':'SLOT_FACE','torso':'SLOT_TORSO','back':'SLOT_BACK','shield':'SLOT_SHIELD','held-item-left':'SLOT_HAND_L','held-item-right':'SLOT_HAND_R','companion':'SLOT_COMPANION','shoulder-left':'SLOT_SHOULDER_L','shoulder-right':'SLOT_SHOULDER_R','waist':'SLOT_WAIST','foot-left':'SLOT_FOOT_L','foot-right':'SLOT_FOOT_R','vehicle':'SLOT_VEHICLE'};
const BASE_PARTS={hair:['M_HairTop','M_HairBack','M_HairFront','M_HairDetail0','M_HairDetail1','M_HairDetail2','M_HairDetail3','M_HairCyanStripe'],torso:['M_Torso','M_ShirtPanel','M_Core'],feet:['M_BootL','M_BootGlowL','M_BootR','M_BootGlowR']};
function accessor(gltf,bin,i){const a=gltf.accessors[i],v=gltf.bufferViews[a.bufferView],off=(v.byteOffset||0)+(a.byteOffset||0),comps={SCALAR:1,VEC2:2,VEC3:3,VEC4:4}[a.type],ctors={5126:Float32Array,5123:Uint16Array,5125:Uint32Array,5121:Uint8Array},Ctor=ctors[a.componentType];return new Ctor(bin,off,a.count*comps)}
function parseChunks(ab){const dv=new DataView(ab);if(dv.getUint32(0,true)!==0x46546c67)throw Error('GLB inválido');let p=12,json=null,bin=null;while(p<ab.byteLength){let len=dv.getUint32(p,true),typ=dv.getUint32(p+4,true),data=ab.slice(p+8,p+8+len);if(typ===0x4e4f534a)json=JSON.parse(new TextDecoder().decode(data));if(typ===0x004e4942)bin=data;p+=8+len}return{json,bin}}
function gpuModel(ab,animated=false){const {json,bin}=parseChunks(ab);const materials=(json.materials||[]).map(m=>{let q=m.pbrMetallicRoughness||{};return{color:q.baseColorFactor||[1,1,1,1],metal:q.metallicFactor||0,rough:q.roughnessFactor??.7,em:m.emissiveFactor||[0,0,0]}});const meshes=(json.meshes||[]).map(m=>m.primitives.map(pr=>{let pos=accessor(json,bin,pr.attributes.POSITION),norm=accessor(json,bin,pr.attributes.NORMAL),idx=accessor(json,bin,pr.indices);let pb=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,pb);gl.bufferData(gl.ARRAY_BUFFER,pos,gl.STATIC_DRAW);let nb=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,nb);gl.bufferData(gl.ARRAY_BUFFER,norm,gl.STATIC_DRAW);let ib=gl.createBuffer();gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,ib);gl.bufferData(gl.ELEMENT_ARRAY_BUFFER,idx,gl.STATIC_DRAW);return{pb,nb,ib,count:idx.length,type:idx instanceof Uint32Array?gl.UNSIGNED_INT:gl.UNSIGNED_SHORT,mat:pr.material||0}}));const nodes=(json.nodes||[]).map((n,i)=>({i,name:n.name||'node'+i,mesh:n.mesh,children:n.children||[],baseT:n.translation||[0,0,0],baseR:n.rotation||[0,0,0,1],baseS:n.scale||[1,1,1],t:[...(n.translation||[0,0,0])],r:[...(n.rotation||[0,0,0,1])],s:[...(n.scale||[1,1,1])],extras:n.extras||{},visible:n.extras?.defaultVisible!==false,world:M.id()}));let gpuBytes=0;for(const mm of meshes)for(const p of mm)gpuBytes+=p.count*(p.type===gl.UNSIGNED_INT?4:2)+p.count*3*4*2;let model={json,materials,meshes,nodes,roots:json.scenes[json.scene||0].nodes,gpuBytes};if(animated){model.clips={};(json.animations||[]).forEach(a=>{let channels=a.channels.map(ch=>{let sm=a.samplers[ch.sampler];return{node:ch.target.node,path:ch.target.path,times:Array.from(accessor(json,bin,sm.input)),values:Array.from(accessor(json,bin,sm.output)),comps:ch.target.path==='rotation'?4:3}});let dur=Math.max(...channels.flatMap(c=>c.times));model.clips[a.name]={name:a.name,channels,duration:dur,loop:a.extras?.loop!==false}})}return model}
function disposeGpuModel(m){if(!m)return;for(const mm of m.meshes||[])for(const p of mm){try{gl.deleteBuffer(p.pb);gl.deleteBuffer(p.nb);gl.deleteBuffer(p.ib)}catch(_){}}}
function releaseUnusedEquipment(){const keep=new Set(equipped.keys());for(const [id,m] of [...assetCache.entries()]){if(keep.has(id))continue;disposeGpuModel(m);assetCache.delete(id);window.DSCacheMemory?.unregister?.(`avatar-equip:${id}`,'avatar-equipment-lru')}}
async function fetchBytes(path){try{return window.DSAssetTransfer?.fetchArrayBuffer?await window.DSAssetTransfer.fetchArrayBuffer(path):await (async()=>{const r=await fetch(path,{cache:'force-cache'});if(r.ok)return r.arrayBuffer();throw Error(`HTTP ${r.status}`)})()}catch(e){throw Error('Asset não encontrado: '+path+' • '+(e?.message||e))}}
async function loadAvatar(file,restoreItems=null){loading.hidden=false;status.textContent='Carregando avatar, rig e slots...';if(avatar)disposeGpuModel(avatar);avatar=gpuModel(await fetchBytes('../assets/avatars/avatar-tech-v1/'+file),true);window.DSCacheMemory?.register?.({id:'avatar:base',label:'Avatar Tech DS',module:'avatar',type:'gpu-model',bytes:avatar.gpuBytes||0,pinned:true,transient:false,dispose:()=>disposeGpuModel(avatar)});clips=avatar.clips||{};active=clips[active]?active:'Idle';start=performance.now();transitionPose=null;equipped.clear();slotOwners.clear();const items=Array.isArray(restoreItems)?restoreItems:savedLoadout();if(items.length){activePresetId=null;for(const id of items)await equip(id,true,false)}else await applyPreset('preset-tech-student',true,false);loading.hidden=true;status.textContent=`Rig 2.0 • ${avatar.nodes.length} nós • ${Object.keys(clips).length} animações • ${equipped.size} itens`;window.DSAvatarViewer={play,rotate:v=>yaw+=v,toggleAuto:()=>auto=!auto,setQuality,setCamera,equip,unequip,applyPreset,releaseUnusedEquipment,getEquipped:()=>[...equipped.keys()],getActiveAnimation:()=>active,setRigFocus:(focus)=>{rigFocus=focus||'full';document.dispatchEvent(new CustomEvent('ds-rig-focus-change',{detail:{focus:rigFocus}}));return rigFocus},getRigFocus:()=>rigFocus,setMotionScale:(value)=>{motionScale=Math.max(.25,Math.min(1.5,Number(value)||1));return motionScale},getRigInfo:()=>({id:'DS_HUMANOID_VOXEL_RIG_2',nodes:avatar?.nodes.length||0,clips:Object.keys(clips).length,focus:rigFocus})};persistLoadout();document.dispatchEvent(new CustomEvent('ds-avatar-ready',{detail:{mode:'webgl',equipped:[...equipped.keys()]}}));}
async function loadEquipmentAsset(item){if(assetCache.has(item.id))return assetCache.get(item.id);status.textContent='Carregando '+item.name+'...';let p='../'+item.model3d;let asset=gpuModel(await fetchBytes(p),false);assetCache.set(item.id,asset);window.DSCacheMemory?.register?.({id:`avatar-equip:${item.id}`,label:item.name,module:'avatar',type:'gpu-equipment',bytes:asset.gpuBytes||0,transient:true,dispose:()=>{if(!equipped.has(item.id)){disposeGpuModel(asset);assetCache.delete(item.id)}}});status.textContent='Item pronto: '+item.name;return asset}
function itemById(id){return equipmentCatalog.find(x=>x.id===id)}
function basePartVisibility(slot,visible){if(!avatar)return;let key=slot==='foot-left'||slot==='foot-right'?'feet':slot;let names=BASE_PARTS[key]||[];avatar.nodes.forEach(n=>{if(names.includes(n.name))n.visible=visible})}
async function equip(id,quiet=false,shouldPersist=true){const item=itemById(id);if(!item)return;await loadEquipmentAsset(item);const attachments=(item.attachments||[]).filter(a=>!a.variant);for(const att of attachments){const old=slotOwners.get(att.slot);if(old&&old!==id)unequip(old,true,false);slotOwners.set(att.slot,id);basePartVisibility(att.slot,false)}equipped.set(id,{item,asset:assetCache.get(id),attachments});activePresetId=null;updateEquipmentUI();if(shouldPersist)persistLoadout();if(!quiet)status.textContent='Equipado: '+item.name;return item}
function unequip(id,quiet=false,shouldPersist=true){const entry=equipped.get(id);if(!entry)return;for(const att of entry.attachments){if(slotOwners.get(att.slot)===id)slotOwners.delete(att.slot);basePartVisibility(att.slot,true)}equipped.delete(id);activePresetId=null;updateEquipmentUI();if(shouldPersist)persistLoadout();if(!quiet)status.textContent='Removido: '+entry.item.name}
async function applyPreset(presetId,quiet=false,shouldPersist=true){const preset=presets.find(p=>p.id===presetId);if(!preset)return;for(const id of [...equipped.keys()])unequip(id,true,false);for(const id of preset.items)await equip(id,true,false);activePresetId=presetId;updateEquipmentUI();if(shouldPersist)persistLoadout();if(!quiet)status.textContent='Conjunto aplicado: '+preset.name}
function updateEquipmentUI(){document.querySelectorAll('[data-equip-item]').forEach(b=>b.classList.toggle('active',equipped.has(b.dataset.equipItem)));document.querySelectorAll('[data-preset]').forEach(b=>b.classList.toggle('active',b.dataset.preset===activePresetId));const count=document.getElementById('equippedCount');if(count)count.textContent=equipped.size;}
function play(name){let map={'Acenar':'Wave','Tchau':'Goodbye','Comemorar':'Celebrate','Pular':'Jump','Aplaudir':'Applause','Pensar':'Think','Apontar':'Point','Sentar':'Sit','Dançar':'DanceLoop','Digitar':'TypeComputer','Estudar':'StudyNotebook','Apresentar':'PresentProject','Scanner':'UseScanner','Foguete':'RocketCelebrate','Ativar aura':'AuraPowerUp','Agachar':'Crouch','Virar':'TurnAround','Olhar':'LookAround','Alongar':'ArmStretch','Joelhos':'KneeLift','Vitória':'VictoryPose','Desfile':'WalkShowcase','Reverência':'Bow','Positivo':'ThumbsUp','Agachamento':'SquatPulse'};name=map[name]||name;if(clips[name]){transitionPose=capturePose();transitionStart=performance.now();transitionDuration=(quality==='basic'?180:quality==='intermediate'?230:260);active=name;start=transitionStart;status.textContent='Animação: '+name;document.dispatchEvent(new CustomEvent('ds-avatar-animation-change',{detail:{clip:name}}))}}
function setCamera(mode){auto=mode==='360';pitch=.08;if(mode==='front')yaw=0;if(mode==='back')yaw=Math.PI;if(mode==='360')yaw=.45;document.querySelectorAll('[data-camera]').forEach(b=>b.classList.toggle('active',b.dataset.camera===mode));}
async function setQuality(q){quality=normalizeQuality(q);q=quality;let f=q==='basic'?'avatar-tech-v1-lod2.glb':(['advanced','ultra','realism'].includes(q))?'avatar-tech-v1-lod0.glb':'avatar-tech-v1-lod1.glb';if(f!==currentLod){currentLod=f;const current=[...equipped.keys()];equipped.clear();slotOwners.clear();await loadAvatar(f,current)}}
function updateAnim(now){if(!avatar)return;avatar.nodes.forEach(n=>{n.t=[...n.baseT];n.r=[...n.baseR];n.s=[...n.baseS]});let c=clips[active]||clips.Idle;if(!c)return;let sec=(now-start)/1000;if(!c.loop&&sec>c.duration){transitionPose=capturePose();transitionStart=now;active='Idle';start=now;c=clips.Idle;sec=0;document.dispatchEvent(new CustomEvent('ds-avatar-animation-change',{detail:{clip:'Idle'}}))}let tm=c.loop?sec%c.duration:Math.min(sec,c.duration);for(let ch of c.channels){let i=0;while(i<ch.times.length-2&&tm>ch.times[i+1])i++;let t0=ch.times[i],t1=ch.times[Math.min(i+1,ch.times.length-1)],u=t1===t0?0:(tm-t0)/(t1-t0),a=ch.values.slice(i*ch.comps,i*ch.comps+ch.comps),b=ch.values.slice((i+1)*ch.comps,(i+1)*ch.comps+ch.comps),v=ch.path==='rotation'?slerp(a,b,u):a.map((x,j)=>x+(b[j]-x)*u);avatar.nodes[ch.node][ch.path==='translation'?'t':ch.path==='rotation'?'r':'s']=v}if(transitionPose){const k=smoothstep(Math.min(1,(now-transitionStart)/transitionDuration));avatar.nodes.forEach((n,i)=>{const from=transitionPose[i];if(!from)return;n.t=from.t.map((v,j)=>v+(n.t[j]-v)*k);n.s=from.s.map((v,j)=>v+(n.s[j]-v)*k);n.r=slerp(from.r,n.r,k)});if(k>=1)transitionPose=null}secondaryMotion(now)}
function drawPrimitive(p,mat,world){gl.bindBuffer(gl.ARRAY_BUFFER,p.pb);gl.enableVertexAttribArray(loc.p);gl.vertexAttribPointer(loc.p,3,gl.FLOAT,false,0,0);gl.bindBuffer(gl.ARRAY_BUFFER,p.nb);gl.enableVertexAttribArray(loc.n);gl.vertexAttribPointer(loc.n,3,gl.FLOAT,false,0,0);gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,p.ib);gl.uniformMatrix4fv(loc.m,false,world);gl.uniform4fv(loc.c,mat.color);gl.uniform3fv(loc.e,mat.em);gl.uniform1f(loc.met,mat.metal);gl.uniform1f(loc.rough,mat.rough);window.DSRendererProfile?.uniforms?.(gl,loc,quality);if(mat.color[3]<1){gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);gl.disable(gl.CULL_FACE)}else{gl.disable(gl.BLEND);gl.enable(gl.CULL_FACE)}gl.drawElements(gl.TRIANGLES,p.count,p.type,0)}
function drawNode(model,i,parent,visible=true){let n=model.nodes[i],local=M.trs(n.t,n.r,n.s);n.world=M.mul(parent,local);let vis=visible&&n.visible;if(vis&&n.mesh!==undefined)for(let p of model.meshes[n.mesh])drawPrimitive(p,model.materials[p.mat]||model.materials[0],n.world);for(let c of n.children)drawNode(model,c,n.world,vis)}
function slotWorld(slot){const name=SLOT_NODE[slot];const n=avatar?.nodes.find(x=>x.name===name);return n?.world||null}
function drawEquipment(){for(const {item,asset,attachments} of equipped.values()){for(const att of attachments){const parent=slotWorld(att.slot);if(!parent)continue;let scale=att.mirrorX?[-1,1,1]:[1,1,1],offset=att.offset||[0,0,0],rot=att.rotation||[0,0,0,1],base=M.mul(parent,M.trs(offset,rot,scale));for(const r of asset.roots)drawNode(asset,r,base)}}}
function resize(){let dpr=quality==='basic'?Math.min(devicePixelRatio,1.15):Math.min(devicePixelRatio,quality==='realism'?3:quality==='ultra'?2.5:quality==='advanced'?2:1.55),w=Math.floor(canvas.clientWidth*dpr),h=Math.floor(canvas.clientHeight*dpr);if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;gl.viewport(0,0,w,h)}}
function frame(now){resize();if(auto&&!drag)yaw+=.0025;updateAnim(now);gl.clearColor(0,0,0,0);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.enable(gl.DEPTH_TEST);gl.depthFunc(gl.LEQUAL);gl.enable(gl.CULL_FACE);gl.enable(gl.DITHER);let target=[0,3.15,0],eye=[target[0]+Math.sin(yaw)*Math.cos(pitch)*dist,target[1]+Math.sin(pitch)*dist,target[2]+Math.cos(yaw)*Math.cos(pitch)*dist],view=M.look(eye,target,[0,1,0]),proj=M.persp(Math.PI/4,canvas.width/canvas.height,.1,100);gl.uniformMatrix4fv(loc.v,false,view);gl.uniformMatrix4fv(loc.pr,false,proj);if(avatar){for(let r of avatar.roots)drawNode(avatar,r,M.id());drawEquipment()}requestAnimationFrame(frame)}
canvas.addEventListener('pointerdown',e=>{drag=true;last=[e.clientX,e.clientY];canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(!drag)return;yaw-=(e.clientX-last[0])*.008;pitch=Math.max(-.45,Math.min(.55,pitch+(e.clientY-last[1])*.006));last=[e.clientX,e.clientY]});canvas.addEventListener('pointerup',()=>drag=false);canvas.addEventListener('wheel',e=>{e.preventDefault();dist=Math.max(6.5,Math.min(14,dist+e.deltaY*.01))},{passive:false});
document.querySelectorAll('[data-camera]').forEach(b=>b.addEventListener('click',()=>setCamera(b.dataset.camera)));document.querySelectorAll('#avatarView [data-equip-item]').forEach(b=>b.addEventListener('click',()=>equipped.has(b.dataset.equipItem)?unequip(b.dataset.equipItem):equip(b.dataset.equipItem)));document.querySelectorAll('[data-preset]').forEach(b=>b.addEventListener('click',()=>applyPreset(b.dataset.preset)));window.addEventListener('ds-avatar-play',e=>play(e.detail));document.addEventListener('ds-view-change',e=>{if(e.detail.current!=='avatarView')setTimeout(releaseUnusedEquipment,900)});window.DSCacheMemory?.attachWebGL?.(canvas,{id:'avatar3d',module:'avatar',onRestore:()=>loadAvatar(currentLod,[...equipped.keys()])});document.addEventListener('ds-quality-change',e=>setQuality(e.detail.actual));document.getElementById('reduceMotion')?.addEventListener('change',e=>{if(e.target.checked){auto=false;play('Idle')}});
loadAvatar(currentLod).catch(e=>{console.error(e);status.textContent='Falha no GLB — fallback visual HQ';loading.hidden=true;canvas.hidden=true;document.getElementById('avatarFallback').hidden=true;window.DSVisualRecovery?.showFallback?.('Falha ao carregar o GLB')});requestAnimationFrame(frame);
})();
