(() => {
'use strict';
const INDEX=window.DS_PACKAGE_INDEX||{packs:[],modeRequirements:{}};
const DB_NAME='ds-store-package-manager'; const DB_VERSION=2; const STORE='packageState';
const SHARED_ASSET_CACHE='ds-store-assets-v1';
const CACHE_PREFIX='ds-store-pack';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const runtime={state:{installed:{},settings:{priority:'balanced',allowAutoDowngrade:true,preferredMode:'auto'},device:{}},tasks:new Map(),focusId:null,ready:false};
const supports={cache:'caches'in window,idb:'indexedDB'in window,sw:'serviceWorker'in navigator,storage:'storage'in navigator};
function fmt(n){if(!Number.isFinite(n))return '—';const u=['B','KB','MB','GB'];let x=n,i=0;while(x>=1024&&i<u.length-1){x/=1024;i++;}return `${x.toFixed(i?1:0)} ${u[i]}`;}
function toast(title,text,error=false){const host=$('#toastRegion');if(!host)return;const e=document.createElement('div');e.className='toast'+(error?' error':'');e.innerHTML=`<strong>${title}</strong><span>${text||''}</span>`;host.append(e);setTimeout(()=>e.remove(),4200);}
function openDB(){return new Promise((resolve,reject)=>{if(!supports.idb)return reject(new Error('IndexedDB indisponível'));const q=indexedDB.open(DB_NAME,DB_VERSION);q.onupgradeneeded=()=>{if(!q.result.objectStoreNames.contains(STORE))q.result.createObjectStore(STORE);};q.onsuccess=()=>resolve(q.result);q.onerror=()=>reject(q.error);});}
async function loadState(){try{const db=await openDB();const v=await new Promise((res,rej)=>{const q=db.transaction(STORE).objectStore(STORE).get('root');q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error);});db.close();if(v)runtime.state=v;}catch(e){try{const v=JSON.parse(localStorage.getItem('ds-package-state')||'null');if(v)runtime.state=v;}catch(_){}}
 runtime.state.installed ||= {}; runtime.state.settings ||= {priority:'balanced',allowAutoDowngrade:true,preferredMode:'auto'}; runtime.state.device ||= {}; runtime.state.fileIndex ||= {}; runtime.state.journal ||= [];
 const essentialVersion=pack('graphics-essential')?.version||'0.9.4.2';
 if(!runtime.state.installed['graphics-essential']||runtime.state.installed['graphics-essential'].virtual)runtime.state.installed['graphics-essential']={version:essentialVersion,status:'installed',installedAt:runtime.state.installed['graphics-essential']?.installedAt||new Date().toISOString(),bytesCached:0,virtual:true};
}
async function saveState(){runtime.state.updatedAt=new Date().toISOString();try{localStorage.setItem('ds-package-summary',JSON.stringify({version:2,installed:Object.fromEntries(Object.entries(runtime.state.installed||{}).map(([id,v])=>[id,{version:v.version,status:v.status}]))}));}catch(_){}try{const db=await openDB();await new Promise((res,rej)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(runtime.state,'root');tx.oncomplete=res;tx.onerror=()=>rej(tx.error);});db.close();}catch(e){try{localStorage.setItem('ds-package-state',JSON.stringify(runtime.state));}catch(_){}}}
function pack(id){return INDEX.packs.find(p=>p.id===id);} function installed(id){const s=runtime.state.installed[id];return !!s&&s.status==='installed'&&s.version===pack(id)?.version;}
function dependents(id){return INDEX.packs.filter(p=>(p.requires||[]).includes(id)&&installed(p.id)).map(p=>p.id);}
async function digest(buffer){const hash=await crypto.subtle.digest('SHA-256',buffer);return [...new Uint8Array(hash)].map(b=>b.toString(16).padStart(2,'0')).join('');}
async function storageInfo(){let estimate={usage:0,quota:0},persisted=false;if(navigator.storage?.estimate)estimate=await navigator.storage.estimate();if(navigator.storage?.persisted)persisted=await navigator.storage.persisted();runtime.state.device.storage={usage:estimate.usage||0,quota:estimate.quota||0,persisted};return {...estimate,persisted};}
async function requestPersistence(){if(!navigator.storage?.persist)return false;const ok=await navigator.storage.persist();await storageInfo();await saveState();render();return ok;}
async function findReusable(entry){if(!('caches'in window))return null;const url=new URL(entry.path,document.baseURI).href;const shared=await caches.open(SHARED_ASSET_CACHE);let hit=await shared.match(url);if(hit&&runtime.state.fileIndex[url]?.sha256===entry.sha256){runtime.state.fileIndex[url].lastUsedAt=new Date().toISOString();return hit}if(hit)await shared.delete(url);for(const key of await caches.keys()){if(!key.startsWith(CACHE_PREFIX)||key===SHARED_ASSET_CACHE)continue;const old=await caches.open(key),candidate=await old.match(url);if(!candidate)continue;if(crypto.subtle&&entry.sha256){const got=await digest(await candidate.clone().arrayBuffer());if(got!==entry.sha256)continue}await shared.put(url,candidate.clone());runtime.state.fileIndex[url]={sha256:entry.sha256,bytes:entry.bytes,lastUsedAt:new Date().toISOString(),source:key};return candidate}return null}
async function ensureQuota(required){const info=await storageInfo();if(!info.quota)return true;const free=info.quota-info.usage;if(free>=required*1.15)return true;await window.DSCacheMemory?.releaseTransient?.('quota-preflight');await cleanLRUPacks(required-free);const next=await storageInfo();if(next.quota-next.usage<required)throw new Error(`Espaço insuficiente. Necessário ${fmt(required)}, disponível ${fmt(Math.max(0,next.quota-next.usage))}.`);return true}
async function cleanLRUPacks(bytesNeeded=0){let freed=0;const candidates=INDEX.packs.filter(p=>!p.required&&installed(p.id)).sort((a,b)=>new Date(runtime.state.installed[a.id]?.lastUsedAt||0)-new Date(runtime.state.installed[b.id]?.lastUsedAt||0));for(const p of candidates){if(freed>=bytesNeeded)break;freed+=runtime.state.installed[p.id]?.bytesCached||p.bytes||0;await removePack(p.id,{silent:true,skipConfirm:true})}return freed}
async function cacheFile(cache,entry,task){while(task.paused)await new Promise(r=>setTimeout(r,120));if(task.cancelled)throw new Error('Instalação cancelada');const url=new URL(entry.path,document.baseURI).href;const reusable=await findReusable(entry);if(reusable){await cache.put(url,reusable.clone());runtime.state.fileIndex[url]={sha256:entry.sha256,bytes:entry.bytes,lastUsedAt:new Date().toISOString(),packs:[...new Set([...(runtime.state.fileIndex[url]?.packs||[]),task.id])]};return entry.bytes}const existing=await cache.match(url);if(existing)return entry.bytes;
 const response=await fetch(url,{cache:'no-cache'});if(!response.ok)throw new Error(`Falha ao carregar ${entry.path} (${response.status})`);const clone=response.clone();if(crypto.subtle&&entry.sha256){const buf=await response.arrayBuffer();const got=await digest(buf);if(got!==entry.sha256)throw new Error(`Integridade inválida em ${entry.path}`);}await cache.put(url,clone);const shared=await caches.open(SHARED_ASSET_CACHE);await shared.put(url,clone.clone());runtime.state.fileIndex[url]={sha256:entry.sha256,bytes:entry.bytes,lastUsedAt:new Date().toISOString(),packs:[...new Set([...(runtime.state.fileIndex[url]?.packs||[]),task.id])]};return entry.bytes;}
async function installPack(id,{silent=false}={}){const p=pack(id);if(!p)throw new Error('Pacote inexistente');if(installed(id))return runtime.state.installed[id];for(const dep of p.requires||[])if(!installed(dep))await installPack(dep,{silent:true});
 if(location.protocol==='file:'){runtime.state.installed[id]={version:p.version,status:'installed',installedAt:new Date().toISOString(),bytesCached:p.bytes,fileCount:p.fileCount,simulatedLocal:true};await saveState();render();if(!silent)toast('Pacote preparado localmente',`${p.name} registrado para demonstração. No GitHub Pages os arquivos serão armazenados no cache.`);return runtime.state.installed[id];}
 if(!supports.cache)throw new Error('Cache Storage indisponível neste navegador');await ensureQuota(p.bytes);const task={id,done:0,total:p.files.length,bytes:0,totalBytes:p.bytes,paused:false,cancelled:false};runtime.tasks.set(id,task);render();
 const cache=await caches.open(`${CACHE_PREFIX}-${id}-v${p.version}`);
 try{for(const entry of p.files){task.bytes+=await cacheFile(cache,entry,task);task.done++;renderProgress(id,task);}runtime.state.installed[id]={version:p.version,status:'installed',installedAt:new Date().toISOString(),bytesCached:task.bytes,fileCount:p.fileCount,lastUsedAt:new Date().toISOString()};await saveState();runtime.tasks.delete(id);await storageInfo();render();document.dispatchEvent(new CustomEvent('ds-pack-installed',{detail:{id,pack:p}}));if(!silent)toast('Pacote pronto',`${p.name} foi armazenado para uso rápido.`);return runtime.state.installed[id];}
 catch(e){runtime.tasks.delete(id);runtime.state.installed[id]={version:p.version,status:'error',error:e.message,updatedAt:new Date().toISOString()};await saveState();render();throw e;}}
function pausePack(id){const t=runtime.tasks.get(id);if(t){t.paused=!t.paused;render();}}
function cancelPack(id){const t=runtime.tasks.get(id);if(t)t.cancelled=true;}
async function removePack(id,{silent=false,skipConfirm=false}={}){const deps=dependents(id);if(deps.length&&!skipConfirm&&!confirm(`Remover também os pacotes dependentes: ${deps.map(x=>pack(x)?.name).join(', ')}?`))return false;for(const dep of deps)await removePack(dep,{silent,skipConfirm:true});const p=pack(id);if(p?.required){toast('Pacote obrigatório','O Essencial não pode ser removido.',true);return false;}if('caches'in window){for(const key of await caches.keys())if(key.startsWith(`${CACHE_PREFIX}-${id}-`))await caches.delete(key);}delete runtime.state.installed[id];for(const [url,meta] of Object.entries(runtime.state.fileIndex||{})){meta.packs=(meta.packs||[]).filter(x=>x!==id);if(!meta.packs.length){try{const c=await caches.open(SHARED_ASSET_CACHE);await c.delete(url)}catch(_){}delete runtime.state.fileIndex[url]}}await saveState();await storageInfo();render();if(!silent)toast('Pacote removido',`${p?.name||id} foi removido do cache.`);return true;}
async function cleanOldCaches(){if(!('caches'in window))return;const valid=new Set(INDEX.packs.map(p=>`${CACHE_PREFIX}-${p.id}-v${p.version}`));for(const key of await caches.keys())if(key.startsWith(CACHE_PREFIX)&&!valid.has(key))await caches.delete(key);navigator.serviceWorker?.controller?.postMessage({type:'CLEAR_OLD_CACHES'});await storageInfo();render();toast('Cache otimizado','Versões antigas foram removidas.');}
async function markPackUsed(id){if(runtime.state.installed[id]){runtime.state.installed[id].lastUsedAt=new Date().toISOString();await saveState()}for(const p of pack(id)?.files||[]){const url=new URL(p.path,document.baseURI).href;if(runtime.state.fileIndex[url])runtime.state.fileIndex[url].lastUsedAt=new Date().toISOString()}window.DSCacheMemory?.log?.('pack-use',id)}
function requiredForMode(mode){mode=window.DSPerformance?.normalize?.(mode)||mode;return INDEX.modeRequirements?.[mode]||INDEX.modeRequirements?.[({basic:'economy',intermediate:'balanced',advanced:'high',realism:'ultraAdvanced'}[mode])]||[];}function missingForMode(mode){return requiredForMode(mode).filter(id=>!installed(id));}
async function ensureMode(mode){mode=window.DSPerformance?.normalize?.(mode)||mode;if(mode==='auto'||mode==='basic')return true;const missing=missingForMode(mode);if(!missing.length){runtime.state.settings.preferredMode=mode;await saveState();return true;}runtime.focusId=missing[0];render();toast('Pacote gráfico necessário',`Prepare ${pack(missing[0])?.name} antes de ativar este modo.`);return false;}
function focusPackage(id){runtime.focusId=id;render();setTimeout(()=>document.querySelector(`[data-pack-id="${id}"]`)?.scrollIntoView({behavior:'smooth',block:'center'}),50);}
function modeReadiness(mode){const req=requiredForMode(mode);const ready=req.filter(installed);return {required:req.length,ready:ready.length,missing:req.filter(id=>!installed(id))};}
function renderProgress(id,t){const card=document.querySelector(`[data-pack-id="${id}"]`);if(!card)return;const pct=t.total?Math.round(t.done/t.total*100):0;card.querySelector('[data-pack-progress]')?.style.setProperty('width',pct+'%');const label=card.querySelector('[data-pack-progress-label]');if(label)label.textContent=`${pct}% • ${t.done}/${t.total} arquivos • ${fmt(t.bytes)}`;}
function packageCard(p){const s=runtime.state.installed[p.id],task=runtime.tasks.get(p.id),isReady=installed(p.id),isUpdate=!!s&&s.version!==p.version;const focused=runtime.focusId===p.id;const requires=(p.requires||[]).map(id=>pack(id)?.name||id).join(', ')||'Nenhuma';const badge=isReady?'Instalado':task?'Carregando':isUpdate?'Atualização':'Disponível';const action=isReady?`<button class="button soft" data-pack-remove="${p.id}" ${p.required?'disabled':''}>${p.required?'Obrigatório':'Remover'}</button>`:task?`<button class="button soft" data-pack-pause="${p.id}">${task.paused?'Retomar':'Pausar'}</button><button class="button danger" data-pack-cancel="${p.id}">Cancelar</button>`:`<button class="button primary" data-pack-install="${p.id}">Preparar pacote</button>`;
 return `<article class="graphics-pack glass ${focused?'focused':''} ${isReady?'installed':''}" data-pack-id="${p.id}"><div class="pack-accent ${p.accent}"></div><div class="pack-head"><div><span class="eyebrow">${p.tier==='module'?'Módulo opcional':'Pacote gráfico'}</span><h2>${p.name}</h2></div><span class="status-chip ${isReady?'success':task?'warning':''}">${badge}</span></div><p>${p.description}</p><div class="pack-stats"><div><span>Tamanho</span><strong>${p.displaySize}</strong></div><div><span>Arquivos</span><strong>${p.fileCount}</strong></div><div><span>Memória estimada</span><strong>${p.memoryEstimateMB?p.memoryEstimateMB+' MB':'—'}</strong></div><div><span>Meta</span><strong>${p.targetFps} FPS</strong></div></div><div class="pack-requires"><span>Dependências</span><strong>${requires}</strong></div><div class="pack-progress"><span data-pack-progress style="width:${task&&task.total?Math.round(task.done/task.total*100):isReady?100:0}%"></span></div><small data-pack-progress-label>${isReady?`Versão ${p.version} • ${s?.simulatedLocal?'registro local':'cache verificado'}`:task?'Iniciando...':p.recommendedFor}</small><div class="pack-actions">${action}<button class="link-button" data-pack-details="${p.id}">Ver arquivos</button></div></article>`;}
function render(){const grid=$('#graphicsPackGrid');if(grid)grid.innerHTML=INDEX.packs.map(packageCard).join('');const installedCount=INDEX.packs.filter(p=>installed(p.id)).length;const set=(id,v)=>{const e=$(id);if(e)e.textContent=v;};set('#packInstalledCount',installedCount);const mode=window.DSPerformance?.actualMode||'intermediate';set('#packActiveMode',window.DSPerformance?.labels?.[mode]||mode);const readiness=modeReadiness(mode);set('#packReadiness',readiness.missing.length?`${readiness.ready}/${readiness.required} preparados`:'Completo');const st=runtime.state.device.storage||{};set('#packStorageUsage',st.quota?`${fmt(st.usage)} de ${fmt(st.quota)}`:'Estimando...');set('#packPersistent',st.persisted?'Ativo':'Não garantido');const bar=$('#packStorageBar');if(bar)bar.style.width=st.quota?Math.min(100,st.usage/st.quota*100)+'%':'0%';$$('[name="graphicsPriority"]').forEach(r=>r.checked=r.value===runtime.state.settings.priority);const down=$('#allowAutoDowngrade');if(down)down.checked=runtime.state.settings.allowAutoDowngrade!==false;bindActions();}
function bindActions(){$$('[data-pack-install]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{await installPack(b.dataset.packInstall);}catch(e){toast('Falha ao preparar pacote',e.message,true);}finally{b.disabled=false;}});$$('[data-pack-remove]').forEach(b=>b.onclick=()=>removePack(b.dataset.packRemove));$$('[data-pack-pause]').forEach(b=>b.onclick=()=>pausePack(b.dataset.packPause));$$('[data-pack-cancel]').forEach(b=>b.onclick=()=>cancelPack(b.dataset.packCancel));$$('[data-pack-details]').forEach(b=>b.onclick=()=>showDetails(b.dataset.packDetails));}
function showDetails(id){const p=pack(id);if(!p)return;const modal=$('#packDetailsModal');$('#packDetailsTitle').textContent=p.name;$('#packDetailsBody').innerHTML=`<p>${p.description}</p><div class="pack-file-list">${p.files.slice(0,80).map(f=>`<div><code>${f.path.replace(/^\.\.\//,'')}</code><span>${fmt(f.bytes)}</span></div>`).join('')}${p.files.length>80?`<small>+ ${p.files.length-80} arquivos adicionais</small>`:''}</div>`;modal.classList.add('show');modal.setAttribute('aria-hidden','false');}
async function init(){await loadState();await storageInfo();if(supports.sw&&location.protocol.startsWith('http'))navigator.serviceWorker.register('../sw.js').catch(()=>{});runtime.ready=true;render();document.addEventListener('ds-quality-change',()=>render());$('#requestPersistentStorage')?.addEventListener('click',async()=>{const ok=await requestPersistence();toast(ok?'Armazenamento persistente ativado':'O navegador manteve a política padrão',ok?'Os pacotes terão menor risco de remoção automática.':'Ainda é possível usar os pacotes normalmente.');});$('#cleanPackageCache')?.addEventListener('click',cleanOldCaches);$('#recalculateStorage')?.addEventListener('click',async()=>{await storageInfo();render();});$('#closePackDetails')?.addEventListener('click',()=>{$('#packDetailsModal').classList.remove('show');$('#packDetailsModal').setAttribute('aria-hidden','true');});$$('[name="graphicsPriority"]').forEach(r=>r.addEventListener('change',async()=>{runtime.state.settings.priority=r.value;try{localStorage.setItem('ds-graphics-priority',r.value)}catch(_){}window.DSPerformance?.setPriority?.(r.value);await saveState();render();}));$('#allowAutoDowngrade')?.addEventListener('change',async e=>{runtime.state.settings.allowAutoDowngrade=e.target.checked;try{localStorage.setItem('ds-auto-downgrade',e.target.checked?'1':'0')}catch(_){}await saveState();});}
document.addEventListener('DOMContentLoaded',init);
window.DSPackManager={installPack,removePack,ensureMode,focusPackage,missingForMode,modeReadiness,storageInfo,requestPersistence,cleanOldCaches,cleanLRUPacks,markPackUsed,isInstalled:installed,get state(){return runtime.state},get ready(){return runtime.ready}};
})();
