(() => {
'use strict';
const MODE_ORDER=['basic','intermediate','advanced','ultra','realism'];
const ALIASES={economy:'basic',balanced:'intermediate',high:'advanced',ultraAdvanced:'realism'};
const LABELS={auto:'Automático',basic:'Básico',intermediate:'Intermediário',advanced:'Avançado',ultra:'Ultra',realism:'Modo Realismo',...Object.fromEntries(Object.entries(ALIASES).map(([a,c])=>[a,({basic:'Básico',intermediate:'Intermediário',advanced:'Avançado',ultra:'Ultra',realism:'Modo Realismo'})[c]]))};
const BASE={
 basic:{dpr:1,particles:60,target:60,minFps:38,lod:'lod2',textureMax:512,shadow:0,scene:'Estúdio Essencial'},
 intermediate:{dpr:1.3,particles:220,target:60,minFps:42,lod:'lod1',textureMax:1024,shadow:512,scene:'Estúdio Neon Balanceado'},
 advanced:{dpr:1.7,particles:650,target:60,minFps:45,lod:'lod0',textureMax:2048,shadow:1024,scene:'Estúdio Tech Avançado'},
 ultra:{dpr:2.15,particles:1400,target:60,minFps:46,lod:'lod0',textureMax:4096,shadow:2048,scene:'Estúdio Ultra Holográfico'},
 realism:{dpr:2.5,particles:2200,target:45,minFps:30,lod:'lod0',textureMax:4096,shadow:4096,scene:'Estúdio Realismo Cinematográfico'}
};
const PRIORITY={performance:{dpr:.78,particles:.62,shadow:.5},balanced:{dpr:1,particles:1,shadow:1},quality:{dpr:1.08,particles:1.12,shadow:1}};
const safeStore={get(k){try{return localStorage.getItem(k)}catch(_){return null}},set(k,v){try{localStorage.setItem(k,v)}catch(_){}}};
function advancedBenchmark(){try{const x=JSON.parse(safeStore.get('ds-benchmark-summary-v095')||'null');if(!x||!Number.isFinite(Number(x.score)))return null;const age=Date.now()-new Date(x.createdAt||0).getTime();return age>=0&&age<1000*60*60*24*45?{score:Number(x.score),mode:x.mode,createdAt:x.createdAt}:null}catch(_){return null}}
const normalize=m=>ALIASES[m]||m;
function priority(){return safeStore.get('ds-graphics-priority')||'balanced'}
function effective(mode){const b=BASE[normalize(mode)]||BASE.intermediate,p=PRIORITY[priority()]||PRIORITY.balanced;return {...b,dpr:Math.min(3,b.dpr*p.dpr),particles:Math.max(20,Math.round(b.particles*p.particles)),shadow:Math.round(b.shadow*p.shadow),priority:priority()}}
const capabilities={};let stored=safeStore.get('ds-quality-mode')||'auto';if(stored!=='auto'&&ALIASES[stored]){stored=ALIASES[stored];safeStore.set('ds-quality-mode',stored)}let requested=stored,actual='intermediate',fps=60,score=0,lastChange=0,lowWindows=0,highWindows=0,frames=0,lastSample=performance.now();
function glInfo(){const c=document.createElement('canvas');const gl=c.getContext('webgl2',{powerPreference:'high-performance'})||c.getContext('webgl');if(!gl)return{webgl:false,webgl2:false,maxTexture:0,maxRenderbuffer:0,renderer:'Indisponível',extensions:0};const dbg=gl.getExtension('WEBGL_debug_renderer_info');return{webgl:true,webgl2:typeof WebGL2RenderingContext!=='undefined'&&gl instanceof WebGL2RenderingContext,maxTexture:gl.getParameter(gl.MAX_TEXTURE_SIZE)||0,maxRenderbuffer:gl.getParameter(gl.MAX_RENDERBUFFER_SIZE)||0,renderer:dbg?gl.getParameter(dbg.UNMASKED_RENDERER_WEBGL):gl.getParameter(gl.RENDERER),extensions:(gl.getSupportedExtensions()||[]).length}}
function cpuScore(duration=80){const end=performance.now()+duration;let ops=0,x=.12345;while(performance.now()<end){x=Math.sin(x+ops*.000001)*Math.cos(x*.71)+Math.sqrt(Math.abs(x)+1);ops++}return Math.min(100,Math.round(ops/18000))}
function calculateScore(){const gl=glInfo();Object.assign(capabilities,gl);capabilities.memory=navigator.deviceMemory||0;capabilities.cores=navigator.hardwareConcurrency||2;capabilities.mobile=/Android|iPhone|iPad|Mobile/i.test(navigator.userAgent);capabilities.screenPixels=screen.width*screen.height*(devicePixelRatio||1);const cpu=cpuScore(70);capabilities.cpuScore=cpu;let s=cpu*.34+Math.min(24,capabilities.cores*2.2)+Math.min(18,capabilities.memory*2.2)+(gl.webgl2?12:gl.webgl?5:0)+Math.min(12,gl.maxTexture/1024*1.5)+(gl.extensions>20?5:0);if(capabilities.mobile)s-=10;if(capabilities.screenPixels>5000000)s-=4;if(matchMedia('(prefers-reduced-motion: reduce)').matches)s=Math.min(s,49);const saved=advancedBenchmark();if(saved){capabilities.advancedBenchmarkScore=saved.score;capabilities.advancedBenchmarkAt=saved.createdAt;s=s*.35+saved.score*.65}score=Math.max(0,Math.min(100,Math.round(s)));return score}
function modeFromScore(s){if(!capabilities.webgl)return'intermediate';if(s>=88)return'realism';if(s>=72)return'ultra';if(s>=46)return'advanced';return'intermediate'}
function updatePanel(){const set=(id,v)=>{const e=document.getElementById(id);if(e)e.textContent=v};set('perfScore',score);set('perfRequested',LABELS[requested]||requested);set('perfActual',LABELS[actual]||actual);set('perfFps',Math.round(fps));set('perfMemory',capabilities.memory?capabilities.memory+' GB':'não informado');set('perfCores',capabilities.cores||'—');set('perfWebgl',capabilities.webgl2?'WebGL 2':capabilities.webgl?'WebGL 1':'Fallback 2D');set('perfTexture',capabilities.maxTexture?capabilities.maxTexture+' px':'—');set('perfRenderer',capabilities.renderer||'—');const bar=document.getElementById('perfScoreBar');if(bar)bar.style.width=score+'%';document.querySelectorAll('[data-performance-mode]').forEach(el=>el.classList.toggle('active',normalize(el.dataset.performanceMode)===actual));const hud=document.getElementById('performanceHud');if(hud){hud.querySelector('[data-hud-fps]').textContent=Math.round(fps);hud.querySelector('[data-hud-mode]').textContent=LABELS[actual]||actual}}
function emit(reason='manual'){const profile=effective(actual);document.dispatchEvent(new CustomEvent('ds-quality-change',{detail:{requested,actual,profile,baseProfile:BASE[actual],score,fps,reason,priority:priority()}}));updatePanel()}
function apply(mode,reason='manual'){mode=normalize(mode);if(!BASE[mode])mode='intermediate';actual=mode;document.body.dataset.quality=actual;document.body.dataset.qualityRequested=requested;document.body.dataset.renderPriority=priority();lastChange=performance.now();emit(reason);return actual}
function setMode(mode){mode=normalize(mode);requested=(mode==='auto'||BASE[mode])?mode:'auto';safeStore.set('ds-quality-mode',requested);document.body.dataset.basicExplicit=String(requested==='basic');return apply(requested==='auto'?modeFromScore(score||calculateScore()):requested,'user')}
function setPriority(value){if(!PRIORITY[value])value='balanced';safeStore.set('ds-graphics-priority',value);document.body.dataset.renderPriority=value;emit('priority-change');return value}
function runBenchmark(full=false){calculateScore();if(full){const start=performance.now();let acc=0;while(performance.now()-start<220){for(let i=0;i<2500;i++)acc+=Math.sin(i+acc*.00001)}capabilities.fullCpuToken=Math.round(acc)%997;score=Math.min(100,Math.round(score*.86+cpuScore(150)*.14))}if(requested==='auto')apply(modeFromScore(score),'benchmark');else emit('benchmark');return Promise.resolve(getReport())}
function getReport(){return{requestedMode:requested,actualMode:actual,score,fps,capabilities:{...capabilities},profile:effective(actual),baseProfile:BASE[actual],priority:priority()}}
function fpsLoop(now){frames++;const elapsed=now-lastSample;if(elapsed>=1000){fps=frames*1000/elapsed;frames=0;lastSample=now;if(requested==='auto'&&now-lastChange>12000){const idx=MODE_ORDER.indexOf(actual),profile=effective(actual),allow=safeStore.get('ds-auto-downgrade')!=='0';if(fps<Math.max(22,profile.minFps)){lowWindows++;highWindows=0}else if(fps>Math.min(59,profile.target*.96)){highWindows++;lowWindows=0}else{lowWindows=Math.max(0,lowWindows-1);highWindows=Math.max(0,highWindows-1)}if(allow&&lowWindows>=3&&idx>1){lowWindows=0;apply(MODE_ORDER[idx-1],'adaptive-downgrade')}else if(allow&&lowWindows>=4&&idx===1&&safeStore.get('ds-allow-basic-auto')==='1'){lowWindows=0;apply('basic','adaptive-emergency')}else if(priority()!=='performance'&&highWindows>=5&&idx<MODE_ORDER.length-1&&score>=([25,50,72,88][idx]||101)){highWindows=0;apply(MODE_ORDER[idx+1],'adaptive-upgrade')}}updatePanel()}requestAnimationFrame(fpsLoop)}
calculateScore();document.body.dataset.basicExplicit=String(requested==='basic');apply(requested==='auto'?modeFromScore(score):requested,'initial');requestAnimationFrame(fpsLoop);
document.addEventListener('DOMContentLoaded',()=>{updatePanel();if(!window.DSAdvancedBenchmark)document.getElementById('runGraphicsBenchmark')?.addEventListener('click',async()=>{const b=document.getElementById('runGraphicsBenchmark');b.disabled=true;b.textContent='Testando CPU e GPU...';await runBenchmark(true);b.disabled=false;b.textContent='Executar benchmark completo'});document.getElementById('togglePerformanceHud')?.addEventListener('change',e=>{const hud=document.getElementById('performanceHud');if(hud)hud.hidden=!e.target.checked})});
document.addEventListener('ds-advanced-benchmark-complete',e=>{const r=e.detail||{};if(Number.isFinite(Number(r.score))){score=Number(r.score);capabilities.advancedBenchmarkScore=score;capabilities.advancedBenchmarkAt=r.createdAt;if(requested==='auto')apply(normalize(r.recommendation?.mode||modeFromScore(score)),'advanced-benchmark');else emit('advanced-benchmark')}});
window.DSPerformance={setMode,setPriority,normalize,runBenchmark,getReport,get requestedMode(){return requested},get actualMode(){return actual},get priority(){return priority()},labels:LABELS,profiles:BASE,effectiveProfile:effective,aliases:ALIASES};
})();
