(() => {
'use strict';
const canvas=document.getElementById('product3dCanvas');if(!canvas)return;const vector=document.getElementById('productSymbol');const status=document.getElementById('product3dStatus');let gl=null,program=null,loc=null,model=null,currentId=null,yaw=.55,pitch=.18,dist=4.5,auto=true,drag=false,last=[0,0],quality='intermediate',raf=0,cache=new Map();
const M={id:()=>new Float32Array([1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]),mul:(a,b)=>{let o=new Float32Array(16);for(let c=0;c<4;c++)for(let r=0;r<4;r++)o[c*4+r]=a[r]*b[c*4]+a[4+r]*b[c*4+1]+a[8+r]*b[c*4+2]+a[12+r]*b[c*4+3];return o},trs:(t,q,s)=>{let[x,y,z,w]=q,x2=x+x,y2=y+y,z2=z+z,xx=x*x2,xy=x*y2,xz=x*z2,yy=y*y2,yz=y*z2,zz=z*z2,wx=w*x2,wy=w*y2,wz=w*z2;return new Float32Array([(1-(yy+zz))*s[0],(xy+wz)*s[0],(xz-wy)*s[0],0,(xy-wz)*s[1],(1-(xx+zz))*s[1],(yz+wx)*s[1],0,(xz+wy)*s[2],(yz-wx)*s[2],(1-(xx+yy))*s[2],0,t[0],t[1],t[2],1])},rotY:a=>new Float32Array([Math.cos(a),0,-Math.sin(a),0,0,1,0,0,Math.sin(a),0,Math.cos(a),0,0,0,0,1]),persp:(fov,a,n,f)=>{let z=1/Math.tan(fov/2),nf=1/(n-f);return new Float32Array([z/a,0,0,0,0,z,0,0,0,0,(f+n)*nf,-1,0,0,2*f*n*nf,0])},look:(eye,target,up)=>{let zx=eye[0]-target[0],zy=eye[1]-target[1],zz=eye[2]-target[2],zl=Math.hypot(zx,zy,zz);zx/=zl;zy/=zl;zz/=zl;let xx=up[1]*zz-up[2]*zy,xy=up[2]*zx-up[0]*zz,xz=up[0]*zy-up[1]*zx,xl=Math.hypot(xx,xy,xz);xx/=xl;xy/=xl;xz/=xl;let yx=zy*xz-zz*xy,yy=zz*xx-zx*xz,yz=zx*xy-zy*xx;return new Float32Array([xx,yx,zx,0,xy,yy,zy,0,xz,yz,zz,0,-(xx*eye[0]+xy*eye[1]+xz*eye[2]),-(yx*eye[0]+yy*eye[1]+yz*eye[2]),-(zx*eye[0]+zy*eye[1]+zz*eye[2]),1])}};
function init(){if(gl)return true;gl=canvas.getContext('webgl2',{antialias:true,alpha:true,powerPreference:'high-performance'})||canvas.getContext('webgl',{antialias:true,alpha:true});if(!gl){status.textContent='WebGL indisponível — exibindo prévia vetorial';return false}const shaderPack=window.DSRendererProfile?.shaderSources?.()||{};const V=shaderPack.vertex||`attribute vec3 a_position;attribute vec3 a_normal;uniform mat4 u_model,u_view,u_proj;varying vec3 v_n;varying vec3 v_w;void main(){vec4 w=u_model*vec4(a_position,1.0);v_w=w.xyz;v_n=normalize(mat3(u_model)*a_normal);gl_Position=u_proj*u_view*w;}`;const F=shaderPack.fragment||`precision mediump float;varying vec3 v_n;uniform vec4 u_color;uniform vec3 u_emissive;uniform float u_metallic,u_roughness;void main(){vec3 n=normalize(v_n),l=normalize(vec3(.65,.9,.75));float d=max(dot(n,l),0.0);gl_FragColor=vec4(u_color.rgb*(.2+d*.8)+u_emissive,u_color.a);}`;function sh(t,s){let x=gl.createShader(t);gl.shaderSource(x,s);gl.compileShader(x);if(!gl.getShaderParameter(x,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(x));return x}program=gl.createProgram();gl.attachShader(program,sh(gl.VERTEX_SHADER,V));gl.attachShader(program,sh(gl.FRAGMENT_SHADER,F));gl.linkProgram(program);gl.useProgram(program);loc={p:gl.getAttribLocation(program,'a_position'),n:gl.getAttribLocation(program,'a_normal'),m:gl.getUniformLocation(program,'u_model'),v:gl.getUniformLocation(program,'u_view'),pr:gl.getUniformLocation(program,'u_proj'),c:gl.getUniformLocation(program,'u_color'),e:gl.getUniformLocation(program,'u_emissive'),met:gl.getUniformLocation(program,'u_metallic'),rough:gl.getUniformLocation(program,'u_roughness'),ultra:gl.getUniformLocation(program,'u_ultra'),...((window.DSRendererProfile?.bind?.(gl,program))||{})};return true}
function accessor(g,b,i){let a=g.accessors[i],v=g.bufferViews[a.bufferView],off=(v.byteOffset||0)+(a.byteOffset||0),comps={SCALAR:1,VEC2:2,VEC3:3,VEC4:4}[a.type],ctors={5126:Float32Array,5123:Uint16Array,5125:Uint32Array,5121:Uint8Array},C=ctors[a.componentType];return new C(b,off,a.count*comps)}
function parse(ab){let dv=new DataView(ab),p=12,j=null,b=null;if(dv.getUint32(0,true)!==0x46546c67)throw Error('GLB inválido');while(p<ab.byteLength){let len=dv.getUint32(p,true),typ=dv.getUint32(p+4,true),d=ab.slice(p+8,p+8+len);if(typ===0x4e4f534a)j=JSON.parse(new TextDecoder().decode(d));if(typ===0x004e4942)b=d;p+=8+len}return{j,b}}
function gpu(ab){
 let{j,b}=parse(ab),materials=(j.materials||[]).map(m=>{let p=m.pbrMetallicRoughness||{};return{color:p.baseColorFactor||[1,1,1,1],metal:p.metallicFactor||0,rough:p.roughnessFactor??.65,em:m.emissiveFactor||[0,0,0]}});
 let meshes=(j.meshes||[]).map(m=>m.primitives.map(pr=>{let pa=j.accessors[pr.attributes.POSITION],pos=accessor(j,b,pr.attributes.POSITION),norm=accessor(j,b,pr.attributes.NORMAL),idx=accessor(j,b,pr.indices);let pb=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,pb);gl.bufferData(gl.ARRAY_BUFFER,pos,gl.STATIC_DRAW);let nb=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,nb);gl.bufferData(gl.ARRAY_BUFFER,norm,gl.STATIC_DRAW);let ib=gl.createBuffer();gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,ib);gl.bufferData(gl.ELEMENT_ARRAY_BUFFER,idx,gl.STATIC_DRAW);return{pb,nb,ib,count:idx.length,type:idx instanceof Uint32Array?gl.UNSIGNED_INT:gl.UNSIGNED_SHORT,mat:pr.material||0,min:pa.min||[-.5,-.5,-.5],max:pa.max||[.5,.5,.5]}}));
 let nodes=(j.nodes||[]).map((n,i)=>({i,mesh:n.mesh,children:n.children||[],t:n.translation||[0,0,0],r:n.rotation||[0,0,0,1],s:n.scale||[1,1,1]})),mins=[Infinity,Infinity,Infinity],maxs=[-Infinity,-Infinity,-Infinity];
 const tp=(m,p)=>[m[0]*p[0]+m[4]*p[1]+m[8]*p[2]+m[12],m[1]*p[0]+m[5]*p[1]+m[9]*p[2]+m[13],m[2]*p[0]+m[6]*p[1]+m[10]*p[2]+m[14]];
 function boundsNode(i,parent){let n=nodes[i],w=M.mul(parent,M.trs(n.t,n.r,n.s));if(n.mesh!==undefined)for(let pr of meshes[n.mesh])for(let x of [pr.min[0],pr.max[0]])for(let y of [pr.min[1],pr.max[1]])for(let z of [pr.min[2],pr.max[2]]){let q=tp(w,[x,y,z]);for(let k=0;k<3;k++){mins[k]=Math.min(mins[k],q[k]);maxs[k]=Math.max(maxs[k],q[k])}}for(let c of n.children)boundsNode(c,w)}
 let roots=j.scenes[j.scene||0].nodes;for(let r of roots)boundsNode(r,M.id());let size=Math.max(...maxs.map((v,i)=>v-mins[i])),center=mins.map((v,i)=>(v+maxs[i])/2);if(center.some(x=>!isFinite(x))){center=[0,0,0];size=2}let gpuBytes=0;for(const mm of meshes)for(const p of mm)gpuBytes+=p.count*(p.type===gl.UNSIGNED_INT?4:2)+p.count*3*4*2;return{materials,meshes,nodes,roots,size:size||2,center,gpuBytes}
}
function disposeGpuModel(m){if(!m)return;for(const mm of m.meshes||[])for(const p of mm){try{gl.deleteBuffer(p.pb);gl.deleteBuffer(p.nb);gl.deleteBuffer(p.ib)}catch(_){}}}
function releaseCache(exceptId=null){for(const [id,m] of [...cache.entries()]){if(id===exceptId)continue;disposeGpuModel(m);cache.delete(id);window.DSCacheMemory?.unregister?.(`product:${id}`,'product-cache-release')}}
async function bytes(item){try{return window.DSAssetTransfer?.fetchArrayBuffer?await window.DSAssetTransfer.fetchArrayBuffer(item.model3d):await (async()=>{const r=await fetch(item.model3d,{cache:'force-cache'});if(r.ok)return r.arrayBuffer();throw Error(`HTTP ${r.status}`)})()}catch(e){throw Error('Modelo 3D indisponível: '+(e?.message||e))}}
function drawPrim(p,mat,w){gl.bindBuffer(gl.ARRAY_BUFFER,p.pb);gl.enableVertexAttribArray(loc.p);gl.vertexAttribPointer(loc.p,3,gl.FLOAT,false,0,0);gl.bindBuffer(gl.ARRAY_BUFFER,p.nb);gl.enableVertexAttribArray(loc.n);gl.vertexAttribPointer(loc.n,3,gl.FLOAT,false,0,0);gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,p.ib);gl.uniformMatrix4fv(loc.m,false,w);gl.uniform4fv(loc.c,mat.color);gl.uniform3fv(loc.e,mat.em);gl.uniform1f(loc.met,mat.metal);gl.uniform1f(loc.rough,mat.rough);if(loc.ultra)gl.uniform1f(loc.ultra,quality==='realism'?1:quality==='ultra'?.58:quality==='advanced'?.22:0);window.DSRendererProfile?.uniforms?.(gl,loc,quality);if(mat.color[3]<1){gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);gl.disable(gl.CULL_FACE)}else{gl.disable(gl.BLEND);gl.enable(gl.CULL_FACE)}gl.drawElements(gl.TRIANGLES,p.count,p.type,0)}
function drawNode(i,parent){let n=model.nodes[i],w=M.mul(parent,M.trs(n.t,n.r,n.s));if(n.mesh!==undefined)for(let p of model.meshes[n.mesh])drawPrim(p,model.materials[p.mat]||model.materials[0],w);for(let c of n.children)drawNode(c,w)}
function resize(){let lim={basic:1,intermediate:1.3,advanced:1.7,ultra:2.15,realism:2.5,economy:1,balanced:1.3,high:1.7,ultraAdvanced:2.5}[quality]||1.3,d=Math.min(devicePixelRatio||1,lim),w=Math.max(1,Math.floor(canvas.clientWidth*d)),h=Math.max(1,Math.floor(canvas.clientHeight*d));if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;gl.viewport(0,0,w,h)}}
function frame(){raf=requestAnimationFrame(frame);if(!model||canvas.hidden||document.hidden)return;resize();if(auto&&!drag)yaw+=quality==='realism'?.0035:quality==='ultra'?.0032:.0028;gl.clearColor(0,0,0,0);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.enable(gl.DEPTH_TEST);let target=[0,0,0],eye=[Math.sin(yaw)*Math.cos(pitch)*dist,Math.sin(pitch)*dist,Math.cos(yaw)*Math.cos(pitch)*dist],view=M.look(eye,target,[0,1,0]),proj=M.persp(Math.PI/4,canvas.width/canvas.height,.05,100),scale=2.25/model.size,base=M.mul(M.rotY(0),M.trs(model.center.map(v=>-v*scale),[0,0,0,1],[scale,scale,scale]));gl.uniformMatrix4fv(loc.v,false,view);gl.uniformMatrix4fv(loc.pr,false,proj);for(let r of model.roots)drawNode(r,base)}
async function open(item){if(!item?.model3d){canvas.hidden=true;vector.hidden=false;status.textContent='Prévia vetorial oficial';currentId=null;return false}if(!init()){canvas.hidden=true;vector.hidden=false;return false}canvas.hidden=false;vector.hidden=true;status.textContent='Carregando modelo GLB sob demanda...';try{model=cache.get(item.id);if(!model){model=gpu(await bytes(item));cache.set(item.id,model);window.DSCacheMemory?.register?.({id:`product:${item.id}`,label:`Prévia ${item.name}`,module:'product',type:'gpu-model',bytes:model.gpuBytes||0,transient:true,dispose:()=>{if(cache.get(item.id)===model)cache.delete(item.id);disposeGpuModel(model)}});if(cache.size>6){const oldest=[...cache.keys()].find(x=>x!==item.id);if(oldest){const old=cache.get(oldest);disposeGpuModel(old);cache.delete(oldest);window.DSCacheMemory?.unregister?.(`product:${oldest}`,'product-lru')}}}currentId=item.id;window.DSCacheMemory?.touch?.(`product:${item.id}`);yaw=.55;pitch=.18;dist=4.5;status.textContent=`Modelo 3D real • rotação 360° • ${quality}`;if(!raf)frame();return true}catch(e){console.warn(e);canvas.hidden=true;vector.hidden=false;status.textContent='Falha no 3D — fallback vetorial ativo';return false}}
function close(){if(currentId)window.DSCacheMemory?.touch?.(`product:${currentId}`);currentId=null;model=null;canvas.hidden=true;vector.hidden=false}
function setQuality(q){quality=q==='auto'?(window.DSPerformance?.actualMode||'balanced'):q;status.textContent=model?`Modelo 3D real • rotação 360° • ${quality}`:status.textContent}
canvas.addEventListener('pointerdown',e=>{drag=true;last=[e.clientX,e.clientY];canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(!drag)return;yaw-=(e.clientX-last[0])*.009;pitch=Math.max(-.7,Math.min(.7,pitch+(e.clientY-last[1])*.007));last=[e.clientX,e.clientY]});canvas.addEventListener('pointerup',()=>drag=false);canvas.addEventListener('wheel',e=>{e.preventDefault();dist=Math.max(2.7,Math.min(8,dist+e.deltaY*.008))},{passive:false});document.addEventListener('ds-quality-change',e=>setQuality(e.detail.actual));document.addEventListener('ds-view-change',e=>{if(e.detail.current!=='storeView')releaseCache()});window.DSCacheMemory?.attachWebGL?.(canvas,{id:'product3d',module:'product',onRestore:()=>{if(currentId){const item=(window.DS_EQUIPMENT?.items||[]).find(x=>x.id===currentId);if(item)open(item)}}});window.DSProduct3D={open,close,releaseCache,setQuality,toggleAuto(){auto=!auto;return auto},rotate(v){yaw+=v},get currentId(){return currentId}};
})();
