/* Loja Virtual DS v0.9.6.0-RG — Ultra / Realismo premium runtime */
(() => {
'use strict';
const map={basic:'lite',intermediate:'advanced',advanced:'advanced',ultra:'advanced',realism:'cinematic',economy:'lite',balanced:'advanced',high:'advanced',ultraAdvanced:'cinematic'};
const profiles={
 lite:{id:'lite',label:'Renderer Lite',level:0,exposure:1,saturation:1,rim:.22,specular:.42,lights:1,scene:'essential',premiumTier:null,envStrength:0,detailStrength:0,clearcoat:0},
 advanced:{id:'advanced',label:'Renderer Advanced',level:.64,exposure:1.08,saturation:1.04,rim:.7,specular:.82,lights:3,scene:'tech-depth',premiumTier:null,envStrength:0,detailStrength:0,clearcoat:.08},
 cinematic:{id:'cinematic',label:'Renderer Cinematic',level:1,exposure:1.15,saturation:1.06,rim:1,specular:1,lights:3,scene:'cinematic-stage',premiumTier:'realism',envStrength:.62,detailStrength:.18,clearcoat:.42}
};
const premium={
 ultra:{pack:'graphics-ultra-core',env:'../assets/runtime/ultra/env-ultra-2048.webp',detail:'../assets/runtime/ultra/material-detail-ultra-1024.webp',stage:'../assets/runtime/ultra/stage-ultra-1920.webp',sprite:'../assets/runtime/ultra/flare-ultra-512.webp',envStrength:.46,detailStrength:.12,clearcoat:.25},
 realism:{pack:'graphics-cinematic',env:'../assets/runtime/realism/env-realism-2048.webp',detail:'../assets/runtime/realism/material-detail-realism-1024.webp',stage:'../assets/runtime/realism/stage-realism-1920.webp',sprite:'../assets/runtime/realism/bokeh-realism-512.webp',envStrength:.62,detailStrength:.18,clearcoat:.42}
};
const state={requested:'lite',actual:'lite',view:'homeView',reason:'boot',premiumTier:null,premiumStatus:'idle'};
const contextData=new WeakMap();
function normalizeMode(m){return ({economy:'basic',balanced:'intermediate',high:'advanced',ultraAdvanced:'realism'}[m]||m||'intermediate')}
function tierFor(mode){mode=normalizeMode(mode);return mode==='ultra'?'ultra':mode==='realism'?'realism':null}
function target(mode=window.DSPerformance?.actualMode||'intermediate',view=state.view){const q=normalizeMode(mode);let id=map[q]||'lite';if(['walletView','integrityView','performanceView','packagesView','validationView'].includes(view))id='lite';return id}
function setText(id,v){const e=document.getElementById(id);if(e)e.textContent=v}
function updatePremiumUi(tier,status){setText('premiumAssetTier',tier?tier==='ultra'?'Ultra 2K':'Realismo 2K':'Não solicitado');setText('premiumAssetStatus',status==='ready'?'Carregado e ativo':status==='loading'?'Carregando sob demanda':status==='error'?'Fallback sem perda funcional':status==='required'?'Prepare ou atualize o pacote':'Aguardando modo premium');document.body.dataset.premiumTier=tier||'none';document.body.dataset.premiumStatus=status||'idle';if(tier&&premium[tier])document.documentElement.style.setProperty('--premium-stage-image',`url("${new URL(premium[tier].stage,document.baseURI).href}")`);else document.documentElement.style.removeProperty('--premium-stage-image')}
function apply(mode,reason='quality'){const q=normalizeMode(mode),requested=map[q]||'lite',actual=target(q);state.requested=requested;state.actual=actual;state.reason=reason;state.premiumTier=(actual==='lite'||q==='advanced')?null:tierFor(q);const p={...profiles[actual]};if(state.premiumTier)Object.assign(p,premium[state.premiumTier]);document.body.dataset.renderer=actual;document.documentElement.style.setProperty('--renderer-exposure',p.exposure);document.documentElement.style.setProperty('--renderer-rim',p.rim);document.querySelectorAll('[data-renderer-profile]').forEach(x=>x.classList.toggle('active',x.dataset.rendererProfile===actual));setText('activeRendererName',p.label);setText('activeRendererPipeline',actual==='lite'?'1 luz • shader leve':state.premiumTier==='ultra'?'3 luzes • ambiente Ultra 2K':state.premiumTier==='realism'?'3 luzes • ambiente Realismo 2K':'3 luzes • tone mapping');setText('activeRendererReason',reason==='area-limit'?'Área administrativa sem cena 3D':'Qualidade visual protegida pela seleção');updatePremiumUi(state.premiumTier,state.premiumTier?'loading':'idle');document.dispatchEvent(new CustomEvent('ds-renderer-change',{detail:{...state,profile:{...p}}}));return p}
function shaderSources(){return {
 vertex:`attribute vec3 a_position;attribute vec3 a_normal;uniform mat4 u_model,u_view,u_proj;varying vec3 v_n;varying vec3 v_w;void main(){vec4 w=u_model*vec4(a_position,1.0);v_w=w.xyz;v_n=normalize(mat3(u_model)*a_normal);gl_Position=u_proj*u_view*w;}`,
 fragment:`precision highp float;varying vec3 v_n;varying vec3 v_w;uniform vec4 u_color;uniform vec3 u_emissive;uniform float u_metallic,u_roughness,u_renderLevel,u_exposure,u_saturation,u_rimStrength,u_specularStrength,u_hasPremium,u_envStrength,u_detailStrength,u_clearcoat;uniform sampler2D u_envMap,u_detailMap;const float PI=3.14159265359;vec3 tonemap(vec3 x){return x/(x+vec3(1.0));}vec2 envUv(vec3 r){return vec2(atan(r.z,r.x)/(2.0*PI)+0.5,asin(clamp(r.y,-1.0,1.0))/PI+0.5);}void main(){vec3 n=normalize(v_n);vec3 view=normalize(vec3(0.15,0.18,1.0));vec3 l1=normalize(vec3(.65,.9,.75));vec3 l2=normalize(vec3(-.72,.35,.48));vec3 l3=normalize(vec3(.08,-.28,-1.0));float d1=max(dot(n,l1),0.0),d2=max(dot(n,l2),0.0),d3=max(dot(n,l3),0.0);float hemi=.5+.5*n.y;float detail=texture2D(u_detailMap,v_w.xz*.095+vec2(v_w.y*.025)).r;float micro=mix(1.0,mix(.82,1.18,detail),u_detailStrength*u_hasPremium);float ao=(.76+.24*hemi)*micro;float gloss=mix(10.0,82.0,(1.0-u_roughness));float sp1=pow(max(dot(reflect(-l1,n),view),0.0),gloss);float sp2=pow(max(dot(reflect(-l2,n),view),0.0),gloss*.72);float rim=pow(1.0-max(dot(n,view),0.0),mix(2.5,1.55,u_renderLevel));vec3 light=vec3(.18)+d1*vec3(.78,.86,1.0)+u_renderLevel*(d2*vec3(.28,.20,.36)+d3*vec3(.08,.14,.22));vec3 base=u_color.rgb*light*ao;vec3 spec=(sp1+sp2*u_renderLevel*.65)*mix(vec3(.7),u_color.rgb,u_metallic)*u_specularStrength;vec3 refl=reflect(-view,n);vec3 env=texture2D(u_envMap,envUv(refl)).rgb;float fres=pow(1.0-max(dot(n,view),0.0),5.0);vec3 envTerm=env*(u_envStrength*u_hasPremium)*mix(.18,.95,max(u_metallic,fres));float coat=pow(max(dot(reflect(-l1,n),view),0.0),110.0)*u_clearcoat*u_hasPremium;vec3 c=base+spec+envTerm+coat*vec3(.82,.93,1.0)+u_emissive*(1.0+u_renderLevel*.62)+rim*(u_emissive+vec3(.025,.075,.12))*u_rimStrength;float lum=dot(c,vec3(.2126,.7152,.0722));c=mix(vec3(lum),c,u_saturation);c*=u_exposure;if(u_renderLevel>.35)c=mix(c,tonemap(c*1.35),u_renderLevel*.68);c=pow(max(c,vec3(0.0)),vec3(1.0/2.2));gl_FragColor=vec4(c,u_color.a);}`
}}
function bind(gl,program){return {level:gl.getUniformLocation(program,'u_renderLevel'),exposure:gl.getUniformLocation(program,'u_exposure'),saturation:gl.getUniformLocation(program,'u_saturation'),rim:gl.getUniformLocation(program,'u_rimStrength'),specular:gl.getUniformLocation(program,'u_specularStrength'),hasPremium:gl.getUniformLocation(program,'u_hasPremium'),envStrength:gl.getUniformLocation(program,'u_envStrength'),detailStrength:gl.getUniformLocation(program,'u_detailStrength'),clearcoat:gl.getUniformLocation(program,'u_clearcoat'),envMap:gl.getUniformLocation(program,'u_envMap'),detailMap:gl.getUniformLocation(program,'u_detailMap')}}
function solidTexture(gl,rgba){const t=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,t);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,1,1,0,gl.RGBA,gl.UNSIGNED_BYTE,new Uint8Array(rgba));gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);return t}
async function imageTexture(gl,url){const res=await fetch(new URL(url,document.baseURI).href,{cache:'force-cache'});if(!res.ok)throw new Error(`Asset premium HTTP ${res.status}`);const bmp=await createImageBitmap(await res.blob());const t=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,t);gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL,false);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,bmp);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.REPEAT);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.REPEAT);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR_MIPMAP_LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.generateMipmap(gl.TEXTURE_2D);bmp.close?.();return t}
function getContext(gl){let d=contextData.get(gl);if(!d){d={neutralEnv:solidTexture(gl,[22,32,46,255]),neutralDetail:solidTexture(gl,[128,128,128,255]),tiers:{},loading:{}};contextData.set(gl,d)}return d}
function packReady(tier){const id=premium[tier]?.pack;if(!id)return false;const selected=tierFor(window.DSPerformance?.actualMode)===tier;if(selected)return true;if(window.DSPackManager?.isInstalled)return window.DSPackManager.isInstalled(id);try{const s=JSON.parse(localStorage.getItem('ds-package-summary')||'null');const v=s?.installed?.[id];return v?.status==='installed'}catch(_){return false}}
function ensurePremium(gl,tier){if(!tier||!premium[tier])return;if(!packReady(tier)){state.premiumStatus='required';updatePremiumUi(tier,'required');return}const d=getContext(gl);if(d.tiers[tier]||d.loading[tier])return;state.premiumStatus='loading';updatePremiumUi(tier,'loading');d.loading[tier]=Promise.all([imageTexture(gl,premium[tier].env),imageTexture(gl,premium[tier].detail)]).then(([env,detail])=>{d.tiers[tier]={env,detail};delete d.loading[tier];state.premiumStatus='ready';updatePremiumUi(tier,'ready');document.dispatchEvent(new CustomEvent('ds-premium-assets-ready',{detail:{tier}}))}).catch(err=>{console.warn('Pacote premium indisponível; mantendo shader base.',err);delete d.loading[tier];state.premiumStatus='error';updatePremiumUi(tier,'error')})}
function uniforms(gl,loc,mode=window.DSPerformance?.actualMode){const q=normalizeMode(mode),id=target(q),p={...profiles[id]},tier=(id==='lite'||q==='advanced')?null:tierFor(q);if(tier)Object.assign(p,premium[tier]);const d=getContext(gl);ensurePremium(gl,tier);const tex=tier&&d.tiers[tier];if(loc.level)gl.uniform1f(loc.level,p.level);if(loc.exposure)gl.uniform1f(loc.exposure,p.exposure);if(loc.saturation)gl.uniform1f(loc.saturation,p.saturation);if(loc.rim)gl.uniform1f(loc.rim,p.rim);if(loc.specular)gl.uniform1f(loc.specular,p.specular);if(loc.hasPremium)gl.uniform1f(loc.hasPremium,tex?1:0);if(loc.envStrength)gl.uniform1f(loc.envStrength,p.envStrength||0);if(loc.detailStrength)gl.uniform1f(loc.detailStrength,p.detailStrength||0);if(loc.clearcoat)gl.uniform1f(loc.clearcoat,p.clearcoat||0);gl.activeTexture(gl.TEXTURE4);gl.bindTexture(gl.TEXTURE_2D,tex?.env||d.neutralEnv);if(loc.envMap)gl.uniform1i(loc.envMap,4);gl.activeTexture(gl.TEXTURE5);gl.bindTexture(gl.TEXTURE_2D,tex?.detail||d.neutralDetail);if(loc.detailMap)gl.uniform1i(loc.detailMap,5);gl.activeTexture(gl.TEXTURE0)}
function dispose(gl){const d=contextData.get(gl);if(!d)return;for(const t of [d.neutralEnv,d.neutralDetail,...Object.values(d.tiers).flatMap(x=>[x.env,x.detail])])try{gl.deleteTexture(t)}catch(_){}contextData.delete(gl)}
document.addEventListener('ds-quality-change',e=>apply(e.detail.actual,'quality'));document.addEventListener('ds-view-change',e=>{state.view=e.detail.current;const desired=target();apply(window.DSPerformance?.actualMode,desired==='lite'&&map[normalizeMode(window.DSPerformance?.actualMode)]!=='lite'?'area-limit':'view')});document.addEventListener('ds-pack-installed',e=>{if(['graphics-ultra-core','graphics-cinematic'].includes(e.detail.id))apply(window.DSPerformance?.actualMode,'pack-installed')});document.addEventListener('DOMContentLoaded',()=>apply(window.DSPerformance?.actualMode||'intermediate','boot'));
window.DSRendererProfile={profiles,premium,state,target,apply,shaderSources,bind,uniforms,dispose,get current(){return profiles[state.actual]}};
})();
