(() => {
'use strict';
const manifest=window.DS_VFX||{effects:[]};
const qualityBudget={basic:60,intermediate:220,advanced:650,ultra:1400,realism:2200,economy:60,balanced:220,high:650,ultraAdvanced:2200,auto:220};
const effectMap=Object.fromEntries(manifest.effects.map(e=>[e.id,e]));
const hex=h=>{h=h.replace('#','');return [parseInt(h.slice(0,2),16),parseInt(h.slice(2,4),16),parseInt(h.slice(4,6),16)]};
const rgba=(h,a=1)=>{const c=hex(h);return `rgba(${c[0]},${c[1]},${c[2]},${a})`};
class VFXStage{
 constructor(canvas,{transparent=true,autoStart=null}={}){this.canvas=canvas;this.ctx=canvas.getContext('2d',{alpha:true});this.transparent=transparent;this.effect=null;this.started=0;this.particles=[];this.bursts=[];this.running=true;this.last=performance.now();this.quality=document.body.dataset.quality||'auto';this.reduced=document.body.classList.contains('reduce-motion');this.resizeObserver=new ResizeObserver(()=>this.resize());this.resizeObserver.observe(canvas.parentElement||canvas);this.resize();this.loop=this.loop.bind(this);requestAnimationFrame(this.loop);if(autoStart)this.play(autoStart)}
 resize(){const box=this.canvas.parentElement?.getBoundingClientRect()||this.canvas.getBoundingClientRect();const dpr=Math.min(window.devicePixelRatio||1,this.quality==='realism'?2.5:this.quality==='ultra'?2.15:this.quality==='advanced'?1.7:this.quality==='intermediate'?1.3:1);this.canvas.width=Math.max(1,Math.round(box.width*dpr));this.canvas.height=Math.max(1,Math.round(box.height*dpr));this.canvas.style.width=box.width+'px';this.canvas.style.height=box.height+'px';this.dpr=dpr;this.w=box.width;this.h=box.height;}
 setQuality(q){this.quality=q;this.resize()}
 play(id){const e=effectMap[id];if(!e)return false;window.DSCacheMemory?.register?.({id:`vfx:${this.canvas.id||'stage'}`,label:`Partículas ${e.name}`,module:'vfx',type:'particle-buffer',bytes:(qualityBudget[this.quality]||250)*96,transient:true,dispose:()=>this.stop()});this.effect=e;this.started=performance.now();this.particles=[];this.bursts=[];this.nextSpawn=0;this.phase=0;this.running=true;this.canvas.dataset.effect=id;return true}
 stop(){this.effect=null;this.particles=[];this.bursts=[];delete this.canvas.dataset.effect}
 spawn(p){const budget=qualityBudget[this.quality]||250;if(this.particles.length<budget)this.particles.push(p)}
 particle(x,y,vx,vy,life,color,size=4,extra={}){this.spawn({x,y,vx,vy,life,maxLife:life,color,size,z:extra.z||0,spin:extra.spin||0,rot:extra.rot||0,shape:extra.shape||'circle',gravity:extra.gravity??0.02,drag:extra.drag??.99})}
 update(dt,now){if(!this.effect)return;const e=this.effect,t=(now-this.started)/1000,scale=this.reduced?.45:1;const cx=this.w/2,cy=this.h*.62; if(e.durationMs&&!e.loop&&now-this.started>e.durationMs){this.stop();return}
   const rate=(n)=>Math.max(1,Math.round(n*scale*(this.quality==='basic'?.42:this.quality==='realism'?1.85:this.quality==='ultra'?1.42:this.quality==='advanced'?1.12:1)));
   if(e.type==='aura'){for(let i=0;i<rate(4);i++){let a=Math.random()*Math.PI*2,r=35+Math.random()*Math.min(this.w*.22,120),x=cx+Math.cos(a)*r,y=cy+Math.sin(a)*r*.18;this.particle(x,y,(Math.random()-.5)*.35,-(.8+Math.random()*1.6),1.1+Math.random()*1.3,e.colors[i%e.colors.length],2+Math.random()*6,{gravity:-.005,drag:.985,shape:Math.random()<.22?'diamond':'circle'});} }
   if(e.type==='confetti'&&this.nextSpawn<now){this.nextSpawn=now+35;for(let i=0;i<rate(8);i++)this.particle(Math.random()*this.w,-15,Math.random()*1.8-.9,1.2+Math.random()*2.4,3+Math.random()*3,e.colors[i%e.colors.length],5+Math.random()*7,{shape:'rect',gravity:.025,spin:(Math.random()-.5)*.25});}
   if(e.type==='snow'&&this.nextSpawn<now){this.nextSpawn=now+40;for(let i=0;i<rate(3);i++)this.particle(Math.random()*this.w,-10,Math.random()*.6-.3,.45+Math.random()*1.1,7+Math.random()*5,e.colors[i%e.colors.length],2+Math.random()*5,{gravity:.003,drag:1});}
   if(e.type==='coins'&&t<1.2&&this.nextSpawn<now){this.nextSpawn=now+45;for(let i=0;i<rate(5);i++){let a=Math.random()*Math.PI*2,s=2+Math.random()*4;this.particle(cx,cy-40,Math.cos(a)*s,Math.sin(a)*s-2,2.8+Math.random()*1.5,e.colors[0],7+Math.random()*8,{shape:'coin',gravity:.07,spin:.14});}}
   if(e.type==='fireworks'&&this.nextSpawn<now&&t<7.5){this.nextSpawn=now+650;let bx=this.w*(.2+Math.random()*.6),by=this.h*(.15+Math.random()*.35);for(let i=0;i<rate(34);i++){let a=i/34*Math.PI*2+Math.random()*.12,s=1.4+Math.random()*3;this.particle(bx,by,Math.cos(a)*s,Math.sin(a)*s,1.5+Math.random()*1.4,e.colors[i%e.colors.length],2+Math.random()*4,{gravity:.035,drag:.975});}}
   if(e.type==='portal'&&this.nextSpawn<now){this.nextSpawn=now+30;for(let i=0;i<rate(4);i++){let a=Math.random()*Math.PI*2,r=Math.min(this.w,this.h)*(.16+Math.random()*.11);this.particle(cx+Math.cos(a)*r,cy-60+Math.sin(a)*r,Math.cos(a+1.57)*.7,Math.sin(a+1.57)*.7,1.2+Math.random(),e.colors[i%e.colors.length],2+Math.random()*5,{gravity:0,drag:.995});}}
   if(e.type==='rocket'&&t<4.8&&this.nextSpawn<now){this.nextSpawn=now+18;let ry=this.h+40-(t/4.8)*(this.h+100);for(let i=0;i<rate(4);i++)this.particle(cx+(Math.random()-.5)*18,ry+42,Math.random()*1.4-.7,1+Math.random()*2,1+Math.random(),e.colors[2],4+Math.random()*8,{gravity:.015,shape:'rect'});if(t>4.2&&!this.burstDone){this.burstDone=true;for(let i=0;i<rate(70);i++){let a=Math.random()*Math.PI*2,s=1.5+Math.random()*4.5;this.particle(cx,this.h*.14,Math.cos(a)*s,Math.sin(a)*s,2+Math.random(),e.colors[i%e.colors.length],2+Math.random()*5,{gravity:.035});}}}
   if(e.type==='levelup'&&this.nextSpawn<now){this.nextSpawn=now+30;for(let i=0;i<rate(3);i++)this.particle(cx+(Math.random()-.5)*150,cy+80,Math.random()*.6-.3,-1-Math.random()*2,1.5+Math.random()*1.5,e.colors[i%e.colors.length],3+Math.random()*7,{gravity:-.005,shape:'diamond'});}
   if(e.type==='powerup'&&this.nextSpawn<now){this.nextSpawn=now+24;for(let i=0;i<rate(5);i++){let a=Math.random()*Math.PI*2,r=30+Math.random()*140;this.particle(cx+Math.cos(a)*r,cy+Math.sin(a)*r*.22,Math.cos(a)*.6,-1.2-Math.random()*2,1.2+Math.random(),e.colors[i%e.colors.length],3+Math.random()*7,{gravity:-.01});}}
   this.particles.forEach(p=>{p.vx*=p.drag;p.vy=p.vy*p.drag+p.gravity*dt*60;p.x+=p.vx*dt*60;p.y+=p.vy*dt*60;p.rot+=p.spin*dt*60;p.life-=dt});this.particles=this.particles.filter(p=>p.life>0&&p.y<this.h+100&&p.x>-100&&p.x<this.w+100);
 }
 drawBase(now){const c=this.ctx,d=this.dpr;c.setTransform(d,0,0,d,0,0);c.clearRect(0,0,this.w,this.h);if(!this.transparent){let g=c.createRadialGradient(this.w/2,this.h*.55,10,this.w/2,this.h*.55,this.w*.7);g.addColorStop(0,'#0b2940');g.addColorStop(1,'#030813');c.fillStyle=g;c.fillRect(0,0,this.w,this.h)}if(!this.effect)return;const e=this.effect,t=(now-this.started)/1000,cx=this.w/2,cy=this.h*.62;c.globalCompositeOperation='lighter';
  if(e.type==='aura'||e.type==='powerup'){for(let j=0;j<4;j++){let r=45+j*28+Math.sin(t*2+j)*8;c.strokeStyle=rgba(e.colors[j%e.colors.length],.28);c.lineWidth=2+j;c.beginPath();c.ellipse(cx,cy,r,r*.2,0,0,Math.PI*2);c.stroke()}let grad=c.createLinearGradient(0,cy+50,0,cy-220);grad.addColorStop(0,rgba(e.colors[0],.05));grad.addColorStop(.55,rgba(e.colors[0],.22));grad.addColorStop(1,rgba(e.colors[1]||e.colors[0],0));c.fillStyle=grad;c.beginPath();c.moveTo(cx-100,cy+30);c.lineTo(cx-45,cy-220);c.lineTo(cx+45,cy-220);c.lineTo(cx+100,cy+30);c.closePath();c.fill()}
  if(e.type==='radar'){let r=Math.min(this.w,this.h)*.34;for(let k=1;k<=3;k++){c.strokeStyle=rgba(e.colors[0],.22);c.lineWidth=2;c.beginPath();c.arc(cx,cy-35,r*k/3,0,Math.PI*2);c.stroke()}let a=t*1.8;c.strokeStyle=rgba(e.colors[1],.95);c.lineWidth=4;c.beginPath();c.moveTo(cx,cy-35);c.lineTo(cx+Math.cos(a)*r,cy-35+Math.sin(a)*r);c.stroke();c.fillStyle=rgba(e.colors[0],.14);c.beginPath();c.moveTo(cx,cy-35);c.arc(cx,cy-35,r,a-.45,a);c.closePath();c.fill()}
  if(e.type==='hologram'||e.type==='lab'){c.strokeStyle=rgba(e.colors[0],.18);c.lineWidth=1;for(let y=40;y<this.h-20;y+=12){c.beginPath();c.moveTo(30,y);c.lineTo(this.w-30,y);c.stroke()}let sy=(t*90)%(this.h+100)-50;c.fillStyle=rgba(e.colors[0],.2);c.fillRect(20,sy,this.w-40,18)}
  if(e.type==='glitch'){for(let i=0;i<8;i++){let y=(Math.sin(t*8+i*2)*.5+.5)*this.h,w=50+Math.random()*this.w*.5,x=Math.random()*(this.w-w);c.fillStyle=rgba(e.colors[i%e.colors.length],.18+Math.random()*.25);c.fillRect(x,y,w,2+Math.random()*12)}c.globalCompositeOperation='source-over'}
  if(e.type==='portal'){let r=Math.min(this.w,this.h)*.26;for(let k=0;k<5;k++){c.strokeStyle=rgba(e.colors[k%e.colors.length],.25+k*.09);c.lineWidth=3+k;c.beginPath();c.arc(cx,cy-60,r+k*12+Math.sin(t*3+k)*6,t*(.4+k*.08),t*(.4+k*.08)+Math.PI*1.55);c.stroke()}}
  if(e.type==='levelup'){let g=c.createLinearGradient(cx-70,0,cx+70,0);g.addColorStop(0,rgba(e.colors[0],0));g.addColorStop(.5,rgba(e.colors[1],.38));g.addColorStop(1,rgba(e.colors[0],0));c.fillStyle=g;c.fillRect(cx-80,20,160,this.h-30)}
  if(e.type==='rocket'&&t<4.8){let ry=this.h+40-(t/4.8)*(this.h+100);c.fillStyle='#eaf7ff';c.beginPath();c.moveTo(cx,ry-50);c.lineTo(cx-18,ry);c.lineTo(cx-13,ry+52);c.lineTo(cx+13,ry+52);c.lineTo(cx+18,ry);c.closePath();c.fill();c.fillStyle=rgba(e.colors[1],.9);c.fillRect(cx-7,ry,14,35)}
 }
 drawParticles(){const c=this.ctx;for(const p of this.particles){let a=Math.max(0,p.life/p.maxLife);c.save();c.translate(p.x,p.y);c.rotate(p.rot);c.shadowColor=p.color;c.shadowBlur=Math.max(4,p.size*2.2);c.fillStyle=rgba(p.color,a);if(p.shape==='rect')c.fillRect(-p.size/2,-p.size,p.size,p.size*2);else if(p.shape==='diamond'){c.rotate(Math.PI/4);c.fillRect(-p.size/2,-p.size/2,p.size,p.size)}else if(p.shape==='coin'){c.beginPath();c.ellipse(0,0,p.size,p.size*.65,0,0,Math.PI*2);c.fill();c.strokeStyle='rgba(255,255,220,.8)';c.lineWidth=2;c.stroke()}else{c.beginPath();c.arc(0,0,p.size,0,Math.PI*2);c.fill()}c.restore()}c.globalCompositeOperation='source-over';c.shadowBlur=0}
 loop(now){let dt=Math.min(.04,(now-this.last)/1000);this.last=now;if(!document.hidden&&this.running){this.update(dt,now);this.drawBase(now);this.drawParticles()}requestAnimationFrame(this.loop)}
}
const stages=[];document.querySelectorAll('canvas[data-vfx-stage]').forEach(canvas=>stages.push(new VFXStage(canvas,{transparent:canvas.dataset.transparent!=='false'})));
const main=stages.find(s=>s.canvas.id==='vfxStudioCanvas')||stages[0];const overlay=stages.find(s=>s.canvas.id==='vfxCanvas');
function play(id,{avatarClip=true}={}){const activeView=document.querySelector('.view.active')?.id;if(activeView==='effectsView')main?.play(id);else if(activeView==='avatarView')overlay?.play(id);else{main?.play(id);overlay?.play(id)}const e=effectMap[id];if(avatarClip&&e){if(e.type==='rocket')window.DSAvatarViewer?.play('RocketCelebrate');else if(e.type==='powerup'||e.type==='aura')window.DSAvatarViewer?.play('AuraPowerUp');else if(e.type==='fireworks'||e.type==='confetti')window.DSAvatarViewer?.play('Celebrate')}document.dispatchEvent(new CustomEvent('ds-vfx-play',{detail:{id,effect:e}}));return !!e}
function stop(){stages.forEach(s=>s.stop());for(const s of stages)window.DSCacheMemory?.unregister?.(`vfx:${s.canvas.id||'stage'}`,'vfx-stop')}
function setQuality(q){stages.forEach(s=>s.setQuality(q))}
window.DSVFX={play,stop,setQuality,effects:manifest.effects,stages};document.addEventListener('ds-view-change',e=>{if(e.detail.current==='effectsView'){overlay?.stop();const id=main?.canvas?.dataset.defaultEffect||'aura-energy-blue';main?.play(id);const effect=effectMap[id];document.getElementById('vfxNowPlaying')?.replaceChildren(document.createTextNode(effect?.name||'Efeito'))}else main?.stop();if(e.detail.current!=='avatarView')overlay?.stop()});document.addEventListener('ds-quality-change',e=>setQuality(e.detail.actual));
document.addEventListener('click',ev=>{const b=ev.target.closest('[data-vfx-effect]');if(b){play(b.dataset.vfxEffect);document.querySelectorAll('[data-vfx-effect]').forEach(x=>x.classList.toggle('active',x===b));const e=effectMap[b.dataset.vfxEffect];document.getElementById('vfxNowPlaying')?.replaceChildren(document.createTextNode(e?.name||'Efeito'))}const speech=ev.target.closest('[data-speech-text]');if(speech){const activeView=document.querySelector('.view.active')?.id;const bubble=document.getElementById(activeView==='effectsView'?'vfxSpeechBubble':'avatarSpeechBubble');if(bubble){bubble.textContent=speech.dataset.speechText;bubble.hidden=false;clearTimeout(bubble._hideTimer);bubble._hideTimer=setTimeout(()=>bubble.hidden=true,3400)}}});
document.addEventListener('change',ev=>{if(ev.target.id==='reduceMotion'){stages.forEach(s=>s.reduced=ev.target.checked)}});
})();