import { ImmersiveInputController } from '../../core/input/ImmersiveInputController.js';
import { MuseumExperienceModel } from '../../core/museum-remaster/MuseumExperienceModel.js';
import { SpaceMuseumSceneRenderer } from '../../rendering/SpaceMuseumSceneRenderer.js';
import { MUSEUM_ZONES,MUSEUM_EXHIBITS,MUSEUM_CAMERAS,MUSEUM_MISSIONS,EXHIBIT_BY_ID,ZONE_BY_ID } from '../../data/visualMuseumSystems.js';
import { TECHNICAL_EXHIBIT_MAP } from '../../data/technicalMuseumSystems.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cameraLabel=id=>MUSEUM_CAMERAS.find(item=>item.id===id)?.label||id;
class VisualMuseumModule{
  constructor(){this.container=null;this.context=null;this.model=new MuseumExperienceModel();this.renderer=null;this.input=null;this.raf=0;this.last=0;this.fps=0;this.panel=null;this.help=false;this.photo=false;this.animationActive=false;this.settingsUnsub=null;this.onClick=e=>this.handleClick(e);this.onKeyDown=e=>this.handleKeyDown(e);}
  mount(container,context){this.container=container;this.context=context;container.addEventListener('click',this.onClick);addEventListener('keydown',this.onKeyDown);this.restore();const requested=sessionStorage.getItem('cosmos-ds-museum-target');sessionStorage.removeItem('cosmos-ds-museum-target');if(EXHIBIT_BY_ID[requested])this.model.selectExhibit(EXHIBIT_BY_ID[requested]);this.render();this.startRuntime();this.settingsUnsub=context.bus.on('settings:changed',()=>this.restart());}
  unmount(){cancelAnimationFrame(this.raf);this.renderer?.destroy();this.input?.detach();this.settingsUnsub?.();this.container?.removeEventListener('click',this.onClick);removeEventListener('keydown',this.onKeyDown);}
  restore(){const completed=this.context.profileStore.active().completedExperiences;for(const item of MUSEUM_EXHIBITS){if(completed.includes(`museum-inspect-${item.id}`))this.model.inspected.add(item.id);if(completed.includes(`museum-interior-${item.id}`))this.model.interiors.add(item.id);if(completed.includes(`museum-animation-${item.id}`))this.model.animations.add(item.id);if(completed.includes(`museum-catalog-${item.id}`))this.model.cataloged.add(item.id);}for(const zone of MUSEUM_ZONES)if(completed.includes(`museum-zone-${zone.id}`))this.model.visitedZones.add(zone.id);}
  render(){const profile=this.context.settingsStore.getProfile(),current=EXHIBIT_BY_ID[this.model.exhibitId],zone=ZONE_BY_ID[current.zone];this.container.innerHTML=`<section class="visual-museum-module quality-${profile.id}"><div class="visual-museum-stage ${this.photo?'photo-mode':''}" id="visual-museum-stage">
    <canvas id="visual-museum-canvas" aria-label="Museu espacial visual 3D navegável em 360 graus"></canvas><div class="museum-vignette"></div><div class="museum-grain"></div><div class="museum-light-sweep"></div>
    <header class="museum-top immersive-hud"><button class="hud-icon" data-action="back">←</button><div class="target-chip"><span id="museum-symbol">${current.symbol}</span><div><b id="museum-name">${esc(current.name)}</b><small id="museum-zone">${esc(zone.name)}</small></div></div><div class="museum-top-actions"><span class="hud-status" id="museum-camera">${cameraLabel(this.model.cameraMode)}</span><span class="hud-status"><b id="museum-fps">--</b> FPS</span><button class="hud-icon" data-action="toggle-help">?</button><button class="hud-icon" data-action="fullscreen">⛶</button></div></header>
    <div class="museum-objective immersive-hud"><span>MUSEU VISUAL</span><b id="museum-objective">Caminhe, inspecione peças, abra interiores e ative mecanismos.</b></div>
    <aside class="museum-telemetry immersive-hud"><div><span>GALERIAS</span><b id="museum-zones">1/4</b></div><div><span>360°</span><b id="museum-inspected">0/6</b></div><div><span>INTERIORES</span><b id="museum-interiors">0/3</b></div><div><span>CATÁLOGO</span><b id="museum-cataloged">0/12</b></div></aside>
    <div class="museum-crosshair"><i></i><i></i></div>
    <nav class="museum-camera-rail immersive-hud">${MUSEUM_CAMERAS.map(item=>`<button class="${item.id===this.model.cameraMode?'active':''}" data-action="set-camera" data-camera="${item.id}"><i>${item.short}</i><span>${esc(item.label)}</span></button>`).join('')}</nav>
    <div class="museum-actions immersive-hud"><button data-action="inspect">INSPECIONAR</button><button data-action="interior" ${current.interior?'':'disabled'}>INTERIOR</button><button data-action="animate">ANIMAR</button><button data-action="toggle-map">MAPA</button><button data-action="toggle-info">FICHA</button>${TECHNICAL_EXHIBIT_MAP[current.id]?'<button data-action="open-technical-panel">PAINEL</button><button data-action="open-space-workshop">OFICINA</button>':''}<button data-action="toggle-photo">FOTO</button></div>
    <nav class="museum-zone-dock immersive-hud">${MUSEUM_ZONES.map(item=>`<button class="${item.id===zone.id?'active':''}" style="--zone-color:${item.color}" data-action="select-zone" data-zone="${item.id}"><i></i><span>${esc(item.name)}</span></button>`).join('')}</nav>
    <div class="museum-exhibit-dock immersive-hud">${MUSEUM_EXHIBITS.map(item=>`<button class="${item.id===current.id?'active':''}" style="--exhibit-color:${item.color}" data-action="select-exhibit" data-exhibit="${item.id}" title="${esc(item.name)}"><i>${item.symbol}</i><span>${esc(item.name)}</span></button>`).join('')}</div>
    <aside class="museum-info-drawer immersive-hud" id="museum-info"><button class="drawer-close" data-action="toggle-info">×</button><div id="museum-info-content">${this.infoMarkup(current)}</div></aside>
    <aside class="museum-map-drawer immersive-hud" id="museum-map"><button class="drawer-close" data-action="toggle-map">×</button><span class="eyebrow">PLANTA INTERATIVA</span><h3>Quatro galerias</h3>${MUSEUM_ZONES.map(item=>`<button class="museum-map-zone" style="--zone-color:${item.color}" data-action="select-zone" data-zone="${item.id}"><i></i><span><b>${esc(item.name)}</b><small>${esc(item.description)}</small></span></button>`).join('')}</aside>
    <aside class="museum-help immersive-hud" id="museum-help"><button class="drawer-close" data-action="toggle-help">×</button><span class="eyebrow">CONTROLES</span><h3>Visite como um jogo</h3><div class="control-grid"><span><kbd>WASD</kbd> caminhar</span><span><kbd>Mouse</kbd> olhar / girar</span><span><kbd>C</kbd> trocar câmera</span><span><kbd>V</kbd> próxima peça</span><span><kbd>Z</kbd> próxima galeria</span><span><kbd>I</kbd> inspecionar</span><span><kbd>E</kbd> animar</span><span><kbd>P</kbd> foto</span></div><p>Use inspeção 360° para observar detalhes e o modo interior quando a peça permitir.</p></aside>
    <div class="virtual-joysticks museum-joysticks"><div class="virtual-joystick left" data-stick="left"><div class="joystick-ring"></div><div class="joystick-knob"></div><span>ANDAR</span></div><div class="virtual-joystick right" data-stick="right"><div class="joystick-ring"></div><div class="joystick-knob"></div><span>OLHAR</span></div></div>
    <div class="museum-mobile-actions immersive-hud"><button data-action="inspect">360</button><button data-action="cycle-camera">C</button><button data-action="animate">AÇÃO</button></div>
    <div class="museum-loading" id="museum-loading"><i></i><span>Abrindo galerias holográficas…</span></div>
  </div></section>`;}
  startRuntime(){const canvas=this.container.querySelector('#visual-museum-canvas');this.input=new ImmersiveInputController({canvas,root:this.container,leftStick:this.container.querySelector('[data-stick="left"]'),rightStick:this.container.querySelector('[data-stick="right"]')});this.input.attach();this.renderer=new SpaceMuseumSceneRenderer(canvas,this.context.settingsStore,{onDiagnostics:d=>{if(d.state==='context-lost')this.context.toast('Contexto gráfico perdido. O passeio foi preservado.');}});this.renderer.start();this.last=performance.now();const tick=now=>{const dt=Math.min(.05,(now-this.last)/1000||.016);this.last=now;this.model.update(dt,this.input.sample());const exhibitIndex=MUSEUM_EXHIBITS.findIndex(item=>item.id===this.model.exhibitId),zoneIndex=MUSEUM_ZONES.findIndex(item=>item.id===this.model.zoneId);this.renderer.setState({exhibitIndex,zoneIndex,snapshot:this.model.snapshot(),animation:this.animationActive});this.fps=Math.round(1/Math.max(.001,dt));this.updateHud();this.raf=requestAnimationFrame(tick);};this.raf=requestAnimationFrame(tick);setTimeout(()=>this.container.querySelector('#museum-loading')?.classList.add('hidden'),500);}
  restart(){if(!this.container?.isConnected)return;cancelAnimationFrame(this.raf);this.renderer?.destroy();this.input?.detach();this.startRuntime();this.context.toast(`Renderização atualizada para ${this.context.settingsStore.getProfile().label}.`);}
  handleClick(event){const target=event.target.closest('[data-action]');if(!target)return;const action=target.dataset.action;if(action==='back')return this.context.onBack();if(action==='select-exhibit')return this.selectExhibit(target.dataset.exhibit);if(action==='select-zone')return this.selectZone(target.dataset.zone);if(action==='set-camera')return this.setCamera(target.dataset.camera);if(action==='cycle-camera')return this.cycleCamera();if(action==='inspect')return this.inspect();if(action==='interior')return this.openInterior();if(action==='animate')return this.animate();if(action==='toggle-map')return this.togglePanel('map');if(action==='toggle-info')return this.togglePanel('info');if(action==='toggle-help'){this.help=!this.help;this.updatePanels();return;}if(action==='open-technical-panel'){const systemId=TECHNICAL_EXHIBIT_MAP[this.model.exhibitId];if(!systemId)return this.context.toast('Esta peça ainda não possui painel operacional.');sessionStorage.setItem('cosmos-ds-technical-target',systemId);return this.context.openModule('technical-operations');}if(action==='open-space-workshop'){const systemId=TECHNICAL_EXHIBIT_MAP[this.model.exhibitId];if(!systemId)return this.context.toast('Esta peça ainda não possui oficina.');sessionStorage.setItem('cosmos-ds-workshop-target',systemId);return this.context.openModule('space-workshop');}if(action==='toggle-photo'){this.photo=this.model.togglePhotoMode();this.container.querySelector('#visual-museum-stage')?.classList.toggle('photo-mode',this.photo);return;}if(action==='fullscreen')return this.container.querySelector('#visual-museum-stage')?.requestFullscreen?.();}
  handleKeyDown(event){if(['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName))return;const key=event.key.toLowerCase();if(key==='c')this.cycleCamera();if(key==='v')this.cycleExhibit();if(key==='z')this.cycleZone();if(key==='i')this.inspect();if(key==='e')this.animate();if(key==='p'){this.photo=this.model.togglePhotoMode();this.container.querySelector('#visual-museum-stage')?.classList.toggle('photo-mode',this.photo);}if(key==='r')this.model.resetCamera();}
  selectExhibit(id){const item=EXHIBIT_BY_ID[id];if(!item)return;this.model.selectExhibit(item);this.animationActive=this.model.animations.has(id);this.panel=null;this.updatePanels();this.updateExhibitUi();this.award(`museum-catalog-${id}`,40,'Peça adicionada ao catálogo');}
  selectZone(id){const zone=ZONE_BY_ID[id];if(!zone)return;this.model.selectZone(id);const first=MUSEUM_EXHIBITS.find(item=>item.zone===id);if(first)this.model.selectExhibit(first);this.award(`museum-zone-${id}`,65,`${zone.name} visitada`);this.updateExhibitUi();this.checkMissions();}
  cycleExhibit(){const index=MUSEUM_EXHIBITS.findIndex(item=>item.id===this.model.exhibitId);this.selectExhibit(MUSEUM_EXHIBITS[(index+1)%MUSEUM_EXHIBITS.length].id);}
  cycleZone(){const index=MUSEUM_ZONES.findIndex(item=>item.id===this.model.zoneId);this.selectZone(MUSEUM_ZONES[(index+1)%MUSEUM_ZONES.length].id);}
  setCamera(id){const item=EXHIBIT_BY_ID[this.model.exhibitId];if(!this.model.setCameraMode(id,{interiorAvailable:item.interior})){this.context.toast('Esta peça não possui interior explorável.');return;}this.container.querySelectorAll('.museum-camera-rail button').forEach(btn=>btn.classList.toggle('active',btn.dataset.camera===id));const el=this.container.querySelector('#museum-camera');if(el)el.textContent=cameraLabel(id);}
  cycleCamera(){const order=['walk','orbit',EXHIBIT_BY_ID[this.model.exhibitId].interior?'interior':'cinematic','cinematic'];const index=order.indexOf(this.model.cameraMode);this.setCamera(order[(index+1)%order.length]);}
  inspect(){const id=this.model.exhibitId;this.model.inspect();this.setCamera('orbit');this.award(`museum-inspect-${id}`,80,'Inspeção 360° registrada');this.checkMissions();}
  openInterior(){const item=EXHIBIT_BY_ID[this.model.exhibitId];if(!this.model.openInterior(item.interior)){this.context.toast('Interior indisponível nesta peça.');return;}this.award(`museum-interior-${item.id}`,110,'Interior explorado');this.container.querySelectorAll('.museum-camera-rail button').forEach(btn=>btn.classList.toggle('active',btn.dataset.camera==='interior'));this.checkMissions();}
  animate(){const item=EXHIBIT_BY_ID[this.model.exhibitId];this.animationActive=!this.animationActive;if(this.animationActive){this.model.activateAnimation();this.award(`museum-animation-${item.id}`,90,`Mecanismo ${item.animation} ativado`);this.checkMissions();}this.context.toast(`${item.name}: animação ${this.animationActive?'ativada':'pausada'}.`);}
  award(id,xp,label){const awarded=this.context.profileStore.addXp(xp,id);if(awarded)this.context.toast(`${label}: +${xp} XP.`);}
  checkMissions(){const p=this.model.progress();const checks=[['visit-zones',p.zones>=4],['inspect-six',p.inspected>=6],['open-interiors',p.interiors>=3],['animate-five',p.animations>=5],['complete-catalog',p.cataloged>=12]];for(const [id,done] of checks){if(done){const mission=MUSEUM_MISSIONS.find(item=>item.id===id);this.award(`museum-mission-${id}`,mission.xp,mission.label);}}if(checks.every(([,done])=>done))this.award('museum-certification',500,'Certificação Curador do Museu Espacial');}
  togglePanel(name){this.panel=this.panel===name?null:name;this.updatePanels();}
  updatePanels(){this.container.querySelector('#museum-info')?.classList.toggle('open',this.panel==='info');this.container.querySelector('#museum-map')?.classList.toggle('open',this.panel==='map');this.container.querySelector('#museum-help')?.classList.toggle('open',this.help);}
  updateExhibitUi(){const item=EXHIBIT_BY_ID[this.model.exhibitId],zone=ZONE_BY_ID[item.zone];const set=(s,v)=>{const el=this.container.querySelector(s);if(el)el.textContent=v;};set('#museum-symbol',item.symbol);set('#museum-name',item.name);set('#museum-zone',zone.name);set('#museum-camera',cameraLabel(this.model.cameraMode));this.container.querySelectorAll('.museum-exhibit-dock button').forEach(btn=>btn.classList.toggle('active',btn.dataset.exhibit===item.id));this.container.querySelectorAll('.museum-zone-dock button').forEach(btn=>btn.classList.toggle('active',btn.dataset.zone===zone.id));const info=this.container.querySelector('#museum-info-content');if(info)info.innerHTML=this.infoMarkup(item);const interior=this.container.querySelector('[data-action="interior"]');if(interior)interior.disabled=!item.interior;}
  updateHud(){const p=this.model.progress();const set=(s,v)=>{const el=this.container.querySelector(s);if(el)el.textContent=v;};set('#museum-fps',String(this.fps));set('#museum-zones',`${p.zones}/4`);set('#museum-inspected',`${p.inspected}/6`);set('#museum-interiors',`${p.interiors}/3`);set('#museum-cataloged',`${p.cataloged}/12`);set('#museum-camera',cameraLabel(this.model.cameraMode));set('#museum-objective',p.cataloged>=12?'Catálogo completo. Continue explorando em modo livre.':`Galerias ${p.zones}/4 · inspeções ${p.inspected}/6 · interiores ${p.interiors}/3 · catálogo ${p.cataloged}/12.`);}
  infoMarkup(item){return `<div class="museum-info-symbol" style="--exhibit-color:${item.color}">${item.symbol}</div><span class="eyebrow">${esc(ZONE_BY_ID[item.zone].name)}</span><h2>${esc(item.name)}</h2><p>${esc(item.description)}</p><div class="museum-info-metrics"><span><b>ESCALA</b>${esc(item.scale)}</span><span><b>INTERIOR</b>${item.interior?'Disponível':'Externo'}</span><span><b>MECANISMO</b>${esc(item.animation)}</span><span><b>PAINEL</b>${TECHNICAL_EXHIBIT_MAP[item.id]?'Operacional':'Ficha 3D'}</span></div>`;}
}
export const createModule=()=>new VisualMuseumModule();
