'use strict';
(function(){
  window.LABDS_LABS=window.LABDS_LABS||{};
  const KEY='lab.displaymedia.state';
  const DEFAULT={tab:'fps',fps:60,hz:60,pixelScale:16,color:'#32e6b0',wave:'sine',frequency:440,xp:0};
  let root,ctx,state,raf=0,audioCtx=null,osc=null,gain=null;
  async function save(){await ctx.storage.set(KEY,state);}
  function setTab(tab){state.tab=tab;root.querySelectorAll('[data-dm-tab]').forEach(b=>b.classList.toggle('active',b.dataset.dmTab===tab));root.querySelectorAll('[data-dm-panel]').forEach(p=>p.classList.toggle('hidden',p.dataset.dmPanel!==tab));save();if(tab==='fps')startFps();else stopFps();if(tab==='pixels')drawPixels();if(tab==='audio')drawWave();}
  function drawFpsFrame(c,w,h,t){c.clearRect(0,0,w,h);const g=c.createLinearGradient(0,0,w,h);g.addColorStop(0,'#050c17');g.addColorStop(1,'#0b2638');c.fillStyle=g;c.fillRect(0,0,w,h);c.strokeStyle='rgba(100,230,255,.1)';for(let x=0;x<w;x+=32){c.beginPath();c.moveTo(x,0);c.lineTo(x,h);c.stroke();}const speed=state.fps/18,x=(t*speed/100)% (w+120)-60;c.fillStyle='#56f0bd';c.fillRect(x,h*.55,46,46);c.fillStyle='#6be7ff';c.fillRect(w-x-46,h*.28,46,46);c.fillStyle='#eaf8ff';c.font='700 17px system-ui';c.fillText(`${state.fps} FPS renderizados`,18,30);c.fillStyle='#a8c9dc';c.font='14px system-ui';c.fillText(`${state.hz} Hz exibidos • ${Math.min(state.fps,state.hz)} quadros distintos/s`,18,54);if(state.fps>state.hz){c.fillStyle='#ffcb67';c.fillText(`${state.fps-state.hz} quadros/s não aparecem como quadros únicos no monitor`,18,78);}else if(state.fps<state.hz){c.fillStyle='#ffcb67';c.fillText(`${state.hz-state.fps} atualizações/s repetem o último quadro disponível`,18,78);}else{c.fillStyle='#58efb8';c.fillText('FPS e Hz estão sincronizados nesta simulação.',18,78);}}
  function startFps(){cancelAnimationFrame(raf);const canvas=root.querySelector('#fpsCanvas');if(!canvas)return;const c=canvas.getContext('2d');const loop=t=>{const rect=canvas.getBoundingClientRect(),ratio=(window.LABDS?.PerformanceManager?.canvasScale?.(2)??Math.min(2,devicePixelRatio||1));if(canvas.width!==Math.round(rect.width*ratio)||canvas.height!==Math.round(rect.height*ratio)){canvas.width=Math.round(rect.width*ratio);canvas.height=Math.round(rect.height*ratio);c.setTransform(ratio,0,0,ratio,0,0);}drawFpsFrame(c,rect.width,rect.height,t);raf=requestAnimationFrame(loop);};raf=requestAnimationFrame(loop);}
  function stopFps(){cancelAnimationFrame(raf);raf=0;}
  function hexRgb(hex){const n=parseInt(hex.slice(1),16);return[(n>>16)&255,(n>>8)&255,n&255];}
  function drawPixels(){const canvas=root.querySelector('#pixelCanvas');if(!canvas)return;const c=canvas.getContext('2d'),rect=canvas.getBoundingClientRect(),ratio=(window.LABDS?.PerformanceManager?.canvasScale?.(2)??Math.min(2,devicePixelRatio||1));canvas.width=Math.round(rect.width*ratio);canvas.height=Math.round(rect.height*ratio);c.setTransform(ratio,0,0,ratio,0,0);c.fillStyle='#02060d';c.fillRect(0,0,rect.width,rect.height);const [r,g,b]=hexRgb(state.color),cols=Math.max(6,Math.floor(rect.width/state.pixelScale)),rows=Math.max(5,Math.floor(rect.height/state.pixelScale));for(let y=0;y<rows;y++)for(let x=0;x<cols;x++){const px=x*state.pixelScale,py=y*state.pixelScale,w=state.pixelScale-2;c.fillStyle=`rgb(${r},0,0)`;c.fillRect(px,py,w/3,w);c.fillStyle=`rgb(0,${g},0)`;c.fillRect(px+w/3,py,w/3,w);c.fillStyle=`rgb(0,0,${b})`;c.fillRect(px+2*w/3,py,w/3,w);}root.querySelector('#pixelInfo').textContent=`Cada pixel é aproximado por subpixels vermelho ${r}, verde ${g} e azul ${b}. Zoom ${state.pixelScale} px.`;}
  function drawWave(){const canvas=root.querySelector('#waveCanvas');if(!canvas)return;const c=canvas.getContext('2d'),rect=canvas.getBoundingClientRect(),ratio=(window.LABDS?.PerformanceManager?.canvasScale?.(2)??Math.min(2,devicePixelRatio||1));canvas.width=Math.round(rect.width*ratio);canvas.height=Math.round(rect.height*ratio);c.setTransform(ratio,0,0,ratio,0,0);c.fillStyle='#050b13';c.fillRect(0,0,rect.width,rect.height);c.strokeStyle='rgba(100,230,255,.1)';for(let y=0;y<rect.height;y+=30){c.beginPath();c.moveTo(0,y);c.lineTo(rect.width,y);c.stroke();}c.strokeStyle='#62e9ff';c.lineWidth=3;c.beginPath();for(let x=0;x<rect.width;x++){const phase=x/rect.width*Math.PI*2*(state.frequency/110);let v=Math.sin(phase);if(state.wave==='square')v=Math.sign(v);if(state.wave==='saw')v=2*((phase/(Math.PI*2))%1)-1;if(state.wave==='triangle')v=2*Math.abs(2*((phase/(Math.PI*2))%1)-1)-1;const y=rect.height/2-v*rect.height*.32;x?c.lineTo(x,y):c.moveTo(x,y);}c.stroke();c.fillStyle='#e9f7ff';c.font='700 16px system-ui';c.fillText(`${state.wave} • ${state.frequency} Hz`,16,26);}
  async function toggleTone(){const button=root.querySelector('#toneBtn');if(osc){osc.stop();osc.disconnect();gain.disconnect();osc=null;button.textContent='Ouvir tom';return;}audioCtx=audioCtx||new (window.AudioContext||window.webkitAudioContext)();osc=audioCtx.createOscillator();gain=audioCtx.createGain();osc.type=state.wave;osc.frequency.value=state.frequency;gain.gain.value=.045;osc.connect(gain).connect(audioCtx.destination);osc.start();button.textContent='Parar som';}
  function selectConnector(id){root.querySelectorAll('[data-connector]').forEach(b=>b.classList.toggle('active',b.dataset.connector===id));const data={hdmi:['HDMI','Áudio e vídeo digital; comum em TVs, monitores e consoles.','Até altas resoluções e taxas, conforme a versão.'],dp:['DisplayPort','Vídeo digital com recursos de alta taxa e múltiplos monitores.','Muito usado em PCs e monitores de alto desempenho.'],vga:['VGA','Sinal analógico de vídeo.','Mais sujeito a ruído e perda de nitidez.'],usb:['USB-C','Conector reversível; pode transportar dados, energia e DisplayPort Alt Mode.','Os recursos dependem do cabo e do dispositivo.']}[id];root.querySelector('#connectorTitle').textContent=data[0];root.querySelector('#connectorDesc').textContent=data[1];root.querySelector('#connectorMeta').textContent=data[2];}
  function render(){root.innerHTML=`<div class="immersive-lab display-media-lab"><header class="immersive-hero"><div><span class="eyebrow">RENDERIZAÇÃO • SINAIS • MÍDIA</span><h2>Telas, pixels, FPS, Hertz e áudio</h2><p>Veja como o computador gera quadros, o monitor atualiza a imagem, os subpixels formam cores e o áudio vira uma onda elétrica e digital.</p></div><div class="immersive-badges"><span>Canvas 2D</span><span>Web Audio</span><span>XP <b id="dmXp">${state.xp}</b></span></div></header><nav class="module-tabs"><button data-dm-tab="fps">FPS × Hz</button><button data-dm-tab="pixels">Pixels RGB</button><button data-dm-tab="connectors">Conectores</button><button data-dm-tab="audio">Áudio</button></nav>
    <section data-dm-panel="fps" class="immersive-grid"><article class="immersive-card"><h3>Controle a renderização</h3><label>FPS do jogo <input id="fpsRange" type="range" min="15" max="240" step="15" value="${state.fps}"><b id="fpsValue">${state.fps}</b></label><label>Taxa do monitor <input id="hzRange" type="range" min="30" max="240" step="30" value="${state.hz}"><b id="hzValue">${state.hz} Hz</b></label><div class="knowledge-card"><strong>FPS</strong> é o número de quadros produzidos pelo sistema. <strong>Hz</strong> é quantas vezes a tela pode atualizar por segundo. A experiência também depende de latência, sincronização e tempo de quadro.</div></article><article class="immersive-card"><div class="visual-stage"><canvas id="fpsCanvas" aria-label="Simulação de FPS e Hertz"></canvas></div></article></section>
    <section data-dm-panel="pixels" class="immersive-grid hidden"><article class="immersive-card"><h3>Amplie os subpixels</h3><label>Cor<input id="pixelColor" type="color" value="${state.color}"></label><label>Ampliação<input id="pixelScale" type="range" min="8" max="34" value="${state.pixelScale}"></label><p id="pixelInfo"></p><div class="metric-row"><div class="metric-card"><small>RGB</small><strong>Luz aditiva</strong></div><div class="metric-card"><small>Branco</small><strong>R + G + B</strong></div><div class="metric-card"><small>Preto</small><strong>subpixels apagados</strong></div></div></article><article class="immersive-card"><div class="visual-stage"><canvas id="pixelCanvas" aria-label="Subpixels RGB ampliados"></canvas></div></article></section>
    <section data-dm-panel="connectors" class="immersive-grid hidden"><article class="immersive-card"><h3>Escolha o conector</h3><div class="connector-picker"><button data-connector="hdmi">HDMI</button><button data-connector="dp">DisplayPort</button><button data-connector="vga">VGA</button><button data-connector="usb">USB-C</button></div><div class="connector-visual"><i id="connectorPlug"></i><span>fonte</span><b>→</b><span>monitor</span></div></article><article class="immersive-card"><h3 id="connectorTitle">HDMI</h3><p id="connectorDesc"></p><div class="knowledge-card" id="connectorMeta"></div><h3>Diagnóstico rápido</h3><ul><li>Confirme a entrada selecionada no monitor.</li><li>Verifique capacidade do cabo e da porta.</li><li>Ajuste resolução e taxa de atualização.</li><li>Evite adaptadores incompatíveis.</li></ul></article></section>
    <section data-dm-panel="audio" class="immersive-grid hidden"><article class="immersive-card"><h3>Gere uma forma de onda</h3><label>Forma<select id="waveSelect"><option value="sine">Senoidal</option><option value="square">Quadrada</option><option value="saw">Dente de serra</option><option value="triangle">Triangular</option></select></label><label>Frequência<input id="frequencyRange" type="range" min="110" max="1760" step="10" value="${state.frequency}"><b id="frequencyValue">${state.frequency} Hz</b></label><button id="toneBtn" class="btn primary">Ouvir tom</button><p class="muted-copy">Volume reduzido. O som só inicia após sua ação.</p></article><article class="immersive-card"><div class="visual-stage"><canvas id="waveCanvas" aria-label="Forma de onda de áudio"></canvas></div><div class="flow-track"><div class="flow-node">Microfone<br><small>pressão → sinal</small></div><span class="flow-arrow">›</span><div class="flow-node">ADC<br><small>amostragem</small></div><span class="flow-arrow">›</span><div class="flow-node">Processamento<br><small>dados</small></div><span class="flow-arrow">›</span><div class="flow-node">DAC + caixa<br><small>sinal → som</small></div></div></article></section></div>`;
    root.querySelectorAll('[data-dm-tab]').forEach(b=>b.addEventListener('click',()=>setTab(b.dataset.dmTab)));root.querySelector('#fpsRange').addEventListener('input',e=>{state.fps=Number(e.target.value);root.querySelector('#fpsValue').textContent=state.fps;save();});root.querySelector('#hzRange').addEventListener('input',e=>{state.hz=Number(e.target.value);root.querySelector('#hzValue').textContent=`${state.hz} Hz`;save();});root.querySelector('#pixelColor').addEventListener('input',e=>{state.color=e.target.value;drawPixels();save();});root.querySelector('#pixelScale').addEventListener('input',e=>{state.pixelScale=Number(e.target.value);drawPixels();save();});root.querySelectorAll('[data-connector]').forEach(b=>b.addEventListener('click',()=>selectConnector(b.dataset.connector)));root.querySelector('#waveSelect').value=state.wave;root.querySelector('#waveSelect').addEventListener('change',e=>{state.wave=e.target.value;drawWave();if(osc)osc.type=state.wave;save();});root.querySelector('#frequencyRange').addEventListener('input',e=>{state.frequency=Number(e.target.value);root.querySelector('#frequencyValue').textContent=`${state.frequency} Hz`;if(osc)osc.frequency.value=state.frequency;drawWave();save();});root.querySelector('#toneBtn').addEventListener('click',toggleTone);selectConnector('hdmi');setTab(state.tab);
  }
  async function mount(host,context){root=host;ctx=context;state={...DEFAULT,...await ctx.storage.get(KEY,DEFAULT)};render();}
  async function unmount(){stopFps();if(osc){osc.stop();osc.disconnect();osc=null;}await save();root=null;ctx=null;state=null;}
  function exportPayload(){return{text:`DISPLAY E MÍDIA\nFPS: ${state.fps}\nHz: ${state.hz}\nFrequência: ${state.frequency} Hz`,native:JSON.stringify(state,null,2),backup:state,meta:[{label:'FPS',value:String(state.fps)},{label:'Hz',value:String(state.hz)}]};}
  function help(){return'<h3>Telas e áudio</h3><p>Altere FPS, Hz, pixels e ondas. A simulação destaca conceitos, mas não mede o desempenho real do aparelho.</p>';}
  window.LABDS_LABS['display-media-lab']={mount,unmount,exportPayload,help};
})();
