import { SPACE_WORKSHOP_BY_ID,WORKSHOP_DIFFICULTIES,WORKSHOP_FLOW_TYPES } from '../../data/spaceWorkshopSystems.js';
const clone=value=>JSON.parse(JSON.stringify(value));
export class SpaceAssemblyModel{
  constructor(systemId='satellite',difficulty='guided'){this.systemId='';this.difficulty='guided';this.selectedComponentId=null;this.selectedFlow='energy';this.installed=new Map();this.connected=new Set();this.inspected=new Set();this.actions=[];this.diagnostics=[];this.activeFault=null;this.repairedFaults=new Set();this.testRuns=0;this.startedAt=new Date().toISOString();this.elapsed=0;this.selectSystem(systemId);this.setDifficulty(difficulty);}
  system(){return SPACE_WORKSHOP_BY_ID[this.systemId];}
  selectSystem(id){if(!SPACE_WORKSHOP_BY_ID[id])return false;this.systemId=id;this.selectedComponentId=this.system().components[0]?.id||null;this.selectedFlow='energy';this.installed=new Map();this.connected=new Set();this.inspected=new Set();this.actions=[];this.diagnostics=[];this.activeFault=null;this.repairedFaults=new Set();this.testRuns=0;this.startedAt=new Date().toISOString();this.elapsed=0;if(this.difficulty==='advanced')this.injectFault(this.system().faults[0].id);return true;}
  setDifficulty(id){if(!WORKSHOP_DIFFICULTIES.some(item=>item.id===id))return false;this.difficulty=id;this.record('difficulty',{id});if(id==='advanced'&&!this.activeFault)this.injectFault(this.system().faults[0].id);return true;}
  selectFlow(id){if(!WORKSHOP_FLOW_TYPES.some(item=>item.id===id))return false;this.selectedFlow=id;this.record('flow',{id});return true;}
  selectComponent(id){if(!this.system().components.some(item=>item.id===id))return false;this.selectedComponentId=id;this.inspected.add(id);this.record('inspect-component',{componentId:id});return true;}
  expectedSlot(componentId){return this.system().components.find(item=>item.id===componentId)?.slot||null;}
  installedSlot(componentId){for(const [slot,id] of this.installed)if(id===componentId)return slot;return null;}
  nextRequiredComponent(){return this.system().components.slice().sort((a,b)=>a.order-b.order).find(item=>!this.installedSlot(item.id))||null;}
  placeComponent(componentId,slotId){const component=this.system().components.find(item=>item.id===componentId),slot=this.system().slots.find(item=>item.id===slotId);if(!component||!slot)return {ok:false,reason:'Componente ou encaixe não encontrado.'};const next=this.nextRequiredComponent();if(this.difficulty==='guided'&&next?.id!==componentId)return {ok:false,reason:`No modo guiado, instale primeiro: ${next.name}.`};if(this.difficulty==='guided'&&component.slot!==slotId)return {ok:false,reason:`O encaixe correto de ${component.name} está destacado.`};const previousSlot=this.installedSlot(componentId);if(previousSlot)this.installed.delete(previousSlot);const displaced=this.installed.get(slotId);if(displaced)this.installed.delete(slotId);this.installed.set(slotId,componentId);this.selectedComponentId=componentId;this.record('place-component',{componentId,slotId,correct:component.slot===slotId,displaced:displaced||null});this.diagnostics=[];return {ok:true,correct:component.slot===slotId,displaced};}
  removeComponent(componentId){const slot=this.installedSlot(componentId);if(!slot)return {ok:false,reason:'O componente ainda não está instalado.'};this.installed.delete(slot);for(const link of this.system().links)if(link.from===componentId||link.to===componentId)this.connected.delete(link.id);this.record('remove-component',{componentId,slot});this.diagnostics=[];return {ok:true,slot};}
  toggleConnection(linkId){const link=this.system().links.find(item=>item.id===linkId);if(!link)return {ok:false,reason:'Conexão não encontrada.'};if(!this.installedSlot(link.from)||!this.installedSlot(link.to))return {ok:false,reason:'Instale os dois componentes antes de conectar.'};if(this.connected.has(linkId)){this.connected.delete(linkId);this.record('disconnect',{linkId,type:link.type});return {ok:true,connected:false,link};}this.connected.add(linkId);this.record('connect',{linkId,type:link.type});this.diagnostics=[];return {ok:true,connected:true,link};}
  injectFault(id){const fault=this.system().faults.find(item=>item.id===id);if(!fault)return null;this.activeFault=clone(fault);if(fault.type==='connection')this.connected.delete(fault.target);this.record('inject-fault',{faultId:id,target:fault.target,type:fault.type});return clone(fault);}
  repairFault(){if(!this.activeFault)return {ok:false,reason:'Nenhuma falha ativa.'};const fault=this.activeFault;if(fault.type==='connection'){const link=this.system().links.find(item=>item.id===fault.target);if(!link||!this.connected.has(link.id))return {ok:false,reason:'Reconecte o enlace indicado antes de confirmar o reparo.'};}else{const installed=this.installedSlot(fault.target);if(!installed)return {ok:false,reason:'Reinstale ou substitua o componente com falha.'};const lastRemove=[...this.actions].reverse().find(item=>item.type==='remove-component'&&item.detail.componentId===fault.target);const lastPlace=[...this.actions].reverse().find(item=>item.type==='place-component'&&item.detail.componentId===fault.target);if(!lastRemove||!lastPlace||new Date(lastPlace.at)<=new Date(lastRemove.at))return {ok:false,reason:'Remova e reinstale o componente para registrar a substituição.'};}
    this.repairedFaults.add(fault.id);this.activeFault=null;this.record('repair-fault',{faultId:fault.id});this.diagnostics=[];return {ok:true,fault};}
  runDiagnostics(){const system=this.system(),issues=[];for(const component of system.components){const slot=this.installedSlot(component.id);if(!slot)issues.push({kind:'missing-component',target:component.id,label:`${component.name} não instalado.`});else if(slot!==component.slot)issues.push({kind:'wrong-slot',target:component.id,label:`${component.name} está no encaixe ${slot}, esperado ${component.slot}.`});}
    for(const link of system.links.filter(item=>item.required))if(!this.connected.has(link.id))issues.push({kind:'missing-connection',target:link.id,label:`Conexão ausente: ${link.label}.`});if(this.activeFault)issues.push({kind:'active-fault',target:this.activeFault.target,label:`Falha ativa: ${this.activeFault.label}.`});this.testRuns++;this.diagnostics=issues;this.record('run-diagnostics',{issues:issues.length,testRuns:this.testRuns});return {ok:issues.length===0,issues:clone(issues),progress:this.progress()};}
  autoStep(){const next=this.nextRequiredComponent();if(next)return {kind:'install',componentId:next.id,slotId:next.slot,label:`Instale ${next.name} em ${next.slot}.`,why:next.role};const nextLink=this.system().links.find(item=>item.required&&!this.connected.has(item.id));if(nextLink)return {kind:'connect',linkId:nextLink.id,label:`Conecte ${nextLink.label}.`,why:`Fluxo de ${nextLink.type}.`};if(this.activeFault)return {kind:'repair',target:this.activeFault.target,label:`Repare: ${this.activeFault.label}.`,why:this.activeFault.diagnostic};if(!this.testRuns||this.diagnostics.length)return {kind:'test',label:'Execute o diagnóstico final.',why:'Confirme montagem, cabos e ausência de falhas.'};return {kind:'complete',label:'Oficina concluída. Gere a evidência.',why:this.system().outcome};}
  progress(){const system=this.system(),correct=system.components.filter(item=>this.installedSlot(item.id)===item.slot).length,requiredLinks=system.links.filter(item=>item.required),links=requiredLinks.filter(item=>this.connected.has(item.id)).length,flows=new Set(requiredLinks.filter(item=>this.connected.has(item.id)).map(item=>item.type));const complete=correct===system.components.length&&links===requiredLinks.length&&!this.activeFault&&this.testRuns>0&&this.diagnostics.length===0;return {installed:this.installed.size,correct,totalComponents:system.components.length,connected:links,totalConnections:requiredLinks.length,flows:flows.size,repaired:this.repairedFaults.size,testRuns:this.testRuns,issues:this.diagnostics.length,complete,percent:Math.round(((correct/system.components.length)*.48+(links/requiredLinks.length)*.37+(this.testRuns?0.1:0)+(!this.activeFault?0.05:0))*100)};}
  update(dt=.016){this.elapsed+=Math.max(0,Number(dt)||0);}
  record(type,detail={}){this.actions.push({type,detail,at:new Date().toISOString()});if(this.actions.length>300)this.actions.shift();}
  snapshot(){return {systemId:this.systemId,difficulty:this.difficulty,selectedComponentId:this.selectedComponentId,selectedFlow:this.selectedFlow,installed:Object.fromEntries(this.installed),connected:[...this.connected],inspected:[...this.inspected],activeFault:this.activeFault?clone(this.activeFault):null,repairedFaults:[...this.repairedFaults],diagnostics:clone(this.diagnostics),actions:clone(this.actions),testRuns:this.testRuns,elapsed:this.elapsed,progress:this.progress(),nextAction:this.autoStep()};}
  evidence(profile={}){const snap=this.snapshot(),system=this.system();return {schema:'cosmos-ds-space-workshop-evidence-v1',generatedAt:new Date().toISOString(),student:{id:profile.id||'',name:profile.name||'',className:profile.className||'',callsign:profile.callsign||''},workshop:{id:system.id,name:system.name,story:system.story,outcome:system.outcome,difficulty:this.difficulty},session:{startedAt:this.startedAt,elapsedSeconds:Math.round(this.elapsed),progress:snap.progress,installed:snap.installed,connections:snap.connected,repairedFaults:snap.repairedFaults,testRuns:snap.testRuns},diagnostics:snap.diagnostics,actions:snap.actions.slice(-120)};}
}
