import {
  CULTURE_SOURCES, SPACE_ORGANIZATIONS, SPACE_CAREERS, SPACE_CULTURE_WORKS,
  CULTURE_DISCOVERY_TRAILS, CULTURE_DISCUSSION_PROMPTS, CULTURE_INTERESTS, CULTURE_DISCOVERY_GOALS
} from '../../data/cultureDiscoverySystems.js';
import { CultureDiscoveryEngine } from '../../core/culture/CultureDiscoveryEngine.js';
import { CultureDiscoveryStore } from '../../core/culture/CultureDiscoveryStore.js';
import { CulturalConstellationRenderer } from '../../rendering/CulturalConstellationRenderer.js';

const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const typeLabel=type=>({organization:'Agência ou empresa',career:'Carreira',work:'Obra cultural'}[type]||type);
const workType=type=>({film:'Filme',series:'Série',documentary:'Documentário',book:'Livro',game:'Jogo'}[type]||type);

class CultureDiscoveryModule {
  constructor(){
    this.container=null;this.context=null;this.engine=new CultureDiscoveryEngine({organizations:SPACE_ORGANIZATIONS,careers:SPACE_CAREERS,works:SPACE_CULTURE_WORKS,trails:CULTURE_DISCOVERY_TRAILS,sources:CULTURE_SOURCES});
    this.store=null;this.renderer=null;this.tab='discover';this.query='';this.filter='all';this.selectedType='work';this.selectedId='interstellar';this.interests=[];this.recommendation=null;this.compareCareers=[];
    this.onClick=e=>this.handleClick(e);this.onInput=e=>this.handleInput(e);this.onChange=e=>this.handleChange(e);
  }
  mount(container,context){
    this.container=container;this.context=context;this.store=new CultureDiscoveryStore(context.profileStore.storage,context.profileStore.active().id);const state=this.store.snapshot();this.interests=state.interests||[];
    if(state.lastViewed){const [type,id]=state.lastViewed.split(':');if(this.engine.get(type,id)){this.selectedType=type;this.selectedId=id;}}
    container.addEventListener('click',this.onClick);container.addEventListener('input',this.onInput);container.addEventListener('change',this.onChange);this.render();this.startRenderer();
  }
  unmount(){this.renderer?.destroy();this.container?.removeEventListener('click',this.onClick);this.container?.removeEventListener('input',this.onInput);this.container?.removeEventListener('change',this.onChange);}
  snapshot(){return this.store.snapshot();}
  render(){
    const state=this.snapshot(),selected=this.engine.get(this.selectedType,this.selectedId)||SPACE_CULTURE_WORKS[0];
    this.container.innerHTML=`<section class="culture-discovery">
      <header class="culture-hero"><div><span class="eyebrow">Fase C5.1 · Cultura, organizações e carreiras</span><h2>Entre no espaço por aquilo que <span>desperta sua curiosidade.</span></h2><p>Agências, empresas, profissões, filmes, séries, documentários, livros e jogos conectados aos laboratórios do COSMOS DS. Sem imagens, cenas ou trilhas protegidas.</p></div><div class="culture-hero-actions"><button class="button secondary" data-action="back">← Portal leve</button><button class="button secondary" data-action="open-project-studio">Projetos e portfólio</button><button class="button primary" data-action="export-evidence">Exportar descoberta</button></div></header>
      <nav class="culture-tabs">${[
        ['discover','Descobrir'],['organizations','Agências e indústria'],['careers','Carreiras'],['culture','Espaço na cultura'],['trails','Trilhas'],['discussion','Discussão']
      ].map(([id,label])=>`<button class="${this.tab===id?'active':''}" data-action="tab" data-tab="${id}">${label}</button>`).join('')}</nav>
      <main>${this.tab==='discover'?this.discoverMarkup(selected,state):this.tab==='organizations'?this.organizationsMarkup(state):this.tab==='careers'?this.careersMarkup(state):this.tab==='culture'?this.cultureMarkup(state):this.tab==='trails'?this.trailsMarkup(state):this.discussionMarkup(state)}</main>
    </section>`;
  }
  discoverMarkup(selected,state){
    const items=this.engine.search(this.query,this.filter);return `<section class="culture-discover-layout">
      <div class="culture-stage-wrap"><canvas id="culture-constellation" aria-label="Constelação visual de organizações, carreiras e obras culturais"></canvas><div class="culture-stage-legend"><span class="org">Agências e empresas</span><span class="career">Carreiras</span><span class="work">Cultura</span></div></div>
      <aside class="culture-control-panel"><div class="culture-search-row"><input id="culture-search" value="${escapeHtml(this.query)}" placeholder="Buscar NASA, programação, Marte, Interestelar…"><select id="culture-filter"><option value="all" ${this.filter==='all'?'selected':''}>Tudo</option><option value="organization" ${this.filter==='organization'?'selected':''}>Organizações</option><option value="career" ${this.filter==='career'?'selected':''}>Carreiras</option><option value="work" ${this.filter==='work'?'selected':''}>Obras</option></select></div><div class="culture-results">${items.slice(0,12).map(item=>this.resultCard(item,state)).join('')||'<p>Nenhum resultado encontrado.</p>'}</div></aside>
      <article class="culture-detail-card">${this.detailMarkup(selected,state)}</article>
    </section>`;
  }
  resultCard(item,state){const key=`${item.entityType}:${item.id}`,favorite=state.favorites.includes(key);return `<button class="culture-result-card ${key===`${this.selectedType}:${this.selectedId}`?'selected':''}" data-action="select-item" data-type="${item.entityType}" data-id="${item.id}"><span>${item.entityType==='organization'?'◎':item.entityType==='career'?'◆':'◈'}</span><div><small>${typeLabel(item.entityType)}</small><b>${escapeHtml(item.name||item.title)}</b><p>${escapeHtml(item.summary||item.entry)}</p></div>${favorite?'<i>★</i>':''}</button>`;}
  detailMarkup(item,state){
    const type=item.entityType||this.selectedType,id=item.id,key=`${type}:${id}`,favorite=state.favorites.includes(key);if(type==='organization'){const source=this.engine.source(item.sourceId);return `<span class="eyebrow">${item.kind==='company'?'INDÚSTRIA':'ORGANIZAÇÃO'} · ${escapeHtml(item.region)}</span><h3>${escapeHtml(item.name)}</h3><p>${escapeHtml(item.summary)}</p><div class="culture-metric-row"><span><b>${item.founded}</b> fundação</span><span><b>${item.focus.length}</b> áreas</span><span><b>${item.modules.length}</b> laboratórios</span></div><h4>Focos</h4><div class="culture-chip-row">${item.focus.map(value=>`<span>${escapeHtml(value)}</span>`).join('')}</div><h4>Tecnologias relacionadas</h4><ul>${item.technology.map(value=>`<li>${escapeHtml(value)}</li>`).join('')}</ul><h4>Exemplos para pesquisar</h4><p>${item.examples.map(escapeHtml).join(' · ')}</p><div class="culture-detail-actions"><button data-action="favorite" data-type="${type}" data-id="${id}">${favorite?'★ Remover favorito':'☆ Favoritar'}</button>${source?`<button data-action="open-source" data-source="${item.sourceId}">Fonte oficial</button>`:''}${item.modules.slice(0,2).map(module=>`<button data-action="open-related" data-module="${module}">Abrir ${escapeHtml(this.context.moduleRegistry.definition(module)?.title||module)}</button>`).join('')}</div>`;}
    if(type==='career'){return `<span class="eyebrow">CARREIRA · ${escapeHtml(item.area)}</span><h3>${escapeHtml(item.name)}</h3><p>${escapeHtml(item.summary)}</p><h4>Competências</h4><div class="culture-chip-row">${item.skills.map(value=>`<span>${escapeHtml(value)}</span>`).join('')}</div><h4>Ferramentas e práticas</h4><p>${item.tools.map(escapeHtml).join(' · ')}</p><section class="culture-challenge"><b>DESAFIO DS</b><p>${escapeHtml(item.challenge)}</p></section><div class="culture-detail-actions"><button data-action="favorite" data-type="${type}" data-id="${id}">${favorite?'★ Remover favorito':'☆ Favoritar'}</button><button data-action="compare-career" data-id="${id}">${this.compareCareers.includes(id)?'Remover da comparação':'Comparar carreira'}</button>${item.modules.slice(0,2).map(module=>`<button data-action="open-related" data-module="${module}">Experimentar laboratório</button>`).join('')}</div>`;}
    const balance=this.engine.scienceFictionBalance(id);return `<span class="eyebrow">${workType(item.type)} · ${item.year} · ${escapeHtml(item.tone)}</span><h3>${escapeHtml(item.title)}</h3><p>${escapeHtml(item.entry)}</p><div class="culture-balance"><div><span>Ciência e conceitos</span><i><em style="width:${balance.sciencePercent}%"></em></i></div><div><span>Ficção ou dramatização</span><i><em class="fiction" style="width:${balance.fictionPercent}%"></em></i></div></div><h4>Conexões científicas</h4><ul>${item.science.map(value=>`<li>${escapeHtml(value)}</li>`).join('')}</ul><h4>O que precisa ser separado da realidade</h4><ul>${item.fiction.map(value=>`<li>${escapeHtml(value)}</li>`).join('')}</ul><section class="culture-challenge"><b>PARA DISCUTIR</b><p>${escapeHtml(item.discussion)}</p></section><small class="culture-rights-note">Referência textual e educacional. Nenhuma cena, imagem promocional, personagem, fala ou trilha sonora foi incorporada.</small><div class="culture-detail-actions"><button data-action="favorite" data-type="${type}" data-id="${id}">${favorite?'★ Remover favorito':'☆ Favoritar'}</button>${item.modules.slice(0,3).map(module=>`<button data-action="open-related" data-module="${module}">Conectar ao laboratório</button>`).join('')}</div>`;
  }
  organizationsMarkup(state){return `<section class="culture-section"><div class="culture-section-head"><div><span class="eyebrow">COOPERAÇÃO E INDÚSTRIA</span><h3>Quem pesquisa, constrói, regula e opera?</h3><p>As fichas separam agências públicas, institutos e empresas. Os exemplos são pontos de partida e não representam um ranking.</p></div><div class="culture-counter">${SPACE_ORGANIZATIONS.length}<small>organizações</small></div></div><div class="culture-card-grid">${SPACE_ORGANIZATIONS.map(item=>this.entityCard('organization',item,state)).join('')}</div></section>`;}
  careersMarkup(state){const selected=SPACE_CAREERS.filter(item=>this.compareCareers.includes(item.id));return `<section class="culture-section"><div class="culture-section-head"><div><span class="eyebrow">CARREIRAS</span><h3>Espaço também é software, dados, testes e interface</h3><p>Compare funções e abra os laboratórios que simulam parte dessas atividades.</p></div><div class="culture-counter">${SPACE_CAREERS.length}<small>carreiras</small></div></div>${selected.length?`<div class="career-compare">${selected.map(item=>`<article><b>${escapeHtml(item.name)}</b><span>${escapeHtml(item.area)}</span><p>${item.skills.map(escapeHtml).join(' · ')}</p></article>`).join('')}</div>`:''}<div class="culture-card-grid">${SPACE_CAREERS.map(item=>this.entityCard('career',item,state)).join('')}</div></section>`;}
  cultureMarkup(state){return `<section class="culture-section"><div class="culture-section-head"><div><span class="eyebrow">ESPAÇO NA CULTURA</span><h3>Use obras como porta de entrada, não como fonte única</h3><p>Cada ficha distingue conceitos científicos, licença narrativa e perguntas para discussão.</p></div><div class="culture-counter">${SPACE_CULTURE_WORKS.length}<small>referências</small></div></div><div class="culture-card-grid culture-work-grid">${SPACE_CULTURE_WORKS.map(item=>this.entityCard('work',item,state)).join('')}</div></section>`;}
  entityCard(type,item,state){const key=`${type}:${item.id}`,favorite=state.favorites.includes(key),subtitle=type==='organization'?`${item.region} · ${item.founded}`:type==='career'?item.area:`${workType(item.type)} · ${item.year}`;return `<article class="culture-entity-card"><header><span>${type==='organization'?'◎':type==='career'?'◆':'◈'}</span><div><small>${escapeHtml(subtitle)}</small><h4>${escapeHtml(item.name||item.title)}</h4></div>${favorite?'<i>★</i>':''}</header><p>${escapeHtml(item.summary||item.entry)}</p><footer><button data-action="select-and-discover" data-type="${type}" data-id="${item.id}">Abrir ficha</button>${type==='career'?`<button data-action="compare-career" data-id="${item.id}">Comparar</button>`:''}</footer></article>`;}
  trailsMarkup(state){const recommendation=this.recommendation||this.engine.recommend(this.interests);return `<section class="culture-section"><div class="culture-section-head"><div><span class="eyebrow">TRILHAS DE DESCOBERTA</span><h3>O que mais chama sua atenção?</h3><p>Selecione interesses para receber uma sequência coerente de ferramentas e laboratórios.</p></div></div><div class="culture-interest-grid">${CULTURE_INTERESTS.map(item=>`<label class="${this.interests.includes(item.id)?'selected':''}"><input type="checkbox" data-interest="${item.id}" ${this.interests.includes(item.id)?'checked':''}><span>${item.icon}</span><b>${item.label}</b></label>`).join('')}</div><div class="hero-actions"><button class="button primary" data-action="recommend">Montar recomendação</button><button class="button secondary" data-action="start-official-culture-trail">Iniciar trilha Cultura Espacial</button></div>${recommendation?.trail?`<article class="culture-recommendation"><span class="eyebrow">RECOMENDAÇÃO</span><h3>${escapeHtml(recommendation.trail.title)}</h3><p>${escapeHtml(recommendation.trail.summary)}</p><ol>${recommendation.trail.steps.map((module,index)=>`<li><span>${index+1}</span><div><b>${escapeHtml(this.context.moduleRegistry.definition(module)?.title||module)}</b><small>${module==='culture-discovery'?'Comece reconhecendo interesses, referências e carreiras.':'Abra a experiência quando chegar a esta etapa.'}</small></div>${module!=='culture-discovery'?`<button data-action="open-related" data-module="${module}">Abrir</button>`:''}</li>`).join('')}</ol></article>`:''}<div class="culture-trail-grid">${CULTURE_DISCOVERY_TRAILS.map(trail=>`<article><span>${CULTURE_INTERESTS.find(item=>item.id===trail.interest)?.icon||'✦'}</span><h4>${escapeHtml(trail.title)}</h4><p>${escapeHtml(trail.summary)}</p><small>${trail.steps.length} etapas</small><button data-action="choose-internal-trail" data-id="${trail.id}">${state.selectedTrail===trail.id?'Trilha selecionada':'Selecionar trilha'}</button></article>`).join('')}</div></section>`;}
  discussionMarkup(state){return `<section class="culture-section"><div class="culture-section-head"><div><span class="eyebrow">ATIVIDADE DE DISCUSSÃO</span><h3>Da curiosidade para a argumentação</h3><p>Registre respostas curtas. Elas entram na evidência exportada e podem ser usadas pelo professor em uma trilha personalizada.</p></div></div><div class="culture-discussion-grid">${CULTURE_DISCUSSION_PROMPTS.map((item,index)=>`<article><span>${String(index+1).padStart(2,'0')}</span><h4>${escapeHtml(item.title)}</h4><p>${escapeHtml(item.prompt)}</p><textarea data-discussion="${item.id}" maxlength="1200" rows="4" placeholder="Registre sua análise…">${escapeHtml(state.discussions[item.id]||'')}</textarea><button data-action="save-discussion" data-id="${item.id}">Salvar análise</button></article>`).join('')}</div></section>`;}
  startRenderer(){if(this.tab!=='discover')return;const canvas=this.container.querySelector('#culture-constellation');if(!canvas)return;this.renderer?.destroy();this.renderer=new CulturalConstellationRenderer({canvas,reducedMotion:this.context.settingsStore.get().reducedMotion,onSelect:(type,id)=>{this.selectedType=type;this.selectedId=id;this.store.visit(type,id);this.render();this.startRenderer();}});this.renderer.start(this.engine.search(this.query,this.filter));this.renderer.setSelected(`${this.selectedType}:${this.selectedId}`);}
  rerender(){this.renderer?.destroy();this.renderer=null;this.render();this.startRenderer();}
  handleInput(event){if(event.target.id==='culture-search'){this.query=event.target.value;this.rerender();}}
  handleChange(event){if(event.target.id==='culture-filter'){this.filter=event.target.value;this.rerender();return;}if(event.target.matches('[data-interest]')){this.interests=[...this.container.querySelectorAll('[data-interest]:checked')].map(input=>input.dataset.interest);this.store.setInterests(this.interests);this.render();}}
  handleClick(event){const target=event.target.closest('[data-action]');if(!target)return;const action=target.dataset.action;
    if(action==='back'){this.context.onBack();return;}
    if(action==='tab'){this.tab=target.dataset.tab;this.rerender();return;}
    if(action==='select-item'||action==='select-and-discover'){this.selectedType=target.dataset.type;this.selectedId=target.dataset.id;this.store.visit(this.selectedType,this.selectedId);this.tab='discover';this.rerender();return;}
    if(action==='favorite'){this.store.toggleFavorite(target.dataset.type,target.dataset.id);this.render();this.startRenderer();return;}
    if(action==='open-project-studio'){this.context.openModule('project-curation-studio');return;}
    if(action==='open-source'){const source=this.engine.source(target.dataset.source);if(source?.url){window.open(source.url,'_blank','noopener,noreferrer');this.context.toast('Fonte oficial aberta em uma nova aba.');}return;}
    if(action==='open-related'){const moduleId=target.dataset.module;this.store.openedModule(moduleId);this.context.recordGuidedEvent?.('interaction',{kind:'culture-related-lab',moduleId});this.context.openModule(moduleId);return;}
    if(action==='compare-career'){const id=target.dataset.id;this.compareCareers=this.compareCareers.includes(id)?this.compareCareers.filter(item=>item!==id):[...this.compareCareers,id].slice(-2);this.render();return;}
    if(action==='recommend'){this.recommendation=this.engine.recommend(this.interests);this.context.profileStore.addXp(35,'c51-culture-recommendation');this.render();return;}
    if(action==='choose-internal-trail'){this.store.chooseTrail(target.dataset.id);this.context.toast('Trilha de descoberta selecionada.');this.render();return;}
    if(action==='start-official-culture-trail'){const status=this.context.guidedTrails.start('culture');this.context.toast('Trilha Cultura Espacial iniciada.');this.context.openModule(status.currentStep.moduleId);return;}
    if(action==='save-discussion'){const text=this.container.querySelector(`[data-discussion="${target.dataset.id}"]`)?.value||'';this.store.recordDiscussion(target.dataset.id,text);this.context.setGuidedEvidence?.(text);this.context.recordGuidedEvent?.('manual-evidence',{kind:'culture-discussion',id:target.dataset.id});this.context.toast(text.trim().length>=20?'Análise registrada.':'Análise salva; procure desenvolver pelo menos uma ideia completa.');return;}
    if(action==='export-evidence'){this.exportEvidence();return;}
  }
  exportEvidence(){const state=this.snapshot(),profile=this.context.profileStore.active(),payload={schema:'cosmos-ds-culture-discovery-evidence-v1',createdAt:new Date().toISOString(),profile:{id:profile.id,name:profile.name,className:profile.className,callsign:profile.callsign},summary:{visited:state.visited.length,favorites:state.favorites.length,interests:state.interests,selectedTrail:state.selectedTrail,openedModules:state.openedModules},discussions:state.discussions,goals:CULTURE_DISCOVERY_GOALS.map(goal=>({id:goal.id,label:goal.label,completed:this.goalCompleted(goal.id,state)})),editorialNotice:'Conteúdo cultural apresentado por descrições autorais e referências textuais, sem incorporar mídia protegida.'};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`cosmos-cultura-${profile.callsign||'aluno'}.json`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);this.context.profileStore.addXp(120,'c51-culture-evidence');this.context.recordGuidedEvent?.('evidence-exported',{moduleId:'culture-discovery'});this.context.toast('Evidência cultural exportada.');}
  goalCompleted(id,state){if(id==='visit-agency')return state.visited.filter(item=>item.startsWith('organization:')).length>=3;if(id==='compare-careers')return this.compareCareers.length>=2;if(id==='analyze-work')return state.visited.some(item=>item.startsWith('work:'));if(id==='choose-trail')return Boolean(state.selectedTrail||state.interests.length);if(id==='discussion')return Object.values(state.discussions).some(value=>value.trim().length>=20);if(id==='open-lab')return state.openedModules.length>0;return false;}
}
export function createModule(){return new CultureDiscoveryModule();}
