import assert from 'node:assert/strict';
import fs from 'node:fs';
const storage=fs.readFileSync(new URL('../assets/js/storage.js',import.meta.url),'utf8');
const app=fs.readFileSync(new URL('../assets/js/app.js',import.meta.url),'utf8');
const sw=fs.readFileSync(new URL('../sw.js',import.meta.url),'utf8');
assert.match(storage,/freshestRecord/,'Deve comparar IndexedDB e checkpoint redundante.');
assert.match(storage,/revision/,'Deve manter revisão do perfil.');
assert.match(storage,/mergeProtectedData/,'Deve combinar progresso de abas concorrentes.');
assert.match(storage,/mergeLessonProgress/,'Conflito deve preservar uma conclusão já registrada.');
assert.match(storage,/mergeDiagnosticProgress/,'Respostas diagnósticas compatíveis devem ser combinadas.');
assert.match(storage,/BroadcastChannel/,'Deve detectar salvamento em outra aba.');
assert.match(storage,/transactionDone/,'Deve aguardar a conclusão da transação IndexedDB.');
assert.match(storage,/storedDigest/,'A verificação deve comparar o conteúdo salvo.');
assert.match(app,/GUIDED_CHECKPOINT_PREFIX='agv\.guided\.checkpoint\.v3'/);
assert.match(app,/localStorage\.setItem\(checkpointKey/,'Checkpoint deve resistir ao fechamento da aba.');
assert.match(app,/ensureLessonCompleted/,'A conclusão deve ser registrada automaticamente.');
assert.match(app,/startedAtMs\+minimum\*1000/,'A liberação do PDF deve usar horário absoluto.');
assert.match(app,/d\.index\+\+/,'A resposta e o próximo índice devem ser persistidos juntos.');
assert.match(app,/pendingServiceWorker/,'Atualização deve ficar pendente.');
assert.doesNotMatch(sw,/then\(\(\)=>self\.skipWaiting\(\)\)/,'O service worker não deve assumir controle durante a aula.');
assert.match(sw,/Promise\.allSettled/,'Cache inicial deve tolerar um recurso isolado indisponível.');
console.log('Continuidade, múltiplas abas, conclusão, diagnóstico e atualização segura validados.');
