import assert from 'node:assert/strict';
import fs from 'node:fs';
import {APP_VERSION,GUIDED_MINIMUM_MINUTES,LESSONS} from '../assets/js/data.js';
const app=fs.readFileSync(new URL('../assets/js/app.js',import.meta.url),'utf8');
const teacher=fs.readFileSync(new URL('../assets/js/teacher-codes.js',import.meta.url),'utf8');
assert.equal(APP_VERSION,'2.5.7');
assert.equal(GUIDED_MINIMUM_MINUTES,5);
assert.equal(LESSONS.length,13);
const start=app.indexOf('async function openLessonAuthorization(lessonId)');
const end=app.indexOf('function initialGuidedActiveSeconds',start);
const gate=app.slice(start,end);
assert.match(gate,/startLesson\(lesson\)/);
assert.doesNotMatch(gate,/showEduAuthAuthorization/);
assert.match(app,/todas as aulas estão liberadas/i);
assert.match(app,/colocar atividades atrasadas em dia/i);
assert.match(teacher,/ACESSO LIVRE/);
assert.doesNotMatch(teacher,/Senha fixa desta aula/);
console.log('Acesso aberto às aulas e comprovante em cinco minutos validados.');
