'use strict';
(function(){
  window.LABDS_LABS=window.LABDS_LABS||{};
  const KEY='lab.ai.state';
  const DEFAULT={tab:'network',xp:0,epochs:0,accuracy:.5,weights:[.2,-.35,.1,.4,-.2,.25],chat:[]};
  let root,ctx,state,raf=0,training=false,trainingGeneration=0;
  async function save(){await ctx.storage.set(KEY,state);}
  function setTab(tab){state.tab=tab;root.querySelectorAll('[data-ai-tab]').forEach(b=>b.classList.toggle('active',b.dataset.aiTab===tab));root.querySelectorAll('[data-ai-panel]').forEach(p=>p.classList.toggle('hidden',p.dataset.aiPanel!==tab));save();if(tab==='network')drawNetwork();else cancelAnimationFrame(raf);}
  function drawNetwork(){cancelAnimationFrame(raf);const canvas=root.querySelector('#aiNetworkCanvas');if(!canvas)return;const c=canvas.getContext('2d');const loop=t=>{const rect=canvas.getBoundingClientRect(),ratio=Math.min(2,devicePixelRatio||1);if(canvas.width!==Math.round(rect.width*ratio)||canvas.height!==Math.round(rect.height*ratio)){canvas.width=Math.round(rect.width*ratio);canvas.height=Math.round(rect.height*ratio);c.setTransform(ratio,0,0,ratio,0,0);}const w=rect.width,h=rect.height;c.clearRect(0,0,w,h);const g=c.createLinearGradient(0,0,w,h);g.addColorStop(0,'#040a13');g.addColorStop(1,'#10233a');c.fillStyle=g;c.fillRect(0,0,w,h);const layers=[[{x:.12,y:.25},{x:.12,y:.5},{x:.12,y:.75}],[{x:.42,y:.18},{x:.42,y:.4},{x:.42,y:.62},{x:.42,y:.82}],[{x:.7,y:.3},{x:.7,y:.7}],[{x:.9,y:.5}]];let wi=0;for(let l=0;l<layers.length-1;l++)for(const a of layers[l])for(const b of layers[l+1]){const weight=state.weights[wi%state.weights.length],pulse=(Math.sin(t/700+wi)+1)/2;c.strokeStyle=weight>=0?`rgba(89,238,190,${.16+pulse*.32})`:`rgba(255,112,139,${.14+pulse*.25})`;c.lineWidth=1+Math.abs(weight)*4;c.beginPath();c.moveTo(a.x*w,a.y*h);c.lineTo(b.x*w,b.y*h);c.stroke();wi++;}for(const [li,layer] of layers.entries())for(const [ni,n] of layer.entries()){c.beginPath();c.arc(n.x*w,n.y*h,li===3?20:15,0,Math.PI*2);c.fillStyle=li===0?'#153951':li===3?'#58eec0':'#10263d';c.fill();c.strokeStyle='#6ce8ff';c.lineWidth=2;c.stroke();c.fillStyle='#e9f8ff';c.font='700 11px system-ui';c.textAlign='center';c.fillText(li===0?`x${ni+1}`:li===3?'ŷ':`n${ni+1}`,n.x*w,n.y*h+4);}c.fillStyle='#b8d6e7';c.font='14px system-ui';c.textAlign='left';c.fillText(`Épocas: ${state.epochs} • Acurácia simulada: ${(state.accuracy*100).toFixed(1)}%`,16,28);raf=requestAnimationFrame(loop);};raf=requestAnimationFrame(loop);}
  async function train(){if(training||!root)return;training=true;const generation=++trainingGeneration,button=root.querySelector('#trainAi'),log=root.querySelector('#trainingLog'),bar=root.querySelector('#trainingProgress');button.disabled=true;for(let i=0;i<20;i++){await new Promise(r=>setTimeout(r,70));if(generation!==trainingGeneration||!root||!state){training=false;return;}state.epochs++;state.accuracy=Math.min(.97,state.accuracy+(1-state.accuracy)*.035+Math.random()*.004);state.weights=state.weights.map(w=>Math.max(-1,Math.min(1,w+(Math.random()-.47)*.06)));bar.style.width=`${(i+1)*5}%`;log.textContent=`época ${state.epochs.toString().padStart(3,'0')} | perda ${(1-state.accuracy).toFixed(4)} | acurácia ${(state.accuracy*100).toFixed(1)}%\n`+log.textContent.split('\n').slice(0,8).join('\n');root.querySelector('#aiAccuracy').textContent=`${(state.accuracy*100).toFixed(1)}%`;root.querySelector('#aiEpochs').textContent=state.epochs;}if(generation!==trainingGeneration||!root)return;state.xp+=30;root.querySelector('#aiXp').textContent=state.xp;await save();if(generation===trainingGeneration&&button.isConnected)button.disabled=false;training=false;}
  function classify(){const hours=Number(root.querySelector('#featureHours').value),tasks=Number(root.querySelector('#featureTasks').value),errors=Number(root.querySelector('#featureErrors').value),score=1/(1+Math.exp(-(-1.6+hours*.18+tasks*.12-errors*.28))),out=root.querySelector('#classifyOutput');out.className=`practice-feedback ${score>.55?'success':'error'}`;out.textContent=`Probabilidade simulada de conclusão: ${(score*100).toFixed(1)}%. O resultado é apenas um modelo didático com três variáveis.`;state.xp+=10;root.querySelector('#aiXp').textContent=state.xp;save();}
  function tokenize(){const text=root.querySelector('#tokenInput').value.trim(),tokens=text.match(/[\p{L}\p{N}_]+|[^\s]/gu)||[],box=root.querySelector('#tokenOutput');box.textContent='';tokens.forEach((token,index)=>{const span=document.createElement('span');span.className='token-pill';span.textContent=`${index}: ${token}`;box.appendChild(span);});root.querySelector('#tokenCount').textContent=tokens.length;}
  function botReply(text){const t=text.toLowerCase();if(/python/.test(t))return 'Python é uma linguagem interpretada muito usada em automação, dados, web e IA. Neste laboratório, o chatbot escolheu esta resposta por uma regra de palavras-chave.';if(/rede neural|neurônio/.test(t))return 'Uma rede neural combina entradas, pesos, ativações e camadas. O treinamento ajusta pesos para reduzir o erro.';if(/chatgpt|modelo|llm/.test(t))return 'Modelos de linguagem estimam próximos tokens usando parâmetros aprendidos em grandes conjuntos de dados. Esta simulação não é um LLM real.';if(/segurança|privacidade/.test(t))return 'Não envie dados pessoais. Sistemas de IA precisam de controle de acesso, avaliação de risco, proteção de dados e revisão humana.';return 'Posso explicar Python, redes neurais, modelos de linguagem, tokens e segurança. Esta resposta veio de regras locais, não de uma IA externa.';}
  function sendChat(){const input=root.querySelector('#chatInput'),text=input.value.trim();if(!text)return;state.chat.push({role:'user',text,at:Date.now()});state.chat.push({role:'bot',text:botReply(text),at:Date.now()});input.value='';renderChat();state.xp+=5;root.querySelector('#aiXp').textContent=state.xp;save();}
  function renderChat(){const box=root.querySelector('#chatMessages');if(!box)return;box.textContent='';for(const msg of state.chat.slice(-20)){const article=document.createElement('article');article.className=`chat-bubble ${msg.role}`;article.textContent=msg.text;box.appendChild(article);}box.scrollTop=box.scrollHeight;}
  function render(){root.innerHTML=`<div class="immersive-lab ai-lab"><header class="immersive-hero"><div><span class="eyebrow">INTELIGÊNCIA ARTIFICIAL • SIMULAÇÃO</span><h2>Veja o que acontece por trás de um modelo</h2><p>Explore neurônios, pesos, treinamento, classificação, tokens, contexto e um chatbot local baseado em regras.</p></div><div class="immersive-badges"><span>XP <b id="aiXp">${state.xp}</b></span><span>Épocas <b id="aiEpochs">${state.epochs}</b></span><span>Acurácia <b id="aiAccuracy">${(state.accuracy*100).toFixed(1)}%</b></span></div></header><nav class="module-tabs"><button data-ai-tab="network">Rede neural</button><button data-ai-tab="classifier">Classificador</button><button data-ai-tab="tokens">Tokens</button><button data-ai-tab="chatbot">Chatbot</button></nav>
    <section data-ai-panel="network" class="immersive-grid"><article class="immersive-card"><h3>Treinamento simplificado</h3><p>O modelo recebe exemplos, calcula um erro e ajusta pesos. Aqui os valores são simulados para visualizar a dinâmica.</p><button id="trainAi" class="btn primary">Treinar 20 épocas</button><div class="large-progress"><i id="trainingProgress"></i></div><pre id="trainingLog" class="terminal-mini">modelo inicializado\naguardando treinamento…</pre><div class="knowledge-card"><strong>Não é o ChatGPT real:</strong> modelos modernos possuem muitas camadas, bilhões de parâmetros, dados, infraestrutura e técnicas de alinhamento.</div></article><article class="immersive-card"><div class="visual-stage"><canvas id="aiNetworkCanvas" aria-label="Rede neural animada"></canvas></div></article></section>
    <section data-ai-panel="classifier" class="immersive-grid hidden"><article class="immersive-card"><h3>Defina as características</h3><label>Horas de estudo<input id="featureHours" type="range" min="0" max="20" value="8"></label><label>Tarefas concluídas<input id="featureTasks" type="range" min="0" max="20" value="12"></label><label>Erros críticos<input id="featureErrors" type="range" min="0" max="10" value="2"></label><button id="classifyBtn" class="btn primary">Classificar</button><div id="classifyOutput" class="practice-feedback"></div></article><article class="immersive-card"><h3>Pipeline</h3><div class="flow-track"><div class="flow-node">Dados</div><span class="flow-arrow">›</span><div class="flow-node">Limpeza</div><span class="flow-arrow">›</span><div class="flow-node">Características</div><span class="flow-arrow">›</span><div class="flow-node">Modelo</div><span class="flow-arrow">›</span><div class="flow-node">Probabilidade</div></div><div class="knowledge-card"><strong>Responsabilidade:</strong> um resultado automatizado precisa ser avaliado quanto a qualidade, viés, explicabilidade e impacto sobre pessoas.</div></article></section>
    <section data-ai-panel="tokens" class="immersive-grid hidden"><article class="immersive-card"><h3>Tokenização didática</h3><textarea id="tokenInput" rows="6">Programar é transformar ideias em instruções.</textarea><button id="tokenizeBtn" class="btn primary">Separar tokens</button><p>Quantidade: <b id="tokenCount">0</b></p></article><article class="immersive-card"><h3>Sequência de tokens</h3><div id="tokenOutput" class="token-output"></div><div class="knowledge-card"><strong>Em modelos reais:</strong> tokens não são necessariamente palavras inteiras. O vocabulário e o algoritmo variam conforme o modelo.</div></article></section>
    <section data-ai-panel="chatbot" class="immersive-grid hidden"><article class="immersive-card"><h3>Chatbot local por regras</h3><div id="chatMessages" class="chat-messages"></div><div class="chat-compose"><input id="chatInput" maxlength="240" placeholder="Pergunte sobre Python, redes neurais ou ChatGPT"><button id="sendChat" class="btn primary">Enviar</button></div></article><article class="immersive-card"><h3>Lógica usada</h3><pre class="terminal-mini">se contém "python" → resposta Python\nse contém "rede neural" → resposta de redes\nse contém "chatgpt" ou "modelo" → resposta LLM\nsenão → ajuda geral</pre><p class="muted-copy">A interface parece um chat, mas a lógica é determinística e local. Isso ajuda a diferenciar chatbot por regras de modelo generativo.</p></article></section></div>`;
    root.querySelectorAll('[data-ai-tab]').forEach(b=>b.addEventListener('click',()=>setTab(b.dataset.aiTab)));root.querySelector('#trainAi').addEventListener('click',train);root.querySelector('#classifyBtn').addEventListener('click',classify);root.querySelector('#tokenizeBtn').addEventListener('click',tokenize);root.querySelector('#sendChat').addEventListener('click',sendChat);root.querySelector('#chatInput').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();sendChat();}});renderChat();setTab(state.tab);
  }
  async function mount(host,context){root=host;ctx=context;state={...DEFAULT,...await ctx.storage.get(KEY,DEFAULT)};render();}
  async function unmount(){training=false;trainingGeneration++;cancelAnimationFrame(raf);if(state&&ctx)await save();root=null;ctx=null;state=null;}
  function exportPayload(){return{text:`IA E REDES NEURAIS\nÉpocas: ${state.epochs}\nAcurácia simulada: ${(state.accuracy*100).toFixed(1)}%\nXP: ${state.xp}`,native:JSON.stringify(state,null,2),backup:state,meta:[{label:'Épocas',value:String(state.epochs)},{label:'XP',value:String(state.xp)}]};}
  function help(){return'<h3>IA e redes neurais</h3><p>O treinamento, o classificador e o chatbot são modelos educacionais simplificados. Nenhuma API de IA externa é chamada.</p>';}
  window.LABDS_LABS['ai-lab']={mount,unmount,exportPayload,help};
})();
