import { ImmersiveInputController } from '../../core/input/ImmersiveInputController.js';
import { DeepSpaceNavigationModel } from '../../core/deep-space/DeepSpaceNavigationModel.js';
import { DeepSpaceSceneRenderer } from '../../rendering/DeepSpaceSceneRenderer.js';
import { COSMIC_DESTINATIONS,DEEP_SPACE_CAMERAS,COSMIC_TOUR,DESTINATION_BY_ID } from '../../data/deepSpaceSystems.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cameraLabel=id=>DEEP_SPACE_CAMERAS.find(item=>item.id===id)?.label||id;
class DeepSpaceRemasterModule{
  constructor(){this.container=null;this.context=null;this.navigation=new DeepSpaceNavigationModel();this.renderer=null;this.input=null;this.raf=0;this.last=0;this.fps=0;this.panel=null;this.help=false;this.photo=false;this.settingsUnsub=null;this.onClick=e=>this.handleClick(e);this.onKeyDown=e=>this.handleKeyDown(e);}
  mount(container,context){this.container=container;this.context=context;container.addEventListener('click',this.onClick);addEventListener('keydown',this.onKeyDown);this.restore();this.render();this.startRuntime();this.settingsUnsub=context.bus.on('settings:changed',()=>this.restart());}
  unmount(){cancelAnimationFrame(this.raf);this.renderer?.destroy();this.input?.detach();this.settingsUnsub?.();this.container?.removeEventListener('click',this.onClick);removeEventListener('keydown',this.onKeyDown);}
  restore(){const completed=this.context.profileStore.active().completedExperiences;for(const item of COSMIC_TOUR)if(completed.includes(item.id))this.navigation.scanned.add(item.destination);}
  render(){const profile=this.context.settingsStore.getProfile(),current=DESTINATION_BY_ID[this.navigation.destinationId];this.container.innerHTML=`<section class="deep-space-module quality-${profile.id}"><div class="deep-space-stage ${this.photo?'photo-mode':''}" id="deep-space-stage">
    <canvas id="deep-space-canvas" aria-label="Universo profundo procedural 3D e 360 graus"></canvas><div class="deep-space-vignette"></div><div class="deep-space-grain"></div><div class="deep-space-warp" id="deep-space-warp"></div>
    <header class="deep-space-top immersive-hud"><button class="hud-icon" data-action="back" aria-label="Voltar">←</button><div class="target-chip"><span id="deep-space-symbol">${current.symbol}</span><div><b id="deep-space-name">${esc(current.name)}</b><small id="deep-space-scale">${esc(current.scale)}</small></div></div><div class="deep-space-top-actions"><span class="hud-status" id="deep-space-camera">${cameraLabel(this.navigation.cameraMode)}</span><span class="hud-status"><b id="deep-space-fps">--</b> FPS</span><button class="hud-icon" data-action="toggle-help">?</button><button class="hud-icon" data-action="fullscreen">⛶</button></div></header>
    <div class="deep-space-objective immersive-hud"><span>VIAGEM CÓSMICA</span><b id="deep-space-objective">Escaneie destinos e atravesse diferentes escalas do Universo.</b></div>
    <aside class="deep-space-telemetry immersive-hud"><div><span>ENERGIA</span><b id="deep-space-energy">100%</b></div><div><span>VELOCIDADE</span><b id="deep-space-speed">0,0</b></div><div><span>VISITADOS</span><b id="deep-space-visited">1/8</b></div><div><span>SCANS</span><b id="deep-space-scans">0/7</b></div></aside>
    <div class="deep-space-crosshair"><i></i><i></i></div>
    <nav class="deep-space-camera-rail immersive-hud">${DEEP_SPACE_CAMERAS.map(item=>`<button class="${item.id===this.navigation.cameraMode?'active':''}" data-action="set-camera" data-camera="${item.id}"><i>${item.short}</i><span>${esc(item.label)}</span></button>`).join('')}</nav>
    <div class="deep-space-actions immersive-hud"><button data-action="scan">ESCANEAR</button><button data-action="toggle-tour">ROTA</button><button data-action="toggle-info">INFO</button><button data-action="toggle-autopilot">AUTO</button><button data-action="toggle-photo">FOTO</button></div>
    <nav class="deep-space-dock immersive-hud">${COSMIC_DESTINATIONS.map(item=>`<button class="${item.id===current.id?'active':''}" style="--cosmic-color:${item.color}" data-action="select-destination" data-destination="${item.id}"><i>${item.symbol}</i><span><b>${esc(item.name)}</b><small>${esc(item.scale)}</small></span></button>`).join('')}</nav>
    <aside class="deep-space-info-drawer immersive-hud" id="deep-space-info"><button class="drawer-close" data-action="toggle-info">×</button><span class="eyebrow">DESTINO ATUAL</span><div id="deep-space-info-content">${this.infoMarkup(current)}</div></aside>
    <aside class="deep-space-tour-drawer immersive-hud" id="deep-space-tour"><button class="drawer-close" data-action="toggle-tour">×</button><span class="eyebrow">ROTA CÓSMICA</span><h3>Viagem entre escalas</h3><div class="deep-space-tour-list">${COSMIC_TOUR.map(item=>`<button data-action="select-destination" data-destination="${item.destination}"><i>${this.navigation.scanned.has(item.destination)?'✓':'○'}</i><span><b>${esc(item.label)}</b><small>+${item.xp} XP</small></span></button>`).join('')}</div></aside>
    <aside class="deep-space-help immersive-hud" id="deep-space-help"><button class="drawer-close" data-action="toggle-help">×</button><span class="eyebrow">CONTROLES</span><h3>Explore como em um jogo</h3><div class="control-grid"><span><kbd>WASD</kbd> mover</span><span><kbd>Mouse</kbd> olhar</span><span><kbd>Q / E</kbd> descer / subir</span><span><kbd>Shift</kbd> dobra rápida</span><span><kbd>C</kbd> câmera</span><span><kbd>T</kbd> próximo destino</span><span><kbd>I</kbd> escanear</span><span><kbd>P</kbd> foto</span></div><p>Joysticks virtuais e gamepad são reconhecidos automaticamente.</p></aside>
    <div class="virtual-joysticks deep-space-joysticks"><div class="virtual-joystick left" data-stick="left"><div class="joystick-ring"></div><div class="joystick-knob"></div><span>MOVER</span></div><div class="virtual-joystick right" data-stick="right"><div class="joystick-ring"></div><div class="joystick-knob"></div><span>OLHAR</span></div></div>
    <div class="deep-space-mobile-actions immersive-hud"><button data-action="mobile-up">▲</button><button data-action="cycle-camera">C</button><button data-action="scan">SCAN</button><button data-action="mobile-down">▼</button></div>
    <div class="deep-space-loading" id="deep-space-loading"><i></i><span>Calculando rota interestelar…</span></div>
  </div></section>`;}
  startRuntime(){const canvas=this.container.querySelector('#deep-space-canvas');this.input=new ImmersiveInputController({canvas,root:this.container,leftStick:this.container.querySelector('[data-stick="left"]'),rightStick:this.container.querySelector('[data-stick="right"]')});this.input.attach();this.renderer=new DeepSpaceSceneRenderer(canvas,this.context.settingsStore,{onDiagnostics:d=>{if(d.state==='context-lost')this.context.toast('Contexto gráfico perdido. A sessão foi preservada.');}});this.renderer.start();this.last=performance.now();const tick=now=>{const dt=Math.min(.05,(now-this.last)/1000||.016);this.last=now;this.navigation.update(dt,this.input.sample());this.renderer.setState(DESTINATION_BY_ID[this.navigation.destinationId],this.navigation.snapshot());this.fps=Math.round(1/Math.max(.001,dt));this.updateHud();this.raf=requestAnimationFrame(tick);};this.raf=requestAnimationFrame(tick);setTimeout(()=>this.container.querySelector('#deep-space-loading')?.classList.add('hidden'),520);}
  restart(){if(!this.container?.isConnected)return;cancelAnimationFrame(this.raf);this.renderer?.destroy();this.input?.detach();this.startRuntime();this.context.toast(`Renderização atualizada para ${this.context.settingsStore.getProfile().label}.`);}
  handleClick(event){const target=event.target.closest('[data-action]');if(!target)return;const action=target.dataset.action;if(action==='back')return this.context.onBack();if(action==='select-destination')return this.selectDestination(target.dataset.destination);if(action==='set-camera')return this.setCamera(target.dataset.camera);if(action==='cycle-camera')return this.setCamera(this.navigation.cycleCamera());if(action==='scan')return this.scan();if(action==='toggle-info')return this.togglePanel('info');if(action==='toggle-tour')return this.togglePanel('tour');if(action==='toggle-help'){this.help=!this.help;this.updatePanels();return;}if(action==='toggle-autopilot'){this.navigation.toggleAutopilot();this.context.toast(`Piloto automático ${this.navigation.autopilot?'ativado':'desativado'}.`);return;}if(action==='toggle-photo'){this.photo=this.navigation.togglePhotoMode();this.container.querySelector('#deep-space-stage')?.classList.toggle('photo-mode',this.photo);return;}if(action==='fullscreen')return this.container.querySelector('#deep-space-stage')?.requestFullscreen?.();if(action==='mobile-up'){this.navigation.position.y+=1;return;}if(action==='mobile-down'){this.navigation.position.y-=1;return;}}
  handleKeyDown(event){if(['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName))return;const key=event.key.toLowerCase();if(key==='c')this.setCamera(this.navigation.cycleCamera());if(key==='t')this.cycleDestination();if(key==='i')this.scan();if(key==='p'){this.photo=this.navigation.togglePhotoMode();this.container.querySelector('#deep-space-stage')?.classList.toggle('photo-mode',this.photo);}if(key==='r')this.navigation.reset();}
  selectDestination(id){if(!DESTINATION_BY_ID[id])return;this.navigation.selectDestination(id);this.panel=null;this.updatePanels();this.updateDestinationUi();}
  cycleDestination(){const index=COSMIC_DESTINATIONS.findIndex(item=>item.id===this.navigation.destinationId);this.selectDestination(COSMIC_DESTINATIONS[(index+1)%COSMIC_DESTINATIONS.length].id);}
  setCamera(id){if(!this.navigation.setCameraMode(id))return;this.container.querySelectorAll('.deep-space-camera-rail button').forEach(btn=>btn.classList.toggle('active',btn.dataset.camera===id));const el=this.container.querySelector('#deep-space-camera');if(el)el.textContent=cameraLabel(id);}
  scan(){const result=this.navigation.scan(),task=COSMIC_TOUR.find(item=>item.destination===result.destinationId);if(task){const awarded=this.context.profileStore.addXp(task.xp,task.id);if(awarded)this.context.toast(`${task.label}: +${task.xp} XP.`);}else{const awarded=this.context.profileStore.addXp(100,`deep-space-scan-${result.destinationId}`);if(awarded)this.context.toast('Destino catalogado: +100 XP.');}if(this.navigation.scanned.size>=7){const awarded=this.context.profileStore.addXp(500,'deep-space-certification');if(awarded)this.context.toast('Certificação Navegador do Universo Profundo: +500 XP.');}this.updateTour();this.updateHud();}
  togglePanel(name){this.panel=this.panel===name?null:name;this.updatePanels();}
  updatePanels(){this.container.querySelector('#deep-space-info')?.classList.toggle('open',this.panel==='info');this.container.querySelector('#deep-space-tour')?.classList.toggle('open',this.panel==='tour');this.container.querySelector('#deep-space-help')?.classList.toggle('open',this.help);}
  updateDestinationUi(){const item=DESTINATION_BY_ID[this.navigation.destinationId];const set=(s,v)=>{const el=this.container.querySelector(s);if(el)el.textContent=v;};set('#deep-space-symbol',item.symbol);set('#deep-space-name',item.name);set('#deep-space-scale',item.scale);this.container.querySelectorAll('.deep-space-dock button').forEach(btn=>btn.classList.toggle('active',btn.dataset.destination===item.id));const content=this.container.querySelector('#deep-space-info-content');if(content)content.innerHTML=this.infoMarkup(item);}
  updateTour(){const drawer=this.container.querySelector('#deep-space-tour');if(!drawer)return;const list=drawer.querySelector('.deep-space-tour-list');if(list)list.innerHTML=COSMIC_TOUR.map(item=>`<button data-action="select-destination" data-destination="${item.destination}"><i>${this.navigation.scanned.has(item.destination)?'✓':'○'}</i><span><b>${esc(item.label)}</b><small>+${item.xp} XP</small></span></button>`).join('');}
  updateHud(){const s=this.navigation.snapshot(),speed=Math.hypot(s.velocity.x,s.velocity.y,s.velocity.z);const set=(sel,val)=>{const el=this.container.querySelector(sel);if(el)el.textContent=val;};set('#deep-space-energy',`${Math.round(s.energy)}%`);set('#deep-space-speed',`${speed.toFixed(1)} u/s`);set('#deep-space-visited',`${s.visited.length}/8`);set('#deep-space-scans',`${s.scanned.length}/7`);set('#deep-space-fps',String(this.fps));set('#deep-space-camera',cameraLabel(s.cameraMode));const warp=this.container.querySelector('#deep-space-warp');warp?.classList.toggle('active',s.warp.active);set('#deep-space-objective',s.scanned.length>=7?'Rota principal concluída. Explore livremente ou use o modo foto.':`Escaneie os destinos da rota cósmica · ${s.scanned.length}/7 concluídos.`);}
  infoMarkup(item){return `<div class="deep-space-info-symbol" style="--cosmic-color:${item.color}">${item.symbol}</div><h2>${esc(item.name)}</h2><p>${esc(item.description)}</p><div class="deep-space-info-metrics"><span><b>ESCALA</b>${esc(item.scale)}</span><span><b>CLASSE VISUAL</b>${esc(item.type)}</span></div>`;}
}
export const createModule=()=>new DeepSpaceRemasterModule();
