#!/usr/bin/env node
'use strict';
const fs=require('node:fs'),path=require('node:path');const root=path.resolve(__dirname,'..'),gameRoot=path.join(root,'games','chess-arena-360');const {ChessEngine,squareIndex,squareName}=require(path.join(gameRoot,'engine.js'));const {chooseMove}=require(path.join(gameRoot,'ai.js'));const checks=[];function check(name,passed,detail=''){checks.push({name,passed:!!passed,detail});if(!passed)console.error('FAIL',name,detail)}
function perft(e,d){if(d===0)return 1;let n=0;for(const m of e.legalMoves()){const c=e.clone();c.play(m);n+=perft(c,d-1)}return n}
// Standard move generation.
let e=new ChessEngine();check('Posição inicial tem 20 jogadas legais',e.legalMoves().length===20,`${e.legalMoves().length}`);check('Perft depth 1 = 20',perft(e,1)===20,`${perft(e,1)}`);check('Perft depth 2 = 400',perft(e,2)===400,`${perft(e,2)}`);const p3=perft(e,3);check('Perft depth 3 = 8902',p3===8902,`${p3}`);check('FEN inicial preservado',e.toFEN().startsWith('rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq -'),'FEN');
for(const sq of ['a1','h1','a8','h8','e4','d5'])check(`Conversão de casa ${sq}`,squareName(squareIndex(sq))===sq,`${squareIndex(sq)}`);
// Fool's mate.
e=new ChessEngine();for(const u of ['f2f3','e7e5','g2g4','d8h4'])check(`Lance ${u} é legal`,e.playUci(u).ok,u);let out=e.outcome();check('Mate do louco detecta xeque-mate',out.status==='checkmate'&&out.winner==='b'&&out.check,JSON.stringify(out));
// Illegal move in check filtering.
e=new ChessEngine('4k3/8/8/8/8/8/4r3/4K3 w - - 0 1');check('Rei em xeque reconhecido',e.inCheck('w'),'torre em e2');check('Jogadas legais removem permanência em xeque',e.legalMoves().every(m=>{const c=e.clone();c.play(m);return !c.inCheck('w')}),`${e.legalMoves().length} jogadas`);
// Castling.
e=new ChessEngine('r3k2r/8/8/8/8/8/8/R3K2R w KQkq - 0 1');let km=e.legalMovesFrom(squareIndex('e1'));check('Roque curto branco disponível',km.some(m=>m.castle==='K'&&m.to===squareIndex('g1')),'e1-g1');check('Roque longo branco disponível',km.some(m=>m.castle==='Q'&&m.to===squareIndex('c1')),'e1-c1');check('Roque curto move torre',(()=>{const c=e.clone();const m=c.legalMoves().find(x=>x.castle==='K');c.play(m);return c.board[squareIndex('g1')]==='K'&&c.board[squareIndex('f1')]==='R'&&!c.castling.includes('K')&&!c.castling.includes('Q')})(),'K g1 / R f1');
e=new ChessEngine('r3k2r/8/8/8/8/5r2/8/R3K2R w KQkq - 0 1');check('Roque através de casa atacada é proibido',!e.legalMovesFrom(squareIndex('e1')).some(m=>m.castle==='K'),'f1 atacada');
// En passant.
e=new ChessEngine('8/8/8/3pP3/8/8/8/K6k w - d6 0 1');let ep=e.legalMovesFrom(squareIndex('e5')).find(m=>m.enPassant);check('En passant é gerado',!!ep,ep?`${squareName(ep.from)}-${squareName(ep.to)}`:'ausente');e.play(ep);check('En passant remove peão capturado',e.board[squareIndex('d6')]==='P'&&e.board[squareIndex('d5')]===null,'peão branco em d6');
// Promotion.
e=new ChessEngine('7k/P7/8/8/8/8/8/K7 w - - 0 1');let promos=e.legalMovesFrom(squareIndex('a7')).filter(m=>m.to===squareIndex('a8'));check('Promoção oferece quatro peças',new Set(promos.map(m=>m.promotion)).size===4,promos.map(m=>m.promotion).join(','));e.play(promos.find(m=>m.promotion==='n'));check('Subpromoção para cavalo funciona',e.board[squareIndex('a8')]==='N','N em a8');
// Stalemate / insufficient / 50 move.
e=new ChessEngine('7k/5Q2/6K1/8/8/8/8/8 b - - 0 1');check('Afogamento detectado',e.outcome().status==='stalemate',JSON.stringify(e.outcome()));e=new ChessEngine('8/8/8/8/8/8/6k1/4K3 w - - 0 1');check('Material insuficiente: reis',e.outcome().status==='draw-insufficient',JSON.stringify(e.outcome()));e=new ChessEngine('8/8/8/8/8/8/6k1/3BK3 w - - 0 1');check('Material insuficiente: rei e bispo',e.outcome().status==='draw-insufficient',JSON.stringify(e.outcome()));e=new ChessEngine('8/8/8/8/8/8/6k1/R3K3 w - - 100 60');check('Regra dos 50 lances',e.outcome().status==='draw-50',JSON.stringify(e.outcome()));
// Threefold via knights with kings+pawns to avoid insufficient material.
e=new ChessEngine();for(const u of ['g1f3','g8f6','f3g1','f6g8','g1f3','g8f6','f3g1','f6g8']){const r=e.playUci(u);check(`Repetição lance ${u}`,r.ok,u)}check('Repetição tripla detectada',e.outcome().status==='draw-threefold',JSON.stringify(e.outcome()));
// Castling rights when rook moves/captured.
e=new ChessEngine('r3k2r/8/8/8/8/8/8/R3K2R w KQkq - 0 1');e.playUci('h1h2');check('Mover torre remove direito de roque correspondente',!e.castling.includes('K')&&e.castling.includes('Q'),e.castling);
// Snapshot restore.
e=new ChessEngine();e.playUci('e2e4');e.playUci('c7c5');const snap=e.snapshot(),r=new ChessEngine();check('Snapshot schema 1 restaura',r.restore(snap),snap.fen);check('Snapshot restaura FEN',r.toFEN()===e.toFEN(),r.toFEN());check('Snapshot restaura histórico de repetição',r.positionHistory.length===e.positionHistory.length,`${r.positionHistory.length}`);
// CPU levels return legal move.
for(const level of ['iniciante','normal','estrategica','mestre']){const c=new ChessEngine();c.playUci('e2e4');const legal=c.legalMoves().map(m=>`${m.from}-${m.to}-${m.promotion||''}`),m=chooseMove(c,level,.42),key=m?`${m.from}-${m.to}-${m.promotion||''}`:'';check(`CPU ${level} retorna lance legal`,!!m&&legal.includes(key),key)}
// CPU can find a mate in one at master.
e=new ChessEngine('7k/6Q1/6K1/8/8/8/8/8 w - - 0 1');let master=chooseMove(e,'mestre',.5);const mate=e.clone();if(master)mate.play(master);check('CPU Mestre prioriza mate imediato',!!master&&mate.outcome().status==='checkmate',master?`${squareName(master.from)}-${squareName(master.to)}`:'sem lance');
// Integration files.
const app=fs.readFileSync(path.join(root,'app.js'),'utf8'),sw=fs.readFileSync(path.join(root,'sw.js'),'utf8'),profiles=JSON.parse(fs.readFileSync(path.join(root,'game-profiles.json'),'utf8')),learning=JSON.parse(fs.readFileSync(path.join(root,'education','game-learning.json'),'utf8')),version=JSON.parse(fs.readFileSync(path.join(root,'version.json'),'utf8'));
for(const file of ['index.html','style.css','engine.js','ai.js','game.js'])check(`Arquivo do jogo: ${file}`,fs.existsSync(path.join(gameRoot,file)),file);for(const file of ['logo.svg','preview-01.svg','preview-02.svg'])check(`Mídia: ${file}`,fs.existsSync(path.join(root,'media','games','chess-arena-360',file)),file);for(const token of ['chess-arena-360','games/chess-arena-360/runtime','fliperama-ds-chess-arena-360'])check(`Integração app: ${token}`,app.includes(token),'app.js');check('Perfil externo registrado',!!profiles['chess-arena-360'],'game-profiles.json');check('Ficha educacional registrada',!!learning['chess-arena-360'],'education/game-learning.json');check('Versão pública v0.39.0',String(version.version).startsWith('0.39.0')&&(app.includes("version: '0.39.0'") || app.includes("version: '0.39.0-hotfix1'")),'version/app');check('Service Worker v0.39.0',(sw.includes("const VERSION = '0.39.0'") || sw.includes("const VERSION = '0.39.0-hotfix1'")),'sw.js');check('Service Worker inclui Chess Arena',sw.includes('./games/chess-arena-360/engine.js')&&sw.includes('./games/chess-arena-360/ai.js'),'offline');check('Three.js local reutilizado',fs.readFileSync(path.join(gameRoot,'game.js'),'utf8').includes("../voxelcraft-ds/vendor/three/three.module.min.js"),'sem CDN');check('Interface expõe visão superior',fs.readFileSync(path.join(gameRoot,'index.html'),'utf8').includes('Visão superior'),'index.html');check('Interface expõe quatro CPUs',fs.readFileSync(path.join(gameRoot,'index.html'),'utf8').match(/CPU ·/g)?.length===4,'4 níveis');
const passed=checks.filter(x=>x.passed).length,failed=checks.length-passed,result={product:'Fliperama DS',version:'0.39.0',phase:'Fase 7.28',game:'Chess Arena 360',generatedAt:new Date().toISOString(),summary:{checks:checks.length,passed,failed},items:checks};fs.writeFileSync(path.join(__dirname,'chess-arena-360-results-v0.39.0.json'),JSON.stringify(result,null,2)+'\n');fs.writeFileSync(path.join(root,'TESTES-CHESS-ARENA-360-v0.39.0.md'),['# Testes — Chess Arena 360 v0.39.0','',`- Verificações: **${checks.length}**`,`- Aprovadas: **${passed}**`,`- Falhas: **${failed}**`,'',...checks.map(x=>`- ${x.passed?'✅':'❌'} **${x.name}** — ${x.detail}`),''].join('\n'));console.log(JSON.stringify(result.summary,null,2));if(failed)process.exitCode=1;
