import fs from 'node:fs';import path from 'node:path';import {Mundo360Simulation} from '../games/mundo-plataforma-ds-360/simulation.mjs';
const root=path.resolve(path.dirname(new URL(import.meta.url).pathname),'..');const read=p=>JSON.parse(fs.readFileSync(path.join(root,p),'utf8'));const vale=read('games/mundo-plataforma-ds-360/region.json').region,village=read('games/mundo-plataforma-ds-360/village.json').region,forest=read('games/mundo-plataforma-ds-360/forest.json').region;const items=[];const ok=(name,passed,detail='')=>items.push({name,passed:!!passed,detail});
ok('3 regiões declaradas',[vale,village,forest].length===3);ok('Floresta identificada',forest.kind==='forest');ok('Floresta 92x88',forest.size[0]===92&&forest.size[2]===88);ok('3 nós de energia',forest.interactables.filter(x=>x.type==='energy-node').length===3);ok('3 rotas ramificadas',Object.keys(forest.routes||{}).length===3);ok('plataforma vertical existe',forest.movingPlatforms.some(x=>x.axis==='y'));ok('clima leve declarado',forest.weather?.type==='energy-drift');ok('4 checkpoints',forest.checkpoints.length===4);ok('5 patrulhas',forest.enemies.length===5);ok('5 perigos',forest.hazards.length===5);
const ids=[...forest.platforms,...forest.movingPlatforms,...forest.obstacles,...forest.hazards,...forest.checkpoints,...forest.enemies,...forest.interactables].map(x=>x.id);ok('IDs únicos',new Set(ids).size===ids.length,`${ids.length} IDs`);

const insideRegion=(pos,r=forest)=>Math.abs(pos[0])<=r.size[0]/2&&Math.abs(pos[2])<=r.size[2]/2;
const overlaps=(pos,box,pad=.42)=>Math.abs(pos[0]-box.position[0])<=box.size[0]/2+pad&&Math.abs(pos[2]-box.position[2])<=box.size[2]/2+pad;
const topOf=p=>p.position[1]+p.size[1]/2;
const supportedBy=(pos,r=forest)=>[...(r.platforms||[]),...(r.movingPlatforms||[])].some(p=>Math.abs(pos[0]-p.position[0])<=p.size[0]/2+.5&&Math.abs(pos[2]-p.position[2])<=p.size[2]/2+.5&&pos[1]>=topOf(p)&&pos[1]-topOf(p)<=1.7);
ok('Vale preserva 6 Orbes',vale.collectibles.length===6);ok('Vale preserva 3 Balizas',vale.beacons.length===3);ok('Vale preserva 3 checkpoints',vale.checkpoints.length===3);ok('Vila preserva 4 pacotes',village.collectibles.length===4);ok('Vila preserva 3 NPCs',village.npcs.length===3);ok('Vila preserva 8 interações',village.interactables.length===8);ok('Vila preserva 3 missões',village.missions.length===3);
for(const pform of forest.platforms){ok(`plataforma ${pform.id} dentro da região`,insideRegion(pform.position));ok(`plataforma ${pform.id} com volume positivo`,pform.size.every(n=>n>0));}
for(const pform of forest.movingPlatforms){ok(`móvel ${pform.id} dentro da região`,insideRegion(pform.position));ok(`móvel ${pform.id} eixo suportado`,['x','y','z'].includes(pform.axis));ok(`móvel ${pform.id} alcance positivo`,pform.range>0&&pform.speed>0);}
for(const o of forest.obstacles){ok(`obstáculo ${o.id} dentro da região`,insideRegion(o.position));}
for(const h of forest.hazards){ok(`perigo ${h.id} dentro da região`,insideRegion(h.position));ok(`perigo ${h.id} não cobre spawn`,!overlaps(forest.spawn,h,.65));}
for(const cp of forest.checkpoints){ok(`checkpoint ${cp.id} dentro da região`,insideRegion(cp.position));ok(`checkpoint ${cp.id} fora de perigo`,!forest.hazards.some(h=>overlaps(cp.position,h,.6)));ok(`checkpoint ${cp.id} fora de obstáculo`,!forest.obstacles.some(o=>overlaps(cp.position,o,.35)));}
for(const e of forest.enemies){ok(`patrulha ${e.id} dentro da região`,insideRegion(e.position));ok(`patrulha ${e.id} eixo válido`,['x','z'].includes(e.axis));}
for(const node of forest.interactables){ok(`nó ${node.id} dentro da região`,insideRegion(node.position));ok(`nó ${node.id} apoiado`,supportedBy(node.position));}
for(const [name,route] of Object.entries(forest.routes||{})){ok(`rota ${name} possui sequência`,route.length>=5);ok(`rota ${name} referencia plataformas existentes`,route.every(id=>[...forest.platforms,...forest.movingPlatforms].some(p=>p.id===id)));}
ok('spawn da Floresta seguro',!forest.hazards.some(h=>overlaps(forest.spawn,h,.65))&&!forest.obstacles.some(o=>overlaps(forest.spawn,o,.45)));ok('portal dentro da Floresta',insideRegion(forest.portal.position));ok('portal não nasce em obstáculo',!forest.obstacles.some(o=>overlaps(forest.portal.position,o,.4)));
const world={schemaVersion:3,regions:[vale,village,forest]},sim=new Mundo360Simulation(world);ok('save novo schema 3',sim.snapshot().schemaVersion===3);ok('campanha tem 3 regiões',sim.progress().totalRegions===3);
// Force Vale complete -> village
for(const c of vale.collectibles)sim.collected.add(c.id);for(const b of vale.beacons)sim.beacons.add(b.id);sim.player.pos={x:vale.portal.position[0],y:vale.portal.position[1],z:vale.portal.position[2]};sim.tick(0,{});ok('Vale leva à Vila',sim.regionIndex===1&&sim.valeCompleted);
// complete village chain deterministically
const pos=(list,id)=>list.find(x=>x.id===id).position;const go=(p,interact=false)=>{sim.player.pos={x:p[0],y:p[1],z:p[2]};sim.player.vel={x:0,y:0,z:0};sim.invulnerable=9;sim.tick(0,{interact});};
go(pos(village.npcs,'lia'),true);ok('Lia inicia missão 1',sim.quest.stage===1);for(const id of ['repair-a','repair-b','repair-c'])go(pos(village.interactables,id),true);ok('3 reparos levam ao retorno',sim.quest.stage===2&&sim.quest.activated.size===3);go(pos(village.npcs,'lia'),true);ok('Lia conclui missão 1',sim.quest.stage===3);go(pos(village.npcs,'ivo'),true);ok('Ivo inicia missão 2',sim.quest.stage===4);for(const c of village.collectibles)go(c.position,false);ok('4 pacotes coletados',sim.collected.size===4&&sim.quest.stage===5);go(pos(village.interactables,'data-terminal'),true);ok('upload conclui missão 2',sim.quest.uploaded&&sim.quest.stage===6);go(pos(village.npcs,'dara'),true);ok('Dara inicia missão 3',sim.quest.stage===7);for(const id of ['relay-west','relay-east','relay-north'])go(pos(village.interactables,id),true);ok('3 relés liberam núcleo',sim.quest.relays.size===3&&sim.quest.stage===8);go(pos(village.interactables,'network-core'),true);ok('núcleo libera portal da Vila',sim.quest.stage===9&&sim.portalOpen());go(village.portal.position,false);ok('Vila leva à Floresta',sim.regionIndex===2&&sim.villageCompleted&&!sim.completed);ok('Floresta começa 0/3',sim.quest.forestNodes.size===0&&!sim.portalOpen());
for(const node of forest.interactables){go(node.position,true);ok(`${node.name} restaura`,sim.quest.forestNodes.has(node.id));}
ok('3 nós abrem portal',sim.portalOpen()&&sim.progress().nodes===3);go(forest.portal.position,false);ok('Floresta conclui campanha atual',sim.completed===true);ok('vitória na região 3',sim.consumeEvents().some(e=>e.type==='victory'&&e.region===3));
// schema2 migration from completed v0.38.2
const legacy={schemaVersion:2,lives:2,score:4500,activeRegion:1,valeCompleted:true,regionProgress:{},quest:{stage:9,talked:[],activated:['repair-a','repair-b','repair-c'],relays:['relay-west','relay-east','relay-north'],uploaded:true},completed:true,player:{position:village.portal.position}},mig=new Mundo360Simulation(world);ok('migra schema2',mig.restore(legacy));ok('schema2 concluído entra na floresta',mig.regionIndex===2&&mig.villageCompleted&&!mig.completed);ok('save migrado vira schema3',mig.snapshot().schemaVersion===3);
// vertical platform transport
const vertical=new Mundo360Simulation({schemaVersion:3,regions:[forest]});const lift=vertical.moving.find(x=>x.axis==='y');vertical.player.pos={x:lift.position[0],y:lift.position[1]+lift.size[1]/2,z:lift.position[2]};vertical.player.vel={x:0,y:0,z:0};vertical.player.grounded=true;vertical.updateMoving(.25);const dy=lift.current[1]-lift.last[1];ok('plataforma vertical move em Y',Math.abs(dy)>0.01,`dy=${dy.toFixed(3)}`);
// source/integration markers
const simsrc=fs.readFileSync(path.join(root,'games/mundo-plataforma-ds-360/simulation.mjs'),'utf8'),render=fs.readFileSync(path.join(root,'games/mundo-plataforma-ds-360/render.mjs'),'utf8'),game=fs.readFileSync(path.join(root,'games/mundo-plataforma-ds-360/game.js'),'utf8');ok('simulação suporta eixo Y',simsrc.includes("m.axis==='y'?1"));ok('render possui floresta',render.includes('#forestGround')&&render.includes('#forestEntities'));ok('render possui clima',render.includes('#weather()')&&render.includes('weatherPoints'));ok('game carrega forest.json',game.includes("'./forest.json'"));ok('ready anuncia 3 regiões',game.includes('regions:3')&&game.includes('forest:true'));

const app=fs.readFileSync(path.join(root,'app.js'),'utf8'),sw=fs.readFileSync(path.join(root,'sw.js'),'utf8'),version=read('version.json'),profiles=read('game-profiles.json'),learning=read('education/game-learning.json');
ok('versão pública v0.38.3',version.version==='0.38.3'&&version.phase.includes('Fase 7.24'));
ok('Service Worker v0.38.3',sw.includes("const VERSION = '0.38.3'"));
ok('Floresta no cache offline',sw.includes("'./games/mundo-plataforma-ds-360/forest.json'"));
ok('wrapper reconhece 3 regiões',app.includes('#summary={region:1,regions:3')&&app.includes("regions:3,mode360:true,village:true,forest:true"));
ok('catálogo marca Fase 7.24',app.includes("phase:'Fase 7.24 · v0.38.3'")&&app.includes('"releasePhase": 7.24'));
ok('catálogo cita Floresta de Circuitos',app.includes("title:'Mundo Plataforma DS 360 · Floresta de Circuitos'"));
ok('perfil externo cita 3 regiões',profiles['mundo-plataforma-ds-360']?.options?.campanha?.includes('Regiões 1–3'));
ok('tutorial externo cita 3 nós',profiles['mundo-plataforma-ds-360']?.tutorialSteps?.some(x=>x.includes('3 Nós de Energia')));
ok('ficha educacional cita Floresta',learning['mundo-plataforma-ds-360']?.stageLabel?.includes('Floresta de Circuitos'));
ok('progressão educacional cita Copa',learning['mundo-plataforma-ds-360']?.progression?.some(x=>x.includes('Copa de Energia')));
ok('save educacional cita schema 3',learning['mundo-plataforma-ds-360']?.qualityNotes?.some(x=>x.includes('schema 3')));
ok('game HUD possui Nós',game.includes("orbsLabel').textContent='Nós'"));
ok('game trata evento forest-node',game.includes("ev.type==='forest-node'"));
ok('game vitória usa 3 regiões',game.includes("post('victory',{region:3,regions:3"));
for(const f of ['logo.svg','preview-01.svg','preview-02.svg']){const q=path.join(root,'media/games/mundo-plataforma-ds-360',f);ok(`mídia ${f}`,fs.existsSync(q));if(fs.existsSync(q)){const t=fs.readFileSync(q,'utf8');ok(`acessibilidade ${f}`,t.includes('role="img"')&&t.includes('aria-label=')&&t.length>500,`${t.length} bytes`);}}
const passed=items.filter(x=>x.passed).length,failed=items.length-passed,result={suite:'Mundo Plataforma DS 360 v0.38.3 · Floresta de Circuitos',checks:items.length,passed,failed,items};fs.writeFileSync(path.join(root,'validation/mundo-plataforma-360-results-v0.38.3.json'),JSON.stringify(result,null,2)+'\n');fs.writeFileSync(path.join(root,'TESTES-MUNDO-PLATAFORMA-360-v0.38.3.md'),`# Testes — Mundo Plataforma DS 360 v0.38.3 · Floresta de Circuitos\n\n- Verificações: **${items.length}**\n- Aprovadas: **${passed}**\n- Falhas: **${failed}**\n\n`+items.map(i=>`- ${i.passed?'✅':'❌'} ${i.name}${i.detail?` — ${i.detail}`:''}`).join('\n')+'\n');console.log(JSON.stringify({checks:items.length,passed,failed}));if(failed){for(const i of items.filter(x=>!x.passed))console.error('FAIL',i.name,i.detail);process.exit(1)}
