import fs from 'node:fs';import path from 'node:path';import {Mundo360Simulation} from '../games/mundo-plataforma-ds-360/simulation.mjs';
const root=path.resolve(path.dirname(new URL(import.meta.url).pathname),'..');const read=p=>JSON.parse(fs.readFileSync(path.join(root,p),'utf8'));const vale=read('games/mundo-plataforma-ds-360/region.json').region,village=read('games/mundo-plataforma-ds-360/village.json').region,forest=read('games/mundo-plataforma-ds-360/forest.json').region,industrial=read('games/mundo-plataforma-ds-360/industrial.json').region;const items=[];const ok=(name,passed,detail='')=>items.push({name,passed:!!passed,detail});
ok('4 regiões declaradas',[vale,village,forest,industrial].length===4);ok('Industrial identificada',industrial.kind==='industrial');ok('Industrial 96x84',industrial.size[0]===96&&industrial.size[2]===84);ok('3 painéis de energia',industrial.interactables.filter(x=>x.type==='industrial-power').length===3);ok('3 consoles de carga',industrial.interactables.filter(x=>x.type==='cargo-console').length===3);ok('1 console mestre',industrial.interactables.filter(x=>x.type==='control-console').length===1);ok('3 esteiras',industrial.conveyors.length===3);ok('4 plataformas móveis',industrial.movingPlatforms.length===4);ok('2 elevadores ou mais',industrial.movingPlatforms.filter(x=>x.axis==='y').length>=2);ok('4 checkpoints',industrial.checkpoints.length===4);ok('5 patrulhas',industrial.enemies.length===5);ok('5 perigos',industrial.hazards.length===5);
const ids=[...industrial.platforms,...industrial.movingPlatforms,...industrial.conveyors,...industrial.obstacles,...industrial.hazards,...industrial.checkpoints,...industrial.enemies,...industrial.interactables].map(x=>x.id);ok('IDs industriais únicos',new Set(ids).size===ids.length,`${ids.length} IDs`);
const inside=(pos,r=industrial)=>Math.abs(pos[0])<=r.size[0]/2&&Math.abs(pos[2])<=r.size[2]/2;const overlaps=(pos,box,pad=.42)=>Math.abs(pos[0]-box.position[0])<=box.size[0]/2+pad&&Math.abs(pos[2]-box.position[2])<=box.size[2]/2+pad;const top=p=>p.position[1]+p.size[1]/2;const supported=(pos,r=industrial)=>[...(r.platforms||[]),...(r.movingPlatforms||[])].some(p=>Math.abs(pos[0]-p.position[0])<=p.size[0]/2+.55&&Math.abs(pos[2]-p.position[2])<=p.size[2]/2+.55&&pos[1]>=top(p)&&pos[1]-top(p)<=1.8);
for(const p of industrial.platforms){ok(`plataforma ${p.id} dentro`,inside(p.position));ok(`plataforma ${p.id} positiva`,p.size.every(n=>n>0));}
for(const p of industrial.movingPlatforms){ok(`móvel ${p.id} dentro`,inside(p.position));ok(`móvel ${p.id} eixo válido`,['x','y','z'].includes(p.axis));ok(`móvel ${p.id} movimento válido`,p.range>0&&p.speed>0);}
for(const b of industrial.conveyors){ok(`esteira ${b.id} dentro`,inside(b.position));ok(`esteira ${b.id} direção normalizada`,Array.isArray(b.direction)&&b.direction.length===2&&Math.hypot(...b.direction)>0);ok(`esteira ${b.id} velocidade positiva`,b.speed>0);}
for(const cp of industrial.checkpoints){ok(`checkpoint ${cp.id} dentro`,inside(cp.position));ok(`checkpoint ${cp.id} fora de perigo`,!industrial.hazards.some(h=>overlaps(cp.position,h,.55)));ok(`checkpoint ${cp.id} fora de obstáculo`,!industrial.obstacles.some(o=>overlaps(cp.position,o,.35)));}
for(const i of industrial.interactables){ok(`interação ${i.id} dentro`,inside(i.position));ok(`interação ${i.id} apoiada`,supported(i.position));}
ok('spawn industrial seguro',!industrial.hazards.some(h=>overlaps(industrial.spawn,h,.65))&&!industrial.obstacles.some(o=>overlaps(industrial.spawn,o,.45)));ok('portal industrial dentro',inside(industrial.portal.position));ok('portal industrial fora de obstáculo',!industrial.obstacles.some(o=>overlaps(industrial.portal.position,o,.4)));
ok('Vale preserva 6 Orbes',vale.collectibles.length===6);ok('Vila preserva 3 missões',village.missions.length===3);ok('Floresta preserva 3 Nós',forest.interactables.filter(x=>x.type==='energy-node').length===3);
const world={schemaVersion:4,regions:[vale,village,forest,industrial]},sim=new Mundo360Simulation(world);ok('save novo schema 4',sim.snapshot().schemaVersion===4);ok('campanha tem 4 regiões',sim.progress().totalRegions===4);
const go=(p,interact=false)=>{sim.player.pos={x:p[0],y:p[1],z:p[2]};sim.player.vel={x:0,y:0,z:0};sim.invulnerable=9;sim.tick(0,{interact});};const find=(arr,id)=>arr.find(x=>x.id===id).position;
// advance previous regions without replaying every mission detail
for(const c of vale.collectibles)sim.collected.add(c.id);for(const b of vale.beacons)sim.beacons.add(b.id);go(vale.portal.position);ok('Vale → Vila',sim.regionIndex===1&&sim.valeCompleted);
sim.quest.stage=9;go(village.portal.position);ok('Vila → Floresta',sim.regionIndex===2&&sim.villageCompleted);
for(const n of forest.interactables.filter(x=>x.type==='energy-node'))sim.quest.forestNodes.add(n.id);go(forest.portal.position);ok('Floresta → Industrial',sim.regionIndex===3&&sim.forestCompleted&&!sim.completed);ok('Industrial inicia energia 0/3',sim.quest.industrialStage===0&&sim.quest.industrialPower.size===0);
for(const id of ['power-panel-west','power-panel-center','power-panel-east'])go(find(industrial.interactables,id),true);ok('3 painéis liberam logística',sim.quest.industrialPower.size===3&&sim.quest.industrialStage===1);
for(const id of ['cargo-console-a','cargo-console-b','cargo-console-c'])go(find(industrial.interactables,id),true);ok('3 cargas liberam controle',sim.quest.cargoRoutes.size===3&&sim.quest.industrialStage===2);
go(find(industrial.interactables,'control-console'),true);ok('console mestre sincroniza',sim.quest.controlSynced&&sim.quest.industrialStage===3&&sim.portalOpen());
go(industrial.portal.position);ok('Industrial conclui campanha',sim.completed===true);ok('vitória na região 4',sim.consumeEvents().some(e=>e.type==='victory'&&e.region===4&&e.totalRegions===4));
// schema 3 migration from completed v0.38.3
const legacy={schemaVersion:3,lives:2,score:9300,activeRegion:2,valeCompleted:true,villageCompleted:true,regionProgress:{},quest:{stage:9,talked:[],activated:['repair-a','repair-b','repair-c'],relays:['relay-west','relay-east','relay-north'],uploaded:true,forestNodes:['energy-node-west','energy-node-east','energy-node-canopy']},completed:true,player:{position:forest.portal.position}},mig=new Mundo360Simulation(world);ok('migra schema3',mig.restore(legacy));ok('schema3 concluído entra na Industrial',mig.regionIndex===3&&mig.forestCompleted&&!mig.completed);ok('save migrado vira schema4',mig.snapshot().schemaVersion===4);ok('pontuação preservada na migração',mig.score===9300);ok('vidas preservadas na migração',mig.lives===2);
// current save restore
const cur=new Mundo360Simulation(world);cur.forestCompleted=true;cur.quest.industrialStage=2;cur.quest.industrialPower=new Set(['power-panel-west','power-panel-center','power-panel-east']);cur.quest.cargoRoutes=new Set(['cargo-console-a','cargo-console-b','cargo-console-c']);cur.regionIndex=3;cur.region=industrial;const snap=cur.snapshot(),restored=new Mundo360Simulation(world);ok('restaura schema4',restored.restore(snap));ok('schema4 preserva etapa industrial',restored.quest.industrialStage===2&&restored.quest.cargoRoutes.size===3);
// conveyor physics
const beltSim=new Mundo360Simulation({schemaVersion:4,regions:[industrial]});const belt=industrial.conveyors[0];beltSim.player.pos={x:belt.position[0],y:0,z:belt.position[2]};beltSim.player.vel={x:0,y:0,z:0};beltSim.player.grounded=true;const beforeX=beltSim.player.pos.x,beforeZ=beltSim.player.pos.z;beltSim.tick(.04,{});const moved=Math.hypot(beltSim.player.pos.x-beforeX,beltSim.player.pos.z-beforeZ);ok('esteira desloca personagem',moved>0.02,`deslocamento=${moved.toFixed(3)}`);
// source/integration markers
const simsrc=fs.readFileSync(path.join(root,'games/mundo-plataforma-ds-360/simulation.mjs'),'utf8'),render=fs.readFileSync(path.join(root,'games/mundo-plataforma-ds-360/render.mjs'),'utf8'),game=fs.readFileSync(path.join(root,'games/mundo-plataforma-ds-360/game.js'),'utf8');ok('simulação possui esteiras',simsrc.includes('region.conveyors')&&simsrc.includes("type==='cargo-console'"));ok('render possui indústria',render.includes('#industrialGround')&&render.includes('#industrialEntities'));ok('game carrega industrial.json',game.includes("'./industrial.json'"));ok('ready anuncia 4 regiões',game.includes('regions:4')&&game.includes('industrial:true'));
const app=fs.readFileSync(path.join(root,'app.js'),'utf8'),sw=fs.readFileSync(path.join(root,'sw.js'),'utf8'),version=read('version.json'),profiles=read('game-profiles.json'),learning=read('education/game-learning.json');ok('versão pública v0.38.4',version.version==='0.38.4'&&version.phase.includes('Fase 7.25'));ok('Service Worker v0.38.4',sw.includes("const VERSION = '0.38.4'"));ok('Industrial no cache offline',sw.includes("'./games/mundo-plataforma-ds-360/industrial.json'"));ok('wrapper reconhece 4 regiões',app.includes('#summary={region:1,regions:4')&&app.includes('regions:4,mode360:true,village:true,forest:true,industrial:true'));ok('catálogo marca Fase 7.25',app.includes("phase:'Fase 7.25 · v0.38.4'")&&app.includes('"releasePhase": 7.25'));ok('catálogo cita Região Industrial',app.includes("title:'Mundo Plataforma DS 360 · Região Industrial'"));ok('perfil externo cita 4 regiões',profiles['mundo-plataforma-ds-360']?.options?.campanha?.includes('Regiões 1–4'));ok('tutorial externo cita 3 cargas',profiles['mundo-plataforma-ds-360']?.tutorialSteps?.some(x=>x.includes('3 Cargas')));ok('ficha educacional cita Industrial',learning['mundo-plataforma-ds-360']?.stageLabel?.includes('Região Industrial'));ok('save educacional cita schema 4',learning['mundo-plataforma-ds-360']?.qualityNotes?.some(x=>x.includes('schema 4')));ok('game HUD possui Energia',game.includes("orbsLabel').textContent=p.industrialStage<1?'Energia'"));ok('game trata evento cargo-route',game.includes("ev.type==='cargo-route'"));ok('game vitória usa 4 regiões',game.includes("post('victory',{region:4,regions:4"));
const passed=items.filter(x=>x.passed).length,failed=items.length-passed,result={suite:'Mundo Plataforma DS 360 v0.38.4 · Região Industrial',checks:items.length,passed,failed,items};fs.writeFileSync(path.join(root,'validation/mundo-plataforma-360-results-v0.38.4.json'),JSON.stringify(result,null,2)+'\n');fs.writeFileSync(path.join(root,'TESTES-MUNDO-PLATAFORMA-360-v0.38.4.md'),`# Testes — Mundo Plataforma DS 360 v0.38.4 · Região Industrial\n\n- Verificações: **${items.length}**\n- Aprovadas: **${passed}**\n- Falhas: **${failed}**\n\n`+items.map(i=>`- ${i.passed?'✅':'❌'} ${i.name}${i.detail?` — ${i.detail}`:''}`).join('\n')+'\n');console.log(JSON.stringify({checks:items.length,passed,failed}));if(failed){for(const i of items.filter(x=>!x.passed))console.error('FAIL',i.name,i.detail);process.exit(1)}
