#!/usr/bin/env node
'use strict';
const fs=require('node:fs');const path=require('node:path');
const root=path.resolve(__dirname,'..');const checks=[];
const test=(name,ok,detail)=>checks.push({name,status:ok?'pass':'fail',detail});
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const json=p=>JSON.parse(read(p));
const app=read('app.js'), sw=read('sw.js'), index=read('index.html'), education=json('education/game-learning.json'), version=json('version.json');
const manifest=json('games/voxelcraft-ds/manifest.json'), storage=read('games/voxelcraft-ds/js/storage.js'), voxel=read('games/voxelcraft-ds/js/game.js'), voxelApp=read('games/voxelcraft-ds/js/app.js');
const three=json('validation/three-d-campaign-results-v0.36.2.json'), voxelResult=json('validation/voxelcraft-campaign-results-v0.36.2.json'), audit=json('validation/game-audit-results.json'), physics=json('validation/platform-physics-test-results.json');

test('Expansão v0.36.2 preservada na release atual',String(version.version).startsWith('0.39.0')&&(app.includes("version: '0.39.0'") || app.includes("version: '0.39.0-hotfix1'"))&&(sw.includes("VERSION = '0.39.0'") || sw.includes("VERSION = '0.39.0-hotfix1'"))&&index.includes('v0.39.0'),'A release atual preserva a expansão histórica.');
test('Release atual identificada',version.phase.includes('Fase 7.28')&&app.includes('Fase 7.28'),'A release atual está identificada sem remover o conteúdo da Fase 7.17C.');
test('Setor · schema 3',app.includes('campaignStage: 1, completedStages: 0')&&app.includes('Campanha concluída: três protocolos poligonais sincronizados.'),'Setor Poligonal possui estado de campanha schema 3.');
test('Setor · protocolo 1',app.includes('Protocolo 1/3 — Geometria Base'),'Primeiro protocolo exige geometria e núcleos.');
test('Setor · protocolo 2',app.includes('Protocolo 2/3 — Materiais e Rotas'),'Segundo protocolo trabalha materiais e checkpoints.');
test('Setor · protocolo 3',app.includes('Protocolo 3/3 — Câmeras de Produção'),'Terceiro protocolo trabalha as três câmeras e conclusão.');
test('Setor · HUD de campanha',app.includes('PROTOCOLO ${state.campaignStage}/3')&&app.includes('P${state?.campaignStage ?? 1}/3'),'Overlay e HUD expõem a etapa atual.');
test('Setor · resultado 3/3',app.includes('/3 protocolos'),'Tela final informa protocolos concluídos.');
test('Câmeras · schema 3',app.includes('Laboratório concluído: três experimentos de câmera comparados e validados.'),'Câmeras em Evolução possui campanha persistente.');
test('Câmeras · experimento 1',app.includes('Experimento 1/3 — Enquadramento'),'Primeiro experimento trabalha lentes e enquadramento.');
test('Câmeras · experimento 2',app.includes('Experimento 2/3 — Campo de Visão'),'Segundo experimento trabalha 45°, 60° e 75°.');
test('Câmeras · experimento 3',app.includes('Experimento 3/3 — Sistema Completo'),'Terceiro experimento exige seis câmeras.');
test('Câmeras · HUD de campanha',app.includes('EXPERIMENTO ${state.campaignStage}/3')&&app.includes('E${state?.campaignStage ?? 1}/3'),'Overlay e HUD expõem experimento atual.');
test('Câmeras · resultado 3/3',app.includes('/3 experimentos'),'Tela final informa experimentos concluídos.');
test('Voxel · manifesto 13',manifest.version===13&&manifest.storage_schema===12&&manifest.campaign_stages===3&&manifest.fliperama_ds_version==='0.36.2','Manifesto registra campanha e schema atuais.');
test('Voxel · schema 12',storage.includes("world.v12")&&storage.includes('version: 12')&&storage.includes('chaptersCompleted'),'Etapa é persistida no estado sanitizado.');
test('Voxel · migração local v11',storage.includes("LEGACY_WORLD_KEYS = ['fliperama-ds.voxelcraft.world.v11']"),'Chave local anterior é importada automaticamente.');
test('Voxel · aprendizagem 3 etapas',voxel.includes('Etapa 1/3 — Streaming do mundo')&&voxel.includes('Etapa 2/3 — Recursos e inventário')&&voxel.includes('Etapa 3/3 — Construção e navegação'),'Aprendizagem possui três objetivos sequenciais.');
test('Voxel · desafio 3 etapas',voxel.includes('Etapa 1/3 — Cartografia de chunks')&&voxel.includes('Etapa 2/3 — Mineração persistente')&&voxel.includes('Etapa 3/3 — Engenharia de campo'),'Desafio possui três objetivos sequenciais.');
test('Voxel · avanço de etapa',voxel.includes("type:'mission-stage-complete'")&&voxel.includes('stats.chapter=completed+1'),'Conclusão intermediária libera a etapa seguinte.');
test('Voxel · conclusão final',voxel.includes('stats.chaptersCompleted=3')&&voxel.includes('As três etapas foram concluídas!'),'A terceira etapa registra conclusão final e XP.');
test('Voxel · resumo do save',voxelApp.includes('etapa ${chapter}/3'),'Menu informa a etapa persistida.');
test('Educação · Setor atualizado',education['polygon-sector-94'].stageLabel.includes('3 protocolos')&&education['polygon-sector-94'].progression.length>=4,'Ficha educacional descreve a campanha.');
test('Educação · Câmeras atualizada',education['camera-evolution'].stageLabel.includes('3 experimentos')&&education['camera-evolution'].progression.length>=4,'Ficha educacional descreve os experimentos.');
test('Educação · Voxel atualizado',education['voxelcraft-ds'].stageLabel.includes('3 etapas')&&education['voxelcraft-ds'].progression.length>=4,'Ficha educacional descreve as etapas.');
test('Teste 3D atual aprovado',three.summary.failed===0&&three.summary.passed===28,'Suíte 3D atual valida física, migração e campanhas.');
test('Teste Voxel atual aprovado',voxelResult.summary.failed===0&&voxelResult.summary.passed===26,'Suíte Voxel atual valida persistência e campanha.');
test('Auditoria geral preservada',audit.summary.gamesPassed===25&&audit.summary.gamesFailed===0&&audit.summary.checksFailed===0,'25 experiências permanecem aprovadas.');
test('Física preservada',physics.summary.failed===0&&physics.summary.passed===18,'Trap Lab e Ponte preservam física validada.');
test('Service Worker inclui validações atuais',sw.includes('three-d-campaign-results-v0.36.2.json')&&sw.includes('voxelcraft-campaign-results-v0.36.2.json')&&sw.includes('progression-expansion-results-v0.36.2.json'),'Resultados atuais fazem parte do shell offline.');
const summary={passed:checks.filter(c=>c.status==='pass').length,failed:checks.filter(c=>c.status==='fail').length,total:checks.length};
const result={product:'Fliperama DS',version:'0.36.2',phase:'Fase 7.17C — Expansão real das fases · Bloco 3/3',generatedAt:new Date().toISOString(),summary,checks};
fs.writeFileSync(path.join(__dirname,'progression-expansion-results-v0.36.2.json'),JSON.stringify(result,null,2)+'\n');
const lines=['# Testes da expansão de progressão — Fliperama DS v0.36.2','',`Gerado em: ${result.generatedAt}`,'',`- Verificações: **${summary.total}**`,`- Aprovadas: **${summary.passed}**`,`- Falhas: **${summary.failed}**`,'','## Resultados','',...checks.map(c=>`- **${c.status==='pass'?'APROVADO':'FALHOU'} — ${c.name}:** ${c.detail}`),''];
fs.writeFileSync(path.join(root,'TESTES-EXPANSAO-PROGRESSAO-v0.36.2.md'),lines.join('\n')+'\n');
console.log(JSON.stringify(summary,null,2));if(summary.failed)process.exitCode=1;
