const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const GRAVITY={earth:9.81,moon:1.62,mars:3.71,microgravity:0,rover:3.71,flight:0};
const MODE_DEFAULTS={earth:{drag:.18,maxSpeed:9},moon:{drag:.04,maxSpeed:5},mars:{drag:.12,maxSpeed:7},microgravity:{drag:.025,maxSpeed:4},rover:{drag:.09,maxSpeed:18},flight:{drag:.015,maxSpeed:42}};
export class UnifiedPhysicsController{
 constructor(mode='earth'){this.setMode(mode);this.reset();}
 setMode(mode){this.mode=GRAVITY[mode]!==undefined?mode:'earth';this.gravity=GRAVITY[this.mode];this.config=MODE_DEFAULTS[this.mode];return this.mode;}
 reset(){this.position={x:0,y:this.mode==='microgravity'?0:1.8,z:0};this.velocity={x:0,y:0,z:0};this.rotation={yaw:0,pitch:0,roll:0};this.grounded=this.gravity>0;this.energy=100;this.fuel=100;this.distance=0;this.collisions=0;this.suspension=[0,0,0,0,0,0];return this.snapshot();}
 update(dt=.016,input={}){dt=clamp(dt,0,.05);const before={...this.position};const boost=input.boost?1.8:1;const accel=(this.mode==='rover'?8:this.mode==='flight'||this.mode==='microgravity'?4.6:5.2)*boost;const yaw=Number(input.lookX||0)*dt*1.8;this.rotation.yaw+=yaw;this.rotation.pitch=clamp(this.rotation.pitch+Number(input.lookY||0)*dt*1.5,-1.45,1.45);this.rotation.roll=clamp(this.rotation.roll+Number(input.roll||0)*dt*1.8,-Math.PI,Math.PI);const forward=Number(input.forward||0),right=Number(input.right||0),up=Number(input.up||0);const sy=Math.sin(this.rotation.yaw),cy=Math.cos(this.rotation.yaw);this.velocity.x+=(right*cy+forward*sy)*accel*dt;this.velocity.z+=(forward*cy-right*sy)*accel*dt;if(this.mode==='flight'||this.mode==='microgravity'){this.velocity.y+=up*accel*dt;this.fuel=clamp(this.fuel-(Math.abs(forward)+Math.abs(right)+Math.abs(up)+Math.abs(input.roll||0))*.04,0,100);}else{this.velocity.y-=this.gravity*dt;if(input.jump&&this.grounded){this.velocity.y=Math.sqrt(2*this.gravity*(this.mode==='moon'?1.4:.65));this.grounded=false;}}
 const drag=Math.exp(-this.config.drag*dt*12);this.velocity.x*=drag;this.velocity.z*=drag;if(this.mode==='flight'||this.mode==='microgravity')this.velocity.y*=drag;const horizontal=Math.hypot(this.velocity.x,this.velocity.z);if(horizontal>this.config.maxSpeed){const s=this.config.maxSpeed/horizontal;this.velocity.x*=s;this.velocity.z*=s;}this.position.x+=this.velocity.x*dt;this.position.y+=this.velocity.y*dt;this.position.z+=this.velocity.z*dt;if(this.gravity>0&&this.position.y<1.8){this.position.y=1.8;this.velocity.y=0;this.grounded=true;}const boundary=45;if(Math.abs(this.position.x)>boundary||Math.abs(this.position.z)>boundary){this.position.x=clamp(this.position.x,-boundary,boundary);this.position.z=clamp(this.position.z,-boundary,boundary);this.velocity.x*=-.18;this.velocity.z*=-.18;this.collisions++;}
 const moved=Math.hypot(this.position.x-before.x,this.position.y-before.y,this.position.z-before.z);this.distance+=moved;this.energy=clamp(this.energy-moved*(this.mode==='rover'?.05:.025),0,100);if(this.mode==='rover'){const t=performance?.now?.()/400||0;this.suspension=this.suspension.map((_,i)=>Math.sin(t+i*1.7)*.08+Math.min(.24,horizontal*.014));}return this.snapshot();}
 snapshot(){return structuredClone({mode:this.mode,gravity:this.gravity,position:this.position,velocity:this.velocity,rotation:this.rotation,grounded:this.grounded,energy:this.energy,fuel:this.fuel,distance:this.distance,collisions:this.collisions,suspension:this.suspension,speed:Math.hypot(this.velocity.x,this.velocity.y,this.velocity.z)});}
}
