(function(){
'use strict';
const CFG=window.DS_EDUAUTH_CONFIG;const enc=new TextEncoder(),dec=new TextDecoder();const ALPH='0123456789ABCDEFGHJKMNPQRSTVWXYZ';
const MODE_CODE={CLASS_SHARED_PIN:1,SESSION_SCOPED_PIN:2,SIGNED_GRANT:3,PROFILE_RECOVERY_ENVELOPE:4};const MODE_ID={1:'CLASS_SHARED_PIN',2:'SESSION_SCOPED_PIN',3:'SIGNED_GRANT',4:'PROFILE_RECOVERY_ENVELOPE'};
const b64=b=>{let s='';new Uint8Array(b).forEach(x=>s+=String.fromCharCode(x));return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')};
const unb64=s=>{s=String(s).replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';return Uint8Array.from(atob(s),c=>c.charCodeAt(0));};
function randomBytes(n){const b=new Uint8Array(n);crypto.getRandomValues(b);return b;}function hex(b){return [...b].map(x=>x.toString(16).padStart(2,'0')).join('');}
function sessionId(){let id=sessionStorage.getItem('ds_eduauth_session_id');if(!id){id=crypto.randomUUID();sessionStorage.setItem('ds_eduauth_session_id',id);}return id;}
function canonical(value){if(value===null||typeof value!=='object')return JSON.stringify(value);if(Array.isArray(value))return '['+value.map(canonical).join(',')+']';return '{'+Object.keys(value).sort().map(k=>JSON.stringify(k)+':'+canonical(value[k])).join(',')+'}';}
function crc32c(bytes){let crc=0xffffffff;for(const byte of bytes){crc^=byte;for(let k=0;k<8;k++)crc=(crc>>>1)^((crc&1)?0x82f63b78:0);}return (crc^0xffffffff)>>>0;}
function base32Encode(bytes){let out='',bits=0,val=0;for(const byte of bytes){val=(val<<8)|byte;bits+=8;while(bits>=5){out+=ALPH[(val>>>(bits-5))&31];bits-=5;}}if(bits>0)out+=ALPH[(val<<(5-bits))&31];return out;}
function base32Decode(text){const clean=String(text).toUpperCase().replace(/[\s-]/g,'').replace(/O/g,'0').replace(/[IL]/g,'1');let out=[],bits=0,val=0;for(const ch of clean){const idx=ALPH.indexOf(ch);if(idx<0)throw new Error('Código-base possui caractere inválido.');val=(val<<5)|idx;bits+=5;if(bits>=8){out.push((val>>>(bits-8))&255);bits-=8;}}return new Uint8Array(out);}
function group(s,n=4){return s.match(new RegExp('.{1,'+n+'}','g')).join('-');}
function registryCode(type,id){const map=CFG.registries[type]||{};const v=map[id];if(!v)throw new Error('Identificador não registrado: '+type+'/'+id);return v;}
function reverse(type,code){const map=CFG.registries[type]||{};return Object.keys(map).find(k=>Number(map[k])===Number(code))||'unknown-'+code;}
function hashTag(text,n=4){return crypto.subtle.digest('SHA-256',enc.encode(String(text))).then(d=>new Uint8Array(d).slice(0,n));}
function putU32(view,offset,value){view.setUint32(offset,Number(value)>>>0,false);}function getU32(view,offset){return view.getUint32(offset,false);}
async function buildRequest(opts={}){try{const previous=JSON.parse(sessionStorage.getItem('ds_eduauth_active_request')||'null');if(previous?.requestTag&&previous?.mode!=='CLASS_SHARED_PIN')sessionStorage.setItem('ds_eduauth_consumed_'+previous.requestTag,'1');}catch(_){}const action=CFG.actions[opts.actionId];if(!action)throw new Error('Ação EduAuth não cadastrada.');const mode=opts.mode||action.preferredMode;const modeCode=MODE_CODE[mode];if(!modeCode)throw new Error('Modalidade inválida.');const now=Math.floor(Date.now()/1000);const win=mode==='CLASS_SHARED_PIN'?CFG.timePolicy.classWindowSeconds:(action.ttlSeconds||CFG.timePolicy.sessionWindowSeconds);const slot=Math.floor(now/win);const isSession=mode!=='CLASS_SHARED_PIN';const extra=isSession?16:0;const payload=new Uint8Array(15+extra);const v=new DataView(payload.buffer);payload[0]=CFG.protocolVersion;payload[1]=modeCode;payload[2]=1;payload[3]=CFG.platform.numericCode;payload[4]=registryCode('classes',opts.classId||'__all__');payload[5]=registryCode('subjects',opts.subjectId);v.setUint16(6,registryCode('lessons',opts.lessonId),false);payload[8]=registryCode('activities',opts.activityId||'principal');payload[9]=registryCode('actions',opts.actionId);putU32(v,10,slot);payload[14]=1;let expiresAt=mode==='CLASS_SHARED_PIN'?now+win:(slot+1)*win;let requestTag='',sessionTag='',resourceTag='';if(isSession){const nonce=randomBytes(4);payload.set(nonce,15);expiresAt=now+(action.ttlSeconds||300);putU32(v,19,expiresAt);const st=await hashTag(sessionId(),4);payload.set(st,23);const rt=await hashTag(opts.resourceId||opts.lessonId,4);payload.set(rt,27);requestTag=hex(nonce);sessionTag=hex(st);resourceTag=hex(rt);}const crc=crc32c(payload);const packet=new Uint8Array(payload.length+4);packet.set(payload);new DataView(packet.buffer).setUint32(payload.length,crc,false);const prefix=mode==='CLASS_SHARED_PIN'?'EA1-C1-K01':mode==='SESSION_SCOPED_PIN'?'EA1-S1-K01':mode==='SIGNED_GRANT'?'EA1-G1-K01':'EA1-R1-K01';const code=prefix+'-'+group(base32Encode(packet));const req={protocol:'EDUAUTH',version:1,mode,code,payloadB64:b64(payload),createdAt:now,expiresAt,requestTag,requestId:requestTag,sessionTag,resourceTag,sessionId:sessionId(),context:{platformId:CFG.platform.id,classId:opts.classId||'__all__',subjectId:opts.subjectId,lessonId:opts.lessonId,activityId:opts.activityId||'principal',actionId:opts.actionId,resourceId:opts.resourceId||opts.lessonId,profileIdHash:opts.profileIdHash||'',reason:opts.reason||'',teacher:opts.teacher||''},action};sessionStorage.setItem('ds_eduauth_active_request',JSON.stringify(req));return req;}
function decodeRequestCode(code){const clean=String(code).trim().toUpperCase();const m=clean.match(/^EA1-([CSGR])1-K(\d\d)-(.+)$/);if(!m)throw new Error('Formato de código-base incompatível.');const packet=base32Decode(m[3]);if(packet.length<19)throw new Error('Código-base incompleto.');const payload=packet.slice(0,-4);const expected=new DataView(packet.buffer,packet.byteOffset+packet.length-4,4).getUint32(0,false);if(crc32c(payload)!==expected)throw new Error('Checksum inválido. Confira a digitação.');const v=new DataView(payload.buffer,payload.byteOffset,payload.byteLength);const out={version:payload[0],mode:MODE_ID[payload[1]],keyVersion:payload[2],platformCode:payload[3],classCode:payload[4],subjectCode:payload[5],lessonCode:v.getUint16(6,false),activityCode:payload[8],actionCode:payload[9],timeSlot:getU32(v,10),policyVersion:payload[14],payloadB64:b64(payload)};const prefixMode={C:'CLASS_SHARED_PIN',S:'SESSION_SCOPED_PIN',G:'SIGNED_GRANT',R:'PROFILE_RECOVERY_ENVELOPE'}[m[1]];if(out.version!==CFG.protocolVersion||out.keyVersion!==1||out.platformCode!==CFG.platform.numericCode||out.mode!==prefixMode)throw new Error('Versão, plataforma ou modalidade incompatível.');if(payload.length>=31){out.nonce=hex(payload.slice(15,19));out.expiresAt=getU32(v,19);out.sessionTag=hex(payload.slice(23,27));out.resourceTag=hex(payload.slice(27,31));out.requestTag=out.nonce;out.requestId=out.requestTag;}out.ids={classId:reverse('classes',out.classCode),subjectId:reverse('subjects',out.subjectCode),lessonId:reverse('lessons',out.lessonCode),activityId:reverse('activities',out.activityCode),actionId:reverse('actions',out.actionCode)};return out;}
async function hmacKey(kind){const raw=unb64(CFG.keys[kind].rawB64);return crypto.subtle.importKey('raw',raw,{name:'HMAC',hash:'SHA-256'},false,['sign']);}
function dynamicNumber(mac){const off=mac[mac.length-1]&15;return((((mac[off]&127)<<24)|((mac[off+1]&255)<<16)|((mac[off+2]&255)<<8)|(mac[off+3]&255))>>>0);}
async function calculateClassPin(request,issuedMinute=Math.floor(Date.now()/60000)){const key=await hmacKey('class');const payload=unb64(request.payloadB64);const stable=payload.slice(0,10);const message=new Uint8Array(stable.length+4);message.set(stable);new DataView(message.buffer).setUint32(stable.length,Number(issuedMinute)>>>0,false);const mac=new Uint8Array(await crypto.subtle.sign('HMAC',key,message));const tag=String(Number(issuedMinute)%1000).padStart(3,'0');const body=String(dynamicNumber(mac)%100000).padStart(5,'0');return tag+body;}
async function calculatePin(request){if(request.mode==='CLASS_SHARED_PIN')return calculateClassPin(request);const key=await hmacKey('session');const payload=unb64(request.payloadB64);const mac=new Uint8Array(await crypto.subtle.sign('HMAC',key,payload));const len=request.action.pinLength||8;return String(dynamicNumber(mac)%(10**len)).padStart(len,'0');}
function normalizePin(v){return String(v||'').replace(/\D/g,'');}function safeEqual(a,b){a=String(a);b=String(b);if(a.length!==b.length)return false;let d=0;for(let i=0;i<a.length;i++)d|=a.charCodeAt(i)^b.charCodeAt(i);return d===0;}
async function verifyPin(request,pin){const normalized=normalizePin(pin);if(request.mode==='CLASS_SHARED_PIN'){if(normalized.length!==8)return false;const tag=Number(normalized.slice(0,3));const nowMinute=Math.floor(Date.now()/60000);for(let age=0;age<=60;age++){const issued=nowMinute-age;if(issued%1000!==tag)continue;if(safeEqual(normalized,await calculateClassPin(request,issued)))return true;}return false;}if(Date.now()/1000>request.expiresAt)throw new Error('Solicitação expirada. Gere uma nova.');if(sessionStorage.getItem('ds_eduauth_consumed_'+request.requestTag)==='1')throw new Error('Esta autorização já foi utilizada.');const exp=await calculatePin(request);const ok=safeEqual(normalized,exp);if(ok&&request.action.singleUse)sessionStorage.setItem('ds_eduauth_consumed_'+request.requestTag,'1');return ok;}
async function importVerifyKey(){return crypto.subtle.importKey('jwk',CFG.keys.signing.publicJwk,{name:'ECDSA',namedCurve:'P-256'},false,['verify']);}
async function verifySignedGrant(request,token){const parts=String(token||'').trim().split('.');if(parts.length!==3||parts[0]!=='EA1-G1')throw new Error('Token assinado inválido.');const payloadText=dec.decode(unb64(parts[1]));const grant=JSON.parse(payloadText);const key=await importVerifyKey();const ok=await crypto.subtle.verify({name:'ECDSA',hash:'SHA-256'},key,unb64(parts[2]),enc.encode(payloadText));if(!ok)throw new Error('Assinatura inválida.');const now=Math.floor(Date.now()/1000);if(now>grant.expiresAt)throw new Error('Autorização assinada expirada.');if(grant.platformId!==CFG.platform.id||grant.actionId!==request.context.actionId||grant.lessonId!==request.context.lessonId||grant.sessionTag!==request.sessionTag||grant.requestTag!==request.requestTag||grant.resourceTag!==request.resourceTag)throw new Error('Autorização pertence a outro contexto ou sessão.');if(sessionStorage.getItem('ds_eduauth_signed_'+request.requestTag)==='1')throw new Error('Autorização assinada já utilizada.');sessionStorage.setItem('ds_eduauth_signed_'+request.requestTag,'1');return grant;}
function describe(req){const r=CFG.registries;return{mode:req.mode,modeLabel:req.mode==='CLASS_SHARED_PIN'?'Código coletivo da aula — validade de 1 hora':req.mode==='SESSION_SCOPED_PIN'?'Código individual da sessão':'Autorização assinada',risk:req.action.risk,classLabel:r.classLabels[req.context.classId]||req.context.classId,subjectLabel:r.subjectLabels[req.context.subjectId]||req.context.subjectId,lessonLabel:r.lessonLabels[req.context.lessonId]||req.context.lessonId,activityLabel:r.activityLabels[req.context.activityId]||req.context.activityId,actionLabel:req.action.label};}
function qrSvg(text,size=240){if(!window.DS_QRCodeModel)return '';const q=new window.DS_QRCodeModel(-1,window.DS_QRErrorCorrectLevel.L);q.addData(text);q.make();const n=q.getModuleCount(),quiet=4,cell=Math.max(2,Math.floor(size/(n+quiet*2))),total=(n+quiet*2)*cell;let rect='';for(let r=0;r<n;r++)for(let c=0;c<n;c++)if(q.isDark(r,c))rect+=`<rect x="${(c+quiet)*cell}" y="${(r+quiet)*cell}" width="${cell}" height="${cell}"/>`;return `<svg xmlns="http://www.w3.org/2000/svg" role="img" aria-label="QR Code da solicitação EduAuth" viewBox="0 0 ${total} ${total}" width="${total}" height="${total}"><rect width="100%" height="100%" fill="white"/><g fill="black">${rect}</g></svg>`;}
async function openAuditDb(){return new Promise((res,rej)=>{const rq=indexedDB.open('ds-eduauth-v1',1);rq.onupgradeneeded=()=>{if(!rq.result.objectStoreNames.contains('audit'))rq.result.createObjectStore('audit',{keyPath:'id'});};rq.onsuccess=()=>res(rq.result);rq.onerror=()=>rej(rq.error);});}
async function audit(type,req,details={}){try{const db=await openAuditDb();const tx=db.transaction('audit','readwrite');tx.objectStore('audit').put({id:crypto.randomUUID(),at:new Date().toISOString(),type,platformId:CFG.platform.id,mode:req?.mode||'',actionId:req?.context?.actionId||'',classId:req?.context?.classId||'',subjectId:req?.context?.subjectId||'',lessonId:req?.context?.lessonId||'',requestTag:req?.requestTag||'',sessionTag:req?.sessionTag||'',details});await new Promise((res,rej)=>{tx.oncomplete=res;tx.onerror=()=>rej(tx.error);});db.close();}catch(e){console.warn('EduAuth audit indisponível',e);}}
window.DS_EduAuthCore={CFG,buildRequest,decodeRequestCode,calculatePin,verifyPin,verifySignedGrant,describe,qrSvg,audit,canonical,b64,unb64,sessionId,normalizePin};
})();
