'use strict';
(function(){
  const commonLanguages=['Português (Brasil)','Português (Portugal)','English (United States)','English (United Kingdom)','Español (España)','Español (Latinoamérica)','Français','Deutsch','Italiano','日本語'];
  const commonKeyboards=['ABNT2','ABNT','US','US International','Português (Portugal)','Español','Latino-americano'];
  const P=(cfg)=>Object.freeze({
    edition:'Padrão',architectures:['x64'],defaultArch:'x64',minRam:2,recRam:4,minDisk:32,
    firmwareSupport:['uefi','bios'],defaultFirmware:'uefi',partitionTable:'gpt',filesystem:'ntfs',
    languages:commonLanguages,keyboards:commonKeyboards,secureBoot:'optional',tpm:'optional',
    desktopApps:['Arquivos','Configurações','Terminal'],oobe:['Região','Teclado','Rede','Usuário','Privacidade'],
    ...cfg
  });
  window.LABDS_VM_PROFILES={
    'windows-xp':P({id:'windows-xp',family:'windows',product:'Windows XP Professional',version:'SP3',edition:'Professional',architectures:['x86'],defaultArch:'x86',minRam:.512,recRam:1,minDisk:8,firmwareSupport:['bios'],defaultFirmware:'bios',partitionTable:'mbr',filesystem:'ntfs',secureBoot:'unsupported',tpm:'unsupported',visual:'winxp',bootLabel:'Windows XP Setup',installer:'winxp',desktop:'Luna',desktopApps:['Meu Computador','Painel de Controle','Prompt de Comando'],oobe:['Região','Nome do computador','Usuário','Rede'],installSteps:['Carregando arquivos de instalação','Preparando disco','Copiando arquivos','Instalando dispositivos','Configurando rede','Registrando componentes','Concluindo instalação']}),
    windows7:P({id:'windows7',family:'windows',product:'Windows 7',version:'SP1',edition:'Professional',architectures:['x86','x64'],defaultArch:'x64',minRam:1,recRam:2,minDisk:20,firmwareSupport:['bios','uefi'],defaultFirmware:'bios',partitionTable:'mbr',filesystem:'ntfs',secureBoot:'unsupported',visual:'win7',bootLabel:'Windows is loading files...',installer:'win7',desktop:'Aero',desktopApps:['Windows Explorer','Painel de Controle','Prompt de Comando'],oobe:['Nome de usuário','Nome do computador','Senha','Windows Update','Data e hora','Local de rede'],installSteps:['Copiando arquivos do Windows','Expandindo arquivos do Windows','Instalando recursos','Instalando atualizações','Concluindo a instalação']}),
    windows8:P({id:'windows8',family:'windows',product:'Windows 8',version:'RTM',edition:'Pro',minRam:2,recRam:4,minDisk:20,visual:'win8',bootLabel:'Windows Setup',installer:'win8',desktop:'Start Screen',desktopApps:['Explorador de Arquivos','Configurações','PowerShell'],oobe:['Personalizar','Nome do computador','Configurações expressas','Conta local'],installSteps:['Copiando arquivos','Preparando arquivos','Instalando recursos','Instalando atualizações','Concluindo']}),
    windows81:P({id:'windows81',family:'windows',product:'Windows 8.1',version:'Update',edition:'Pro',minRam:2,recRam:4,minDisk:20,visual:'win81',bootLabel:'Windows Setup',installer:'win81',desktop:'Start Screen 8.1',desktopApps:['Explorador de Arquivos','Configurações do PC','PowerShell'],oobe:['Região','Licença','Configurações expressas','Rede','Conta local','OneDrive simulado'],installSteps:['Copiando arquivos','Preparando arquivos','Instalando recursos','Aplicando atualizações','Concluindo']}),
    windows10:P({id:'windows10',family:'windows',product:'Windows 10',version:'22H2',edition:'Pro',minRam:2,recRam:4,minDisk:32,visual:'win10',bootLabel:'Instalação do Windows',installer:'win10',desktop:'Windows 10',desktopApps:['Explorador de Arquivos','Configurações','PowerShell'],oobe:['Região','Teclado','Rede','Uso pessoal','Conta local','PIN','Privacidade'],installSteps:['Copiando arquivos','Preparando arquivos','Instalando recursos','Instalando atualizações','Concluindo']}),
    windows11:P({id:'windows11',family:'windows',product:'Windows 11',version:'24H2',edition:'Pro',minRam:4,recRam:8,minDisk:64,firmwareSupport:['uefi'],defaultFirmware:'uefi',secureBoot:'required',tpm:'required',visual:'win11',bootLabel:'Windows Setup',installer:'win11',desktop:'Windows 11',desktopApps:['Explorador de Arquivos','Configurações','Terminal'],oobe:['Região','Teclado','Rede','Conta local simulada','PIN','Privacidade'],installSteps:['Copiando arquivos','Preparando arquivos','Instalando recursos','Aplicando atualizações','Concluindo']}),
    ubuntu2404:P({id:'ubuntu2404',family:'linux',product:'Ubuntu Desktop',version:'24.04 LTS',edition:'GNOME',minRam:4,recRam:8,minDisk:25,filesystem:'ext4',visual:'ubuntu',bootLabel:'Try or Install Ubuntu',installer:'ubuntu-modern',desktop:'GNOME',desktopApps:['Files','Configurações','Terminal'],secureBoot:'optional',tpm:'unsupported',oobe:['Idioma','Acessibilidade','Teclado','Rede','Tipo de instalação','Usuário','Fuso horário'],installSteps:['Preparando sistema de arquivos','Copiando arquivos','Instalando pacotes','Configurando hardware','Criando usuário','Instalando GRUB','Limpando arquivos temporários']}),
    ubuntu2604:P({id:'ubuntu2604',family:'linux',product:'Ubuntu Desktop',version:'26.04 LTS — perfil educacional',edition:'GNOME',minRam:4,recRam:8,minDisk:30,filesystem:'ext4',visual:'ubuntu26',bootLabel:'Try or Install Ubuntu',installer:'ubuntu-modern',desktop:'GNOME',desktopApps:['Files','App Center','Terminal'],secureBoot:'optional',tpm:'unsupported',oobe:['Idioma','Acessibilidade','Teclado','Rede','Aplicativos','Disco','Usuário','Fuso'],installSteps:['Preparando disco','Copiando sistema','Instalando pacotes','Configurando idiomas','Criando usuário','Instalando bootloader','Finalizando']}),
    mint:P({id:'mint',family:'linux',product:'Linux Mint',version:'22',edition:'Cinnamon',minRam:2,recRam:4,minDisk:25,filesystem:'ext4',visual:'mint',bootLabel:'Start Linux Mint',installer:'ubiquity',desktop:'Cinnamon',desktopApps:['Nemo','Configurações do Sistema','Terminal'],secureBoot:'optional',tpm:'unsupported',oobe:['Idioma','Teclado','Codecs','Disco','Fuso','Usuário'],installSteps:['Copiando arquivos','Instalando sistema','Configurando hardware','Instalando bootloader','Limpando','Concluindo']}),
    debian13:P({id:'debian13',family:'linux',product:'Debian',version:'13',edition:'GNOME',minRam:2,recRam:4,minDisk:20,filesystem:'ext4',visual:'debian',bootLabel:'Debian GNU/Linux installer menu',installer:'debian-installer',desktop:'GNOME',desktopApps:['Files','Configurações','Terminal'],secureBoot:'optional',tpm:'unsupported',oobe:['Idioma','Localização','Teclado','Rede','Usuários','Discos','Espelho','Software'],installSteps:['Detectando hardware','Instalando sistema base','Configurando apt','Selecionando software','Instalando GRUB','Finalizando']}),
    fedora:P({id:'fedora',family:'linux',product:'Fedora Workstation',version:'41',edition:'GNOME',minRam:4,recRam:8,minDisk:20,filesystem:'btrfs',visual:'fedora',bootLabel:'Start Fedora Workstation Live',installer:'anaconda',desktop:'GNOME',desktopApps:['Files','Software','Terminal'],secureBoot:'optional',tpm:'unsupported',oobe:['Idioma','Destino da instalação','Rede e hostname','Usuário','Resumo'],installSteps:['Preparando armazenamento','Instalando software','Configurando sistema','Instalando bootloader','Gerando initramfs','Finalizando']}),
    arch:P({id:'arch',family:'linux',product:'Arch Linux',version:'Rolling',edition:'Modo técnico',minRam:1,recRam:2,minDisk:12,filesystem:'ext4',visual:'arch',bootLabel:'Arch Linux install medium',installer:'arch-console',desktop:'Console',desktopApps:['Terminal','Arquivos','Configuração'],secureBoot:'unsupported',tpm:'unsupported',oobe:['Teclado','Rede','Discos','Base','Fuso','Usuário','Bootloader'],installSteps:['Particionando disco','Montando volumes','Instalando base','Gerando fstab','Configurando sistema','Instalando bootloader','Finalizando']}),
    kde:P({id:'kde',family:'linux',product:'Sistema Linux KDE',version:'Plasma 6',edition:'Perfil genérico',minRam:2,recRam:4,minDisk:20,filesystem:'ext4',visual:'kde',bootLabel:'Linux KDE Live',installer:'calamares',desktop:'KDE Plasma',desktopApps:['Dolphin','Configurações do Sistema','Konsole'],secureBoot:'optional',tpm:'unsupported',oobe:['Idioma','Teclado','Localização','Disco','Usuário','Resumo'],installSteps:['Preparando partições','Copiando arquivos','Configurando sistema','Instalando bootloader','Finalizando']}),
    chromeos:P({id:'chromeos',family:'chrome',product:'ChromeOS — Chromebook virtual',version:'Perfil atual',edition:'Nativo',architectures:['x64','arm64'],defaultArch:'x64',minRam:4,recRam:8,minDisk:32,firmwareSupport:['chrome'],defaultFirmware:'chrome',partitionTable:'gpt',filesystem:'chromeos',secureBoot:'required',tpm:'required',visual:'chromeos',bootLabel:'Verified Boot',installer:'chromeos-oobe',desktop:'ChromeOS',desktopApps:['Files','Configurações','Crosh'],keyboards:['Chromebook','ABNT2','US'],oobe:['Idioma','Teclado','Acessibilidade','Rede','Termos','Perfil local simulado','PIN','Tema'],installSteps:['Verificando imagem','Atualizando componentes','Configurando armazenamento','Aplicando sistema','Verificando assinatura','Finalizando']}),
    'chromeos-flex':P({id:'chromeos-flex',family:'chrome',product:'ChromeOS Flex',version:'Perfil atual',edition:'Computador x86-64',architectures:['x64'],defaultArch:'x64',minRam:4,recRam:8,minDisk:16,firmwareSupport:['uefi','bios'],defaultFirmware:'uefi',partitionTable:'gpt',filesystem:'chromeos',secureBoot:'optional',tpm:'optional',visual:'chromeosflex',bootLabel:'ChromeOS Flex USB',installer:'chromeos-flex',desktop:'ChromeOS Flex',desktopApps:['Files','Configurações','Crosh'],keyboards:['ABNT2','US','US International'],oobe:['Idioma','Teclado','Acessibilidade','Rede','Experimentar ou instalar','Conta local simulada'],installSteps:['Verificando hardware','Apagando disco virtual','Criando estrutura interna','Copiando sistema','Verificando instalação','Desligando']}),
    'mac-intel':P({id:'mac-intel',family:'macos',product:'macOS',version:'Perfil moderno — Intel',edition:'Mac Intel',architectures:['x64'],defaultArch:'x64',minRam:4,recRam:8,minDisk:64,firmwareSupport:['mac-intel'],defaultFirmware:'mac-intel',partitionTable:'gpt',filesystem:'apfs',secureBoot:'optional',tpm:'unsupported',visual:'macintel',bootLabel:'macOS Recovery',installer:'macos',desktop:'macOS',desktopApps:['Finder','Configurações do Sistema','Terminal'],keyboards:['Apple Português','Apple US','ABNT2'],oobe:['Idioma','Região','Acessibilidade','Rede','Privacidade','Migração','Conta local simulada','Aparência'],installSteps:['Preparando instalação','Verificando volume APFS','Copiando arquivos','Instalando componentes','Atualizando firmware simulado','Reiniciando','Finalizando']}),
    'mac-apple':P({id:'mac-apple',family:'macos',product:'macOS',version:'Perfil moderno — Apple silicon',edition:'Mac Apple silicon',architectures:['arm64'],defaultArch:'arm64',minRam:8,recRam:16,minDisk:64,firmwareSupport:['mac-apple'],defaultFirmware:'mac-apple',partitionTable:'gpt',filesystem:'apfs',secureBoot:'required',tpm:'unsupported',visual:'macapple',bootLabel:'Carregando opções de inicialização',installer:'macos',desktop:'macOS',desktopApps:['Finder','Configurações do Sistema','Terminal'],keyboards:['Apple Português','Apple US'],oobe:['Idioma','Região','Acessibilidade','Rede','Privacidade','Migração','Conta local simulada','Aparência'],installSteps:['Verificando elegibilidade','Preparando volume APFS','Baixando componentes simulados','Instalando sistema','Selando volume do sistema','Reiniciando','Finalizando']})
  };
  window.LABDS_VM_PROFILE_GROUPS=[
    {label:'Microsoft Windows',ids:['windows-xp','windows7','windows8','windows81','windows10','windows11']},
    {label:'Linux',ids:['ubuntu2404','ubuntu2604','mint','debian13','fedora','arch','kde']},
    {label:'Google',ids:['chromeos','chromeos-flex']},
    {label:'Apple',ids:['mac-intel','mac-apple']}
  ];
})();
