import { SpaceAssemblyModel } from '../../core/workshop/SpaceAssemblyModel.js';
import { SpaceAssemblyRenderer } from '../../rendering/SpaceAssemblyRenderer.js';
import { SPACE_WORKSHOP_SYSTEMS,SPACE_WORKSHOP_BY_ID,WORKSHOP_DIFFICULTIES,WORKSHOP_FLOW_TYPES,WORKSHOP_GOALS } from '../../data/spaceWorkshopSystems.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const download=(name,text,type='application/json')=>{const blob=new Blob([text],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
class SpaceWorkshopModule{
  constructor(){this.container=null;this.context=null;this.model=null;this.renderer=null;this.raf=0;this.last=0;this.help=false;this.log=false;this.onClick=e=>this.handleClick(e);this.onKey=e=>this.handleKey(e);}
  mount(container,context){this.container=container;this.context=context;const requested=sessionStorage.getItem('cosmos-ds-workshop-target');sessionStorage.removeItem('cosmos-ds-workshop-target');this.model=new SpaceAssemblyModel(SPACE_WORKSHOP_BY_ID[requested]?requested:'satellite','guided');container.addEventListener('click',this.onClick);addEventListener('keydown',this.onKey);this.render();this.startRenderer();}
  unmount(){cancelAnimationFrame(this.raf);this.renderer?.destroy();this.container?.removeEventListener('click',this.onClick);removeEventListener('keydown',this.onKey);}
  render(){const system=this.model.system(),snap=this.model.snapshot(),selected=system.components.find(item=>item.id===snap.selectedComponentId)||system.components[0],next=snap.nextAction;this.container.innerHTML=`<section class="space-workshop" style="--workshop:${system.color}"><div class="workshop-stage"><canvas id="space-workshop-canvas" aria-label="Bancada 3D didática de ${esc(system.name)}"></canvas><div class="workshop-scanlines"></div>
  <header class="workshop-top immersive-hud"><button class="hud-icon" data-action="back">←</button><div class="target-chip"><span>${system.symbol}</span><div><b>${esc(system.name)}</b><small>Montagem, conexões, diagnóstico e manutenção</small></div></div><div class="workshop-top-actions"><span class="hud-status" id="workshop-renderer">Canvas 2D 3D</span><button class="hud-icon" data-action="toggle-help">?</button><button class="hud-icon" data-action="fullscreen">⛶</button></div></header>
  <div class="objective-chip workshop-objective"><span>PRÓXIMA AÇÃO · ${esc(snap.difficulty.toUpperCase())}</span><b>${esc(next.label)}</b><small>${esc(next.why)}</small></div>
  <nav class="workshop-system-rail immersive-hud">${SPACE_WORKSHOP_SYSTEMS.map(item=>`<button class="${item.id===system.id?'active':''}" data-action="select-system" data-system="${item.id}" style="--system:${item.color}"><i>${item.symbol}</i><span><b>${esc(item.name)}</b><small>${item.components.length} componentes</small></span></button>`).join('')}</nav>
  <nav class="workshop-difficulty immersive-hud">${WORKSHOP_DIFFICULTIES.map(item=>`<button class="${item.id===snap.difficulty?'active':''}" data-action="set-difficulty" data-difficulty="${item.id}" title="${esc(item.description)}"><b>${item.short}</b><span>${item.label}</span></button>`).join('')}</nav>
  <nav class="workshop-flow-rail immersive-hud">${WORKSHOP_FLOW_TYPES.map(item=>`<button class="${item.id===snap.selectedFlow?'active':''}" data-action="set-flow" data-flow="${item.id}"><i>${item.short}</i><span>${item.label}</span><small>${system.links.filter(link=>link.type===item.id&&snap.connected.includes(link.id)).length}/${system.links.filter(link=>link.type===item.id).length}</small></button>`).join('')}</nav>
  <aside class="workshop-parts immersive-hud"><span class="eyebrow">BANDEJA DE COMPONENTES</span><div>${system.components.map(item=>{const slot=Object.entries(snap.installed).find(([,id])=>id===item.id)?.[0],fault=snap.activeFault?.target===item.id;return `<button class="${item.id===selected.id?'active':''} ${slot?'installed':''} ${fault?'fault':''}" data-action="select-component" data-component="${item.id}"><i>${item.icon}</i><span><b>${esc(item.name)}</b><small>${slot?`Instalado: ${esc(slot)}`:`Ordem ${item.order} · ${esc(item.role)}`}</small></span></button>`;}).join('')}</div></aside>
  <aside class="workshop-detail immersive-hud"><span class="eyebrow">${selected.icon} COMPONENTE SELECIONADO</span><h2>${esc(selected.name)}</h2><p>${esc(selected.description)}</p><dl><div><dt>Função</dt><dd>${esc(selected.role)}</dd></div><div><dt>Relação com DS</dt><dd>${esc(selected.ds)}</dd></div><div><dt>Sensores</dt><dd>${esc(selected.sensors.join(' · '))}</dd></div><div><dt>Software</dt><dd>${esc(selected.software.join(' · '))}</dd></div><div><dt>Encaixe esperado</dt><dd>${esc(selected.slot)}</dd></div></dl><div class="workshop-component-actions"><button data-action="install-selected">Instalar no encaixe</button><button data-action="remove-selected" class="secondary">Remover/substituir</button><button data-action="repair-fault" class="secondary">Confirmar reparo</button></div></aside>
  <aside class="workshop-connections immersive-hud"><header><span class="eyebrow">CABOS E CONEXÕES</span><b>${esc(snap.selectedFlow)}</b></header><div>${system.links.filter(item=>item.type===snap.selectedFlow).map(item=>`<button class="${snap.connected.includes(item.id)?'connected':''} ${snap.activeFault?.target===item.id?'fault':''}" data-action="toggle-connection" data-link="${item.id}"><i>${snap.connected.includes(item.id)?'●':'○'}</i><span><b>${esc(item.label)}</b><small>${esc(item.from)} → ${esc(item.to)}</small></span></button>`).join('')}</div></aside>
  <aside class="workshop-diagnostics immersive-hud"><header><span class="eyebrow">DIAGNÓSTICO</span><b>${snap.progress.issues?snap.progress.issues+' pendência(s)':snap.testRuns?'APROVADO':'AGUARDANDO'}</b></header>${snap.activeFault?`<article class="workshop-fault"><b>${esc(snap.activeFault.label)}</b><p>${esc(snap.activeFault.symptom)}</p><small>${esc(snap.activeFault.diagnostic)}</small></article>`:''}${snap.diagnostics.length?`<div class="workshop-issues">${snap.diagnostics.slice(0,6).map(item=>`<p><b>${esc(item.kind)}</b>${esc(item.label)}</p>`).join('')}</div>`:'<p class="workshop-diagnostic-empty">Execute o teste para verificar montagem, encaixes e conexões.</p>'}<footer><button data-action="run-diagnostics">Executar teste</button><button data-action="inject-fault" class="secondary">Injetar falha</button></footer></aside>
  <aside class="workshop-progress immersive-hud"><header><span>MONTAGEM ${snap.progress.percent}%</span><b>${snap.progress.correct}/${snap.progress.totalComponents} peças · ${snap.progress.connected}/${snap.progress.totalConnections} conexões</b></header><div class="workshop-progress-bar"><i style="width:${snap.progress.percent}%"></i></div><p>${esc(system.story)}</p><footer><button data-action="register-evidence">Registrar na trilha</button><button data-action="export-evidence">Exportar evidência</button><button class="secondary" data-action="open-technical">Abrir painel técnico</button><button class="secondary" data-action="reset-workshop">Reiniciar</button></footer></aside>
  <button class="workshop-log-toggle immersive-hud" data-action="toggle-log">LOG ${snap.actions.length}</button><aside class="workshop-log immersive-hud ${this.log?'open':''}"><button class="drawer-close" data-action="toggle-log">×</button><span class="eyebrow">HISTÓRICO DA OFICINA</span>${snap.actions.slice(-16).reverse().map(item=>`<p><b>${esc(item.type)}</b><small>${new Date(item.at).toLocaleTimeString('pt-BR')}</small></p>`).join('')||'<p>Nenhuma ação.</p>'}</aside>
  <aside class="workshop-help immersive-hud ${this.help?'open':''}"><button class="drawer-close" data-action="toggle-help">×</button><span class="eyebrow">COMO UTILIZAR</span><h3>Montar, conectar, testar e reparar</h3><ol><li>Escolha um componente.</li><li>Toque no encaixe ou use “Instalar”.</li><li>Conecte energia, dados e comandos.</li><li>Execute o diagnóstico.</li><li>Remova e reinstale peças com falha.</li></ol><p>Os sistemas são modelos didáticos e não procedimentos industriais reais.</p></aside>
  <div class="workshop-loading" id="workshop-loading"><i></i><span>Preparando bancada e componentes…</span></div></div></section>`;}
  startRenderer(){const canvas=this.container.querySelector('#space-workshop-canvas');this.renderer=new SpaceAssemblyRenderer(canvas,this.context.settingsStore,{onSelect:hit=>this.handleCanvasSelect(hit),onDiagnostics:d=>{const el=this.container?.querySelector('#workshop-renderer');if(el)el.textContent=`${d.renderer} · ${d.resolution}`;}});this.renderer.setSystem(this.model.system());this.renderer.setState(this.model.snapshot());this.renderer.start();this.last=performance.now();const tick=now=>{const dt=Math.min(.05,(now-this.last)/1000||.016);this.last=now;this.model.update(dt);this.renderer?.setState(this.model.snapshot());this.raf=requestAnimationFrame(tick);};this.raf=requestAnimationFrame(tick);setTimeout(()=>this.container.querySelector('#workshop-loading')?.classList.add('hidden'),380);}
  restart(){cancelAnimationFrame(this.raf);this.renderer?.destroy();this.render();this.startRenderer();}
  handleCanvasSelect(hit){if(hit.kind==='component'){this.model.selectComponent(hit.id);this.restart();return;}const selected=this.model.snapshot().selectedComponentId,result=this.model.placeComponent(selected,hit.slotId);this.context.toast(result.ok?(result.correct?'Componente instalado no encaixe correto.':'Componente instalado, mas o encaixe está incorreto.'):result.reason);if(result.ok)this.context.recordGuidedEvent?.('workshop-install',{systemId:this.model.systemId,componentId:selected,slotId:hit.slotId,correct:result.correct});this.restart();this.checkGoals();}
  selectSystem(id){if(!this.model.selectSystem(id))return;sessionStorage.setItem('cosmos-ds-workshop-target',id);this.restart();this.context.toast(`${this.model.system().name} preparada.`);}
  installSelected(){const id=this.model.snapshot().selectedComponentId,slot=this.model.expectedSlot(id),result=this.model.placeComponent(id,slot);this.context.toast(result.ok?'Componente instalado.':result.reason);if(result.ok)this.context.recordGuidedEvent?.('workshop-install',{systemId:this.model.systemId,componentId:id,slotId:slot,correct:true});this.restart();this.checkGoals();}
  removeSelected(){const id=this.model.snapshot().selectedComponentId,result=this.model.removeComponent(id);this.context.toast(result.ok?'Componente removido para inspeção/substituição.':result.reason);if(result.ok)this.context.recordGuidedEvent?.('workshop-remove',{systemId:this.model.systemId,componentId:id});this.restart();}
  toggleConnection(id){const result=this.model.toggleConnection(id);this.context.toast(result.ok?(result.connected?'Conexão estabelecida.':'Conexão removida.'):result.reason);if(result.ok)this.context.recordGuidedEvent?.('workshop-connection',{systemId:this.model.systemId,linkId:id,connected:result.connected});this.restart();this.checkGoals();}
  runDiagnostics(){const result=this.model.runDiagnostics();this.context.recordGuidedEvent?.('workshop-diagnostic',{systemId:this.model.systemId,ok:result.ok,issues:result.issues.length});this.context.toast(result.ok?'Teste final aprovado.':'Diagnóstico encontrou pendências.');this.restart();this.checkGoals();}
  injectFault(){const faults=this.model.system().faults,current=this.model.snapshot().activeFault?.id,index=Math.max(-1,faults.findIndex(item=>item.id===current)),fault=this.model.injectFault(faults[(index+1)%faults.length].id);this.context.toast(`${fault.label}: falha didática ativada.`);this.restart();}
  repairFault(){const result=this.model.repairFault();this.context.toast(result.ok?'Reparo confirmado pelo diagnóstico.':result.reason);if(result.ok)this.context.recordGuidedEvent?.('workshop-repair',{systemId:this.model.systemId,faultId:result.fault.id});this.restart();this.checkGoals();}
  registerEvidence(){const evidence=this.model.evidence(this.context.profileStore.active()),summary=`Oficina ${evidence.workshop.name}: ${evidence.session.progress.percent}% · ${evidence.session.progress.correct}/${evidence.session.progress.totalComponents} peças · ${evidence.session.progress.connected}/${evidence.session.progress.totalConnections} conexões.`;this.context.setGuidedEvidence?.(summary);this.context.recordGuidedEvent?.('workshop-evidence',{systemId:this.model.systemId,complete:evidence.session.progress.complete});this.context.toast('Evidência registrada na jornada ativa.');this.checkGoals();}
  exportEvidence(){const evidence=this.model.evidence(this.context.profileStore.active());download(`cosmos-oficina-${this.model.systemId}-${Date.now()}.json`,JSON.stringify(evidence,null,2));this.context.profileStore.addXp(150,'workshop-export-evidence');this.context.toast('Evidência de montagem exportada.');this.checkGoals();}
  openTechnical(){sessionStorage.setItem('cosmos-ds-technical-target',this.model.systemId);this.context.openModule('technical-operations');}
  checkGoals(){const p=this.model.progress(),checks=[['assemble-one',p.complete],['connect-flows',p.flows>=3],['diagnose-fault',p.repaired>=1]];for(const [id,done] of checks)if(done){const goal=WORKSHOP_GOALS.find(item=>item.id===id);if(this.context.profileStore.addXp(goal.xp,`space-workshop-${id}-${this.model.systemId}`))this.context.toast(`${goal.label}: +${goal.xp} XP.`);}}
  handleClick(event){const target=event.target.closest('[data-action]');if(!target)return;const action=target.dataset.action;if(action==='back')return this.context.onBack();if(action==='select-system')return this.selectSystem(target.dataset.system);if(action==='set-difficulty'){this.model.setDifficulty(target.dataset.difficulty);return this.restart();}if(action==='set-flow'){this.model.selectFlow(target.dataset.flow);return this.restart();}if(action==='select-component'){this.model.selectComponent(target.dataset.component);return this.restart();}if(action==='install-selected')return this.installSelected();if(action==='remove-selected')return this.removeSelected();if(action==='toggle-connection')return this.toggleConnection(target.dataset.link);if(action==='run-diagnostics')return this.runDiagnostics();if(action==='inject-fault')return this.injectFault();if(action==='repair-fault')return this.repairFault();if(action==='register-evidence')return this.registerEvidence();if(action==='export-evidence')return this.exportEvidence();if(action==='open-technical')return this.openTechnical();if(action==='reset-workshop'){const id=this.model.systemId,d=this.model.difficulty;this.model=new SpaceAssemblyModel(id,d);return this.restart();}if(action==='toggle-help'){this.help=!this.help;this.container.querySelector('.workshop-help')?.classList.toggle('open',this.help);return;}if(action==='toggle-log'){this.log=!this.log;this.container.querySelector('.workshop-log')?.classList.toggle('open',this.log);return;}if(action==='fullscreen')return this.container.querySelector('.workshop-stage')?.requestFullscreen?.();}
  handleKey(event){if(['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName))return;const key=event.key.toLowerCase();if(key==='i')this.installSelected();if(key==='t')this.runDiagnostics();if(key==='f')this.injectFault();if(key==='r')this.repairFault();if(['1','2','3'].includes(key)){this.model.selectFlow(WORKSHOP_FLOW_TYPES[Number(key)-1].id);this.restart();}}
}
export const createModule=()=>new SpaceWorkshopModule();
