/* Loja Virtual DS v0.9.6.0-RG — Benchmark DS Avançado */
const VERSION='0.9.6.0-RG';
const CORE_CACHE=`ds-store-core-v${VERSION}`;
const RUNTIME_CACHE='ds-store-runtime-v1';
const META_CACHE='ds-store-meta-v1';
const CORE=['./index.html','./demo/index.html','./demo/styles-core.css','./demo/styles-recovery.css','./demo/visual-recovery.js','./assets/runtime/recovery/avatar-three-quarter-hq.webp','./assets/runtime/recovery/avatar-front-hq.webp','./demo/boot.module.js','./demo/modules/shared.module.js','./demo/modules/renderer.module.js','./demo/renderer-profile.js','./demo/asset-transfer.js','./assets/compression/mesh-transfer-manifest.json','./demo/config-cache-memory.js','./demo/cache-memory-manager.js','./demo/performance-manager.js','./demo/graphics-mode-controller.js','./demo/config-data.js','./demo/catalog-data.js','./demo/equipment-data.js','./demo/vfx-data.js','./dist/ds-store-foundation.js'];
self.addEventListener('install',event=>{event.waitUntil(caches.open(CORE_CACHE).then(cache=>cache.addAll(CORE)).catch(()=>{}));self.skipWaiting()});
self.addEventListener('activate',event=>{event.waitUntil((async()=>{for(const key of await caches.keys())if(key.startsWith('ds-store-core-v')&&key!==CORE_CACHE)await caches.delete(key);await self.clients.claim()})())});
async function networkFirst(req,cacheName){const cache=await caches.open(cacheName);try{const res=await fetch(req);if(res.ok)await cache.put(req,res.clone());return res}catch(e){return (await cache.match(req))||Response.error()}}
async function staleWhileRevalidate(req,cacheName){const cache=await caches.open(cacheName),hit=await cache.match(req);const update=fetch(req).then(res=>{if(res.ok)cache.put(req,res.clone());return res}).catch(()=>null);return hit||await update||Response.error()}
async function cacheFirst(req,cacheName){const cache=await caches.open(cacheName),hit=await cache.match(req);if(hit)return hit;const res=await fetch(req);if(res.ok)await cache.put(req,res.clone());return res}
self.addEventListener('fetch',event=>{const req=event.request;if(req.method!=='GET')return;const url=new URL(req.url);if(req.mode==='navigate'){event.respondWith(networkFirst(req,CORE_CACHE).then(r=>r.ok?r:caches.match('./demo/index.html')));return}if(/\/(packs|config)\//.test(url.pathname)||/manifest\.json$/.test(url.pathname)){event.respondWith(networkFirst(req,META_CACHE));return}if(/\.(glb|glb\.gz|gz|ktx2|webp|avif|png|jpg|jpeg|svg|woff2?)$/i.test(url.pathname)){event.respondWith(cacheFirst(req,RUNTIME_CACHE));return}event.respondWith(staleWhileRevalidate(req,RUNTIME_CACHE))});
self.addEventListener('message',event=>{const d=event.data||{};if(d.type==='SKIP_WAITING')self.skipWaiting();if(d.type==='CLEAR_OLD_CACHES')event.waitUntil((async()=>{for(const k of await caches.keys())if(k.startsWith('ds-store-core-v')&&k!==CORE_CACHE)await caches.delete(k)})());if(d.type==='PURGE_RUNTIME')event.waitUntil(caches.delete(RUNTIME_CACHE))});
