import { GUIDED_TRAILS, GUIDED_TRAIL_BY_ID } from '../../data/guidedTrailDefinitions.js';
const clone=value=>structuredClone(value);
const stripComputed=value=>{const copy={...value};for(const key of ['currentStep','percent','total','completed','currentActiveMs','remainingMs','requiredEventMet','definition'])delete copy[key];return copy;};
export class GuidedTrailEngine {
  constructor(store,{customRepository=null,idleThresholdMs=180000}={}){this.store=store;this.customRepository=customRepository;this.idleThresholdMs=idleThresholdMs;}
  definitions(){const custom=this.customRepository?.list?.().map(item=>item.toGuidedDefinition())||[];return [...GUIDED_TRAILS.map(item=>clone(item)),...custom.map(item=>clone(item))];}
  definition(id){const official=GUIDED_TRAIL_BY_ID[id];if(official)return clone(official);const custom=this.customRepository?.getPlan?.(id);return custom?custom.toGuidedDefinition():null;}
  status(id){const definition=this.definition(id);if(!definition)return null;const saved=this.store.trail(id)||{};const completed=[...new Set(saved.completedStepIds||[])].filter(stepId=>definition.steps.some(step=>step.id===stepId));const index=Math.min(Math.max(0,Number(saved.currentIndex||0)),Math.max(0,definition.steps.length-1));const currentStep=definition.steps[index]||null;const currentActiveMs=Number(saved.stepActiveMs?.[currentStep?.id]||0);const minimumMs=Math.max(0,Number(currentStep?.minimumMinutes||0)*60000);const events=saved.eventTypesByStep?.[currentStep?.id]||[];const required=currentStep?.requiredEvent||'none';const requiredEventMet=required==='none'||events.includes(required)||(required==='manual-evidence'&&String(saved.evidenceByStep?.[currentStep?.id]||'').trim().length>=3);return {schema:'cosmos-ds-guided-trail-state-v2',trailId:id,state:saved.state||'READY',currentIndex:index,completedStepIds:completed,visitedModuleIds:[...new Set(saved.visitedModuleIds||[])],startedAt:saved.startedAt||null,completedAt:saved.completedAt||null,lastVisitedAt:saved.lastVisitedAt||null,currentOpenModuleId:saved.currentOpenModuleId||null,lastTick:Number(saved.lastTick||0),lastActivityAt:Number(saved.lastActivityAt||0),stepActiveMs:clone(saved.stepActiveMs||{}),eventTypesByStep:clone(saved.eventTypesByStep||{}),evidenceByStep:clone(saved.evidenceByStep||{}),earlyReleaseByStep:clone(saved.earlyReleaseByStep||{}),completedRecords:clone(saved.completedRecords||[]),events:clone(saved.events||[]),percent:Math.round(completed.length/definition.steps.length*100),currentStep,total:definition.steps.length,completed:completed.length,currentActiveMs,remainingMs:Math.max(0,minimumMs-currentActiveMs),requiredEventMet,definition};}
  start(id,at=Date.now()){const definition=this.definition(id);if(!definition)throw new Error('Trilha não encontrada.');const existing=this.status(id),now=Number(at);const state=existing?.state&&existing.state!=='READY'?stripComputed(existing):{trailId:id,state:'ACTIVE',currentIndex:0,completedStepIds:[],visitedModuleIds:[],startedAt:new Date(now).toISOString(),completedAt:null,lastVisitedAt:null,currentOpenModuleId:null,lastTick:now,lastActivityAt:now,stepActiveMs:{},eventTypesByStep:{},evidenceByStep:{},earlyReleaseByStep:{},completedRecords:[],events:[]};state.state='ACTIVE';state.lastTick=now;state.lastActivityAt=now;this.store.setTrail(id,state);this.store.setActive(id);this.log(id,'trail-started',{},now);return this.status(id);}
  active(){const id=this.store.snapshot().activeTrailId;return id?this.status(id):null;}
  rawActive(){const id=this.store.snapshot().activeTrailId;return id?this.store.trail(id):null;}
  log(id,type,detail={},at=Date.now()){const raw=this.store.trail(id)||{};const events=[...(raw.events||[]),{id:`evt-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,type,detail:clone(detail),at:new Date(at).toISOString()}].slice(-500);this.store.setTrail(id,{...raw,events});}
  pause(at=Date.now()){const active=this.active();if(!active)return null;this.tick(at);this.store.setTrail(active.trailId,{...stripComputed(this.status(active.trailId)),state:'PAUSED',currentOpenModuleId:null});this.store.setActive(null);this.log(active.trailId,'trail-paused',{},at);return this.status(active.trailId);}
  visitModule(moduleId,at=Date.now()){const active=this.active();if(!active)return null;this.tick(at);const raw=this.store.trail(active.trailId)||{},visited=[...new Set([...(raw.visitedModuleIds||[]),moduleId])];this.store.setTrail(active.trailId,{...raw,visitedModuleIds:visited,lastVisitedAt:new Date(at).toISOString(),currentOpenModuleId:moduleId,lastTick:Number(at),lastActivityAt:Number(at)});this.signal('module-opened',{moduleId},at);return this.status(active.trailId);}
  leaveModule(moduleId,at=Date.now()){const active=this.active();if(!active)return null;this.tick(at);const raw=this.store.trail(active.trailId)||{};if(raw.currentOpenModuleId===moduleId)this.store.setTrail(active.trailId,{...raw,currentOpenModuleId:null,lastTick:Number(at)});return this.status(active.trailId);}
  tick(at=Date.now()){const active=this.active();if(!active||active.state!=='ACTIVE')return active;const raw=this.store.trail(active.trailId)||{},now=Number(at),last=Number(raw.lastTick||now),delta=Math.max(0,Math.min(60000,now-last)),step=active.currentStep,idleFor=Math.max(0,now-Number(raw.lastActivityAt||now));const onTarget=raw.currentOpenModuleId===step?.moduleId;if(delta>0&&onTarget&&idleFor<this.idleThresholdMs){const map={...(raw.stepActiveMs||{})};map[step.id]=Number(map[step.id]||0)+delta;this.store.setTrail(active.trailId,{...raw,stepActiveMs:map,lastTick:now});}else if(now!==last)this.store.setTrail(active.trailId,{...raw,lastTick:now});return this.status(active.trailId);}
  activity(type='interaction',detail={},at=Date.now()){const active=this.active();if(!active||active.state!=='ACTIVE')return false;this.tick(at);const raw=this.store.trail(active.trailId)||{};if(raw.currentOpenModuleId!==active.currentStep?.moduleId)return false;this.store.setTrail(active.trailId,{...raw,lastActivityAt:Number(at),lastTick:Number(at)});this.signal(type==='interaction'?'interaction':type,detail,at);return true;}
  signal(type,detail={},at=Date.now()){const active=this.active();if(!active?.currentStep)return null;const raw=this.store.trail(active.trailId)||{},stepId=active.currentStep.id,map={...(raw.eventTypesByStep||{})},types=[...new Set([...(map[stepId]||[]),String(type)])];map[stepId]=types;const events=[...(raw.events||[]),{id:`evt-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,type:String(type),stepId,detail:clone(detail),at:new Date(at).toISOString()}].slice(-500);this.store.setTrail(active.trailId,{...raw,eventTypesByStep:map,events});return this.status(active.trailId);}
  setEvidence(text){const active=this.active();if(!active?.currentStep)return null;const raw=this.store.trail(active.trailId)||{},map={...(raw.evidenceByStep||{})};map[active.currentStep.id]=String(text||'').trim().slice(0,1200);this.store.setTrail(active.trailId,{...raw,evidenceByStep:map});if(map[active.currentStep.id].length>=3)this.signal('manual-evidence',{length:map[active.currentStep.id].length});return this.status(active.trailId);}
  authorizeEarlyRelease({code,reason,at=Date.now()}={}){const active=this.active(),trail=active?this.definition(active.trailId):null;if(!active?.currentStep||!trail?.custom)return {ok:false,reason:'Liberação antecipada disponível apenas em trilhas do professor.'};if(String(code||'').trim().toUpperCase()!==String(trail.teacherCode||'').toUpperCase())return {ok:false,reason:'Código do professor incorreto.'};const clean=String(reason||'').trim();if(clean.length<10)return {ok:false,reason:'Registre um motivo com pelo menos 10 caracteres.'};const raw=this.store.trail(active.trailId)||{},map={...(raw.earlyReleaseByStep||{})};map[active.currentStep.id]={reason:clean.slice(0,500),authorizedAt:new Date(at).toISOString(),codeVerified:true};this.store.setTrail(active.trailId,{...raw,earlyReleaseByStep:map});this.signal('early-release-authorized',{reason:map[active.currentStep.id].reason},at);return {ok:true,status:this.status(active.trailId)};}
  canCompleteCurrent(){const active=this.active();if(!active?.currentStep)return {ok:false,reason:'Nenhuma trilha ativa.'};if(!active.visitedModuleIds.includes(active.currentStep.moduleId))return {ok:false,reason:'Abra o laboratório indicado antes de registrar a etapa.'};if(active.remainingMs>0&&!active.earlyReleaseByStep?.[active.currentStep.id]){const minutes=Math.ceil(active.remainingMs/60000);return {ok:false,reason:`Permaneça em atividade por mais ${minutes} min nesta etapa ou solicite liberação registrada ao professor.`};}if(!active.requiredEventMet){const labels={interaction:'realize ao menos uma interação no laboratório','manual-evidence':'registre a evidência solicitada','module-opened':'abra o laboratório indicado'};return {ok:false,reason:`Antes de concluir, ${labels[active.currentStep.requiredEvent]||'cumpra o evento configurado'}.`};}return {ok:true};}
  completeCurrent(at=Date.now()){this.tick(at);const check=this.canCompleteCurrent();if(!check.ok)return check;const active=this.active(),definition=this.definition(active.trailId),step=active.currentStep,raw=this.store.trail(active.trailId)||{},completed=[...new Set([...(raw.completedStepIds||[]),step.id])],done=completed.length>=definition.steps.length,nextIndex=done?definition.steps.length-1:Math.min(active.currentIndex+1,definition.steps.length-1);const record={id:step.id,title:step.title,moduleId:step.moduleId,evidence:String(raw.evidenceByStep?.[step.id]||step.expected||step.evidence||'').slice(0,1200),activeMs:Number(raw.stepActiveMs?.[step.id]||0),events:clone(raw.eventTypesByStep?.[step.id]||[]),earlyRelease:clone(raw.earlyReleaseByStep?.[step.id]||null),completedAt:new Date(at).toISOString(),order:active.currentIndex+1};const next={...raw,state:done?'COMPLETED':'ACTIVE',currentIndex:nextIndex,completedStepIds:completed,completedAt:done?new Date(at).toISOString():null,currentOpenModuleId:done?null:raw.currentOpenModuleId,lastTick:Number(at),lastActivityAt:Number(at),completedRecords:[...(raw.completedRecords||[]).filter(item=>item.id!==step.id),record]};this.store.setTrail(active.trailId,next);if(done)this.store.setActive(null);this.log(active.trailId,'step-completed',{stepId:step.id,done},at);return {ok:true,done,status:this.status(active.trailId),completedStep:clone(step),record};}
  resume(id,at=Date.now()){const status=this.status(id);if(!status)throw new Error('Trilha não encontrada.');if(status.state==='COMPLETED')return status;this.store.setTrail(id,{...stripComputed(status),state:'ACTIVE',lastTick:Number(at),lastActivityAt:Number(at)});this.store.setActive(id);this.log(id,'trail-resumed',{},at);return this.status(id);}
  reset(id){this.store.reset(id);return this.status(id);}
  nextModule(){return this.active()?.currentStep?.moduleId||null;}
  followingModule(){const active=this.active();if(!active)return null;const definition=this.definition(active.trailId);return definition?.steps?.[active.currentIndex+1]?.moduleId||null;}
}
