import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { requireLiveAuthSession } from "./session-guard.ts";
import { createClient } from "jsr:@supabase/supabase-js@2.111.0";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const json=(body:unknown,status=200,extra:Record<string,string>={})=>new Response(JSON.stringify(body),{status,headers:{...cors,...extra,"content-type":"application/json","cache-control":"no-store"}});
const COMPLETION_EVENTS=new Set(['activity.completed','challenge.completed','lesson.completed','block.completed','daily.completed']);
const S=(v:unknown,n=500)=>String(v??'').trim().slice(0,n);
function ipOf(req:Request){const cf=S(req.headers.get('cf-connecting-ip'),128);if(cf)return cf;const real=S(req.headers.get('x-real-ip'),128);if(real)return real;const xs=S(req.headers.get('x-forwarded-for'),512).split(',').map(x=>x.trim()).filter(Boolean);return xs.length?S(xs[xs.length-1],128):null}
async function rate(db:any,key:string,limit:number,window:number,block:number){const{data,error}=await db.rpc('security_consume_rate_limit',{p_key:key,p_limit:limit,p_window_seconds:window,p_block_seconds:block});return error?{allowed:true,count:0,retry_after:0}:(data||{allowed:true,count:0,retry_after:0})}
async function signal(url:string,anon:string,auth:string,action:string,severity:string,payload:any){try{await fetch(`${url}/functions/v1/security-telemetry`,{method:'POST',headers:{'content-type':'application/json','apikey':anon,'Authorization':auth},body:JSON.stringify({action,severity,payload})});}catch(_){}}
async function accessTelemetry(db:any,url:string,anon:string,auth:string,userId:string,ip:string|null){if(!ip)return;const since=new Date(Date.now()-3600_000).toISOString();const{data}=await db.from('agv_core_security_events').select('id').eq('user_id',userId).eq('ip_address',ip).eq('category','access_security').gte('created_at',since).limit(1);if(!(data||[]).length)await signal(url,anon,auth,'session.check','info',{source:'agv-progress-event'});}
Deno.serve(async(req)=>{
 if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return json({error:'method_not_allowed'},405);
 try{
  const auth=req.headers.get('Authorization')||'',url=Deno.env.get('SUPABASE_URL')!,anon=Deno.env.get('SUPABASE_ANON_KEY')!,service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,ip=ipOf(req);
  const userClient=createClient(url,anon,{global:{headers:{Authorization:auth}}});const{data:{user},error:userError}=await userClient.auth.getUser();if(userError||!user)return json({error:'unauthorized'},401);
  const admin=createClient(url,service,{auth:{persistSession:false,autoRefreshToken:false}});const live=await requireLiveAuthSession(admin,auth,user.id);if(!live.ok)return json({error:live.error,detail:live.detail||null},live.status);const lim=await rate(admin,`progress:${user.id}:${ip||'noip'}`,120,60,120);if(lim.allowed===false){await signal(url,anon,auth,'client.rapid_requests','high',{source:'agv-progress-event',count:lim.count});return json({error:'rate_limited',retry_after:lim.retry_after||120},429,{'Retry-After':String(lim.retry_after||120)});}await accessTelemetry(admin,url,anon,auth,user.id,ip);
  const body=await req.json(),platformCode=String(body.platformId||'').trim(),activityId=body.activityId?String(body.activityId).trim():null,eventType=String(body.eventType||'').trim(),progress=body.progress===null||body.progress===undefined?null:Number(body.progress);if(!platformCode||!eventType)return json({error:'invalid_request'},400);if(progress!==null&&(!Number.isFinite(progress)||progress<0||progress>100))return json({error:'invalid_progress'},400);
  const{data:platform}=await admin.from('platforms').select('id,code').eq('code',platformCode).eq('active',true).maybeSingle();if(!platform)return json({error:'platform_not_registered'},404);
  if(activityId){const{data:activity}=await admin.from('activity_catalog').select('activity_id,reward_policy,metadata,active').eq('platform_id',platform.id).eq('activity_id',activityId).maybeSingle();if(!activity?.active)return json({error:'activity_not_registered'},404);const isCompletion=COMPLETION_EVENTS.has(eventType)||(progress!==null&&progress>=100);if(isCompletion&&activity.metadata?.client_progress_allowed!==true){await signal(url,anon,auth,'client.integrity_warning','high',{source:'agv-progress-event',reason:'completion_requires_server',platformCode,activityId,eventType});return json({error:'server_validation_required',message:'A conclusão desta atividade precisa ser validada pelo endpoint específico da plataforma.'},403);}}
  const{data,error}=await admin.rpc('record_core_progress_event',{p_user_id:user.id,p_platform_code:platformCode,p_activity_id:activityId,p_event_type:eventType,p_progress:progress,p_score:body.score??null,p_payload:body.payload&&typeof body.payload==='object'?body.payload:{},p_idempotency_key:String(body.idempotencyKey||''),p_occurred_at:new Date().toISOString()});if(error)return json({error:'progress_rejected',message:error.message},400);return json(data||{ok:true});
 }catch(error){return json({error:'invalid_request',message:String((error as Error)?.message||error)},400)}
});
