(()=>{
'use strict';
const cfg={supabaseUrl:'https://iresvqwyaqotghjssncg.supabase.co',publishableKey:'sb_publishable_9yUn07uD4XYySt1ynzZu-A_v8HSoSDO'};
const auth=window.AGVSession.create(cfg),$=id=>document.getElementById(id),SCHOOL='@escola.pr.gov.br';
const ROOT=new URL('../',location.href);
function safeReturnTo(raw){try{const value=String(raw||'').trim();if(!value||value.startsWith('//')||/^[a-z][a-z0-9+.-]*:/i.test(value))return 'index.html';const u=new URL(value,ROOT);if(u.origin!==ROOT.origin||!u.pathname.startsWith(ROOT.pathname))return 'index.html';const rel=`${u.pathname.slice(ROOT.pathname.length)}${u.search}${u.hash}`;if(/^auth\//.test(rel)||/^reset-password\//.test(rel))return 'index.html';return rel||'index.html';}catch{return 'index.html';}}
const params=new URLSearchParams(location.search),returnTo=safeReturnTo(params.get('returnTo'));
const destination=()=>new URL(returnTo,ROOT).href;
const oauthReturn=()=>{const u=new URL('auth/',ROOT);u.searchParams.set('returnTo',returnTo);return u.href;};
function msg(text='',ok=false){$('message').textContent=text;$('message').classList.toggle('ok',ok);}
async function profile(){const user=await auth.getUser();const rows=await auth.request(`/rest/v1/profiles?select=id,full_name,email,role,active,must_change_password&id=eq.${encodeURIComponent(user.id)}&limit=1`);const p=Array.isArray(rows)?rows[0]:null;if(!p)throw new Error('Conta autenticada, mas ainda não cadastrada no AGV.');if(!p.active)throw new Error('Seu acesso está inativo. Procure a equipe responsável.');return p;}
async function continueSession(){const p=await profile();if(p.must_change_password){sessionStorage.setItem('agv-auth-return-to',returnTo);location.replace(new URL('atividades/',ROOT).href);return;}location.replace(destination());}
async function restore(){const oauth=auth.consumeAuthRedirect();if(oauth?.handled&&oauth.error){msg(`Login Google não concluído: ${oauth.error}`);return;}const s=await auth.getSession();if(!s)return;if(oauth?.handled)msg('Google autenticado. Validando seu perfil…',true);try{await continueSession();}catch(err){console.error(err);await auth.signOut();msg(err.message||'Não foi possível validar seu acesso.');}}
$('login-form').addEventListener('submit',async e=>{e.preventDefault();const button=$('login-btn'),email=$('email').value.trim().toLowerCase(),password=$('password').value;if(!email.endsWith(SCHOOL))return msg(`Use o e-mail institucional ${SCHOOL}.`);if(!password)return msg('Informe sua senha. No primeiro acesso do aluno, use o CGM.');button.disabled=true;msg('Entrando…');try{try{await auth.signIn(email,password);}catch(first){if(!/^\d{6,12}$/.test(password))throw first;msg('Validando primeiro acesso…');const out=await auth.signUpStudent(email,password,oauthReturn());if(!out?.access_token)await auth.signIn(email,password);}await continueSession();}catch(err){console.error(err);await auth.signOut();msg('Não foi possível entrar. Confira e-mail e senha. Aluno no primeiro acesso: use o CGM.');}finally{button.disabled=false;}});
$('google-btn').addEventListener('click',()=>{const b=$('google-btn');b.disabled=true;msg('Abrindo o Google…');try{auth.signInWithOAuth('google',oauthReturn());}catch(err){console.error(err);b.disabled=false;msg('Não foi possível iniciar o Google agora.');}});
$('forgot-btn').addEventListener('click',()=>{$('recovery-email').value=$('email').value.trim().toLowerCase();$('login-form').classList.add('hidden');$('recovery').classList.remove('hidden');$('recovery-email').focus();});
$('recovery-cancel').addEventListener('click',()=>{$('recovery').classList.add('hidden');$('login-form').classList.remove('hidden');});
$('recovery-send').addEventListener('click',async()=>{const b=$('recovery-send'),email=$('recovery-email').value.trim().toLowerCase(),m=$('recovery-message');m.textContent='';m.classList.remove('ok');if(!email.endsWith(SCHOOL)){m.textContent=`Use seu e-mail institucional ${SCHOOL}.`;return;}b.disabled=true;m.textContent='Enviando…';try{await auth.resetPasswordForEmail(email,new URL('reset-password/',ROOT).href);m.textContent='Se o e-mail estiver cadastrado, o link de recuperação foi enviado.';m.classList.add('ok');}catch(err){console.error(err);m.textContent=err?.status===429?'Muitas tentativas. Aguarde alguns minutos.':'Não foi possível enviar agora. Tente novamente.';}finally{b.disabled=false;}});
restore();
})();