import { WORLD_BY_ID,VEHICLE_BY_ID,PLANETARY_MISSIONS } from '../../data/lunarMarsRemasterSystems.js';
const clamp=(v,min,max)=>Math.min(max,Math.max(min,v));
export class PlanetaryExplorationModel{
constructor({worldId='moon'}={}){this.worldId=worldId;this.vehicleId='astronaut';this.cameraId='third-person';this.position={x:7,y:1.8,z:10};this.heading=.35;this.pitch=-.12;this.energy=100;this.oxygen=100;this.distanceKm=0;this.samples=0;this.mappedSectors=new Set();this.armDeployed=false;this.beacon=false;this.storm=0;this.state='EXPLORING';this.completed=new Set();this.elapsed=0;}
setWorld(id){if(!WORLD_BY_ID[id])return false;this.worldId=id;this.vehicleId='astronaut';this.cameraId='third-person';this.position={x:7,y:WORLD_BY_ID[id].gravity<2?1.8:1.3,z:10};this.heading=.35;this.pitch=-.12;this.energy=100;this.oxygen=100;this.distanceKm=0;this.samples=0;this.mappedSectors.clear();this.armDeployed=false;this.beacon=false;this.storm=0;this.state='EXPLORING';this.completed.clear();return true;}
setVehicle(id){const vehicle=VEHICLE_BY_ID[id];if(!vehicle?.worlds.includes(this.worldId))return false;this.vehicleId=id;this.cameraId=id==='astronaut'?'third-person':id==='mars-drone'?'drone':'vehicle';return true;}
setCamera(id){this.cameraId=id;return true;}
complete(id){if(this.completed.has(id))return false;this.completed.add(id);return true;}
injectStorm(){if(this.worldId!=='mars')return false;this.storm=1;this.state='STORM';return true;}
recoverStorm(){if(this.storm<=0)return false;this.storm=0;this.state='EXPLORING';this.complete('mars-storm');return true;}
deployArm(){if(this.vehicleId!=='mars-rover')return false;this.armDeployed=!this.armDeployed;return true;}
collectSample(){if(this.worldId==='mars'&&this.vehicleId==='mars-rover'&&!this.armDeployed)return {ok:false,reason:'Abra o braço robótico antes da coleta.'};this.samples++;this.energy=clamp(this.energy-1.6,0,100);if(this.worldId==='moon'&&this.samples>=2)this.complete('moon-sample');if(this.worldId==='mars')this.complete('mars-arm');return {ok:true,count:this.samples};}
mapSector(){if(this.vehicleId!=='mars-drone')return {ok:false,reason:'Use o drone para mapear setores.'};const id=`S-${Math.floor(this.position.x/24)}-${Math.floor(this.position.z/24)}`;this.mappedSectors.add(id);this.energy=clamp(this.energy-3,0,100);if(this.mappedSectors.size>=3)this.complete('mars-drone');return {ok:true,count:this.mappedSectors.size};}
installBeacon(){if(this.worldId!=='moon')return false;this.beacon=true;this.complete('moon-beacon');return true;}
inspectModule(){if(this.worldId!=='moon')return false;this.cameraId='module-interior';this.complete('moon-module');return true;}
step(input={},dt=.016){dt=clamp(dt,0,.05);this.elapsed+=dt;const world=WORLD_BY_ID[this.worldId],vehicle=VEHICLE_BY_ID[this.vehicleId]||VEHICLE_BY_ID.astronaut;const lookX=Number(input.lookX)||0,lookY=Number(input.lookY)||0;this.heading+=lookX*.018;this.pitch=clamp(this.pitch+lookY*.012,-1.15,.85);const forward=Number(input.forward)||0,strafe=Number(input.strafe)||0,lift=Number(input.lift)||0;const speed=vehicle.speed*(input.boost?1.8:1)*(this.storm>.4?.55:1);const dx=(Math.sin(this.heading)*forward+Math.cos(this.heading)*strafe)*speed*dt,dz=(Math.cos(this.heading)*forward-Math.sin(this.heading)*strafe)*speed*dt;const ox=this.position.x,oz=this.position.z;this.position.x=clamp(this.position.x+dx,-1600,1600);this.position.z=clamp(this.position.z+dz,-1600,1600);this.position.y=this.vehicleId==='mars-drone'?clamp(this.position.y+lift*7*dt,2,38):(world.gravity<2?1.8:1.3);this.distanceKm+=Math.hypot(this.position.x-ox,this.position.z-oz)/1000;const moving=Math.abs(forward)+Math.abs(strafe)+Math.abs(lift);this.energy=clamp(this.energy-moving*vehicle.energyUse*dt-this.storm*.025,0,100);if(this.vehicleId==='astronaut')this.oxygen=clamp(this.oxygen-.018*dt*(1+moving*.5),0,100);if(this.worldId==='moon'&&this.vehicleId==='lunar-rover'&&this.distanceKm>=1.2)this.complete('moon-rover');if(this.worldId==='mars'&&this.vehicleId==='mars-rover'&&this.distanceKm>=1.8)this.complete('mars-route');if(this.energy<=0)this.state='POWER_SAFE';return this.telemetry();}
telemetry(){return {worldId:this.worldId,vehicleId:this.vehicleId,cameraId:this.cameraId,position:{...this.position},heading:this.heading,pitch:this.pitch,energy:this.energy,oxygen:this.oxygen,distanceKm:this.distanceKm,samples:this.samples,mappedSectors:this.mappedSectors.size,armDeployed:this.armDeployed,beacon:this.beacon,storm:this.storm,state:this.state,elapsed:this.elapsed,completed:[...this.completed],missionTotal:PLANETARY_MISSIONS[this.worldId].length,gravity:WORLD_BY_ID[this.worldId].gravity};}
}
