(function(){
  'use strict';
  const META={
    title:'Desafio DS',version:'22.0.0',status:'estável',createdAt:'2026',updatedAt:'2026-07-29',
    lead:'Professor Gabriel',institution:'Colégio Estadual Alberto Gomes Veiga',program:'Técnico em Desenvolvimento de Sistemas',
    ai:{tool:'ChatGPT',provider:'OpenAI',model:'GPT-5.6 Thinking',mode:'Raciocínio e desenvolvimento assistido',validation:'Professor Gabriel'},
    changes:[
      {version:'22.0.0',date:'29/07/2026',title:'EduAuth Offline',items:['Substituídas senhas fixas por autorizações temporárias vinculadas ao contexto.','Adicionados PIN coletivo, PIN por sessão e autorização assinada em ambiente de desenvolvimento.','Adicionados códigos-base públicos, QR Code opcional, limite de tentativas e auditoria local.','Gerados manifest, registro de ações, vetores de teste e template de provisionamento.']},
      {version:'21.0.0',date:'29/07/2026',title:'Perfis, entrega e contexto escolar',items:['Adicionado perfil local criptografado em IndexedDB.','Adicionados backup, importação, bloqueio, expiração e recuperação administrativa por arquivo.','Adicionada Central de Ajuda, créditos, horário escolar e catálogo educacional.','Aprimorada a Central de Conclusão e Entrega do Modo Guiado.']},
      {version:'20.0.0',date:'29/07/2026',title:'Diagnóstico e responsividade',items:['Separados os modos competitivo e diagnóstico completo.','Revisado o layout responsivo e ampliada a trilha de Programação Mobile.']},
      {version:'19.0.0',date:'28/07/2026',title:'Modo Guiado',items:['Adicionado o Modo Guiado por turma, disciplina e código de aula.']}
    ]
  };
  const TOOLS=[
    {id:'lab-virtual',name:'Lab Virtual DS',description:'Laboratórios, simuladores e ferramentas de diferentes áreas de Desenvolvimento de Sistemas.',status:'configurar link',url:'',areas:['Programação','Hardware','Redes']},
    {id:'diagnostico-edu',name:'Diagnóstico Edu',description:'Diagnóstico de aprendizagem com indicadores e explicações adaptadas.',status:'em desenvolvimento',url:'',areas:['Diagnóstico','Aprendizagem']},
    {id:'recuperacao',name:'Recuperação Adaptada',description:'Atividades com explicações progressivas e recursos de apoio.',status:'em desenvolvimento',url:'',areas:['Acessibilidade','Recuperação']},
    {id:'ctf',name:'CTF de Cibersegurança',description:'Desafios educativos de segurança, criptografia e investigação controlada.',status:'em desenvolvimento',url:'',areas:['Segurança','Criptografia']}
  ];
  const CAREERS=[
    ['Desenvolvimento web','HTML, CSS, JavaScript, APIs, Git e acessibilidade.','Front-end, manutenção de sites, full-stack júnior.'],
    ['Desenvolvimento mobile','Responsividade, experiência de toque, Kotlin, Swift e soluções multiplataforma.','Aplicações mobile, testes e prototipação.'],
    ['Suporte e infraestrutura','Hardware, sistemas operacionais, redes, diagnóstico e atendimento.','Suporte técnico, help desk e field service.'],
    ['Testes e qualidade','Identificação de erros, casos de teste, documentação e validação.','QA, testes manuais e suporte à implantação.'],
    ['Análise de sistemas','Requisitos, processos, protótipos, UML e validação com usuários.','Análise de requisitos e documentação.']
  ];
  function escapeHtml(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
  function inject(){if(document.getElementById('platformUtilityDock'))return;const dock=document.createElement('nav');dock.id='platformUtilityDock';dock.className='platform-utility-dock';dock.setAttribute('aria-label','Ajuda e informações');dock.innerHTML='<button type="button" data-shell="help">Ajuda</button><button type="button" data-shell="tools">Ferramentas</button><button type="button" data-shell="about">Sobre</button>';document.body.appendChild(dock);const modal=document.createElement('div');modal.id='platformShellModal';modal.className='modal-overlay hidden';modal.setAttribute('role','dialog');modal.setAttribute('aria-modal','true');modal.innerHTML='<div class="modal-card platform-shell-card"><div class="platform-shell-head"><div><span class="modal-kicker">DESAFIO DS</span><h2 id="platformShellTitle">Informações</h2></div><button id="platformShellClose" class="btn ghost" type="button">Fechar</button></div><div id="platformShellContent"></div></div>';document.body.appendChild(modal);dock.querySelectorAll('[data-shell]').forEach(button=>button.addEventListener('click',()=>open(button.dataset.shell)));modal.querySelector('#platformShellClose').addEventListener('click',close);modal.addEventListener('click',event=>{if(event.target===modal)close();});const footer=document.createElement('footer');footer.className='credits-footer';footer.innerHTML=`Idealização e desenvolvimento pedagógico: <strong>${META.lead}</strong> · Versão ${META.version} · Atualizado em ${META.updatedAt}`;document.body.appendChild(footer);}
  function open(section){const modal=document.getElementById('platformShellModal'),title=document.getElementById('platformShellTitle'),content=document.getElementById('platformShellContent');modal.classList.remove('hidden');document.body.classList.add('modal-open');if(section==='help'){title.textContent='Central de ajuda';content.innerHTML=helpHtml();bindHelp(content);}else if(section==='tools'){title.textContent='Ferramentas e carreiras';content.innerHTML=toolsHtml();}else{title.textContent='Sobre, créditos e versões';content.innerHTML=aboutHtml();}}
  function close(){document.getElementById('platformShellModal')?.classList.add('hidden');document.body.classList.remove('modal-open');}
  function helpHtml(){return `<div class="shell-tabs"><button class="active" data-help-tab="delivery" type="button">Entrega</button><button data-help-tab="classroom" type="button">Classroom</button><button data-help-tab="github" type="button">GitHub/VS Code</button><button data-help-tab="storage" type="button">Armazenamento</button></div><div id="shellHelpBody">${deliveryHelp()}</div>`;}
  function bindHelp(root){
    const bindLinks=()=>root.querySelectorAll('[data-open-url]').forEach(button=>button.addEventListener('click',()=>window.open(button.dataset.openUrl,'_blank','noopener,noreferrer')));
    root.querySelectorAll('[data-help-tab]').forEach(button=>button.addEventListener('click',()=>{root.querySelectorAll('[data-help-tab]').forEach(b=>b.classList.toggle('active',b===button));const body=root.querySelector('#shellHelpBody');body.innerHTML=button.dataset.helpTab==='classroom'?classroomHelp():button.dataset.helpTab==='github'?githubHelp():button.dataset.helpTab==='storage'?storageHelp():deliveryHelp();bindLinks();}));bindLinks();
  }
  const deliveryHelp=()=>`<div class="help-flow"><h3>Entrega rápida</h3><ol><li>Conclua e revise a atividade.</li><li>Exporte o arquivo.</li><li>Localize-o em Downloads.</li><li>Abra a atividade correta no Classroom.</li><li>Anexe o arquivo ou link.</li><li>Selecione Entregar e confirme.</li></ol><p>A plataforma registra a exportação e a abertura do Classroom, mas não confirma a entrega sem API oficial.</p></div>`;
  const classroomHelp=()=>`<div class="help-flow"><h3>Como entregar no Classroom</h3><ol><li>Confirme a conta escolar correta.</li><li>Abra a turma e a atividade indicada.</li><li>Entre em <strong>Seu trabalho</strong>.</li><li>Escolha <strong>Adicionar ou criar</strong>.</li><li>Selecione Arquivo ou Link.</li><li>Aguarde o carregamento e confira o nome.</li><li>Clique em <strong>Entregar</strong> e confirme.</li></ol><p>Se não houver anexo, siga a orientação do professor para marcar como concluída.</p></div>`;
  const githubHelp=()=>`<div class="help-flow"><h3>Projeto de programação</h3><ol><li>Baixe e extraia o ZIP.</li><li>Leia o README.</li><li>Abra a pasta no VS Code.</li><li>Teste antes de publicar.</li><li>Crie ou abra o repositório no GitHub.</li><li>Envie os arquivos e escreva uma mensagem de commit clara.</li><li>Copie o link e anexe no Classroom quando solicitado.</li></ol><div class="help-actions"><button class="btn secondary" type="button" data-open-url="https://github.com/">Abrir GitHub</button><button class="btn secondary" type="button" data-open-url="https://vscode.dev/">Abrir VS Code Web</button></div><p>Nunca publique senhas, tokens, arquivos .env ou dados pessoais.</p></div>`;
  const storageHelp=()=>`<div class="help-flow"><h3>Upload não funciona?</h3><ol><li>Confira se o arquivo existe e abre normalmente.</li><li>Verifique a conta escolar conectada.</li><li>Teste a internet.</li><li>Confira o espaço do Drive, Gmail e Google Fotos.</li><li>Verifique lixeiras e anexos grandes.</li><li>Antes de excluir, faça cópia dos arquivos importantes.</li></ol><p>A conta escolar pode possuir 5 GB ou, no máximo, 15 GB. A plataforma não exclui arquivos automaticamente.</p><div class="notice-card">No Google Fotos, confirme a conta ativa e desative o backup da conta escolar antes de excluir imagens sincronizadas.</div></div>`;
  function aboutHtml(){return `<section class="about-hero"><h3>${META.title}</h3><p>Plataforma educacional idealizada e desenvolvida pelo professor Gabriel com apoio de inteligência artificial, testes em sala e colaboração de estudantes e professores.</p></section><div class="about-grid"><article><h3>Créditos</h3><p><strong>Idealização, desenvolvimento pedagógico, coordenação e validação:</strong> ${META.lead}.</p><p><strong>Contexto:</strong> ${META.program}, ${META.institution}.</p><p><strong>Colaboração:</strong> estudantes do 1º, 2º e 3º DS, Técnico Subsequente noturno e professores colaboradores.</p></article><article><h3>Assistência tecnológica</h3><p>${META.ai.tool} — ${META.ai.model}</p><p>${META.ai.mode}. Uso em análise, programação, revisão, correção e documentação.</p><p>A direção pedagógica e a validação final são humanas.</p></article></div><h3>Histórico de versões</h3><div class="version-list">${META.changes.map(item=>`<details ${item.version===META.version?'open':''}><summary><strong>v${item.version}</strong> · ${item.date} — ${escapeHtml(item.title)}</summary><ul>${item.items.map(change=>`<li>${escapeHtml(change)}</li>`).join('')}</ul></details>`).join('')}</div><div class="limitations-card"><h3>Limitações do modo totalmente front-end</h3><ul><li>O navegador controla a persistência local.</li><li>Não existe confirmação real do Classroom sem API e autenticação.</li><li>Não há sincronização automática entre dispositivos.</li><li>O perfil exportado precisa ser guardado pelo aluno.</li><li>A recuperação exige o arquivo administrativo correto.</li></ul></div>`;}
  function toolsHtml(){return `<section class="tool-catalog-intro"><h3>Conheça outras ferramentas</h3><p>Os projetos aparecem com o estado real. Uma ferramenta sem link configurado não é apresentada como disponível.</p></section><div class="tool-catalog-grid">${TOOLS.map(tool=>`<article><span class="tool-status">${escapeHtml(tool.status)}</span><h3>${escapeHtml(tool.name)}</h3><p>${escapeHtml(tool.description)}</p><small>${tool.areas.map(escapeHtml).join(' · ')}</small>${tool.url?`<button class="btn secondary full" type="button" data-tool-url="${escapeHtml(tool.url)}">Abrir ferramenta</button>`:'<button class="btn ghost full" type="button" disabled>Link ainda não configurado</button>'}</article>`).join('')}</div><h3>Carreiras relacionadas</h3><p class="career-note">Estas são conexões educacionais gerais. Vagas atuais precisam ser verificadas novamente em fontes oficiais.</p><div class="career-path-grid">${CAREERS.map(([title,skills,roles])=>`<article><h3>${escapeHtml(title)}</h3><p>${escapeHtml(skills)}</p><strong>${escapeHtml(roles)}</strong></article>`).join('')}</div><div class="notice-card">As oportunidades mudam rapidamente. Sempre confirme prazo, requisitos e candidatura na fonte oficial.</div>`;}
  function init(){inject();}
  window.DS_PlatformShell={open,close,meta:META};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
