import fs from 'node:fs';import path from 'node:path';import {fileURLToPath,pathToFileURL} from 'node:url';
const __dirname=path.dirname(fileURLToPath(import.meta.url)),root=path.resolve(__dirname,'..');
const vale=JSON.parse(fs.readFileSync(path.join(root,'games/mundo-plataforma-ds-360/region.json'),'utf8')).region;
const villageData=JSON.parse(fs.readFileSync(path.join(root,'games/mundo-plataforma-ds-360/village.json'),'utf8'));const village=villageData.region;
const game=fs.readFileSync(path.join(root,'games/mundo-plataforma-ds-360/game.js'),'utf8');const render=fs.readFileSync(path.join(root,'games/mundo-plataforma-ds-360/render.mjs'),'utf8');const app=fs.readFileSync(path.join(root,'app.js'),'utf8');const sw=fs.readFileSync(path.join(root,'sw.js'),'utf8');const profiles=JSON.parse(fs.readFileSync(path.join(root,'game-profiles.json'),'utf8'));const learning=JSON.parse(fs.readFileSync(path.join(root,'education/game-learning.json'),'utf8'));const version=JSON.parse(fs.readFileSync(path.join(root,'version.json'),'utf8'));
const {Mundo360Simulation}=await import(pathToFileURL(path.join(root,'games/mundo-plataforma-ds-360/simulation.mjs')).href+'?v='+Date.now());
const items=[];const ok=(name,cond,detail='')=>items.push({name,passed:!!cond,detail});
const allIds=[];for(const key of ['platforms','movingPlatforms','obstacles','hazards','collectibles','beacons','checkpoints','enemies','npcs','interactables'])for(const x of village[key]||[])allIds.push(x.id);
ok('schema da Vila',villageData.schemaVersion===1);ok('nome Vila Tecnológica',village.name.includes('Vila Tecnológica'));ok('região marcada como village',village.kind==='village');ok('mundo da Vila 80×72',village.size[0]===80&&village.size[2]===72);ok('4 setores na Vila',village.sectors.length===4);ok('Oficina presente',village.buildings.some(x=>x.id==='building-workshop'));ok('Estação de Dados presente',village.buildings.some(x=>x.id==='building-data'));ok('Centro de Rede presente',village.buildings.some(x=>x.id==='building-core'));ok('3 NPCs',village.npcs.length===3);ok('Lia presente',village.npcs.some(x=>x.id==='lia'));ok('Ivo presente',village.npcs.some(x=>x.id==='ivo'));ok('Dara presente',village.npcs.some(x=>x.id==='dara'));ok('8 interações',village.interactables.length===8);ok('3 módulos de oficina',village.interactables.filter(x=>x.type==='repair').length===3);ok('3 relés',village.interactables.filter(x=>x.type==='relay').length===3);ok('terminal de upload',village.interactables.some(x=>x.type==='data-terminal'));ok('núcleo da vila',village.interactables.some(x=>x.type==='core'));ok('3 missões',village.missions.length===3);ok('4 pacotes de dados',village.collectibles.length===4);ok('4 checkpoints',village.checkpoints.length===4);ok('2 plataformas móveis',village.movingPlatforms.length===2);ok('IDs da Vila únicos',new Set(allIds).size===allIds.length,`${allIds.length} IDs`);
const within=pos=>Math.abs(pos[0])<village.size[0]/2&&Math.abs(pos[2])<village.size[2]/2;const inside=(pos,o,pad=.42)=>Math.abs(pos[0]-o.position[0])<=o.size[0]/2+pad&&Math.abs(pos[2]-o.position[2])<=o.size[2]/2+pad;
for(const npc of village.npcs){ok(`${npc.id} dentro da Vila`,within(npc.position));ok(`${npc.id} não nasce em parede`,!village.obstacles.some(o=>inside(npc.position,o)));}
for(const it of village.interactables){ok(`${it.id} dentro da Vila`,within(it.position));ok(`${it.id} acessível fora de parede`,!village.obstacles.some(o=>inside(it.position,o)));}
for(const cp of village.checkpoints){ok(`${cp.id} dentro da Vila`,within(cp.position));ok(`${cp.id} fora de parede`,!village.obstacles.some(o=>inside(cp.position,o)));ok(`${cp.id} fora de perigo`,!village.hazards.some(h=>inside(cp.position,h,.5)));}
function supported(pos){return village.platforms.some(p=>Math.abs(pos[0]-p.position[0])<=p.size[0]/2&&Math.abs(pos[2]-p.position[2])<=p.size[2]/2&&pos[1]>=p.position[1]+p.size[1]/2&&pos[1]<=p.position[1]+p.size[1]/2+1.5)}
for(const c of village.collectibles)ok(`${c.id} apoiado em plataforma`,supported(c.position));
for(const b of village.buildings){ok(`${b.id} tem porta`,Array.isArray(b.door?.position)&&b.door.position.length===3);ok(`${b.id} cabe na região`,within(b.position));}
const world={schemaVersion:2,regions:[vale,village]},sim=new Mundo360Simulation(world);ok('mundo começa na Região 1',sim.regionIndex===0&&sim.region.id===vale.id);ok('save do mundo usa schema 2',sim.snapshot().schemaVersion===2);ok('mundo declara duas regiões',sim.progress().totalRegions===2);
for(const c of vale.collectibles)sim.collected.add(c.id);for(const b of vale.beacons)sim.beacons.add(b.id);sim.player.pos={x:vale.portal.position[0],y:vale.portal.position[1],z:vale.portal.position[2]};sim.player.vel={x:0,y:0,z:0};sim.tick(0,{});ok('Portal Nexus leva à Vila',sim.regionIndex===1&&sim.region.id===village.id);ok('transição marca Vale concluído',sim.valeCompleted===true);ok('transição gera region-change',sim.consumeEvents().some(e=>e.type==='region-change'));ok('Vila inicia na missão 1',sim.quest.stage===0&&sim.progress().mission===1);ok('portal final começa fechado',sim.portalOpen()===false);
const pos=(list,id)=>list.find(x=>x.id===id).position;const go=(p,interact=false)=>{sim.player.pos={x:p[0],y:p[1],z:p[2]};sim.player.vel={x:0,y:0,z:0};sim.invulnerable=9;sim.tick(0,{interact});};
// gating
const gate=new Mundo360Simulation(world);for(const c of vale.collectibles)gate.collected.add(c.id);for(const b of vale.beacons)gate.beacons.add(b.id);gate.player.pos={x:0,y:1.25,z:0};gate.tick(0,{});gate.player.pos={x:pos(village.interactables,'repair-a')[0],y:pos(village.interactables,'repair-a')[1],z:pos(village.interactables,'repair-a')[2]};gate.player.vel={x:0,y:0,z:0};gate.tick(0,{interact:true});ok('módulo não ativa antes de falar com Lia',gate.quest.activated.size===0);
// mission 1
go(pos(village.npcs,'lia'),true);ok('Lia inicia missão 1',sim.quest.stage===1);for(const id of ['repair-a','repair-b','repair-c'])go(pos(village.interactables,id),true);ok('3 módulos podem ser ativados',sim.quest.activated.size===3);ok('oficina pede retorno à Lia',sim.quest.stage===2);go(pos(village.npcs,'lia'),true);ok('missão 1 conclui e libera Ivo',sim.quest.stage===3&&sim.progress().mission===2);
// mission 2
go(pos(village.npcs,'ivo'),true);ok('Ivo libera coleta de dados',sim.quest.stage===4);for(const c of village.collectibles)go(c.position,false);ok('4 pacotes podem ser coletados',sim.collected.size===4);ok('coleta total libera upload',sim.quest.stage===5);go(pos(village.interactables,'data-terminal'),true);ok('upload conclui missão 2',sim.quest.uploaded===true&&sim.quest.stage===6&&sim.progress().mission===3);
// mission 3
go(pos(village.npcs,'dara'),true);ok('Dara libera relés',sim.quest.stage===7);for(const id of ['relay-west','relay-east','relay-north'])go(pos(village.interactables,id),true);ok('3 relés podem ser ativados',sim.quest.relays.size===3);ok('relés liberam Núcleo',sim.quest.stage===8);go(pos(village.interactables,'network-core'),true);ok('Núcleo libera portal final',sim.quest.stage===9&&sim.portalOpen());go(village.portal.position,false);ok('Portal de Continuidade conclui campanha',sim.completed===true);ok('vitória final gera evento',sim.consumeEvents().some(e=>e.type==='victory'));
// snapshot current
const snap=sim.snapshot(),restored=new Mundo360Simulation(world);ok('restore schema 2 aceita campanha concluída',restored.restore(snap));ok('restore preserva Região 2',restored.regionIndex===1);ok('restore preserva 4 dados',restored.collected.size===4);ok('restore preserva 3 reparos',restored.quest.activated.size===3);ok('restore preserva 3 relés',restored.quest.relays.size===3);ok('restore preserva estágio 9',restored.quest.stage===9);ok('restore preserva conclusão final',restored.completed===true);
// migration legacy incomplete
const legacyIncomplete={schemaVersion:1,lives:2,score:700,collected:[vale.collectibles[0].id],beacons:[],checkpoint:{id:'spawn',position:vale.spawn},completed:false,player:{position:vale.spawn}},migA=new Mundo360Simulation(world);ok('migra save v0.38.1 incompleto',migA.restore(legacyIncomplete));ok('save incompleto continua no Vale',migA.regionIndex===0&&!migA.valeCompleted&&migA.collected.size===1);ok('save migrado passa a schema 2',migA.snapshot().schemaVersion===2);
// migration legacy complete
const legacyComplete={schemaVersion:1,lives:3,score:2500,collected:vale.collectibles.map(x=>x.id),beacons:vale.beacons.map(x=>x.id),checkpoint:{id:'cp-n',position:[0,.05,-12]},completed:true,player:{position:[0,1.25,0]}},migB=new Mundo360Simulation(world);ok('migra save v0.38.1 concluído',migB.restore(legacyComplete));ok('save concluído entra direto na Vila',migB.regionIndex===1&&migB.valeCompleted);ok('migração não marca campanha nova como concluída',migB.completed===false);ok('migração começa missão da Vila em 1',migB.quest.stage===0&&migB.progress().mission===1);ok('migração gera evento informativo',migB.consumeEvents().some(e=>e.type==='migration'));
// legacy compatibility
const legacySim=new Mundo360Simulation(vale);ok('modo legado ainda usa schema 1',legacySim.snapshot().schemaVersion===1);for(const c of vale.collectibles)legacySim.collected.add(c.id);for(const b of vale.beacons)legacySim.beacons.add(b.id);legacySim.player.pos={x:0,y:1.25,z:0};legacySim.tick(0,{});ok('modo legado ainda conclui no Portal Nexus',legacySim.completed===true);
// rendering / integration
ok('render troca de região sem recarregar runtime',render.includes('setRegion(region)')&&render.includes('sim.region.id!==this.region.id'));ok('render cria interiores leves da Vila',render.includes('#villageGround')&&render.includes('building-workshop')===false&&render.includes('region.buildings'));ok('render possui NPC meshes',render.includes('this.npcMeshes'));ok('render possui terminais interativos',render.includes('this.interactionMeshes'));ok('perfil baixo reduz luz/decor',render.includes("this.quality==='baixo'"));ok('portal consulta simulação',render.includes('sim.portalOpen()'));ok('game carrega village.json',game.includes("'./village.json'"));ok('tecla E interage',game.includes("e.code==='KeyE'"));ok('touch possui interact',game.includes("a==='interact'"));ok('gamepad possui interact',game.includes('interact:!!p.buttons[2]'));ok('ready declara 2 regiões',game.includes('regions:2')&&game.includes('village:true'));ok('HUD alterna Dados/Missão',game.includes("orbsLabel').textContent='Dados'")&&game.includes("beaconsLabel').textContent='Missão'"));ok('ponte envia region-change',game.includes("post('region-change'"));ok('ponte envia mission',game.includes("post('mission'"));
ok('runtime wrapper reconhece 2 regiões',app.includes("#summary={region:1,regions:2")&&app.includes("regions:2,mode360:true,village:true"));ok('runtime wrapper recebe region-change',app.includes("type==='progress'||type==='region-change'||type==='mission'"));ok('catálogo marca Fase 7.23',app.includes("phase:'Fase 7.23 · v0.38.2'")&&app.includes('"releasePhase": 7.23'));ok('perfil externo inclui interação',profiles['mundo-plataforma-ds-360']?.keyActions?.KeyE==='interact');ok('perfil externo cita Vila',profiles['mundo-plataforma-ds-360']?.options?.campanha?.includes('Vila Tecnológica'));ok('ficha educacional cita 3 missões',learning['mundo-plataforma-ds-360']?.stageLabel?.includes('3 missões'));ok('progressão educacional inclui Oficina',learning['mundo-plataforma-ds-360']?.progression?.some(x=>x.includes('Oficina')));ok('versão pública v0.38.2',version.version==='0.38.2'&&version.phase.includes('Fase 7.23'));ok('Service Worker v0.38.2',sw.includes("const VERSION = '0.38.2'"));ok('Vila no cache offline',sw.includes("'./games/mundo-plataforma-ds-360/village.json'"));
for(const f of ['logo.svg','preview-01.svg','preview-02.svg']){const q=path.join(root,'media/games/mundo-plataforma-ds-360',f);ok(`mídia ${f}`,fs.existsSync(q));if(fs.existsSync(q)){const t=fs.readFileSync(q,'utf8');ok(`acessibilidade ${f}`,t.includes('role="img"')&&t.includes('aria-label=')&&t.length>500,`${t.length} bytes`);}}
const passed=items.filter(x=>x.passed).length,failed=items.length-passed;const result={suite:'Mundo Plataforma DS 360 v0.38.2 · Vila Tecnológica',checks:items.length,passed,failed,items};fs.writeFileSync(path.join(root,'validation/mundo-plataforma-360-results-v0.38.2.json'),JSON.stringify(result,null,2)+'\n');fs.writeFileSync(path.join(root,'TESTES-MUNDO-PLATAFORMA-360-v0.38.2.md'),`# Testes — Mundo Plataforma DS 360 v0.38.2 · Vila Tecnológica\n\n- Verificações: **${items.length}**\n- Aprovadas: **${passed}**\n- Falhas: **${failed}**\n\n`+items.map(i=>`- ${i.passed?'✅':'❌'} ${i.name}${i.detail?` — ${i.detail}`:''}`).join('\n')+'\n');console.log(JSON.stringify({checks:items.length,passed,failed}));if(failed){for(const i of items.filter(x=>!x.passed))console.error('FAIL',i.name,i.detail);process.exit(1)}
