#!/usr/bin/env node
'use strict';
const fs=require('node:fs');const path=require('node:path');
const root=path.resolve(__dirname,'..'),gameRoot=path.join(root,'games','hexa-reactor');
const {Engine,DIRS}=require(path.join(gameRoot,'engine.js'));const data=JSON.parse(fs.readFileSync(path.join(gameRoot,'levels.json'),'utf8'));const checks=[];
function check(name,passed,detail=''){checks.push({name,passed:!!passed,detail});if(!passed)console.error('FAIL',name,detail)}
check('Campanha possui 12 níveis',data.levels.length===12,`encontrados ${data.levels.length}`);check('Tabuleiro axial radius-2 possui 19 posições',data.board.cells.length===19,`${data.board.cells.length}`);check('Hexágono possui seis direções',DIRS.length===6,`${DIRS.length}`);
let previous=0;
for(const l of data.levels){
  const ids=l.pieces.map(p=>p.id),coords=l.pieces.map(p=>`${p.q},${p.r}`);check(`Fase ${l.id} IDs únicos`,new Set(ids).size===ids.length,`${ids.length} peças`);check(`Fase ${l.id} posições únicas`,new Set(coords).size===coords.length,`${coords.length} células`);check(`Fase ${l.id} possui receptor`,l.pieces.some(p=>p.kind==='sink'),`${l.sinks.length} receptores`);check(`Fase ${l.id} possui fonte`,l.pieces.some(p=>p.kind==='source'),`${l.sources.length} fontes`);check(`Fase ${l.id} começa não resolvida`,!new Engine(l).evaluate().complete,'estado inicial');
  const e=new Engine(l),sol=e.solve();check(`Fase ${l.id} solução estabiliza fluxo`,sol.complete&&sol.poweredSinks.length===sol.totalSinks&&sol.overload.length===0&&sol.leaks===0,`receptores ${sol.poweredSinks.length}/${sol.totalSinks}; overload ${sol.overload.length}; leaks ${sol.leaks}`);
  const cw=l.pieces.filter(p=>!p.fixed).reduce((n,p)=>n+((6-p.rotation)%6),0);check(`Fase ${l.id} cabe no orçamento touch`,l.moves>=cw,`giros ${cw}/${l.moves}`);check(`Fase ${l.id} dificuldade não regride`,l.moves>=previous,`${l.moves} giros`);previous=Math.min(l.moves,previous||l.moves); // informational only for first; later budget may vary by topology
  const snap=new Engine(l).snapshot();const r=new Engine(l);check(`Fase ${l.id} snapshot restaura`,r.restore(snap)&&r.movesLeft===snap.movesLeft,'schema 1');
}
const late=data.levels.slice(8);check('Fases finais usam múltiplas fontes',late.every(l=>l.sources.length>=2),late.map(l=>l.sources.length).join(','));check('Campanha possui células de sobrecarga',data.levels.filter(l=>l.unstable.length>0).length>=8,`${data.levels.filter(l=>l.unstable.length>0).length} fases`);
// Real rotation / overload behavior.
{const l=data.levels.find(x=>x.unstable.length);const e=new Engine(l);const id=e.hint();const before=e.movesLeft;const r=e.rotate(id,1);check('Rotação consome exatamente um giro',r.ok&&e.movesLeft===before-1,`${before}->${e.movesLeft}`)}
{const l=data.levels[0],e=new Engine(l);const fixed=e.pieces.find(p=>p.fixed);const before=e.movesLeft;const r=e.rotate(fixed.id,1);check('Fonte fixa não gira',!r.ok&&e.movesLeft===before,r.reason)}
const app=fs.readFileSync(path.join(root,'app.js'),'utf8'),sw=fs.readFileSync(path.join(root,'sw.js'),'utf8'),profiles=JSON.parse(fs.readFileSync(path.join(root,'game-profiles.json'),'utf8')),learning=JSON.parse(fs.readFileSync(path.join(root,'education','game-learning.json'),'utf8'));
for(const token of ['hexa-reactor','games/hexa-reactor/runtime','fliperama-ds-hexa-reactor'])check(`Integração app: ${token}`,app.includes(token),'app.js');for(const file of ['index.html','style.css','engine.js','game.js','levels.json'])check(`Arquivo do jogo: ${file}`,fs.existsSync(path.join(gameRoot,file)),file);for(const file of ['logo.svg','preview-01.svg','preview-02.svg'])check(`Mídia: ${file}`,fs.existsSync(path.join(root,'media','games','hexa-reactor',file)),file);
check('Perfil externo registrado',!!profiles['hexa-reactor'],'game-profiles.json');check('Ficha educacional registrada',!!learning['hexa-reactor'],'game-learning.json');check('Service Worker inclui Hexa Reactor',sw.includes("./games/hexa-reactor/engine.js")&&sw.includes("./games/hexa-reactor/levels.json"),'offline');check('Three.js local reutilizado',fs.readFileSync(path.join(gameRoot,'game.js'),'utf8').includes("../voxelcraft-ds/vendor/three/three.module.min.js"),'sem CDN');
const passed=checks.filter(x=>x.passed).length,failed=checks.length-passed;const result={product:'Fliperama DS',version:'0.38.6',game:'Hexa Reactor',generatedAt:new Date().toISOString(),summary:{checks:checks.length,passed,failed},items:checks};fs.writeFileSync(path.join(__dirname,'hexa-reactor-results-v0.38.6.json'),JSON.stringify(result,null,2)+'\n');fs.writeFileSync(path.join(root,'TESTES-HEXA-REACTOR-v0.38.6.md'),['# Testes — Hexa Reactor v0.38.6','',`- Verificações: **${checks.length}**`,`- Aprovadas: **${passed}**`,`- Falhas: **${failed}**`,'',...checks.map(x=>`- ${x.passed?'✅':'❌'} **${x.name}** — ${x.detail}`),''].join('\n'));console.log(JSON.stringify(result.summary,null,2));if(failed)process.exitCode=1;
