import fs from 'node:fs';import path from 'node:path';import {Mundo360Simulation} from '../games/mundo-plataforma-ds-360/simulation.mjs';
const root=path.resolve(path.dirname(new URL(import.meta.url).pathname),'..');const read=p=>JSON.parse(fs.readFileSync(path.join(root,p),'utf8'));
const files=['region.json','village.json','forest.json','industrial.json','tower.json'];const regions=files.map(f=>read('games/mundo-plataforma-ds-360/'+f).region);const [vale,village,forest,industrial,tower]=regions;const items=[];const ok=(name,passed,detail='')=>items.push({name,passed:!!passed,detail});
const inside=(pos,r)=>Math.abs(pos[0])<=r.size[0]/2+.01&&Math.abs(pos[2])<=r.size[2]/2+.01;const overlapsXZ=(pos,box,pad=.42)=>Math.abs(pos[0]-box.position[0])<=box.size[0]/2+pad&&Math.abs(pos[2]-box.position[2])<=box.size[2]/2+pad;const top=p=>p.position[1]+p.size[1]/2;const supported=(pos,r)=>[...(r.platforms||[]),...(r.movingPlatforms||[])].some(p=>Math.abs(pos[0]-p.position[0])<=p.size[0]/2+.6&&Math.abs(pos[2]-p.position[2])<=p.size[2]/2+.6&&pos[1]>=top(p)-.05&&pos[1]-top(p)<=1.85);
ok('5 regiões declaradas',regions.length===5);ok('Torre identificada',tower.kind==='tower');ok('Torre é região 5',tower.name.includes('Região 5'));ok('Torre 72x72',tower.size[0]===72&&tower.size[2]===72);ok('Portal no topo',tower.portal.position[1]>26);ok('3 consoles de sincronização',tower.interactables.filter(x=>x.type==='tower-sync').length===3);ok('1 Núcleo Central',tower.interactables.filter(x=>x.type==='tower-core').length===1);ok('6 plataformas móveis',tower.movingPlatforms.length===6);ok('5 elevadores verticais ou mais',tower.movingPlatforms.filter(x=>x.axis==='y').length>=5);ok('5 checkpoints verticais',tower.checkpoints.length===5);ok('5 patrulhas na torre',tower.enemies.length===5);ok('5 perigos em múltiplas alturas',tower.hazards.length===5&&new Set(tower.hazards.map(x=>Math.round(x.position[1]))).size>=4);ok('13 plataformas fixas',tower.platforms.length===13);
const ids=[...tower.platforms,...tower.movingPlatforms,...tower.obstacles,...tower.hazards,...tower.checkpoints,...tower.enemies,...tower.interactables].map(x=>x.id);ok('IDs da Torre únicos',new Set(ids).size===ids.length,`${ids.length} IDs`);
for(const p of tower.platforms){ok(`plataforma ${p.id} dentro`,inside(p.position,tower));ok(`plataforma ${p.id} dimensões positivas`,p.size.every(n=>n>0));}
for(const p of tower.movingPlatforms){ok(`móvel ${p.id} dentro`,inside(p.position,tower));ok(`móvel ${p.id} eixo válido`,['x','y','z'].includes(p.axis));ok(`móvel ${p.id} movimento válido`,p.range>0&&p.speed>0);if(p.axis==='y')ok(`elevador ${p.id} alcança faixa vertical`,p.range>=2.0,`range=${p.range}`);}
for(const cp of tower.checkpoints){ok(`checkpoint ${cp.id} dentro`,inside(cp.position,tower));ok(`checkpoint ${cp.id} apoiado`,supported(cp.position,tower));ok(`checkpoint ${cp.id} fora de obstáculo`,!tower.obstacles.some(o=>overlapsXZ(cp.position,o,.25)));}
for(const i of tower.interactables){ok(`interação ${i.id} dentro`,inside(i.position,tower));ok(`interação ${i.id} apoiada`,supported(i.position,tower));}
ok('spawn da Torre seguro',inside(tower.spawn,tower)&&!tower.hazards.some(h=>Math.abs(tower.spawn[1]-h.position[1])<1&&overlapsXZ(tower.spawn,h,.6)));ok('portal final dentro',inside(tower.portal.position,tower));ok('portal final apoiado',supported(tower.portal.position,tower));
const ys=tower.platforms.map(top).sort((a,b)=>a-b);ok('plataformas cobrem cinco faixas verticais',new Set(ys.map(y=>Math.round(y/5))).size>=5,ys.map(x=>x.toFixed(1)).join(','));
const vertical=tower.movingPlatforms.filter(x=>x.axis==='y');for(const p of vertical){const lo=top(p)-p.range,hi=top(p)+p.range;ok(`elevador ${p.id} tem curso > 4`,hi-lo>=4,`${lo.toFixed(1)}–${hi.toFixed(1)}`);}
// campaign deterministic progression
const world={schemaVersion:5,regions},sim=new Mundo360Simulation(world);ok('save novo schema 5',sim.snapshot().schemaVersion===5);ok('campanha tem 5 regiões',sim.progress().totalRegions===5);
const go=(pos,interact=false)=>{sim.player.pos={x:pos[0],y:pos[1],z:pos[2]};sim.player.vel={x:0,y:0,z:0};sim.invulnerable=9;sim.tick(0,{interact});};const find=(r,id)=>r.interactables.find(x=>x.id===id).position;
for(const c of vale.collectibles)sim.collected.add(c.id);for(const b of vale.beacons)sim.beacons.add(b.id);go(vale.portal.position);ok('Vale → Vila',sim.regionIndex===1&&sim.valeCompleted);
sim.quest.stage=9;go(village.portal.position);ok('Vila → Floresta',sim.regionIndex===2&&sim.villageCompleted);
for(const n of forest.interactables.filter(x=>x.type==='energy-node'))sim.quest.forestNodes.add(n.id);go(forest.portal.position);ok('Floresta → Industrial',sim.regionIndex===3&&sim.forestCompleted);
sim.quest.industrialStage=3;sim.quest.controlSynced=true;go(industrial.portal.position);ok('Industrial → Torre',sim.regionIndex===4&&sim.industrialCompleted&&!sim.completed);ok('Torre inicia 0/3',sim.quest.towerSync.size===0&&sim.quest.towerStage===0);
for(const id of ['tower-sync-1','tower-sync-2','tower-sync-3'])go(find(tower,id),true);ok('3 consoles liberam Núcleo',sim.quest.towerSync.size===3&&sim.quest.towerStage===1);ok('portal ainda fechado antes do Núcleo',!sim.portalOpen());go(find(tower,'tower-core'),true);ok('Núcleo Central ativo',sim.quest.towerCore&&sim.quest.towerStage===2);ok('portal final liberado',sim.portalOpen());go(tower.portal.position);const events=sim.consumeEvents();ok('Torre conclui campanha',sim.completed===true);ok('vitória na região 5',events.some(e=>e.type==='victory'&&e.region===5&&e.totalRegions===5));ok('evento final Convergência Central',events.some(e=>e.type==='mission-complete'&&e.label==='Convergência Central'));
// migration schema4 completed
const legacy={schemaVersion:4,lives:2,score:12000,activeRegion:3,valeCompleted:true,villageCompleted:true,forestCompleted:true,regionProgress:{},quest:{stage:9,talked:[],activated:[],relays:[],uploaded:true,forestNodes:[],industrialStage:3,industrialPower:['power-panel-west','power-panel-center','power-panel-east'],cargoRoutes:['cargo-console-a','cargo-console-b','cargo-console-c'],controlSynced:true},completed:true,player:{position:industrial.portal.position}},mig=new Mundo360Simulation(world);ok('migra schema4',mig.restore(legacy));ok('schema4 concluído entra na Torre',mig.regionIndex===4&&mig.industrialCompleted&&!mig.completed);ok('save migrado vira schema5',mig.snapshot().schemaVersion===5);ok('pontuação preservada na migração',mig.score===12000);ok('vidas preservadas na migração',mig.lives===2);ok('evento de migração 4→5',mig.consumeEvents().some(e=>e.type==='migration'&&e.fromSchema===4&&e.toSchema===5));
// current restore
const cur=new Mundo360Simulation(world);cur.valeCompleted=cur.villageCompleted=cur.forestCompleted=cur.industrialCompleted=true;cur.regionIndex=4;cur.region=tower;cur.quest.towerStage=1;cur.quest.towerSync=new Set(['tower-sync-1','tower-sync-2','tower-sync-3']);cur.quest.towerCore=false;const snap=cur.snapshot(),restored=new Mundo360Simulation(world);ok('restaura schema5',restored.restore(snap));ok('schema5 preserva Torre ativa',restored.regionIndex===4&&restored.industrialCompleted);ok('schema5 preserva 3 consoles',restored.quest.towerSync.size===3&&restored.quest.towerStage===1);ok('schema5 preserva Núcleo pendente',restored.quest.towerCore===false);
// checkpoint height safety regression: same XZ but wrong height must not activate
const cp=tower.checkpoints.find(x=>x.id==='tower-cp-ring2'),heightSim=new Mundo360Simulation({schemaVersion:5,regions:[tower]});heightSim.player.pos={x:cp.position[0],y:0,z:cp.position[2]};heightSim.player.vel={x:0,y:0,z:0};heightSim.invulnerable=9;heightSim.tick(0,{});ok('checkpoint alto não ativa pelo chão',heightSim.checkpoint.id==='spawn');heightSim.player.pos={x:cp.position[0],y:cp.position[1],z:cp.position[2]};heightSim.tick(0,{});ok('checkpoint alto ativa na altura correta',heightSim.checkpoint.id===cp.id);
// high hazard now height-aware
const hz=tower.hazards.find(x=>x.id==='tower-glitch-ring2'),hazSim=new Mundo360Simulation({schemaVersion:5,regions:[tower]});hazSim.invulnerable=0;hazSim.player.pos={x:hz.position[0],y:hz.position[1],z:hz.position[2]};hazSim.player.vel={x:0,y:0,z:0};const lives0=hazSim.lives;hazSim.tick(0,{});ok('perigo elevado causa dano na altura',hazSim.lives===lives0-1);const safeSim=new Mundo360Simulation({schemaVersion:5,regions:[tower]});safeSim.invulnerable=0;safeSim.player.pos={x:hz.position[0],y:0,z:hz.position[2]};safeSim.player.vel={x:0,y:0,z:0};const lives1=safeSim.lives;safeSim.tick(0,{});ok('perigo elevado não atinge jogador no chão',safeSim.lives===lives1);
// source and integration
const simsrc=fs.readFileSync(path.join(root,'games/mundo-plataforma-ds-360/simulation.mjs'),'utf8'),render=fs.readFileSync(path.join(root,'games/mundo-plataforma-ds-360/render.mjs'),'utf8'),game=fs.readFileSync(path.join(root,'games/mundo-plataforma-ds-360/game.js'),'utf8'),app=fs.readFileSync(path.join(root,'app.js'),'utf8'),sw=fs.readFileSync(path.join(root,'sw.js'),'utf8'),version=read('version.json'),profiles=read('game-profiles.json'),learning=read('education/game-learning.json');
ok('simulação possui Torre',simsrc.includes("kind==='tower'")&&simsrc.includes("type==='tower-sync'")&&simsrc.includes("type==='tower-core'"));ok('simulação possui checkpoint por altura',simsrc.includes("Math.abs(p.pos.y-cp.position[1])<1.6"));ok('simulação possui perigo 3D',simsrc.includes('pointIn3DBox'));ok('render possui Torre',render.includes('#towerGround')&&render.includes('#towerEntities'));ok('game carrega tower.json',game.includes("'./tower.json'"));ok('ready anuncia 5 regiões',game.includes('regions:5')&&game.includes('tower:true'));
ok('versão pública v0.39.0',version.version==='0.39.0'&&version.phase.includes('Fase 7.28'));ok('Service Worker v0.39.0',sw.includes("const VERSION = '0.39.0'"));ok('Torre no cache offline',sw.includes("'./games/mundo-plataforma-ds-360/tower.json'"));ok('wrapper reconhece 5 regiões',app.includes('#summary={region:1,regions:5')&&app.includes('regions:5,mode360:true,village:true,forest:true,industrial:true,tower:true'));ok('catálogo marca Fase 7.26',app.includes("phase:'Fase 7.26 · v0.38.5'")&&app.includes('"releasePhase": 7.26'));ok('catálogo cita Torre Central',app.includes("title:'Mundo Plataforma DS 360 · Torre Central'"));ok('perfil externo cita 5 regiões',profiles['mundo-plataforma-ds-360']?.options?.campanha?.includes('Regiões 1–5'));ok('tutorial externo cita 3 consoles',profiles['mundo-plataforma-ds-360']?.tutorialSteps?.some(x=>x.includes('3 consoles')));ok('ficha educacional cita Torre',learning['mundo-plataforma-ds-360']?.stageLabel?.includes('Torre Central'));ok('save educacional cita schema 5',learning['mundo-plataforma-ds-360']?.qualityNotes?.some(x=>x.includes('schema 5')));ok('game HUD possui Sincronia',game.includes("orbsLabel').textContent=p.towerStage<1?'Sincronia'"));ok('game trata evento tower-core',game.includes("ev.type==='tower-core'"));ok('game vitória usa 5 regiões',game.includes("post('victory',{region:5,regions:5"));
const preview=fs.readFileSync(path.join(root,'media/games/mundo-plataforma-ds-360/preview-02.svg'),'utf8');ok('preview mostra Torre Central',preview.includes('TORRE CENTRAL · REGIÃO 5')&&preview.includes('Núcleo Central'));
const passed=items.filter(x=>x.passed).length,failed=items.length-passed,result={suite:'Mundo Plataforma DS 360 v0.38.5 · Torre Central',checks:items.length,passed,failed,items};fs.writeFileSync(path.join(root,'validation/mundo-plataforma-360-results-v0.38.5.json'),JSON.stringify(result,null,2)+'\n');fs.writeFileSync(path.join(root,'TESTES-MUNDO-PLATAFORMA-360-v0.38.5.md'),`# Testes — Mundo Plataforma DS 360 v0.38.5 · Torre Central\n\n- Verificações: **${items.length}**\n- Aprovadas: **${passed}**\n- Falhas: **${failed}**\n\n`+items.map(i=>`- ${i.passed?'✅':'❌'} ${i.name}${i.detail?` — ${i.detail}`:''}`).join('\n')+'\n');console.log(JSON.stringify({checks:items.length,passed,failed}));if(failed){for(const i of items.filter(x=>!x.passed))console.error('FAIL',i.name,i.detail);process.exit(1)}
