const fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'..');
const levels=JSON.parse(fs.readFileSync(path.join(root,'games/plataforma-classica-ds/levels.json'),'utf8'));
const game=fs.readFileSync(path.join(root,'games/plataforma-classica-ds/game.js'),'utf8');
const app=fs.readFileSync(path.join(root,'app.js'),'utf8');
const profiles=JSON.parse(fs.readFileSync(path.join(root,'game-profiles.json'),'utf8'));
const learning=JSON.parse(fs.readFileSync(path.join(root,'education/game-learning.json'),'utf8'));
const version=JSON.parse(fs.readFileSync(path.join(root,'version.json'),'utf8'));
let checks=[]; function ok(name,value,detail=''){checks.push({name,passed:!!value,detail});}
function r(a){return{x:a[0],y:a[1],w:a[2],h:a[3]}}
function intersects(a,b){return a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y}
function supportIndex(l,x,y,minD=20,maxD=115){let best=-1,bestD=1e9;l.platforms.forEach((p,i)=>{const [px,py,pw]=p;if(x>=px-12&&x<=px+pw+12){const d=py-y;if(d>=minD&&d<=maxD&&d<bestD){best=i;bestD=d}}});return best}
function reachablePlatforms(l){const n=l.platforms.length,g=Array.from({length:n},()=>[]);for(let i=0;i<n;i++)for(let j=0;j<n;j++){if(i===j)continue;const a=r(l.platforms[i]),b=r(l.platforms[j]);const gap=b.x>a.x+a.w?b.x-(a.x+a.w):a.x>b.x+b.w?a.x-(b.x+b.w):0;const rise=a.y-b.y;const drop=b.y-a.y;if(gap<=175&&rise<=100&&drop<=200)g[i].push(j)}const start=supportIndex(l,l.spawn[0]+15,l.spawn[1]+42,-4,30);const seen=new Set(start>=0?[start]:[]),q=start>=0?[start]:[];while(q.length){const i=q.shift();for(const j of g[i])if(!seen.has(j)){seen.add(j);q.push(j)}}return{seen,start}}
ok('schema de fases = 1',levels.schemaVersion===1);ok('mundo Campo dos Pixels',levels.world?.id==='campo-dos-pixels');ok('exatamente 6 fases',levels.levels.length===6);
const titles=['Sinal de Partida','Bosque de Bits','Cavernas de Cache','Fábrica de Clock','Torres de Render','Castelo do Kernel'];titles.forEach((t,i)=>ok(`fase ${i+1} título`,levels.levels[i].title===t));
for(const [i,l] of levels.levels.entries()){
 const n=i+1; ok(`fase ${n} largura progressiva`,l.width>=2200+i*180);ok(`fase ${n} possui checkpoint`,Array.isArray(l.checkpoint)&&l.checkpoint.length===2);ok(`fase ${n} possui portal`,Array.isArray(l.exit)&&l.exit.length===4);ok(`fase ${n} possui pelo menos 4 chips`,l.chips.length>=4);ok(`fase ${n} possui 1 segredo`,l.secrets.length===1);ok(`fase ${n} possui perigos`,l.hazards.length>=2);ok(`fase ${n} possui inimigos`,l.enemies.length>=2);
 const {seen,start}=reachablePlatforms(l);ok(`fase ${n} spawn apoiado`,start>=0);const exitPlatform=supportIndex(l,l.exit[0]+l.exit[2]/2,l.exit[1]+l.exit[3],-4,30);ok(`fase ${n} portal em plataforma alcançável`,exitPlatform>=0&&seen.has(exitPlatform),`platform=${exitPlatform}`);
 l.chips.forEach(([x,y],j)=>{const p=supportIndex(l,x,y);ok(`fase ${n} chip ${j+1} alcançável`,p>=0&&seen.has(p),`platform=${p}`)});l.secrets.forEach(([x,y],j)=>{const p=supportIndex(l,x,y);ok(`fase ${n} segredo ${j+1} alcançável`,p>=0&&seen.has(p),`platform=${p}`)});
 const cp={x:l.checkpoint[0],y:l.checkpoint[1]-18,w:28,h:78};ok(`fase ${n} checkpoint fora de perigo`,!l.hazards.some(h=>intersects(cp,r(h))));
 const sp={x:l.spawn[0],y:l.spawn[1],w:30,h:42};ok(`fase ${n} spawn fora de perigo`,!l.hazards.some(h=>intersects(sp,r(h))));
}
ok('fase final possui boss',!!levels.levels[5].boss);ok('boss exige 3 impactos',levels.levels[5].boss?.hp===3);ok('boss é Guardião do Clock',levels.levels[5].boss?.type==='clock-guardian');ok('fases 1-5 sem boss',levels.levels.slice(0,5).every(l=>!l.boss));
ok('game usa coyote time',game.includes('COYOTE_MS = 105'));ok('game usa jump buffer',game.includes('JUMP_BUFFER_MS = 125'));ok('game possui câmera lateral',game.includes('cameraX'));ok('game possui Gamepad API',game.includes('navigator.getGamepads'));ok('game possui touch',game.includes('setupTouch()'));ok('game possui checkpoint',game.includes('updateCheckpoint()'));ok('game exige chips e boss',game.includes('collectedChips.size===level.chips.length')&&game.includes('!boss.alive'));ok('game possui modo histórico',game.includes("visualStyle==='historico'"));ok('game possui modo moderno',game.includes('drawModernBackground'));ok('mesma simulação para os estilos',!game.includes('if(visualStyle')||game.includes('drawHistoricalBackground'));
ok('save schema 1',game.includes('schemaVersion:1'));ok('evento ready',game.includes("post('ready'"));ok('evento finished',game.includes("post('finished'"));ok('ponte de mensagem correta',game.includes('fliperama-ds-plataforma-classica'));
ok('runtime integrado ao loader',app.includes("'plataforma-classica-ds': () =>"));ok('runtime wrapper integrado',app.includes('class PlataformaClassicaRuntime'));ok('iframe sob demanda',app.includes("./games/plataforma-classica-ds/index.html"));ok('HUD portal 1/6',app.includes("`${state?.level ?? 1}/6`"));ok('resultado Mundo 1',app.includes('Mundo 1 — Campo dos Pixels concluído!'));
ok('perfil externo existe',!!profiles['plataforma-classica-ds']);ok('perfil oferece 2 estilos',Object.keys(profiles['plataforma-classica-ds']?.options||{}).length===2);ok('perfil default moderno',profiles['plataforma-classica-ds']?.defaultOption==='moderno');ok('ficha educacional existe',!!learning['plataforma-classica-ds']);ok('ficha declara 6 progressões',learning['plataforma-classica-ds']?.progression?.length===6);
for(const f of ['logo.svg','preview-01.svg','preview-02.svg']){const q=path.join(root,'media/games/plataforma-classica-ds',f);ok(`mídia ${f} existe`,fs.existsSync(q));if(fs.existsSync(q)){const txt=fs.readFileSync(q,'utf8');ok(`mídia ${f} acessível`,/role="img"/.test(txt)&&/aria-label=/.test(txt));}}
ok('versão pública atual preserva Plataforma Clássica',String(version.version).startsWith('0.39.0'));ok('fase pública atual preserva Plataforma Clássica',String(version.phase).includes('7.28'));ok('app build atual preserva Plataforma Clássica',(app.includes("version: '0.39.0'") || app.includes("version: '0.39.0-hotfix1'")));
const passed=checks.filter(c=>c.passed).length,failed=checks.length-passed;const result={suite:'Plataforma Clássica DS v0.37.1',checks:checks.length,passed,failed,items:checks};fs.writeFileSync(path.join(root,'validation/plataforma-classica-results-v0.37.1.json'),JSON.stringify(result,null,2));console.log(JSON.stringify({checks:checks.length,passed,failed}));if(failed){for(const c of checks.filter(c=>!c.passed))console.error('FAIL',c.name,c.detail);process.exit(1)}
