import fs from 'node:fs';import path from 'node:path';import {fileURLToPath,pathToFileURL} from 'node:url';
const __dirname=path.dirname(fileURLToPath(import.meta.url)),root=path.resolve(__dirname,'..');
const data=JSON.parse(fs.readFileSync(path.join(root,'games/mundo-plataforma-ds-360/region.json'),'utf8'));const region=data.region;
const game=fs.readFileSync(path.join(root,'games/mundo-plataforma-ds-360/game.js'),'utf8');const render=fs.readFileSync(path.join(root,'games/mundo-plataforma-ds-360/render.mjs'),'utf8');const app=fs.readFileSync(path.join(root,'app.js'),'utf8');const sw=fs.readFileSync(path.join(root,'sw.js'),'utf8');const profiles=JSON.parse(fs.readFileSync(path.join(root,'game-profiles.json'),'utf8'));const learning=JSON.parse(fs.readFileSync(path.join(root,'education/game-learning.json'),'utf8'));
const {Mundo360Simulation}=await import(pathToFileURL(path.join(root,'games/mundo-plataforma-ds-360/simulation.mjs')).href+'?v='+Date.now());
const items=[];const ok=(name,cond,detail='')=>items.push({name,passed:!!cond,detail});
const allIds=[];for(const key of ['platforms','movingPlatforms','obstacles','hazards','collectibles','beacons','checkpoints','enemies'])for(const x of region[key]||[])allIds.push(x.id);
ok('schema da região',data.schemaVersion===1);ok('nome Vale Nexus 360',region.name.includes('Vale Nexus 360'));ok('mundo 72×72',region.size[0]===72&&region.size[2]===72);ok('cinco setores incluindo hub',region.sectors.length===5&&region.sectors.some(s=>s.id==='hub'));ok('setor norte',region.sectors.some(s=>s.center[1]<-20));ok('setor leste',region.sectors.some(s=>s.center[0]>20));ok('setor sul',region.sectors.some(s=>s.center[1]>20));ok('setor oeste',region.sectors.some(s=>s.center[0]<-20));ok('IDs únicos',new Set(allIds).size===allIds.length,`${allIds.length} IDs`);ok('6 orbes',region.collectibles.length===6);ok('3 balizas',region.beacons.length===3);ok('3 checkpoints',region.checkpoints.length===3);ok('4 plataformas móveis',region.movingPlatforms.length===4);ok('8 campos Glitch',region.hazards.length===8);ok('6 patrulhas',region.enemies.length===6);ok('portal central',Math.hypot(region.portal.position[0],region.portal.position[2])<.5);
const within=pos=>Math.abs(pos[0])<region.size[0]/2&&Math.abs(pos[2])<region.size[2]/2;
for(const c of region.collectibles)ok(`${c.id} dentro do Vale`,within(c.position)&&c.position[1]>1);
for(const b of region.beacons)ok(`${b.id} dentro do Vale`,within(b.position)&&b.position[1]>1);
for(const cp of region.checkpoints){ok(`${cp.id} dentro do Vale`,within(cp.position));ok(`${cp.id} fora de perigo`,!region.hazards.some(h=>Math.abs(cp.position[0]-h.position[0])<=h.size[0]/2+.5&&Math.abs(cp.position[2]-h.position[2])<=h.size[2]/2+.5));}
for(const m of region.movingPlatforms)ok(`${m.id} movimento válido`,['x','z'].includes(m.axis)&&m.range>=4&&m.speed>0);
for(const e of region.enemies)ok(`${e.id} patrulha válida`,['x','z'].includes(e.axis)&&e.range>=4&&e.speed>0);
function supported(pos){return region.platforms.some(p=>Math.abs(pos[0]-p.position[0])<=p.size[0]/2&&Math.abs(pos[2]-p.position[2])<=p.size[2]/2&&pos[1]>=p.position[1]+p.size[1]/2&&pos[1]<=p.position[1]+p.size[1]/2+1.5)}
for(const c of region.collectibles)ok(`${c.id} apoiado em plataforma`,supported(c.position));for(const b of region.beacons)ok(`${b.id} apoiada em plataforma`,supported(b.position));
const sim=new Mundo360Simulation(region);ok('simulação começa com 3 vidas',sim.lives===3);ok('simulação começa sem orbes',sim.collected.size===0);ok('simulação começa sem balizas',sim.beacons.size===0);ok('save schema 1',sim.snapshot().schemaVersion===1);ok('progresso declara 6 orbes',sim.progress().totalOrbs===6);ok('progresso declara 3 balizas',sim.progress().totalBeacons===3);
const x0=sim.player.pos.x;sim.player.grounded=true;sim.player.coyote=.12;sim.tick(.016,{x:1,z:0,jump:false});ok('movimento altera X',sim.player.pos.x>x0);sim.player.grounded=true;sim.player.coyote=.12;sim.tick(.016,{x:0,z:0,jump:true});ok('salto aplica velocidade vertical',sim.player.vel.y>0);
const beforeMove=sim.moving[0].current[0]+sim.moving[0].current[2];sim.tick(.25,{});const afterMove=sim.moving[0].current[0]+sim.moving[0].current[2];ok('plataforma móvel evolui no tempo',Math.abs(afterMove-beforeMove)>.01);
for(const c of region.collectibles){sim.player.pos={x:c.position[0],y:c.position[1],z:c.position[2]};sim.player.vel={x:0,y:0,z:0};sim.invulnerable=9;sim.tick(0,{});}ok('6 orbes podem ser sincronizados',sim.collected.size===6);
for(const b of region.beacons){sim.player.pos={x:b.position[0],y:b.position[1],z:b.position[2]};sim.player.vel={x:0,y:0,z:0};sim.invulnerable=9;sim.tick(0,{});}ok('3 balizas podem ser ativadas',sim.beacons.size===3);
sim.player.pos={x:region.portal.position[0],y:region.portal.position[1],z:region.portal.position[2]};sim.player.vel={x:0,y:0,z:0};sim.tick(0,{});ok('portal conclui com 6+3',sim.completed===true);ok('vitória gera evento',sim.consumeEvents().some(e=>e.type==='victory'));
const snap=sim.snapshot();const restored=new Mundo360Simulation(region);ok('restore aceita snapshot atual',restored.restore(snap));ok('restore preserva 6 orbes',restored.collected.size===6);ok('restore preserva 3 balizas',restored.beacons.size===3);ok('restore preserva conclusão',restored.completed===true);
const damage=new Mundo360Simulation(region),h=region.hazards[0];damage.player.pos={x:h.position[0],y:.1,z:h.position[2]};damage.player.vel={x:0,y:0,z:0};damage.tick(0,{});ok('campo Glitch causa dano',damage.lives===2&&damage.consumeEvents().some(e=>e.type==='damage'));
const enemy=new Mundo360Simulation(region),en=enemy.enemies[0];enemy.player.pos={x:en.position[0],y:en.position[1],z:en.position[2]};enemy.player.vel={x:0,y:0,z:0};enemy.tick(0,{});ok('patrulha causa dano',enemy.lives===2&&enemy.consumeEvents().some(e=>e.type==='damage'));
const cpSim=new Mundo360Simulation(region),cp=region.checkpoints[0];cpSim.player.pos={x:cp.position[0],y:cp.position[1],z:cp.position[2]};cpSim.player.vel={x:0,y:0,z:0};cpSim.tick(0,{});ok('checkpoint pode ser ativado',cpSim.checkpoint.id===cp.id);
ok('Three.js local',render.includes("../voxelcraft-ds/vendor/three/three.module.min.js"));ok('câmera perspectiva',render.includes('new THREE.PerspectiveCamera'));ok('yaw de câmera',render.includes('this.yaw'));ok('pitch limitado',render.includes('this.pitch'));ok('modo panorama 360',render.includes('togglePanorama'));ok('bússola em graus',render.includes('heading()'));ok('câmera olha para jogador',render.includes('this.camera.lookAt(target)'));ok('qualidade controla sombras',render.includes("quality==='alto'||quality==='ultra'"));ok('densidade por perfil',render.includes("this.quality==='baixo'?18"));ok('render lê simulação',render.includes('update(sim,dt)'));
ok('gamepad API',game.includes('navigator.getGamepads'));ok('analógico direito controla câmera',game.includes('view.setGamepadLook'));ok('arraste controla câmera',game.includes("canvas.addEventListener('pointermove'"));ok('tecla C alterna 360',game.includes("e.code==='KeyC'"));ok('touch panorama 360',game.includes("a==='panorama'"));ok('movimento relativo à câmera',game.includes('worldX=')&&game.includes('worldZ='));ok('save local',game.includes("localStorage.setItem(SAVE_KEY"));ok('ponte postMessage',game.includes('fliperama-ds-mundo-plataforma-360'));
ok('runtime loader no portal',app.includes("'mundo-plataforma-ds-360': () =>"));ok('runtime wrapper',app.includes('MundoPlataforma360Runtime'));ok('iframe isolado',app.includes("./games/mundo-plataforma-ds-360/index.html"));ok('catálogo 23ª experiência',app.includes('Mundo Plataforma DS 360')&&app.includes('releasePhase": 7.22'));ok('perfil externo',!!profiles['mundo-plataforma-ds-360']);ok('ficha educacional',!!learning['mundo-plataforma-ds-360']);ok('progressão educacional rica',learning['mundo-plataforma-ds-360']?.progression?.length>=5);ok('Service Worker v0.38.1',sw.includes("const VERSION = '0.38.1'"));ok('runtime no cache offline',sw.includes("'./games/mundo-plataforma-ds-360/simulation.mjs'")&&sw.includes("'./games/mundo-plataforma-ds-360/render.mjs'"));
for(const f of ['logo.svg','preview-01.svg','preview-02.svg']){const q=path.join(root,'media/games/mundo-plataforma-ds-360',f);ok(`mídia ${f}`,fs.existsSync(q));if(fs.existsSync(q)){const t=fs.readFileSync(q,'utf8');ok(`acessibilidade ${f}`,t.includes('role="img"')&&t.includes('aria-label=')&&t.length>500,`${t.length} bytes`);}}
const passed=items.filter(x=>x.passed).length,failed=items.length-passed;const result={suite:'Mundo Plataforma DS 360 v0.38.1',checks:items.length,passed,failed,items};fs.writeFileSync(path.join(root,'validation/mundo-plataforma-360-results-v0.38.1.json'),JSON.stringify(result,null,2)+'\n');fs.writeFileSync(path.join(root,'TESTES-MUNDO-PLATAFORMA-360-v0.38.1.md'),`# Testes — Mundo Plataforma DS 360 v0.38.1\n\n- Verificações: **${items.length}**\n- Aprovadas: **${passed}**\n- Falhas: **${failed}**\n\n`+items.map(i=>`- ${i.passed?'✅':'❌'} ${i.name}${i.detail?` — ${i.detail}`:''}`).join('\n')+'\n');console.log(JSON.stringify({checks:items.length,passed,failed}));if(failed){for(const i of items.filter(x=>!x.passed))console.error('FAIL',i.name,i.detail);process.exit(1)}
