import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { requireLiveAuthSession } from "./session-guard.ts";
import { createClient } from "jsr:@supabase/supabase-js@2.111.0";
const H={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const J=(x:unknown,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{...H,"Content-Type":"application/json"}});
class S extends Error{}
Deno.serve(async r=>{if(r.method==='OPTIONS')return new Response('ok',{headers:H});try{
 const url=Deno.env.get('SUPABASE_URL')!, key=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!, ah=r.headers.get('Authorization')||'';
 const a=createClient(url,Deno.env.get('SUPABASE_ANON_KEY')!,{global:{headers:{Authorization:ah}}}), db=createClient(url,key,{auth:{persistSession:false}});
 const {data:{user}}=await a.auth.getUser(); if(!user?.email)return J({error:'unauthorized'},401); const live=await requireLiveAuthSession(db,ah,user.id);if(!live.ok)return J({error:live.error,detail:live.detail||null},live.status);
 const [{data:p},{data:w}]=await Promise.all([db.from('profiles').select('role,active,must_change_password').eq('id',user.id).maybeSingle(),db.from('staff_allowlist').select('role,active,full_name').eq('email',user.email.toLowerCase()).eq('active',true).maybeSingle()]);
 const role=String(w?.role||p?.role||''); if(!p?.active)return J({error:'forbidden'},403);if(p.must_change_password)return J({error:'password_change_required'},403);if(!['teacher','admin','super_admin'].includes(role))return J({error:'forbidden'},403); const admin=['admin','super_admin'].includes(role);
 const {data:ta}=admin?{data:[]} : await db.from('teacher_classes').select('class_id').eq('teacher_email',user.email.toLowerCase()).eq('active',true); const assigned=(ta||[]).map((x:any)=>String(x.class_id));
 const exFor=async(cs:string[])=>{if(!cs.length)return[];const [{data:m},{data:e},{data:s}]=await Promise.all([db.from('class_subjects').select('subject_id').in('class_id',cs).eq('active',true),db.from('exercises').select('id,class_id,subject_id,exercise_number,title,active,config').eq('active',true),db.from('subjects').select('id,slug')]);const ss=new Set((m||[]).map((x:any)=>String(x.subject_id))),cc=new Set(cs),slugs=new Map((s||[]).map((x:any)=>[String(x.id),String(x.slug||'')]));return(e||[]).filter((x:any)=>x.class_id?cc.has(String(x.class_id)):ss.has(String(x.subject_id))).map((x:any)=>({...x,subject_slug:slugs.get(String(x.subject_id))||''}))};
 const scope=async(sid:string,eid?:string)=>{if(admin)return;const {data:m}=await db.from('class_memberships').select('class_id').eq('user_id',sid).eq('active',true);const aa=new Set(assigned),cs=(m||[]).map((x:any)=>String(x.class_id)).filter((x:string)=>aa.has(x));if(!cs.length)throw new S('student_out_of_scope');if(eid){const es=await exFor(cs);if(!es.some((x:any)=>String(x.id)===eid))throw new S('exercise_out_of_scope')}};
 const b=await r.json().catch(()=>({})), act=b.action||'overview';
 if(act==='staff_status')return J({staff:true,role,full_name:w?.full_name||null,assigned_class_ids:admin?null:assigned});
 if(act==='overview'){
  const [{data:c},{data:m},{data:pr},{data:g},{data:e},{data:q},{data:s}]=await Promise.all([db.from('classes').select('id,code,name,shift,school_year,active').eq('active',true),db.from('class_memberships').select('class_id,user_id,active').eq('active',true),db.from('profiles').select('id,full_name,email,role,active,last_login_at').eq('role','student').eq('active',true),db.from('student_exercises').select('student_id,exercise_id,status,progress_percent,attempts,started_at,auto_score,auto_score_at,submitted_score,submitted_at,last_activity_at,completed_at,approval_status,teacher_feedback,teacher_feedback_at,security_locked,security_lock_reason,security_locked_at,completion_source'),db.from('exercises').select('id,subject_id,class_id,exercise_number,title,active,config').eq('active',true),db.from('student_preregistrations').select('id,full_name,institutional_email,cgm,class_id,enrollment_status,active,claimed_user_id,claimed_at'),db.from('subjects').select('id,slug')]);
  const slugs=new Map((s||[]).map((x:any)=>[String(x.id),String(x.slug||'')])),exercises=(e||[]).map((x:any)=>({...x,subject_slug:slugs.get(String(x.subject_id))||''}));
  if(admin)return J({classes:c||[],memberships:m||[],profiles:pr||[],progress:g||[],exercises,preregistrations:(q||[]).map((x:any)=>({...x,cgm:undefined,has_cgm:!!x.cgm})),scope:'global'});
  const cc=new Set(assigned),mm=(m||[]).filter((x:any)=>cc.has(String(x.class_id))),ids=new Set(mm.map((x:any)=>String(x.user_id))),ee=await exFor(assigned),eids=new Set(ee.map((x:any)=>String(x.id)));
  return J({classes:(c||[]).filter((x:any)=>cc.has(String(x.id))),memberships:mm,profiles:(pr||[]).filter((x:any)=>ids.has(String(x.id))),progress:(g||[]).filter((x:any)=>ids.has(String(x.student_id))&&eids.has(String(x.exercise_id))),exercises:ee,preregistrations:(q||[]).filter((x:any)=>cc.has(String(x.class_id))).map((x:any)=>({id:x.id,full_name:x.full_name,institutional_email:x.institutional_email,class_id:x.class_id,enrollment_status:x.enrollment_status,active:x.active,claimed_user_id:x.claimed_user_id,claimed_at:x.claimed_at,has_cgm:!!x.cgm})),scope:'assigned',assigned_class_ids:assigned});
 }
 const sid=String(b.student_id||''), eid=String(b.exercise_id||'');
 if(act==='student_detail'){if(!sid)return J({error:'missing_parameters'},400);await scope(sid);const [{data:g},{data:x},{data:y},{data:ar}]=await Promise.all([db.from('student_exercises').select('*').eq('student_id',sid),db.from('student_accommodations').select('*').eq('student_id',sid).eq('active',true),db.from('exercise_releases').select('*').eq('student_id',sid),db.from('pedagogical_adaptation_requests').select('id,status,request_source,created_at,updated_at,resolved_at').eq('student_id',sid).order('created_at',{ascending:false}).limit(10)]);if(admin)return J({progress:g||[],accommodations:x||[],releases:y||[],adaptation_requests:ar||[]});const {data:m}=await db.from('class_memberships').select('class_id').eq('user_id',sid).eq('active',true);const aa=new Set(assigned),cs=(m||[]).map((z:any)=>String(z.class_id)).filter((z:string)=>aa.has(z)),es=await exFor(cs),ei=new Set(es.map((z:any)=>String(z.id)));return J({progress:(g||[]).filter((z:any)=>ei.has(String(z.exercise_id))),accommodations:(x||[]).filter((z:any)=>!z.exercise_id||ei.has(String(z.exercise_id))),releases:(y||[]).filter((z:any)=>ei.has(String(z.exercise_id))),adaptation_requests:ar||[]});}
 if(act==='experience_overview'){
  const [{data:classes},{data:memberships},{data:profiles},{data:accommodations},{data:prefs},{data:modePrefs},{data:assignments},{data:xp},{data:events},{data:studentProgress},{data:exercises},{data:subjects}]=await Promise.all([
    db.from('classes').select('id,code,name').eq('active',true),
    db.from('class_memberships').select('class_id,user_id,is_primary,active').eq('active',true),
    db.from('profiles').select('id,full_name,email,last_login_at').eq('role','student').eq('active',true),
    db.from('student_accommodations').select('student_id,config,updated_at').is('exercise_id',null).eq('accommodation_type','learning_mode').eq('active',true),
    db.from('pedagogical_learning_preferences').select('*'),
    db.from('pedagogical_adaptation_preferences').select('student_id,adaptation_key,mode,updated_at'),
    db.from('pedagogical_experience_assignments').select('*').order('display_order').order('created_at'),
    db.from('pedagogical_experience_progress').select('*'),
    db.from('pedagogical_experience_events').select('id,student_id,assignment_id,adaptation_key,subject_slug,event_type,mode,metadata,occurred_at').order('occurred_at',{ascending:false}).limit(800),
    db.from('student_exercises').select('student_id,exercise_id,status,progress_percent,last_activity_at,completed_at,submitted_score'),
    db.from('exercises').select('id,subject_id,exercise_number,title,active').eq('active',true),
    db.from('subjects').select('id,slug,name')
  ]);
  const classMap=new Map((classes||[]).map((x:any)=>[String(x.id),x])),subjectMap=new Map((subjects||[]).map((x:any)=>[String(x.id),x])),exerciseMap=new Map((exercises||[]).map((x:any)=>[String(x.id),x]));
  const allowedIds=new Set<string>();
  if(admin){for(const p of profiles||[])allowedIds.add(String(p.id));}
  else{const aa=new Set(assigned);for(const m of memberships||[])if(aa.has(String(m.class_id)))allowedIds.add(String(m.user_id));}
  const classByStudent=new Map<string,any>();for(const m of memberships||[]){const uid=String(m.user_id);if(!allowedIds.has(uid))continue;const current=classByStudent.get(uid);if(!current||m.is_primary)classByStudent.set(uid,classMap.get(String(m.class_id))||null);}
  const rows=(profiles||[]).filter((p:any)=>allowedIds.has(String(p.id))).map((p:any)=>{
   const id=String(p.id);
   const acc=(accommodations||[]).filter((x:any)=>String(x.student_id)===id).sort((a:any,b:any)=>Date.parse(b.updated_at||0)-Date.parse(a.updated_at||0))[0]||null;
   const adaptationKey=String(acc?.config?.profile_key||acc?.config?.adaptation_profile||'support');
   const conventional=(studentProgress||[]).filter((x:any)=>String(x.student_id)===id).map((x:any)=>{
    const ex=exerciseMap.get(String(x.exercise_id)),sub=subjectMap.get(String(ex?.subject_id));
    return {...x,exercise_number:ex?.exercise_number||null,exercise_title:ex?.title||null,subject_slug:sub?.slug||null,subject_name:sub?.name||null};
   });
   return {student_id:id,full_name:p.full_name,email:p.email,last_login_at:p.last_login_at,class:classByStudent.get(id)||null,adaptation:acc,preference:(prefs||[]).find((x:any)=>String(x.student_id)===id)||null,mode_preference:(modePrefs||[]).filter((x:any)=>String(x.student_id)===id&&String(x.adaptation_key)===adaptationKey).sort((a:any,b:any)=>Date.parse(b.updated_at||0)-Date.parse(a.updated_at||0))[0]||null,assignments:(assignments||[]).filter((x:any)=>String(x.student_id)===id),experience_progress:(xp||[]).filter((x:any)=>String(x.student_id)===id),events:(events||[]).filter((x:any)=>String(x.student_id)===id).slice(0,120),conventional_progress:conventional};
  });
  return J({students:rows,scope:admin?'global':'assigned'});
 }
 if(act==='update_experience_assignment'){
  const id=String(b.id||'');if(!id)return J({error:'missing_parameters'},400);
  const {data:row}=await db.from('pedagogical_experience_assignments').select('id,student_id').eq('id',id).maybeSingle();if(!row)return J({error:'not_found'},404);await scope(String(row.student_id));
  const patch:any={updated_at:new Date().toISOString()};
  if(Object.prototype.hasOwnProperty.call(b,'deadline'))patch.deadline=b.deadline?String(b.deadline):null;
  if(Object.prototype.hasOwnProperty.call(b,'active'))patch.active=b.active===true;
  if(Object.prototype.hasOwnProperty.call(b,'display_order'))patch.display_order=Math.max(0,Math.min(999,Number(b.display_order||0)));
  if(Object.prototype.hasOwnProperty.call(b,'extra_time_minutes'))patch.extra_time_minutes=Math.max(0,Math.min(1440,Number(b.extra_time_minutes||0)));
  const {data,error}=await db.from('pedagogical_experience_assignments').update(patch).eq('id',id).select().single();if(error)throw error;return J({ok:true,assignment:data});
 }
 if(act==='create_experience_assignment'){
  const studentId=String(b.student_id||''),subjectSlug=String(b.subject_slug||'').trim(),subjectName=String(b.subject_name||'').trim(),title=String(b.title||'').trim(),purpose=String(b.purpose||'complementary'),instruction=String(b.instruction||'').trim();
  if(!studentId||!subjectSlug||!subjectName||!title||!instruction)return J({error:'missing_parameters'},400);
  if(!['evaluation','recovery','complementary','extra','practice'].includes(purpose))return J({error:'invalid_purpose'},400);
  await scope(studentId);
  const {data:acc}=await db.from('student_accommodations').select('config').eq('student_id',studentId).is('exercise_id',null).eq('accommodation_type','learning_mode').eq('active',true).order('updated_at',{ascending:false}).limit(1).maybeSingle();
  if(!acc)return J({error:'personalized_experience_not_enabled'},409);
  const adaptationKey=String(acc.config?.profile_key||acc.config?.adaptation_profile||'support'),now=new Date().toISOString(),keyPart=crypto.randomUUID().slice(0,8);
  const row:any={student_id:studentId,adaptation_key:adaptationKey,subject_slug:subjectSlug.slice(0,120),subject_name:subjectName.slice(0,180),experience_key:`teacher-${Date.now()}-${keyPart}`,title:title.slice(0,180),purpose,deadline:b.deadline?String(b.deadline):null,extra_time_minutes:Math.max(0,Math.min(1440,Number(b.extra_time_minutes||0))),display_order:Math.max(0,Math.min(999,Number(b.display_order||50))),active:true,created_by:user.id,updated_at:now,config:{summary:instruction.slice(0,700),kicker:'Atividade personalizada',heading:title.slice(0,180),intro:'Atividade atribuída pelo professor e organizada separadamente do histórico convencional.',steps:[{id:'orientacao',type:'message',title:'Orientação do professor',text:instruction.slice(0,2500)}]}};
  const {data,error}=await db.from('pedagogical_experience_assignments').insert(row).select().single();if(error)throw error;return J({ok:true,assignment:data});
 }
 if(act==='log_teacher_preview'){
  const studentId=String(b.student_id||''),assignmentId=b.assignment_id?String(b.assignment_id):null;if(!studentId)return J({error:'missing_parameters'},400);await scope(studentId);
  const {data:acc}=await db.from('student_accommodations').select('config').eq('student_id',studentId).is('exercise_id',null).eq('accommodation_type','learning_mode').eq('active',true).order('updated_at',{ascending:false}).limit(1).maybeSingle();
  const {error}=await db.from('pedagogical_experience_events').insert({student_id:studentId,assignment_id:assignmentId,adaptation_key:String(acc?.config?.profile_key||acc?.config?.adaptation_profile||'support'),event_type:'teacher_preview_opened',mode:'adapted',metadata:{viewer_id:user.id,viewer_role:role,source:'staff_preview'},occurred_at:new Date().toISOString()});if(error)throw error;return J({ok:true});
 }
 if(act==='student_files'){if(!sid||!eid)return J({error:'missing_parameters'},400);await scope(sid,eid);const {data,error}=await db.from('student_files').select('id,filename,language,content,revision,saved_at').eq('student_id',sid).eq('exercise_id',eid).order('filename');if(error)throw error;return J({files:data||[]});}
 if(act==='resolve_adaptation_request'){const id=String(b.id||''),status=String(b.status||'approved');if(!id||!['approved','declined','closed'].includes(status))return J({error:'invalid_request'},400);const {data:reqRow}=await db.from('pedagogical_adaptation_requests').select('student_id').eq('id',id).maybeSingle();if(!reqRow)return J({error:'not_found'},404);await scope(String(reqRow.student_id));const {error}=await db.from('pedagogical_adaptation_requests').update({status,resolved_at:new Date().toISOString(),resolved_by:user.id,updated_at:new Date().toISOString()}).eq('id',id);if(error)throw error;return J({ok:true});}
 if(act==='set_accommodation'){if(!sid)return J({error:'missing_parameters'},400);const globalScope=b.global_scope===true||!eid;await scope(sid,globalScope?undefined:eid);const type=String(b.accommodation_type||'support');if(globalScope){const {data:old}=await db.from('student_accommodations').select('id').eq('student_id',sid).is('exercise_id',null).eq('accommodation_type',type).eq('active',true).order('updated_at',{ascending:false}).limit(1).maybeSingle();const patch={student_id:sid,exercise_id:null,accommodation_type:type,config:b.config||{},reason:String(b.reason||''),active:true,created_by:user.id,updated_at:new Date().toISOString()};const z=old?.id?await db.from('student_accommodations').update(patch).eq('id',old.id).select().single():await db.from('student_accommodations').insert(patch).select().single();if(z.error)throw z.error;return J({ok:true,accommodation:z.data});}const {data,error}=await db.from('student_accommodations').insert({student_id:sid,exercise_id:eid,accommodation_type:type,config:b.config||{},reason:String(b.reason||''),active:true,created_by:user.id}).select().single();if(error)throw error;return J({ok:true,accommodation:data});}
 if(act==='disable_accommodation'){const id=String(b.id||'');const {data:x}=await db.from('student_accommodations').select('student_id,exercise_id').eq('id',id).maybeSingle();if(!x)return J({error:'not_found'},404);await scope(String(x.student_id),x.exercise_id?String(x.exercise_id):undefined);const {error}=await db.from('student_accommodations').update({active:false,updated_at:new Date().toISOString()}).eq('id',id);if(error)throw error;return J({ok:true});}
 if(act==='set_release'){if(!sid||!eid)return J({error:'missing_parameters'},400);await scope(sid,eid);const patch={student_id:sid,exercise_id:eid,class_id:null,enabled:b.enabled!==false,allow_html_base:b.allow_html_base??null,allow_css_base:b.allow_css_base??null,allow_js_base:b.allow_js_base??null,allow_extra_hints:b.allow_extra_hints??null,allow_guided_support:b.allow_guided_support??null,created_by:user.id,updated_at:new Date().toISOString()};const {data:o}=await db.from('exercise_releases').select('id').eq('student_id',sid).eq('exercise_id',eid).maybeSingle();const z=o?.id?await db.from('exercise_releases').update(patch).eq('id',o.id).select().single():await db.from('exercise_releases').insert(patch).select().single();if(z.error)throw z.error;return J({ok:true,release:z.data});}
 if(act==='manual_review'){const st=String(b.approval_status||'pending');if(!sid||!eid||!['not_required','pending','approved','changes_requested'].includes(st))return J({error:'invalid_parameters'},400);await scope(sid,eid);const {data:current}=await db.from('student_exercises').select('progress_percent,status').eq('student_id',sid).eq('exercise_id',eid).maybeSingle();if(!current)return J({error:'progress_not_found'},404);const n=new Date().toISOString(),patch:any={approval_status:st,teacher_feedback:String(b.teacher_feedback||'')||null,teacher_feedback_at:n,last_activity_at:n};if(st==='approved')Object.assign(patch,{approved_by:user.id,approved_at:n,status:'completed',progress_percent:100,completed_at:n,completion_source:'manual_review_approved'});if(st==='changes_requested')Object.assign(patch,{approved_by:null,approved_at:null,status:'in_progress',progress_percent:Math.min(99,Math.max(0,Number(current.progress_percent||0))),completed_at:null,completion_source:'manual_review_changes_requested'});const {data,error}=await db.from('student_exercises').update(patch).eq('student_id',sid).eq('exercise_id',eid).select().maybeSingle();if(error)throw error;return J({ok:true,progress:data});}
 return J({error:'unknown_action'},400);
}catch(e){if(e instanceof S)return J({error:e.message},403);return J({error:'internal_error',detail:String((e as Error)?.message||e)},500)}});
