import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { requireLiveAuthSession } from "./session-guard.ts";
import { createClient } from "jsr:@supabase/supabase-js@2.111.0";
const H={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const J=(x:unknown,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{...H,"Content-Type":"application/json"}});
class S extends Error{}
const low=(v:unknown)=>String(v??'').trim().toLowerCase();
const clampScore=(v:unknown)=>Math.max(0,Math.min(100,Math.round(Number(v)||0)));
function aliases(name:string){const n=low(name),s=new Set([n]);if(n==='style.css')s.add('estilo.css');if(n==='estilo.css')s.add('style.css');if(n==='app.js')s.add('script.js');if(n==='script.js')s.add('app.js');if(n==='main.kt')s.add('mainactivity.kt');if(n==='mainactivity.kt')s.add('main.kt');if(n==='referencia.md')s.add('atividade.md');return [...s]}
function strip(lang:string,src:string){let v=String(src||'').replace(/\r\n?/g,'\n'),l=low(lang);if(['html','xml'].includes(l))v=v.replace(/<!--[\s\S]*?-->/g,' ');if(['css','javascript','js','kotlin','kt'].includes(l))v=v.replace(/\/\*[\s\S]*?\*\//g,' ').replace(/^\s*\/\/.*$/gm,' ');if(['python','py'].includes(l))v=v.replace(/^\s*#.*$/gm,' ');return v}
function tokens(lang:string,src:string){return(strip(lang,src).match(/(===|!==|=>|==|!=|>=|<=|&&|\|\||\+\+|--|\*\*|\/\/|\$\{|[A-Za-z_$À-ÿ][\w$À-ÿ-]*|\d+(?:\.\d+)?|"(?:\\.|[^"\\])*"|'(?:\\.|[^'\\])*'|`(?:\\.|[^`\\])*`|[{}()[\]<>:;,.#@%+*\/=!?&|$-])/g)||[]).map(t=>/[A-Za-zÀ-ÿ]/.test(t)?t.toLowerCase():t)}
function f1(a:string[],b:string[]){if(!a.length&&!b.length)return 1;if(!a.length||!b.length)return 0;const A=new Map<string,number>(),B=new Map<string,number>();for(const x of a)A.set(x,(A.get(x)||0)+1);for(const x of b)B.set(x,(B.get(x)||0)+1);let c=0;for(const[k,n]of A)c+=Math.min(n,B.get(k)||0);const p=c/a.length,r=c/b.length;return p+r?2*p*r/(p+r):0}
function pairs(t:string[]){const s=new Set<string>();for(let i=0;i<t.length-1;i++)s.add(`${t[i]}\u0001${t[i+1]}`);return s}function jac(a:Set<string>,b:Set<string>){if(!a.size&&!b.size)return 1;let i=0;for(const x of a)if(b.has(x))i++;return(a.size+b.size-i)?i/(a.size+b.size-i):0}
function structural(t:string[]){return new Set(t.filter(x=>x.length>1||['{','}','(',')','[',']','<','>','=',':',';','!','?','%','/','*','+','-','=>','===','!==','==','!=','>=','<=','&&','||','${'].includes(x)))}
function balanced(src:string){const p:any={'(':')','[':']','{':'}'},st:string[]=[];let q='';for(let i=0;i<src.length;i++){const c=src[i];if(q){if(c==='\\'){i++;continue}if(c===q)q='';continue}if(['"',"'",'`'].includes(c)){q=c;continue}if(p[c])st.push(p[c]);else if([')',']','}'].includes(c)&&st.pop()!==c)return false}return st.length===0&&!q}
function syntax(lang:string,src:string){const l=low(lang),v=strip(l,src);if(!v.trim())return false;if(['javascript','js'].includes(l)){try{new Function(v);return true}catch{return false}}return balanced(v)}
const RESERVED:any={javascript:new Set('break case catch class const continue debugger default delete do else export extends finally for function if import in instanceof let new return super switch this throw try typeof var void while with yield async await true false null undefined document window console math json array object string number boolean date promise set map queryselector queryselectorall getelementbyid addeventlistener textcontent innerhtml value classlist'.split(' ')),python:new Set('and as assert async await break class continue def del elif else except false finally for from global if import in is lambda none nonlocal not or pass raise return true try while with yield print input len int float str bool list dict set tuple range enumerate zip min max sum abs round'.split(' ')),kotlin:new Set('as break class continue do else false for fun if in interface is null object package return super this throw true try typealias typeof val var when while import override private public protected internal open data sealed abstract enum android bundle button textview linearlayout appcompatactivity gravity setcontentview setonclicklistener'.split(' '))};
function canonicalTokens(lang:string,src:string){const l=low(lang),base=tokens(l,src),reserved=RESERVED[l==='js'?'javascript':l==='py'?'python':l==='kt'?'kotlin':l];if(!reserved)return base;return base.map((t,i)=>{if(!/^[A-Za-z_$À-ÿ][\w$À-ÿ-]*$/.test(t)||reserved.has(t))return t;return(base[i-1]||'')==='.'?t:'<id>'})}
function codeScore(lang:string,student:string,reference:string){const rawS=tokens(lang,student),rawR=tokens(lang,reference),s=canonicalTokens(lang,student),r=canonicalTokens(lang,reference);if(!s.length)return{score:0,syntax_ok:false};const ok=syntax(lang,student),exact=s.length===r.length&&s.every((x,i)=>x===r[i]);if(exact&&ok)return{score:100,syntax_ok:true,exact:true,canonical_match:true,token_f1:100,sequence:100,structure:100};const tf=f1(s,r),seq=jac(pairs(s),pairs(r)),str=jac(structural(s),structural(r)),literal=f1(rawS,rawR);let score=Math.round((tf*.45+seq*.25+str*.20+literal*.10)*100);if(!ok)score=Math.min(score,70);return{score:Math.max(0,Math.min(99,score)),syntax_ok:ok,exact:false,canonical_match:false,token_f1:Math.round(tf*100),sequence:Math.round(seq*100),structure:Math.round(str*100)}}
function promptLabels(ref:string){return String(ref||'').split(/\r?\n/).map(x=>x.trim()).map(x=>x.match(/^(?:[-*]|\d+[.)])\s*([^:]{3,80}):/i)?.[1]?.trim()).filter(Boolean)as string[]}
function textScore(student:string,reference:string){const s=String(student||'').trim(),labels=promptLabels(reference);if(!s)return{score:0,prompt_coverage:0,length_score:0};const lower=s.toLowerCase();let hit=0;for(const label of labels){const words=label.toLowerCase().split(/\s+/).filter(w=>w.length>3);if(words.some(w=>lower.includes(w)))hit++}const coverage=labels.length?hit/labels.length:Math.min(1,s.length/300),length=Math.min(1,s.length/Math.max(240,labels.length*55));return{score:Math.min(100,Math.round((coverage*.55+length*.45)*100)),prompt_coverage:Math.round(coverage*100),length_score:Math.round(length*100)}}
async function historicalGrade(db:any,row:any){
 const [{data:refs,error:re},{data:files,error:fe},{data:exercise}]=await Promise.all([db.from('exercise_reference_files').select('filename,language,content,updated_at').eq('exercise_id',row.exercise_id).order('filename'),db.from('student_files').select('filename,language,content,revision,saved_at,created_at').eq('student_id',row.student_id).eq('exercise_id',row.exercise_id).order('filename'),db.from('exercises').select('subject_id,exercise_number').eq('id',row.exercise_id).maybeSingle()]);if(re||fe)throw re||fe;if(!(refs||[]).length)return{skipped:true,reason:'reference_unavailable'};
 const{data:subject}=exercise?.subject_id?await db.from('subjects').select('slug').eq('id',exercise.subject_id).maybeSingle():{data:null};let historical:any[]=[];try{const{data,error}=await db.from('exercise_reference_file_versions').select('id,filename,language,content,version_key,label,source_kind,source_ref,effective_from,is_current,active').eq('exercise_id',row.exercise_id).eq('active',true).order('filename');if(!error)historical=data||[]}catch(_){historical=[]}
 const subjectSlug=low(subject?.slug),referenceOnly=(refs||[]).filter((ref:any)=>subjectSlug==='programacao-mobile-sub'&&low(ref.filename)==='referencia.md'),gradedRefs=(refs||[]).filter((ref:any)=>!referenceOnly.includes(ref)),map=new Map((files||[]).map((f:any)=>[low(f.filename),f])),details:any[]=[];let weighted=0,total=0,currentMatches=0,legacyMatches=0;
 for(const ref of gradedRefs){const current=String(ref.content||''),refLang=low(ref.language||'text'),weight=Math.max(1,tokens(refLang,current).length||current.length/20||1);total+=weight;let student:any=null;for(const n of aliases(ref.filename)){if(map.has(n)){student=map.get(n);break}}const candidates:any[]=[{...ref,is_current:true,version_key:'current',label:'Atual • sincronizada'}];for(const candidate of historical)if(aliases(ref.filename).some(n=>aliases(candidate.filename).includes(n)))candidates.push(candidate);if(!student){details.push({filename:null,reference_filename:ref.filename,language:refLang,score:0,missing:true,empty:true});continue}const content=String(student.content||''),language=low(student.language||ref.language||'text'),empty=!content.trim();let best:any=null;for(const candidate of candidates){const result=empty?{score:0,syntax_ok:false,empty:true}:((['markdown','md','text'].includes(language)&&low(ref.filename)==='referencia.md')?textScore(content,String(candidate.content||'')):codeScore(language,content,String(candidate.content||'')));if(!best||Number(result.score)>Number(best.result.score)||(Number(result.score)===Number(best.result.score)&&candidate.is_current&&!best.candidate.is_current))best={candidate,result}}const result=best?.result||{score:0,syntax_ok:false},matched=best?.candidate||candidates[0];weighted+=Number(result.score||0)*weight;if(matched.is_current)currentMatches++;else legacyMatches++;details.push({filename:student.filename,reference_filename:ref.filename,language,missing:false,empty,...result,matched_reference_version_key:matched.version_key||null,matched_reference_label:matched.label||matched.source_ref||'Referência histórica',matched_reference_current:Boolean(matched.is_current)})}
 const score=clampScore(total?weighted/total:0),required=subjectSlug==='programacao-front-end'?['index.html','estilo.css','script.js']:subjectSlug==='programacao-mobile-sub'?(Number(exercise?.exercise_number)===4?['MainActivity.kt','strings.xml']:['MainActivity.kt']):[],requiredIncomplete=required.filter(name=>{const detail=details.find((d:any)=>aliases(name).includes(low(d.reference_filename)));return!detail||detail.missing||detail.empty}),stamp=new Date().toISOString();return{skipped:false,score,details:{version:'historical-regrade-v1-reference-history',score,files:details,reference_files:gradedRefs.length,reference_files_total:(refs||[]).length,reference_variants:historical.length,reference_match:legacyMatches&&currentMatches?'mixed':legacyMatches?'legacy':'current',current_file_matches:currentMatches,legacy_file_matches:legacyMatches,student_files:(files||[]).length,subject:subject?.slug||null,required_files:required,required_incomplete:requiredIncomplete,graded_at:stamp,regraded_by_staff:true}};
}
Deno.serve(async r=>{if(r.method==='OPTIONS')return new Response('ok',{headers:H});try{
 const url=Deno.env.get('SUPABASE_URL')!, key=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!, ah=r.headers.get('Authorization')||'';
 const a=createClient(url,Deno.env.get('SUPABASE_ANON_KEY')!,{global:{headers:{Authorization:ah}}}), db=createClient(url,key,{auth:{persistSession:false}});
 const {data:{user}}=await a.auth.getUser(); if(!user?.email)return J({error:'unauthorized'},401); const live=await requireLiveAuthSession(db,ah,user.id);if(!live.ok)return J({error:live.error,detail:live.detail||null},live.status);
 const [{data:p},{data:w}]=await Promise.all([db.from('profiles').select('role,active,must_change_password').eq('id',user.id).maybeSingle(),db.from('staff_allowlist').select('role,active,full_name').eq('email',user.email.toLowerCase()).eq('active',true).maybeSingle()]);
 const role=String(w?.role||p?.role||''); if(!p?.active)return J({error:'forbidden'},403);if(p.must_change_password)return J({error:'password_change_required'},403);if(!['teacher','admin','super_admin'].includes(role))return J({error:'forbidden'},403); const admin=['admin','super_admin'].includes(role);
 const {data:ta}=admin?{data:[]} : await db.from('teacher_classes').select('class_id').eq('teacher_email',user.email.toLowerCase()).eq('active',true); const assigned=(ta||[]).map((x:any)=>String(x.class_id));
 const exFor=async(cs:string[])=>{if(!cs.length)return[];const [{data:m},{data:e},{data:s}]=await Promise.all([db.from('class_subjects').select('subject_id').in('class_id',cs).eq('active',true),db.from('exercises').select('id,class_id,subject_id,exercise_number,title,active,config').eq('active',true),db.from('subjects').select('id,slug')]);const ss=new Set((m||[]).map((x:any)=>String(x.subject_id))),cc=new Set(cs),slugs=new Map((s||[]).map((x:any)=>[String(x.id),String(x.slug||'')]));return(e||[]).filter((x:any)=>x.class_id?cc.has(String(x.class_id)):ss.has(String(x.subject_id))).map((x:any)=>({...x,subject_slug:slugs.get(String(x.subject_id))||''}))};
 const scope=async(sid:string,eid?:string)=>{if(admin)return;const {data:m}=await db.from('class_memberships').select('class_id').eq('user_id',sid).eq('active',true);const aa=new Set(assigned),cs=(m||[]).map((x:any)=>String(x.class_id)).filter((x:string)=>aa.has(x));if(!cs.length)throw new S('student_out_of_scope');if(eid){const es=await exFor(cs);if(!es.some((x:any)=>String(x.id)===eid))throw new S('exercise_out_of_scope')}};
 const b=await r.json().catch(()=>({})), act=b.action||'overview';
 if(act==='staff_status')return J({staff:true,role,full_name:w?.full_name||null,assigned_class_ids:admin?null:assigned});
 if(act==='overview'){
  const [{data:c},{data:m},{data:pr},{data:g},{data:e},{data:q},{data:s}]=await Promise.all([db.from('classes').select('id,code,name,shift,school_year,active').eq('active',true),db.from('class_memberships').select('class_id,user_id,active').eq('active',true),db.from('profiles').select('id,full_name,email,role,active,last_login_at').eq('role','student').eq('active',true),db.from('student_exercises').select('student_id,exercise_id,status,progress_percent,attempts,started_at,auto_score,auto_score_at,submitted_score,submitted_at,last_activity_at,completed_at,approval_status,teacher_feedback,teacher_feedback_at,security_locked,security_lock_reason,security_locked_at,completion_source'),db.from('exercises').select('id,subject_id,class_id,exercise_number,title,active,config').eq('active',true),db.from('student_preregistrations').select('id,full_name,institutional_email,cgm,class_id,enrollment_status,active,claimed_user_id,claimed_at'),db.from('subjects').select('id,slug')]);
  const slugs=new Map((s||[]).map((x:any)=>[String(x.id),String(x.slug||'')])),exercises=(e||[]).map((x:any)=>({...x,subject_slug:slugs.get(String(x.subject_id))||''}));
  if(admin)return J({classes:c||[],memberships:m||[],profiles:pr||[],progress:g||[],exercises,preregistrations:(q||[]).map((x:any)=>({...x,cgm:undefined,has_cgm:!!x.cgm})),scope:'global'});
  const cc=new Set(assigned),mm=(m||[]).filter((x:any)=>cc.has(String(x.class_id))),ids=new Set(mm.map((x:any)=>String(x.user_id))),ee=await exFor(assigned),eids=new Set(ee.map((x:any)=>String(x.id)));
  return J({classes:(c||[]).filter((x:any)=>cc.has(String(x.id))),memberships:mm,profiles:(pr||[]).filter((x:any)=>ids.has(String(x.id))),progress:(g||[]).filter((x:any)=>ids.has(String(x.student_id))&&eids.has(String(x.exercise_id))),exercises:ee,preregistrations:(q||[]).filter((x:any)=>cc.has(String(x.class_id))).map((x:any)=>({id:x.id,full_name:x.full_name,institutional_email:x.institutional_email,class_id:x.class_id,enrollment_status:x.enrollment_status,active:x.active,claimed_user_id:x.claimed_user_id,claimed_at:x.claimed_at,has_cgm:!!x.cgm})),scope:'assigned',assigned_class_ids:assigned});
 }
 if(['historical_regrade_preview','historical_regrade_apply'].includes(act)){
  const apply=act==='historical_regrade_apply';if(apply&&b.confirmed!==true)return J({error:'explicit_confirmation_required'},409);
  const classId=String(b.class_id||''),limit=Math.max(1,Math.min(apply?40:30,Number(b.limit||30)));let allowedStudents:string[]|null=null;
  if(classId){if(!admin&&!assigned.includes(classId))return J({error:'class_out_of_scope'},403);const{data:mm}=await db.from('class_memberships').select('user_id').eq('class_id',classId).eq('active',true);allowedStudents=(mm||[]).map((x:any)=>String(x.user_id));if(!allowedStudents.length)return J({ok:true,mode:apply?'apply':'preview',candidates:0,processed:0,updated:0,skipped:0,items:[]});}
  let query=db.from('student_exercises').select('student_id,exercise_id,status,progress_percent,submitted_score,submitted_at,auto_score,auto_score_at,approval_status,completion_source,completed_at,metadata').or('submitted_at.not.is.null,auto_score_at.not.is.null').not('completion_source','in','(historical_regrade_completed,historical_regrade_partial)').order('submitted_at',{ascending:true,nullsFirst:false}).limit(limit*3);
  if(allowedStudents)query=query.in('student_id',allowedStudents);const{data:raw,error:qe}=await query;if(qe)throw qe;const candidates:any[]=[];
  for(const row of raw||[]){if(candidates.length>=limit)break;if(['manual_review_approved','manual_review_changes_requested'].includes(String(row.completion_source||'')))continue;if(!admin){try{await scope(String(row.student_id),String(row.exercise_id))}catch(_){continue}}candidates.push(row)}
  const items:any[]=[];let applied=0,updated=0,skipped=0;
  for(const row of candidates){try{const result=await historicalGrade(db,row);if(result.skipped){skipped++;items.push({student_id:row.student_id,exercise_id:row.exercise_id,skipped:true,reason:result.reason});continue}const previous=row.submitted_score==null?null:clampScore(row.submitted_score),official=Math.max(previous??0,result.score),stamp=new Date().toISOString(),changed=previous===null||official!==previous||!row.auto_score_at;const item:any={student_id:row.student_id,exercise_id:row.exercise_id,previous_score:previous,computed_score:result.score,official_score:official,changed,required_incomplete:result.details.required_incomplete||[],files:(result.details.files||[]).map((f:any)=>({filename:f.filename||f.reference_filename,score:f.score,missing:!!f.missing,empty:!!f.empty,syntax_ok:f.syntax_ok}))};
    if(apply){const completed=official>=100||String(row.status)==='completed'||String(row.approval_status)==='approved',patch:any={auto_score:result.score,auto_score_at:stamp,autograde_details:result.details,submitted_score:official,submitted_at:row.submitted_at||stamp,progress_percent:completed?100:Math.min(99,official),status:completed?'completed':'in_progress',completed_at:completed?(row.completed_at||stamp):null,completion_source:completed?'historical_regrade_completed':'historical_regrade_partial',last_activity_at:stamp,metadata:{...(row.metadata||{}),historical_regrade:{computed_score:result.score,official_score:official,regraded_at:stamp,regraded_by:user.id,authority:'staff-dashboard-historical-regrade-v1',score_changed:changed}}};const{error}=await db.from('student_exercises').update(patch).eq('student_id',row.student_id).eq('exercise_id',row.exercise_id);if(error)throw error;applied++;if(changed)updated++;item.applied=true}
    items.push(item);
   }catch(error){skipped++;items.push({student_id:row.student_id,exercise_id:row.exercise_id,skipped:true,reason:String((error as Error)?.message||error)})}}
  return J({ok:true,mode:apply?'apply':'preview',candidates:candidates.length,processed:items.length,applied,updated,skipped,has_more:(raw||[]).length>candidates.length,items,policy:{never_reduces_score:true,manual_reviews_preserved:true,batch_limit:limit}});
 }
 const sid=String(b.student_id||''), eid=String(b.exercise_id||'');
 if(act==='student_detail'){if(!sid)return J({error:'missing_parameters'},400);await scope(sid);const [{data:g},{data:x},{data:y},{data:ar}]=await Promise.all([db.from('student_exercises').select('*').eq('student_id',sid),db.from('student_accommodations').select('*').eq('student_id',sid).eq('active',true),db.from('exercise_releases').select('*').eq('student_id',sid),db.from('pedagogical_adaptation_requests').select('id,status,request_source,created_at,updated_at,resolved_at').eq('student_id',sid).order('created_at',{ascending:false}).limit(10)]);if(admin)return J({progress:g||[],accommodations:x||[],releases:y||[],adaptation_requests:ar||[]});const {data:m}=await db.from('class_memberships').select('class_id').eq('user_id',sid).eq('active',true);const aa=new Set(assigned),cs=(m||[]).map((z:any)=>String(z.class_id)).filter((z:string)=>aa.has(z)),es=await exFor(cs),ei=new Set(es.map((z:any)=>String(z.id)));return J({progress:(g||[]).filter((z:any)=>ei.has(String(z.exercise_id))),accommodations:(x||[]).filter((z:any)=>!z.exercise_id||ei.has(String(z.exercise_id))),releases:(y||[]).filter((z:any)=>ei.has(String(z.exercise_id))),adaptation_requests:ar||[]});}
 if(act==='experience_overview'){
  const [{data:classes},{data:memberships},{data:profiles},{data:accommodations},{data:prefs},{data:modePrefs},{data:assignments},{data:xp},{data:events},{data:studentProgress},{data:exercises},{data:subjects}]=await Promise.all([
    db.from('classes').select('id,code,name').eq('active',true),
    db.from('class_memberships').select('class_id,user_id,is_primary,active').eq('active',true),
    db.from('profiles').select('id,full_name,email,last_login_at').eq('role','student').eq('active',true),
    db.from('student_accommodations').select('student_id,config,updated_at').is('exercise_id',null).eq('accommodation_type','learning_mode').eq('active',true),
    db.from('pedagogical_learning_preferences').select('*'),
    db.from('pedagogical_adaptation_preferences').select('student_id,adaptation_key,mode,updated_at'),
    db.from('pedagogical_experience_assignments').select('*').order('display_order').order('created_at'),
    db.from('pedagogical_experience_progress').select('*'),
    db.from('pedagogical_experience_events').select('id,student_id,assignment_id,adaptation_key,subject_slug,event_type,mode,metadata,occurred_at').order('occurred_at',{ascending:false}).limit(800),
    db.from('student_exercises').select('student_id,exercise_id,status,progress_percent,last_activity_at,completed_at,submitted_score'),
    db.from('exercises').select('id,subject_id,exercise_number,title,active').eq('active',true),
    db.from('subjects').select('id,slug,name')
  ]);
  const classMap=new Map((classes||[]).map((x:any)=>[String(x.id),x])),subjectMap=new Map((subjects||[]).map((x:any)=>[String(x.id),x])),exerciseMap=new Map((exercises||[]).map((x:any)=>[String(x.id),x]));
  const allowedIds=new Set<string>();
  if(admin){for(const p of profiles||[])allowedIds.add(String(p.id));}
  else{const aa=new Set(assigned);for(const m of memberships||[])if(aa.has(String(m.class_id)))allowedIds.add(String(m.user_id));}
  const classByStudent=new Map<string,any>();for(const m of memberships||[]){const uid=String(m.user_id);if(!allowedIds.has(uid))continue;const current=classByStudent.get(uid);if(!current||m.is_primary)classByStudent.set(uid,classMap.get(String(m.class_id))||null);}
  const rows=(profiles||[]).filter((p:any)=>allowedIds.has(String(p.id))).map((p:any)=>{
   const id=String(p.id);
   const acc=(accommodations||[]).filter((x:any)=>String(x.student_id)===id).sort((a:any,b:any)=>Date.parse(b.updated_at||0)-Date.parse(a.updated_at||0))[0]||null;
   const adaptationKey=String(acc?.config?.profile_key||acc?.config?.adaptation_profile||'support');
   const conventional=(studentProgress||[]).filter((x:any)=>String(x.student_id)===id).map((x:any)=>{
    const ex=exerciseMap.get(String(x.exercise_id)),sub=subjectMap.get(String(ex?.subject_id));
    return {...x,exercise_number:ex?.exercise_number||null,exercise_title:ex?.title||null,subject_slug:sub?.slug||null,subject_name:sub?.name||null};
   });
   return {student_id:id,full_name:p.full_name,email:p.email,last_login_at:p.last_login_at,class:classByStudent.get(id)||null,adaptation:acc,preference:(prefs||[]).find((x:any)=>String(x.student_id)===id)||null,mode_preference:(modePrefs||[]).filter((x:any)=>String(x.student_id)===id&&String(x.adaptation_key)===adaptationKey).sort((a:any,b:any)=>Date.parse(b.updated_at||0)-Date.parse(a.updated_at||0))[0]||null,assignments:(assignments||[]).filter((x:any)=>String(x.student_id)===id),experience_progress:(xp||[]).filter((x:any)=>String(x.student_id)===id),events:(events||[]).filter((x:any)=>String(x.student_id)===id).slice(0,120),conventional_progress:conventional};
  });
  return J({students:rows,scope:admin?'global':'assigned'});
 }
 if(act==='update_experience_assignment'){
  const id=String(b.id||'');if(!id)return J({error:'missing_parameters'},400);
  const {data:row}=await db.from('pedagogical_experience_assignments').select('id,student_id').eq('id',id).maybeSingle();if(!row)return J({error:'not_found'},404);await scope(String(row.student_id));
  const patch:any={updated_at:new Date().toISOString()};
  if(Object.prototype.hasOwnProperty.call(b,'deadline'))patch.deadline=b.deadline?String(b.deadline):null;
  if(Object.prototype.hasOwnProperty.call(b,'active'))patch.active=b.active===true;
  if(Object.prototype.hasOwnProperty.call(b,'display_order'))patch.display_order=Math.max(0,Math.min(999,Number(b.display_order||0)));
  if(Object.prototype.hasOwnProperty.call(b,'extra_time_minutes'))patch.extra_time_minutes=Math.max(0,Math.min(1440,Number(b.extra_time_minutes||0)));
  const {data,error}=await db.from('pedagogical_experience_assignments').update(patch).eq('id',id).select().single();if(error)throw error;return J({ok:true,assignment:data});
 }
 if(act==='create_experience_assignment'){
  const studentId=String(b.student_id||''),subjectSlug=String(b.subject_slug||'').trim(),subjectName=String(b.subject_name||'').trim(),title=String(b.title||'').trim(),purpose=String(b.purpose||'complementary'),instruction=String(b.instruction||'').trim();
  if(!studentId||!subjectSlug||!subjectName||!title||!instruction)return J({error:'missing_parameters'},400);
  if(!['evaluation','recovery','complementary','extra','practice'].includes(purpose))return J({error:'invalid_purpose'},400);
  await scope(studentId);
  const {data:acc}=await db.from('student_accommodations').select('config').eq('student_id',studentId).is('exercise_id',null).eq('accommodation_type','learning_mode').eq('active',true).order('updated_at',{ascending:false}).limit(1).maybeSingle();
  if(!acc)return J({error:'personalized_experience_not_enabled'},409);
  const adaptationKey=String(acc.config?.profile_key||acc.config?.adaptation_profile||'support'),now=new Date().toISOString(),keyPart=crypto.randomUUID().slice(0,8);
  const row:any={student_id:studentId,adaptation_key:adaptationKey,subject_slug:subjectSlug.slice(0,120),subject_name:subjectName.slice(0,180),experience_key:`teacher-${Date.now()}-${keyPart}`,title:title.slice(0,180),purpose,deadline:b.deadline?String(b.deadline):null,extra_time_minutes:Math.max(0,Math.min(1440,Number(b.extra_time_minutes||0))),display_order:Math.max(0,Math.min(999,Number(b.display_order||50))),active:true,created_by:user.id,updated_at:now,config:{summary:instruction.slice(0,700),kicker:'Atividade personalizada',heading:title.slice(0,180),intro:'Atividade atribuída pelo professor e organizada separadamente do histórico convencional.',steps:[{id:'orientacao',type:'message',title:'Orientação do professor',text:instruction.slice(0,2500)}]}};
  const {data,error}=await db.from('pedagogical_experience_assignments').insert(row).select().single();if(error)throw error;return J({ok:true,assignment:data});
 }
 if(act==='log_teacher_preview'){
  const studentId=String(b.student_id||''),assignmentId=b.assignment_id?String(b.assignment_id):null;if(!studentId)return J({error:'missing_parameters'},400);await scope(studentId);
  const {data:acc}=await db.from('student_accommodations').select('config').eq('student_id',studentId).is('exercise_id',null).eq('accommodation_type','learning_mode').eq('active',true).order('updated_at',{ascending:false}).limit(1).maybeSingle();
  const {error}=await db.from('pedagogical_experience_events').insert({student_id:studentId,assignment_id:assignmentId,adaptation_key:String(acc?.config?.profile_key||acc?.config?.adaptation_profile||'support'),event_type:'teacher_preview_opened',mode:'adapted',metadata:{viewer_id:user.id,viewer_role:role,source:'staff_preview'},occurred_at:new Date().toISOString()});if(error)throw error;return J({ok:true});
 }
 if(act==='student_files'){if(!sid||!eid)return J({error:'missing_parameters'},400);await scope(sid,eid);const {data,error}=await db.from('student_files').select('id,filename,language,content,revision,saved_at').eq('student_id',sid).eq('exercise_id',eid).order('filename');if(error)throw error;return J({files:data||[]});}
 if(act==='resolve_adaptation_request'){const id=String(b.id||''),status=String(b.status||'approved');if(!id||!['approved','declined','closed'].includes(status))return J({error:'invalid_request'},400);const {data:reqRow}=await db.from('pedagogical_adaptation_requests').select('student_id').eq('id',id).maybeSingle();if(!reqRow)return J({error:'not_found'},404);await scope(String(reqRow.student_id));const {error}=await db.from('pedagogical_adaptation_requests').update({status,resolved_at:new Date().toISOString(),resolved_by:user.id,updated_at:new Date().toISOString()}).eq('id',id);if(error)throw error;return J({ok:true});}
 if(act==='set_accommodation'){if(!sid)return J({error:'missing_parameters'},400);const globalScope=b.global_scope===true||!eid;await scope(sid,globalScope?undefined:eid);const type=String(b.accommodation_type||'support');if(globalScope){const {data:old}=await db.from('student_accommodations').select('id').eq('student_id',sid).is('exercise_id',null).eq('accommodation_type',type).eq('active',true).order('updated_at',{ascending:false}).limit(1).maybeSingle();const patch={student_id:sid,exercise_id:null,accommodation_type:type,config:b.config||{},reason:String(b.reason||''),active:true,created_by:user.id,updated_at:new Date().toISOString()};const z=old?.id?await db.from('student_accommodations').update(patch).eq('id',old.id).select().single():await db.from('student_accommodations').insert(patch).select().single();if(z.error)throw z.error;return J({ok:true,accommodation:z.data});}const {data,error}=await db.from('student_accommodations').insert({student_id:sid,exercise_id:eid,accommodation_type:type,config:b.config||{},reason:String(b.reason||''),active:true,created_by:user.id}).select().single();if(error)throw error;return J({ok:true,accommodation:data});}
 if(act==='disable_accommodation'){const id=String(b.id||'');const {data:x}=await db.from('student_accommodations').select('student_id,exercise_id').eq('id',id).maybeSingle();if(!x)return J({error:'not_found'},404);await scope(String(x.student_id),x.exercise_id?String(x.exercise_id):undefined);const {error}=await db.from('student_accommodations').update({active:false,updated_at:new Date().toISOString()}).eq('id',id);if(error)throw error;return J({ok:true});}
 if(act==='set_release'){if(!sid||!eid)return J({error:'missing_parameters'},400);await scope(sid,eid);const patch={student_id:sid,exercise_id:eid,class_id:null,enabled:b.enabled!==false,allow_html_base:b.allow_html_base??null,allow_css_base:b.allow_css_base??null,allow_js_base:b.allow_js_base??null,allow_extra_hints:b.allow_extra_hints??null,allow_guided_support:b.allow_guided_support??null,created_by:user.id,updated_at:new Date().toISOString()};const {data:o}=await db.from('exercise_releases').select('id').eq('student_id',sid).eq('exercise_id',eid).maybeSingle();const z=o?.id?await db.from('exercise_releases').update(patch).eq('id',o.id).select().single():await db.from('exercise_releases').insert(patch).select().single();if(z.error)throw z.error;return J({ok:true,release:z.data});}
 if(act==='manual_review'){const st=String(b.approval_status||'pending');if(!sid||!eid||!['not_required','pending','approved','changes_requested'].includes(st))return J({error:'invalid_parameters'},400);await scope(sid,eid);const {data:current}=await db.from('student_exercises').select('progress_percent,status').eq('student_id',sid).eq('exercise_id',eid).maybeSingle();if(!current)return J({error:'progress_not_found'},404);const n=new Date().toISOString(),patch:any={approval_status:st,teacher_feedback:String(b.teacher_feedback||'')||null,teacher_feedback_at:n,last_activity_at:n};if(st==='approved')Object.assign(patch,{approved_by:user.id,approved_at:n,status:'completed',progress_percent:100,completed_at:n,completion_source:'manual_review_approved'});if(st==='changes_requested')Object.assign(patch,{approved_by:null,approved_at:null,status:'in_progress',progress_percent:Math.min(99,Math.max(0,Number(current.progress_percent||0))),completed_at:null,completion_source:'manual_review_changes_requested'});const {data,error}=await db.from('student_exercises').update(patch).eq('student_id',sid).eq('exercise_id',eid).select().maybeSingle();if(error)throw error;return J({ok:true,progress:data});}
 return J({error:'unknown_action'},400);
}catch(e){if(e instanceof S)return J({error:e.message},403);return J({error:'internal_error',detail:String((e as Error)?.message||e)},500)}});
