'use strict';
(function(){
  window.LABDS_LABS=window.LABDS_LABS||{};const KEY='lab.iptv.state';let root,ctx,state,timer=null,phase=0;
  const $=s=>root.querySelector(s),$$=s=>[...root.querySelectorAll(s)],clamp=(n,a,b)=>Math.min(b,Math.max(a,Number(n)||0));
  const CHANNELS=[{name:'Tech News',resolution:'1080p',bitrate:5.5,color:'#55d6ff'},{name:'Aula de Redes',resolution:'720p',bitrate:2.8,color:'#7f6cff'},{name:'Laboratório 3D',resolution:'4K',bitrate:18,color:'#43e6a8'},{name:'Canal de Dados',resolution:'1080p',bitrate:6.2,color:'#ffcf5d'}];
  function defaults(){return{mode:'unicast',connection:'wifi',bandwidth:25,latency:35,jitter:8,loss:1,quality:'auto',tvs:[0,1,2,3],history:[]};}
  function demand(){if(state.mode==='multicast')return Math.max(...state.tvs.map(i=>CHANNELS[i].bitrate));return state.tvs.reduce((sum,i)=>sum+CHANNELS[i].bitrate,0);}
  function metrics(index){const channel=CHANNELS[state.tvs[index]],share=state.mode==='multicast'?state.bandwidth:state.bandwidth/state.tvs.length,available=share*(1-state.loss/100),ratio=available/channel.bitrate,buffer=Math.max(0,Math.min(100,(ratio-0.55)*150-state.jitter*.7)),freeze=ratio<.8||state.loss>5||state.jitter>35,quality=state.quality==='auto'?(ratio>2?'1080p':ratio>1?'720p':'480p'):state.quality;return{channel,available,buffer,freeze,quality,delay:state.latency+state.jitter*(.5+Math.random())};}
  function tick(){phase++;const values=state.tvs.map((_,index)=>metrics(index));state.history.push({at:Date.now(),bandwidth:state.bandwidth,demand:demand(),buffer:values.reduce((s,v)=>s+v.buffer,0)/values.length});state.history=state.history.slice(-80);renderTvs(values);draw();ctx.storage.set(KEY,state);}
  function renderTvs(values=state.tvs.map((_,i)=>metrics(i))){const host=$('#iptvTvs');host.innerHTML=values.map((m,index)=>`<article class="iptv-tv ${m.freeze?'freeze':''}"><div class="tv-screen" style="--channel:${m.channel.color}"><span class="scan-lines"></span><strong>${m.freeze?'BUFFER...':m.channel.name}</strong><small>${m.quality} • ${m.channel.bitrate} Mb/s</small></div><select data-tv-index="${index}">${CHANNELS.map((ch,i)=>`<option value="${i}" ${state.tvs[index]===i?'selected':''}>${ch.name}</option>`).join('')}</select><dl><dt>Disponível</dt><dd>${m.available.toFixed(1)} Mb/s</dd><dt>Buffer</dt><dd>${m.buffer.toFixed(0)}%</dd><dt>Atraso</dt><dd>${m.delay.toFixed(0)} ms</dd></dl></article>`).join('');$$('[data-tv-index]').forEach(select=>select.onchange=()=>{state.tvs[Number(select.dataset.tvIndex)]=Number(select.value);ctx.storage.set(KEY,state);tick();});$('#iptvDemand').textContent=`${demand().toFixed(1)} Mb/s`;$('#iptvStatus').textContent=demand()>state.bandwidth?'Rede congestionada':'Capacidade suficiente';$('#iptvStatus').className=demand()>state.bandwidth?'warning':'ok';}
  function draw(){const canvas=$('#iptvChart');if(!canvas)return;const c=canvas.getContext('2d'),w=canvas.width,h=canvas.height;c.clearRect(0,0,w,h);c.fillStyle='#07111f';c.fillRect(0,0,w,h);const max=Math.max(10,...state.history.flatMap(v=>[v.bandwidth,v.demand]));[['bandwidth','#55d6ff'],['demand','#ff6f8d']].forEach(([key,color])=>{c.strokeStyle=color;c.lineWidth=3;c.beginPath();state.history.forEach((p,i)=>{const x=30+i*(w-50)/Math.max(1,state.history.length-1),y=h-25-p[key]/max*(h-50);i?c.lineTo(x,y):c.moveTo(x,y);});c.stroke();});c.fillStyle='#dceaff';c.font='12px system-ui';c.fillText('Azul: banda disponível • Rosa: demanda',12,18);}
  function template(){return`<div class="iptv-lab"><header><div><span class="eyebrow">TRANSMISSÃO IP SIMULADA</span><h2>IPTV e qualidade de rede</h2><p>Canais e conteúdos são fictícios. Compare unicast, multicast, bitrate, buffer, latência, jitter e perda.</p></div><div class="iptv-controls"><label>Modo<select id="iptvMode"><option value="unicast">Unicast</option><option value="multicast">Multicast</option></select></label><label>Conexão<select id="iptvConnection"><option value="wifi">Wi-Fi</option><option value="cable">Cabo</option><option value="mobile">Rede móvel</option></select></label><label>Banda (Mb/s)<input id="iptvBandwidth" type="range" min="2" max="100" value="${state.bandwidth}"></label><label>Latência<input id="iptvLatency" type="range" min="5" max="300" value="${state.latency}"></label><label>Jitter<input id="iptvJitter" type="range" min="0" max="100" value="${state.jitter}"></label><label>Perda (%)<input id="iptvLoss" type="range" min="0" max="20" step=".5" value="${state.loss}"></label><label>Qualidade<select id="iptvQuality"><option value="auto">Automática</option><option value="480p">480p</option><option value="720p">720p</option><option value="1080p">1080p</option></select></label></div></header><section class="iptv-summary"><article><b id="iptvDemand"></b><span>demanda estimada</span></article><article><b>${state.bandwidth} Mb/s</b><span>banda configurada</span></article><article><b id="iptvStatus"></b><span>estado da rede</span></article></section><section id="iptvTvs" class="iptv-tvs"></section><section class="iptv-chart-card"><canvas id="iptvChart" width="900" height="280"></canvas><div class="state-card info"><h3>Atividade</h3><p>Faça os quatro televisores funcionarem sem congelamento usando a menor banda possível. Compare a diferença entre unicast e multicast.</p><button id="validateIptv" class="btn primary">Validar rede</button></div></section></div>`;}
  async function mount(host,context){root=host;ctx=context;state={...defaults(),...(await ctx.storage.get(KEY,{}))};root.innerHTML=template();$('#iptvMode').value=state.mode;$('#iptvConnection').value=state.connection;$('#iptvQuality').value=state.quality;['Mode','Connection','Quality'].forEach(key=>$('#iptv'+key).onchange=()=>{state[key.toLowerCase()]=$('#iptv'+key).value;tick();});['Bandwidth','Latency','Jitter','Loss'].forEach(key=>$('#iptv'+key).oninput=()=>{state[key.toLowerCase()]=Number($('#iptv'+key).value);tick();});$('#validateIptv').onclick=()=>{const values=state.tvs.map((_,i)=>metrics(i)),ok=values.every(v=>!v.freeze&&v.buffer>20);if(ok){ctx.core?.complete?.('iptv:stable',{xp:60,credits:25,reason:'Rede IPTV estável'});ctx.toast('Rede validada.','success');}else ctx.toast('Ainda há congelamento ou buffer insuficiente.','warning');};tick();timer=setInterval(tick,850);}
  async function unmount(){clearInterval(timer);await ctx?.storage?.set?.(KEY,state);root=null;ctx=null;}
  function exportPayload(){return{text:`IPTV\nModo: ${state.mode}\nBanda: ${state.bandwidth} Mb/s\nDemanda: ${demand().toFixed(1)} Mb/s`,native:JSON.stringify(state,null,2),backup:state};}
  function help(){return'<p>Unicast cria um fluxo por televisor. Multicast pode compartilhar um fluxo na rede. Bitrate, banda, jitter, latência e perda afetam buffer e qualidade.</p>';}
  window.LABDS_LABS['iptv-lab']={mount,unmount,exportPayload,help};
})();
