const definitions = [
  { id:'curiosity-center', title:'COSMOS Curioso — Enciclopédia Imersiva', icon:'?', status:'available', phase:24, tag:'Curiosidades + Tecnologia', description:'Central visual 3D/360° com busca, fontes, comparações, favoritos, coleções e conexões com programação.', loader:() => import('../../modules/curiosity-center/CuriosityCenterModule.js') },
  { id:'performance-qa', title:'Otimização e QA Final', icon:'▥', status:'available', phase:23, tag:'FPS + Memória + Pacotes', description:'Diagnóstico ao vivo, três pacotes gráficos, checklist de aceite, resolução dinâmica e relatório final.', loader:() => import('../../modules/performance-qa/PerformanceQAModule.js') },
  { id:'integrated-campaigns', title:'Campanhas Espaciais Integradas', icon:'✦', status:'available', phase:22, tag:'Lua + Marte + Estação', description:'Três campanhas cinematográficas com etapas conectadas, eventos, escolhas, checkpoints e evidências.', loader:() => import('../../modules/integrated-campaigns/IntegratedCampaignsModule.js') },
  { id:'physics-controls', title:'Física e Controles Avançados', icon:'⌁', status:'available', phase:21, tag:'6DOF + Rover + Gamepad', description:'Gravidades, primeira e terceira pessoa, microgravidade, suspensão, RCS, colisões e controles assistidos.', loader:() => import('../../modules/physics-controls/PhysicsControlsModule.js') },
  { id:'cinematic-studio', title:'Iluminação e Fotorealismo', icon:'◈', status:'available', phase:20, tag:'HDR + Sombras + Cinema', description:'Estúdio 3D/360° com exposição, PBR, bloom, sombras, AO, profundidade de campo e orçamento gráfico.', loader:() => import('../../modules/cinematic-studio/CinematicStudioModule.js') },
  { id:'premium-assets', title:'Assets Premium Animados 3D/360°', icon:'⬢', status:'available', phase:18, tag:'Rigs + glTF + PBR', description:'Oito modelos articulados com múltiplas peças, animações glTF, colliders, pontos de interação, LOD, PBR, HDR e cache offline.', loader:() => import('../../modules/premium-assets/PremiumAssetsModule.js') },
  { id:'deep-space-remaster', title:'Universo Profundo Imersivo 360°', icon:'✺', status:'available', phase:15, tag:'Galáxias + Voo livre', description:'Oito destinos cósmicos, viagem entre escalas, nebulosas volumétricas, buraco negro didático, joystick e gamepad.', loader:() => import('../../modules/deep-space-remaster/DeepSpaceRemasterModule.js') },
  { id:'visual-museum', title:'Museu Visual Espacial 3D', icon:'⬡', status:'available', phase:15, tag:'Museu + Interiores', description:'Quatro galerias, doze peças, caminhada, inspeção 360°, interiores e mecanismos animados.', loader:() => import('../../modules/visual-museum/VisualMuseumModule.js') },
  { id:'planetary-remaster', title:'Lua e Marte Imersivos 360°', icon:'◒', status:'available', phase:14, tag:'Exploração + Rover + Drone', description:'Primeira e terceira pessoa, módulo lunar, rovers, drone, braço robótico, terreno, poeira e tempestades.', loader:() => import('../../modules/lunar-mars-remaster/LunarMarsRemasterModule.js') },
  { id:'station-remaster', title:'Estação Espacial Imersiva 360°', icon:'✥', status:'available', phase:13, tag:'6DOF + EVA + Frota', description:'Quatro estações, cápsulas, ônibus espacial, satélites, interior/exterior, EVA, acoplamento e voo orbital em seis graus de liberdade.', loader:() => import('../../modules/station-remaster/StationRemasterModule.js') },
  { id:'launch-remaster', title:'Lançamentos Imersivos 360°', icon:'⬆', status:'available', phase:12, tag:'Remaster 3D + Replay', description:'Hangar 360°, ônibus espacial, câmeras internas e externas, joystick, lançamento, separação e replay cinematográfico.', loader:() => import('../../modules/launch-remaster/LaunchRemasterModule.js') },
  { id:'solar-remaster', title:'Sistema Solar Imersivo 360°', icon:'◌', status:'available', phase:11, tag:'Remaster 3D + Gamepad', description:'Voo livre, inspeção planetária, satélites, câmera cinematográfica, joysticks e shaders procedurais.', loader:() => import('../../modules/solar-remaster/SolarSystemRemasterModule.js') },
  { id:'academy', title:'Academia Espacial DS', icon:'◈', status:'available', phase:1, tag:'Fundamentos', description:'Sensores, processamento, atuadores, telemetria e primeiro desafio interativo.', loader:() => import('../../modules/academy/AcademyModule.js') },
  { id:'mission-control', title:'Centro de Controle', icon:'⌁', status:'available', phase:1, tag:'Telemetria', description:'Console operacional com fluxo de dados, alertas, estados e diagnóstico de anomalias.', loader:() => import('../../modules/mission-control/MissionControlModule.js') },
  { id:'history', title:'Museu da Computação Espacial', icon:'⌛', status:'available', phase:2, tag:'História + Código', description:'Linha do tempo animada com Mercury, Gemini, Apollo, estações, robótica e frameworks.', loader:() => import('../../modules/history/HistoryModule.js') },
  { id:'people', title:'Pessoas e Equipes de Missão', icon:'✦', status:'available', phase:2, tag:'Pessoas + Papéis', description:'Galeria holográfica, contribuições profissionais e visão sistêmica das equipes.', loader:() => import('../../modules/people/PeopleModule.js') },
  { id:'languages', title:'Linguagens Espaciais', icon:'</>', status:'available', phase:2, tag:'Arquitetura', description:'Assembly, C, C++, Python, TypeScript e SQL escolhidos conforme o problema.', loader:() => import('../../modules/languages/LanguagesModule.js') },
  { id:'mission-control-advanced', title:'Centro de Controle Avançado', icon:'◉', status:'available', phase:3, tag:'Sistemas críticos', description:'Web Worker, estados, filas prioritárias, replay e quatro cenários progressivos de falha.', loader:() => import('../../modules/mission-control-advanced/MissionControlAdvancedModule.js') },
  { id:'earth', title:'Terra, Satélites e Órbitas', icon:'◎', status:'available', phase:4, tag:'Geodados + WebGL', description:'Globo procedural, mecânica orbital, satélites modulares, cobertura, energia e comunicação.', loader:() => import('../../modules/earth-orbit/EarthOrbitModule.js') },
  { id:'launch', title:'Engenharia de Foguetes', icon:'▲', status:'available', phase:5, tag:'Laboratório técnico', description:'Configuração, cálculos, intertravamentos, Worker físico, falhas e inserção orbital com foco em engenharia.', loader:() => import('../../modules/launch/LaunchModule.js') },
  { id:'moon', title:'Lua e Apollo', icon:'◐', status:'available', phase:6, tag:'Assembly + GLSL', description:'História Apollo, computador didático, prioridades, pouso, rover e ciência lunar.', loader:() => import('../../modules/moon-apollo/MoonApolloModule.js') },
  { id:'mars', title:'Marte e Robótica', icon:'●', status:'available', phase:7, tag:'Autonomia + A*', description:'Terreno procedural, rover, atraso de comunicação, A*, visão, drone e banco científico.', loader:() => import('../../modules/mars-robotics/MarsRoboticsModule.js') },
  { id:'station', title:'Estação Espacial', icon:'✣', status:'available', phase:8, tag:'360° + Sistemas', description:'Interior e exterior 3D, acoplamento, energia, suporte à vida, robótica, EVA e logística.', loader:() => import('../../modules/space-station/SpaceStationModule.js') },
  { id:'observatory', title:'Observatório e Universo Profundo', icon:'✧', status:'available', phase:9, tag:'Espectro + GLSL', description:'Planetário 360°, telescópios, imagens científicas, espectroscopia e banco de observações.', loader:() => import('../../modules/observatory/ObservatoryModule.js') },
  { id:'mission-director', title:'Direção de Missões e Professor', icon:'◆', status:'available', phase:10, tag:'Professor + XR', description:'Missões configuráveis, tempo ativo, checkpoints, evidências, Classroom, acessibilidade e WebXR opcional.', loader:() => import('../../modules/mission-director/MissionDirectorModule.js') }
];

export class ModuleRegistry {
  list() { return definitions.map(item => ({ ...item, loader: undefined })); }
  async load(id) {
    const definition = definitions.find(item => item.id === id);
    if (!definition?.loader) throw new Error('Este módulo será liberado em uma fase futura.');
    const module = await definition.loader();
    return module.createModule();
  }
}
