import assert from 'node:assert/strict';
import fs from 'node:fs';
const student=fs.readFileSync(new URL('../../prova/assets/student.js',import.meta.url),'utf8');
const sim=fs.readFileSync(new URL('../../prova/assets/simulator.js',import.meta.url),'utf8');
const css=fs.readFileSync(new URL('../../prova/assets/prova.css',import.meta.url),'utf8');
const html=fs.readFileSync(new URL('../../prova/index.html',import.meta.url),'utf8');
for(const text of ['BUSCANDO PARTIDA','SINCRONIZANDO SERVIDOR','BUSCANDO JOGADORES','MONTANDO ESQUADRÃO','CARREGANDO MISSÃO','LOBBY PRONTO']) assert.ok(student.includes(text),text);
assert.ok(student.includes('startMatchmakingSequence'), 'real student flow must start matchmaking sequence');
assert.ok(student.includes('matchmaking-live-strip'), 'waiting room must expose live tactical status strip');
for(const text of ['BUSCANDO PARTIDA','BUSCANDO JOGADORES','MONTANDO LOBBY','FORMANDO ESQUADRÃO','DEPLOYING SQUAD']) assert.ok(sim.includes(text),text);
for(const cls of ['.matchmaking-overlay','.mm-radar','.mm-player-lock','.matchmaking-live-strip']) assert.ok(css.includes(cls),cls);
assert.ok(css.includes('@media(prefers-reduced-motion:reduce)'), 'reduced motion support required');
assert.ok(css.includes('.exam-focus-mode .mm-scanlines'), 'focus mode must simplify effects');
assert.ok(/14\.10\.8\.(?:3[2-9]|[4-9]\d|\d{3,})/.test(html), 'student cache key must be bumped');
console.log('p10933 cinematic matchmaking v14.10.8.32: OK');
