import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';
const root=path.resolve(import.meta.dirname,'../..');const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const js=read('lobby/assets/lobby.js'),three=read('lobby/assets/lobby3d.js'),html=read('lobby/index.html'),cfg=read('lobby/assets/config.js');
assert.ok(/LOBBY_VERSION='0\.(7|8|9)\.0'/.test(cfg)||cfg.includes("LOBBY_VERSION='1.0.0'"));
assert.match(html,/id="campus-drawer"/);assert.match(html,/id="campus-button"/);
assert.match(js,/CAMPUS_TASKS/);assert.match(js,/localStorage\.setItem\('agv:p55:campus'/);
assert.match(js,/não concede moedas|não concede benefícios|não concede moedas/i);
assert.match(three,/Monitor AGV/);assert.match(three,/Monitor dos Labs/);assert.match(three,/campusKiosk/);assert.match(three,/meetPad/);
assert.doesNotMatch(js,/claim_core_reward|agv-reward-claim/);
console.log('PASS p5-campus-vivo-v11.9');
