import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';
const root=path.resolve(import.meta.dirname,'../..');const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const js=read('lobby/assets/lobby.js'),three=read('lobby/assets/lobby3d.js'),mobility=read('lobby/assets/world/campus-mobility-systems.js'),html=read('lobby/index.html'),cfg=read('lobby/assets/config.js');
const currentRelease=JSON.parse(read('release-current.json'));assert.ok(cfg.includes(`LOBBY_VERSION='${currentRelease.version}'`));
assert.match(html,/id="campus-drawer"/);assert.match(html,/id="campus-button"/);
assert.match(js,/CAMPUS_TASKS/);assert.match(js,/localStorage\.setItem\('agv:p55:campus'/);
assert.match(js,/não concede moedas|não concede benefícios|não concede moedas/i);
assert.match(mobility,/Monitor Tech Oeste/);assert.match(mobility,/Monitor Inovação/);assert.match(three,/campusKiosk/);assert.match(three,/meetPad/);
assert.doesNotMatch(js,/claim_core_reward|agv-reward-claim/);
console.log('PASS p5-campus-vivo-v11.9');
