import assert from 'node:assert/strict';
import fs from 'node:fs';
const js=fs.readFileSync(new URL('../../lobby/assets/lobby3d.js',import.meta.url),'utf8');
const lobby=fs.readFileSync(new URL('../../lobby/assets/lobby.js',import.meta.url),'utf8');
const cfg=fs.readFileSync(new URL('../../lobby/assets/config.js',import.meta.url),'utf8');
const currentRelease=JSON.parse(fs.readFileSync(new URL('../../release-current.json',import.meta.url),'utf8'));assert.ok(cfg.includes(`LOBBY_VERSION='${currentRelease.version}'`),'Lobby deve declarar a release corrente');
for(const marker of ['labInterior','automaticDoor','labComputer','interiorOrigins','exteriorEntrances','enterInterior','exitInterior','lab-terminal','smartboard','lab-portal']) assert.ok(js.includes(marker),`faltando ${marker}`);
for(const marker of ['building-entrance','interior-exit','lab-terminal','smartboard','lab-portal','onInteriorChange']) assert.ok(lobby.includes(marker),`lobby.js sem ${marker}`);
assert.match(js,/publicPos=activeInterior\?exteriorEntrances\[activeInterior\]:\(activeToolInterior\?CAMPUS_INTERIOR_MAP\[activeToolInterior\]\?\.entrance:null\)/,'coordenada interna não pode ser enviada como presença pública');assert.match(js,/publicPos\?worldToPresence\(publicPos\.x,publicPos\.z\):worldToPresence\(self\.position\.x,self\.position\.z\)/);
assert.ok(!js.includes('claim_core_reward'),'renderer não pode conceder recompensa');
assert.ok(!js.includes('service_role'),'renderer não pode conter service role');
console.log('PASS p5-interiores-labs-v12.1');
