import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
const root=path.resolve(import.meta.dirname,'../..');
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const exists=p=>fs.existsSync(path.join(root,p));
const html=read('lobby/index.html');
const lobby=read('lobby/assets/lobby.js');
const game=read('lobby/assets/lobby3d.js');
const environment=read('lobby/assets/world/campus-environment.js');
const camera=read('lobby/assets/render/camera-controller.js');
const avatar=read('lobby/assets/characters/avatar-system.js');
const portals=read('lobby/assets/game/portal-manager.js');
const css=read('lobby/assets/lobby.css');
const cfg=read('lobby/assets/config.js');
const securityMigration=read('core/database/029_security_hardening_ip_rate_limits.sql');
const release=JSON.parse(read('release-v11.5.json'));
assert.ok(html.includes('id="game3d"')&&game.includes('WebGLRenderer'),'canvas WebGL 3D ausente');
assert.ok(exists('lobby/vendor/three/three.module.min.js')&&exists('lobby/vendor/three/three.core.min.js'),'Three local incompleto');
const currentRelease=JSON.parse(read('release-current.json'));assert.ok(cfg.includes(`LOBBY_VERSION='${currentRelease.version}'`),'versão Lobby deve acompanhar a release corrente');
assert.equal(release.version,'v11.5-P5.1-CAMPUS-3D-CINEMATIC');
assert.ok(game.includes('skyDome')&&game.includes('FogExp2')&&game.includes('tree(x,z')&&game.includes('createCampusEnvironment'),'ambientação P5.1 incompleta');assert.ok(environment.includes('createCentralHub')&&environment.includes('centralFountain'),'praça/fonte central modularizada ausente');
assert.ok(game.includes('PerspectiveCamera')&&game.includes('createCameraController')&&camera.includes('setYaw')&&camera.includes('setPitch')&&camera.includes('getDistance'),'câmera 360 incompleta');
assert.ok(camera.includes('shoulder:.52')&&camera.includes('camera.fov=THREE.MathUtils.damp'),'câmera cinematográfica/dynamic FOV ausente');
assert.ok(game.includes("keys.has('KeyW')")&&game.includes("keys.has('ShiftLeft')")&&game.includes('running?6.4:3.65'),'andar/correr ausente');
assert.ok(game.includes("e.code==='Space'")&&game.includes('vertical-=20*dt'),'pulo/gravidada ausente');
assert.ok(html.includes('move-joystick')&&game.includes('bindJoystick'),'joystick mobile ausente');
assert.ok(avatar.includes('CapsuleGeometry')&&avatar.includes('createAvatarSystem')&&avatar.includes('function createAvatar')&&avatar.includes('function animate('),'avatar humanoide revisado ausente');
assert.ok(avatar.includes('hashSeed')&&avatar.includes('const SKINS=[')&&avatar.includes('const HAIRS=['),'variação determinística do avatar ausente');
assert.ok(avatar.includes("u.emoteKind==='wave'")&&avatar.includes("u.emoteKind==='like'")&&avatar.includes("u.emoteKind==='spark'"),'emotes animados ausentes');
assert.ok(game.includes('syncOtherAvatars')&&game.includes('.position.lerp('),'interpolação remota ausente');
assert.ok(['1ds','2ds','3ds','sub'].every(x=>game.includes(`'${x}'`))&&environment.includes('function createBuilding'),'quatro ambientes 3D ausentes');
assert.ok(portals.includes('particleField')&&portals.includes('function createPortal')&&portals.includes('PORTAL ABERTO'),'portais energizados ausentes');
assert.ok(html.includes('loading3d')&&html.includes('zone-banner')&&css.includes('.cinematic-frame'),'HUD cinematográfico ausente');
assert.doesNotMatch(game,/exercise_releases|student_exercises|SUPABASE/i,'renderer 3D não pode ser autoridade de dados');
assert.match(lobby,/functions\.invoke\('lobby-moderation'/,'moderação P4 não preservada');
assert.match(lobby,/functions\.invoke\('lobby-presence'/,'presença não usa Edge Function');
assert.doesNotMatch(lobby,/from\('lobby_presence'\)\.upsert|from\('lobby_presence'\)\.delete/,'frontend não pode escrever presença diretamente');
assert.match(lobby,/security-telemetry/,'telemetria de segurança não preservada');
assert.ok(game.includes('worldToPresence')&&game.includes('presenceToWorld'),'compatibilidade de coordenadas ausente');
assert.doesNotMatch(`${html}\n${lobby}\n${game}`,/SUPABASE_SERVICE_ROLE_KEY|sb_secret_|service_role\s*[:=]\s*['"]/i,'service role no frontend');
assert.match(securityMigration,/revoke truncate, references, trigger, insert, update, delete on table public\.lobby_presence from authenticated/i,'privilégios de presença não endurecidos');
assert.match(securityMigration,/grant select on table public\.lobby_presence to authenticated/i,'SELECT do lobby deve permanecer');
assert.match(securityMigration,/outside_parana|security_ip_cache|security_consume_rate_limit/,'baseline de segurança P4.3 ausente');
console.log('PASS p5-lobby-3d-v11.5: campus cinematic + avatares + presença segura + P4.3 preservado');
