import fs from 'node:fs';
import assert from 'node:assert/strict';
const lobby=fs.readFileSync(new URL('../../lobby/assets/lobby.js',import.meta.url),'utf8');
const three=fs.readFileSync(new URL('../../lobby/assets/lobby3d.js',import.meta.url),'utf8');
const lite=fs.readFileSync(new URL('../../lobby/assets/lobby-lite.js',import.meta.url),'utf8');
const index=fs.readFileSync(new URL('../../lobby/index.html',import.meta.url),'utf8');
const cfg=fs.readFileSync(new URL('../../lobby/assets/config.js',import.meta.url),'utf8');
const perf=fs.readFileSync(new URL('../../lobby/assets/render/performance-manager.js',import.meta.url),'utf8');
assert.match(lobby,/lobby_3d_boot_timeout/);
assert.match(lobby,/startLite\(/);
assert.match(lobby,/freshCanvas\(\)/);
assert.match(lobby,/retry3D/);
assert.match(three,/three_import_timeout/);
assert.match(perf,/saveData\|\|mobile\|\|hardware<=4\|\|cores<=4/);assert.match(perf,/if\(profile\.lowEnd\)return 'low'/);
assert.match(three,/signal\?\.aborted/);
assert.match(lite,/createLobbyLite/);
assert.match(lite,/onPlayerState/);
assert.match(index,/id="retry-3d"/);
assert.match(index,/id="enter-lite"/);
const currentRelease=JSON.parse(fs.readFileSync(new URL('../../release-current.json',import.meta.url),'utf8'));assert.ok(cfg.includes(`LOBBY_VERSION='${currentRelease.version}'`));
assert.doesNotMatch(lite,/SUPABASE|service_role|exercise_releases/i);
console.log('PASS p5 lobby mobile recovery v11.5.2');
