import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
const root=path.resolve(import.meta.dirname,'../..');
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const html=read('lobby/index.html');
const lobby=read('lobby/assets/lobby.js');
const game=read('lobby/assets/lobby3d.js');
const cfg=read('lobby/assets/config.js');
const release=JSON.parse(read('release-v11.6.json'));
assert.equal(release.version,'v11.6-P5.2-HEAVY-ADAPTIVE');
assert.ok(/LOBBY_VERSION='0\.(4\.0|5\.0|6\.0|7\.0|8\.0|9\.0)'/.test(cfg)||cfg.includes("LOBBY_VERSION='1.0.0'"));
assert.ok(game.includes("ultra:{")&&game.includes("shadowSize:2048"),'perfil Ultra ausente');
assert.ok(game.includes('updateAdaptive')&&game.includes("fps<27")&&game.includes("fps>54"),'qualidade adaptativa ausente');
assert.ok(game.includes("cameraMode='shoulder'")&&game.includes("cameraMode==='wide'"),'modos de câmera ausentes');
assert.ok(game.includes('cameraDistanceSafe')&&game.includes('colliders.some'),'anti-clipping da câmera ausente');
assert.ok(html.includes('id="camera-button"')&&html.includes('id="perf-badge"'),'HUD P5.2 incompleto');
assert.ok(lobby.includes('toggleCamera')&&lobby.includes('perfUpdate'),'integração câmera/FPS ausente');
assert.ok(lobby.includes("order=['low','medium','high','ultra']"),'ciclo de qualidade incompleto');
assert.ok(game.includes('pack=box')&&game.includes('const cap='),'detalhes adicionais de avatar ausentes');
assert.ok(lobby.includes('portal-travel')&&read('lobby/assets/lobby.css').includes('@keyframes portal-travel'),'transição de portal ausente');
assert.ok(read('lobby/assets/lobby-lite.js').includes('createLobbyLite'),'fallback leve removido');
assert.doesNotMatch(game,/SUPABASE|exercise_releases|student_exercises/i,'renderer ganhou autoridade indevida');
assert.match(lobby,/functions\.invoke\('lobby-presence'/,'presença server-side removida');
console.log('PASS p5-lobby-heavy-adaptive-v11.6');
