import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';
const root=path.resolve(path.dirname(new URL(import.meta.url).pathname),'../..');
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const rel=JSON.parse(read('release-v11.7.json'));assert.equal(rel.version,'v11.7-P5.3-RIGGED-GLB');
const rig=read('lobby/assets/rigged-avatar.js'),lobby=read('lobby/assets/lobby3d.js'),avatar=read('lobby/assets/characters/avatar-system.js'),cfg=read('lobby/assets/config.js');
assert.ok(rig.includes('AnimationMixer')&&rig.includes('QuaternionKeyframeTrack')&&rig.includes('SkinnedMesh'),'runtime GLB rigado ausente');
assert.ok(avatar.includes("import('../rigged-avatar.js?v=14.10.8.65')")&&avatar.includes("rigAsset?'rigged-glb-v2':'procedural-v2'")&&avatar.includes('proceduralBody'),'fallback GLB/procedural ausente');assert.ok(lobby.includes('getAvatarMode:()=>avatarSystem.getMode()'),'renderer deve consultar o Avatar System');
const currentRelease=JSON.parse(read('release-current.json'));assert.ok(cfg.includes(`LOBBY_VERSION='${currentRelease.version}'`),'versão do Lobby deve acompanhar a release corrente');
const b=fs.readFileSync(path.join(root,'lobby/assets/models/agv-avatar-rig-v1.glb'));assert.equal(b.toString('ascii',0,4),'glTF');assert.equal(b.readUInt32LE(4),2);assert.equal(b.readUInt32LE(8),b.length);
let off=12,json=null;while(off<b.length){const len=b.readUInt32LE(off),type=b.readUInt32LE(off+4);if(type===0x4e4f534a)json=JSON.parse(b.subarray(off+8,off+8+len).toString('utf8').trim());off+=8+len;}assert.ok(json);assert.ok(json.skins?.length===1&&json.meshes?.length===1);assert.deepEqual(json.animations.map(a=>a.name),['Idle','Walk','Run','Jump','Wave']);assert.ok(json.skins[0].joints.length>=8);assert.ok(b.length<100_000,'GLB inicial deve permanecer leve');
console.log('PASS p5-rigged-glb-v11.7');
