import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';
const root=path.resolve(path.dirname(new URL(import.meta.url).pathname),'../..');
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const rel=JSON.parse(read('release-v11.8.json'));assert.equal(rel.version,'v11.8-P5.4-SOCIAL-ACTIONS');
const html=read('lobby/index.html'),app=read('lobby/assets/lobby.js'),world=read('lobby/assets/lobby3d.js'),rig=read('lobby/assets/rigged-avatar.js'),cfg=read('lobby/assets/config.js');
for(const action of ['dance','cheer','crouch'])assert.ok(html.includes(`data-local-action="${action}"`),`ação ${action} ausente`);
assert.ok(app.includes("e.code==='KeyR'")&&app.includes('setLocalAction'), 'atalho/menu de ações ausente');
assert.ok(world.includes("const seats=[")&&world.includes('toggleSeat(seat)'), 'bancos interativos ausentes');
assert.ok(world.includes("localAction==='sit'")&&rig.includes("localAction==='sit'"), 'pose sentada não cobre GLB e procedural');
assert.ok(rig.includes("localAction==='dance'")&&rig.includes("localAction==='cheer'")&&rig.includes("localAction==='crouch'"),'poses rigadas extras ausentes');
assert.ok(cfg.includes("LOBBY_VERSION='0.6.0'")||cfg.includes("LOBBY_VERSION='0.7.0'")||cfg.includes("LOBBY_VERSION='0.8.0'")||cfg.includes("LOBBY_VERSION='0.9.0'")||cfg.includes("LOBBY_VERSION='1.0.0'"),'versão Lobby incorreta');
assert.ok(!app.includes("emote('dance'")&&!app.includes("emote('cheer'")&&!app.includes("emote('crouch'"),'ações locais não podem ampliar protocolo do backend');
console.log('PASS p5-social-actions-v11.8');
