import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
const root=path.resolve(import.meta.dirname,'../..');
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const exists=p=>fs.existsSync(path.join(root,p));
const hub=read('index.html'), hubJs=read('assets/hub.js'), session=read('core/session/agv-session.js');
const adminHtml=read('admin/index.html'), admin=read('admin/assets/admin.js');
const profHtml=read('professor/index.html'), prof=read('professor/assets/professor.js');
const actHtml=read('atividades/index.html'), act=read('atividades/assets/js/app.js');
assert.doesNotMatch(hub,/http-equiv="refresh"|location\.replace\(['"]lobby\//i,'raiz não pode redirecionar obrigatoriamente ao Lobby');
assert.match(hub,/Hub Educacional/,'Hub raiz ausente');
assert.ok(hub.includes('href="atividades/"')&&/href="lobby\/\?v=14\.10\.8\.18"/.test(hub),'atalhos principais ausentes');
assert.ok(hub.includes('data-role="teacher,admin,super_admin"')&&hub.includes('data-role="admin,super_admin"'),'cards por papel ausentes');
assert.ok(exists('core/session/agv-session.js')&&session.includes('grant_type=refresh_token'),'camada de sessão/refresh ausente');
assert.match(session,/sb-\$\{ref\}-auth-token/,'sessão deve usar chave padrão Supabase');
assert.match(session,/localStorage/,'sessão comum deve persistir em localStorage');
assert.doesNotMatch(prof,/agv:teacher-console:session|sessionStorage\.setItem\(tokenKey/,'Console Professor ainda usa sessão paralela');
assert.ok(adminHtml.includes('../core/session/agv-session.js')&&profHtml.includes('../core/session/agv-session.js'),'Admin/Professor não carregam sessão comum');
assert.ok(admin.includes('AGVSession.create')&&prof.includes('AGVSession.create'),'Admin/Professor não usam sessão comum');
assert.ok(prof.includes('if(err?.status===401)clearSession()'),'perfil sem permissão não deve apagar sessão global');
assert.ok(actHtml.includes('id="hub-btn"')&&act.includes("window.location.href = '../'"),'Atividades não volta ao Hub');
assert.ok(adminHtml.includes('id="open-hub"')&&profHtml.includes('id="open-hub"'),'atalho Hub ausente em staff');
assert.doesNotMatch(`${hub}\n${hubJs}\n${session}`,/service_role|SUPABASE_SERVICE_ROLE_KEY|sb_secret_/i,'segredo privilegiado exposto no Hub');
assert.match(hub,/connect-src 'self' https:\/\/iresvqwyaqotghjssncg\.supabase\.co/,'CSP do Hub deve limitar conexões ao Supabase');
console.log('PASS p6-session-hub-v12.4: Hub raiz + sessão Supabase compartilhada + refresh + navegação unificada');
