import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
const root=path.resolve(path.dirname(new URL(import.meta.url).pathname),'../..');
const js=fs.readFileSync(path.join(root,'admin/assets/admin.js'),'utf8');
const css=fs.readFileSync(path.join(root,'admin/assets/admin.css'),'utf8');
assert.match(js,/function renderReports\(\)/,'reports renderer exists');
assert.match(js,/Relatórios consolidados/,'consolidated reports heading');
assert.match(js,/Alunos que precisam de atenção/,'attention report exists');
assert.match(js,/Por turma/,'class report exists');
assert.match(js,/Por disciplina/,'subject report exists');
assert.match(js,/Perfil 360º → Plataformas/,'platform telemetry limitation is explicit');
assert.match(js,/function exportReportsCsv\(\)/,'CSV export exists');
assert.match(js,/reportWindowStart/,'period filter exists');
assert.match(js,/reportNeedsAttention/,'attention classification exists');
assert.doesNotMatch(js,/service_role/i,'admin frontend must not expose service role');
assert.match(css,/\.report-kpis/,'responsive KPI styles exist');
assert.match(css,/@media\(max-width:720px\)/,'mobile reports styles exist');
console.log('P6.10 reports v13.8 — PASS');
