import { PerformanceBudgetManager,QUALITY_PACKS } from '../../core/performance/PerformanceBudgetManager.js';
import { QADiagnosticsRenderer } from '../../rendering/QADiagnosticsRenderer.js';
import { QA_DEVICE_PROFILES,QA_CHECKLIST,QA_GOALS } from '../../data/performanceSystems.js';
class PerformanceQAModule{
 constructor(){this.host=null;this.context=null;this.manager=new PerformanceBudgetManager('balanced');this.renderer=null;this.raf=0;this.last=0;this.samples=[];this.checks=new Set();this.packs=new Set(['balanced']);this.goals=new Set();this.device=QA_DEVICE_PROFILES[1];this.onClick=e=>this.click(e);}
 mount(host,context){this.host=host;this.context=context;for(const g of QA_GOALS)if(context.profileStore.hasCompleted(`qa-${g.id}`))this.goals.add(g.id);host.addEventListener('click',this.onClick);this.render();this.start();}
 render(){this.host.innerHTML=`<section class="qa-module"><header class="qa-top"><button data-action="back">← Portal</button><div><span>FASE 23</span><h1>Otimização e Validação Final</h1></div><button data-action="export">Exportar relatório</button></header><main class="qa-grid"><section class="qa-card qa-chart"><canvas data-qa-canvas></canvas><div class="qa-live"><span><b data-fps>--</b> FPS</span><span><b data-frame>--</b> ms</span><span><b data-triangles>--</b> tri</span><span><b data-draws>--</b> draws</span><span><b data-memory>--</b> MB</span></div></section><section class="qa-card"><h2>Pacotes gráficos</h2><div class="qa-packs">${Object.values(QUALITY_PACKS).map(p=>`<button data-action="pack" data-id="${p.id}" class="${p.id==='balanced'?'active':''}"><b>${p.label}</b><span>${p.targetFps} FPS · ${p.maxTriangles.toLocaleString('pt-BR')} tri</span></button>`).join('')}</div><h3>Dispositivo de teste</h3><div class="qa-devices">${QA_DEVICE_PROFILES.map((d,i)=>`<button data-action="device" data-id="${d.id}" class="${i===1?'active':''}">${d.label}</button>`).join('')}</div><button data-action="diagnostic" class="qa-primary">Executar diagnóstico</button></section><section class="qa-card"><h2>Checklist de aceite</h2><div class="qa-checklist">${QA_CHECKLIST.map(c=>`<button data-action="check" data-id="${c.id}"><i>○</i>${c.label}</button>`).join('')}</div><div class="qa-recommendation"><span>RECOMENDAÇÃO</span><b data-recommendation>Equilibrado</b><small data-scale>Escala dinâmica 84%</small></div></section><section class="qa-card"><h2>Objetivos</h2><div class="qa-objectives">${QA_GOALS.map(g=>`<span class="${this.goals.has(g.id)?'done':''}" data-goal="${g.id}"><i>${this.goals.has(g.id)?'✓':'○'}</i>${g.label}<b>+${g.xp}</b></span>`).join('')}</div><p>Os testes finais verificam inicialização, resize, fullscreen, entrada, lifecycle, fallback, armazenamento, acessibilidade e desempenho.</p></section></main></section>`;}
 start(){this.renderer=new QADiagnosticsRenderer(this.host.querySelector('[data-qa-canvas]'),this.context.settingsStore);this.renderer.start();this.last=performance.now();const tick=now=>{const dt=Math.max(.001,(now-this.last)/1000);this.last=now;const profile=this.manager.pack;const variation=Math.sin(now*.0017)*5;const sample=this.manager.sample({fps:Math.max(24,profile.targetFps+variation),frameMs:1000/Math.max(24,profile.targetFps+variation),triangles:profile.maxTriangles*(.48+.08*Math.sin(now*.0007)),drawCalls:profile.maxDrawCalls*(.44+.09*Math.cos(now*.0009)),textureMb:profile.maxTextureMb*.38,memoryMb:180+this.device.memory*32});this.samples.push(sample);if(this.samples.length>90)this.samples.shift();this.renderer.setSamples(this.samples);this.update(sample);this.raf=requestAnimationFrame(tick);};this.raf=requestAnimationFrame(tick);}
 click(e){const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action;if(a==='back')return this.context.onBack();if(a==='pack'){this.manager.setPack(b.dataset.id);this.packs.add(b.dataset.id);this.host.querySelectorAll('[data-action="pack"]').forEach(x=>x.classList.toggle('active',x===b));if(this.packs.size===3)this.complete('compare-packs');}if(a==='device'){this.device=QA_DEVICE_PROFILES.find(x=>x.id===b.dataset.id)||this.device;this.host.querySelectorAll('[data-action="device"]').forEach(x=>x.classList.toggle('active',x===b));}if(a==='diagnostic'){this.complete('run-diagnostic');const d=this.manager.diagnostics();this.context.toast(`Diagnóstico: ${d.average.fps.toFixed(0)} FPS, recomendação ${d.recommendation}.`);}if(a==='check'){this.checks.add(b.dataset.id);b.classList.add('done');b.querySelector('i').textContent='✓';if(this.checks.size===QA_CHECKLIST.length)this.complete('complete-checklist');}if(a==='export'){this.complete('export-report');this.export();}}
 update(s){const set=(q,v)=>{const e=this.host.querySelector(q);if(e)e.textContent=v};set('[data-fps]',Math.round(s.fps));set('[data-frame]',s.frameMs.toFixed(1));set('[data-triangles]',Math.round(s.triangles).toLocaleString('pt-BR'));set('[data-draws]',Math.round(s.drawCalls));set('[data-memory]',Math.round(s.memoryMb));const d=this.manager.diagnostics();set('[data-recommendation]',QUALITY_PACKS[d.recommendation].label);set('[data-scale]',`Escala dinâmica ${Math.round(d.dynamicScale*100)}%`);}
 export(){const report={schema:'cosmos-ds-qa-final-v1',generatedAt:new Date().toISOString(),device:this.device,diagnostics:this.manager.diagnostics(),checks:[...this.checks],samples:this.samples.slice(-30)};const blob=new Blob([JSON.stringify(report,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='cosmos-ds-relatorio-qa.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 complete(id){if(this.goals.has(id))return;this.goals.add(id);const g=QA_GOALS.find(x=>x.id===id);if(g&&this.context.profileStore.addXp(g.xp,`qa-${id}`))this.context.toast(`${g.label}: +${g.xp} XP`);const el=this.host.querySelector(`[data-goal="${id}"]`);el?.classList.add('done');if(el?.querySelector('i'))el.querySelector('i').textContent='✓';if(this.goals.size===QA_GOALS.length&&this.context.profileStore.addXp(600,'qa-final-certification'))this.context.toast('Certificação QA e Otimização: +600 XP');}
 unmount(){cancelAnimationFrame(this.raf);this.renderer?.destroy();this.host?.removeEventListener('click',this.onClick);if(this.host)this.host.innerHTML='';}
}
export const createModule=()=>new PerformanceQAModule();
