'use strict';

window.LABDS = window.LABDS || {};

window.LABDS.VERSION = '4.21.0';
window.LABDS.RELEASE_DATE = '2026-08-02';
window.LABDS.RELEASE = Object.freeze({
  version:'4.21.0',
  updatedAt:'2026-08-03T01:05:00-03:00',
  channel:'stable',
  title:'Hardware Studio 3D com catálogo, periféricos e benchmarks',
  notes:Object.freeze([
    'Montagem de Computador evoluiu para Hardware Studio 3D com mais peças, marcas, gerações, gabinetes, cores e configurações.',
    'Foram adicionados monitores, dispositivos de entrada e saída, periféricos, nobreaks, diagnósticos e benchmarks didáticos para jogos, vídeo, trabalho e estudos.',
    'O laboratório agora possui gráficos Baixo, Médio, Alto e Ultra com visualização 360°, materiais 3D, vidro, sombras, RGB, shader e partículas conforme o desempenho.'
  ])
});
window.LABDS.REMOVED_TOOL_IDS = Object.freeze([
  'iara','iara-ds','iara_ds','iara-assistant','assistant-ds',
  'teacher-mode','teacher-lab','modo-professor','modo-professor-atividades','professor'
]);
window.LABDS.DEPRECATED_TOOL_REDIRECTS = Object.freeze(Object.fromEntries(window.LABDS.REMOVED_TOOL_IDS.map(id=>[id,'help-center'])));
window.LABDS.EDUAUTH_ENABLED = true;
window.LABDS.APP_NAME = 'Laboratório Virtual DS';
window.LABDS.FLIPERAMA_DS_URL = ''; // Preencher somente após a publicação e validação do portal independente.
window.LABDS.STUDENT_CLASSES = ['1º DS — Manhã','2º DS — Manhã','3º DS — Manhã','1º ADM — Manhã','2º ADM — Manhã','1º Portos — Manhã','2º DS — Noite','DS Subsequente — Noite','Outra turma'];
window.LABDS.CLASSROOM_DEFAULT_URL = 'https://classroom.google.com/';
window.LABDS.CLASSROOM_NOTICE = 'O Lab Virtual DS não envia nem anexa arquivos automaticamente. O estudante deve selecionar no Classroom o arquivo que acabou de baixar.';
window.LABDS.SESSION_PRIVACY_NOTICE = 'Nome e turma são usados apenas para identificar o relatório local desta sessão. Nenhum dado é enviado pelo Laboratório Virtual DS a servidores externos.';

window.LABDS.TERMINALS = [
  { id:'cmd', type:'terminal', featured:true, category:'terminal', level:'basic', os:['windows'], runtime:'simulation', runtimeLabel:'Simulação avançada', name:'Prompt de Comando — CMD', shortName:'CMD', description:'Arquivos, diretórios, comandos de sistema e diagnóstico de rede em um Windows virtual.', shell:'cmd', theme:'theme-cmd', icon:'C:\\>', subtitle:'Windows 11 • CMD simulado', extension:'bat', mime:'application/x-bat', tags:['Windows','Arquivos','Rede'], boot:'Microsoft Windows [versão 11.0.26100.0000]\n(c) Microsoft Corporation. Todos os direitos reservados.\n' },
  { id:'powershell', type:'terminal', featured:true, category:'terminal', level:'intermediate', os:['windows'], runtime:'simulation', runtimeLabel:'Simulação avançada', name:'Windows PowerShell', shortName:'PowerShell', description:'Cmdlets, aliases, variáveis, arquivos, processos e pipelines educacionais.', shell:'powershell', theme:'theme-powershell', icon:'PS', subtitle:'PowerShell • Cmdlets e pipelines', extension:'ps1', mime:'text/plain', tags:['Windows','Cmdlets','Pipeline'], boot:'Windows PowerShell\nCopyright (C) Microsoft Corporation. Todos os direitos reservados.\n' },
  { id:'bash', type:'terminal', featured:true, category:'terminal', level:'basic', os:['linux'], runtime:'simulation', runtimeLabel:'Simulação avançada', name:'Terminal Linux — Bash', shortName:'Bash', description:'Shell GNU/Linux com arquivos, permissões, pipelines e pacotes simulados.', shell:'bash', distro:'linux', theme:'theme-bash', icon:'$_', subtitle:'GNU/Linux • Bash simulado', extension:'sh', mime:'text/x-shellscript', tags:['Linux','Bash','Permissões'], boot:'Laboratório Virtual DS GNU/Linux\nDigite "help" ou "man comando" para ajuda.\n' },
  { id:'ubuntu', type:'terminal', featured:false, category:'terminal', level:'basic', os:['linux'], runtime:'simulation', runtimeLabel:'Simulação avançada', name:'Terminal Ubuntu', shortName:'Ubuntu', description:'Ambiente Ubuntu com Bash, apt e identidade visual própria.', shell:'bash', distro:'ubuntu', theme:'theme-ubuntu', icon:'◉', subtitle:'Ubuntu 24.04 LTS • apt simulado', extension:'sh', mime:'text/x-shellscript', tags:['Ubuntu','apt','Bash'], boot:'Welcome to Ubuntu 24.04 LTS (GNU/Linux simulado)\n' },
  { id:'debian', type:'terminal', featured:false, category:'terminal', level:'basic', os:['linux'], runtime:'simulation', runtimeLabel:'Simulação avançada', name:'Terminal Debian', shortName:'Debian', description:'Ambiente Debian com estrutura de arquivos e gerenciador apt simulados.', shell:'bash', distro:'debian', theme:'theme-debian', icon:'deb', subtitle:'Debian 12 • apt simulado', extension:'sh', mime:'text/x-shellscript', tags:['Debian','apt','Bash'], boot:'Debian GNU/Linux 12 laboratorio-ds tty1\n' },
  { id:'kali', type:'terminal', featured:false, category:'terminal', level:'advanced', os:['linux'], runtime:'simulation', runtimeLabel:'Simulação educacional', name:'Terminal Kali Linux', shortName:'Kali', description:'Identidade visual Kali; ferramentas de segurança são limitadas a respostas conceituais e isoladas.', shell:'bash', distro:'kali', theme:'theme-kali', icon:'K', subtitle:'Kali Linux • segurança educacional simulada', extension:'sh', mime:'text/x-shellscript', tags:['Kali','Linux','Seguro'], boot:'Kali GNU/Linux Rolling — laboratório educacional isolado\nNenhum comando acessa redes ou dispositivos reais.\n' },
  { id:'fedora', type:'terminal', featured:false, category:'terminal', level:'intermediate', os:['linux'], runtime:'simulation', runtimeLabel:'Simulação avançada', name:'Terminal Fedora', shortName:'Fedora', description:'Ambiente Fedora com Bash e gerenciador dnf simulado.', shell:'bash', distro:'fedora', theme:'theme-fedora', icon:'f', subtitle:'Fedora Workstation • dnf simulado', extension:'sh', mime:'text/x-shellscript', tags:['Fedora','dnf','Bash'], boot:'Fedora Linux 40 (Workstation Edition) — sessão simulada\n' },
  { id:'chromeos', type:'terminal', featured:false, category:'terminal', level:'basic', os:['browser','linux'], runtime:'simulation', runtimeLabel:'Simulação educacional', name:'Terminal ChromeOS — Crosh', shortName:'ChromeOS', description:'Terminal simplificado inspirado no Crosh, com comandos de diagnóstico e shell educacional.', shell:'bash', distro:'chromeos', theme:'theme-chromeos', icon:'crosh', subtitle:'ChromeOS • Crosh/shell simulado', extension:'sh', mime:'text/x-shellscript', tags:['ChromeOS','Crosh','Rede'], boot:'crosh> Ambiente educacional simulado\nDigite "help" para ver comandos disponíveis.\n' },
  { id:'macos', type:'terminal', featured:true, category:'terminal', level:'intermediate', os:['macos'], runtime:'simulation', runtimeLabel:'Simulação avançada', name:'Terminal macOS — Zsh', shortName:'macOS', description:'Comandos Unix e utilitários exclusivos apresentados em ambiente educacional inspirado no macOS.', shell:'macos', distro:'macos', theme:'theme-macos', icon:'%', subtitle:'macOS • Zsh simulado', extension:'sh', mime:'text/x-shellscript', tags:['macOS','Zsh','Unix'], boot:`Last login: ${new Date().toDateString()} on ttys000\n` }
];

window.LABDS.TOOLS = [
  ...window.LABDS.TERMINALS,
  { id:'python', type:'lab', module:'python-lab', featured:true, category:'programming', level:'basic', os:['browser','multi'], runtime:'real-online', runtimeLabel:'Execução real no navegador', name:'Ambiente Python', shortName:'Python', description:'Editor, console, entrada padrão e execução real com Pyodide carregado sob demanda.', icon:'Py', extension:'py', mime:'text/x-python', tags:['Python','Pyodide','Editor'] },
  { id:'javascript', type:'lab', module:'javascript-lab', featured:true, category:'programming', level:'basic', os:['browser','multi'], runtime:'real', runtimeLabel:'Execução real isolada', name:'Ambiente JavaScript', shortName:'JavaScript', description:'Execute JavaScript em Web Worker isolado, com console, erros e interrupção de loops.', icon:'JS', extension:'js', mime:'text/javascript', tags:['JavaScript','Worker','Console'] },
  { id:'web', type:'lab', module:'web-lab', featured:true, category:'programming', level:'intermediate', os:['browser','multi'], runtime:'real', runtimeLabel:'Execução real isolada', name:'HTML, CSS e JavaScript Web', shortName:'Front-end', description:'Editores separados, visualização ao vivo em iframe sandbox e simulação de dispositivos.', icon:'</>', extension:'html', mime:'text/html', tags:['HTML','CSS','Preview'] },
  { id:'sql', type:'lab', module:'sql-lab', featured:true, category:'database', level:'intermediate', os:['browser','multi'], runtime:'real-online', runtimeLabel:'SQLite real no navegador', name:'Laboratório SQL', shortName:'SQL', description:'SQLite em WebAssembly, explorador de tabelas, resultados tabulares e persistência local.', icon:'DB', extension:'sql', mime:'application/sql', tags:['SQLite','SQL','Tabelas'] },
  { id:'network', type:'lab', module:'network-lab', featured:true, category:'network', level:'intermediate', os:['multi'], runtime:'simulation', runtimeLabel:'Simulação avançada', name:'Laboratório de Redes', shortName:'Redes', description:'Topologia, IP, DNS, gateway, latência, jitter, perda e falhas configuráveis.', icon:'⌁', extension:'json', mime:'application/json', tags:['TCP/IP','Ping','DNS'] },
  { id:'virtual-machine', type:'lab', module:'vm-lab', featured:true, category:'systems', level:'advanced', os:['multi'], runtime:'simulation', runtimeLabel:'Simulação educacional', name:'Sistemas Operacionais e Máquinas Virtuais', shortName:'Sistemas/VM', description:'Monte hardware virtual, configure BIOS/UEFI, discos e instale versões distintas de Windows, Linux, ChromeOS e macOS em uma simulação técnica.', icon:'VM', extension:'vm.json', mime:'application/json', tags:['Virtualização','BIOS','ISO'] },
  { id:'hardware', type:'lab', module:'hardware-lab', featured:false, category:'systems', level:'intermediate', os:['multi'], runtime:'simulation', runtimeLabel:'Simulação 3D/WebGL', name:'Hardware Studio 3D', shortName:'Hardware 3D', description:'Monte computadores completos em 3D com mais realismo, personalize gabinete, bancada, iluminação, ferramentas, periféricos e compare benchmarks didáticos para jogos, criação, trabalho e estudos.', icon:'PC', extension:'pc.json', mime:'application/json', tags:['CPU','RAM','Fonte'] },
  { id:'graphics', type:'lab', module:'graphics-lab', featured:true, category:'graphics', level:'basic', os:['browser','multi'], runtime:'real', runtimeLabel:'Execução visual real', name:'Cores, Pixels e Resolução', shortName:'Computação gráfica', description:'Conversões de cor, contraste, canais RGBA, grade de pixels e estimativa de tamanho.', icon:'RGB', extension:'png', mime:'image/png', tags:['Pixels','RGB','HEX'] },
  { id:'block-programming', type:'lab', module:'blocks-lab', featured:false, category:'programming', level:'basic', os:['browser','multi'], runtime:'demo', runtimeLabel:'Execução visual interativa', name:'Programação em Blocos', shortName:'Blocos', description:'Monte algoritmos, veja a rota 2D mudar em tempo real e execute cada bloco passo a passo com pseudocódigo e JavaScript equivalente.', icon:'▦', extension:'json', mime:'application/json', tags:['Lógica','Blocos','Pseudocódigo'] },
  { id:'data-tools', type:'lab', module:'data-tools-lab', featured:false, category:'programming', level:'basic', os:['browser','multi'], runtime:'real', runtimeLabel:'Execução real no navegador', name:'Bits, Bases e Codificações', shortName:'Conversores', description:'Conversão binária, hexadecimal, Base64, Unicode e hashes educacionais.', icon:'01', extension:'txt', mime:'text/plain', tags:['Binário','Base64','Hash'] },
  { id:'git-github', type:'lab', module:'git-lab', featured:true, category:'devops', level:'intermediate', os:['browser','multi'], runtime:'simulation', runtimeLabel:'Simulação técnica local', name:'Git e GitHub', shortName:'Git/GitHub', description:'Repositório, commits, branches, merge, conflitos, remoto e publicação no GitHub Pages em uma simulação segura.', icon:'git', extension:'git.json', mime:'application/json', tags:['Git','GitHub','Versionamento','Pages'] },
  { id:'cybersecurity', type:'lab', module:'security-lab', featured:true, category:'security', level:'advanced', os:['browser','multi'], runtime:'simulation', runtimeLabel:'Simulação defensiva isolada', name:'Cibersegurança Defensiva', shortName:'Segurança', description:'Phishing, XSS, sanitização, autenticação, 2FA, hash, integridade, logs e resposta a incidentes com dados fictícios.', icon:'SEC', extension:'security.json', mime:'application/json', tags:['XSS','Phishing','2FA','Logs'] },
  { id:'cyber-ops', type:'lab', module:'cyber-ops-lab', featured:true, immersive:true, category:'security', level:'advanced', os:['browser','multi'], runtime:'simulation', runtimeLabel:'Missões defensivas simuladas', name:'Cyber Ops — Shadow Grid', shortName:'Cyber Ops', description:'Laboratório narrativo com 3 módulos, 6 missões, investigação, resposta a incidentes, criptointeligência, emblemas e evidências exportáveis.', icon:'OPS', extension:'cyberops.json', mime:'application/json', tags:['Cyber Ops','Shadow Grid','Incidentes','Investigação','Criptointeligência','Missões','Forense'] },
  { id:'sysadmin', type:'lab', module:'sysadmin-lab', featured:true, category:'systems', level:'advanced', os:['multi'], runtime:'simulation', runtimeLabel:'Simulação administrativa', name:'Administração de Sistemas e Redes', shortName:'Administração', description:'Usuários, grupos, permissões, serviços, domínio, DHCP, firewall, VPN, MikroTik e CFTV em ambientes fictícios.', icon:'ADM', extension:'admin.json', mime:'application/json', tags:['Usuários','AD','VPN','MikroTik','CFTV'] },
  { id:'code-games', type:'lab', module:'code-games-lab', featured:true, category:'science', level:'intermediate', os:['browser','multi'], runtime:'simulation', runtimeLabel:'Simulações educacionais interativas', name:'Simuladores Interativos DS', shortName:'Simuladores DS', description:'Três simuladores educacionais preservados no Lab Virtual: probabilidade responsável, mercado e análise de dados, e operação de drone 360° com pré-voo, calibração, modos de voo, rádio controle, telemetria, quatro modelos, pistas ampliadas, clima e segurança.', icon:'SIM', extension:'json', mime:'application/json', tags:['Simulação','Probabilidade','Dados','Mercado','Drone','Three.js','Pré-voo','Calibração','Telemetria','Pistas','Clima','Acessibilidade','Mobile'] },
  { id:'voxelcraft-3d', type:'lab', module:'voxelcraft-lab', featured:true, category:'games', level:'advanced', os:['browser','multi'], runtime:'real-online', runtimeLabel:'Renderização WebGL 3D real', name:'VoxelCraft DS 3D', shortName:'VoxelCraft 3D', description:'Explore um mundo voxel procedural com chunks, física, inventário, construção, perfis gráficos e missões de aprendizagem.', icon:'VOX', extension:'voxel.json', mime:'application/json', tags:['Three.js','WebGL','Voxel','Chunks','3D','Jogos','Programação'] },
  { id:'fintech-pix', type:'lab', module:'fintech-lab', featured:true, category:'fintech', level:'intermediate', os:['browser','multi'], runtime:'simulation', runtimeLabel:'Simulação financeira educacional', name:'Fintech, Caixa Eletrônico e Pix', shortName:'Fintech/Pix', description:'Simule caixa eletrônico, transferência Pix, QR, autenticação, antifraude, liquidação e comprovante com valores fictícios.', icon:'PIX', extension:'fintech.json', mime:'application/json', tags:['Pix','Banco','ATM','Criptografia','Transação'] },
  { id:'blockchain-crypto', type:'lab', module:'blockchain-lab', featured:true, category:'fintech', level:'advanced', os:['browser','multi'], runtime:'real', runtimeLabel:'Hash real e rede simulada', name:'Blockchain e Criptomoedas', shortName:'Blockchain', description:'Construa blocos, gere hash real, simule mineração, consenso e validação de uma rede distribuída sem dinheiro real.', icon:'CHAIN', extension:'chain.json', mime:'application/json', tags:['Blockchain','SHA-256','Consenso','Bitcoin','Rede P2P'] },
  { id:'digital-communication', type:'lab', module:'communication-lab', featured:true, category:'network', level:'intermediate', os:['browser','multi'], runtime:'simulation', runtimeLabel:'Comunicação e criptografia simuladas', name:'E-mail, Mensagens e Criptografia', shortName:'Comunicação', description:'Acompanhe DNS, SMTP, TLS, servidores, entrega de e-mail e mensagens com criptografia ponta a ponta conceitual.', icon:'MSG', extension:'message.json', mime:'application/json', tags:['E-mail','SMTP','TLS','WhatsApp','Chaves'] },
  { id:'display-media', type:'lab', module:'display-media-lab', featured:true, category:'media', level:'intermediate', os:['browser','multi'], runtime:'real', runtimeLabel:'Renderização e áudio no navegador', name:'Telas, Pixels, FPS, Hertz e Áudio', shortName:'Display e mídia', description:'Compare FPS e Hz, explore pixels RGB, conectores de vídeo, ondas sonoras, microfone e alto-falante.', icon:'Hz', extension:'media.json', mime:'application/json', tags:['FPS','Hertz','RGB','HDMI','DisplayPort','Áudio'] },
  { id:'automation-iot', type:'lab', module:'automation-lab', featured:true, category:'automation', level:'advanced', os:['browser','multi'], runtime:'simulation', runtimeLabel:'Automação industrial simulada', name:'Automação, IoT, OCR e Robótica', shortName:'Automação/IoT', description:'Monte fluxos com sensores, OCR de placa, cancela, balança, atuadores, alertas e braço robótico.', icon:'IOT', extension:'automation.json', mime:'application/json', tags:['IoT','OCR','Robótica','Sensores','Automação'] },
  { id:'help-center', type:'lab', module:'help-center-lab', featured:true, category:'support', level:'basic', os:['browser','multi'], runtime:'real', runtimeLabel:'Busca local e offline', name:'Central de Ajuda e Conhecimento', shortName:'Ajuda local', description:'Pesquise ferramentas, comandos, linguagens, atividades, tutoriais, FAQ e glossário sem depender de inteligência artificial remota.', icon:'?', extension:'help.json', mime:'application/json', tags:['Ajuda','Busca','FAQ','Glossário','Offline'] },
  { id:'tutorial-center', type:'lab', module:'tutorial-center-lab', featured:true, category:'support', level:'basic', os:['browser','multi'], runtime:'real', runtimeLabel:'Tutoriais locais com checklist', name:'Central de Tutoriais e Passo a Passo', shortName:'Tutoriais', description:'Aprenda Classroom, e-mail, arquivos, VS Code, Git, planilhas, apresentações, hospedagem e nuvem com checklists em três níveis.', icon:'TUT', extension:'tutorial.json', mime:'application/json', tags:['Tutorial','Classroom','Gmail','Drive','Git','VS Code','Passo a passo'] },
  { id:'tech-explorer', type:'lab', module:'tech-explorer-lab', featured:true, category:'exploration', level:'basic', os:['browser','multi'], runtime:'real', runtimeLabel:'Biblioteca local e fontes oficiais', name:'Explorar Tecnologia, Linguagens e Carreiras', shortName:'Explorar Tecnologia', description:'Biblioteca visual com mais de 70 linguagens, carreiras, salários pesquisados, IA, linha do tempo, exemplos e documentação.', icon:'EXP', extension:'research.json', mime:'application/json', tags:['Linguagens','Carreiras','Salários','IA','História','NASA','Mercado'] },
  { id:'productivity-suite', type:'lab', module:'productivity-lab', featured:true, category:'productivity', level:'intermediate', os:['browser','multi'], runtime:'real', runtimeLabel:'Aplicativos locais integrados', name:'Produtividade e Escritório', shortName:'Escritório', description:'Planilhas, documentos, apresentações, formulários, e-mail, nuvem e fluxo de servidores em um ambiente educacional integrado.', icon:'OFF', extension:'office.json', mime:'application/json', tags:['Planilhas','Documentos','Apresentações','Formulários','E-mail','Nuvem'] },
  { id:'market-simulator', type:'lab', module:'market-lab', featured:true, category:'fintech', level:'intermediate', os:['browser','multi'], runtime:'simulation', runtimeLabel:'Mercado educacional simulado', name:'Mercado Tech e Análise de Gráficos', shortName:'Mercado Tech', description:'Analise ativos fictícios, compre ou venda e acompanhe um gráfico que evolui independentemente da sua decisão.', icon:'MKT', extension:'market.json', mime:'application/json', tags:['Gráfico','Mercado','Probabilidade','Créditos Tech'] },
  { id:'printing-3d', type:'lab', module:'printing3d-lab', featured:true, category:'fabrication', level:'intermediate', os:['browser','multi'], runtime:'simulation', runtimeLabel:'Fatiamento e impressão simulados', name:'Impressão 3D e Modelagem', shortName:'Impressão 3D', description:'Prepare uma impressora FDM ou SLA, inspecione modelos em WebGL 360°, fatie camadas e acompanhe cabeçote, temperaturas, material e falhas simuladas.', icon:'3D', extension:'gcode', mime:'text/plain', tags:['FDM','Resina','STL','G-code','Filamento'] },
  { id:'energy-systems', type:'lab', module:'energy-lab', featured:false, category:'energy', level:'intermediate', os:['browser','multi'], runtime:'simulation', runtimeLabel:'Cálculos e geração simulados', name:'Energia, Queda de Tensão, Solar e Eólica', shortName:'Energia', description:'Calcule queda de tensão, configure painéis solares e turbinas e compare produção, consumo e armazenamento.', icon:'⚡', extension:'energy.json', mime:'application/json', tags:['Solar','Eólica','Tensão','Corrente','Bateria'] },
  { id:'traffic-radar', type:'lab', module:'traffic-lab', featured:false, category:'automation', level:'intermediate', os:['browser','multi'], runtime:'simulation', runtimeLabel:'Trânsito e lógica simulados', name:'Radar, Semáforo e Trânsito Inteligente', shortName:'Trânsito', description:'Meça velocidade, programe fases de semáforo, use sensores e evite conflitos em um cruzamento.', icon:'RAD', extension:'traffic.json', mime:'application/json', tags:['Radar','Semáforo','Sensores','Automação'] },
  { id:'world-tools', type:'lab', module:'world-tools-lab', featured:true, category:'utilities', level:'basic', os:['browser','multi'], runtime:'real', runtimeLabel:'Relógios e cálculos locais em tempo real', name:'Relógios Mundiais, Alarmes e Conversores', shortName:'Relógios mundiais', description:'Relógios analógicos e digitais, quatro fusos do Brasil, comparação mundial, despertador, contagem regressiva, cronômetro e conversores.', icon:'UTC', extension:'convert.json', mime:'application/json', tags:['Fuso','Brasil','Despertador','Cronômetro','Temperatura','Unidades','Conversão'] },
  { id:'solar-system', type:'lab', module:'solar-system-lab', featured:true, category:'science', level:'intermediate', os:['browser','multi'], runtime:'real', runtimeLabel:'Simulação Canvas em tempo real', name:'Sistema Solar Interativo 2D e Perspectiva', shortName:'Sistema Solar', description:'Explore os oito planetas, órbitas, ciclos, escala de tempo, zoom, partículas e fatos da NASA em uma simulação educacional.', icon:'SOL', extension:'solar.json', mime:'application/json', tags:['Sistema Solar','Planetas','NASA','Astronomia','Canvas','2D','3D'] },
  { id:'school-randomizer', type:'lab', module:'school-randomizer-lab', featured:true, category:'organization', level:'basic', os:['browser','multi'], runtime:'real', runtimeLabel:'Sorteio local reproduzível', name:'Sorteios, Turmas e Organização Escolar', shortName:'Sorteios escolares', description:'Sorteie nomes, números, equipes, turmas e salas com sementes, restrições, histórico e exportação.', icon:'SRT', extension:'random.json', mime:'application/json', tags:['Sorteio','Nomes','Equipes','Turmas','Salas','Professor'] },
  { id:'biomonitor', type:'lab', module:'biomonitor-lab', featured:true, category:'science', level:'intermediate', os:['browser','multi'], runtime:'simulation', runtimeLabel:'Sinais fisiológicos simulados', name:'BioMonitor — Batimentos e Sinais', shortName:'BioMonitor', description:'Painel educacional com traçado cardíaco, cenários de esforço, recuperação, alarmes e gráficos simulados.', icon:'BPM', extension:'bio.json', mime:'application/json', tags:['Batimentos','ECG','Ciência','Gráfico','Simulação'] },
  { id:'thermal-panel', type:'lab', module:'thermal-panel-lab', featured:true, category:'science', level:'intermediate', os:['browser','multi'], runtime:'simulation', runtimeLabel:'Sensores e efeitos gráficos simulados', name:'Clima Extremo — Temperatura e Sensores', shortName:'Clima Extremo', description:'Controle temperaturas extremas com termômetro, alarmes, telemetria, gelo, calor, fumaça e efeitos reversíveis.', icon:'TEMP', extension:'thermal.json', mime:'application/json', tags:['Temperatura','Sensores','Frio','Calor','Automação','Partículas'] },
  { id:'audio-lab', type:'lab', module:'audio-lab', featured:true, category:'media', level:'intermediate', os:['browser','multi'], runtime:'real', runtimeLabel:'Web Audio API com ativação explícita', name:'AudioLab — Frequências e Equalização', shortName:'AudioLab', description:'Gere ondas com volume limitado, visualize espectro, ajuste equalização e identifique graves, médios e agudos.', icon:'Hz', extension:'audio.json', mime:'application/json', tags:['Áudio','Frequência','Equalizador','Ondas','Espectro','Web Audio'] },
  { id:'iptv-streaming', type:'lab', module:'iptv-lab', featured:false, category:'media', level:'intermediate', os:['browser','multi'], runtime:'simulation', runtimeLabel:'Transmissão IP simulada', name:'IPTV, Streaming e Qualidade de Rede', shortName:'IPTV', description:'Compare unicast e multicast, bitrate, buffer, latência, jitter e perda em televisores fictícios.', icon:'TV', extension:'stream.json', mime:'application/json', tags:['IPTV','Streaming','Bitrate','Buffer','Multicast'] },
  { id:'device-sensors', type:'lab', module:'device-lab', featured:false, category:'utilities', level:'intermediate', os:['browser','multi'], runtime:'real', runtimeLabel:'APIs reais com permissão', name:'Câmera, Microfone e Sensores do Dispositivo', shortName:'Dispositivo', description:'Teste recursos do navegador somente após consentimento, com visualização local, diagnóstico e fallbacks.', icon:'CAM', extension:'device.json', mime:'application/json', tags:['Câmera','Microfone','Sensores','Permissões'] },

  { id:'artificial-intelligence', type:'lab', module:'ai-lab', featured:true, category:'emerging', level:'advanced', os:['browser','multi'], runtime:'simulation', runtimeLabel:'Modelo matemático simplificado', name:'Inteligência Artificial e Redes Neurais', shortName:'IA e Redes Neurais', description:'Visualize neurônios, pesos, treinamento, classificação, tokens, contexto e a lógica de um chatbot educacional.', icon:'AI', extension:'ai.json', mime:'application/json', tags:['IA','Rede Neural','Chatbot','Tokens','Treinamento'] },
  { id:'network-operations', type:'lab', module:'network-ops-lab', featured:true, category:'network', level:'advanced', os:['multi'], runtime:'simulation', runtimeLabel:'Operações de rede simuladas', name:'Rack, MikroTik, CFTV e Cabeamento', shortName:'NOC e CFTV', description:'Crimpe RJ45, configure VLAN, portas, DHCP, firewall, câmeras IP, bitrate e armazenamento.', icon:'NOC', extension:'noc.json', mime:'application/json', tags:['RJ45','MikroTik','VLAN','CFTV','NVR','Rack'] },
  { id:'game-engine', type:'lab', module:'game-engine-lab', featured:true, category:'graphics', level:'advanced', os:['browser','multi'], runtime:'real', runtimeLabel:'Renderização Canvas em tempo real', name:'Laboratório de Engine e Renderização', shortName:'Engine e Renderização', description:'Explore loop, física e telemetria; edite um mundo isométrico com desfazer/refazer e meça o custo real do Canvas com recomendações.', icon:'ENG', extension:'engine.json', mime:'application/json', tags:['Canvas','Game Loop','Física','Colisão','Câmera','Renderização','Profiler'] },
  { id:'electronics', type:'lab', module:'electronics-lab', featured:false, category:'automation', level:'intermediate', os:['browser','multi'], runtime:'simulation', runtimeLabel:'Circuitos e cálculos simulados', name:'Eletrônica, Energia e Calculadoras', shortName:'Eletrônica', description:'Use calculadora científica, monte circuito com LED, tensão, corrente, resistência, polaridade e motor.', icon:'VΩ', extension:'circuit.json', mime:'application/json', tags:['Eletrônica','Ohm','LED','Circuito','Calculadora'] }
];


window.LABDS.EXPERIENCE_LABELS = {
  all:'Todos os tipos', game:'Jogos', emulator:'Emuladores', sensor:'Sensores', simulator:'Simuladores', executor:'Executores de código', tutorial:'Tutoriais e biblioteca', creator:'Criação e produtividade', utility:'Utilitários'
};
window.LABDS.HOME_SHOWCASE_INTERVAL = 7000;
const LABDS_EXPERIENCE_MAP = {
  game:['voxelcraft-3d'],
  emulator:['cmd','powershell','bash','ubuntu','debian','kali','fedora','chromeos','macos','virtual-machine','hardware','network','sysadmin','network-operations','cyber-ops','fintech-pix','blockchain-crypto','digital-communication','iptv-streaming','market-simulator','traffic-radar','energy-systems','printing-3d','artificial-intelligence'],
  sensor:['device-sensors','biomonitor','thermal-panel','audio-lab','automation-iot','display-media','electronics'],
  executor:['python','javascript','web','sql','graphics','data-tools','block-programming'],
  tutorial:['tutorial-center','help-center','tech-explorer'],
  creator:['productivity-suite','school-randomizer','git-github'],
  utility:['world-tools','solar-system']
};
for (const tool of window.LABDS.TOOLS) {
  const experiences=Object.entries(LABDS_EXPERIENCE_MAP).filter(([,ids])=>ids.includes(tool.id)).map(([id])=>id);
  if(!experiences.length)experiences.push('simulator');
  if(tool.runtime==='simulation'&&!experiences.includes('simulator'))experiences.push('simulator');
  tool.experiences=[...new Set(experiences)];
}

window.LABDS.CATEGORY_LABELS = {
  terminal:'Terminais', programming:'Programação', database:'Banco de Dados', network:'Redes e Comunicação', systems:'Sistemas e Hardware', graphics:'Computação Gráfica e Renderização', devops:'Git e DevOps', security:'Cibersegurança', games:'Arcade e Jogos', fintech:'Fintech e Blockchain', automation:'Automação e Eletrônica', emerging:'IA e Tecnologias Emergentes', media:'Mídia, Telas e Áudio', productivity:'Produtividade e Escritório', fabrication:'Fabricação Digital', energy:'Energia e Sustentabilidade', utilities:'Utilitários e Dispositivo', support:'Ajuda e Tutoriais', exploration:'Exploração Tecnológica', science:'Ciência e Astronomia', organization:'Organização Escolar'
};

window.LABDS.RUNTIME_HELP = {
  real:'O código ou cálculo é executado de verdade em um ambiente isolado dentro do navegador.',
  'real-online':'A execução é real, mas a tecnologia WebAssembly é carregada pela internet na primeira utilização.',
  simulation:'O comportamento é reproduzido por um motor educacional. Nenhum sistema operacional, rede ou máquina virtual real é acessado.',
  demo:'Este módulo apresenta uma demonstração visual com recursos limitados e claramente identificados.'
};

window.LABDS.DEFAULT_NETWORK_PROFILE = 'rede_domestica';
window.LABDS.MAX_TERMINAL_LINES = 1200;
window.LABDS.PYODIDE_URL = 'https://cdn.jsdelivr.net/pyodide/v0.27.7/full/pyodide.js';
window.LABDS.PYODIDE_INDEX = 'https://cdn.jsdelivr.net/pyodide/v0.27.7/full/';
window.LABDS.SQLJS_URL = 'https://cdn.jsdelivr.net/npm/sql.js@1.13.0/dist/sql-wasm.js';
window.LABDS.SQLJS_WASM = 'https://cdn.jsdelivr.net/npm/sql.js@1.13.0/dist/sql-wasm.wasm';

window.LABDS.SECURITY_LIMITS = {codeBytes:200000,outputBytes:200000,workerMessages:350,previewMessages:250,previewMessageBytes:16384,sqlTimeoutMs:9000,javascriptTimeoutMs:8000,pythonTimeoutMs:25000};
