import { TECHNICAL_SYSTEM_BY_ID,TECHNICAL_VIEW_MODES } from '../../data/technicalMuseumSystems.js';
const clamp=(v,min,max)=>Math.min(max,Math.max(min,v));
const clone=value=>JSON.parse(JSON.stringify(value));
export class OperationalPanelModel{
  constructor(systemId='satellite'){this.systemId=null;this.viewMode='external';this.selectedSubsystemId=null;this.values={};this.fault=null;this.inspected=new Set();this.usedModes=new Set(['external']);this.actions=[];this.resolvedFaults=new Set();this.completedSteps=new Set();this.procedureIndex=0;this.startedAt=new Date().toISOString();this.elapsed=0;this.selectSystem(systemId);}
  system(){return TECHNICAL_SYSTEM_BY_ID[this.systemId];}
  selectSystem(id){const system=TECHNICAL_SYSTEM_BY_ID[id];if(!system)return false;this.systemId=id;this.selectedSubsystemId=system.subsystems[0]?.id||null;this.viewMode='external';this.values=Object.fromEntries(system.telemetry.map(item=>[item.id,item.nominal]));this.fault=null;this.inspected=new Set();this.usedModes=new Set(['external']);this.actions=[];this.resolvedFaults=new Set();this.completedSteps=new Set();this.procedureIndex=0;this.startedAt=new Date().toISOString();this.elapsed=0;return true;}
  selectSubsystem(id){if(!this.system().subsystems.some(item=>item.id===id))return false;this.selectedSubsystemId=id;this.inspected.add(id);this.record(`inspect:${id}`,{subsystemId:id});this.evaluateProcedure();return true;}
  setViewMode(id){if(!TECHNICAL_VIEW_MODES.some(item=>item.id===id))return false;this.viewMode=id;this.usedModes.add(id);this.record(`mode:${id}`,{});this.evaluateProcedure();return true;}
  injectFault(id){const fault=this.system().faults.find(item=>item.id===id);if(!fault)return null;this.fault=fault;this.applyEffect(fault.effect);this.record(`fault:${id}`,{severity:fault.severity});return clone(fault);}
  executeCommand(id){const command=this.system().commands.find(item=>item.id===id);if(!command)return {ok:false,reason:'Comando não encontrado.'};this.applyEffect(command.effect);this.record(`command:${id}`,{target:command.target});if(this.fault&&this.fault.target===command.target){this.resolvedFaults.add(this.fault.id);this.record(`resolve:${this.fault.id}`,{command:id});this.fault=null;}this.evaluateProcedure();return {ok:true,command:clone(command),snapshot:this.snapshot()};}
  applyEffect(effect={}){const metrics=Object.fromEntries(this.system().telemetry.map(item=>[item.id,item]));for(const [id,delta] of Object.entries(effect)){const metric=metrics[id];if(!metric)continue;this.values[id]=clamp(Number(this.values[id]??metric.nominal)+Number(delta||0),metric.min,metric.max);}}
  update(dt=.016){this.elapsed+=Math.max(0,Number(dt)||0);const system=this.system();for(const item of system.telemetry){const current=Number(this.values[item.id]??item.nominal),drift=(item.nominal-current)*Math.min(.06,dt*.08);this.values[item.id]=clamp(current+drift,item.min,item.max);}if(this.fault){for(const [id,delta] of Object.entries(this.fault.effect||{})){const metric=system.telemetry.find(item=>item.id===id);if(metric)this.values[id]=clamp(this.values[id]+Math.sign(delta)*Math.abs(delta)*dt*.002,metric.min,metric.max);}}}
  metricState(metric){const value=this.values[metric.id];return value<metric.warnLow||value>metric.warnHigh?'alert':'nominal';}
  record(type,detail={}){this.actions.push({type,detail,at:new Date().toISOString()});if(this.actions.length>240)this.actions.shift();}
  evaluateProcedure(){const step=this.currentStep();if(!step)return;const types=new Set(this.actions.map(item=>item.type));if(types.has(step.requiredAction)){this.completedSteps.add(step.id);this.procedureIndex=Math.min(this.system().procedure.length,this.procedureIndex+1);}}
  currentStep(){return this.system().procedure[this.procedureIndex]||null;}
  progress(){return {inspected:this.inspected.size,modes:this.usedModes.size,resolved:this.resolvedFaults.size,steps:this.completedSteps.size,totalSteps:this.system().procedure.length,completed:this.completedSteps.size>=this.system().procedure.length};}
  snapshot(){const system=this.system();return {systemId:this.systemId,viewMode:this.viewMode,selectedSubsystemId:this.selectedSubsystemId,values:{...this.values},telemetry:system.telemetry.map(item=>({...item,value:this.values[item.id],state:this.metricState(item)})),fault:this.fault?clone(this.fault):null,progress:this.progress(),procedureIndex:this.procedureIndex,currentStep:this.currentStep()?clone(this.currentStep()):null,actions:clone(this.actions),elapsed:this.elapsed};}
  evidence(profile={}){const system=this.system(),snap=this.snapshot();return {schema:'cosmos-ds-technical-panel-evidence-v1',generatedAt:new Date().toISOString(),student:{id:profile.id||'',name:profile.name||'',className:profile.className||'',callsign:profile.callsign||''},system:{id:system.id,name:system.name,summary:system.summary},session:{startedAt:this.startedAt,elapsedSeconds:Math.round(this.elapsed),viewModes:[...this.usedModes],inspectedSubsystems:[...this.inspected],resolvedFaults:[...this.resolvedFaults],procedure:snap.progress,activeFault:this.fault?.id||null},telemetry:snap.telemetry.map(item=>({id:item.id,label:item.label,value:Number(item.value.toFixed(item.precision)),unit:item.unit,state:item.state})),actions:snap.actions.slice(-80)};}
}
