'use strict';
(function(){
  window.LABDS_LABS=window.LABDS_LABS||{};
  const KEY='lab.school-randomizer.v32';
  const DEFAULT_CLASSES=['1º DS — Manhã|38','2º DS — Manhã|36','3º DS — Manhã|34','1º ADM — Manhã|36','2º ADM — Manhã|35','1º Portos — Manhã|32','DS Subsequente — Noite|30'];
  const DEFAULT_ROOMS=['Laboratório de Informática|32','Sala Multimídia|35','Biblioteca|25','Auditório|80','Sala 01|40','Sala 02|40','Sala 03|40'];
  let root,ctx,state;
  const $=s=>root.querySelector(s),$$=s=>[...root.querySelectorAll(s)];
  const esc=value=>String(value??'').replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]));
  const clamp=(n,a,b)=>Math.min(b,Math.max(a,Number(n)||0));
  function defaults(){return{tab:'names',names:'Ana\nBruno\nCarla\nDiego\nEduarda\nFelipe',drawCount:1,noRepeat:true,seed:'AGV-2026',remaining:[],numbers:{min:1,max:40,count:1,noRepeat:true,exclude:''},teams:{count:3,together:'',avoid:''},classes:DEFAULT_CLASSES.join('\n'),rooms:DEFAULT_ROOMS.join('\n'),history:[]};}
  function cleanList(text){return [...new Set(String(text||'').split(/\r?\n|[,;]/).map(x=>x.trim()).filter(Boolean))].slice(0,500);}
  function hashSeed(value){let h=2166136261;for(const c of String(value||Date.now())){h^=c.charCodeAt(0);h=Math.imul(h,16777619);}return h>>>0;}
  function rngFrom(seed){let a=hashSeed(seed);return function(){a|=0;a=a+0x6D2B79F5|0;let t=Math.imul(a^a>>>15,1|a);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296;};}
  function shuffle(items,seed){const out=[...items],rng=rngFrom(seed);for(let i=out.length-1;i>0;i--){const j=Math.floor(rng()*(i+1));[out[i],out[j]]=[out[j],out[i]];}return out;}
  function save(){ctx.storage.set(KEY,state);}
  function addHistory(kind,label,result,meta={}){state.history.unshift({id:crypto.randomUUID?.()||String(Date.now()),kind,label,result,meta,at:new Date().toISOString()});state.history=state.history.slice(0,80);save();renderHistory();}
  function reward(kind){ctx.core?.complete?.(`school-randomizer:${kind}`,{xp:35,credits:15,reason:`Sorteio escolar validado: ${kind}`});}
  function sectionTemplate(){return`<div class="randomizer-lab">
    <header class="randomizer-hero"><div><span class="eyebrow">ORGANIZAÇÃO ESCOLAR</span><h2>Sorteios, equipes, turmas e salas</h2><p>Crie sorteios reproduzíveis, sem repetição e com histórico local. As listas podem ser editadas ou importadas.</p></div><div class="randomizer-seed"><label>Semente do sorteio<input id="randomSeed" value="${esc(state.seed)}" maxlength="80"></label><small>A mesma semente e a mesma lista produzem o mesmo resultado.</small></div></header>
    <nav class="randomizer-tabs" aria-label="Ferramentas de sorteio">${[['names','Nomes'],['teams','Equipes'],['numbers','Números'],['rooms','Turmas e salas']].map(([id,label])=>`<button type="button" data-random-tab="${id}" class="${state.tab===id?'active':''}">${label}</button>`).join('')}</nav>
    <section class="randomizer-layout"><main id="randomizerPanel"></main><aside><div class="state-card info"><h3>Resultado atual</h3><div id="randomizerResult" class="randomizer-result" aria-live="polite"><span>Faça um sorteio para ver o resultado.</span></div></div><section class="randomizer-history"><div class="section-heading compact"><div><span class="eyebrow">REGISTRO LOCAL</span><h3>Histórico</h3></div><button id="clearRandomHistory" class="btn subtle" type="button">Limpar</button></div><div id="randomizerHistory"></div></section></aside></section>
  </div>`;}
  function namesPanel(){return`<section class="randomizer-card"><h3>Sorteador de nomes</h3><p>Cole um nome por linha. A opção sem repetição mantém uma fila até todos serem sorteados.</p><label>Lista de nomes<textarea id="randomNames" rows="11" maxlength="12000">${esc(state.names)}</textarea></label><div class="randomizer-controls"><label>Quantidade<input id="randomDrawCount" type="number" min="1" max="50" value="${state.drawCount}"></label><label class="check-row"><input id="randomNoRepeat" type="checkbox" ${state.noRepeat?'checked':''}> Não repetir até esgotar a lista</label></div><div class="button-row"><button id="drawNames" class="btn primary" type="button">Sortear nomes</button><button id="resetNamesPool" class="btn secondary" type="button">Reiniciar fila</button><button id="importNames" class="btn secondary" type="button">Importar TXT/CSV</button><input id="importNamesFile" type="file" accept=".txt,.csv,text/plain,text/csv" hidden></div><small id="namesPoolInfo"></small></section>`;}
  function teamsPanel(){return`<section class="randomizer-card"><h3>Formação de equipes</h3><p>As equipes são distribuídas pelo menor tamanho. Regras “juntos” e “separados” usam nomes exatamente como aparecem na lista.</p><label>Estudantes<textarea id="teamNames" rows="10" maxlength="12000">${esc(state.names)}</textarea></label><div class="randomizer-controls"><label>Número de equipes<input id="teamCount" type="number" min="2" max="20" value="${state.teams.count}"></label><label>Devem ficar juntos <small>Ex.: Ana + Bruno</small><textarea id="teamTogether" rows="3">${esc(state.teams.together)}</textarea></label><label>Evitar na mesma equipe <small>Ex.: Carla + Diego</small><textarea id="teamAvoid" rows="3">${esc(state.teams.avoid)}</textarea></label></div><button id="drawTeams" class="btn primary" type="button">Formar equipes</button><div id="teamWarnings" class="inline-message hidden"></div></section>`;}
  function numbersPanel(){return`<section class="randomizer-card"><h3>Sorteador de números</h3><div class="randomizer-controls grid"><label>Mínimo<input id="numberMin" type="number" value="${state.numbers.min}"></label><label>Máximo<input id="numberMax" type="number" value="${state.numbers.max}"></label><label>Quantidade<input id="numberCount" type="number" min="1" max="200" value="${state.numbers.count}"></label><label>Números excluídos<input id="numberExclude" value="${esc(state.numbers.exclude)}" placeholder="3, 7, 12"></label><label class="check-row"><input id="numberNoRepeat" type="checkbox" ${state.numbers.noRepeat?'checked':''}> Não repetir no mesmo sorteio</label></div><button id="drawNumbers" class="btn primary" type="button">Sortear números</button></section>`;}
  function roomsPanel(){return`<section class="randomizer-card"><h3>Sorteador de turmas e salas</h3><p>Use o formato <code>Nome|quantidade</code>. O sistema escolhe apenas salas com capacidade suficiente para a turma.</p><div class="room-editor-grid"><label>Turmas<textarea id="classList" rows="10">${esc(state.classes)}</textarea></label><label>Salas<textarea id="roomList" rows="10">${esc(state.rooms)}</textarea></label></div><div class="button-row"><button id="drawClassRoom" class="btn primary" type="button">Sortear turma e sala compatível</button><button id="drawClassOnly" class="btn secondary" type="button">Sortear somente turma</button><button id="drawRoomOnly" class="btn secondary" type="button">Sortear somente sala</button></div></section>`;}
  function parsePairs(text){return String(text||'').split(/\r?\n/).map(line=>line.split(/\s*\+\s*/).map(x=>x.trim()).filter(Boolean)).filter(pair=>pair.length>=2);}
  function renderPanel(){const panel=$('#randomizerPanel');panel.innerHTML=state.tab==='names'?namesPanel():state.tab==='teams'?teamsPanel():state.tab==='numbers'?numbersPanel():roomsPanel();bindPanel();if(state.tab==='names')updatePoolInfo();}
  function showResult(title,items,detail=''){const host=$('#randomizerResult');host.textContent='';const h=document.createElement('strong');h.textContent=title;host.appendChild(h);const list=document.createElement('div');list.className='randomizer-result-items';items.forEach((item,index)=>{const chip=document.createElement('span');chip.textContent=String(item);chip.style.setProperty('--delay',`${index*70}ms`);list.appendChild(chip);});host.appendChild(list);if(detail){const small=document.createElement('small');small.textContent=detail;host.appendChild(small);}host.classList.remove('animate');requestAnimationFrame(()=>host.classList.add('animate'));}
  function updatePoolInfo(){const all=cleanList(state.names),remaining=Array.isArray(state.remaining)?state.remaining.length:0;const el=$('#namesPoolInfo');if(el)el.textContent=state.noRepeat?`${remaining||all.length} de ${all.length} nomes disponíveis na fila.`:`${all.length} nomes na lista; repetição permitida.`;}
  function drawNames(){state.names=$('#randomNames').value;state.drawCount=clamp($('#randomDrawCount').value,1,50);state.noRepeat=$('#randomNoRepeat').checked;state.seed=$('#randomSeed').value.trim()||String(Date.now());const all=cleanList(state.names);if(!all.length)return ctx.toast('Informe pelo menos um nome.','warning');let source=state.noRepeat&&state.remaining.length?state.remaining.filter(name=>all.includes(name)):all;if(!source.length)source=all;const count=Math.min(state.drawCount,state.noRepeat?source.length:50),random=shuffle(source,`${state.seed}:${state.history.length}:${source.length}`);const result=state.noRepeat?random.slice(0,count):Array.from({length:count},(_,i)=>random[i%random.length]);if(state.noRepeat)state.remaining=source.filter(name=>!result.includes(name));showResult('Nomes sorteados',result,`Semente: ${state.seed}`);addHistory('names','Sorteio de nomes',result.join(', '),{seed:state.seed,noRepeat:state.noRepeat});reward('names');updatePoolInfo();}
  function formTeams(){state.names=$('#teamNames').value;state.teams.count=clamp($('#teamCount').value,2,20);state.teams.together=$('#teamTogether').value;state.teams.avoid=$('#teamAvoid').value;state.seed=$('#randomSeed').value.trim()||String(Date.now());const names=cleanList(state.names);if(names.length<state.teams.count)return ctx.toast('A quantidade de estudantes precisa ser maior ou igual ao número de equipes.','warning');const known=new Set(names),together=parsePairs(state.teams.together),avoid=parsePairs(state.teams.avoid),used=new Set(),groups=[];for(const pair of together){const group=[...new Set(pair.filter(x=>known.has(x)&&!used.has(x)))];if(group.length){group.forEach(x=>used.add(x));groups.push(group);}}for(const name of shuffle(names.filter(x=>!used.has(x)),`${state.seed}:solo`))groups.push([name]);const teams=Array.from({length:state.teams.count},(_,i)=>({name:`Equipe ${i+1}`,members:[]}));for(const group of shuffle(groups,`${state.seed}:groups`)){teams.sort((a,b)=>a.members.length-b.members.length);teams[0].members.push(...group);}const violations=[];for(const pair of avoid){const team=teams.find(t=>pair.every(name=>t.members.includes(name)));if(team)violations.push(`${pair.join(' + ')} ficaram na ${team.name}.`);}const result=teams.map(t=>`${t.name}: ${t.members.join(', ')}`);showResult('Equipes formadas',result,violations.length?'Há restrições que exigem ajuste manual.':'Distribuição concluída sem conflito detectado.');const warning=$('#teamWarnings');if(violations.length){warning.textContent=`Atenção: ${violations.join(' ')}`;warning.classList.remove('hidden');}addHistory('teams','Formação de equipes',result.join(' | '),{seed:state.seed,violations});reward('teams');save();}
  function drawNumbers(){const n=state.numbers;n.min=Math.trunc(Number($('#numberMin').value));n.max=Math.trunc(Number($('#numberMax').value));n.count=clamp($('#numberCount').value,1,200);n.noRepeat=$('#numberNoRepeat').checked;n.exclude=$('#numberExclude').value;state.seed=$('#randomSeed').value.trim()||String(Date.now());if(!Number.isFinite(n.min)||!Number.isFinite(n.max)||n.max<n.min)return ctx.toast('Defina um intervalo válido.','warning');const excluded=new Set(String(n.exclude).split(/[,;\s]+/).map(Number).filter(Number.isFinite)),pool=[];for(let value=n.min;value<=n.max&&pool.length<100000;value++)if(!excluded.has(value))pool.push(value);if(!pool.length)return ctx.toast('Todos os números foram excluídos.','warning');if(n.noRepeat&&n.count>pool.length)return ctx.toast(`Há somente ${pool.length} números disponíveis sem repetição.`,'warning');const random=shuffle(pool,`${state.seed}:numbers:${state.history.length}`),rng=rngFrom(`${state.seed}:replace:${state.history.length}`);const result=n.noRepeat?random.slice(0,n.count):Array.from({length:n.count},()=>pool[Math.floor(rng()*pool.length)]);showResult('Números sorteados',result,`Intervalo ${n.min}–${n.max}`);addHistory('numbers','Sorteio de números',result.join(', '),{seed:state.seed});reward('numbers');save();}
  function parseCapacity(text){return String(text||'').split(/\r?\n/).map(line=>{const [name,raw]=line.split('|');return{name:String(name||'').trim(),capacity:clamp(raw,0,10000)};}).filter(x=>x.name);}
  function drawRoom(mode){state.classes=$('#classList').value;state.rooms=$('#roomList').value;state.seed=$('#randomSeed').value.trim()||String(Date.now());const classes=parseCapacity(state.classes),rooms=parseCapacity(state.rooms),seed=`${state.seed}:rooms:${state.history.length}`;if(mode!=='room'&&!classes.length)return ctx.toast('Cadastre pelo menos uma turma.','warning');if(mode!=='class'&&!rooms.length)return ctx.toast('Cadastre pelo menos uma sala.','warning');if(mode==='class'){const item=shuffle(classes,seed)[0];showResult('Turma sorteada',[`${item.name} — ${item.capacity||'?'} estudantes`]);addHistory('classes','Sorteio de turma',item.name,{seed:state.seed});reward('classes');save();return;}if(mode==='room'){const item=shuffle(rooms,seed)[0];showResult('Sala sorteada',[`${item.name} — capacidade ${item.capacity||'não informada'}`]);addHistory('rooms','Sorteio de sala',item.name,{seed:state.seed});reward('rooms');save();return;}const chosenClass=shuffle(classes,`${seed}:class`)[0],compatible=rooms.filter(room=>!chosenClass.capacity||!room.capacity||room.capacity>=chosenClass.capacity);if(!compatible.length)return ctx.toast('Nenhuma sala cadastrada comporta a turma sorteada.','warning');const chosenRoom=shuffle(compatible,`${seed}:room`)[0];showResult('Alocação sorteada',[chosenClass.name,chosenRoom.name],`${chosenClass.capacity||'?'} estudantes • capacidade ${chosenRoom.capacity||'?'}`);addHistory('allocation','Turma e sala',`${chosenClass.name} → ${chosenRoom.name}`,{seed:state.seed,classSize:chosenClass.capacity,roomCapacity:chosenRoom.capacity});reward('allocation');save();}
  function renderHistory(){const host=$('#randomizerHistory');if(!host)return;host.textContent='';if(!state.history.length){host.innerHTML='<p class="empty">Nenhum sorteio registrado.</p>';return;}state.history.slice(0,12).forEach(item=>{const article=document.createElement('article'),time=document.createElement('time'),strong=document.createElement('strong'),span=document.createElement('span');time.textContent=new Date(item.at).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'});strong.textContent=item.label;span.textContent=item.result;article.append(time,strong,span);host.appendChild(article);});}
  function bindPanel(){if(state.tab==='names'){$('#drawNames').onclick=drawNames;$('#resetNamesPool').onclick=()=>{state.remaining=[];save();updatePoolInfo();ctx.toast('Fila reiniciada.','success');};$('#randomNames').oninput=()=>{state.names=$('#randomNames').value;state.remaining=[];save();updatePoolInfo();};$('#randomNoRepeat').onchange=()=>{state.noRepeat=$('#randomNoRepeat').checked;state.remaining=[];save();updatePoolInfo();};$('#importNames').onclick=()=>$('#importNamesFile').click();$('#importNamesFile').onchange=async event=>{const file=event.target.files?.[0];if(!file)return;$('#randomNames').value=(await file.text()).replace(/[,;]/g,'\n');$('#randomNames').dispatchEvent(new Event('input'));};}
    if(state.tab==='teams')$('#drawTeams').onclick=formTeams;
    if(state.tab==='numbers')$('#drawNumbers').onclick=drawNumbers;
    if(state.tab==='rooms'){$('#drawClassRoom').onclick=()=>drawRoom('both');$('#drawClassOnly').onclick=()=>drawRoom('class');$('#drawRoomOnly').onclick=()=>drawRoom('room');}
  }
  async function mount(host,context){root=host;ctx=context;state={...defaults(),...(await ctx.storage.get(KEY,{}))};state.numbers={...defaults().numbers,...(state.numbers||{})};state.teams={...defaults().teams,...(state.teams||{})};root.innerHTML=sectionTemplate();$$('[data-random-tab]').forEach(button=>button.onclick=()=>{state.tab=button.dataset.randomTab;save();$$('[data-random-tab]').forEach(x=>x.classList.toggle('active',x===button));renderPanel();});$('#randomSeed').oninput=()=>{state.seed=$('#randomSeed').value;save();};$('#clearRandomHistory').onclick=()=>{if(confirm('Limpar o histórico local de sorteios?')){state.history=[];save();renderHistory();}};renderPanel();renderHistory();}
  async function unmount(){await ctx?.storage?.set?.(KEY,state);root=null;ctx=null;}
  function exportPayload(){const session=ctx?.session?.get?.();const text=['SORTEIOS E ORGANIZAÇÃO ESCOLAR',`Estudante: ${session?.studentName||'Não informado'}`,`Turma: ${session?.studentClass||'Não informada'}`,`Semente atual: ${state.seed}`,'','HISTÓRICO',...state.history.map(item=>`${new Date(item.at).toLocaleString('pt-BR')} — ${item.label}: ${item.result}`)].join('\n');return{text,native:JSON.stringify({version:window.LABDS.VERSION,exportedAt:new Date().toISOString(),state},null,2),backup:state,meta:[{label:'Sorteios',value:String(state.history.length)},{label:'Semente',value:state.seed}]};}
  function help(){return'<p>Use uma semente para reproduzir o sorteio. Cadastre somente nomes necessários para a atividade e exporte o resultado quando precisar comprovar a organização.</p>';}
  window.LABDS_LABS['school-randomizer-lab']={mount,unmount,exportPayload,help};
})();
