import { createClient } from "jsr:@supabase/supabase-js@2.111.0";
const H={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const J=(x:unknown,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{...H,"Content-Type":"application/json"}}),now=()=>new Date().toISOString();
function sid(auth:string){try{const p=auth.replace(/^Bearer\s+/i,'').trim().split('.')[1];if(!p)return null;let r=p.replace(/-/g,'+').replace(/_/g,'/');while(r.length%4)r+='=';return String(JSON.parse(atob(r))?.session_id||'')||null}catch{return null}}
const low=(v:unknown)=>String(v??'').trim().toLowerCase();
function aliases(name:string){const n=low(name),s=new Set([n]);if(n==='style.css')s.add('estilo.css');if(n==='estilo.css')s.add('style.css');if(n==='app.js')s.add('script.js');if(n==='script.js')s.add('app.js');if(n==='main.kt')s.add('mainactivity.kt');if(n==='mainactivity.kt')s.add('main.kt');if(n==='referencia.md')s.add('atividade.md');return [...s]}
function strip(lang:string,src:string){let v=String(src||'').replace(/\r\n?/g,'\n'),l=low(lang);if(['html','xml'].includes(l))v=v.replace(/<!--[\s\S]*?-->/g,' ');if(['css','javascript','js','kotlin','kt'].includes(l))v=v.replace(/\/\*[\s\S]*?\*\//g,' ').replace(/^\s*\/\/.*$/gm,' ');if(['python','py'].includes(l))v=v.replace(/^\s*#.*$/gm,' ');return v}
function tokens(lang:string,src:string){return (strip(lang,src).match(/(===|!==|=>|==|!=|>=|<=|&&|\|\||\+\+|--|\*\*|\/\/|\$\{|[A-Za-z_$À-ÿ][\w$À-ÿ-]*|\d+(?:\.\d+)?|"(?:\\.|[^"\\])*"|'(?:\\.|[^'\\])*'|`(?:\\.|[^`\\])*`|[{}()[\]<>:;,.#@%+*\/=!?&|$-])/g)||[]).map(t=>/[A-Za-zÀ-ÿ]/.test(t)?t.toLowerCase():t)}
function f1(a:string[],b:string[]){if(!a.length&&!b.length)return 1;if(!a.length||!b.length)return 0;const A=new Map<string,number>(),B=new Map<string,number>();for(const x of a)A.set(x,(A.get(x)||0)+1);for(const x of b)B.set(x,(B.get(x)||0)+1);let c=0;for(const [k,n] of A)c+=Math.min(n,B.get(k)||0);const p=c/a.length,r=c/b.length;return p+r?2*p*r/(p+r):0}
function pairs(t:string[]){const s=new Set<string>();for(let i=0;i<t.length-1;i++)s.add(`${t[i]}\u0001${t[i+1]}`);return s}function jac(a:Set<string>,b:Set<string>){if(!a.size&&!b.size)return 1;let i=0;for(const x of a)if(b.has(x))i++;return (a.size+b.size-i)?i/(a.size+b.size-i):0}
function structural(t:string[]){return new Set(t.filter(x=>x.length>1||['{','}','(',')','[',']','<','>','=',':',';','!','?','%','/','*','+','-','=>','===','!==','==','!=','>=','<=','&&','||','${'].includes(x)))}
function balanced(src:string){const p:any={'(':')','[':']','{':'}'},st:string[]=[];let q='';for(let i=0;i<src.length;i++){const c=src[i];if(q){if(c==='\\'){i++;continue}if(c===q)q='';continue}if(['"',"'",'`'].includes(c)){q=c;continue}if(p[c])st.push(p[c]);else if([')',']','}'].includes(c)&&st.pop()!==c)return false}return st.length===0&&!q}
function syntax(lang:string,src:string){const l=low(lang),v=strip(l,src);if(!v.trim())return false;if(['javascript','js'].includes(l)){try{new Function(v);return true}catch{return false}}return balanced(v)}
const RESERVED:any={
 javascript:new Set('break case catch class const continue debugger default delete do else export extends finally for function if import in instanceof let new return super switch this throw try typeof var void while with yield async await true false null undefined document window console math json array object string number boolean date promise set map queryselector queryselectorall getelementbyid addeventlistener textcontent innerhtml value classlist'.split(' ')),
 python:new Set('and as assert async await break class continue def del elif else except false finally for from global if import in is lambda none nonlocal not or pass raise return true try while with yield print input len int float str bool list dict set tuple range enumerate zip min max sum abs round'.split(' ')),
 kotlin:new Set('as break class continue do else false for fun if in interface is null object package return super this throw true try typealias typeof val var when while import override private public protected internal open data sealed abstract enum android bundle button textview linearlayout appcompatactivity gravity setcontentview setonclicklistener'.split(' '))
};
function canonicalTokens(lang:string,src:string){const l=low(lang),base=tokens(l,src),reserved=RESERVED[l==='js'?'javascript':l==='py'?'python':l==='kt'?'kotlin':l];if(!reserved)return base;return base.map((t,i)=>{if(!/^[A-Za-z_$À-ÿ][\w$À-ÿ-]*$/.test(t)||reserved.has(t))return t;const prev=base[i-1]||'';if(prev==='.')return t;return '<id>'})}
function codeScore(lang:string,student:string,reference:string){const rawS=tokens(lang,student),rawR=tokens(lang,reference),s=canonicalTokens(lang,student),r=canonicalTokens(lang,reference);if(!s.length)return {score:0,syntax_ok:false};const ok=syntax(lang,student);const exact=s.length===r.length&&s.every((x,i)=>x===r[i]);if(exact&&ok)return {score:100,syntax_ok:true,exact:true,canonical_match:true,token_f1:100,sequence:100,structure:100};const tf=f1(s,r),seq=jac(pairs(s),pairs(r)),str=jac(structural(s),structural(r)),literal=f1(rawS,rawR);let score=Math.round((tf*.45+seq*.25+str*.20+literal*.10)*100);if(!ok)score=Math.min(score,70);return {score:Math.max(0,Math.min(99,score)),syntax_ok:ok,exact:false,canonical_match:false,token_f1:Math.round(tf*100),sequence:Math.round(seq*100),structure:Math.round(str*100)}}
function promptLabels(ref:string){return String(ref||'').split(/\r?\n/).map(x=>x.trim()).map(x=>x.match(/^(?:[-*]|\d+[.)])\s*([^:]{3,80}):/i)?.[1]?.trim()).filter(Boolean) as string[]}
function textScore(student:string,reference:string){const s=String(student||'').trim(),labels=promptLabels(reference);if(!s)return {score:0,prompt_coverage:0,length_score:0};const lower=s.toLowerCase();let hit=0;for(const label of labels){const words=label.toLowerCase().split(/\s+/).filter(w=>w.length>3);if(words.some(w=>lower.includes(w)))hit++}const coverage=labels.length?hit/labels.length:Math.min(1,s.length/300),length=Math.min(1,s.length/Math.max(240,labels.length*55));return {score:Math.min(100,Math.round((coverage*.55+length*.45)*100)),prompt_coverage:Math.round(coverage*100),length_score:Math.round(length*100)}}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:H});try{
 const url=Deno.env.get('SUPABASE_URL')!,auth=req.headers.get('Authorization')||'',uc=createClient(url,Deno.env.get('SUPABASE_ANON_KEY')!,{global:{headers:{Authorization:auth}}}),db=createClient(url,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,{auth:{persistSession:false,autoRefreshToken:false}}),{data:{user}}=await uc.auth.getUser();if(!user)return J({error:'unauthorized'},401);const session=sid(auth);if(!session)return J({error:'session_claim_missing'},401);const {data:alive,error:ae}=await db.rpc('security_is_auth_session_active_service',{p_user_id:user.id,p_session_id:session});if(ae)return J({error:'session_guard_unavailable'},503);if(alive!==true)return J({error:'session_revoked'},401);
 const {data:p}=await db.from('profiles').select('role,active,must_change_password').eq('id',user.id).maybeSingle();if(!p?.active||p.role!=='student'||p.must_change_password)return J({error:'student_not_ready'},403);const b=await req.json().catch(()=>({})),action=String(b?.action||'grade'),eid=String(b?.exercise_id||''),activitySession=String(b?.session_id||'');if(!['grade','submit','set_help_hint','merge_help_legacy'].includes(action)||!eid)return J({error:'invalid_request'},400);
 const {data:m}=await db.from('class_memberships').select('class_id').eq('user_id',user.id).eq('active',true).order('is_primary',{ascending:false}).limit(1).maybeSingle();if(!m?.class_id)return J({error:'no_class'},403);const {data:e}=await db.from('exercises').select('id,class_id,subject_id,exercise_number,default_locked,active,visible').eq('id',eid).maybeSingle();if(!e?.active||!e.visible)return J({error:'exercise_forbidden'},403);let belongs=e.class_id?String(e.class_id)===String(m.class_id):false;if(!e.class_id){const {data:cs}=await db.from('class_subjects').select('class_id').eq('class_id',m.class_id).eq('subject_id',e.subject_id).eq('active',true).maybeSingle();belongs=!!cs}if(!belongs)return J({error:'exercise_forbidden'},403);
 const {data:progress}=await db.from('student_exercises').select('status,security_locked,security_lock_reason,attempts,metadata,progress_percent,submitted_score,submitted_at,completed_at,completion_source').eq('student_id',user.id).eq('exercise_id',eid).maybeSingle();if(progress?.security_locked||progress?.status==='blocked')return J({error:'activity_locked',reason:progress?.security_lock_reason||'Atividade bloqueada.'},423);let released=!e.default_locked;const {data:sr}=await db.from('exercise_releases').select('enabled,release_at,lock_at').eq('student_id',user.id).eq('exercise_id',eid).order('updated_at',{ascending:false}).limit(1).maybeSingle();if(sr)released=sr.enabled&&(!sr.release_at||Date.parse(sr.release_at)<=Date.now())&&(!sr.lock_at||Date.parse(sr.lock_at)>Date.now());else{const {data:cr}=await db.from('exercise_releases').select('enabled,release_at,lock_at').is('student_id',null).eq('class_id',m.class_id).eq('exercise_id',eid).order('updated_at',{ascending:false}).limit(1).maybeSingle();if(cr)released=cr.enabled&&(!cr.release_at||Date.parse(cr.release_at)<=Date.now())&&(!cr.lock_at||Date.parse(cr.lock_at)>Date.now())}if(!released)return J({error:'exercise_locked_by_teacher'},423);
 if(!activitySession)return J({error:'active_supervised_session_required'},423);const {data:activity}=await db.from('activity_sessions').select('id,locked,ended_at').eq('id',activitySession).eq('student_id',user.id).eq('exercise_id',eid).maybeSingle();if(!activity||activity.locked||activity.ended_at)return J({error:'active_supervised_session_required'},423)
 if(action==='merge_help_legacy'){
   const corrections=Math.max(0,Math.min(20,Math.floor(Number(b?.manual_corrections)||0)));
   const hintIndex=Math.max(0,Math.min(999,Math.floor(Number(b?.hint_index)||0)));
   const {data,error}=await db.rpc('merge_student_exercise_help_progress',{p_student_id:user.id,p_exercise_id:eid,p_manual_corrections:corrections,p_hint_index:hintIndex});
   if(error)return J({error:'help_progress_unavailable'},503);
   return J({ok:true,action,help_progress:data||null});
 }
 if(action==='set_help_hint'){
   const hintIndex=Math.max(0,Math.min(999,Math.floor(Number(b?.hint_index)||0)));
   const {data,error}=await db.rpc('set_student_exercise_help_hint',{p_student_id:user.id,p_exercise_id:eid,p_hint_index:hintIndex});
   if(error)return J({error:'help_progress_unavailable'},503);
   return J({ok:true,action,help_progress:data||null});
 }
 const [{data:refs,error:re},{data:files,error:fe},{data:subject}]=await Promise.all([db.from('exercise_reference_files').select('filename,language,content,updated_at').eq('exercise_id',eid).order('filename'),db.from('student_files').select('filename,language,content,revision,saved_at,created_at').eq('student_id',user.id).eq('exercise_id',eid).order('filename'),db.from('subjects').select('slug').eq('id',e.subject_id).maybeSingle()]);if(re||fe)throw re||fe;if(!(refs||[]).length)return J({error:'reference_unavailable'},503);
 let historicalRefs:any[]=[];try{const {data,error}=await db.from('exercise_reference_file_versions').select('id,filename,language,content,version_key,label,source_kind,source_ref,effective_from,effective_to,is_current,active,content_hash').eq('exercise_id',eid).eq('active',true).order('filename');if(!error)historicalRefs=Array.isArray(data)?data:[]}catch(error){console.info('[exercise-autograde] reference history unavailable; current reference only',String((error as Error)?.message||error))}
 const subjectSlug=low(subject?.slug),referenceOnly=(refs||[]).filter((ref:any)=>subjectSlug==='programacao-mobile-sub'&&low(ref.filename)==='referencia.md'),gradedRefs=(refs||[]).filter((ref:any)=>!referenceOnly.includes(ref));
 const map=new Map((files||[]).map((f:any)=>[low(f.filename),f])),details:any[]=[];let weighted=0,total=0,meaningful=false,currentMatches=0,legacyMatches=0;
 for(const ref of gradedRefs){
   const currentReference=String(ref.content||''),referenceLanguage=low(ref.language||'text'),w=Math.max(1,tokens(referenceLanguage,currentReference).length||currentReference.length/20||1);total+=w;let student:any=null;for(const n of aliases(ref.filename)){if(map.has(n)){student=map.get(n);break}}
   const candidateMap=new Map<string,any>();
   const addCandidate=(candidate:any,current=false)=>{const content=String(candidate?.content||'');if(!content.trim())return;const key=low(candidate.filename)+'\u0001'+content.replace(/\r\n?/g,'\n');const existing=candidateMap.get(key);if(!existing||current)candidateMap.set(key,{...candidate,content,is_current:Boolean(current||candidate?.is_current)});};
   addCandidate({...ref,id:null,version_key:'current',label:'Atual • sincronizada',source_kind:'exercise_reference_files',source_ref:'exercise_reference_files'},true);
   for(const candidate of historicalRefs){if(aliases(ref.filename).some(n=>aliases(candidate.filename).includes(n)))addCandidate(candidate,Boolean(candidate.is_current));}
   const candidates=[...candidateMap.values()];
   if(!student){details.push({filename:null,reference_filename:ref.filename,language:referenceLanguage,score:0,missing:true,empty:true,reference_candidates:candidates.length,matched_reference_current:true,matched_reference_label:'Atual • sincronizada'});continue}
   const content=String(student.content||''),language=low(student.language||ref.language||'text'),empty=!content.trim();if(!empty)meaningful=true;let best:any=null;
   for(const candidate of candidates){const reference=String(candidate.content||''),result=empty?{score:0,syntax_ok:false,empty:true}:(['markdown','md','text'].includes(language)&&low(ref.filename)==='referencia.md'?textScore(content,reference):codeScore(language,content,reference));const evaluated={candidate,result};if(!best||Number(result.score||0)>Number(best.result.score||0)||(Number(result.score||0)===Number(best.result.score||0)&&candidate.is_current&&!best.candidate.is_current))best=evaluated}
   const result=best?.result||{score:0,syntax_ok:false},matched=best?.candidate||{...ref,is_current:true,label:'Atual • sincronizada',version_key:'current'};weighted+=Number(result.score||0)*w;if(matched.is_current)currentMatches++;else legacyMatches++;
   details.push({filename:student.filename,reference_filename:ref.filename,language,missing:false,empty,...result,reference_candidates:candidates.length,matched_reference_version_id:matched.id||null,matched_reference_version_key:matched.version_key||null,matched_reference_label:matched.label||matched.source_ref||'Referência histórica',matched_reference_source:matched.source_ref||matched.source_kind||null,matched_reference_current:Boolean(matched.is_current),matched_reference_effective_from:matched.effective_from||ref.updated_at||null})
 }
 const score=Math.max(0,Math.min(100,Math.round(total?weighted/total:0))),stamp=now(),requiredThreeFiles=subjectSlug==='programacao-front-end'?['index.html','estilo.css','script.js']:subjectSlug==='programacao-mobile-sub'?(Number((e as any).exercise_number)===4?['MainActivity.kt','strings.xml']:['MainActivity.kt']):[],requiredIncomplete=requiredThreeFiles.filter(name=>{const detail=details.find((d:any)=>aliases(name).includes(low(d.reference_filename)));return !detail||detail.missing||detail.empty}),referenceMatch=legacyMatches&&currentMatches?'mixed':legacyMatches?'legacy':'current',grade={version:'autograde-v8-reference-history',score,files:details,reference_files:gradedRefs.length,reference_files_total:(refs||[]).length,reference_only_files:referenceOnly.map((ref:any)=>ref.filename),reference_variants:historicalRefs.length,reference_match:referenceMatch,current_file_matches:currentMatches,legacy_file_matches:legacyMatches,student_files:(files||[]).length,subject:subject?.slug||null,required_files:requiredThreeFiles,required_incomplete:requiredIncomplete,graded_at:stamp};if(action==='submit'&&requiredIncomplete.length)return J({error:'required_files_incomplete',score,files:details,required_files:requiredThreeFiles,incomplete_files:requiredIncomplete,reference_match:referenceMatch,partial:true},400);if(action==='submit'&&!meaningful)return J({error:'empty_activity',score:0,files:details},400);
 const previousSubmitted=Math.max(0,Math.min(100,Math.round(Number(progress?.submitted_score||0))));
 const officialScore=action==='submit'?Math.max(previousSubmitted,score):previousSubmitted;
 const attempts=Number(progress?.attempts||0)+(action==='submit'?1:0);
 const legacyAlreadyCompleted=Boolean(progress?.status==='completed'&&progress?.metadata?.legacy_version_accepted===true);
 const fullyCompleted=action==='submit'&&(officialScore>=100||legacyAlreadyCompleted);
 const previousBest=progress?.metadata?.best_autograde_submission&&typeof progress.metadata.best_autograde_submission==='object'?progress.metadata.best_autograde_submission:null;
 const bestSubmission=action==='submit'&&score>=previousSubmitted?{score,submitted_at:stamp,authority:'server-reference-v8-history'}:previousBest||((progress?.submitted_score!==null&&progress?.submitted_score!==undefined)?{score:previousSubmitted,submitted_at:progress?.submitted_at||null,authority:'server-reference-v3'}:null);
 if(progress){
   const patch:any={auto_score:score,auto_score_at:stamp,autograde_details:grade,last_activity_at:stamp};
   if(action==='submit'){
     Object.assign(patch,{
       status:fullyCompleted?'completed':'in_progress',
       progress_percent:fullyCompleted?100:Math.min(99,officialScore),
       submitted_score:officialScore,
       submitted_at:stamp,
       completed_at:fullyCompleted?(progress?.completed_at||stamp):null,
       attempts,
       completion_source:fullyCompleted?'autograde_submission':'autograde_submission_partial',
       metadata:{...(progress.metadata||{}),last_autograde_submission:{score,best_score:officialScore,submitted_at:stamp,authority:'server-reference-v8-history'},best_autograde_submission:bestSubmission}
     });
   }
   const {error}=await db.from('student_exercises').update(patch).eq('student_id',user.id).eq('exercise_id',eid);if(error)throw error
 }else{
   const row:any={student_id:user.id,exercise_id:eid,status:'in_progress',progress_percent:0,attempts:0,started_at:stamp,last_activity_at:stamp,auto_score:score,auto_score_at:stamp,autograde_details:grade,completion_source:'platform'};
   if(action==='submit'){
     const completed=score>=100;
     Object.assign(row,{status:completed?'completed':'in_progress',progress_percent:completed?100:Math.min(99,score),attempts:1,submitted_score:score,submitted_at:stamp,completed_at:completed?stamp:null,completion_source:completed?'autograde_submission':'autograde_submission_partial',metadata:{last_autograde_submission:{score,best_score:score,submitted_at:stamp,authority:'server-reference-v8-history'},best_autograde_submission:{score,submitted_at:stamp,authority:'server-reference-v8-history'}}});
   }
   const {error}=await db.from('student_exercises').insert(row);if(error)throw error
 }
 let helpProgress=null,helpSyncFailed=false;
 if(action==='grade'&&b?.manual_correction===true){
   const {data,error}=await db.rpc('increment_student_exercise_help_progress',{p_student_id:user.id,p_exercise_id:eid});
   if(error)helpSyncFailed=true;else helpProgress=data||null;
 }
 return J({ok:true,action,score,official_score:action==='submit'?officialScore:null,attempts,submitted:action==='submit',completed:fullyCompleted||(action==='submit'&&!progress&&score>=100),partial:action==='submit'?!fullyCompleted&&score<100:score<100,files:details,required_files:requiredThreeFiles,incomplete_files:requiredIncomplete,reference_match:referenceMatch,current_file_matches:currentMatches,legacy_file_matches:legacyMatches,reference_variants:historicalRefs.length,authority:'server-reference-v8-history',graded_at:stamp,submitted_at:action==='submit'?stamp:null,help_progress:helpProgress,help_sync_failed:helpSyncFailed});
}catch(e){console.error(e);return J({error:'internal_error',detail:String((e as Error)?.message||e)},500)}});
