import { PremiumAssetSceneRenderer } from '../../rendering/PremiumAssetSceneRenderer.js';
import { PremiumAssetManager } from '../../core/assets/PremiumAssetManager.js';
import { ImmersiveInputController } from '../../core/input/ImmersiveInputController.js';
import { SpatialAudioEngine } from '../../core/assets/SpatialAudioEngine.js';
import { PREMIUM_ASSET_ICONS, PREMIUM_INSPECTION_GOALS, PREMIUM_RENDER_MODES } from '../../data/premiumAssetSystems.js';
const escapeHtml=value=>String(value??'').replace(/[&<>"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[char]));
const kb=value=>Math.max(1,Math.round(Number(value||0)/1024));
class PremiumAssetsModule{
  constructor(){this.host=null;this.context=null;this.renderer=null;this.input=null;this.assets=[];this.activeId='shuttle';this.diagnostics={};this.inspected=new Set();this.lodsSeen=new Set();this.modesSeen=new Set([0]);this.animationsSeen=new Set();this.goals=new Set();this.audio=new SpatialAudioEngine();this.hotspotsSeen=new Set();this.onClick=e=>this.handleClick(e);this.onChange=e=>this.handleChange(e);this.onKeyDown=e=>this.handleKeyDown(e);}
  mount(host,context){this.host=host;this.context=context;this.host.innerHTML='<section class="premium-assets-stage"><div class="premium-assets-loading"><i></i><b>Preparando pipeline GLB/PBR</b><span>Geometria, texturas e ambiente HDR sob demanda</span></div></section>';this.boot().catch(error=>{this.context.toast(error.message||'Falha ao abrir o laboratório premium.');this.context.onBack();});}
  async boot(){this.manager=new PremiumAssetManager({settingsStore:this.context.settingsStore});await this.manager.init();this.assets=this.manager.list();this.activeId=this.assets[0]?.id||'shuttle';const completed=this.context.profileStore.active().completedExperiences;for(const goal of PREMIUM_INSPECTION_GOALS)if(completed.includes(`premium-${goal.id}`))this.goals.add(goal.id);this.render();const canvas=this.host.querySelector('.premium-assets-canvas'),left=this.host.querySelector('[data-stick="left"]'),right=this.host.querySelector('[data-stick="right"]');this.input=new ImmersiveInputController({canvas,root:this.host,leftStick:left,rightStick:right});this.renderer=new PremiumAssetSceneRenderer(canvas,this.context.settingsStore,{input:this.input,onDiagnostics:data=>this.updateDiagnostics(data),onAssetLoaded:data=>this.assetLoaded(data)});this.renderer.manager=this.manager;this.renderer.assetId=this.activeId;this.input.attach();this.host.addEventListener('click',this.onClick);this.host.addEventListener('change',this.onChange);addEventListener('keydown',this.onKeyDown);await this.renderer.start();this.host.querySelector('.premium-assets-loading')?.classList.add('hidden');}
  render(){const profile=this.context.settingsStore.getProfile(),asset=this.assets.find(item=>item.id===this.activeId)||this.assets[0],completed=this.context.profileStore.active().completedExperiences;this.host.innerHTML=`<section class="premium-assets-stage quality-${profile.id}">
    <canvas class="premium-assets-canvas" aria-label="Visualizador 3D de assets premium"></canvas>
    <div class="premium-assets-grain" aria-hidden="true"></div>
    <header class="immersive-hud premium-assets-top"><button data-action="back" class="icon-button" aria-label="Voltar">←</button><div class="target-chip"><i>${PREMIUM_ASSET_ICONS[asset?.id]||'⬡'}</i><span><b data-asset-title>${escapeHtml(asset?.title||'Asset Premium')}</b><small>GLB · PBR · LOD · HDR</small></span></div><span class="hud-status" data-renderer-status>CARREGANDO</span><button data-action="fullscreen" class="icon-button">⛶</button></header>
    <div class="objective-chip premium-assets-objective"><i>◆</i><span><b>ESTÚDIO PREMIUM</b><small>Inspecione, compare LODs e prepare pacotes gráficos.</small></span></div>
    <aside class="premium-assets-telemetry">
      <div><b>TRIÂNGULOS</b><span data-diag="triangles">—</span></div><div><b>VÉRTICES</b><span data-diag="vertices">—</span></div><div><b>PEÇAS</b><span data-diag="parts">—</span></div><div><b>ANIMAÇÕES</b><span data-diag="animations">—</span></div><div><b>LOD</b><span data-diag="lod">AUTO</span></div><div><b>CARGA</b><span data-diag="load">—</span></div>
    </aside>
    <nav class="premium-assets-tools" aria-label="Ferramentas gráficas">
      ${PREMIUM_RENDER_MODES.map(mode=>`<button data-action="mode" data-mode="${mode.id}" class="${mode.id===0?'active':''}"><i>${mode.icon}</i><span>${mode.label}</span></button>`).join('')}
      <button data-action="section"><i>◫</i><span>Corte</span></button><button data-action="autorotate" class="active"><i>↻</i><span>Girar</span></button><button data-action="photo"><i>◌</i><span>Foto</span></button>
    </nav>
    <div class="premium-assets-lod"><b>LOD</b><select data-control="lod" aria-label="Nível de detalhe"><option value="auto">Automático</option><option value="0">0 · Desempenho</option><option value="1">1 · Equilibrado</option><option value="2">2 · Experiência</option></select><button data-action="cache-pack">⇩ Offline</button><button data-action="release-pack">⌫ Memória</button></div>
    <aside class="premium-hotspot-panel immersive-hud" data-hotspot-panel><b>INTERIORES HD</b><span>Carregando componentes interativos…</span></aside><div class="premium-animation-rail immersive-hud" data-animation-rail><b>RIG GLTF</b><span>Selecione um asset para carregar as animações.</span></div><div class="premium-assets-progress"><span>${PREMIUM_INSPECTION_GOALS.map(goal=>`<i data-goal="${goal.id}" title="${escapeHtml(goal.label)}" class="${completed.includes(`premium-${goal.id}`)?'done':''}"></i>`).join('')}</span><small data-progress-label>${this.goals.size}/${PREMIUM_INSPECTION_GOALS.length} objetivos gráficos</small></div>
    <div class="virtual-joysticks premium-assets-joysticks"><div class="virtual-joystick" data-stick="left"><span class="joystick-knob"></span><small>ZOOM</small></div><div class="virtual-joystick" data-stick="right"><span class="joystick-knob"></span><small>360°</small></div></div>
    <div class="premium-assets-mobile-actions"><button data-action="previous">◀</button><button data-action="next">▶</button><button data-action="section">◫</button></div>
    <footer class="premium-assets-dock">${this.assets.map(item=>`<button data-action="asset" data-id="${item.id}" class="${item.id===this.activeId?'active':''}" style="--asset-color:${item.category==='Robótica'?'#ff9164':item.category==='Satélites'?'#78d9ff':'#8af2d2'}"><i>${PREMIUM_ASSET_ICONS[item.id]||'⬡'}</i><span><b>${escapeHtml(item.title)}</b><small>${escapeHtml(item.category)}</small></span></button>`).join('')}</footer>
    <aside class="premium-assets-info" data-panel="info"><button data-action="close-info" class="drawer-close">×</button><h2 data-info-title>${escapeHtml(asset?.title||'')}</h2><p data-info-description>${escapeHtml(asset?.description||'')}</p><div class="premium-assets-specs" data-info-specs></div><button data-action="cache-pack" class="primary-button">Baixar pacote offline</button></aside>
    <button data-action="info" class="premium-assets-info-button">i</button>
    <div class="premium-assets-loading"><i></i><b>CARREGANDO ASSET GLB</b><span data-loading-label>Selecionando LOD compatível</span></div>
  </section>`;}
  async handleClick(event){const button=event.target.closest('[data-action]');if(!button)return;const action=button.dataset.action;if(action==='back')return this.context.onBack();if(action==='fullscreen')return this.renderer.requestFullscreen();if(action==='asset')return this.selectAsset(button.dataset.id);if(action==='previous'||action==='next'){const index=this.assets.findIndex(item=>item.id===this.activeId),step=action==='next'?1:-1;return this.selectAsset(this.assets[(index+step+this.assets.length)%this.assets.length].id);}if(action==='mode'){this.host.querySelectorAll('[data-action="mode"]').forEach(item=>item.classList.toggle('active',item===button));this.renderer.setMode(button.dataset.mode);this.modesSeen.add(Number(button.dataset.mode));this.checkGoals();}if(action==='section'){button.classList.toggle('active');this.renderer.setInteriorMode(button.classList.contains('active'));if(button.classList.contains('active'))this.completeGoal('section-cut');}if(action==='autorotate'){button.classList.toggle('active');this.renderer.setAutoRotate(button.classList.contains('active'));}if(action==='photo')this.host.querySelector('.premium-assets-stage')?.classList.toggle('photo-mode');if(action==='info')this.host.querySelector('[data-panel="info"]')?.classList.add('open');if(action==='close-info')this.host.querySelector('[data-panel="info"]')?.classList.remove('open');if(action==='hotspot'){const result=this.renderer.activateInteraction(button.dataset.index);if(result){await this.audio.playMechanical(result.audio,{pan:Math.sin(this.renderer.yaw),intensity:1});this.hotspotsSeen.add(String(result.node));this.host.querySelectorAll('[data-action="hotspot"]').forEach(item=>item.classList.toggle('active',item===button));const label=this.host.querySelector('[data-hotspot-status]');if(label)label.textContent=`${result.label} · ${result.clip||result.action}`;if(this.hotspotsSeen.size>=3)this.completeGoal('interact-three');}}if(action==='audio'){button.classList.toggle('active');this.audio.setEnabled(button.classList.contains('active'));}if(action==='play-animation'){const name=button.dataset.animation;if(this.renderer.playAnimation(name,{restart:true})){this.animationsSeen.add(name);this.host.querySelectorAll('[data-action="play-animation"]').forEach(item=>item.classList.toggle('active',item.dataset.animation===name));this.checkGoals();}}if(action==='pause-animation')this.renderer.pauseAnimation();if(action==='inspect-rig'){this.completeGoal('inspect-rig');this.host.querySelector('[data-panel="info"]')?.classList.add('open');}if(action==='cache-pack')await this.cachePack();if(action==='release-pack'){this.renderer.manager.releaseAll();this.context.toast('Cópias de CPU liberadas; o asset visível permanece na GPU até a troca ou saída.');}}
  async handleChange(event){if(event.target.matches('[data-control="lod"]')){this.showLoading(`Carregando LOD ${event.target.value}`);await this.renderer.setLod(event.target.value);this.lodsSeen.add(String(this.renderer.current?.selected?.level));this.checkGoals();this.hideLoading();}}
  handleKeyDown(event){if(['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName))return;if(event.code==='KeyC'){const modes=[0,1,2,3],index=modes.indexOf(this.renderer.mode),next=modes[(index+1)%modes.length];this.renderer.setMode(next);this.host.querySelectorAll('[data-action="mode"]').forEach(item=>item.classList.toggle('active',Number(item.dataset.mode)===next));this.modesSeen.add(next);this.checkGoals();}if(event.code==='KeyV'){const index=this.assets.findIndex(item=>item.id===this.activeId);this.selectAsset(this.assets[(index+1)%this.assets.length].id);}if(event.code==='KeyP')this.host.querySelector('.premium-assets-stage')?.classList.toggle('photo-mode');if(event.code==='KeyF')this.renderer.requestFullscreen();}
  async selectAsset(id){if(id===this.activeId)return;this.activeId=id;this.showLoading('Carregando geometria, materiais e HDR');this.host.querySelectorAll('[data-action="asset"]').forEach(item=>item.classList.toggle('active',item.dataset.id===id));const asset=this.assets.find(item=>item.id===id);this.host.querySelector('[data-asset-title]').textContent=asset.title;await this.renderer.loadAsset(id,this.host.querySelector('[data-control="lod"]')?.value||'auto');this.hideLoading();}
  assetLoaded(data){this.inspected.add(data.asset.id);this.lodsSeen.add(String(data.selected.level));this.host.querySelector('[data-info-title]')&&(this.host.querySelector('[data-info-title]').textContent=data.asset.title);this.host.querySelector('[data-info-description]')&&(this.host.querySelector('[data-info-description]').textContent=data.asset.description);const specs=this.host.querySelector('[data-info-specs]');if(specs)specs.innerHTML=`<span><b>LOD</b>${data.selected.level}</span><span><b>Triângulos</b>${(data.scene?.triangles||data.geometry.triangles).toLocaleString('pt-BR')}</span><span><b>Vértices</b>${(data.scene?.vertices||data.geometry.vertices).toLocaleString('pt-BR')}</span><span><b>Tamanho</b>${kb(data.selected.bytes)} KB</span><span><b>Metal</b>${Math.round(data.asset.metalness*100)}%</span><span><b>Rugosidade</b>${Math.round(data.asset.roughness*100)}%</span><span><b>Peças</b>${data.scene?.parts||1}</span><span><b>Animações</b>${data.scene?.animations?.length||0}</span><span><b>Interações</b>${data.scene?.interactions?.length||0}</span><span><b>Colliders</b>${data.scene?.colliders?.length||0}</span>`;const rail=this.host.querySelector('[data-animation-rail]');if(rail){const animations=data.scene?.animations||[];rail.innerHTML=`<b>RIG GLTF · ${data.scene?.parts||0} PEÇAS</b><div>${animations.map(item=>`<button data-action="play-animation" data-animation="${escapeHtml(item.name)}"><i>▶</i><span>${escapeHtml(item.name)}</span><small>${item.duration.toFixed(1)}s</small></button>`).join('')}<button data-action="pause-animation"><i>Ⅱ</i><span>Pausar</span></button><button data-action="inspect-rig"><i>⌗</i><span>${data.scene?.interactions?.length||0} pontos · ${data.scene?.colliders?.length||0} colliders</span></button></div>`;}const panel=this.host.querySelector('[data-hotspot-panel]'),hotspots=this.renderer.interactionList();if(panel)panel.innerHTML=`<header><b>INTERIORES HD · ${hotspots.length} HOTSPOTS</b><button data-action="audio" class="active" title="Áudio mecânico">◖))</button></header><div>${hotspots.map((item,index)=>`<button data-action="hotspot" data-index="${index}"><i>◎</i><span><b>${escapeHtml(item.label)}</b><small>${escapeHtml(item.description)}</small></span></button>`).join('')||'<span>Este LOD não possui hotspots publicados.</span>'}</div><small data-hotspot-status>${data.scene?.colliders?.length||0} colliders compostos protegendo a navegação</small>`;this.checkGoals();}
  updateDiagnostics(data){this.diagnostics=data;const stage=this.host?.querySelector('.premium-assets-stage');if(!stage)return;const map={triangles:Number(data.triangles||0).toLocaleString('pt-BR'),vertices:Number(data.vertices||0).toLocaleString('pt-BR'),lod:data.lod==='auto'?'AUTO':`LOD ${data.lod}`,load:data.loadMs?`${data.loadMs} ms`:'—',parts:data.parts??this.renderer?.current?.scene?.parts??'—',animations:data.animations??this.renderer?.current?.scene?.animations?.length??'—'};for(const [key,value] of Object.entries(map)){const el=stage.querySelector(`[data-diag="${key}"]`);if(el)el.textContent=value;}const status=stage.querySelector('[data-renderer-status]');if(status)status.textContent=data.renderer||data.state;}
  async cachePack(){const asset=this.renderer.manager.asset(this.activeId),environment=this.renderer.manager.environment(asset.environment);this.showLoading('Preparando pacote offline');try{await this.renderer.manager.cache.cacheAsset(asset,environment,progress=>{const label=this.host.querySelector('[data-loading-label]');if(label)label.textContent=`${progress.completed}/${progress.total} arquivos armazenados`;});this.completeGoal('offline-pack');this.context.toast(`${asset.title} disponível offline após a primeira instalação.`);}catch(error){this.context.toast(error.message||'Não foi possível armazenar o pacote.');}finally{this.hideLoading();}}
  checkGoals(){if(this.inspected.size>=4)this.completeGoal('inspect-four');if(this.lodsSeen.has('0')&&this.lodsSeen.has('1')&&this.lodsSeen.has('2'))this.completeGoal('compare-lod');if(this.modesSeen.size>=4)this.completeGoal('material-lab');if(this.animationsSeen.size>=3)this.completeGoal('animate-three');const label=this.host.querySelector('[data-progress-label]');if(label)label.textContent=`${this.goals.size}/${PREMIUM_INSPECTION_GOALS.length} objetivos gráficos`;}
  completeGoal(id){if(this.goals.has(id))return;this.goals.add(id);const goal=PREMIUM_INSPECTION_GOALS.find(item=>item.id===id);const dot=this.host?.querySelector(`[data-goal="${id}"]`);dot?.classList.add('done');if(goal&&this.context.profileStore.addXp(goal.xp,`premium-${goal.id}`))this.context.toast(`${goal.label}: +${goal.xp} XP`);const label=this.host?.querySelector('[data-progress-label]');if(label)label.textContent=`${this.goals.size}/${PREMIUM_INSPECTION_GOALS.length} objetivos gráficos`;this.checkCertification();}
  checkCertification(){if(this.goals.size<PREMIUM_INSPECTION_GOALS.length)return;if(this.context.profileStore.addXp(500,'premium-assets-certification'))this.context.toast('Certificação Pipeline Gráfico Premium: +500 XP');}
  showLoading(label){const overlay=this.host.querySelector('.premium-assets-loading');overlay?.classList.remove('hidden');const text=overlay?.querySelector('[data-loading-label]');if(text)text.textContent=label;}
  hideLoading(){this.host.querySelector('.premium-assets-loading')?.classList.add('hidden');}
  unmount(){this.input?.detach();this.renderer?.destroy();this.audio?.destroy();this.host?.removeEventListener('click',this.onClick);this.host?.removeEventListener('change',this.onChange);removeEventListener('keydown',this.onKeyDown);if(this.host)this.host.innerHTML='';}
}
export const createModule=()=>new PremiumAssetsModule();
