'use strict';
(function(){
  window.LABDS_LABS=window.LABDS_LABS||{};
  const KEY='lab.electronics.state';
  const DEFAULT={tab:'circuit',voltage:5,resistance:220,polarity:true,motor:40,xp:0,history:[]};
  let root,ctx,state,raf=0;
  async function save(){await ctx.storage.set(KEY,state);}
  function setTab(tab){state.tab=tab;root.querySelectorAll('[data-el-tab]').forEach(b=>b.classList.toggle('active',b.dataset.elTab===tab));root.querySelectorAll('[data-el-panel]').forEach(p=>p.classList.toggle('hidden',p.dataset.elPanel!==tab));save();if(tab==='circuit')drawCircuit();if(tab==='motor')drawMotor();else cancelAnimationFrame(raf);}
  function calculateCircuit(){const current=state.voltage/state.resistance,power=state.voltage*current,ledOk=state.polarity&&current>0.002&&current<0.03;root.querySelector('#currentValue').textContent=`${(current*1000).toFixed(2)} mA`;root.querySelector('#powerValue').textContent=`${power.toFixed(3)} W`;root.querySelector('#ledStatus').textContent=ledOk?'ACESO':!state.polarity?'POLARIDADE INVERTIDA':current>=0.03?'CORRENTE ALTA':'CORRENTE BAIXA';root.querySelector('#ledStatus').className=ledOk?'ok':'bad';drawCircuit();save();}
  function drawCircuit(){cancelAnimationFrame(raf);const canvas=root.querySelector('#circuitCanvas');if(!canvas)return;const c=canvas.getContext('2d');const loop=t=>{const rect=canvas.getBoundingClientRect(),ratio=Math.min(2,devicePixelRatio||1);if(canvas.width!==Math.round(rect.width*ratio)||canvas.height!==Math.round(rect.height*ratio)){canvas.width=Math.round(rect.width*ratio);canvas.height=Math.round(rect.height*ratio);c.setTransform(ratio,0,0,ratio,0,0);}const w=rect.width,h=rect.height;c.clearRect(0,0,w,h);c.fillStyle='#050c15';c.fillRect(0,0,w,h);c.strokeStyle='#426a7d';c.lineWidth=5;c.beginPath();c.moveTo(w*.16,h*.5);c.lineTo(w*.3,h*.5);c.lineTo(w*.42,h*.5);c.lineTo(w*.58,h*.5);c.lineTo(w*.72,h*.5);c.lineTo(w*.84,h*.5);c.lineTo(w*.84,h*.78);c.lineTo(w*.16,h*.78);c.closePath();c.stroke();c.strokeStyle='#ffca67';c.lineWidth=4;c.beginPath();for(let i=0;i<7;i++){const x=w*.3+i*w*.12/6,y=h*.5+(i%2?12:-12);i?c.lineTo(x,y):c.moveTo(x,y);}c.stroke();c.fillStyle='#d8f6ff';c.font='700 14px system-ui';c.fillText(`${state.resistance} Ω`,w*.31,h*.42);c.strokeStyle='#eaf8ff';c.lineWidth=4;c.beginPath();c.moveTo(w*.16,h*.42);c.lineTo(w*.16,h*.62);c.moveTo(w*.13,h*.46);c.lineTo(w*.13,h*.58);c.stroke();c.fillText(`${state.voltage} V`,w*.08,h*.36);const current=state.voltage/state.resistance,ledOk=state.polarity&&current>.002&&current<.03;c.beginPath();c.arc(w*.65,h*.5,25,0,Math.PI*2);c.fillStyle=ledOk?'#5df1ad':'#3b4850';c.shadowBlur=ledOk?24:0;c.shadowColor='#5df1ad';c.fill();c.shadowBlur=0;c.strokeStyle='#8dd9ff';c.stroke();if(ledOk){for(let i=0;i<14;i++){const p=(t/900+i/14)%1,x=w*.16+p*w*.68;c.beginPath();c.arc(x,p<.78?h*.78:h*.5,2.8,0,Math.PI*2);c.fillStyle='#67eaff';c.fill();}}c.fillStyle='#c8e7f4';c.fillText(state.polarity?'corrente convencional →':'polaridade invertida',w*.42,h*.9);raf=requestAnimationFrame(loop);};raf=requestAnimationFrame(loop);}
  function tokenizeExpression(source){
    const text=String(source||'').replace(/,/g,'.').trim();
    if(text.length>180)throw new Error('expressão muito longa');
    const tokens=[];let index=0;
    while(index<text.length){
      const rest=text.slice(index),space=/^\s+/.exec(rest);if(space){index+=space[0].length;continue;}
      const number=/^(?:\d+(?:\.\d*)?|\.\d+)/.exec(rest);if(number){tokens.push({type:'number',value:Number(number[0])});index+=number[0].length;continue;}
      const name=/^[a-z]+/i.exec(rest);if(name){tokens.push({type:'name',value:name[0].toLowerCase()});index+=name[0].length;continue;}
      const char=text[index];if('+-*/%^()'.includes(char)){tokens.push({type:char,value:char});index++;continue;}
      throw new Error(`caractere inválido na posição ${index+1}`);
    }
    tokens.push({type:'eof'});return tokens;
  }
  function calculateSafe(source){
    const tokens=tokenizeExpression(source),functions={sqrt:Math.sqrt,sin:Math.sin,cos:Math.cos,tan:Math.tan,log:Math.log10,ln:Math.log,exp:Math.exp,abs:Math.abs},constants={pi:Math.PI,e:Math.E};let position=0;
    const peek=()=>tokens[position],take=type=>{if(peek().type!==type)throw new Error(`esperado ${type}`);return tokens[position++];};
    function primary(){const token=peek();if(token.type==='number'){position++;return token.value;}if(token.type==='name'){position++;if(Object.hasOwn(constants,token.value))return constants[token.value];const fn=functions[token.value];if(!fn)throw new Error(`função desconhecida: ${token.value}`);take('(');const value=expression();take(')');return fn(value);}if(token.type==='('){position++;const value=expression();take(')');return value;}throw new Error('número, constante ou parêntese esperado');}
    function unary(){if(peek().type==='+'){position++;return unary();}if(peek().type==='-'){position++;return -unary();}return primary();}
    function power(){let left=unary();if(peek().type==='^'){position++;left=Math.pow(left,power());}return left;}
    function product(){let left=power();while(['*','/','%'].includes(peek().type)){const op=tokens[position++].type,right=power();if((op==='/'||op==='%')&&right===0)throw new Error('divisão por zero');left=op==='*'?left*right:op==='/'?left/right:left%right;}return left;}
    function expression(){let left=product();while(['+','-'].includes(peek().type)){const op=tokens[position++].type,right=product();left=op==='+'?left+right:left-right;}return left;}
    const value=expression();if(peek().type!=='eof')throw new Error('há elementos após o fim da expressão');if(!Number.isFinite(value))throw new Error('resultado inválido');return value;
  }
  function evalExpression(){const input=root.querySelector('#calcInput').value.trim(),out=root.querySelector('#calcOutput');try{const value=calculateSafe(input),shown=Math.abs(value)>=1e12||Math.abs(value)<1e-8&&value!==0?value.toExponential(8):Number(value.toPrecision(12));out.textContent=String(shown);state.history.unshift(`${input} = ${shown}`);state.history=state.history.slice(0,12);state.xp+=4;root.querySelector('#elXp').textContent=state.xp;renderHistory();save();}catch(error){out.textContent=`Não foi possível calcular: ${error.message}.`;}}
  function renderHistory(){const box=root.querySelector('#calcHistory');if(box)box.textContent=state.history.join('\n')||'Sem cálculos.';}
  function drawMotor(){cancelAnimationFrame(raf);const canvas=root.querySelector('#motorCanvas');if(!canvas)return;const c=canvas.getContext('2d');const loop=t=>{const rect=canvas.getBoundingClientRect(),ratio=Math.min(2,devicePixelRatio||1);if(canvas.width!==Math.round(rect.width*ratio)||canvas.height!==Math.round(rect.height*ratio)){canvas.width=Math.round(rect.width*ratio);canvas.height=Math.round(rect.height*ratio);c.setTransform(ratio,0,0,ratio,0,0);}const w=rect.width,h=rect.height;c.fillStyle='#050b13';c.fillRect(0,0,w,h);const cx=w/2,cy=h/2,r=Math.min(w,h)*.22,angle=t*.001*state.motor/35;c.save();c.translate(cx,cy);c.rotate(angle);for(let i=0;i<6;i++){c.rotate(Math.PI/3);c.fillStyle=i%2?'#58eebb':'#62dfff';c.fillRect(0,-10,r,20);}c.restore();c.beginPath();c.arc(cx,cy,32,0,Math.PI*2);c.fillStyle='#142b3e';c.fill();c.strokeStyle='#8aeaff';c.lineWidth=4;c.stroke();c.fillStyle='#e9f8ff';c.font='700 16px system-ui';c.fillText(`PWM ${state.motor}%`,16,26);c.fillStyle='#a9cadb';c.font='14px system-ui';c.fillText(`Velocidade simulada: ${Math.round(state.motor*32)} rpm`,16,50);raf=requestAnimationFrame(loop);};raf=requestAnimationFrame(loop);}
  function render(){root.innerHTML=`<div class="immersive-lab electronics-lab"><header class="immersive-hero"><div><span class="eyebrow">ELETRÔNICA • ENERGIA • CÁLCULO</span><h2>Do número ao circuito</h2><p>Calcule, monte um circuito com LED, observe polaridade, corrente, potência e controle de motor por PWM.</p></div><div class="immersive-badges"><span>XP <b id="elXp">${state.xp}</b></span><span>Lei de Ohm</span><span>Canvas</span></div></header><nav class="module-tabs"><button data-el-tab="circuit">Circuito LED</button><button data-el-tab="calculator">Calculadora</button><button data-el-tab="motor">Motor e PWM</button></nav>
    <section data-el-panel="circuit" class="immersive-grid"><article class="immersive-card"><h3>Fonte, resistor e LED</h3><label>Tensão<input id="voltageRange" type="range" min="1" max="12" step="0.5" value="${state.voltage}"><b id="voltageValue">${state.voltage} V</b></label><label>Resistência<input id="resistanceRange" type="range" min="47" max="2200" step="1" value="${state.resistance}"><b id="resistanceValue">${state.resistance} Ω</b></label><label class="settings-check"><input id="polarityCheck" type="checkbox" ${state.polarity?'checked':''}> LED na polaridade correta</label><div class="metric-row"><div class="metric-card"><small>Corrente</small><strong id="currentValue"></strong></div><div class="metric-card"><small>Potência</small><strong id="powerValue"></strong></div><div class="metric-card"><small>LED</small><strong id="ledStatus"></strong></div></div><div class="knowledge-card"><strong>Lei de Ohm:</strong> I = V / R. Um resistor limita a corrente e ajuda a proteger o LED.</div></article><article class="immersive-card"><div class="visual-stage"><canvas id="circuitCanvas" aria-label="Circuito elétrico simulado"></canvas></div></article></section>
    <section data-el-panel="calculator" class="immersive-grid hidden"><article class="immersive-card calculator-shell"><h3>Calculadora científica</h3><input id="calcInput" value="sqrt(144) + 2^5" autocomplete="off" spellcheck="false"><div class="calculator-keys">${['7','8','9','/','sqrt(','4','5','6','*','^','1','2','3','-','pi','0','.','(',')','+'].map(k=>`<button data-key="${k}">${k}</button>`).join('')}</div><button id="calcRun" class="btn primary">Calcular</button><output id="calcOutput">—</output></article><article class="immersive-card"><h3>Histórico</h3><pre id="calcHistory" class="terminal-mini"></pre><div class="knowledge-card"><strong>Boas práticas:</strong> use parênteses para deixar a prioridade explícita e verifique unidades antes de interpretar resultados.</div></article></section>
    <section data-el-panel="motor" class="immersive-grid hidden"><article class="immersive-card"><h3>Controle por PWM</h3><label>Ciclo ativo<input id="motorRange" type="range" min="0" max="100" value="${state.motor}"><b id="motorValue">${state.motor}%</b></label><p>O PWM liga e desliga a alimentação rapidamente. O ciclo ativo altera a energia média entregue ao motor.</p><div class="flow-track"><div class="flow-node">Código</div><span class="flow-arrow">›</span><div class="flow-node">PWM</div><span class="flow-arrow">›</span><div class="flow-node">Driver</div><span class="flow-arrow">›</span><div class="flow-node">Motor</div></div></article><article class="immersive-card"><div class="visual-stage"><canvas id="motorCanvas" aria-label="Motor controlado por PWM"></canvas></div></article></section></div>`;
    root.querySelectorAll('[data-el-tab]').forEach(b=>b.addEventListener('click',()=>setTab(b.dataset.elTab)));root.querySelector('#voltageRange').addEventListener('input',e=>{state.voltage=Number(e.target.value);root.querySelector('#voltageValue').textContent=`${state.voltage} V`;calculateCircuit();});root.querySelector('#resistanceRange').addEventListener('input',e=>{state.resistance=Number(e.target.value);root.querySelector('#resistanceValue').textContent=`${state.resistance} Ω`;calculateCircuit();});root.querySelector('#polarityCheck').addEventListener('change',e=>{state.polarity=e.target.checked;calculateCircuit();});root.querySelectorAll('[data-key]').forEach(b=>b.addEventListener('click',()=>{root.querySelector('#calcInput').value+=b.dataset.key;}));root.querySelector('#calcRun').addEventListener('click',evalExpression);root.querySelector('#calcInput').addEventListener('keydown',e=>{if(e.key==='Enter')evalExpression();});root.querySelector('#motorRange').addEventListener('input',e=>{state.motor=Number(e.target.value);root.querySelector('#motorValue').textContent=`${state.motor}%`;save();});calculateCircuit();renderHistory();setTab(state.tab);
  }
  async function mount(host,context){root=host;ctx=context;state={...DEFAULT,...await ctx.storage.get(KEY,DEFAULT)};render();}
  async function unmount(){cancelAnimationFrame(raf);await save();root=null;ctx=null;state=null;}
  function exportPayload(){return{text:`ELETRÔNICA\nTensão: ${state.voltage} V\nResistência: ${state.resistance} Ω\nXP: ${state.xp}`,native:JSON.stringify(state,null,2),backup:state,meta:[{label:'XP',value:String(state.xp)},{label:'Cálculos',value:String(state.history.length)}]};}
  function help(){return'<h3>Eletrônica e calculadoras</h3><p>O circuito e o motor são simulações educacionais. Não conecte componentes reais sem orientação e dimensionamento adequados.</p>';}
  window.LABDS_LABS['electronics-lab']={mount,unmount,exportPayload,help};
})();
