import * as THREE from '../voxelcraft-ds/vendor/three/three.module.min.js';
const THEMES={north:{base:0x315f88,accent:0x79d7ff},east:{base:0x376f54,accent:0x82ffba},south:{base:0x81583b,accent:0xffbd7a},west:{base:0x5d4a88,accent:0xc2a7ff},village:{base:0x365c68,accent:0x73e6dc},workshop:{base:0x76533a,accent:0xffb56b},data:{base:0x315f85,accent:0x72d7ff},civic:{base:0x554977,accent:0xa28cff},forest:{base:0x31563c,accent:0x75e69b},bridge:{base:0x5b4937,accent:0xd8b77c},energy:{base:0x294b3b,accent:0x86ffae},industrial:{base:0x50565a,accent:0xffb45e},conveyor:{base:0x3c4246,accent:0xffd16f},crane:{base:0x6c5b35,accent:0xffc94f},control:{base:0x354b61,accent:0x70c7ff},tower:{base:0x33465d,accent:0x8bd8ff},sky:{base:0x425d7d,accent:0xa8e7ff},core:{base:0x51426b,accent:0xd7a7ff}};
const colorValue=(v,fallback)=>typeof v==='string'?Number(v):Number.isFinite(v)?v:fallback;
export class Mundo360Renderer{
  constructor(canvas,region,{quality='medio',reduced=false}={}){this.canvas=canvas;this.region=region;this.quality=quality;this.reduced=reduced;this.scene=new THREE.Scene();this.camera=new THREE.PerspectiveCamera(62,1,.1,180);this.renderer=new THREE.WebGLRenderer({canvas,antialias:quality!=='baixo',powerPreference:'high-performance'});this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.shadowMap.enabled=quality==='alto'||quality==='ultra';this.renderer.setPixelRatio(Math.min(devicePixelRatio,quality==='ultra'?1.6:quality==='alto'?1.35:quality==='medio'?1.1:1));this.root=new THREE.Group();this.scene.add(this.root);this.yaw=Math.PI;this.pitch=.38;this.distance=7.5;this.panorama=false;this.clock=0;this.#lights();this.#player();this.setRegion(region);this.resize();}
  #lights(){this.scene.add(new THREE.HemisphereLight(0xbde8ff,0x203018,1.8));this.sun=new THREE.DirectionalLight(0xffffff,2.2);this.sun.position.set(22,36,14);this.sun.castShadow=this.renderer.shadowMap.enabled;this.sun.shadow.mapSize.set(this.quality==='ultra'?2048:1024,this.quality==='ultra'?2048:1024);this.scene.add(this.sun);}
  material(color,emissive=0){return new THREE.MeshStandardMaterial({color,roughness:.62,metalness:.08,emissive,emissiveIntensity:emissive?.35:0});}
  box(size,pos,color,emissive=0){const m=new THREE.Mesh(new THREE.BoxGeometry(...size),this.material(color,emissive));m.position.set(...pos);m.receiveShadow=true;m.castShadow=this.renderer.shadowMap.enabled;this.root.add(m);return m;}
  #disposeRoot(){this.root.traverse(o=>{if(o.geometry)o.geometry.dispose?.();if(o.material){const mats=Array.isArray(o.material)?o.material:[o.material];for(const m of mats)m.dispose?.();}});this.root.clear();}
  setRegion(region){this.#disposeRoot();this.region=region;this.platformMeshes=new Map();this.enemyMeshes=new Map();this.collectibleMeshes=new Map();this.beaconMeshes=new Map();this.checkpointMeshes=new Map();this.npcMeshes=new Map();this.interactionMeshes=new Map();this.weatherPoints=null;this.portal=null;const bg=colorValue(region.visual?.background,region.kind==='village'?0x091827:region.kind==='forest'?0x071710:region.kind==='industrial'?0x0b1118:region.kind==='tower'?0x07101d:0x081426),fog=colorValue(region.visual?.fog,region.kind==='village'?0x11283a:region.kind==='forest'?0x102a1d:region.kind==='industrial'?0x18222c:region.kind==='tower'?0x152640:0x0c1c30);this.scene.background=new THREE.Color(bg);this.scene.fog=new THREE.FogExp2(fog,this.quality==='baixo'?.012:.008);this.#build();}
  #build(){this.box(this.region.size,[0,-.5,0],colorValue(this.region.visual?.ground,this.region.kind==='village'?0x243c43:0x243b37));if(this.region.kind==='village')this.#villageGround();else if(this.region.kind==='forest')this.#forestGround();else if(this.region.kind==='industrial')this.#industrialGround();else if(this.region.kind==='tower')this.#towerGround();else{const hub=new THREE.Mesh(new THREE.CylinderGeometry(9.5,10.5,.35,24),this.material(0x263f59,0x0d263a));hub.position.y=.15;hub.receiveShadow=true;this.root.add(hub);}for(const p of this.region.platforms||[]){const t=THEMES[p.theme]||THEMES.north;this.platformMeshes.set(p.id,this.box(p.size,p.position,t.base));}for(const p of this.region.movingPlatforms||[]){const t=THEMES[p.theme]||THEMES.north;this.platformMeshes.set(p.id,this.box(p.size,p.position,t.accent,t.accent));}for(const o of this.region.obstacles||[])this.box(o.size,o.position,this.region.kind==='village'?0x36505d:0x2a4057,0x101d2c);for(const h of this.region.hazards||[]){const mesh=this.box(h.size,h.position,0x7c244f,0x8c1f60);mesh.material.transparent=true;mesh.material.opacity=.8;mesh.userData.hazard=true;}
    for(const c of this.region.collectibles||[]){const m=new THREE.Mesh(new THREE.IcosahedronGeometry(.42,1),new THREE.MeshStandardMaterial({color:this.region.kind==='village'?0x6fe3ff:0x7eeaff,emissive:0x38c9ff,emissiveIntensity:1.25,metalness:.35,roughness:.15}));m.position.set(...c.position);m.castShadow=true;this.root.add(m);this.collectibleMeshes.set(c.id,m);}for(const b of this.region.beacons||[]){const g=new THREE.Group();const base=new THREE.Mesh(new THREE.CylinderGeometry(.55,.75,.28,8),this.material(0x344b62));const stem=new THREE.Mesh(new THREE.CylinderGeometry(.12,.16,1.25,8),this.material(0x58a7c8));stem.position.y=.72;const top=new THREE.Mesh(new THREE.OctahedronGeometry(.35,0),new THREE.MeshStandardMaterial({color:0xffef87,emissive:0xffc638,emissiveIntensity:1.1}));top.position.y=1.45;g.add(base,stem,top);g.position.set(b.position[0],b.position[1]-.08,b.position[2]);this.root.add(g);this.beaconMeshes.set(b.id,g);}for(const cp of this.region.checkpoints||[]){const m=new THREE.Mesh(new THREE.CylinderGeometry(.65,.82,.18,10),new THREE.MeshStandardMaterial({color:0x73ffae,emissive:0x24a862,emissiveIntensity:.65}));m.position.set(...cp.position);this.root.add(m);this.checkpointMeshes.set(cp.id,m);}for(const e of this.region.enemies||[]){const g=new THREE.Group();const color=e.type==='glitch'?0xb274ff:e.type==='sentinel'?0xff7b6b:0xff4d8e;const core=new THREE.Mesh(new THREE.OctahedronGeometry(.48,0),new THREE.MeshStandardMaterial({color,emissive:color,emissiveIntensity:.5,roughness:.28,metalness:.3}));g.add(core);const ring=new THREE.Mesh(new THREE.TorusGeometry(.68,.08,6,16),this.material(0xd8ecff));ring.rotation.x=Math.PI/2;g.add(ring);g.position.set(...e.position);this.root.add(g);this.enemyMeshes.set(e.id,g);}if(this.region.kind==='village')this.#villageEntities();if(this.region.kind==='forest')this.#forestEntities();if(this.region.kind==='industrial')this.#industrialEntities();if(this.region.kind==='tower')this.#towerEntities();this.#portal();this.#decor();if(this.region.kind==='forest')this.#weather();}
  #portal(){const pg=new THREE.Group();const ring=new THREE.Mesh(new THREE.TorusGeometry(1.05,.15,8,30),new THREE.MeshStandardMaterial({color:0x5ee8ff,emissive:0x3ad6ff,emissiveIntensity:1.4}));ring.rotation.y=Math.PI/2;pg.add(ring);const inner=new THREE.Mesh(new THREE.CircleGeometry(.82,24),new THREE.MeshBasicMaterial({color:0x4bb6ff,transparent:true,opacity:.18,side:THREE.DoubleSide}));inner.rotation.y=Math.PI/2;pg.add(inner);pg.position.set(...this.region.portal.position);this.root.add(pg);this.portal=pg;}

  #industrialGround(){
    const dock=new THREE.Mesh(new THREE.CylinderGeometry(15,16,.2,20),this.material(0x343a3d,0x171b1e));dock.position.set(0,.09,30);dock.receiveShadow=true;this.root.add(dock);
    for(const lane of [{p:[0,.025,16],s:[8,.08,30]},{p:[22,.025,4],s:[38,.08,6]},{p:[0,.025,-13],s:[7,.08,30]}]){const m=this.box(lane.s,lane.p,0x2a2e31);m.material.roughness=.9;}
    for(const belt of this.region.conveyors||[]){const mesh=this.box(belt.size,belt.position,0x30363a,0x5b4318);mesh.material.emissiveIntensity=.18;const count=Math.max(2,Math.floor((belt.size[0]+belt.size[2])/4));for(let i=0;i<count;i++){const dir=belt.direction||[1,0],alongX=Math.abs(dir[0])>=Math.abs(dir[1]);const t=(i-(count-1)/2)*2.5;const arrow=new THREE.Mesh(new THREE.ConeGeometry(.18,.48,3),new THREE.MeshBasicMaterial({color:0xffcf6a}));arrow.rotation.x=Math.PI/2;arrow.rotation.z=alongX?(dir[0]>0?-Math.PI/2:Math.PI/2):(dir[1]>0?Math.PI:0);arrow.position.set(belt.position[0]+(alongX?t:0),belt.position[1]+.14,belt.position[2]+(alongX?0:t));this.root.add(arrow);}}
    for(const m of this.region.movingPlatforms||[]){if(m.theme!=='crane')continue;const post=this.box([.3,6,.3],[m.position[0],3,m.position[2]],0x6c5b35);post.material.roughness=.55;}
  }
  #industrialEntities(){
    for(const item of this.region.interactables||[]){const type=item.type;const t=type==='industrial-power'?THEMES.energy:type==='cargo-console'?THEMES.conveyor:THEMES.control;const g=new THREE.Group();const base=new THREE.Mesh(new THREE.CylinderGeometry(.48,.62,.26,8),this.material(t.base));const core=new THREE.Mesh(new THREE.BoxGeometry(.5,.72,.5),new THREE.MeshStandardMaterial({color:t.accent,emissive:t.accent,emissiveIntensity:.55,roughness:.28,metalness:.25}));core.position.y=.5;g.add(base,core);if(type==='control-console'){const ring=new THREE.Mesh(new THREE.TorusGeometry(.5,.08,6,18),new THREE.MeshStandardMaterial({color:0x9fdcff,emissive:0x70c7ff,emissiveIntensity:1.0}));ring.rotation.x=Math.PI/2;ring.position.y=.5;g.add(ring);}g.position.set(...item.position);this.root.add(g);this.interactionMeshes.set(item.id,g);}
  }
  #towerGround(){
    const base=new THREE.Mesh(new THREE.CylinderGeometry(16,18,.28,28),this.material(0x263446,0x10243a));base.position.set(0,.12,24);base.receiveShadow=true;this.root.add(base);
    for(const y of [4.5,9.5,15,20.5,25.5]){const ring=new THREE.Mesh(new THREE.TorusGeometry(11.5-(y/25)*2.2,.12,8,42),new THREE.MeshStandardMaterial({color:0x7299c4,emissive:0x335f8b,emissiveIntensity:.35,transparent:true,opacity:.5}));ring.rotation.x=Math.PI/2;ring.position.set(0,y,0);this.root.add(ring);}
    for(const x of [-7,7])for(const z of [-5,5]){const column=new THREE.Mesh(new THREE.CylinderGeometry(.22,.28,26,8),this.material(0x43566d));column.position.set(x,13,z);column.material.transparent=true;column.material.opacity=.62;this.root.add(column);}
    if(this.quality!=='baixo'){const beacon=new THREE.PointLight(0x9ddcff,this.quality==='ultra'?4:2.6,30,2);beacon.position.set(0,24,0);this.root.add(beacon);const crown=new THREE.PointLight(0xd7a7ff,this.quality==='ultra'?4:2.4,22,2);crown.position.set(0,28,0);this.root.add(crown);}
  }
  #towerEntities(){
    for(const item of this.region.interactables||[]){const isCore=item.type==='tower-core',t=isCore?THEMES.core:THEMES.tower,g=new THREE.Group();const base=new THREE.Mesh(new THREE.CylinderGeometry(isCore?.7:.48,isCore?.9:.62,isCore?.34:.26,10),this.material(t.base));const core=new THREE.Mesh(isCore?new THREE.IcosahedronGeometry(.55,1):new THREE.BoxGeometry(.5,.72,.5),new THREE.MeshStandardMaterial({color:t.accent,emissive:t.accent,emissiveIntensity:.65,roughness:.22,metalness:.3}));core.position.y=isCore?.72:.5;g.add(base,core);const ring=new THREE.Mesh(new THREE.TorusGeometry(isCore?.75:.46,.07,7,22),new THREE.MeshStandardMaterial({color:t.accent,emissive:t.accent,emissiveIntensity:1}));ring.rotation.x=Math.PI/2;ring.position.y=isCore?.72:.5;g.add(ring);g.position.set(...item.position);this.root.add(g);this.interactionMeshes.set(item.id,g);}
  }
  #forestGround(){
    const clearing=new THREE.Mesh(new THREE.CylinderGeometry(11,12,.18,24),this.material(0x284936,0x0d2a1a));clearing.position.set(0,.08,31);clearing.receiveShadow=true;this.root.add(clearing);
    const trails=[{p:[-13,.03,15],s:[6,.08,30],r:-.55},{p:[13,.03,15],s:[6,.08,30],r:.55},{p:[0,.03,-12],s:[5,.08,34],r:0}];
    for(const t of trails){const m=this.box(t.s,t.p,0x314636);m.rotation.y=t.r;m.material.roughness=.9;}
    for(const b of this.region.platforms||[]){if(b.theme!=='bridge')continue;const railColor=0xa99065;for(const sx of [-1,1]){const rail=this.box([.12,.65,b.size[2]],[b.position[0]+sx*(b.size[0]/2-.18),b.position[1]+b.size[1]/2+.3,b.position[2]],railColor);rail.material.roughness=.75;}}
  }
  #forestEntities(){
    for(const item of this.region.interactables||[]){if(item.type!=='energy-node')continue;const g=new THREE.Group();const base=new THREE.Mesh(new THREE.CylinderGeometry(.55,.72,.32,8),this.material(0x294b3b));const ring=new THREE.Mesh(new THREE.TorusGeometry(.46,.09,7,20),new THREE.MeshStandardMaterial({color:0x86ffae,emissive:0x4cff86,emissiveIntensity:.75,roughness:.25}));ring.rotation.x=Math.PI/2;ring.position.y=.55;const core=new THREE.Mesh(new THREE.OctahedronGeometry(.28,0),new THREE.MeshStandardMaterial({color:0xcaffd7,emissive:0x55ff91,emissiveIntensity:1.0}));core.position.y=.55;g.add(base,ring,core);g.position.set(...item.position);this.root.add(g);this.interactionMeshes.set(item.id,g);}
  }
  #weather(){
    if(this.reduced)return;const count=this.quality==='baixo'?24:this.quality==='medio'?52:this.quality==='alto'?88:128;const pos=new Float32Array(count*3);for(let i=0;i<count;i++){pos[i*3]=((i*37)%89)-44;pos[i*3+1]=1+((i*17)%15);pos[i*3+2]=((i*53)%84)-42;}const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.BufferAttribute(pos,3));const mat=new THREE.PointsMaterial({color:0x8dffc1,size:this.quality==='ultra'?.11:.08,transparent:true,opacity:.52,depthWrite:false});this.weatherPoints=new THREE.Points(geo,mat);this.root.add(this.weatherPoints);
  }
  #villageGround(){const plaza=new THREE.Mesh(new THREE.CylinderGeometry(12,12,.18,24),this.material(0x315361,0x102e38));plaza.position.set(0,.08,15);plaza.receiveShadow=true;this.root.add(plaza);for(const road of [{p:[0,.02,2],s:[6,.08,34]},{p:[0,.02,15],s:[56,.08,5]},{p:[0,.02,-15],s:[6,.08,22]}]){const m=this.box(road.s,road.p,0x253a45);m.material.roughness=.82;}for(const b of this.region.buildings||[]){const t=THEMES[b.theme]||THEMES.village;const floor=this.box([b.size[0]-1,.16,b.size[2]-1],[b.position[0],.08,b.position[2]],t.base);floor.material.roughness=.72;const frame=new THREE.LineSegments(new THREE.EdgesGeometry(new THREE.BoxGeometry(...b.size)),new THREE.LineBasicMaterial({color:t.accent,transparent:true,opacity:.32}));frame.position.set(...b.position);this.root.add(frame);if(this.quality!=='baixo'){const lamp=new THREE.PointLight(t.accent,this.quality==='ultra'?3.0:2.0,15,2);lamp.position.set(b.position[0],3.7,b.position[2]);this.root.add(lamp);}const sign=this.box([2.6,.45,.18],[b.door.position[0],2.4,b.door.position[2]],t.accent,t.accent);sign.material.emissiveIntensity=.75;}}
  #villageEntities(){for(const npc of this.region.npcs||[]){const color=colorValue(npc.color,0x8fe8ff),g=new THREE.Group();const body=new THREE.Mesh(new THREE.CylinderGeometry(.32,.42,.9,8),new THREE.MeshStandardMaterial({color,roughness:.55,metalness:.05}));body.position.y=.62;const head=new THREE.Mesh(new THREE.SphereGeometry(.27,12,8),this.material(0xf2dfca));head.position.y=1.28;const marker=new THREE.Mesh(new THREE.OctahedronGeometry(.13,0),new THREE.MeshStandardMaterial({color,emissive:color,emissiveIntensity:1.2}));marker.position.y=1.85;g.add(body,head,marker);g.position.set(...npc.position);this.root.add(g);this.npcMeshes.set(npc.id,g);}for(const item of this.region.interactables||[]){const t=item.type==='repair'?THEMES.workshop:item.type==='relay'?THEMES.civic:item.type==='core'?{base:0x3b4166,accent:0xffe078}:THEMES.data;const g=new THREE.Group();const base=new THREE.Mesh(new THREE.CylinderGeometry(.42,.55,.25,8),this.material(t.base));const core=new THREE.Mesh(new THREE.BoxGeometry(.42,.62,.42),new THREE.MeshStandardMaterial({color:t.accent,emissive:t.accent,emissiveIntensity:.5,roughness:.25}));core.position.y=.42;g.add(base,core);g.position.set(...item.position);this.root.add(g);this.interactionMeshes.set(item.id,g);}}
  #decor(){const density=this.quality==='baixo'?18:this.quality==='medio'?34:this.quality==='alto'?52:68;if(this.region.kind==='village'){for(let i=0;i<Math.floor(density*.65);i++){const x=-36+(i*13%72),z=-32+(i*19%62);if(Math.abs(x)<12&&z>4)continue;const post=this.box([.14,1.8,.14],[x,.9,z],0x4d7180);const light=new THREE.Mesh(new THREE.SphereGeometry(.13,8,6),new THREE.MeshStandardMaterial({color:0x9fffee,emissive:0x67f6df,emissiveIntensity:.9}));light.position.set(x,1.8,z);this.root.add(light);}}else if(this.region.kind==='industrial'){for(let i=0;i<Math.floor(density*1.2);i++){const x=-43+((i*19)%86),z=-36+((i*23)%72);if(Math.abs(x)<10&&z>-6)continue;const h=1.2+(i%4)*.45;const stack=this.box([1.2+(i%3)*.4,h,1.1],[x,h/2,z],i%3===0?0x665743:0x41484d);stack.material.roughness=.8;if(i%5===0){const lamp=new THREE.Mesh(new THREE.SphereGeometry(.09,7,5),new THREE.MeshStandardMaterial({color:0xffc66d,emissive:0xff9d2e,emissiveIntensity:1.1}));lamp.position.set(x,h+.2,z);this.root.add(lamp);}}}else if(this.region.kind==='tower'){for(let i=0;i<Math.floor(density*.8);i++){const a=(i/Math.max(1,Math.floor(density*.8)))*Math.PI*2,r=18+(i%4)*2.4,x=Math.cos(a)*r,z=Math.sin(a)*r+4;const mast=this.box([.15,1.6+(i%3)*.5,.15],[x,.8+(i%3)*.25,z],0x526c89);const light=new THREE.Mesh(new THREE.SphereGeometry(.1,7,5),new THREE.MeshStandardMaterial({color:0xa8e7ff,emissive:0x6bcaff,emissiveIntensity:1.1}));light.position.set(x,1.7+(i%3)*.5,z);this.root.add(light);}}else if(this.region.kind==='forest'){for(let i=0;i<density*2;i++){const x=-43+((i*17)%86),z=-40+((i*29)%80);if(Math.abs(x)<7&&z>20)continue;if(Math.abs(x)<9&&z<2)continue;const group=new THREE.Group();const h=1.5+(i%5)*.35;const trunk=new THREE.Mesh(new THREE.CylinderGeometry(.16,.28,h,5),this.material(0x4b392b));trunk.position.y=h/2;const crown=new THREE.Mesh(new THREE.ConeGeometry(.75+(i%4)*.12,1.7+(i%3)*.35,5),this.material(i%6===0?0x366e66:0x2f6a43));crown.position.y=h+1.0;group.add(trunk,crown);group.position.set(x,0,z);group.rotation.y=i*.71;this.root.add(group);}}else for(let i=0;i<density;i++){const a=(i/density)*Math.PI*2+(i%5)*.13,r=13+(i%9)*2.35,x=Math.cos(a)*r,z=Math.sin(a)*r;if(Math.abs(x)>34||Math.abs(z)>34)continue;const group=new THREE.Group();const trunk=new THREE.Mesh(new THREE.CylinderGeometry(.13,.2,.9,5),this.material(0x594738));trunk.position.y=.45;const crown=new THREE.Mesh(new THREE.ConeGeometry(.55+((i*7)%5)*.08,1.5,5),this.material(i%4===0?0x4e6b96:0x3f7659));crown.position.y=1.35;group.add(trunk,crown);group.position.set(x,0,z);group.rotation.y=a;this.root.add(group);}if(this.quality!=='baixo'){const grid=new THREE.GridHelper(this.region.size[0],Math.round(this.region.size[0]/2),0x4c7594,0x2d4a5b);grid.position.y=.012;grid.material.transparent=true;grid.material.opacity=.12;this.root.add(grid);}}
  #player(){const g=new THREE.Group();const body=new THREE.Mesh(new THREE.DodecahedronGeometry(.48,0),new THREE.MeshStandardMaterial({color:0x55dfff,emissive:0x113d55,emissiveIntensity:.55,roughness:.32,metalness:.25}));body.position.y=.78;body.castShadow=true;const head=new THREE.Mesh(new THREE.IcosahedronGeometry(.29,1),this.material(0xf7f1d4));head.position.y=1.45;const visor=new THREE.Mesh(new THREE.BoxGeometry(.34,.11,.06),new THREE.MeshStandardMaterial({color:0x142238,emissive:0x4acfff,emissiveIntensity:.85}));visor.position.set(0,1.46,-.27);g.add(body,head,visor);for(const sx of [-1,1]){const leg=new THREE.Mesh(new THREE.BoxGeometry(.18,.62,.18),this.material(0x32769e));leg.position.set(sx*.2,.28,0);g.add(leg);}this.scene.add(g);this.player=g;}
  setCameraDelta(dx,dy){this.yaw-=dx*.005;this.pitch=Math.max(-.12,Math.min(1.05,this.pitch-dy*.004));}
  setGamepadLook(x,y,dt){this.yaw-=x*dt*2.1;this.pitch=Math.max(-.12,Math.min(1.05,this.pitch-y*dt*1.5));}
  togglePanorama(){this.panorama=!this.panorama;this.distance=this.panorama?11.5:7.5;return this.panorama;}
  heading(){const deg=(this.yaw*180/Math.PI%360+360)%360;const dirs=['N','NE','L','SE','S','SO','O','NO'];return{deg:Math.round(deg),label:dirs[Math.round(deg/45)%8]};}
  movementBasis(){return{sin:Math.sin(this.yaw),cos:Math.cos(this.yaw)};}
  update(sim,dt){if(sim.region.id!==this.region.id)this.setRegion(sim.region);this.clock+=dt;for(const m of sim.moving){const mesh=this.platformMeshes.get(m.id);if(mesh)mesh.position.set(...m.current);}for(const e of sim.enemies){const mesh=this.enemyMeshes.get(e.id);if(mesh){mesh.position.set(...e.current);mesh.rotation.y+=dt*1.4;}}for(const [id,m] of this.collectibleMeshes){m.visible=!sim.collected.has(id)&&(this.region.kind!=='village'||sim.quest.stage===4);if(m.visible){m.rotation.y+=dt*1.8;m.rotation.x+=dt*.8;if(!this.reduced)m.scale.setScalar(1+Math.sin(this.clock*3+id.length)*.08);}}for(const [id,m] of this.beaconMeshes){const active=sim.beacons.has(id);m.children.at(-1).material.emissiveIntensity=active?2.1:1.1;if(!this.reduced)m.rotation.y+=dt*(active?1.2:.35);}for(const [id,m] of this.checkpointMeshes){const active=sim.checkpoint.id===id;m.material.emissiveIntensity=active?1.55:.65;m.scale.setScalar(active?1.12:1);}for(const [id,g] of this.npcMeshes){if(!this.reduced)g.children.at(-1).position.y=1.85+Math.sin(this.clock*2.5+id.length)*.08;g.rotation.y=Math.sin(this.clock*.4+id.length)*.12;}for(const [id,g] of this.interactionMeshes){const item=(this.region.interactables||[]).find(x=>x.id===id);const active=item?.type==='repair'?sim.quest.activated.has(id):item?.type==='relay'?sim.quest.relays.has(id):item?.type==='data-terminal'?sim.quest.uploaded:item?.type==='core'?sim.quest.stage>=9:item?.type==='energy-node'?sim.quest.forestNodes.has(id):item?.type==='industrial-power'?sim.quest.industrialPower.has(id):item?.type==='cargo-console'?sim.quest.cargoRoutes.has(id):item?.type==='control-console'?sim.quest.controlSynced:item?.type==='tower-sync'?sim.quest.towerSync.has(id):item?.type==='tower-core'?sim.quest.towerCore:false;const core=g.children[1];if(core?.material)core.material.emissiveIntensity=active?1.7:.5;if(g.children[2]?.material)g.children[2].material.emissiveIntensity=active?2.2:1.0;if(!this.reduced)g.rotation.y+=dt*(active?1.0:.35);}if(this.weatherPoints){this.weatherPoints.position.x=Math.sin(this.clock*.35)*1.2;this.weatherPoints.position.y=-((this.clock*.45)%3);}const open=sim.portalOpen();this.portal.visible=true;this.portal.children[0].material.color.setHex(open?0x6dffbd:0x58708d);this.portal.children[0].material.emissive.setHex(open?0x41ffac:0x193047);this.portal.children[0].material.emissiveIntensity=open?1.8:.35;this.portal.rotation.y+=dt*(open?1.1:.25);this.player.position.set(sim.player.pos.x,sim.player.pos.y,sim.player.pos.z);const vx=sim.player.vel.x,vz=sim.player.vel.z;if(Math.hypot(vx,vz)>.1)this.player.rotation.y=Math.atan2(-vx,-vz);this.player.visible=sim.invulnerable>0?Math.floor(this.clock*12)%2===0:true;this.#camera(sim.player.pos,dt);this.renderer.render(this.scene,this.camera);}
  #camera(pos,dt){const target=new THREE.Vector3(pos.x,pos.y+1.05,pos.z);const cp=Math.cos(this.pitch),sp=Math.sin(this.pitch);const desired=new THREE.Vector3(target.x-Math.sin(this.yaw)*cp*this.distance,target.y+sp*this.distance+2.2,target.z-Math.cos(this.yaw)*cp*this.distance);this.camera.position.lerp(desired,1-Math.exp(-dt*(this.panorama?3.5:6)));this.camera.lookAt(target);}
  resize(){const w=innerWidth,h=innerHeight;this.renderer.setSize(w,h,false);this.camera.aspect=w/h;this.camera.updateProjectionMatrix();}
}
