import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import { fileURLToPath } from 'node:url';
const here=path.dirname(fileURLToPath(import.meta.url));
const root=path.resolve(here,'../..');
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const html=read('admin/index.html');
const js=read('admin/assets/admin.js');
const css=read('admin/assets/admin.css');
const config=read('admin/assets/config.js');
const profileEdge=read('core/edge-functions/admin-profile-user/index.ts');
const historyPolicy=read('core/database/023_student_file_history_staff_read.sql');
const professor=read('professor/assets/professor.js');
const views=['Visão Geral','Usuários','Turmas','Atividades','Correções','Código dos Alunos','Sessões','GitHub','Segurança','Auditoria','Relatórios','Configurações'];
for(const v of views) assert.ok(html.includes(v),`menu ${v}`);
for(const action of ['update_profile','set_active','force_password_change','end_activity_sessions']) assert.ok(profileEdge.includes(`act==='${action}'`),`admin-profile-user ${action}`);
for(const tab of ["summary:'Resumo'","activities:'Atividades'","code:'Código'","history:'Histórico'","github:'GitHub'","sessions:'Sessões'","security:'Segurança'","audit:'Auditoria'"]) assert.ok(js.includes(tab),`tab ${tab}`);
assert.match(js,/student_file_history\?/,'histórico de código via RLS');
assert.match(js,/activity_sessions\?/,'histórico de sessões via RLS');
assert.match(historyPolicy,/private\.staff_can_access_student\(student_id\)/,'histórico restrito por escopo staff');
assert.match(config,/admin-profile-user/);
assert.match(config,/staff-dashboard/);
assert.match(config,/supervision/);
assert.doesNotMatch(js,/SUPABASE_SERVICE_ROLE_KEY|sb_secret_/i);
assert.doesNotMatch(profileEdge,/auth\.admin\./,'ações Auth admin não simuladas no endpoint operacional');
assert.match(professor,/URLSearchParams\(location\.search\)\.get\('student'\)/,'deeplink do ADM para Professor');
assert.match(html,/Content-Security-Policy/);
assert.match(css,/\.profile-metrics/);
console.log(JSON.stringify({status:'ok',views:12,p0:true,p1Operational:true,p2:true,authAdminPending:true,studentHistoryScoped:true},null,2));
