import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
const root=path.resolve(path.dirname(new URL(import.meta.url).pathname),'../..');
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const admin=read('admin/assets/admin.js');
const adminHtml=read('admin/index.html');
const teacher=read('professor/assets/professor.js');
const teacherHtml=read('professor/index.html');
const mig24=read('core/database/024_p3_exercise_release_integrity_and_audit.sql');
const mig25=read('core/database/025_p3_staff_read_activity_catalog.sql');

assert.match(admin,/Central de Atividades/);
assert.match(admin,/release_at/);
assert.match(admin,/lock_at/);
for(const key of ['allow_html_base','allow_css_base','allow_js_base','allow_extra_hints','allow_guided_support']) assert.match(admin,new RegExp(key));
assert.match(admin,/saveActivityConfig/);
assert.match(admin,/bulkClassAvailability/);
assert.match(admin,/save.*group|scope==='group'/s);
assert.match(adminHtml,/activity-dialog/);
assert.match(adminHtml,/Turma inteira/);
assert.match(adminHtml,/Um aluno/);
assert.match(adminHtml,/Grupo de alunos/);

assert.match(teacherHtml,/teacher-release-panel/);
assert.match(teacherHtml,/Liberações/);
assert.match(teacher,/saveTeacherRelease/);
assert.match(teacher,/class_subjects/);
assert.match(teacher,/exercise_releases/);

assert.match(mig24,/exercise_releases_unique_class/);
assert.match(mig24,/exercise_releases_unique_student/);
assert.match(mig24,/exercise_releases_exactly_one_scope/);
assert.match(mig24,/exercise_releases_schedule_order/);
assert.match(mig24,/trg_audit_exercise_releases/);
assert.match(mig24,/private\.audit_exercise_release_change/);
assert.match(mig24,/exercise_releases_staff_delete/);
assert.match(mig25,/class_subjects_staff_read/);
assert.match(mig25,/exercises_staff_read/);
assert.doesNotMatch(admin,/service_role|SUPABASE_SERVICE_ROLE/i);
assert.doesNotMatch(teacher,/service_role|SUPABASE_SERVICE_ROLE/i);
console.log('admin-p3-activity-center-v10: PASS');
