import fs from 'node:fs';
import assert from 'node:assert/strict';
const lobby=fs.readFileSync(new URL('../../lobby/assets/lobby.js',import.meta.url),'utf8');
const three=fs.readFileSync(new URL('../../lobby/assets/lobby3d.js',import.meta.url),'utf8');
const lite=fs.readFileSync(new URL('../../lobby/assets/lobby-lite.js',import.meta.url),'utf8');
const index=fs.readFileSync(new URL('../../lobby/index.html',import.meta.url),'utf8');
const cfg=fs.readFileSync(new URL('../../lobby/assets/config.js',import.meta.url),'utf8');
assert.match(lobby,/lobby_3d_boot_timeout/);
assert.match(lobby,/startLite\(/);
assert.match(lobby,/freshCanvas\(\)/);
assert.match(lobby,/retry3D/);
assert.match(three,/three_import_timeout/);
assert.match(three,/mobile\|\|hardware<=4\?'low'/);
assert.match(three,/signal\?\.aborted/);
assert.match(lite,/createLobbyLite/);
assert.match(lite,/onPlayerState/);
assert.match(index,/id="retry-3d"/);
assert.match(index,/id="enter-lite"/);
assert.ok(/LOBBY_VERSION='0\.(3\.3|4\.0|5\.0|6\.0|7\.0|8\.0|9\.0)'/.test(cfg)||cfg.includes("LOBBY_VERSION='1.0.1'"));
assert.doesNotMatch(lite,/SUPABASE|service_role|exercise_releases/i);
console.log('PASS p5 lobby mobile recovery v11.5.2');
