import fs from 'node:fs';
import assert from 'node:assert/strict';
const root=new URL('../../',import.meta.url);
const read=p=>fs.readFileSync(new URL(p,root),'utf8');
const html=read('admin/index.html');
const js=read('admin/assets/admin.js');
const css=read('admin/assets/admin.css');
const activityAdmin=read('atividades/assets/js/admin.js');
assert.match(html,/data-view="monitor">Acompanhamento/,'Admin deve expor a Central de Acompanhamento');
assert.match(js,/function renderMonitor\(/,'Central deve ter render próprio');
assert.match(js,/sessionFresh\(/,'Online deve depender de heartbeat recente');
assert.match(js,/12000/,'Auto-refresh operacional deve ser de 12 segundos');
assert.match(js,/document\.hidden/,'Auto-refresh deve respeitar aba oculta');
assert.match(js,/data-student360/,'Acompanhamento deve abrir Perfil 360º');
assert.match(js,/riskLabel/,'Acompanhamento deve mostrar risco');
assert.match(css,/monitor-kpis/,'UI de acompanhamento deve ter KPIs responsivos');
assert.match(css,/@media\(max-width:620px\)/,'Acompanhamento deve ter regra mobile');
assert.match(activityAdmin,/staff-admin-central-btn/,'Área staff deve apontar administradores para a Central');
assert.doesNotMatch(js,/service_role|SUPABASE_SERVICE_ROLE_KEY/,'Frontend admin não pode conter service role');
console.log('P6.1 Admin Central v12.5: OK');
