import fs from 'node:fs';
import assert from 'node:assert/strict';
const root=new URL('../../',import.meta.url);
const read=p=>fs.readFileSync(new URL(p,root),'utf8');
const js=read('admin/assets/admin.js');
const css=read('admin/assets/admin.css');
assert.match(js,/ALERTA CRÍTICO — acesso fora do Paraná/,'Acesso fora do Paraná deve ser destacado como crítico');
assert.match(js,/risk_code==='outside_parana'/,'Central deve usar o risk_code server-side para fora do Paraná');
assert.match(js,/Geo inconclusiva/,'Geolocalização inconclusiva deve ser separada de ataque confirmado');
assert.match(js,/function uaLabel/,'Central deve apresentar dispositivo\/navegador a partir do user agent');
assert.match(js,/function exportSecurityCsv/,'Admin deve poder exportar o recorte de segurança');
assert.match(js,/data-ackaccess/,'Eventos de acesso devem poder ser marcados como revisados');
assert.match(js,/security-telemetry.*admin_ack/s,'Reconhecimento deve continuar passando pela Edge Function');
assert.match(js,/\['monitor','overview','security'\]/,'Central de segurança deve participar do auto-refresh visível');
assert.match(css,/security-critical/,'UI deve ter destaque próprio para crítico');
assert.match(css,/security-card\.severity-critical/,'Cards devem diferenciar severidade crítica');
assert.match(css,/@media\(max-width:720px\)/,'Central de segurança deve ter layout mobile');
assert.doesNotMatch(js,/SUPABASE_SERVICE_ROLE_KEY|service_role/,'Frontend admin não pode expor service role');
assert.doesNotMatch(js,/claim_core_reward|reward_claim/i,'Central de segurança não pode conceder recompensa');
console.log('P6.2 Central de Segurança v12.6: OK');
