import fs from 'node:fs';
import assert from 'node:assert/strict';
const root=new URL('../../',import.meta.url);
const read=p=>fs.readFileSync(new URL(p,root),'utf8');
const html=read('atividades/index.html');
const js=read('atividades/assets/js/app.js');
const css=read('atividades/assets/css/app.css');
assert.match(html,/id="next-action-label"/,'Painel deve ter próxima ação explícita');
assert.match(html,/id="available-activity-list"/,'Painel deve resumir atividades disponíveis');
assert.match(html,/id="completed-activity-list"/,'Painel deve resumir atividades concluídas');
assert.match(html,/id="locked-activity-list"/,'Painel deve mostrar atividades ainda não liberadas');
assert.match(js,/const nextExercise=latestExercise\|\|firstAvailable/,'Prioridade deve ser continuar atividade em andamento e depois próxima liberada');
assert.match(js,/exerciseAvailability\(ex,progressMap\.get\(ex\.id\)\)/,'Resumo deve reutilizar o gate de liberação existente');
assert.match(js,/progress\?\.security_locked\|\|progress\?\.status==='blocked'/,'Bloqueio de segurança deve continuar prevalecendo');
assert.match(js,/releasedTotal/,'Progresso geral deve ser calculado com base no universo pedagógico liberado/concluído');
assert.match(css,/student-focus-grid/,'Dashboard deve possuir layout específico do aluno');
assert.match(css,/@media\(max-width:390px\)/,'Dashboard deve ter tratamento para celular pequeno');
assert.doesNotMatch(js,/SUPABASE_SERVICE_ROLE_KEY|service_role/,'Painel do aluno não pode expor service role');
assert.doesNotMatch(js,/claim_core_reward|reward_claim/i,'Dashboard do aluno não pode conceder recompensas');
console.log('P6.3 Painel Principal do Aluno v12.7: OK');
