import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
const root=path.resolve(path.dirname(new URL(import.meta.url).pathname),'../..');
const html=fs.readFileSync(path.join(root,'atividades/index.html'),'utf8');
const workspace=fs.readFileSync(path.join(root,'atividades/assets/js/workspace.js'),'utf8');
const supervision=fs.readFileSync(path.join(root,'atividades/assets/js/supervision.js'),'utf8');

assert.doesNotMatch(html,/script-src[^\"]*'unsafe-eval'/,'unsafe-eval removed from app CSP');
assert.match(html,/script-src[^\"]*'wasm-unsafe-eval'/,'WASM compatibility retained explicitly');
assert.match(html,/worker-src 'self'/,'workers restricted to self');
assert.doesNotMatch(html,/worker-src[^;]*blob:/,'blob workers not allowed');
assert.match(html,/frame-src 'self'/,'frame source explicit');
assert.match(html,/media-src 'none'/,'media disabled by default');
assert.match(html,/id="preview-frame"[^>]*sandbox="allow-scripts"[^>]*referrerpolicy="no-referrer"/,'preview isolated');
assert.doesNotMatch(html,/sandbox="[^"]*allow-same-origin/,'preview cannot become same-origin');
assert.match(workspace,/const addSupportNote=.*document\.createElement\('div'\)/s,'support notes built with DOM');
assert.match(workspace,/span\.textContent=String\(message\|\|''\)/,'support message uses textContent');
assert.doesNotMatch(workspace,/guidance\.insertAdjacentHTML/,'support no longer injected as HTML');
assert.match(supervision,/summary\.replaceChildren\(\)/,'policy summary cleared safely');
assert.match(supervision,/span\.textContent=text/,'policy summary uses textContent');
console.log('P7.2 frontend hardening v14.1 — PASS');
