import * as THREE from '../voxelcraft-ds/vendor/three/three.module.min.js';
const params=new URLSearchParams(location.search);const quality=params.get('quality')||'medio';const reduced=params.get('reduced')==='1'||(typeof matchMedia==='function'&&matchMedia('(prefers-reduced-motion: reduce)').matches);const muted=params.get('muted')==='1';
const world=await fetch('./world.json').then(r=>r.json());const areas=world.areas;const el=id=>document.getElementById(id);
const SAVE_KEY='fliperama-plataforma-poligonal-3d';const SOURCE='fliperama-ds-plataforma-poligonal';
let portalPaused=false,areaIndex=0,lives=3,score=0,collected=new Set(),checkpoint=null,invulnerable=0,gameFinished=false;
function post(type,detail={}){parent?.postMessage({source:SOURCE,type,detail},location.origin==='null'?'*':location.origin)}
const canvas=el('scene');const renderer=new THREE.WebGLRenderer({canvas,antialias:quality!=='baixo',powerPreference:'high-performance'});renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.shadowMap.enabled=quality==='alto'||quality==='ultra';renderer.setPixelRatio(Math.min(devicePixelRatio,quality==='ultra'?1.6:quality==='alto'?1.35:quality==='medio'?1.1:1));
const scene=new THREE.Scene();const camera=new THREE.PerspectiveCamera(60,1,.1,120);const clock=new THREE.Clock();const worldRoot=new THREE.Group();scene.add(worldRoot);
scene.add(new THREE.HemisphereLight(0xaadfff,0x1a1830,1.25));const sun=new THREE.DirectionalLight(0xffffff,2.1);sun.position.set(6,12,8);sun.castShadow=renderer.shadowMap.enabled;scene.add(sun);
const state={pos:new THREE.Vector3(),vel:new THREE.Vector3(),yaw:0,grounded:false,coyote:0,jumpBuffer:0};
const player=new THREE.Group();const body=new THREE.Mesh(new THREE.CapsuleGeometry(.42,.72,4,8),new THREE.MeshStandardMaterial({color:0x64d8ff,roughness:.38,metalness:.18,emissive:0x0a4165,emissiveIntensity:.22}));body.castShadow=true;body.position.y=.82;const head=new THREE.Mesh(new THREE.IcosahedronGeometry(.34,1),new THREE.MeshStandardMaterial({color:0xf2fbff,roughness:.32,metalness:.12}));head.position.y=1.65;head.castShadow=true;const visor=new THREE.Mesh(new THREE.BoxGeometry(.38,.12,.05),new THREE.MeshStandardMaterial({color:0x13283d,emissive:0x59dfff,emissiveIntensity:.7}));visor.position.set(0,1.68,.32);player.add(body,head,visor);scene.add(player);
let staticPlatforms=[],movingPlatforms=[],collectibleMeshes=[],enemyMeshes=[],checkpointMesh=null,portalMesh=null;let areaGroup=null;
const keys={};const touch={forward:false,back:false,left:false,right:false,jump:false};
addEventListener('keydown',e=>{keys[e.code]=true;if(e.code==='Space'){state.jumpBuffer=.14;e.preventDefault()}if(e.code==='KeyR')restartArea()});addEventListener('keyup',e=>keys[e.code]=false);
document.querySelectorAll('[data-action]').forEach(btn=>{const a=btn.dataset.action;const set=v=>{touch[a]=v;if(a==='jump'&&v)state.jumpBuffer=.14};btn.addEventListener('pointerdown',e=>{e.preventDefault();btn.setPointerCapture(e.pointerId);set(true)});btn.addEventListener('pointerup',()=>set(false));btn.addEventListener('pointercancel',()=>set(false));});
let dragging=false,lastX=0;canvas.addEventListener('pointerdown',e=>{if(e.pointerType==='mouse'&&e.button!==0)return;dragging=true;lastX=e.clientX});addEventListener('pointermove',e=>{if(!dragging)return;const dx=e.clientX-lastX;lastX=e.clientX;state.yaw-=dx*.006});addEventListener('pointerup',()=>dragging=false);
function themeFor(name){return {city:{bg:0x071629,fog:0x0c2540,ground:0x244968,accent:0x59dfff},forest:{bg:0x071b19,fog:0x0b3028,ground:0x2d5946,accent:0x72ffc6},factory:{bg:0x15151a,fog:0x26252b,ground:0x4a4b55,accent:0xffb55e},tower:{bg:0x120a24,fog:0x25123f,ground:0x3b2d63,accent:0xd193ff}}[name]}
function boxMesh(size,pos,color,emissive=0){const g=new THREE.BoxGeometry(...size);const m=new THREE.MeshStandardMaterial({color,roughness:.56,metalness:.14,emissive,emissiveIntensity:emissive?0.22:0});const mesh=new THREE.Mesh(g,m);mesh.position.set(...pos);mesh.receiveShadow=true;mesh.castShadow=renderer.shadowMap.enabled;worldRoot.add(mesh);return mesh}
function addDecor(theme){const count=quality==='baixo'?10:quality==='medio'?18:quality==='alto'?28:36;for(let i=0;i<count;i++){const geo=i%3===0?new THREE.ConeGeometry(.4+Math.random()*.4,1.8+Math.random()*2,5):new THREE.DodecahedronGeometry(.3+Math.random()*.6,0);const mat=new THREE.MeshStandardMaterial({color:new THREE.Color(theme.accent).multiplyScalar(.5+Math.random()*.5),roughness:.55,metalness:.15});const m=new THREE.Mesh(geo,mat);const r=9+Math.random()*6,a=Math.random()*Math.PI*2;m.position.set(Math.cos(a)*r,(geo.type.includes('Cone')?1:1.5)+Math.random()*2,Math.sin(a)*r);m.rotation.set(Math.random(),Math.random()*3,Math.random());worldRoot.add(m)}}
function loadArea(index,spawnOverride=null){areaIndex=Math.max(0,Math.min(areas.length-1,index));while(worldRoot.children.length)worldRoot.remove(worldRoot.children[0]);staticPlatforms=[];movingPlatforms=[];collectibleMeshes=[];enemyMeshes=[];checkpointMesh=null;portalMesh=null;const a=areas[areaIndex],theme=themeFor(a.theme);scene.background=new THREE.Color(theme.bg);scene.fog=new THREE.FogExp2(theme.fog,quality==='baixo'?.055:.035);boxMesh(a.ground.size,a.ground.position,theme.ground);staticPlatforms.push({mesh:worldRoot.children.at(-1),size:a.ground.size});for(const p of a.platforms){const mesh=boxMesh(p.size,p.position,theme.ground+0x111111);staticPlatforms.push({mesh,size:p.size,id:p.id})}for(const p of a.movingPlatforms){const mesh=boxMesh(p.size,p.position,theme.accent,theme.accent);movingPlatforms.push({mesh,size:p.size,id:p.id,axis:p.axis,range:p.range,speed:p.speed,origin:new THREE.Vector3(...p.position),phase:Math.random()*Math.PI*2,last:new THREE.Vector3(...p.position)})}for(const c of a.collectibles){if(collected.has(c.id))continue;const mesh=new THREE.Mesh(new THREE.OctahedronGeometry(.38,0),new THREE.MeshStandardMaterial({color:theme.accent,emissive:theme.accent,emissiveIntensity:.8,metalness:.35,roughness:.18}));mesh.position.set(...c.position);mesh.userData.id=c.id;worldRoot.add(mesh);collectibleMeshes.push(mesh)}
checkpointMesh=new THREE.Mesh(new THREE.CylinderGeometry(.5,.7,.18,6),new THREE.MeshStandardMaterial({color:0x77ffb0,emissive:0x1d8d52,emissiveIntensity:.55}));checkpointMesh.position.set(...a.checkpoint.position);worldRoot.add(checkpointMesh);
portalMesh=new THREE.Group();const ring=new THREE.Mesh(new THREE.TorusGeometry(.9,.13,8,28),new THREE.MeshStandardMaterial({color:theme.accent,emissive:theme.accent,emissiveIntensity:1.1}));ring.rotation.y=Math.PI/2;portalMesh.add(ring);portalMesh.position.set(...a.portal.position);worldRoot.add(portalMesh);
for(const e of a.enemies){const group=new THREE.Group();const mat=new THREE.MeshStandardMaterial({color:e.type==='guardian'?0xff5de0:e.type==='sentinel'?0xff8b4b:e.type==='glitch'?0x9e6cff:0xff5e73,roughness:.35,metalness:.25,emissive:e.type==='guardian'?0x5f184f:0x351020,emissiveIntensity:.45});const core=new THREE.Mesh(new THREE.IcosahedronGeometry(.48,0),mat);core.castShadow=true;group.add(core);for(let j=0;j<3;j++){const limb=new THREE.Mesh(new THREE.BoxGeometry(.16,.16,.7),mat);limb.rotation.y=j*Math.PI*2/3;limb.position.set(Math.sin(limb.rotation.y)*.38,0,Math.cos(limb.rotation.y)*.38);group.add(limb)}group.position.set(...e.position);group.userData={...e,origin:new THREE.Vector3(...e.position),t:Math.random()*6};worldRoot.add(group);enemyMeshes.push(group)}addDecor(theme);
const spawn=spawnOverride||a.spawn;state.pos.set(...spawn);state.vel.set(0,0,0);checkpoint={area:areaIndex,pos:[...spawn]};updateHud();save();}
function platformTopHit(prevY,newY,x,z){let best=null;for(const p of [...staticPlatforms,...movingPlatforms]){const m=p.mesh,s=p.size;const top=m.position.y+s[1]/2;if(Math.abs(x-m.position.x)<=s[0]/2+.32&&Math.abs(z-m.position.z)<=s[2]/2+.32&&prevY>=top-.08&&newY<=top+.12){if(!best||top>best.top)best={ref:p,mesh:p.mesh,size:p.size,id:p.id,top}}}return best}
function respawn(){lives--;score=Math.max(0,score-150);if(lives<=0){lives=3;collected=new Set([...collected].filter(id=>!id.startsWith(`a${areaIndex+1}-`)));loadArea(areaIndex,areas[areaIndex].spawn);post('progress',{event:'continue',area:areaIndex+1,lives});return}state.pos.set(...checkpoint.pos);state.vel.set(0,0,0);invulnerable=1.4;updateHud();save()}
function restartArea(){const prefix=`a${areaIndex+1}-`;collected=new Set([...collected].filter(id=>!id.startsWith(prefix)));loadArea(areaIndex,areas[areaIndex].spawn)}
function areaCollected(){const prefix=`a${areaIndex+1}-`;return [...collected].filter(id=>id.startsWith(prefix)).length}
function updateHud(){el('areaLabel').textContent=`Área ${areaIndex+1}/4 · ${areas[areaIndex].name.replace(/^Área \d · /,'')}`;el('shards').textContent=`${collected.size}/12`;el('lives').textContent=lives;el('score').textContent=score.toLocaleString('pt-BR');const n=areaCollected();el('objective').textContent=n<3?`Colete os fragmentos desta área: ${n}/3.`:(areaIndex<3?'Portal liberado — atravesse para a próxima área.':'Portal final liberado — alcance o Núcleo de Render.');}
function save(){localStorage.setItem(SAVE_KEY,JSON.stringify({schemaVersion:1,areaIndex,lives,score,collected:[...collected],checkpoint}));post('progress',{area:areaIndex+1,totalAreas:4,shards:collected.size,lives,score})}
function restore(){try{const s=JSON.parse(localStorage.getItem(SAVE_KEY)||'null');if(s?.schemaVersion===1){areaIndex=Math.min(3,Math.max(0,s.areaIndex||0));lives=Math.max(1,s.lives||3);score=Math.max(0,s.score||0);collected=new Set(Array.isArray(s.collected)?s.collected:[]);checkpoint=s.checkpoint||null;return true}}catch{}return false}
function gamepadInput(){const pads=navigator.getGamepads?.()||[];const p=pads[0];if(!p)return {x:0,z:0,jump:false,look:0};const x=Math.abs(p.axes[0]||0)>.15?p.axes[0]:0,z=Math.abs(p.axes[1]||0)>.15?p.axes[1]:0,look=Math.abs(p.axes[2]||0)>.16?p.axes[2]:0;return{x,z,jump:!!p.buttons[0]?.pressed,look}}
function updateMoving(t,dt){for(const p of movingPlatforms){p.last.copy(p.mesh.position);const off=Math.sin(t*p.speed+p.phase)*p.range;p.mesh.position[p.axis]=p.origin[p.axis]+off}}
function updateEnemies(t,dt){if(invulnerable>0)invulnerable-=dt;for(const e of enemyMeshes){const u=e.userData;const off=Math.sin(t*u.speed+u.t)*u.range;e.position[u.axis]=u.origin[u.axis]+off;e.rotation.y+=dt*1.2;const dx=e.position.x-state.pos.x,dz=e.position.z-state.pos.z;if(invulnerable<=0&&dx*dx+dz*dz<1.15*1.15&&Math.abs(e.position.y-state.pos.y)<1.8)respawn()}}
function updatePlayer(dt){const gp=gamepadInput();state.yaw-=gp.look*dt*1.7;const forward=(keys.KeyW||keys.ArrowUp||touch.forward?1:0)-(keys.KeyS||keys.ArrowDown||touch.back?1:0);const side=(keys.KeyD||keys.ArrowRight||touch.right?1:0)-(keys.KeyA||keys.ArrowLeft||touch.left?1:0);let mx=side+gp.x,mz=forward-gp.z;if(gp.jump||touch.jump||keys.Space)state.jumpBuffer=Math.max(state.jumpBuffer,.08);const len=Math.hypot(mx,mz)||1;mx/=len;mz/=len;const speed=5.4;const sin=Math.sin(state.yaw),cos=Math.cos(state.yaw);const wx=mx*cos+mz*sin,wz=-mx*sin+mz*cos;state.vel.x=wx*speed;state.vel.z=-wz*speed;state.vel.y-=18.5*dt;state.coyote=Math.max(0,state.coyote-dt);state.jumpBuffer=Math.max(0,state.jumpBuffer-dt);if(state.grounded)state.coyote=.11;if(state.jumpBuffer>0&&state.coyote>0){state.vel.y=7.3;state.grounded=false;state.coyote=0;state.jumpBuffer=0}const prevY=state.pos.y;const nx=state.pos.x+state.vel.x*dt,nz=state.pos.z+state.vel.z*dt,ny=state.pos.y+state.vel.y*dt;const a=areas[areaIndex],halfX=a.ground.size[0]/2-.5,halfZ=a.ground.size[2]/2-.5;state.pos.x=Math.max(-halfX,Math.min(halfX,nx));state.pos.z=Math.max(-halfZ,Math.min(halfZ,nz));const hit=platformTopHit(prevY,ny,state.pos.x,state.pos.z);if(state.vel.y<=0&&hit){state.pos.y=hit.top;state.vel.y=0;state.grounded=true;if(movingPlatforms.includes(hit.ref)){const delta=hit.mesh.position.clone().sub(hit.ref.last);state.pos.x+=delta.x;state.pos.z+=delta.z}}else{state.pos.y=ny;state.grounded=false}if(state.pos.y<-5)respawn();player.position.copy(state.pos);player.rotation.y=Math.atan2(wx||Math.sin(state.yaw),-(wz||-Math.cos(state.yaw)));
for(let i=collectibleMeshes.length-1;i>=0;i--){const m=collectibleMeshes[i];if(m.position.distanceTo(player.position)<1.25){collected.add(m.userData.id);score+=300;worldRoot.remove(m);collectibleMeshes.splice(i,1);updateHud();save()}}
if(checkpointMesh&&checkpointMesh.position.distanceTo(player.position)<1.4&&(!checkpoint||checkpoint.area!==areaIndex||Math.hypot(checkpoint.pos[0]-checkpointMesh.position.x,checkpoint.pos[2]-checkpointMesh.position.z)>.2)){checkpoint={area:areaIndex,pos:[checkpointMesh.position.x,checkpointMesh.position.y+.2,checkpointMesh.position.z]};score+=150;checkpointMesh.material.emissiveIntensity=1.2;save()}
if(portalMesh){portalMesh.visible=areaCollected()>=3;portalMesh.rotation.y+=dt*.7;if(portalMesh.visible&&portalMesh.position.distanceTo(player.position)<1.65){if(areaIndex<3){score+=700;loadArea(areaIndex+1);post('area-complete',{area:areaIndex,score})}else if(!gameFinished){gameFinished=true;score+=1800;save();el('resultText').textContent=`12/12 fragmentos · ${score.toLocaleString('pt-BR')} pontos · 4 áreas concluídas.`;el('result').hidden=false;post('victory',{area:4,shards:12,lives,score,completed:true})}}}}
function updateCamera(dt){const dist=6.6,height=3.6;const target=new THREE.Vector3(state.pos.x,state.pos.y+1.1,state.pos.z);const desired=new THREE.Vector3(target.x-Math.sin(state.yaw)*dist,target.y+height,target.z-Math.cos(state.yaw)*dist);camera.position.lerp(desired,1-Math.exp(-dt*6));camera.lookAt(target)}
function resize(){renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix()}addEventListener('resize',resize);resize();
addEventListener('message',e=>{if((location.origin!=='null'&&e.origin!==location.origin)||e.data?.source!=='fliperama-ds')return;const t=e.data.type;if(t==='pause'||t==='shutdown')portalPaused=true;else if(t==='resume'||t==='start')portalPaused=false;else if(t==='restart'){portalPaused=false;localStorage.removeItem(SAVE_KEY);areaIndex=0;lives=3;score=0;collected.clear();gameFinished=false;el('result').hidden=true;loadArea(0)}});
el('replay').onclick=()=>{localStorage.removeItem(SAVE_KEY);areaIndex=0;lives=3;score=0;collected.clear();gameFinished=false;el('result').hidden=true;loadArea(0)};
restore();const restoreCp=checkpoint&&checkpoint.area===areaIndex?checkpoint.pos:null;loadArea(areaIndex,restoreCp);post('ready',{renderer:'three',runtime:'plataforma-poligonal-ds-3d',areas:4});
let time=0;function frame(){const dt=Math.min(.035,clock.getDelta());if(!portalPaused&&!gameFinished){time+=dt;updateMoving(time,dt);updateEnemies(time,dt);updatePlayer(dt);updateCamera(dt);for(const c of collectibleMeshes){c.rotation.y+=dt*1.8;c.rotation.x+=dt*.8;if(!reduced)c.position.y+=Math.sin(time*3+c.position.x)*.0009}if(checkpointMesh&&!reduced)checkpointMesh.rotation.y+=dt*.6}renderer.render(scene,camera);requestAnimationFrame(frame)}requestAnimationFrame(frame);
