'use strict';

(function(){
  window.LABDS_LABS=window.LABDS_LABS||{};
  const STORAGE_KEY='lab.help.state';
  const GLOSSARY=[
    {term:'Algoritmo',area:'Programação',definition:'Sequência finita de passos para resolver um problema ou realizar uma tarefa.',examples:['Receita de cálculo de média','Fluxo de login','Ordenação de dados'],tools:['block-programming','python','javascript']},
    {term:'Variável',area:'Programação',definition:'Nome associado a um valor que pode ser consultado e alterado durante a execução.',examples:['idade = 16','saldo = 250.0'],tools:['python','javascript']},
    {term:'Função',area:'Programação',definition:'Bloco reutilizável que recebe entradas, executa uma lógica e pode devolver uma saída.',examples:['calcularMedia(notas)','validarEmail(texto)'],tools:['python','javascript','web']},
    {term:'Banco de dados',area:'Dados',definition:'Sistema organizado para armazenar, consultar e relacionar informações.',examples:['Cadastro de produtos','Notas de estudantes'],tools:['sql','productivity-suite']},
    {term:'IP',area:'Redes',definition:'Endereço lógico utilizado para identificar um dispositivo em uma rede.',examples:['192.168.1.10','2001:db8::10'],tools:['network','network-operations']},
    {term:'DNS',area:'Redes',definition:'Serviço que traduz nomes de domínio para endereços IP.',examples:['site.exemplo.local → 192.0.2.20'],tools:['network','digital-communication']},
    {term:'XSS',area:'Segurança',definition:'Falha em que conteúdo não confiável é interpretado como código no navegador. A prevenção inclui escape, sanitização, CSP e uso correto de textContent.',examples:['Texto do usuário nunca deve entrar diretamente em innerHTML'],tools:['cybersecurity','web']},
    {term:'Hash',area:'Segurança',definition:'Resumo matemático de tamanho fixo usado para verificar integridade. Não é o mesmo que criptografia reversível.',examples:['SHA-256 de um arquivo'],tools:['cybersecurity','blockchain-crypto','data-tools']},
    {term:'Commit',area:'Git',definition:'Registro versionado de um conjunto de alterações em um repositório.',examples:['git commit -m "Corrige formulário"'],tools:['git-github']},
    {term:'Web Worker',area:'Web',definition:'Contexto de execução em segundo plano usado para evitar que tarefas pesadas bloqueiem a interface.',examples:['Executar JavaScript ou SQL com timeout'],tools:['javascript','sql']},
    {term:'WebGL',area:'Gráficos',definition:'API gráfica do navegador utilizada para renderização 2D e 3D acelerada por GPU.',examples:['VoxelCraft DS 3D'],tools:['voxelcraft-3d','game-engine']},
    {term:'Fatiamento 3D',area:'Fabricação',definition:'Processo que transforma um modelo 3D em camadas e trajetórias de impressão.',examples:['Gerar G-code para FDM'],tools:['printing-3d']},
    {term:'CC e CCO',area:'Produtividade',definition:'CC mostra a cópia aos demais destinatários; CCO oculta o endereço dos outros destinatários.',examples:['Enviar comunicado preservando privacidade'],tools:['productivity-suite','digital-communication']},
    {term:'Referência absoluta',area:'Planilhas',definition:'Referência de célula que não muda ao copiar uma fórmula, como $A$1.',examples:['=B2*$F$1'],tools:['productivity-suite']},
    {term:'FPS e Hertz',area:'Mídia',definition:'FPS indica quadros produzidos por segundo; Hertz indica quantas atualizações a tela pode exibir por segundo.',examples:['120 FPS em tela de 60 Hz'],tools:['display-media']}
  ];
  const FAQ=[
    ['Os laboratórios são reais?','Alguns executam tecnologias reais no navegador, como JavaScript, SQLite, Canvas e WebGL. Outros são simulações educacionais identificadas na interface.'],
    ['Os dados vão para algum servidor?','O Lab Virtual DS armazena progresso localmente no navegador. Recursos externos só são usados quando uma biblioteca precisa ser carregada na primeira execução.'],
    ['Como salvar o progresso?','Use o perfil V3 para exportar o progresso global em JSON e o menu de manutenção para exportar o backup completo dos laboratórios.'],
    ['Por que um laboratório pode ficar mais lento?','WebGL, WebAssembly, câmera e grandes grades usam mais memória. Abra o diagnóstico e escolha qualidade Baixa ou Econômica em aparelhos limitados.'],
    ['Como reportar um erro?','Abra o menu V3 e selecione Reportar problema. O relatório é gerado localmente para copiar ou baixar.'],
    ['O Lab Virtual DS substitui ferramentas profissionais?','Não. Ele oferece experiências práticas e introdutórias quando a ferramenta oficial não está disponível.']
  ];
  let root,ctx,state={query:'',favorites:[]};
  const $=selector=>root.querySelector(selector);
  const norm=value=>String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
  function buildIndex(){
    const tools=window.LABDS.TOOLS.filter(tool=>tool.id!=='help-center').map(tool=>({type:'tool',title:tool.name,area:window.LABDS.CATEGORY_LABELS[tool.category]||tool.category,description:tool.description,keywords:[tool.id,tool.shortName,...(tool.tags||[])].join(' '),toolId:tool.id}));
    const glossary=GLOSSARY.map(item=>({type:'glossary',title:item.term,area:item.area,description:item.definition,keywords:[item.term,item.area,...item.examples].join(' '),tools:item.tools}));
    const commands=[
      ['mkdir','Cria uma pasta no CMD, PowerShell ou terminal Unix.','cmd'],['cd','Entra em uma pasta ou mostra o diretório atual.','cmd'],['ls / dir','Lista arquivos e pastas.','bash'],['git status','Mostra o estado do repositório Git.','git-github'],['SELECT','Consulta registros em SQL.','sql'],['print()','Exibe valores em Python.','python'],['console.log()','Registra valores no console JavaScript.','javascript'],['ping','Testa conectividade e latência.','network']
    ].map(([title,description,toolId])=>({type:'command',title,area:'Comandos',description,keywords:`${title} ${description}`,toolId}));
    return [...tools,...glossary,...commands];
  }
  const INDEX=buildIndex();
  function search(query){const terms=norm(query).split(/\s+/).filter(Boolean);if(!terms.length)return INDEX.filter(item=>item.type==='tool').slice(0,12);return INDEX.map(item=>{const hay=norm(`${item.title} ${item.area} ${item.description} ${item.keywords}`);const score=terms.reduce((total,term)=>total+(hay.includes(term)?hay.startsWith(term)?5:2:0),0)+(norm(item.title).includes(norm(query))?8:0);return{...item,score};}).filter(item=>item.score>0).sort((a,b)=>b.score-a.score||a.title.localeCompare(b.title)).slice(0,40);}
  function renderResults(){const query=$('#helpSearch').value.trim();state.query=query;ctx.storage.set(STORAGE_KEY,state);const items=search(query),host=$('#helpResults');host.textContent='';$('#helpCount').textContent=`${items.length} resultado(s)`;items.forEach(item=>{const article=document.createElement('article');article.className='help-result';const head=document.createElement('div'),badge=document.createElement('span'),title=document.createElement('h3'),p=document.createElement('p'),actions=document.createElement('div');badge.textContent=item.type==='tool'?'Ferramenta':item.type==='command'?'Comando':'Glossário';title.textContent=item.title;p.textContent=item.description;head.append(badge,title);actions.className='button-row';const related=item.toolId?[item.toolId]:(item.tools||[]);related.forEach(id=>{const tool=window.LABDS.TOOLS.find(entry=>entry.id===id);if(!tool)return;const button=document.createElement('button');button.type='button';button.className='btn secondary';button.textContent=`Abrir ${tool.shortName||tool.name}`;button.addEventListener('click',()=>window.LABDS.App.openTool(id));actions.appendChild(button);});article.append(head,p,actions);host.appendChild(article);});if(!items.length){host.innerHTML='<div class="empty-state"><strong>Nenhum resultado local encontrado.</strong><span>Tente outro termo, categoria, comando ou linguagem.</span></div>';}}
  function template(){return `<div class="help-center-lab"><section class="help-hero"><div><span class="eyebrow">BUSCA LOCAL E OFFLINE</span><h2>Central de Ajuda e Conhecimento</h2><p>Encontre rapidamente ferramentas, comandos, conceitos e respostas frequentes. Para cursos completos, abra a Central de Tutoriais; para linguagens e carreiras, use Explorar Tecnologia.</p></div><div class="help-search-row"><input id="helpSearch" type="search" placeholder="Ex.: fórmula SE, Python, IP, Git, XSS..." autocomplete="off"><button id="helpSearchBtn" class="btn primary" type="button">Pesquisar</button></div><div class="help-quick">${['Classroom','Tutoriais','Python','Linguagens','Carreiras','Relógios','Sistema Solar','GitHub Pages'].map(term=>`<button type="button" data-help-term="${term}">${term}</button>`).join('')}</div></section><section class="help-layout"><div><div class="panel-title"><h2>Resultados</h2><span id="helpCount"></span></div><div id="helpResults" class="help-results"></div></div><aside class="help-faq"><h2>Perguntas frequentes</h2>${FAQ.map(([question,answer])=>`<details><summary>${question}</summary><p>${answer}</p></details>`).join('')}<div class="state-card info"><h3>Ajuda contextual</h3><p>Abra o botão Ajuda dentro de cada laboratório para consultar instruções específicas daquele ambiente.</p></div></aside></section></div>`;}
  async function mount(host,context){root=host;ctx=context;state={query:'',favorites:[],...(await ctx.storage.get(STORAGE_KEY,{}))};root.innerHTML=template();$('#helpSearch').value=state.query||'';$('#helpSearch').addEventListener('input',renderResults);$('#helpSearch').addEventListener('keydown',event=>{if(event.key==='Enter'){event.preventDefault();renderResults();}});$('#helpSearchBtn').addEventListener('click',renderResults);root.querySelectorAll('[data-help-term]').forEach(button=>button.addEventListener('click',()=>{$('#helpSearch').value=button.dataset.helpTerm;renderResults();}));renderResults();}
  async function unmount(){await ctx?.storage?.set?.(STORAGE_KEY,state);root=null;ctx=null;}
  function exportPayload(){return{text:`CENTRAL DE AJUDA\nPesquisa atual: ${state.query}\nItens indexados: ${INDEX.length}`,native:JSON.stringify({query:state.query,indexed:INDEX.length},null,2),backup:state};}
  function help(){return '<p>Digite uma palavra, conceito, comando, linguagem ou nome de laboratório. A pesquisa funciona inteiramente no navegador e pode ser usada offline depois do primeiro carregamento.</p>';}
  window.LABDS_LABS['help-center-lab']={mount,unmount,exportPayload,help};
})();
