'use strict';
const VERSION='labds-v4.21.0-hardware-system-benchmark-incident-phase-a55-agv-core-p1-v7';
const CORE=`${VERSION}-core`,RUNTIME=`${VERSION}-runtime`,EXTERNAL=`${VERSION}-external`;
const CORE_FILES=[
  './','./index.html','./offline.html','./manifest.webmanifest','./assets/icon.svg','./assets/hero-tech-lab.svg','./css/boot.css',
  './js/core/bootstrap.js','./js/core/resource-loader.js','./js/core/performance-manager.js',
  './css/style.css','./css/session.css','./css/performance.css','./css/v3.css','./css/v32.css',
  './js/config.js','./js/schemas.js','./js/storage.js','./js/session.js','./js/agv-core-bridge.js','./js/v3/core.js','./js/accessibility.js','./js/app.js'
];
async function addCore(){const cache=await caches.open(CORE);await Promise.all(CORE_FILES.map(async url=>{try{await cache.add(new Request(url,{cache:'reload'}));}catch(error){console.warn('[SW] núcleo não armazenado',url,error);}}));}
self.addEventListener('install',event=>event.waitUntil(addCore()));
self.addEventListener('activate',event=>event.waitUntil((async()=>{const valid=new Set([CORE,RUNTIME,EXTERNAL]);await Promise.all((await caches.keys()).filter(key=>key.startsWith('labds-')&&!valid.has(key)).map(key=>caches.delete(key)));await self.clients.claim();})()));
async function trim(cacheName,maxEntries){const cache=await caches.open(cacheName),keys=await cache.keys();if(keys.length<=maxEntries)return;await Promise.all(keys.slice(0,keys.length-maxEntries).map(key=>cache.delete(key)));}
async function put(cacheName,request,response,maxEntries){if(!response?.ok)return response;const cache=await caches.open(cacheName);await cache.put(request,response.clone());trim(cacheName,maxEntries).catch(()=>{});return response;}
async function networkFirst(request,{cacheName=RUNTIME,fallback=null,timeoutMs=5000,maxEntries=180}={}){const cache=await caches.open(cacheName),controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),timeoutMs);try{return await put(cacheName,request,await fetch(request,{signal:controller.signal,cache:'no-cache'}),maxEntries);}catch{return(await cache.match(request))||(await caches.match(request))||(fallback?await caches.match(fallback):null)||Response.error();}finally{clearTimeout(timeout);}}
async function staleWhileRevalidate(request,{cacheName=RUNTIME,maxEntries=180}={}){const cache=await caches.open(cacheName),cached=(await cache.match(request))||(await caches.match(request)),fresh=fetch(request,{cache:'no-cache'}).then(response=>put(cacheName,request,response,maxEntries)).catch(()=>null);return cached||await fresh||Response.error();}
self.addEventListener('fetch',event=>{const request=event.request;if(request.method!=='GET')return;const url=new URL(request.url);if(url.origin===self.location.origin){if(request.mode==='navigate'||request.destination==='document'){event.respondWith(networkFirst(request,{fallback:'./offline.html',timeoutMs:4000}));return;}if(['script','style','worker','sharedworker','image','manifest','font'].includes(request.destination)||url.pathname.endsWith('/module.json')||url.pathname.endsWith('/MODULE_INDEX.json')){event.respondWith(staleWhileRevalidate(request));return;}event.respondWith(networkFirst(request,{timeoutMs:4500}));return;}if(url.hostname==='cdn.jsdelivr.net')event.respondWith(staleWhileRevalidate(request,{cacheName:EXTERNAL,maxEntries:30}));});
self.addEventListener('message',event=>{if(event.data?.type==='SKIP_WAITING')self.skipWaiting();if(event.data?.type==='CLEAR_RUNTIME')event.waitUntil(Promise.all([caches.delete(RUNTIME),caches.delete(EXTERNAL)]));if(event.data?.type==='GET_VERSION')event.source?.postMessage?.({type:'LABDS_VERSION',version:VERSION});if(event.data?.type==='CACHE_URLS'&&Array.isArray(event.data.urls))event.waitUntil((async()=>{const cache=await caches.open(RUNTIME);for(const url of event.data.urls.slice(0,20)){try{await cache.add(url);}catch{}}await trim(RUNTIME,180);})());});
