(function(){
  'use strict';
  const MANIFEST_VERSION='1.0.0';
  const PERMISSIONS=Object.freeze({
    'clipboard-write':{label:'Área de transferência',required:false,purpose:'Copiar códigos, comprovantes e comandos quando você selecionar o botão Copiar.',data:'Somente o texto mostrado na ação atual.',processing:'No dispositivo.',stored:false,fallback:'Selecione o texto e copie manualmente.',revocation:'Revise as permissões do site nas configurações do navegador.'},
    'file-read':{label:'Arquivos selecionados',required:false,purpose:'Importar somente o perfil, chave ou arquivo escolhido por você.',data:'Somente o arquivo selecionado.',processing:'No dispositivo.',stored:'Conforme a função solicitada e o perfil criptografado.',fallback:'Continue sem importar ou use outro arquivo válido.',revocation:'Cancele o seletor ou remova o arquivo antes de confirmar.'},
    'file-download':{label:'Download de arquivos',required:false,purpose:'Exportar evidências, backups e projetos para a pasta de downloads.',data:'Resultado ou pacote gerado pela atividade.',processing:'No dispositivo.',stored:'Na pasta escolhida pelo navegador.',fallback:'Copie o conteúdo quando a opção estiver disponível.',revocation:'Apague o arquivo da pasta de downloads quando não precisar mais.'},
    'persistent-storage':{label:'Armazenamento persistente',required:false,purpose:'Reduzir o risco de o navegador remover automaticamente um perfil local.',data:'Perfil criptografado e preferências.',processing:'No dispositivo.',stored:'Até a expiração configurada ou exclusão pelo aluno.',fallback:'Use backup do perfil e exporte as evidências.',revocation:'Exclua o perfil ou os dados do site nas configurações do navegador.'},
    fullscreen:{label:'Tela cheia',required:false,purpose:'Aumentar o espaço da atividade em telas pequenas.',data:'Nenhum dado pessoal.',processing:'No dispositivo.',stored:false,fallback:'Continue normalmente sem tela cheia.',revocation:'Pressione Esc ou use o controle do navegador.'}
  });
  let modal=null,pending=null;
  function inject(){if(document.getElementById('permissionExplainModal'))return;modal=document.createElement('div');modal.id='permissionExplainModal';modal.className='modal-overlay hidden';modal.setAttribute('role','dialog');modal.setAttribute('aria-modal','true');modal.innerHTML=`<section class="modal-card permission-card"><span class="modal-kicker">PERMISSÃO CONTEXTUAL</span><h2 id="permissionTitle">Permissão</h2><p class="permission-educational">Esta solicitação faz parte de uma atividade educacional. O recurso será utilizado somente para a finalidade descrita nesta tela.</p><dl id="permissionDetails"></dl><p id="permissionMessage" class="mode-status"></p><div class="modal-actions"><button id="permissionCancel" class="btn ghost" type="button">Continuar sem permitir</button><button id="permissionAllow" class="btn primary" type="button">Continuar com a ação</button></div></section>`;document.body.appendChild(modal);modal.querySelector('#permissionCancel').addEventListener('click',()=>finish(false));modal.querySelector('#permissionAllow').addEventListener('click',()=>finish(true));}
  function finish(allowed){modal.classList.add('hidden');document.body.classList.remove('modal-open');const resolve=pending?.resolve,action=pending?.action,id=pending?.id;pending=null;record(id,allowed?'GRANTED':'FALLBACK_SELECTED');if(allowed&&typeof action==='function')Promise.resolve().then(action).then(value=>resolve?.({allowed:true,value})).catch(error=>resolve?.({allowed:false,error}));else resolve?.({allowed:false});}
  function record(id,status){const item={permissionAcceptanceId:crypto.randomUUID?.()||String(Date.now()),permissionId:id,permissionType:id,manifestVersion:MANIFEST_VERSION,purposeId:id,toolId:'desafio-ds',toolVersion:'30.0.0',at:new Date().toISOString(),status,fallbackSelected:status==='FALLBACK_SELECTED',explanationViewed:true};if(window.DS_ProfileManager?.hasSession?.()){const history=window.DS_ProfileManager.getPath('permissions.history',[]);history.push(item);window.DS_ProfileManager.setPath('permissions.history',history.slice(-100));window.DS_ProfileManager.recordAudit?.('permission_decision',{permissionId:id,status});}}
  function explain(id,action){inject();const config=PERMISSIONS[id];if(!config)return Promise.resolve({allowed:false,error:new Error('Permissão não declarada no manifesto.')});return new Promise(resolve=>{pending={id,action,resolve};modal.querySelector('#permissionTitle').textContent=config.label;const dl=modal.querySelector('#permissionDetails');dl.replaceChildren();[['Por que solicitamos',config.purpose],['Dados utilizados',config.data],['Processamento',config.processing],['Armazenamento',String(config.stored)],['Alternativa',config.fallback],['Como revogar',config.revocation]].forEach(([term,desc])=>{const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=term;dd.textContent=desc;dl.append(dt,dd);});modal.classList.remove('hidden');document.body.classList.add('modal-open');setTimeout(()=>modal.querySelector('#permissionAllow').focus(),20);});}
  async function requestPersistentStorage(){return explain('persistent-storage',async()=>{if(!navigator.storage?.persist)return false;return navigator.storage.persist();});}
  function list(){return Object.entries(PERMISSIONS).map(([id,value])=>({id,...value}));}
  window.DS_Permissions=Object.freeze({manifestVersion:MANIFEST_VERSION,permissions:PERMISSIONS,explain,requestPersistentStorage,list});
})();
