(function(){
  'use strict';
  const META={
    title:'Desafio DS',version:'33.0.0-piloto',status:'piloto pedagógico',createdAt:'2026',updatedAt:'2026-08-04',
    lead:'Professor Gabriel',institution:'Colégio Estadual José Bonifácio',program:'Técnico em Desenvolvimento de Sistemas',
    ai:{tool:'ChatGPT',provider:'OpenAI',model:'GPT-5.6 Thinking',mode:'Raciocínio, implementação e validação assistida',validation:'Professor Gabriel'},
    changes:[
      {version:'33.0.0-piloto',date:'04/08/2026',title:'21 aulas piloto com conteúdo real',items:['Aulas organizadas por turno, turma e disciplina.','Conteúdo autoral com contexto, explicação, exemplo, prática, laboratório interno, fixação e entrega.','Três aulas piloto em cada uma das sete disciplinas.','Simuladores internos, códigos para copiar e baixar e guias de uso no VS Code.','As outras 93 aulas permanecem disponíveis para comparação antes da expansão do novo padrão.']},
      {version:'32.0.0',date:'04/08/2026',title:'Fluxo simples de aula e comprovante',items:['Código coletivo válido por uma hora solicitado somente no início da aula.','Removidas validações repetidas durante as etapas.','Plataformas externas apresentadas pelo nome, com envio de comprovante pelo aluno.','Conclusão com comprovante completo para impressão em PDF, logs e links de entrega.','Áreas de toque e botões revisados para celular, tablet e Chromebook.']},
      {version:'30.1.0',date:'04/08/2026',title:'Painel EduAuth Professor acessível',items:['Adicionado gerador direto de senha coletiva por turma, disciplina e aula.','Separado o gerador de senhas das funções de auditoria e manutenção.','Melhoradas as instruções exibidas ao professor e aos alunos durante a liberação.']},
      {version:'30.0.0',date:'03/08/2026',title:'Sequência curricular revisada',items:['Reorganizadas as trilhas ativas para 114 aulas coerentes com o trimestre.','Consolidados conteúdos repetidos sem apagar IDs, histórico ou progresso.','Front-End da manhã passa a priorizar JavaScript; Inovação amplia empresa, mercado e finanças; 3º DS recebe laboratórios de linguagens e games.','Removidos projetos finais obrigatórios deste ciclo e adicionadas estações e miniapps guiados.']},
      {version:'29.1.0',date:'03/08/2026',title:'Classroom por turma e disciplina',items:['Adicionado seletor contextual antes de abrir o Classroom.','Configurados os sete links reais das disciplinas das quatro turmas.','Links normalizados para não depender da posição da conta Google no navegador.']},
      {version:'28.1.0',date:'03/08/2026',title:'Fliperama DS integrado',items:['Configurado o endereço oficial do Fliperama DS.','Atividades de lógica, física, animação, controles e UX agora abrem a plataforma diretamente.','Mantido o retorno por evidência para consolidar a atividade no Modo Guiado.']},
      {version:'25.0.0',date:'30/07/2026',title:'Segurança, termos e integridade pedagógica',items:['Adicionado termo obrigatório e versionado de uso responsável.','Adicionadas política de privacidade, aviso de simulações e manifesto de permissões.','Migrada a pontuação competitiva para extrato de XP encadeado com estados disponível, em análise e bloqueado.','Adicionados reforços contra XSS, importações maliciosas e poluição de protótipo.','Adicionados funcionamento offline, agradecimento da versão e documentação de segurança e avaliação.']},
      {version:'24.0.0',date:'30/07/2026',title:'Central de Código por aula',items:['Adicionada visualização, cópia e download de códigos coerentes com as aulas.','Adicionado download de projetos ZIP com README e estrutura organizada.','Incluídos comandos de terminal, dependências, verificações, FAQ e limitações sob demanda.']},
      {version:'23.0.0',date:'30/07/2026',title:'Aulas guiadas revisadas',items:['Revisadas as trilhas de Mobile, Front-End e Introdução à Programação.','Adicionados simuladores de variáveis, laços, decisões, Box Model, coerência visual e continuidade de fluxo.']},
      {version:'22.0.0',date:'29/07/2026',title:'EduAuth Offline',items:['Substituídas senhas fixas por autorizações temporárias vinculadas ao contexto.','Adicionados PIN coletivo, PIN por sessão, autorização assinada e auditoria local.']},
      {version:'21.0.0',date:'29/07/2026',title:'Perfis, entrega e contexto escolar',items:['Adicionado perfil local criptografado em IndexedDB.','Adicionados backup, importação, bloqueio, expiração e recuperação administrativa.']},
      {version:'20.0.0',date:'29/07/2026',title:'Diagnóstico e responsividade',items:['Separados os modos competitivo e diagnóstico completo.','Revisado o layout responsivo e ampliada a trilha de Programação Mobile.']},
      {version:'19.0.0',date:'28/07/2026',title:'Modo Guiado',items:['Adicionado o Modo Guiado por turma, disciplina e código de aula.']}
    ]
  };
  const TOOLS=[
    {name:'Lab Virtual DS',description:'Laboratórios e simuladores de diferentes áreas de Desenvolvimento de Sistemas.',status:'use o endereço informado pelo professor',url:'',areas:['Programação','Hardware','Redes']},
    {name:'Lab 3D / HoloMotion',description:'Experiências 3D, 360°, gestos, desempenho e visualização espacial.',status:'use o endereço informado pelo professor',url:'',areas:['3D','VR','Desempenho']},
    {name:'CTF Cyber',description:'Desafios educativos de segurança, criptografia e investigação controlada.',status:'use o endereço informado pelo professor',url:'',areas:['Segurança','Criptografia']},
    {name:'Fliperama DS',description:'Jogos e experiências para estudar lógica, física, animações, controles, responsividade e experiência do usuário.',status:'use o endereço informado pelo professor',url:'',areas:['Jogos','Lógica','Física','UX']},
    {name:'Diagnóstico Edu',description:'Diagnóstico de aprendizagem com indicadores e explicações adaptadas.',status:'em desenvolvimento',url:'',areas:['Diagnóstico','Aprendizagem']},
    {name:'Recuperação Adaptada',description:'Atividades com explicações progressivas e recursos de apoio.',status:'em desenvolvimento',url:'',areas:['Acessibilidade','Recuperação']}
  ];
  const CAREERS=[
    ['Desenvolvimento web','HTML, CSS, JavaScript, APIs, Git e acessibilidade.','Front-end, manutenção de sites e full-stack júnior.'],
    ['Desenvolvimento mobile','Responsividade, experiência de toque, Kotlin, Swift e soluções multiplataforma.','Aplicações mobile, testes e prototipação.'],
    ['Suporte e infraestrutura','Hardware, sistemas operacionais, redes, diagnóstico e atendimento.','Suporte técnico, help desk e field service.'],
    ['Testes e qualidade','Identificação de erros, casos de teste, documentação e validação.','QA, testes manuais e suporte à implantação.'],
    ['Análise de sistemas','Requisitos, processos, protótipos, UML e validação com usuários.','Análise de requisitos e documentação.']
  ];
  const esc=value=>window.DS_Sanitize?.escapeHtml?.(value)||String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function inject(){
    if(document.getElementById('platformUtilityDock'))return;
    const dock=document.createElement('nav');dock.id='platformUtilityDock';dock.className='platform-utility-dock';dock.setAttribute('aria-label','Ajuda e informações');dock.innerHTML='<button type="button" data-shell="help">Ajuda</button><button type="button" data-shell="classroom">Classroom</button><button type="button" data-shell="terms">Termos</button><button type="button" data-shell="tools">Ferramentas</button><button type="button" data-shell="about">Sobre</button>';document.body.appendChild(dock);
    const modal=document.createElement('div');modal.id='platformShellModal';modal.className='modal-overlay hidden';modal.setAttribute('role','dialog');modal.setAttribute('aria-modal','true');modal.innerHTML='<div class="modal-card platform-shell-card"><div class="platform-shell-head"><div><span class="modal-kicker">DESAFIO DS</span><h2 id="platformShellTitle">Informações</h2></div><button id="platformShellClose" class="btn ghost" type="button">Fechar</button></div><div id="platformShellContent"></div></div>';document.body.appendChild(modal);
    dock.querySelectorAll('[data-shell]').forEach(button=>button.addEventListener('click',()=>open(button.dataset.shell)));modal.querySelector('#platformShellClose').addEventListener('click',close);modal.addEventListener('click',event=>{if(event.target===modal)close();});
    const footer=document.createElement('footer');footer.className='credits-footer';footer.innerHTML=`Idealização e desenvolvimento pedagógico: <strong>${META.lead}</strong> · Versão ${META.version} · Atualizado em ${META.updatedAt}`;document.body.appendChild(footer);
  }
  function open(section){
    if(section==='terms'){window.DS_Terms?.open?.();return;}if(section==='classroom'){window.DS_Classroom?.open?.({source:'barra-global'});return;}
    const modal=document.getElementById('platformShellModal'),title=document.getElementById('platformShellTitle'),content=document.getElementById('platformShellContent');modal.classList.remove('hidden');document.body.classList.add('modal-open');
    if(section==='help'){title.textContent='Central de ajuda';content.innerHTML=helpHtml();bindHelp(content);}else if(section==='tools'){title.textContent='Ferramentas e carreiras';content.innerHTML=toolsHtml();bindUrls(content);}else{title.textContent='Sobre, créditos e versões';content.innerHTML=aboutHtml();}
  }
  function close(){document.getElementById('platformShellModal')?.classList.add('hidden');document.body.classList.remove('modal-open');}
  function helpHtml(){return `<div class="shell-tabs"><button class="active" data-help-tab="delivery" type="button">Entrega</button><button data-help-tab="classroom" type="button">Classroom</button><button data-help-tab="github" type="button">GitHub/VS Code</button><button data-help-tab="storage" type="button">Armazenamento</button><button data-help-tab="privacy" type="button">Privacidade</button></div><div id="shellHelpBody">${deliveryHelp()}</div>`;}
  function bindHelp(root){root.querySelectorAll('[data-help-tab]').forEach(button=>button.addEventListener('click',()=>{root.querySelectorAll('[data-help-tab]').forEach(b=>b.classList.toggle('active',b===button));const tab=button.dataset.helpTab,body=root.querySelector('#shellHelpBody');body.innerHTML=tab==='classroom'?classroomHelp():tab==='github'?githubHelp():tab==='storage'?storageHelp():tab==='privacy'?privacyHelp():deliveryHelp();bindUrls(body);}));bindUrls(root);}
  function bindUrls(root){root.querySelectorAll('[data-open-url]').forEach(button=>button.addEventListener('click',()=>{const url=window.DS_Sanitize?.safeUrl?.(button.dataset.openUrl);if(url)window.open(url,'_blank','noopener,noreferrer');}));}
  const deliveryHelp=()=>`<div class="help-flow"><h3>Entrega rápida</h3><ol><li>Conclua e revise a atividade.</li><li>Exporte o arquivo.</li><li>Localize-o em Downloads.</li><li>Abra a atividade correta no Classroom.</li><li>Anexe o arquivo ou link.</li><li>Selecione Entregar e confirme.</li></ol><p>A plataforma registra a exportação e a abertura do Classroom, mas não confirma a entrega sem API oficial.</p></div>`;
  const classroomHelp=()=>`<div class="help-flow"><h3>Como entregar no Classroom</h3><ol><li>Confirme a conta escolar correta.</li><li>Selecione <strong>Abrir Classroom</strong>.</li><li>Escolha a disciplina da sua turma.</li><li>Abra a atividade indicada pelo professor.</li><li>Entre em <strong>Seu trabalho</strong> e escolha <strong>Adicionar ou criar</strong>.</li><li>Selecione Arquivo ou Link.</li><li>Aguarde o carregamento, clique em <strong>Entregar</strong> e confirme.</li></ol><button class="btn secondary" type="button" data-open-classroom-selector>Abrir Classroom</button></div>`;
  const githubHelp=()=>`<div class="help-flow"><h3>Projeto de programação</h3><ol><li>Baixe e extraia o ZIP.</li><li>Leia o README.</li><li>Abra a pasta no VS Code.</li><li>Teste antes de publicar.</li><li>Envie os arquivos ao GitHub e use uma mensagem de commit clara.</li></ol><div class="help-actions"><button class="btn secondary" type="button" data-open-url="https://github.com/">Abrir GitHub</button><button class="btn secondary" type="button" data-open-url="https://vscode.dev/">Abrir VS Code Web</button></div><p>Nunca publique senhas, tokens, arquivos .env ou dados pessoais.</p></div>`;
  const storageHelp=()=>`<div class="help-flow"><h3>Upload ou perfil não funciona?</h3><ol><li>Confira se o arquivo existe e abre normalmente.</li><li>Verifique a conta escolar conectada.</li><li>Teste a internet.</li><li>Confira o espaço do Drive, Gmail e Google Fotos.</li><li>Mantenha um backup do perfil e das evidências.</li></ol><p>A conta escolar pode possuir 5 GB ou, no máximo, 15 GB. A plataforma não exclui arquivos automaticamente.</p></div>`;
  function privacyHelp(){const permissions=window.DS_Permissions?.list?.()||[];return `<div class="help-flow"><h3>Permissões e privacidade</h3><p>A plataforma não solicita câmera, microfone ou localização. As ações abaixo são iniciadas somente quando você escolhe usá-las.</p><div class="permission-summary-list">${permissions.map(item=>`<details><summary>${esc(item.label)} · ${item.required?'essencial':'opcional'}</summary><p><strong>Finalidade:</strong> ${esc(item.purpose)}</p><p><strong>Alternativa:</strong> ${esc(item.fallback)}</p><p><strong>Revogação:</strong> ${esc(item.revocation)}</p></details>`).join('')}</div><button class="btn secondary" type="button" id="openTermsFromHelp">Abrir termo e política</button></div>`;}
  function aboutHtml(){return `<section class="about-hero"><h3>${META.title}</h3><p>Plataforma educacional idealizada e desenvolvida pelo professor Gabriel com apoio de inteligência artificial, testes em sala e colaboração de estudantes e professores.</p></section><div class="about-grid"><article><h3>Créditos</h3><p><strong>Idealização, desenvolvimento pedagógico, coordenação e validação:</strong> ${META.lead}.</p><p><strong>Contexto:</strong> ${META.program}, ${META.institution}.</p><p><strong>Colaboração:</strong> estudantes do 1º, 2º e 3º DS, Técnico Subsequente noturno e professores colaboradores.</p></article><article><h3>Assistência tecnológica</h3><p>${META.ai.tool} — ${META.ai.model}</p><p>${META.ai.mode}. A direção pedagógica e a validação final são humanas.</p></article></div><div class="notice-card"><strong>Finalidade educacional</strong><p>XP e recompensas são virtuais, não possuem valor financeiro e não influenciam a nota. O diagnóstico orienta o aprendizado e não substitui avaliação clínica, psicológica ou médica.</p></div><h3>Histórico de versões</h3><div class="version-list">${META.changes.map(item=>`<details ${item.version===META.version?'open':''}><summary><strong>v${item.version}</strong> · ${item.date} — ${esc(item.title)}</summary><ul>${item.items.map(change=>`<li>${esc(change)}</li>`).join('')}</ul></details>`).join('')}</div><div class="limitations-card"><h3>Limitações do modo totalmente front-end</h3><ul><li>O navegador controla a persistência local.</li><li>Um usuário com controle total do navegador pode manipular o ambiente; a plataforma detecta inconsistências, mas não equivale a um servidor autoritativo.</li><li>Não existe confirmação real do Classroom sem API e autenticação.</li><li>Não há sincronização automática entre dispositivos.</li><li>A recuperação exige o arquivo administrativo correto.</li></ul></div>`;}
  function toolsHtml(){return `<section class="tool-catalog-intro"><h3>Conheça outras ferramentas</h3><p>As ferramentas aparecem pelo nome. Use o endereço atualizado informado pelo professor ou na atividade do Classroom.</p></section><div class="tool-catalog-grid">${TOOLS.map(tool=>`<article><span class="tool-status">${esc(tool.status)}</span><h3>${esc(tool.name)}</h3><p>${esc(tool.description)}</p><small>${tool.areas.map(esc).join(' · ')}</small>${tool.url?`<button class="btn secondary full" type="button" data-open-url="${esc(tool.url)}">Abrir ferramenta</button>`:'<div class="tool-access-note">Acesse pelo endereço informado na aula ou no Classroom.</div>'}</article>`).join('')}</div><h3>Carreiras relacionadas</h3><p class="career-note">Estas são conexões educacionais gerais. Vagas atuais precisam ser verificadas novamente em fontes oficiais.</p><div class="career-path-grid">${CAREERS.map(([title,skills,roles])=>`<article><h3>${esc(title)}</h3><p>${esc(skills)}</p><strong>${esc(roles)}</strong></article>`).join('')}</div>`;}
  function init(){inject();document.addEventListener('click',event=>{if(event.target?.id==='openTermsFromHelp')window.DS_Terms?.open?.();if(event.target?.matches?.('[data-open-classroom-selector]'))window.DS_Classroom?.open?.({source:'central-ajuda'});});}
  window.DS_PlatformShell={open,close,meta:META};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
