import { CinematicPostProcessController } from '../core/rendering/CinematicPostProcessController.js';
const VS=`#version 300 es
precision highp float;out vec2 v_uv;void main(){vec2 p=vec2((gl_VertexID<<1)&2,gl_VertexID&2);v_uv=p*.5;gl_Position=vec4(p*2.-1.,0,1);}`;
const FS=`#version 300 es
precision highp float;in vec2 v_uv;out vec4 outColor;uniform vec2 u_resolution;uniform float u_time,u_yaw,u_pitch,u_zoom,u_mode,u_steps,u_exposure,u_bloom,u_ao,u_dof,u_motion,u_particles;
float hash(vec3 p){p=fract(p*.1031);p+=dot(p,p.yzx+33.33);return fract((p.x+p.y)*p.z);}float noise(vec3 p){vec3 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(mix(hash(i),hash(i+vec3(1,0,0)),f.x),mix(hash(i+vec3(0,1,0)),hash(i+vec3(1,1,0)),f.x),f.y),mix(mix(hash(i+vec3(0,0,1)),hash(i+vec3(1,0,1)),f.x),mix(hash(i+vec3(0,1,1)),hash(i+vec3(1,1,1)),f.x),f.y),f.z);}float fbm(vec3 p){float s=0.,a=.5;for(int i=0;i<5;i++){s+=a*noise(p);p=p*2.03+1.7;a*=.5;}return s;}mat2 rot(float a){float c=cos(a),s=sin(a);return mat2(c,-s,s,c);}float sphere(vec3 p,float r){return length(p)-r;}float box(vec3 p,vec3 b){vec3 q=abs(p)-b;return length(max(q,0.))+min(max(q.x,max(q.y,q.z)),0.);}vec2 map(vec3 p){float d=100.;float mat=0.;if(u_mode<.5){float ground=p.y+1.;float tower=box(p-vec3(-2.,1.,0.),vec3(.25,2.,.25));float rocket=max(length(p.xz)-.45,abs(p.y-1.2)-2.2);d=min(ground,min(tower,rocket));mat=rocket<ground?1.:0.;}else if(u_mode<1.5){d=sphere(p,2.2);mat=2.;}else if(u_mode<2.5){d=min(p.y+1.,sphere(p-vec3(0,-.25,0),1.5));mat=3.;}else if(u_mode<3.5){float terrain=p.y+1.+fbm(p*.45)*.35;float rover=box(p-vec3(0,-.55,0),vec3(.9,.35,.55));d=min(terrain,rover);mat=4.;}else{d=100.;mat=5.;}return vec2(d,mat);}vec3 normal(vec3 p){float e=.002;return normalize(vec3(map(p+vec3(e,0,0)).x-map(p-vec3(e,0,0)).x,map(p+vec3(0,e,0)).x-map(p-vec3(0,e,0)).x,map(p+vec3(0,0,e)).x-map(p-vec3(0,0,e)).x));}
void main(){vec2 uv=v_uv*2.-1.;uv.x*=u_resolution.x/max(1.,u_resolution.y);uv*=u_zoom;vec3 ro=vec3(0,1.2,-6.5),rd=normalize(vec3(uv,1.4));rd.xz*=rot(u_yaw);rd.yz*=rot(u_pitch);vec3 col=vec3(.002,.006,.018);float t=0.,m=0.;int steps=int(u_steps);for(int i=0;i<110;i++){if(i>=steps)break;vec3 p=ro+rd*t;vec2 h=map(p);if(h.x<.002){m=h.y;vec3 n=normal(p),l=normalize(vec3(-.5,.8,-.4));float dif=max(dot(n,l),0.),rim=pow(1.-max(dot(n,-rd),0.),2.);vec3 base=m==1.?vec3(.72,.76,.82):m==2.?vec3(.04,.22,.65):m==3.?vec3(.56,.54,.5):m==4.?vec3(.65,.18,.06):vec3(.18,.2,.24);col=base*(.08+dif*.9)+rim*vec3(.15,.45,1.)+u_ao*.06;break;}t+=h.x*.72;if(t>35.)break;}float stars=step(.9985,hash(floor(rd*220.+u_time*.01)));col+=stars*u_particles;float neb=fbm(rd*3.+u_time*.01);col+=vec3(.08,.02,.18)*pow(neb,3.)*(u_mode>3.5?2.:.3);float glow=exp(-length(uv-vec2(.55,-.35))*3.)*u_bloom;col+=vec3(1.,.32,.06)*glow;col*=1.-length(uv)*u_dof*.08;col=mix(col,col+vec3(.04,.08,.15)*abs(sin(u_time*4.)),u_motion*.08);col*=1.-u_ao*.08*length(uv);col=vec3(1.)-exp(-col*u_exposure);col=pow(max(col,0.),vec3(1./2.2));outColor=vec4(col,1.);}`;
function makeShader(gl,type,source){const s=gl.createShader(type);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw new Error(gl.getShaderInfoLog(s)||'shader');return s;}function makeProgram(gl){const p=gl.createProgram(),v=makeShader(gl,gl.VERTEX_SHADER,VS),f=makeShader(gl,gl.FRAGMENT_SHADER,FS);gl.attachShader(p,v);gl.attachShader(p,f);gl.linkProgram(p);gl.deleteShader(v);gl.deleteShader(f);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw new Error(gl.getProgramInfoLog(p)||'link');return p;}
export class CinematicStudioRenderer{
 constructor(canvas,settingsStore,{onDiagnostics=()=>{}}={}){this.canvas=canvas;this.settingsStore=settingsStore;this.onDiagnostics=onDiagnostics;this.gl=null;this.ctx=null;this.program=null;this.raf=0;this.yaw=.2;this.pitch=-.08;this.zoom=1;this.mode=0;this.controller=new CinematicPostProcessController(settingsStore.getProfile().id);this.reducedMotion=settingsStore.get().reducedMotion;this.resize=()=>this.handleResize();this.lost=e=>{e.preventDefault();this.onDiagnostics({state:'context-lost'});};this.restored=()=>this.start();}
 start(){this.destroy(false);this.controller.setProfile(this.settingsStore.getProfile().id);this.reducedMotion=this.settingsStore.get().reducedMotion;this.gl=this.canvas.getContext('webgl2',{antialias:false,powerPreference:'high-performance'});if(!this.gl)return this.startFallback();try{this.program=makeProgram(this.gl);this.vao=this.gl.createVertexArray();this.gl.bindVertexArray(this.vao);}catch{return this.startFallback();}this.canvas.addEventListener('webglcontextlost',this.lost);this.canvas.addEventListener('webglcontextrestored',this.restored);addEventListener('resize',this.resize);this.handleResize();const draw=now=>{this.draw(now*.001);this.raf=requestAnimationFrame(draw);};this.raf=requestAnimationFrame(draw);this.onDiagnostics({state:'webgl2',...this.controller.budget()});}
 setScene(index){this.mode=Number(index)||0;} setCamera(yaw,pitch,zoom=1){this.yaw=yaw;this.pitch=pitch;this.zoom=zoom;} setCinema(v){return this.controller.setCinema(v);} setExposure(v){return this.controller.setExposure(v);} updateTelemetry(v){return this.controller.updateTelemetry(v);} profile(){return this.controller.snapshot();}
 draw(time){const gl=this.gl;if(!gl||!this.program)return;const s=this.controller.snapshot();gl.viewport(0,0,this.canvas.width,this.canvas.height);gl.useProgram(this.program);const u=(n)=>gl.getUniformLocation(this.program,n);gl.uniform2f(u('u_resolution'),this.canvas.width,this.canvas.height);for(const [name,val] of Object.entries({u_time:this.reducedMotion?0:time,u_yaw:this.yaw,u_pitch:this.pitch,u_zoom:this.zoom,u_mode:this.mode,u_steps:s.steps,u_exposure:s.exposure,u_bloom:s.bloom,u_ao:s.ao,u_dof:s.dof,u_motion:s.motion,u_particles:s.particles}))gl.uniform1f(u(name),val);gl.drawArrays(gl.TRIANGLES,0,3);}
 handleResize(){const p=this.settingsStore.getProfile(),scale=Math.min(2,devicePixelRatio||1)*p.renderScale;this.canvas.width=Math.max(2,Math.round(this.canvas.clientWidth*scale));this.canvas.height=Math.max(2,Math.round(this.canvas.clientHeight*scale));}
 startFallback(){this.gl=null;this.ctx=this.canvas.getContext('2d');addEventListener('resize',this.resize);this.handleResize();const draw=now=>{const c=this.ctx;if(!c)return;const w=this.canvas.width,h=this.canvas.height,g=c.createRadialGradient(w*.62,h*.38,0,w*.62,h*.38,w*.7);g.addColorStop(0,'#20498c');g.addColorStop(.25,'#121d45');g.addColorStop(1,'#02040d');c.fillStyle=g;c.fillRect(0,0,w,h);c.fillStyle='rgba(255,255,255,.7)';for(let i=0;i<90;i++){const x=(i*83)%w,y=(i*47)%h;c.fillRect(x,y,i%7===0?2:1,i%7===0?2:1);}c.fillStyle='#dce8ff';c.font=`${Math.max(14,w/40)}px sans-serif`;c.fillText('Modo compatível 2D · iluminação cinematográfica',24,h-32);this.raf=requestAnimationFrame(draw);};this.raf=requestAnimationFrame(draw);this.onDiagnostics({state:'canvas2d'});}
 resize(){this.handleResize();}
 requestFullscreen(){return this.canvas.parentElement?.requestFullscreen?.();}
 destroy(remove=true){cancelAnimationFrame(this.raf);removeEventListener('resize',this.resize);this.canvas?.removeEventListener('webglcontextlost',this.lost);this.canvas?.removeEventListener('webglcontextrestored',this.restored);if(this.gl){if(this.vao)this.gl.deleteVertexArray(this.vao);if(this.program)this.gl.deleteProgram(this.program);}this.gl=null;this.ctx=null;this.program=null;this.vao=null;if(remove)this.onDiagnostics({state:'destroyed'});}
}
