const clamp=(value,min,max)=>Math.min(max,Math.max(min,value));

export class MarsSceneRenderer {
  constructor(canvas,settingsStore){
    this.canvas=canvas;this.settingsStore=settingsStore;this.gl=null;this.ctx=null;this.program=null;this.vao=null;this.raf=0;this.startTime=performance.now();
    this.yaw=.25;this.pitch=-.08;this.zoom=1;this.drag=null;this.telemetry={position:{x:0,y:11},battery:100,wheelSlip:0,stormLevel:0,state:'READY',armState:'STOWED'};this.route=[];
    this.onPointerDown=e=>this.pointerDown(e);this.onPointerMove=e=>this.pointerMove(e);this.onPointerUp=()=>{this.drag=null;};this.onWheel=e=>this.wheel(e);this.onResize=()=>this.resize();
    if(!this.initWebGL())this.ctx=this.canvas.getContext('2d');
    this.resizeObserver=typeof ResizeObserver!=='undefined'?new ResizeObserver(()=>this.resize()):null;this.resizeObserver?.observe(canvas);if(!this.resizeObserver)addEventListener('resize',this.onResize);
    canvas.addEventListener('pointerdown',this.onPointerDown);addEventListener('pointermove',this.onPointerMove);addEventListener('pointerup',this.onPointerUp);canvas.addEventListener('wheel',this.onWheel,{passive:false});this.resize();
  }
  initWebGL(){
    const gl=this.canvas.getContext('webgl2',{antialias:false,alpha:false,powerPreference:'high-performance'});if(!gl)return false;
    const vertex=`#version 300 es
      in vec2 a_position;out vec2 v_uv;void main(){v_uv=a_position*.5+.5;gl_Position=vec4(a_position,0.,1.);}`;
    const fragment=`#version 300 es
      precision highp float;in vec2 v_uv;out vec4 outColor;
      uniform vec2 u_resolution;uniform float u_time;uniform float u_yaw;uniform float u_pitch;uniform float u_zoom;uniform vec2 u_rover;uniform float u_slip;uniform float u_storm;uniform float u_quality;uniform float u_motion;uniform float u_arm;
      mat2 rot(float a){float c=cos(a),s=sin(a);return mat2(c,-s,s,c);}float hash21(vec2 p){p=fract(p*vec2(123.34,456.21));p+=dot(p,p+45.32);return fract(p.x*p.y);}float noise(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(hash21(i),hash21(i+vec2(1,0)),f.x),mix(hash21(i+vec2(0,1)),hash21(i+vec2(1)),f.x),f.y);}float fbm(vec2 p){float v=0.,a=.5;for(int i=0;i<5;i++){v+=a*noise(p);p=p*2.03+17.1;a*=.5;}return v;}
      float terrain(vec2 p){float h=(fbm(p*.04)-.5)*7.;h+=(fbm(p*.17)-.5)*2.;float ridge=abs(sin(p.x*.025+p.y*.018))*1.8;return h+ridge;}
      float sdBox(vec3 p,vec3 b){vec3 q=abs(p)-b;return length(max(q,0.))+min(max(q.x,max(q.y,q.z)),0.);}
      float sdCapsule(vec3 p,vec3 a,vec3 b,float r){vec3 pa=p-a,ba=b-a;float h=clamp(dot(pa,ba)/dot(ba,ba),0.,1.);return length(pa-ba*h)-r;}
      float rover(vec3 p){vec3 q=p-vec3((u_rover.x-5.5)*2.3,terrain(vec2((u_rover.x-5.5)*2.3,(u_rover.y-5.5)*2.3))+1.45,(u_rover.y-5.5)*2.3);q.xz*=rot(u_yaw*.08);float body=sdBox(q-vec3(0,.2,0),vec3(1.35,.42,.9));float deck=sdBox(q-vec3(0,.8,0),vec3(.95,.22,.68));float mast=sdCapsule(q,vec3(.2,.95,0),vec3(.2,2.1,0),.12);float head=sdBox(q-vec3(.2,2.15,0),vec3(.38,.22,.26));float wheels=1e4;for(int i=0;i<3;i++){float z=-.72+float(i)*.72;for(int s=-1;s<=1;s+=2){vec3 w=q-vec3(float(s)*1.45,-.18,z);w.yz*=rot(1.5708);w.xz*=rot(u_slip*.12*sin(u_time*12.*u_motion));wheels=min(wheels,max(length(w.yz)-.34,abs(w.x)-.18));}}float arm=1e4;if(u_arm>.5){arm=min(sdCapsule(q,vec3(.8,.72,-.2),vec3(1.9,.35,-.55),.1),sdCapsule(q,vec3(1.9,.35,-.55),vec3(2.45,.05,-.85),.09));}return min(min(body,deck),min(min(mast,head),min(wheels,arm)));}
      float mapScene(vec3 p){return min(p.y-terrain(p.xz),rover(p));}
      vec3 normalAt(vec3 p){vec2 e=vec2(.025,0);float d=mapScene(p);return normalize(vec3(mapScene(p+e.xyy)-d,mapScene(p+e.yxy)-d,mapScene(p+e.yyx)-d));}
      float march(vec3 ro,vec3 rd,out vec3 p){float t=0.;int steps=int(mix(54.,108.,u_quality));for(int i=0;i<116;i++){if(i>=steps)break;p=ro+rd*t;float d=mapScene(p);if(abs(d)<.018||t>180.)break;t+=max(.018,d*.62);}return t;}
      void main(){vec2 uv=(gl_FragCoord.xy-.5*u_resolution)/u_resolution.y;uv/=u_zoom;vec3 ro=vec3(sin(u_yaw)*34.,11.+u_pitch*22.,cos(u_yaw)*34.);vec3 ta=vec3(0,1.5,0);vec3 f=normalize(ta-ro),r=normalize(cross(f,vec3(0,1,0))),u=cross(r,f);vec3 rd=normalize(f+uv.x*r+uv.y*u);vec3 p;float t=march(ro,rd,p);vec3 sun=normalize(vec3(-.65,.5,.25));float sky=max(0.,rd.y);vec3 col=mix(vec3(.055,.018,.012),vec3(.34,.075,.028),pow(sky,.45));if(t<180.){vec3 n=normalAt(p);float diff=max(0.,dot(n,sun));float rock=.45+.28*noise(p.xz*.6)+.1*noise(p.xz*3.);vec3 ground=vec3(.58,.22,.095)*rock*(.32+diff*.9);float metal=smoothstep(.3,1.,p.y-terrain(p.xz));vec3 machine=vec3(.66,.64,.52)*(.2+diff*.9)+vec3(.05,.1,.13)*pow(1.-max(0.,dot(n,-rd)),3.);col=mix(ground,machine,metal);}
      float dust=fbm(uv*vec2(10.,4.)+vec2(u_time*.18*u_motion,0.));dust*=smoothstep(.25,.95,u_storm)*(.22+.65*smoothstep(-.3,.35,uv.y));col=mix(col,vec3(.62,.25,.09),dust*u_storm*.62);float tracks=smoothstep(.035,0.,abs(uv.x+.18*sin(uv.y*8.)))*smoothstep(-.5,.05,uv.y);col-=vec3(.06,.025,.01)*tracks*u_slip;col*=1.-dot(v_uv-.5,v_uv-.5)*.55;col=pow(max(col,0.),vec3(.82));outColor=vec4(col,1.);}`;
    const compile=(type,source)=>{const shader=gl.createShader(type);gl.shaderSource(shader,source);gl.compileShader(shader);if(!gl.getShaderParameter(shader,gl.COMPILE_STATUS))throw new Error(gl.getShaderInfoLog(shader));return shader;};
    try{const program=gl.createProgram();gl.attachShader(program,compile(gl.VERTEX_SHADER,vertex));gl.attachShader(program,compile(gl.FRAGMENT_SHADER,fragment));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw new Error(gl.getProgramInfoLog(program));const vao=gl.createVertexArray();gl.bindVertexArray(vao);const buffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,3,-1,-1,3]),gl.STATIC_DRAW);const loc=gl.getAttribLocation(program,'a_position');gl.enableVertexAttribArray(loc);gl.vertexAttribPointer(loc,2,gl.FLOAT,false,0,0);this.gl=gl;this.program=program;this.vao=vao;return true;}catch(error){console.warn('Renderizador de Marte WebGL2 indisponível.',error);return false;}
  }
  setTelemetry(payload){this.telemetry={...this.telemetry,...payload};}
  setRoute(route){this.route=route??[];}
  pointerDown(event){this.drag={x:event.clientX,y:event.clientY,yaw:this.yaw,pitch:this.pitch};this.canvas.setPointerCapture?.(event.pointerId);}
  pointerMove(event){if(!this.drag)return;this.yaw=this.drag.yaw+(event.clientX-this.drag.x)*.006;this.pitch=clamp(this.drag.pitch+(event.clientY-this.drag.y)*.005,-.42,.4);}
  wheel(event){event.preventDefault();this.zoom=clamp(this.zoom+Math.sign(event.deltaY)*.08,.65,1.5);}
  resize(){const rect=this.canvas.getBoundingClientRect();const profile=this.settingsStore.getProfile();const dpr=devicePixelRatio||1;const scale=profile.id==='performance'?.56:profile.id==='experience'?Math.min(1.45,dpr):Math.min(.95,dpr);this.canvas.width=Math.max(1,Math.round(rect.width*scale));this.canvas.height=Math.max(1,Math.round(rect.height*scale));this.gl?.viewport(0,0,this.canvas.width,this.canvas.height);}
  start(){cancelAnimationFrame(this.raf);this.startTime=performance.now();this.loop();}
  loop=()=>{this.draw();this.raf=requestAnimationFrame(this.loop);};
  draw(){
    const profile=this.settingsStore.getProfile(),settings=this.settingsStore.get(),elapsed=(performance.now()-this.startTime)/1000;
    if(this.gl){const gl=this.gl;gl.useProgram(this.program);gl.bindVertexArray(this.vao);gl.uniform2f(gl.getUniformLocation(this.program,'u_resolution'),this.canvas.width,this.canvas.height);const one=(name,value)=>gl.uniform1f(gl.getUniformLocation(this.program,name),value);one('u_time',settings.reducedMotion?0:elapsed);one('u_yaw',this.yaw);one('u_pitch',this.pitch);one('u_zoom',this.zoom);gl.uniform2f(gl.getUniformLocation(this.program,'u_rover'),this.telemetry.position?.x??0,this.telemetry.position?.y??11);one('u_slip',this.telemetry.wheelSlip??0);one('u_storm',this.telemetry.stormLevel??0);one('u_quality',profile.id==='performance'?.08:profile.id==='experience'?1:.52);one('u_motion',settings.reducedMotion?0:profile.motionFactor);one('u_arm',this.telemetry.armState==='DEPLOYED'?1:0);gl.drawArrays(gl.TRIANGLES,0,3);return;}
    if(!this.ctx)return;const ctx=this.ctx,w=this.canvas.width,h=this.canvas.height;ctx.fillStyle='#170704';ctx.fillRect(0,0,w,h);const sky=ctx.createLinearGradient(0,0,0,h*.68);sky.addColorStop(0,'#16050a');sky.addColorStop(1,'#a63d19');ctx.fillStyle=sky;ctx.fillRect(0,0,w,h*.7);ctx.fillStyle='#77311e';ctx.beginPath();ctx.moveTo(0,h*.62);for(let x=0;x<=w;x+=18)ctx.lineTo(x,h*.61+Math.sin(x*.019)*18+Math.sin(x*.047)*7);ctx.lineTo(w,h);ctx.lineTo(0,h);ctx.fill();const cx=w*.5,cy=h*.58,s=Math.min(w,h)*.09;ctx.fillStyle='#b9b18f';ctx.fillRect(cx-s,cy-s*.5,s*2,s*.7);ctx.fillStyle='#75818a';ctx.fillRect(cx-s*.6,cy-s*1.1,s*1.2,s*.55);ctx.strokeStyle='#cdd2c2';ctx.lineWidth=4;for(const side of [-1,1])for(let i=-1;i<=1;i++){ctx.beginPath();ctx.arc(cx+side*s*1.1,cy+i*s*.32,s*.25,0,Math.PI*2);ctx.stroke();}if((this.telemetry.stormLevel??0)>.3){ctx.fillStyle=`rgba(190,80,30,${this.telemetry.stormLevel*.35})`;ctx.fillRect(0,0,w,h);}}
  destroy(){cancelAnimationFrame(this.raf);this.resizeObserver?.disconnect();if(!this.resizeObserver)removeEventListener('resize',this.onResize);this.canvas.removeEventListener('pointerdown',this.onPointerDown);removeEventListener('pointermove',this.onPointerMove);removeEventListener('pointerup',this.onPointerUp);this.canvas.removeEventListener('wheel',this.onWheel);if(this.gl&&this.program)this.gl.deleteProgram(this.program);this.gl=null;this.ctx=null;}
}
