(function(){
'use strict';const Core=()=>window.DS_EduAuthCore;let modal=null,active=null,timer=null;function attemptKey(req){return 'ds_eduauth_attempts_'+String(req.code||'').replace(/[^A-Z0-9]/gi,'').slice(-80);}
function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function ensure(){if(modal)return;modal=document.createElement('div');modal.id='eduauthModal';modal.className='modal-overlay hidden';modal.setAttribute('role','dialog');modal.setAttribute('aria-modal','true');modal.setAttribute('aria-labelledby','eduauthTitle');modal.innerHTML=`<div class="modal-card eduauth-card"><div class="eduauth-head"><div><span class="modal-kicker">EDUAUTH OFFLINE</span><h2 id="eduauthTitle">Autorização do professor</h2></div><button id="eduauthClose" class="btn ghost" type="button">Cancelar</button></div><div id="eduauthDev" class="eduauth-dev">${Core().CFG.productionProvisioned?'Proteção operacional offline ativa. A autorização é válida somente para o contexto exibido.':'Ambiente de desenvolvimento — não utilizar em atividade real.'}</div><div id="eduauthContext" class="eduauth-context"></div><div class="eduauth-code-wrap"><label>Código-base público</label><output id="eduauthCode" class="eduauth-code"></output><div class="eduauth-code-actions"><button id="eduauthCopy" class="btn secondary" type="button">Copiar código</button><button id="eduauthQr" class="btn ghost" type="button">Mostrar QR Code</button><button id="eduauthNew" class="btn ghost" type="button">Nova solicitação</button></div></div><div id="eduauthQrPanel" class="eduauth-qr hidden"></div><div id="eduauthInputArea"></div><p id="eduauthStatus" class="mode-status" aria-live="polite"></p><div class="eduauth-foot"><span id="eduauthCountdown"></span><span id="eduauthAttempts"></span></div></div>`;document.body.appendChild(modal);modal.querySelector('#eduauthClose').onclick=()=>finish(false,new Error('Autorização cancelada.'));modal.querySelector('#eduauthCopy').onclick=copy;modal.querySelector('#eduauthQr').onclick=toggleQr;modal.querySelector('#eduauthNew').onclick=renew;}
function status(text,type=''){const n=modal.querySelector('#eduauthStatus');n.textContent=text;n.className='mode-status '+type;}
function contextHtml(req){const d=Core().describe(req);return `<dl><div><dt>Modalidade</dt><dd>${escapeHtml(d.modeLabel)}</dd></div><div><dt>Risco</dt><dd>${escapeHtml(d.risk)}</dd></div><div><dt>Turma</dt><dd>${escapeHtml(d.classLabel)}</dd></div><div><dt>Disciplina</dt><dd>${escapeHtml(d.subjectLabel)}</dd></div><div><dt>Recurso</dt><dd>${escapeHtml(d.lessonLabel)}</dd></div><div><dt>Ação</dt><dd>${escapeHtml(d.actionLabel)}</dd></div></dl>`;}
async function authorize(options){ensure();if(active)finish(false,new Error('Nova solicitação iniciada.'));const req=await Core().buildRequest(options);return new Promise((resolve,reject)=>{active={options,req,resolve,reject,attempts:Number(sessionStorage.getItem(attemptKey(req))||0),lockedUntil:0};render();Core().audit('request_created',req,{risk:req.action.risk});});}
function render(){const {req}=active;modal.classList.remove('hidden');modal.querySelector('#eduauthContext').innerHTML=contextHtml(req);modal.querySelector('#eduauthCode').textContent=req.code;modal.querySelector('#eduauthQrPanel').classList.add('hidden');modal.querySelector('#eduauthQrPanel').innerHTML='';const area=modal.querySelector('#eduauthInputArea');if(req.mode==='SIGNED_GRANT'||req.mode==='PROFILE_RECOVERY_ENVELOPE'){area.innerHTML=`<label for="eduauthGrant">Autorização assinada</label><textarea id="eduauthGrant" rows="4" placeholder="Cole o token EA1-G1 gerado pelo EduAuth Professor"></textarea><button id="eduauthValidate" class="btn primary full" type="button">Verificar autorização assinada</button>`;}else{const len=req.action.pinLength||8;area.innerHTML=`<label for="eduauthPin">Senha temporária do professor</label><input id="eduauthPin" inputmode="numeric" autocomplete="one-time-code" maxlength="${len+2}" placeholder="${len===10?'00000 00000':'0000 0000'}"><button id="eduauthValidate" class="btn primary full" type="button">Validar autorização</button>`;}area.querySelector('#eduauthValidate').onclick=validate;const input=area.querySelector('input,textarea');input.onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();validate();}};if(active.attempts>=Core().CFG.security.maximumAttempts){area.querySelector('#eduauthValidate').disabled=true;input.disabled=true;status('Limite de tentativas atingido. Gere uma nova solicitação.','bad');}else status('Informe o código-base ao professor e aguarde a senha temporária.');updateAttempts();clearInterval(timer);timer=setInterval(tick,1000);tick();setTimeout(()=>input.focus(),50);}
function tick(){if(!active)return;const left=Math.max(0,active.req.expiresAt-Math.floor(Date.now()/1000));modal.querySelector('#eduauthCountdown').textContent=`Validade: ${Math.floor(left/60).toString().padStart(2,'0')}:${(left%60).toString().padStart(2,'0')}`;if(left<=0){status('Solicitação expirada. Gere uma nova.','bad');modal.querySelector('#eduauthValidate').disabled=true;}}
function updateAttempts(){modal.querySelector('#eduauthAttempts').textContent=`Tentativas: ${Math.max(0,Core().CFG.security.maximumAttempts-active.attempts)}`;}
async function validate(){if(!active)return;const now=Date.now();if(now<active.lockedUntil)return status(`Aguarde ${Math.ceil((active.lockedUntil-now)/1000)} segundo(s).`,'warn');const btn=modal.querySelector('#eduauthValidate');btn.disabled=true;status('Validando o código, a sessão e a ação…','warn');try{let grant;if(active.req.mode==='SIGNED_GRANT'||active.req.mode==='PROFILE_RECOVERY_ENVELOPE'){grant=await Core().verifySignedGrant(active.req,modal.querySelector('#eduauthGrant').value);}else{const ok=await Core().verifyPin(active.req,modal.querySelector('#eduauthPin').value);if(!ok)throw new Error('Código inválido, expirado ou pertencente a outra solicitação.');grant={mode:active.req.mode,actionId:active.req.context.actionId,resourceId:active.req.context.resourceId,grantedAt:Date.now(),expiresAt:active.req.expiresAt};}await Core().audit('authorization_granted',active.req,{attempts:active.attempts+1});status('Autorização confirmada e limitada a esta ação.','ok');setTimeout(()=>finish(true,grant),450);}catch(error){active.attempts++;sessionStorage.setItem(attemptKey(active.req),String(active.attempts));await Core().audit('authorization_denied',active.req,{attempts:active.attempts,error:'invalid_or_expired'});updateAttempts();if(active.attempts>=Core().CFG.security.maximumAttempts){status('Limite de tentativas atingido. Gere uma nova solicitação.','bad');sessionStorage.setItem('ds_eduauth_consumed_'+active.req.requestTag,'1');}else{const delay=[0,1000,2000,4000,8000][active.attempts]||8000;active.lockedUntil=Date.now()+delay;status('Código inválido, expirado ou pertencente a outra solicitação.','bad');btn.disabled=false;}}finally{if(active&&active.attempts<Core().CFG.security.maximumAttempts)btn.disabled=false;}}
async function copy(){if(!active)return;try{const result=await window.DS_Permissions?.explain?.('clipboard-write',()=>navigator.clipboard.writeText(active.req.code));if(result?.allowed)status('Código-base copiado.','ok');else throw new Error('cópia cancelada');}catch(e){const r=document.createRange();r.selectNodeContents(modal.querySelector('#eduauthCode'));getSelection().removeAllRanges();getSelection().addRange(r);status('Selecione e copie o código-base.','warn');}}
function toggleQr(){if(!active)return;const p=modal.querySelector('#eduauthQrPanel');if(!p.classList.contains('hidden')){p.classList.add('hidden');return;}p.innerHTML=Core().qrSvg(active.req.code)||'<p>QR Code indisponível neste navegador. Utilize copiar e colar.</p>';p.classList.remove('hidden');}
async function renew(){if(!active)return;try{const req=await Core().buildRequest(active.options);active.req=req;active.attempts=Number(sessionStorage.getItem(attemptKey(req))||0);active.lockedUntil=0;render();await Core().audit('request_renewed',req,{risk:req.action.risk});}catch(error){status(error?.message||'Não foi possível gerar nova solicitação.','bad');}}
function finish(ok,value){if(!active)return;const a=active;active=null;clearInterval(timer);modal.classList.add('hidden');modal.querySelector('#eduauthQrPanel').innerHTML='';ok?a.resolve(value):a.reject(value instanceof Error?value:new Error(String(value||'Cancelado')));}
window.DS_EduAuth={authorize,decodeRequestCode:(c)=>Core().decodeRequestCode(c),calculatePin:(r)=>Core().calculatePin(r),environment:Core().CFG.environment,productionProvisioned:Core().CFG.productionProvisioned};
})();
