import {
  INTERDISCIPLINARY_PROJECTS,CAREER_SIMULATIONS,SOURCE_RELIABILITY_CRITERIA,SOURCE_RELIABILITY_CASES,
  PROJECT_COMPETENCIES,EXHIBITION_THEMES,PROJECT_PORTFOLIO_ARTIFACT_TYPES,PROJECT_STAGES,PROJECT_CURATION_GOALS
} from '../../data/interdisciplinaryProjectSystems.js';
import { ProjectCurationEngine } from '../../core/projects/ProjectCurationEngine.js';
import { SourceReliabilityEngine } from '../../core/projects/SourceReliabilityEngine.js';
import { StudentPortfolioStore } from '../../core/projects/StudentPortfolioStore.js';
import { DigitalExhibitionRenderer } from '../../rendering/DigitalExhibitionRenderer.js';

const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const download=(name,text,type='application/json')=>{const blob=new Blob([text],{type}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1200);};
const stageLabel=id=>PROJECT_STAGES.find(item=>item.id===id)?.label||id;
const artifactType=id=>PROJECT_PORTFOLIO_ARTIFACT_TYPES.find(item=>item.id===id)?.label||id;

class ProjectCurationStudioModule {
  constructor(){
    this.container=null;this.context=null;this.store=null;this.renderer=null;
    this.engine=new ProjectCurationEngine({projects:INTERDISCIPLINARY_PROJECTS,careers:CAREER_SIMULATIONS,sources:SOURCE_RELIABILITY_CASES,competencies:PROJECT_COMPETENCIES,themes:EXHIBITION_THEMES});
    this.sourceEngine=new SourceReliabilityEngine(SOURCE_RELIABILITY_CRITERIA);
    this.tab='projects';this.selectedProjectId=INTERDISCIPLINARY_PROJECTS[0].id;this.selectedCareerId=CAREER_SIMULATIONS[0].id;this.selectedSourceId=SOURCE_RELIABILITY_CASES[0].id;
    this.onClick=e=>this.handleClick(e);this.onChange=e=>this.handleChange(e);this.onInput=e=>this.handleInput(e);this.onSubmit=e=>this.handleSubmit(e);
  }
  mount(container,context){this.container=container;this.context=context;this.store=new StudentPortfolioStore(context.profileStore.storage,context.profileStore.active().id);const state=this.store.snapshot();this.selectedProjectId=state.activeProjectId||this.selectedProjectId;this.selectedCareerId=state.activeRoleId||this.selectedCareerId;container.addEventListener('click',this.onClick);container.addEventListener('change',this.onChange);container.addEventListener('input',this.onInput);container.addEventListener('submit',this.onSubmit);this.store.visitTab(this.tab);this.render();}
  unmount(){this.renderer?.destroy();this.container?.removeEventListener('click',this.onClick);this.container?.removeEventListener('change',this.onChange);this.container?.removeEventListener('input',this.onInput);this.container?.removeEventListener('submit',this.onSubmit);}
  state(){return this.store.snapshot();}
  render(){this.renderer?.destroy();this.renderer=null;const state=this.state(),completion=this.engine.completion(state);this.container.innerHTML=`<section class="project-curation-studio">
    <header class="project-hero"><div><span class="eyebrow">Fase C5.2 · Projetos, profissões e curadoria científica</span><h2>Transforme descobertas em <span>projetos, portfólio e exposição.</span></h2><p>Experimente profissões, verifique fontes, documente competências e publique uma pequena mostra digital sem depender de mídias externas.</p></div><div class="project-hero-actions"><button class="button secondary" data-action="back">← Portal leve</button><button class="button secondary" data-action="open-culture">Cultura e carreiras</button><button class="button primary" data-action="export-evidence">Exportar evidência</button></div></header>
    <section class="project-progress-strip"><div><b>${completion.projectStages}%</b><span>projeto</span></div><div><b>${completion.career}</b><span>simulações</span></div><div><b>${completion.sourceReviews}</b><span>fontes avaliadas</span></div><div><b>${completion.portfolio}</b><span>itens no portfólio</span></div><div><b>${completion.exhibition}</b><span>peças na exposição</span></div></section>
    <nav class="project-tabs">${[['projects','Projetos'],['careers','Simular carreira'],['sources','Curadoria de fontes'],['portfolio','Portfólio'],['exhibition','Exposição digital']].map(([id,label])=>`<button class="${this.tab===id?'active':''}" data-action="tab" data-tab="${id}">${label}</button>`).join('')}</nav>
    <main>${this.tab==='projects'?this.projectsMarkup(state):this.tab==='careers'?this.careersMarkup(state):this.tab==='sources'?this.sourcesMarkup(state):this.tab==='portfolio'?this.portfolioMarkup(state):this.exhibitionMarkup(state)}</main>
  </section>`;if(this.tab==='exhibition')this.startRenderer();}
  projectsMarkup(state){const project=this.engine.project(this.selectedProjectId)||INTERDISCIPLINARY_PROJECTS[0],done=state.projectStages[project.id]||[],roles=this.engine.compatibleCareers(project.id);return `<section class="project-workspace"><aside class="project-card-rail">${INTERDISCIPLINARY_PROJECTS.map(item=>`<button class="project-brief-card ${item.id===project.id?'selected':''}" data-action="select-project" data-id="${item.id}"><i>${item.icon}</i><span><small>${esc(item.area)}</small><b>${esc(item.title)}</b><em>${esc(item.duration)}</em></span></button>`).join('')}</aside><article class="project-detail-panel"><span class="eyebrow">PROJETO INTERDISCIPLINAR · ${esc(project.area)}</span><h3>${esc(project.title)}</h3><p>${esc(project.summary)}</p><section class="project-question"><b>DESAFIO CENTRAL</b><p>${esc(project.challenge)}</p></section><div class="project-columns"><div><h4>Possíveis funções</h4><div class="project-chip-row">${roles.map(role=>`<button data-action="choose-role" data-id="${role.id}">${role.icon} ${esc(role.name)}</button>`).join('')}</div><h4>Laboratórios relacionados</h4><div class="project-chip-row">${project.modules.map(module=>`<button data-action="open-module" data-module="${module}">${esc(this.context.moduleRegistry.definition(module)?.title||module)}</button>`).join('')}</div></div><div><h4>Entregas sugeridas</h4><ul>${project.deliverables.map(value=>`<li>${esc(value)}</li>`).join('')}</ul><h4>Competências</h4><div class="project-competency-row">${project.competencies.map(id=>`<span>${esc(PROJECT_COMPETENCIES.find(item=>item.id===id)?.label||id)}</span>`).join('')}</div></div></div><h4>Etapas do projeto</h4><div class="project-stage-grid">${project.stages.map((stage,index)=>`<button class="${done.includes(stage)?'done':''}" data-action="toggle-stage" data-stage="${stage}"><span>${done.includes(stage)?'✓':index+1}</span><b>${esc(stageLabel(stage))}</b><small>${done.includes(stage)?'Etapa registrada':'Toque para registrar'}</small></button>`).join('')}</div><label class="project-note-field"><span>Registro do projeto</span><textarea data-project-note="${project.id}" rows="5" maxlength="1800" placeholder="Problema, decisões, dados, testes e próximos passos…">${esc(state.projectNotes[project.id]||'')}</textarea></label><div class="project-actions"><button class="button secondary" data-action="save-project-note">Salvar registro</button><button class="button primary" data-action="add-project-artifact">Adicionar ao portfólio</button></div></article></section>`;}
  careersMarkup(state){const career=this.engine.career(this.selectedCareerId)||CAREER_SIMULATIONS[0],decision=state.careerDecisions[career.id];return `<section class="career-simulation-layout"><aside class="career-simulation-list">${CAREER_SIMULATIONS.map(item=>`<button class="${item.id===career.id?'selected':''}" data-action="select-career" data-id="${item.id}"><i>${item.icon}</i><span><small>${esc(item.area)}</small><b>${esc(item.name)}</b></span>${state.careerDecisions[item.id]?'<em>✓</em>':''}</button>`).join('')}</aside><article class="career-simulation-panel"><span class="eyebrow">SIMULAÇÃO DE PROFISSÃO · ${esc(career.area)}</span><h3>${career.icon} ${esc(career.name)}</h3><p>${esc(career.summary)}</p><div class="project-competency-row">${career.skills.map(value=>`<span>${esc(value)}</span>`).join('')}</div><section class="career-scenario"><b>CENÁRIO</b><p>${esc(career.scenario)}</p></section><div class="career-choice-grid">${career.choices.map(choice=>`<button class="${decision?.choiceId===choice.id?'selected':''}" data-action="career-choice" data-choice="${choice.id}"><b>${esc(choice.label)}</b><small>Tomar esta decisão</small></button>`).join('')}</div>${decision?`<section class="career-feedback ${decision.score===3?'excellent':decision.score?'partial':'risk'}"><b>${decision.score===3?'Decisão consistente':decision.score?'Decisão parcial':'Decisão de alto risco'}</b><p>${esc(decision.feedback)}</p><span>${decision.score}/3 pontos de qualidade técnica</span></section>`:''}<h4>Experimente nos laboratórios</h4><div class="project-chip-row">${career.modules.map(module=>`<button data-action="open-module" data-module="${module}">${esc(this.context.moduleRegistry.definition(module)?.title||module)}</button>`).join('')}</div></article></section>`;}
  sourcesMarkup(state){const source=this.engine.source(this.selectedSourceId)||SOURCE_RELIABILITY_CASES[0],review=state.sourceReviews[source.id]||{},ratings=review.ratings||{};return `<section class="source-curation-layout"><aside class="source-case-list">${SOURCE_RELIABILITY_CASES.map(item=>`<button class="${item.id===source.id?'selected':''}" data-action="select-source" data-id="${item.id}"><span>${item.expectedBand==='alta'?'◎':item.expectedBand==='média'?'◐':'△'}</span><div><small>${esc(item.kind)}</small><b>${esc(item.title)}</b></div>${state.sourceReviews[item.id]?'<em>✓</em>':''}</button>`).join('')}</aside><article class="source-review-panel"><span class="eyebrow">CURADORIA CIENTÍFICA · CASO DIDÁTICO</span><h3>${esc(source.title)}</h3><p>${esc(source.summary)}</p><div class="source-clues">${source.clues.map(value=>`<span>${esc(value)}</span>`).join('')}</div><form data-form="source-review"><input type="hidden" name="sourceId" value="${source.id}"><div class="source-rubric">${SOURCE_RELIABILITY_CRITERIA.map(criterion=>`<label><span><b>${esc(criterion.label)}</b><small>${esc(criterion.question)}</small></span><select name="${criterion.id}" data-source-rating="${criterion.id}">${[0,1,2,3,4].map(value=>`<option value="${value}" ${Number(ratings[criterion.id])===value?'selected':''}>${value} · ${['não atende','fraco','parcial','bom','muito bom'][value]}</option>`).join('')}</select></label>`).join('')}</div><button class="button primary" type="submit">Avaliar confiabilidade</button></form>${review.score!==undefined?`<section class="source-score ${review.band}"><div><b>${review.score}</b><span>/100</span></div><p><strong>Faixa calculada: ${esc(review.band)}</strong><br>${esc(review.feedback)} ${review.matched?'Sua avaliação ficou próxima do diagnóstico esperado.':'Compare as pistas e revise os critérios.'}</p></section>`:''}<small class="source-policy">Os casos são exemplos didáticos locais. Em uma pesquisa real, abra a fonte original, verifique autoria, data, método, contexto e confirmação independente.</small></article></section>`;}
  portfolioMarkup(state){return `<section class="portfolio-layout"><article class="portfolio-form-card"><span class="eyebrow">PORTFÓLIO DO ESTUDANTE</span><h3>Registre o que você produziu e aprendeu</h3><form data-form="portfolio-artifact"><label>Título<input name="title" maxlength="100" required placeholder="Ex.: Painel de telemetria da missão"></label><label>Tipo<select name="type">${PROJECT_PORTFOLIO_ARTIFACT_TYPES.map(item=>`<option value="${item.id}">${esc(item.label)}</option>`).join('')}</select></label><label>Laboratório ou origem<select name="moduleId"><option value="project-curation-studio">Estúdio de Projetos</option>${this.context.moduleRegistry.list().filter(item=>item.status==='available').map(item=>`<option value="${item.id}">${esc(item.title)}</option>`).join('')}</select></label><label>Resumo ou reflexão<textarea name="reflection" rows="5" maxlength="1500" required placeholder="O que foi feito? Que decisão você tomou? O que aprendeu?"></textarea></label><fieldset><legend>Competências demonstradas</legend><div class="portfolio-competency-grid">${PROJECT_COMPETENCIES.map(item=>`<label><input type="checkbox" name="competencies" value="${item.id}"><span>${esc(item.label)}</span></label>`).join('')}</div></fieldset><button class="button primary" type="submit">Adicionar ao portfólio</button></form></article><section class="portfolio-gallery"><div class="project-section-head"><div><span class="eyebrow">COLEÇÃO LOCAL</span><h3>${state.portfolio.length} itens registrados</h3></div><button class="button secondary" data-action="export-portfolio">Exportar portfólio</button></div>${state.portfolio.length?`<div class="portfolio-card-grid">${[...state.portfolio].reverse().map(item=>`<article><header><span>${esc(artifactType(item.type))}</span><button data-action="remove-artifact" data-id="${item.id}" aria-label="Remover">×</button></header><h4>${esc(item.title)}</h4><p>${esc(item.reflection)}</p><div>${(item.competencies||[]).map(id=>`<small>${esc(PROJECT_COMPETENCIES.find(value=>value.id===id)?.label||id)}</small>`).join('')}</div><footer>${esc(this.context.moduleRegistry.definition(item.moduleId)?.title||item.moduleId)} · ${new Date(item.createdAt).toLocaleDateString('pt-BR')}</footer></article>`).join('')}</div>`:'<div class="project-empty"><b>Seu portfólio ainda está vazio.</b><p>Registre relatórios, códigos, dados, imagens processadas, protótipos e reflexões produzidos nos laboratórios.</p></div>'}</section></section>`;}
  exhibitionMarkup(state){const exhibition=state.exhibition,theme=EXHIBITION_THEMES.find(item=>item.id===exhibition.theme)||EXHIBITION_THEMES[0],selected=state.portfolio.filter(item=>exhibition.selectedArtifactIds.includes(item.id));return `<section class="exhibition-layout"><div class="exhibition-stage"><canvas id="digital-exhibition-canvas" aria-label="Prévia procedural da exposição digital"></canvas><div class="exhibition-stage-label"><span>${esc(theme.name)}</span><b>${selected.length}/6 peças</b></div></div><aside class="exhibition-controls"><span class="eyebrow">MINIEXPOSIÇÃO DIGITAL</span><h3>Conte uma história com suas evidências</h3><label>Título<input id="exhibition-title" value="${esc(exhibition.title)}" maxlength="100"></label><label>Texto de abertura<textarea id="exhibition-intro" rows="4" maxlength="900">${esc(exhibition.intro)}</textarea></label><label>Tema<select id="exhibition-theme">${EXHIBITION_THEMES.map(item=>`<option value="${item.id}" ${item.id===exhibition.theme?'selected':''}>${esc(item.name)}</option>`).join('')}</select></label><h4>Escolha até seis peças</h4><div class="exhibition-artifact-list">${state.portfolio.length?state.portfolio.map(item=>`<label class="${exhibition.selectedArtifactIds.includes(item.id)?'selected':''}"><input type="checkbox" data-exhibition-artifact="${item.id}" ${exhibition.selectedArtifactIds.includes(item.id)?'checked':''}><span><b>${esc(item.title)}</b><small>${esc(artifactType(item.type))}</small></span></label>`).join(''):'<p>Adicione itens ao portfólio antes de montar a exposição.</p>'}</div><div class="project-actions"><button class="button secondary" data-action="refresh-exhibition">Atualizar prévia</button><button class="button primary" data-action="export-exhibition" ${selected.length<1?'disabled':''}>Exportar exposição HTML</button></div><small class="source-policy">O HTML exportado contém somente textos e dados autorais do estudante. Nenhuma mídia externa é incorporada automaticamente.</small></aside></section>`;}
  startRenderer(){const canvas=this.container.querySelector('#digital-exhibition-canvas');if(!canvas)return;const state=this.state(),theme=EXHIBITION_THEMES.find(item=>item.id===state.exhibition.theme)||EXHIBITION_THEMES[0],artifacts=state.portfolio.filter(item=>state.exhibition.selectedArtifactIds.includes(item.id));this.renderer=new DigitalExhibitionRenderer({canvas,reducedMotion:this.context.settingsStore.get().reducedMotion});this.renderer.start({theme,artifacts,title:state.exhibition.title});}
  rerender(){this.render();}
  handleInput(event){if(event.target.matches('[data-project-note]'))return;if(event.target.id==='exhibition-title'||event.target.id==='exhibition-intro'){this.store.updateExhibition({[event.target.id==='exhibition-title'?'title':'intro']:event.target.value});this.updateRenderer();}}
  handleChange(event){if(event.target.id==='exhibition-theme'){this.store.updateExhibition({theme:event.target.value});this.rerender();return;}if(event.target.matches('[data-exhibition-artifact]')){this.store.toggleExhibitionArtifact(event.target.dataset.exhibitionArtifact);this.rerender();}}
  handleSubmit(event){event.preventDefault();if(event.target.dataset.form==='source-review'){const form=new FormData(event.target),ratings={};SOURCE_RELIABILITY_CRITERIA.forEach(item=>ratings[item.id]=Number(form.get(item.id)||0));const score=this.sourceEngine.score(ratings),result=this.sourceEngine.compareExpected(score,this.engine.source(String(form.get('sourceId')))?.expectedBand);this.store.reviewSource(String(form.get('sourceId')),{ratings,score,...result});this.context.profileStore.addXp(35,`c52-source-${form.get('sourceId')}`);this.context.recordGuidedEvent?.('interaction',{kind:'source-review',score});this.rerender();return;}if(event.target.dataset.form==='portfolio-artifact'){const form=new FormData(event.target),competencies=form.getAll('competencies');this.store.addArtifact({title:String(form.get('title')||'').trim(),type:String(form.get('type')||'reflection'),moduleId:String(form.get('moduleId')||'project-curation-studio'),reflection:String(form.get('reflection')||'').trim(),competencies});this.context.profileStore.addXp(50,'c52-portfolio-artifact');this.context.recordGuidedEvent?.('manual-evidence',{kind:'portfolio-artifact'});this.rerender();}}
  handleClick(event){const target=event.target.closest('[data-action]');if(!target)return;const action=target.dataset.action;if(action==='back'){this.context.onBack();return;}if(action==='open-culture'){this.context.openModule('culture-discovery');return;}if(action==='tab'){this.tab=target.dataset.tab;this.store.visitTab(this.tab);this.rerender();return;}if(action==='select-project'){this.selectedProjectId=target.dataset.id;this.store.selectProject(this.selectedProjectId);this.rerender();return;}if(action==='choose-role'||action==='select-career'){this.selectedCareerId=target.dataset.id;this.store.selectRole(this.selectedCareerId);this.tab='careers';this.rerender();return;}if(action==='toggle-stage'){this.store.toggleStage(this.selectedProjectId,target.dataset.stage);this.context.recordGuidedEvent?.('interaction',{kind:'project-stage',stage:target.dataset.stage});this.rerender();return;}if(action==='save-project-note'){const text=this.container.querySelector(`[data-project-note="${this.selectedProjectId}"]`)?.value||'';this.store.note(this.selectedProjectId,text);this.context.setGuidedEvidence?.(text);this.context.toast('Registro do projeto salvo.');return;}if(action==='add-project-artifact'){const project=this.engine.project(this.selectedProjectId),text=this.container.querySelector(`[data-project-note="${this.selectedProjectId}"]`)?.value||project.summary;this.store.note(this.selectedProjectId,text);this.store.addArtifact({title:project.title,type:'reflection',moduleId:'project-curation-studio',reflection:text,competencies:project.competencies});this.context.profileStore.addXp(50,`c52-project-${project.id}`);this.tab='portfolio';this.rerender();return;}if(action==='open-module'){this.context.recordGuidedEvent?.('interaction',{kind:'project-related-lab',moduleId:target.dataset.module});this.context.openModule(target.dataset.module);return;}if(action==='career-choice'){const result=this.engine.careerDecision(this.selectedCareerId,target.dataset.choice);if(result){this.store.decideCareer(this.selectedCareerId,result);this.context.profileStore.addXp(result.score===3?45:20,`c52-career-${this.selectedCareerId}`);this.context.recordGuidedEvent?.('interaction',{kind:'career-decision',score:result.score});this.rerender();}return;}if(action==='select-source'){this.selectedSourceId=target.dataset.id;this.rerender();return;}if(action==='remove-artifact'){this.store.removeArtifact(target.dataset.id);this.rerender();return;}if(action==='export-portfolio'){this.exportPortfolio();return;}if(action==='refresh-exhibition'){this.rerender();return;}if(action==='export-exhibition'){this.exportExhibition();return;}if(action==='export-evidence'){this.exportEvidence();return;}}
  updateRenderer(){if(!this.renderer)return;const state=this.state(),theme=EXHIBITION_THEMES.find(item=>item.id===state.exhibition.theme)||EXHIBITION_THEMES[0],artifacts=state.portfolio.filter(item=>state.exhibition.selectedArtifactIds.includes(item.id));this.renderer.update({theme,artifacts,title:state.exhibition.title});}
  exportPortfolio(){const state=this.state(),profile=this.context.profileStore.active(),payload={schema:'cosmos-ds-student-portfolio-v1',createdAt:new Date().toISOString(),profile:{name:profile.name,className:profile.className,callsign:profile.callsign},items:state.portfolio};download(`cosmos-portfolio-${profile.callsign||'aluno'}.json`,JSON.stringify(payload,null,2));this.store.exported();this.context.toast('Portfólio exportado.');}
  exportExhibition(){const state=this.state(),theme=EXHIBITION_THEMES.find(item=>item.id===state.exhibition.theme)||EXHIBITION_THEMES[0],items=state.portfolio.filter(item=>state.exhibition.selectedArtifactIds.includes(item.id)),profile=this.context.profileStore.active();const cards=items.map(item=>`<article><small>${esc(artifactType(item.type))}</small><h2>${esc(item.title)}</h2><p>${esc(item.reflection)}</p><footer>${(item.competencies||[]).map(id=>esc(PROJECT_COMPETENCIES.find(value=>value.id===id)?.label||id)).join(' · ')}</footer></article>`).join('');const html=`<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>${esc(state.exhibition.title)}</title><style>body{margin:0;padding:40px;font:16px system-ui;color:#eff7ff;background:${theme.background}}header{max-width:900px;margin:auto;text-align:center}header span,article small{color:${theme.accent};letter-spacing:.1em;text-transform:uppercase}main{max-width:1100px;margin:32px auto;display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:16px}article{padding:22px;border:1px solid ${theme.accent}66;border-radius:18px;background:#ffffff0a}p{line-height:1.6;color:#b8c7d8}footer{color:#8ea3b9;font-size:.8rem}@media(max-width:600px){body{padding:18px}}</style></head><body><header><span>COSMOS DS · Exposição digital do estudante</span><h1>${esc(state.exhibition.title)}</h1><p>${esc(state.exhibition.intro)}</p><b>${esc(profile.name)} · ${esc(profile.className)}</b></header><main>${cards}</main></body></html>`;download(`cosmos-exposicao-${profile.callsign||'aluno'}.html`,html,'text/html');this.store.exported();this.context.profileStore.addXp(100,'c52-digital-exhibition');this.context.recordGuidedEvent?.('evidence-exported',{moduleId:'project-curation-studio',kind:'digital-exhibition'});this.context.toast('Exposição HTML exportada.');}
  exportEvidence(){const state=this.state(),profile=this.context.profileStore.active(),completion=this.engine.completion(state),payload={schema:'cosmos-ds-project-curation-evidence-v1',createdAt:new Date().toISOString(),profile:{id:profile.id,name:profile.name,className:profile.className,callsign:profile.callsign},activeProject:this.engine.project(state.activeProjectId),activeRole:this.engine.career(state.activeRoleId),completion,projectStages:state.projectStages,projectNotes:state.projectNotes,careerDecisions:state.careerDecisions,sourceReviews:state.sourceReviews,portfolio:state.portfolio,exhibition:state.exhibition,goals:PROJECT_CURATION_GOALS.map(goal=>({id:goal.id,label:goal.label,completed:this.goalCompleted(goal.id,state,completion)})),notice:'Casos de fontes e profissões são simulações didáticas locais. O estudante deve consultar e citar fontes originais em pesquisas reais.'};download(`cosmos-projetos-${profile.callsign||'aluno'}.json`,JSON.stringify(payload,null,2));this.store.exported();this.context.profileStore.addXp(120,'c52-project-evidence');this.context.recordGuidedEvent?.('evidence-exported',{moduleId:'project-curation-studio'});this.context.toast('Evidência interdisciplinar exportada.');}
  goalCompleted(id,state,completion){if(id==='choose-project')return Boolean(state.activeProjectId);if(id==='career-simulation')return completion.career>=1;if(id==='review-sources')return completion.sourceReviews>=3;if(id==='portfolio')return completion.portfolio>=3;if(id==='exhibition')return completion.exhibition>=3;if(id==='export')return state.exports>=1;return false;}
}
export function createModule(){return new ProjectCurationStudioModule();}
