'use strict';
(function(){
  window.LABDS_LABS=window.LABDS_LABS||{};
  const KEY='lab.communication.state';
  const DEFAULT={tab:'email',xp:0,messages:[]};
  let root,ctx,state,timer=0;
  async function save(){await ctx.storage.set(KEY,state);}
  function setTab(tab){state.tab=tab;root.querySelectorAll('[data-com-tab]').forEach(b=>b.classList.toggle('active',b.dataset.comTab===tab));root.querySelectorAll('[data-com-panel]').forEach(p=>p.classList.toggle('hidden',p.dataset.comPanel!==tab));save();}
  function animate(nodes,log,lines,done){clearTimeout(timer);nodes.forEach(n=>n.classList.remove('active'));let i=0;log.textContent='';const next=()=>{if(i>0)nodes[i-1]?.classList.remove('active');if(i>=nodes.length){done?.();return;}nodes[i].classList.add('active');log.textContent+=`${lines[i]}\n`;i++;timer=setTimeout(next,650);};next();}
  function validEmail(value){return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value);}
  function sendEmail(){const to=root.querySelector('#mailTo').value.trim(),subject=root.querySelector('#mailSubject').value.trim(),body=root.querySelector('#mailBody').value.trim(),feedback=root.querySelector('#mailFeedback');if(!validEmail(to)||subject.length<3||body.length<8){feedback.className='practice-feedback error';feedback.textContent='Revise destinatário, assunto e mensagem. Um e-mail profissional precisa de contexto suficiente.';return;}const suspicious=/senha|urgente|clique aqui|pix|premio|prêmio/i.test(subject+' '+body);const nodes=[...root.querySelectorAll('#mailFlow .flow-node')],log=root.querySelector('#mailLog');feedback.className='practice-feedback';feedback.textContent='Enviando pelo laboratório…';animate(nodes,log,['1. O cliente organiza cabeçalhos e corpo MIME.','2. O DNS encontra o servidor MX do domínio.','3. O cliente entrega a mensagem ao servidor SMTP.','4. O canal TLS protege o transporte entre servidores.','5. O servidor de destino aplica filtros e entrega na caixa postal.'],()=>{state.xp+=suspicious?10:25;state.messages.push({to,subject,at:Date.now(),suspicious});root.querySelector('#comXp').textContent=state.xp;feedback.className=`practice-feedback ${suspicious?'error':'success'}`;feedback.textContent=suspicious?'Mensagem entregue, mas o filtro marcou sinais de risco. Reveja urgência, pedido de senha ou promessa de prêmio.':'Mensagem entregue na simulação. Cabeçalhos, DNS, SMTP e TLS foram processados.';save();ctx.logEvent({eventType:'communication',action:'E-mail simulado',status:'success',details:{suspicious}});});}
  async function encryptMessage(){const text=root.querySelector('#chatText').value.trim(),out=root.querySelector('#cryptoOutput');if(!text){out.textContent='Digite uma mensagem fictícia.';return;}const key=await crypto.subtle.generateKey({name:'AES-GCM',length:256},true,['encrypt','decrypt']),iv=crypto.getRandomValues(new Uint8Array(12)),data=new TextEncoder().encode(text),cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,data),raw=await crypto.subtle.exportKey('raw',key),hex=a=>[...new Uint8Array(a)].map(b=>b.toString(16).padStart(2,'0')).join('');out.textContent=`Mensagem original: ${text}\n\nChave efêmera: ${hex(raw).slice(0,32)}…\nIV: ${hex(iv)}\nTexto cifrado: ${hex(cipher).slice(0,120)}…\n\nNa comunicação ponta a ponta real, o gerenciamento de chaves é muito mais complexo.`;state.xp+=20;root.querySelector('#comXp').textContent=state.xp;save();}
  function inspectHeader(){const raw=root.querySelector('#headerInput').value,out=root.querySelector('#headerOutput');const lines=raw.split(/\r?\n/).map(x=>x.trim()).filter(Boolean),map={};for(const line of lines){const index=line.indexOf(':');if(index>0)map[line.slice(0,index).toLowerCase()]=line.slice(index+1).trim();}const notes=[];notes.push(map.from&&validEmail(map.from)?'From: formato válido.':'From: ausente ou inválido.');notes.push(map.to&&validEmail(map.to)?'To: formato válido.':'To: ausente ou inválido.');notes.push(map.subject?.length>2?'Subject: presente.':'Subject: ausente ou muito curto.');notes.push(map['reply-to']&&map['reply-to']!==map.from?'Atenção: Reply-To diferente do remetente.':'Reply-To coerente ou ausente.');out.textContent=notes.join('\n');}
  function render(){root.innerHTML=`<div class="immersive-lab communication-lab"><header class="immersive-hero"><div><span class="eyebrow">COMUNICAÇÃO DIGITAL</span><h2>Como mensagens atravessam a internet</h2><p>Simule e-mail, servidores, DNS, SMTP, TLS, cabeçalhos e criptografia ponta a ponta sem enviar nada para fora do navegador.</p></div><div class="immersive-badges"><span>XP <b id="comXp">${state.xp}</b></span><span>Rede simulada</span><span>Criptografia local</span></div></header><nav class="module-tabs"><button data-com-tab="email">E-mail</button><button data-com-tab="chat">Mensagens seguras</button><button data-com-tab="headers">Cabeçalhos</button><button data-com-tab="servers">Servidores</button></nav>
    <section data-com-panel="email" class="immersive-grid"><article class="immersive-card"><h3>Redigir e-mail profissional</h3><label>Para<input id="mailTo" value="suporte@empresa.local"></label><label>Assunto<input id="mailSubject" value="Solicitação de acesso ao sistema"></label><label>Mensagem<textarea id="mailBody" rows="7">Olá, equipe de suporte. Preciso de acesso ao ambiente de testes para concluir a atividade. Poderiam orientar os próximos passos? Obrigado.</textarea></label><button id="sendMail" class="btn primary">Enviar na simulação</button><div id="mailFeedback" class="practice-feedback"></div></article><article class="immersive-card"><h3>Caminho da mensagem</h3><div id="mailFlow" class="flow-track"><div class="flow-node">Cliente<br><small>MIME</small></div><span class="flow-arrow">›</span><div class="flow-node">DNS<br><small>registro MX</small></div><span class="flow-arrow">›</span><div class="flow-node">SMTP<br><small>envio</small></div><span class="flow-arrow">›</span><div class="flow-node">TLS<br><small>canal</small></div><span class="flow-arrow">›</span><div class="flow-node">Destino<br><small>caixa postal</small></div></div><pre id="mailLog" class="terminal-mini">Pronto para enviar.</pre></article></section>
    <section data-com-panel="chat" class="immersive-grid hidden"><article class="immersive-card"><h3>Criptografia local demonstrativa</h3><label>Mensagem fictícia<textarea id="chatText" rows="5">Encontro de equipe às 14h no laboratório.</textarea></label><button id="encryptMessage" class="btn primary">Criptografar com AES-GCM</button><p class="muted-copy">O exemplo usa criptografia real do navegador, mas não implementa o protocolo completo de um aplicativo de mensagens.</p></article><article class="immersive-card"><h3>O que viaja pela rede?</h3><pre id="cryptoOutput" class="terminal-mini">A saída cifrada aparecerá aqui.</pre><div class="flow-track"><div class="flow-node">Chave local</div><span class="flow-arrow">›</span><div class="flow-node">Cifra</div><span class="flow-arrow">›</span><div class="flow-node">Rede</div><span class="flow-arrow">›</span><div class="flow-node">Decifra</div></div></article></section>
    <section data-com-panel="headers" class="immersive-grid hidden"><article class="immersive-card"><h3>Analise cabeçalhos</h3><textarea id="headerInput" rows="10">From: financeiro@empresa.local\nTo: aluno@escola.local\nSubject: Relatório mensal\nReply-To: financeiro@empresa.local\nDate: Mon, 27 Jul 2026 10:20:00 -0300</textarea><button id="inspectHeader" class="btn primary">Analisar</button></article><article class="immersive-card"><h3>Resultado</h3><pre id="headerOutput" class="terminal-mini">Clique em analisar.</pre><div class="knowledge-card"><strong>Cabeçalhos ajudam a investigar:</strong> origem declarada, destinatário, caminho por servidores, autenticação e divergências suspeitas.</div></article></section>
    <section data-com-panel="servers" class="immersive-grid hidden"><article class="immersive-card"><h3>Protocolos principais</h3><div class="protocol-grid"><button><b>SMTP</b><span>envio entre clientes e servidores</span><small>25 / 465 / 587</small></button><button><b>IMAP</b><span>sincroniza pastas e mensagens</span><small>143 / 993</small></button><button><b>POP3</b><span>baixa mensagens para o cliente</span><small>110 / 995</small></button><button><b>DNS MX</b><span>indica o servidor do domínio</span><small>porta DNS 53</small></button></div></article><article class="immersive-card"><h3>Exemplo de arquitetura</h3><div class="server-rack"><div>Cliente web</div><i></i><div>Gateway</div><i></i><div>Servidor SMTP</div><i></i><div>Armazenamento</div></div></article></section></div>`;
    root.querySelectorAll('[data-com-tab]').forEach(b=>b.addEventListener('click',()=>setTab(b.dataset.comTab)));root.querySelector('#sendMail').addEventListener('click',sendEmail);root.querySelector('#encryptMessage').addEventListener('click',encryptMessage);root.querySelector('#inspectHeader').addEventListener('click',inspectHeader);setTab(state.tab);
  }
  async function mount(host,context){root=host;ctx=context;state={...DEFAULT,...await ctx.storage.get(KEY,DEFAULT)};render();}
  async function unmount(){clearTimeout(timer);await save();root=null;ctx=null;state=null;}
  function exportPayload(){return{text:`COMUNICAÇÃO DIGITAL\nMensagens simuladas: ${state.messages.length}\nXP: ${state.xp}`,native:JSON.stringify(state,null,2),backup:state,meta:[{label:'Mensagens',value:String(state.messages.length)},{label:'XP',value:String(state.xp)}]};}
  function help(){return'<h3>Comunicação digital</h3><p>O laboratório não envia e-mails nem mensagens reais. Ele demonstra fluxos de DNS, SMTP, TLS, cabeçalhos e criptografia local.</p>';}
  window.LABDS_LABS['communication-lab']={mount,unmount,exportPayload,help};
})();
